### ISSUE TITLE
issue with ClusterRole of kube-state-metrics

### ISSUE THREAD

**Issue by s0rc3r3r01** [coreos/prometheus-operator#1008]
**What did you do?**
Deploy prometheus operator in cluster with RBAC enabled
**What did you expect to see?**
No RBAC exceptions
**What did you see instead? Under which circumstances?**
Logs on apiserevr : 
`I0222 12:22:24.280453       5 rbac.go:114] RBAC DENY: user "system:serviceaccount:monitoring:kube-state-metrics" groups ["system:serviceaccounts" "system:serviceaccounts:monitoring" "system:authenticated"] cannot "list" resource "persistentvolumeclaims" cluster-wide
I0222 12:22:24.280531       5 rbac.go:114] RBAC DENY: user "system:serviceaccount:monitoring:kube-state-metrics" groups ["system:serviceaccounts" "system:serviceaccounts:monitoring" "system:authenticated"] cannot "list" resource "limitranges" cluster-wide
I0222 12:22:24.281267       5 rbac.go:114] RBAC DENY: user "system:serviceaccount:monitoring:kube-state-metrics" groups ["system:serviceaccounts" "system:serviceaccounts:monitoring" "system:authenticated"] cannot "list" resource "statefulsets.apps" cluster-wide
I0222 12:22:24.281938       5 rbac.go:114] RBAC DENY: user "system:serviceaccount:monitoring:kube-state-metrics" groups ["system:serviceaccounts" "system:serviceaccounts:monitoring" "system:authenticated"] cannot "list" resource "replicationcontrollers" cluster-wide
I0222 12:22:24.282177       5 rbac.go:114] RBAC DENY: user "system:serviceaccount:monitoring:kube-state-metrics" groups ["system:serviceaccounts" "system:serviceaccounts:monitoring" "system:authenticated"] cannot "list" resource "services" cluster-wide
I0222 12:22:24.589083       5 rbac.go:114] RBAC DENY: user "system:serviceaccount:monitoring:kube-state-metrics" groups ["system:serviceaccounts" "system:serviceaccounts:monitoring" "system:authenticated"] cannot "list" resource "cronjobs.batch" cluster-wide`
**Environment**
* Kubernetes version information:

`kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.10", GitCommit:"bebdeb749f1fa3da9e1312c4b08e439c404b3136", GitTreeState:"clean", BuildDate:"2017-11-03T17:13:44Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.12+coreos.0", GitCommit:"dc657bc96218ea0db2ca931022e282f39cf5064c", GitTreeState:"clean", BuildDate:"2018-01-17T19:36:25Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
* Kubernetes cluster kind: 
self-hosted

* Manifests:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kube-state-metrics
rules:
- apiGroups: [""]
  resources:
  - nodes
  - pods
  - resourcequotas
  verbs: ["list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  verbs: ["list", "watch"]
```

* Prometheus Operator Logs:

```
Applying kube-state-metrics yaml
```
