### ISSUE TITLE
Cross namespace monitoring problem

### ISSUE THREAD

**Issue by ralberto** [coreos/prometheus-operator#1013]
**What did you do?**
Deployed prometheus operator and a prometheus instance in a namespace called "monitoring". Once pods were running, I've deployed a ServiceMonitor to monitor a service running in another namespace.

```json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myservice-api
  labels:
    k8s-app: myservice-api
spec:
  jobLabel: k8s-myservice
  selector:
    matchLabels:
      app: myservice
  namespaceSelector:
    matchNames:
    - myservicenamespace
  endpoints:
  - port: http
    scheme: http
    interval: 5s
```

**What did you expect to see?**
Service "myservice-api" being monitored by prometheus.

**What did you see instead? Under which circumstances?**
Service "myservice-api" is not monitored because the generated configuration on prometheus.yaml is filtering on namespace "monitoring" and not on namespace "myservicenamespace".
```
...
- job_name: monitoring/alertmanager/0
  honor_labels: false           
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:                     
      names:             
      - monitoring
...
```
If I change the ServiceMonitor to include more namespaces, ex:
```
...
  namespaceSelector:
    matchNames:
    - myservicenamespace
    - monitoring
  endpoints:
...
```
then the generated configuration includes both namespaces.
```
...
- job_name: monitoring/alertmanager/0
  honor_labels: false           
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:                     
      names:
      - myservicenamespace
      - monitoring
...
```
**Environment**
prometheus-operator: 0.17.0

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

Using Kismatic

* Manifests:

```
See above
```
