### ISSUE TITLE
Monitoring custom services: no metrics

### ISSUE THREAD

**Issue by ScottBrenner** [coreos/prometheus-operator#1017]
**What did you do?**

Have a pod exposing metrics in Prometheus-friendly format on port 9103, followed [the example on monitoring custom services](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#monitoring-custom-services) but the second Prometheus that is deployed does not have metrics from the custom service.

**What did you expect to see?**

Metrics from my custom service in Prometheus

**Environment**

* Kubernetes version information:

	`Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5-gke.0", GitCommit:"2c2a807131fa8708abc92f3513fe167126c8cce5", GitTreeState:"clean", BuildDate:"2017-12-19T20:05:45Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind: 

	Monitoring GKE 1.8.5 with kube-prometheus.

* Manifests:

Copied, modified, and deployed from the example linked above. 

prometheus-hana-svc.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: prometheus-hana
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30100
    port: 9103
    protocol: TCP
    targetPort: 9090
  selector:
    prometheus: hana
```

prometheus-hana.yaml
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: hana
  namespace: monitoring
  labels:
    prometheus: hana
spec:
  version: v2.2.0-rc.0
  serviceMonitorSelector:
    matchLabels:
      tier: hana-metrics-collector
  resources:
    requests:
      # 2Gi is default, but won't schedule if you don't have a node with >2Gi
      # memory. Modify based on your target and time-series count for
      # production use. This value is mainly meant for demonstration/testing
      # purposes.
      memory: 400Mi
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-main
      port: 9093
```
servicemonitor-hana.yaml
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hana
  labels:
    tier: hana-metrics-collector
spec:
  selector:
     matchLabels:
       tier: hana-metrics-collector
  endpoints:
  - port: 9103
    interval: 10s
```

Part of custom service manifest
```
kind: Deployment
metadata:
  labels:
    app: hana
    component: metrics-collector
  name: hana-metrics-collector
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hana
        component: metrics-collector
...
---
apiVersion: v1
kind: Service
metadata:
  name: hana-metrics-collector
  labels:
    app: hana
    component: metrics-collector
    tier: hana-metrics-collector
  namespace: monitoring
spec:
  ports:
  - port: 9103
    name: prometheus
  selector:
    app: hana
    component: metrics-collector
```
The service discovery page on my main Prometheus now has a section for my custom service, although all "discovered labels" for it are "dropped". Any tips?
