### ISSUE TITLE
Support for ReadOnlyRootFilesystem

### ISSUE THREAD

**Issue by tourea** [coreos/prometheus-operator#1024]
## Feature Request
In general it a good practice to enable SecurityContext.readOnlyRootFilesystem on pods in order reduces security attack vectors since the container instance's filesystem cannot be tampered with or written to unless it has explicit read-write permissions on its filesystem folder and directories.
Currently, only `FSGroup, RunAsNonRoot, RunAsUser` are supported by `v1.PodSecurityContext` (see pkg/prometheus/statefulset.go).

It would nice to add such a support.

**Comment by brancz** [comment]
This is definitely something we should do. Would you like to create a PR to add this? :slightly_smiling_face:

**Comment by lorenzo-biava** [comment]
@brancz Any plans to get this feature in the roadmap? The container SecurityContext would be very useful from a security standpoint.

**Comment by lorenzo-biava** [comment]
Looks like this is actually available via the `containers` override field in `PrometheusSpec`, `AlertmanagerSpec`, etc.
@brancz I guess the issue can be closed.

E.g. via Helm:
```
prometheusSpec:
  containers:
  - name: prometheus
    securityContext:
      readOnlyRootFilesystem: true
  - name: config-reloader
    securityContext:
      readOnlyRootFilesystem: true
  - name: thanos-sidecar
    securityContext:
      readOnlyRootFilesystem: true
```
