### ISSUE TITLE
Alertmanager source url not use Prometheus external url

### ISSUE THREAD

**Issue by sebglon** [coreos/prometheus-operator#1083]
**What did you do?**
Whit Helm, i use prometheus and alertmanager with inngress and fqdn.

**What did you expect to see?**
Ingress work well with fqdn 
But external url are not valueted with fqdn.
prometheus external url is: http://monitoring-prometheus.monitoring:9090

**What did you see instead? Under which circumstances?**
Is it normal?
Is it possible to populate prometheus external Url with your fqdn?
 
**Environment**
GCE, Helm,

Prometheus valuues:
```
prometheus:
  externalLabels:
    project: ${project}
    cluster: ${cluster}
ingress:
    annotations:
      nginx.ingress.kubernetes.io/auth-signin: https://${auth_fqdn}/oauth2/start
      nginx.ingress.kubernetes.io/auth-url: https://${auth_fqdn}/oauth2/auth
    fqdn: "${metrics_fqdn}"
    tls: 
      - hosts:
          - ${metrics_fqdn}    
```
