### ISSUE TITLE
grafana pod crashing due to persistent volume

### ISSUE THREAD

**Issue by shavo007** [coreos/prometheus-operator#1089]
**What did you do?**
Install helm charts

**What did you expect to see?**
Grafana up and running with persistence

**What did you see instead? Under which circumstances?**
```

Unable to mount volumes for pod "grafana-grafana-5554887f4d-k2bxd_monitoring(b184d337-27ec-11e8-91bd-06223c5ed442)": timeout expired waiting for volumes to attach/mount for pod "monitoring"/"grafana-grafana-5554887f4d-k2bxd". list of unattached/unmounted volumes=[grafana-storage]
Error syncing pod

```

**Environment**
Kops 1.8 on aws

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

```

* Kubernetes cluster kind: 

	 kops, 

* Manifests:

```
storageSpec: 
   class: default
   accessMode: ReadWriteOnce
   resources:
     requests:
       storage: 2Gi

```

* Prometheus Operator Logs:

I see the volume is dynamically created with the claim is bound.

Even when i delete the pod and automatically recreates, the pod still crashes.

**Comment by gianrubio** [comment]
Maybe the storageSpec example in grafana are outdated, could you try to use [the same notation](https://github.com/coreos/prometheus-operator/blob/master/helm/prometheus/values.yaml#L280-L288) that we use in prometheus?

**Comment by shavo007** [comment]
changed but fails validation:

```executing "grafana/templates/pvc.yaml" at <.Values.storageSpec....>: can't evaluate field requests in type interface {}
```

```
storageSpec:
  volumeClaimTemplate:
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
```

The format is different for grafana https://github.com/coreos/prometheus-operator/blob/master/helm/grafana/values.yaml#L70

**Comment by gianrubio** [comment]
I successfully created a grafana pod using the storageSpec below, in a k8s created by kops.  The first timeout error is related to something in your infrasctucture  and not in the grafana pod. Did you try to  create a storage in other deployments or you have the same error?

```
storageSpec:
   class: default
   accessMode: ReadWriteOnce
   resources:
     requests:
       storage: 2Gi
```
