### ISSUE TITLE
Alert rule configmap example in Documentation/user-guides/alerting.md has incorrect label selector for role

### ISSUE THREAD

**Issue by Chehai** [coreos/prometheus-operator#1102]
**What did you do?**
I set up an alert rule configmap using the example in Documentation/user-guides/alerting.md
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-example-rules
  labels:
    role: prometheus-rulefiles
    prometheus: example
data:
  example.rules.yaml: |+
    groups:
    - name: ./example.rules
      rules:
      - alert: ExampleAlert
        expr: vector(1)
```

**What did you expect to see?**

I expected to see ExampleAlert shows up in alertmanager.
 
**What did you see instead? Under which circumstances?**

No alerts were generated.

**Environment**

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

kubeadm

**Solution**
Change label selector for role to be `alert-rules`.  For example:
```yaml
  labels:
    role: alert-rules
```
Helm chart got it right: https://github.com/coreos/prometheus-operator/blob/master/helm/kube-prometheus/templates/configmap.yaml#L10
