### ISSUE TITLE
Support for monitoring external HTTPs targets

### ISSUE THREAD

**Issue by optiomas** [coreos/prometheus-operator#1114]
**What did you do?**

In order to monitor a service external to the cluster, I followed your example at https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/Monitoring%20external%20etcd.md.

**What did you expect to see?**

A successfully scraped target.

**What did you see instead? Under which circumstances?**

Prometheus reports the target returns a 404. The reason for this is that setting the `tlsConfig.serverName` doesn't set a `Host` header in the [Prometheus HTTP Client](https://github.com/prometheus/prometheus/blob/master/util/httputil/client.go#L173).

Since the endpoint is explicitly defined as an IP address, and the target is only exposed over HTTPs, the Host header needs to be set.

Alternatively, the `ServiceMonitor` could be changed to support `Services` of the type `externalName`: https://akomljen.com/kubernetes-tips-part-1/

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.7+coreos.0", GitCommit:"768e049ab5230010251f30475e0e785e2e999566", GitTreeState:"clean", BuildDate:"2018-01-18T00:17:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

tectonic-installer

* Manifests:

```
kind: Endpoints
apiVersion: v1
metadata:
  labels:
    app: jira
  name: jira
  namespace: production
subsets:
  - addresses:
    - ip: ELIDED
    ports:
    - name: https
      protocol: TCP
      port: 443
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: jira
  name: jira
  namespace: production
spec:
  jobLabel: app
  endpoints:
    - port: https
      interval: 30s
      path: /plugins/servlet/prometheus/metrics
      scheme: https
      params:
        token: [ELIDED]
      tlsConfig:
        serverName: "ELIDED"
  namespaceSelector:
    matchNames:
      - production
  selector:
    matchLabels:
      app: jira
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jira
  name: jira
  namespace: production
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: https
    protocol: TCP
    port: 443
```
