### ISSUE TITLE
StorageSpec for prometheus's persistent volume is not picked up by prometheus-operator

### ISSUE THREAD

**Issue by MIllgner** [coreos/prometheus-operator#1121]
**What did you do?**
I tried to configure prometheus-operator's value file to get a PVC/PV instead of an emptyDir{}. I did it with following commands:

helm upgrade -i prometheus-operator coreos/prometheus-operator  --namespace monitoring
helm upgrade -i kube-prometheus coreos/kube-prometheus  --namespace monitoring -f values.yaml

**What did you expect to see?**

I expected to get a PVC and a PV and a kube-prometheus pod which is picking up this volume. The value file contains:
```
storageSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: ibmc-file-gold
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 50Gi
      selector:
        matchLabels:
          app: prometheus
```

**What did you see instead? Under which circumstances?**

I got a failure during deployment:
```
Error: UPGRADE FAILED: Prometheus.monitoring.coreos.com "kube-prometheus" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"...
spec.storage.class in body is required
spec.storage.selector in body is required
spec.storage.resources in body is required
```
Then I added the requested values in the values.yaml file and deployed:
```
storageSpec:
    class: ""
    selector:
      matchLabels:
        app: prometheus
    resources: {}
    volumeClaimTemplate:
      spec:
        storageClassName: ibmc-file-gold
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 50Gi
      selector:
        matchLabels:
          app: prometheus
```
With this configuration the error message went away ... BUT

There is no change for kube-prometheus POD. It still has the emptyDir as data volume.
And in addition no PVC / PV is created.

**Environment**

* Kubernetes version information:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:29:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.3-2+0b1ffe38401940", GitCommit:"0b1ffe38401940a979b81c581f6774888c1ead7f", GitTreeState:"clean", BuildDate:"2018-03-14T08:29:35Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
