### ISSUE TITLE
Add Grafana TPR

### ISSUE THREAD

**Issue by brancz** [coreos/prometheus-operator#115]
With Prometheus deployments becoming more dynamic, we need to catch up with deploying Grafana, its dashboards and datasources in a similarly dynamic and easy way.

@alexsomesan @fabxc 

Goes with the discussion in #14 and #98 .

**Comment by brancz** [comment]
Grafana will likely need a sidecar to handle the selection and reloading of ConfigMaps just like the recently introduced Prometheus config reloader. As Grafana json dashboards are quite large they will quickly (and reportedly already have) grow larger than the 1mb size limit of a single ConfigMap.

**Comment by fabxc** [comment]
We can probably generalise that sidecar as it should be roughly the same, right?

Wondering whether there's a meaningful way to also generalise the idea of dashboard definitions and data sources. But probably a bit pre-mature as there's unfortunately no Grafana alternative in sight more tailored to our idea of how things should be done.

**Comment by brancz** [comment]
There is definitely a lot of overlap so I think the common part we can generalize away in a package and share among the projects.

Yes I'm also still uncertain how to handle data sources.

I'm currently imagining the Grafana TPR to look something like this:

```
apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "Grafana"
metadata:
  name: "main"
  labels:
    grafana: "main"
spec:
  replicas: 2
  version: v4.1.1
  serviceAccountName: grafana
  dashboardSelector:
    matchLabels:
    - grafana: true
  datasources:
  - name: prometheus
    type: prometheus
    url: http://prometheus.monitoring.svc:9090/
  resources:
    requests:
      memory: 400Mi
```

As the concept of how datasources work in grafana are very specific, it might be fine to have tight coupling of the datasources and grafana itself like that.
