### ISSUE TITLE
Defining storage in kube-prometheus

### ISSUE THREAD

**Issue by deboshrestha** [coreos/prometheus-operator#1159]
**What did you do?**
We are using [this](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus) to use Prometheus in our Kubernetes cluster. The deployment method we are using is as follows - 

``` 
 export KUBECONFIG=<path> # defaults to "~/.kube/config" 
 cd contrib/kube-prometheus/
 hack/cluster-monitoring/deploy
```
The next step we are trying is set up a PV and PVC for storage of the metrics collected by Prometheus. 
We are using Flexvolume here defining the PV and PVC .

Also, we are changing the kube-prometheus/manifests/prometheus-operator/prometheus-operator.yaml to use the flexvolume for storage.

**What did you expect to see?**
I expect to see the PVC being bound to the operator and some data in the volume that is mounted using flexvolume.

**What did you see instead? Under which circumstances?**

When I create a PV, PVC and do a `hack/cluster-monitoring/deploy` I do see the prometheus-operator pod being created and using the specified PVC, 
```Volumes:
  prometheus-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  prometheus-data-pvc
    ReadOnly:   false
  prometheus-operator-token-sp0q3:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-operator-token-sp0q3
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  prometheus-node=1
Tolerations:     <none>
Events:
  Type    Reason                 Age   From                  Message
  ----    ------                 ----  ----                  -------
  Normal  Scheduled              29m   default-scheduler     Successfully assigned prometheus-operator-1542233190-9fl4w to sre-k8s-4-1
  Normal  SuccessfulMountVolume  29m   kubelet, sre-k8s-4-1  MountVolume.SetUp succeeded for volume "prometheus-operator-token-sp0q3"
  Normal  SuccessfulMountVolume  29m   kubelet, sre-k8s-4-1  MountVolume.SetUp succeeded for volume "data"
  Normal  Pulled                 29m   kubelet, sre-k8s-4-1  Container image "quay.io/coreos/prometheus-operator:v0.17.0" already present on machine
  Normal  Created                29m   kubelet, sre-k8s-4-1  Created container
  Normal  Started                29m   kubelet, sre-k8s-4-1  Started container
```

But I don't see any data inside the mounted volume.
That makes me wonder if I am specifying storage the wrong way and not the way it is intended to be used.

**Environment**

* Kubernetes version information:

	insert output of `kubectl version` here
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T20:00:41Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5+coreos.0", GitCommit:"070d238cd2ec359928548e486a9171b498573181", GitTreeState:"clean", BuildDate:"2017-08-31T21:28:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
	Its created using kubespray. And the nodes are nova VMs.

* Manifests:
_PV_
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: data
  labels:
    lvm-volume: prometheus
    prometheus-node: "1"
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "wrigley/lvm"
    fsType: "ext4"
    options:
      volumeID: "data"
      size: "5g"
      volumegroup: "flexvolume-prometheus"
```

_PVC_

```---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "prometheus-data-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      lvm-volume: prometheus
      prometheus-node: "1"
```
_prometheus-operator.yaml_
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
    spec:
      nodeSelector:
        prometheus-node: "1"
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        image: quay.io/coreos/prometheus-operator:v0.17.0
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
        - name: prometheus-data
          mountPath: /prometheus
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator
      volumes:
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-data-pvc
```

I have the following questions - 
1. Am I using the storage volume specification in the right place?
2. There are some values that the prometheus.io docs says to put in place for defining local storage -
 
--storage.tsdb.path: This determines where Prometheus writes its database. Defaults to data/.
--storage.tsdb.retention: This determines when to remove old data. Defaults to 15d.

Where do these values go?

Any help in this matter will be deeply appreciated.

**Comment by brancz** [comment]
You will want to set the PVC template in the Prometheus object, not the Prometheus Operator deployment object. See the [storage user-guide](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/storage.md).

**Comment by deboshrestha** [comment]
Thanks for responding. Now I have attached the storage portion to the Prometheus object in this manner -

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  labels:
    prometheus: k8s
spec:
  replicas: 1
  version: v2.2.0-rc.1
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpressions:
    - {key: k8s-app, operator: Exists}
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: k8s
  nodeSelector:
    prometheus-node: "1"
  resources:
    requests:
      # 2Gi is default, but won't schedule if you don't have a node with >2Gi
      # memory. Modify based on your target and time-series count for
      # production use. This value is mainly meant for demonstration/testing
      # purposes.
      memory: 400Mi
    retention: 4h
  storage:
    volumeClaimTemplate:
       spec:
         selector:
           matchLabels:
             app: prometheus
         resources:
           requests:
             storage: 4Gi
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-main
      port: web
``` 

And the PV is being created this way -

```
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-data
  labels:
    app: "prometheus"
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "wrigley/lvm"
    fsType: "ext4"
    options:
      volumeID: "prometheus-sre-k8s-4-1"
      size: "4g"
      volumegroup: "flexvolume-sre-k8s-4-1-prometheus"
```

However, still its not attaching to the Prometheus "prometheus-k8s-0" pod , and if I do a describe on it I see the following - 

```
kubectl describe pod prometheus-k8s-0 -n monitoring
Name:           prometheus-k8s-0
Namespace:      monitoring
Node:           sre-k8s-4-1/172.29.236.217
Start Time:     Mon, 02 Apr 2018 23:31:10 -0400
Labels:         app=prometheus
                controller-revision-hash=prometheus-k8s-547481901
                prometheus=k8s
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"StatefulSet","namespace":"monitoring","name":"prometheus-k8s","uid":"bf839df0-36e9-11e8-b6b3-fa163e895cec"...
Status:         Running
IP:             10.233.84.27
Controlled By:  StatefulSet/prometheus-k8s
Containers:
  prometheus:
    Container ID:  docker://645353d977626d7a89fa63df019e98375d9160226d12803d18e3c9680b31a971
    Image:         quay.io/prometheus/prometheus:v2.2.0-rc.1
    Image ID:      docker-pullable://quay.io/prometheus/prometheus@sha256:7972cd55570d800ab4343e48c5e74dd3c5608e9c4212728206e7de58eb7c7a39
    Port:          9090/TCP
    Args:
      --config.file=/etc/prometheus/config/prometheus.yaml
      --storage.tsdb.path=/var/prometheus/data
      --storage.tsdb.retention=24h
      --web.enable-lifecycle
      --storage.tsdb.no-lockfile
      --web.route-prefix=/
    State:          Running
      Started:      Mon, 02 Apr 2018 23:31:11 -0400
    Ready:          True
    Restart Count:  0
    Requests:
      memory:     400Mi
    Liveness:     http-get http://:web/-/healthy delay=30s timeout=3s period=5s #success=1 #failure=10
    Readiness:    http-get http://:web/-/ready delay=0s timeout=3s period=5s #success=1 #failure=6
    Environment:  <none>
    Mounts:
      /etc/prometheus/config from config (ro)
      /etc/prometheus/rules from rules (ro)
      /var/prometheus/data from prometheus-k8s-db (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-k8s-token-4xs8p (ro)
  prometheus-config-reloader:
    Container ID:  docker://faeb6ff1d148ad0845f5388d693b164d9f0730375ab51d585aa28b4a054a7449
    Image:         quay.io/coreos/prometheus-config-reloader:v0.0.2
    Image ID:      docker-pullable://quay.io/coreos/prometheus-config-reloader@sha256:9ea705b2234f7deea22058a00ea46a303087828bde579b37255a590e8c0f4eca
    Port:          <none>
    Args:
      -reload-url=http://localhost:9090/-/reload
      -config-volume-dir=/etc/prometheus/config
      -rule-volume-dir=/etc/prometheus/rules
    State:          Running
      Started:      Mon, 02 Apr 2018 23:31:11 -0400
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     10m
      memory:  50Mi
    Requests:
      cpu:        10m
      memory:     50Mi
    Environment:  <none>
    Mounts:
      /etc/prometheus/config from config (ro)
      /etc/prometheus/rules from rules (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-k8s-token-4xs8p (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          True
  PodScheduled   True
Volumes:
  config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-k8s
    Optional:    false
  rules:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  prometheus-k8s-db:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  prometheus-k8s-token-4xs8p:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-k8s-token-4xs8p
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  prometheus-node=1
Tolerations:     <none>
Events:
  Type    Reason                 Age   From                  Message
  ----    ------                 ----  ----                  -------
  Normal  Scheduled              12m   default-scheduler     Successfully assigned prometheus-k8s-0 to sre-k8s-4-1
  Normal  SuccessfulMountVolume  12m   kubelet, sre-k8s-4-1  MountVolume.SetUp succeeded for volume "prometheus-k8s-db"
  Normal  SuccessfulMountVolume  12m   kubelet, sre-k8s-4-1  MountVolume.SetUp succeeded for volume "rules"
  Normal  SuccessfulMountVolume  12m   kubelet, sre-k8s-4-1  MountVolume.SetUp succeeded for volume "config"
  Normal  SuccessfulMountVolume  12m   kubelet, sre-k8s-4-1  MountVolume.SetUp succeeded for volume "prometheus-k8s-token-4xs8p"
  Normal  Pulled                 12m   kubelet, sre-k8s-4-1  Container image "quay.io/coreos/prometheus-config-reloader:v0.0.2" already present on machine
  Normal  Created                12m   kubelet, sre-k8s-4-1  Created container
  Normal  Started                12m   kubelet, sre-k8s-4-1  Started container
  Normal  Pulled                 12m   kubelet, sre-k8s-4-1  Container image "quay.io/prometheus/prometheus:v2.2.0-rc.1" already present on machine
  Normal  Created                12m   kubelet, sre-k8s-4-1  Created container
  Normal  Started                12m   kubelet, sre-k8s-4-1  Started container
```

As you can see the volumes are still pointing to EmptyDir , and when I read the documentation it seems like that's the default way Pods will pick up storage if there is nothing attached/assigned to them. 
Any idea what's going on here?

**Comment by brancz** [comment]
PVC templates cannot be changed after initial creation, you need to either delete the underlying statefulset or delete and re-create the Prometheus object entirely.

**Comment by deboshrestha** [comment]
I am redeploying it this way - since we are using kube-prometheus -

`hack/cluster-monitoring/teardown`  -- to bring it down. 

Then create the PV only this time and delete the previous PV and PVC. And this way to bring it up -

`hack/cluster-monitoring/deploy`

Shouldn't this re create the underlying statefulset and also the Prometheus object?

**Comment by brancz** [comment]
Yep, you're right, I noticed your volumeClaimTemplate is indented one space too much, maybe that's causing it.

**Comment by deboshrestha** [comment]
Thanks , I will try it out .

**Comment by deboshrestha** [comment]
Its interesting, this time when I recreated the whole thing it actually worked , and when I do a describe on my pod I get the following - 

```
kubectl describe pod prometheus-k8s-0 -n monitoring
Name:           prometheus-k8s-0
Namespace:      monitoring
Node:           sre-k8s-4-1/172.29.236.217
Start Time:     Tue, 03 Apr 2018 10:49:43 -0400
Labels:         app=prometheus
                controller-revision-hash=prometheus-k8s-2014020412
                prometheus=k8s
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"StatefulSet","namespace":"monitoring","name":"prometheus-k8s","uid":"3e5fa900-374e-11e8-baf9-fa163e6eda8d"...
Status:         Running
IP:             10.233.84.29
Controlled By:  StatefulSet/prometheus-k8s
Containers:
  prometheus:
    Container ID:  docker://b0ed0a38102e0329f0dbe476a2c6864aa7d5d68fec752b35d71c4749d1f51151
    Image:         quay.io/prometheus/prometheus:v2.2.0-rc.1
    Image ID:      docker-pullable://quay.io/prometheus/prometheus@sha256:7972cd55570d800ab4343e48c5e74dd3c5608e9c4212728206e7de58eb7c7a39
    Port:          9090/TCP
    Args:
      --config.file=/etc/prometheus/config/prometheus.yaml
      --storage.tsdb.path=/var/prometheus/data
      --storage.tsdb.retention=24h
      --web.enable-lifecycle
      --storage.tsdb.no-lockfile
      --web.route-prefix=/
    State:          Running
      Started:      Tue, 03 Apr 2018 10:49:45 -0400
    Ready:          True
    Restart Count:  0
    Requests:
      memory:     400Mi
    Liveness:     http-get http://:web/-/healthy delay=30s timeout=3s period=5s #success=1 #failure=10
    Readiness:    http-get http://:web/-/ready delay=0s timeout=3s period=5s #success=1 #failure=6
    Environment:  <none>
    Mounts:
      /etc/prometheus/config from config (ro)
      /etc/prometheus/rules from rules (ro)
      /var/prometheus/data from prometheus-k8s-db (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-k8s-token-088t4 (ro)
  prometheus-config-reloader:
    Container ID:  docker://17a4cdae061fea383c58bc168d07e20d41d64541f7f9960d85a00e905d8ba205
    Image:         quay.io/coreos/prometheus-config-reloader:v0.0.2
    Image ID:      docker-pullable://quay.io/coreos/prometheus-config-reloader@sha256:9ea705b2234f7deea22058a00ea46a303087828bde579b37255a590e8c0f4eca
    Port:          <none>
    Args:
      -reload-url=http://localhost:9090/-/reload
      -config-volume-dir=/etc/prometheus/config
      -rule-volume-dir=/etc/prometheus/rules
    State:          Running
      Started:      Tue, 03 Apr 2018 10:49:45 -0400
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     10m
      memory:  50Mi
    Requests:
      cpu:        10m
      memory:     50Mi
    Environment:  <none>
    Mounts:
      /etc/prometheus/config from config (ro)
      /etc/prometheus/rules from rules (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-k8s-token-088t4 (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          True
  PodScheduled   True
Volumes:
  prometheus-k8s-db:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  prometheus-k8s-db-prometheus-k8s-0
    ReadOnly:   false
  config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-k8s
    Optional:    false
  rules:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  prometheus-k8s-token-088t4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-k8s-token-088t4
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  prometheus-node=1
Tolerations:     <none>
Events:
  Type     Reason                 Age                From                  Message
  ----     ------                 ----               ----                  -------
  Warning  FailedScheduling       42m (x2 over 42m)  default-scheduler     PersistentVolumeClaim is not bound: "prometheus-k8s-db-prometheus-k8s-0" (repeated 6 times)
  Normal   Scheduled              42m                default-scheduler     Successfully assigned prometheus-k8s-0 to sre-k8s-4-1
  Normal   SuccessfulMountVolume  42m                kubelet, sre-k8s-4-1  MountVolume.SetUp succeeded for volume "rules"
  Normal   SuccessfulMountVolume  42m                kubelet, sre-k8s-4-1  MountVolume.SetUp succeeded for volume "prometheus-k8s-token-088t4"
  Normal   SuccessfulMountVolume  42m                kubelet, sre-k8s-4-1  MountVolume.SetUp succeeded for volume "config"
  Normal   SuccessfulMountVolume  42m                kubelet, sre-k8s-4-1  MountVolume.SetUp succeeded for volume "prometheus-data"
  Normal   Pulled                 42m                kubelet, sre-k8s-4-1  Container image "quay.io/prometheus/prometheus:v2.2.0-rc.1" already present on machine
  Normal   Created                42m                kubelet, sre-k8s-4-1  Created container
  Normal   Started                42m                kubelet, sre-k8s-4-1  Started container
  Normal   Pulled                 42m                kubelet, sre-k8s-4-1  Container image "quay.io/coreos/prometheus-config-reloader:v0.0.2" already present on machine
  Normal   Created                42m                kubelet, sre-k8s-4-1  Created container
  Normal   Started                42m                kubelet, sre-k8s-4-1  Started container
```

And it seems the volume is finally mounting. yay! 

Also, this is my final PV 
```
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-data
  labels:
    app: "prometheus"
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "wrigley/lvm"
    fsType: "ext4"
    options:
      volumeID: "prometheus-sre-k8s-4-1"
      size: "4g"
      volumegroup: "flexvolume-sre-k8s-4-1-prometheus"
``` 
and prometheus-k8s object -
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  labels:
    prometheus: k8s
spec:
  replicas: 1
  version: v2.2.0-rc.1
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpressions:
    - {key: k8s-app, operator: Exists}
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: k8s
  nodeSelector:
    prometheus-node: "1"
  resources:
    requests:
      # 2Gi is default, but won't schedule if you don't have a node with >2Gi
      # memory. Modify based on your target and time-series count for
      # production use. This value is mainly meant for demonstration/testing
      # purposes.
      memory: 400Mi
    retention: 4h
  storage:
    volumeClaimTemplate:
       spec:
         selector:
           matchLabels:
             app: prometheus
         resources:
           requests:
             storage: 4Gi
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-main
      port: web
```

Thanks for all your help! The next step I will do is see if I can do the original 2 replicas thing  in the spec portion and see how to specify two volumes for them in the Prometheus object. By the way is it even possible to do so?
