### ISSUE TITLE
Bug: sourceLabels should not be required in RelabelConfig

### ISSUE THREAD

**Issue by distol** [coreos/prometheus-operator#1167]
Prometheus Operator v0.17.0, Prometheus v2.2.1.

## Problem
For now, if you try to use `action: labeldrop`, you will get the following error in Prometheus:
```
labeldrop action requires only 'regex', and no other fields"
```

## Service Monitor Example
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  labels:    prometheus: main
spec:
  jobLabel: prometheus-target
  selector:
    matchLabels:
      prometheus-target: node-exporter
  namespaceSelector:
    matchNames:
    - kube-prometheus
  endpoints:
  - port: https
    scheme: https
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      insecureSkipVerify: true
    metricRelabelings:
    - action: labeldrop
      regex: endpoint
      sourceLabels: [] # <- ugly hack, but whithout it operator ignores whole relabeling
```

## Extra info
* `replacement`, that is also required according documention, should also not be required
* According to prometheus docs all fields are optional.
