### ISSUE TITLE
How to use snmp_exporter with prometheus-operator?

### ISSUE THREAD

**Issue by jmreicha** [coreos/prometheus-operator#1177]
**What did you do?**

Attempted to configure the snmp_exporter using the prometheu-operator following instructions from [this issue](https://github.com/coreos/prometheus-operator/issues/256#issuecomment-376696419), borrowing configurations and manifests from [this repo](https://github.com/carlosedp/prometheus-operator-ARM/tree/master/manifests/snmp-exporter).

I created a `service` and `deployment` for the snmp_exporter (all in the same namespace) as mentioned in the other issue, and modified the `ServiceMonitor` to use the configuration posted below.

I double checked that my target IP address and module were correct and snmp_exporter logs look fine.

**What did you expect to see?**

I was the prometheus-operator to pick up the configuration and create a Prometheus configuration for the snmp_exporter.

**What did you see instead? Under which circumstances?**

The prometheus-operator doesn't seem to update the configuration after creating/updating the `ServiceMonitor`.

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

`docker-for-mac 18.03.0-ce-mac58`

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: snmp-exporter
  name: snmp-exporter
spec:
  jobLabel: k8s-app
  selector:
    app: snmp-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - interval: 60s
    port: http-metrics
    params:
      module:
      - default
      target:
      - 1.2.3.4
    path: "/snmp"
    targetPort: 9116
```

* Prometheus Operator Logs:

I don't see any updates when to the operator logs when creating/modifying the `ServiceMonitor`, just the "no configuration change" message.

```
...
ts=2018-04-04T00:18:02.912327Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
ts=2018-04-04T00:18:02.9261971Z caller=operator.go:981 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-04-04T00:18:03.4193776Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
ts=2018-04-04T00:18:03.4455821Z caller=operator.go:981 component=prometheusoperator msg="updating config skipped, no configuration change"
...
```

**Comment by gianrubio** [comment]
Did you deploy prometheus crd using [serviceMonitorSelector](https://github.com/coreos/prometheus-operator/blob/512db0d7920d9bc42163ae2b12e4f7681d5912fb/example/rbac/prometheus/prometheus.yaml#L10-L12)? In that case you should have the same labels in your serviceMonitor.

If it's not the case please share the Prometheus object, services and endpoints.

**Comment by jmreicha** [comment]
@gianrubio I deployed the prometheus-operator using Helm and it looks like it just created a Prometheus crd for `kube-prometheus`, I didn't actually create a Prometheus object only the `ServiceMonitor` that I posted above.

I wonder if that's part of my problem?

**Comment by jmreicha** [comment]
Adding the Prometheus object and tying it to the ServiceMonitor that got me farther, but I'm still not seeing the configuration or the new target in the Prometheus console.

The prometheus-operator logs do indicate that the the configurations get updated but still not seeing a new target for the exporter or anything for it in the Prometheus configs.

```
ts=2018-04-05T17:12:47.8138389Z caller=operator.go:308 component=prometheusoperator msg="Prometheus added" key=default/snmp-exporter
ts=2018-04-05T17:12:47.8151946Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=default/snmp-exporter
ts=2018-04-05T17:12:47.8858378Z caller=operator.go:970 component=prometheusoperator msg="creating configuration"
ts=2018-04-05T17:12:48.034944Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=default/blackbox-exporter
ts=2018-04-05T17:12:48.0653846Z caller=operator.go:981 component=prometheusoperator msg="updating config skipped, no configuration change"
```

**Comment by gianrubio** [comment]
On the prometheus object you have this section

```
 serviceMonitorSelector:
      matchLabels:
        prometheus: kube-prometheus
```

Prometheus operator will only pick servicemonitors that has this labels, so I'd recommend you to add this label in your servicemonitor. It should be something like this:

```


apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: snmp-exporter
    prometheus: kube-prometheus
  name: snmp-exporter
spec:
  jobLabel: k8s-app
  selector:
    app: snmp-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - interval: 60s
    port: http-metrics
    params:
      module:
      - default
      target:
      - 165.227.106.171
    path: "/snmp"
    targetPort: 9116

```
