### ISSUE TITLE
NodeDiskRunningFull is a bit too aggressive on nodes with small disks

### ISSUE THREAD

**Issue by atopuzov** [coreos/prometheus-operator#1180]
**What did you do?**

Let autoscaler spin up a node with a small disk (8 Gi). 

**What did you expect to see?**

No alarms.

**What did you see instead? Under which circumstances?**

Every time a new node is spun up NodeDiskRunningFull (the one with critical severity) is alarming.
They clear up some 10-15 mins later.

**Environment**

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

kops

* Manifests:

```
  - alert: NodeDiskRunningFull
    expr: predict_linear(node_filesystem_free[30m], 3600 * 2) < 0
    for: 10m
    labels:
      severity: critical
    annotations:
      description: device {{$labels.device}} on node {{$labels.instance}} is running
        full within the next 2 hours (mounted at {{$labels.mountpoint}})
      summary: Node disk is running full within 2 hours
```

* Prometheus Operator Logs:

Not relevant to prometheus operator.
