### ISSUE TITLE
ServiceMonitor - Correct usage of staticTargets?

### ISSUE THREAD

**Issue by ScottBrenner** [coreos/prometheus-operator#1201]
Regarding [this](https://github.com/coreos/prometheus-operator/blob/7c84fdb17d606a23a2e8e98354e6ed00212d4628/example/prometheus-operator-crd/servicemonitor.crd.yaml#L143)-

I've followed the [custom service monitoring example](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#monitoring-custom-services) and want to additionally monitor a static target - see below. Is this correct?

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ...
  labels:
    tier: ...
spec:
  selector:
     matchLabels:
       tier: ...
  endpoints:
  - port: prometheus
    interval: 10s
  - staticTargets: "IP:PORT"    <------ is this correct?
```

I'm not seeing anything in Prometheus that reflects the `staticTargets` so I'm probably not using it correctly - how should I?

**Comment by mikeln** [comment]
I think these are correct: 
```
staticTargets:
  - 'https://prometheus.mycluster'
  - 'http://somethingelse.mycluster'
  - 'withaport.mycluster:9090'
```

However,  I do not see the prometheus config get updated when I add a staticTarget service monitor.    
Is there some "special sauce" needed to get  kube-prometheus/prometheus to pick the the config change?

**Comment by ScottBrenner** [comment]
Thanks. FWIW I've been doing a `kubectl -f apply <file>` then `curl -X POST <prometheus URL>/-/reload`.

**Comment by brancz** [comment]
Note static targets support was only merged after the latest release. It will only land in the next minor release and it’s experimental so may change at any time without deprecation.

**Comment by mxinden** [comment]
>  Is there some "special sauce" needed to get kube-prometheus/prometheus to pick the the config change?

@mikeln The prometheus operator should automatically update the Prometheus config and reload Prometheus. Are you able to reproduce this? If so, would you mind opening up a new issue?

**Comment by mikeln** [comment]
https://github.com/coreos/prometheus-operator/issues/1207

**Comment by mxinden** [comment]
@mikeln @ScottBrenner  The _static-targets-feature_ has not been released by now. It is only part of the `master` branch (See [comment](https://github.com/coreos/prometheus-operator/issues/1201#issuecomment-380014739)). I am sorry for any confusion this might have caused.

Feel free to reopen here, in case you are facing the same issue on `master`.

---

> Although v0.18.1 is not in quay.io yet... was running v0.18.0, so not sure of the validity of the issue.

@mikeln We will soon push any images for all branches automatically to quay. Sorry for the delay here.

**Comment by brancz** [comment]
In fact some early testers have reported that it doesn’t work as intended so static targets may be reverted and or significantly changed even before it ever being released.

**Comment by ScottBrenner** [comment]
Got it. How could I configure the [custom service monitoring example](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#monitoring-custom-services) to monitor a static target?

**Comment by brancz** [comment]
@ScottBrenner In most cases you can probably just use the same strategy as laid out here: https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/Monitoring%20external%20etcd.md

**Comment by ScottBrenner** [comment]
@brancz Bingo! Much appreciated.

@mikebryant see above ☝️

**Comment by camilb** [comment]
This example works fine for most use cases. I'm using it to scrape a VM outside Kubernetes, running `node_exporter`. Also tested #1100 but didn't work for me.

```yaml
kind: Service
apiVersion: v1
metadata:
  name: external
  namespace: monitoring
  labels:
    k8s-app: external
spec:
  externalName: 1.1.1.1
  type: ExternalName
  ports:
  - name: http
    port: 9100
    protocol: TCP
    targetPort: 9100
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external
  namespace: monitoring
  labels:
    k8s-app: external
subsets:
- addresses:
  - ip: 1.1.1.1
  ports:
  - name: http
    port: 9100
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external
  labels:
    k8s-app: external
  namespace: monitoring
spec:
  endpoints:
  - interval: 15s
    port: http
    path: /metrics
    honorLabels: true
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      k8s-app: external
```
