### ISSUE TITLE
Invalid ServiceMonitor manifest will crash the operator

### ISSUE THREAD

**Issue by k1-hedayati** [coreos/prometheus-operator#1202]
**What did you do?**
Created an invalid ServiceMonitor manifest.

**What did you expect to see?**
Just ignore invalid ServiceMonitor and don't crash.
There was a comment on #892 stating that CRD validation is not implemented yet, utill it gets implemented as a workaround is it possible to ignore invalid CRD and move on?

**What did you see instead? Under which circumstances?**
Operator enters `CrashLoopBackOff` state.

**Environment**

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: X
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: X
  endpoints:
  - port: X
    metricRelabelings:
      - sourceLabels: "[__meta_kubernetes_service_namespace, __meta_kubernetes_service_name]"
        regex: "(.+);(.+)"
        action: "replace"
        replacement: "$1/$2"
        targetLabel: "job"
  namespaceSelector:
    matchNames:
      - X
```

* Prometheus Operator Logs:

```
ts=2018-04-10T04:26:30.817714468Z caller=operator.go:394 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
ts=2018-04-10T04:26:30.839119053Z caller=operator.go:394 component=alertmanageroperator msg="sync alertmanager" key=monitoring/alertmanager
ts=2018-04-10T04:26:36.817047883Z caller=main.go:130 msg="Unhandled error received. Exiting..." err="creating CRDs failed: timed out waiting for Custom Resource: json: c
annot unmarshal string into Go struct field RelabelConfig.sourceLabels of type []string"
```
