### ISSUE TITLE
StaticTarget ServiceMonitor Is Not Updating Prometheus Configuration

### ISSUE THREAD

**Issue by mikeln** [coreos/prometheus-operator#1207]
**What did you do?**
Use a serviceMonitor with a static target to monitor another cluster via the <cluster prometheus ingress>/federate  endpoint.  (Use PR1100 changes)

**What did you expect to see?**
Data from the other cluster.  More directly, the prometheus.yaml config file should have been updated for the new static configs.

**What did you see instead? Under which circumstances?**
No change to the prometheus config file, the new static config was not added.

**Environment**
prometheus-operator v0.18.0  (v0.18.1 is not in quay.io yet...).  deployed via Helm.   

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
Helm:
```
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```
* Kubernetes cluster kind: 

AWS kubernetes cluster created via samung-cnct/kraken.

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: federated-a-cluster
  namespace: monitoring
  labels:
    app: federated-cluster
    cluster: a
spec:
  jobLabel: feda
 selector:
    matchLabels:
      name: nothing
  namesapceSelector:
    matchNames:
    - nothing
  endpoints:
  - interval: 30s
    path: /federate
    params:
      'match[]':
        - '{__name__="up"}'
    staticTargets:
      - 'https://prometheus.a.bogus.io'
      - 'http://prometheus.a.bogus.io'
```
