### ISSUE TITLE
intermittent "This site can’t be reached" for services

### ISSUE THREAD

**Issue by ayk33** [coreos/prometheus-operator#1213]
**What did you do?**
I deployed all three services `Prometheus, Grafana, Alertmanager` via the helm charts `coreos/prometheus-operator` and `coreos/kube-prometheus`. From there I am creating a service with type LoadBalancer for each service. (Manifest of service can be found below)

**What did you see instead? Under which circumstances?**
The issue I am running into is hard to pin down. Intermittently when I try and hit the elb created,  it takes a long time trying to load the page and eventually I end up getting a `This site can't be reached` on chrome with error `ERR_CONNECTION_RESET`
![image](https://user-images.githubusercontent.com/8599737/38648332-803d7a64-3da5-11e8-905f-2c832fdd6f83.png)

If I refresh the page though at any moment while it is loading I am able to hit the prometheus page perfectly fine. This happens with all three services.
As part of troubleshooting process I tried opening up the the port the elb is forwarding traffic to (the prometheus port) on the EC2 instances security group and hitting that port directly. This worked perfectly fine and consistently, which leads me to believe the issue is related to the elb. 

I don't know if this is an issue from the kubernetes side or the prometheus-operator side. I figured I would start here because none of the other services I have deployed in my cluster are showing similar behavior. 

**Environment**

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-16T19:13:55Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
Kubernetes cluster deployed via kops into an AWS VPC
3 master nodes and 3 worker nodes. 
	
* Manifests:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
  name: prometheus-internal-elb
  namespace: monitoring
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    statefulset.kubernetes.io/pod-name: prometheus-kube-prometheus-0
  type: LoadBalancer
```
