### ISSUE TITLE
Prometheus not created with OwnerReferencesPermissionEnforcement admission controller enabled

### ISSUE THREAD

**Issue by klynch** [coreos/prometheus-operator#1221]
**What did you do?**

After upgrading the cluster to 1.10 and enabling more admission controllers (particulary `OwnerReferencesPermissionEnforcement`) , Prometheus was unable to create a Prometheus instance.

I attempted to apply the changes from #975 but it did not solve the problem. 

After removing the `OwnerReferencesPermissionEnforcement`, the prometheus-operator behaved as expected.

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:13:02Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

 Custom built bare-metal with Ansible.

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: klynch
spec:
  ruleSelector:
    matchLabels:
      prometheus: klynch
      role: prometheus-alerts
  serviceMonitorSelector:
    matchLabels:
      prometheus: klynch
      role: prometheus-targets
```

* Prometheus Operator Logs:

```
E0413 00:20:17.913837       1 operator.go:591] Sync "klynch/prometheus" failed: creating config failed: secrets "prometheus-prometheus" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion monitoring.coreos.com/v1 Kind Prometheus: allowed by ClusterRoleBinding "prometheus-operator" of ClusterRole "prometheus-operator" to ServiceAccount "prometheus-operator/kube-system", no matches for kind "Prometheus" in version "monitoring.coreos.com/v1"
```
