### ISSUE TITLE
loglevel is ignored for alertmanager

### ISSUE THREAD

**Issue by Deshke** [coreos/prometheus-operator#1225]
**What did you do?**
added the `loglevel: debug` to alertmanager-main

```yaml
spec:
  ExternalURL: https://foo.bar.tld/alertmanager-main/
  logLevel: debug
  replicas: 3
  version: v0.15.0-rc.1
```

**What did you expect to see?**

debug log in the logs and `--log.level=debug` as arg for the alertmanager

**What did you see instead? Under which circumstances?**
```yaml
 kubectl -n monitoring describe pod alertmanager-main-1
Name:           alertmanager-main-1
Namespace:      monitoring
Node:           ip-172-25-33-187.us-east-2.compute.internal/172.25.33.187
Start Time:     Tue, 17 Apr 2018 09:28:31 +0200
Labels:         alertmanager=main
                app=alertmanager
                controller-revision-hash=alertmanager-main-7f64f658c5
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"StatefulSet","namespace":"monitoring","name":"alertmanager-main","uid":"20e7e01c-420f-11e8-b874-069d260f2e...
Status:         Running
IP:             100.88.100.15
Controlled By:  StatefulSet/alertmanager-main
Containers:
  alertmanager:
    Container ID:  docker://5418c244fce1eb26cc7e0d795a6ec97631d9669a51107428f33f673b5cf6150b
    Image:         quay.io/prometheus/alertmanager:v0.15.0-rc.1
    Image ID:      docker-pullable://quay.io/prometheus/alertmanager@sha256:d7bf6d0943f8a83c55aa50a7c6e6331a1be63f624f88176f110ee41ad720a12f
    Ports:         9093/TCP, 6783/TCP
    Args:
      --config.file=/etc/alertmanager/config/alertmanager.yaml
      --cluster.listen-address=$(POD_IP):6783
      --storage.path=/alertmanager
      --web.listen-address=:9093
      --web.external-url=https://foo.bar.tld/alertmanager-main/
      --web.route-prefix=/
      --cluster.peer=alertmanager-main-0.alertmanager-operated.monitoring.svc:6783
      --cluster.peer=alertmanager-main-1.alertmanager-operated.monitoring.svc:6783
      --cluster.peer=alertmanager-main-2.alertmanager-operated.monitoring.svc:6783
    State:          Running
      Started:      Tue, 17 Apr 2018 09:28:34 +0200
    Ready:          True
    Restart Count:  0
    Requests:
      memory:   200Mi
    Liveness:   http-get http://:web/api/v1/status delay=0s timeout=3s period=10s #success=1 #failure=10
    Readiness:  http-get http://:web/api/v1/status delay=3s timeout=3s period=5s #success=1 #failure=10
    Environment:
      POD_IP:   (v1:status.podIP)
    Mounts:
      /alertmanager from alertmanager-main-db (rw)
      /etc/alertmanager/config from config-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-28zcn (ro)
  config-reloader:
    Container ID:  docker://8f75517bfdec6f7a1500fe406cbec6f5af3808e6a3f0d16de73695ca938b56f4
    Image:         quay.io/coreos/configmap-reload:v0.0.1
    Image ID:      docker-pullable://quay.io/coreos/configmap-reload@sha256:e2fd60ff0ae4500a75b80ebaa30e0e7deba9ad107833e8ca53f0047c42c5a057
    Port:          <none>
    Args:
      -webhook-url=http://localhost:9093/-/reload
      -volume-dir=/etc/alertmanager/config
    State:          Running
      Started:      Tue, 17 Apr 2018 09:28:42 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     5m
      memory:  10Mi
    Requests:
      cpu:        5m
      memory:     10Mi
    Environment:  <none>
    Mounts:
      /etc/alertmanager/config from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-28zcn (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          True
  PodScheduled   True
Volumes:
  config-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  alertmanager-main
    Optional:    false
  alertmanager-main-db:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  default-token-28zcn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-28zcn
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.alpha.kubernetes.io/notReady:NoExecute for 300s
                 node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason                 Age   From                                                  Message
  ----    ------                 ----  ----                                                  -------
  Normal  Scheduled              9m    default-scheduler                                     Successfully assigned alertmanager-main-1 to ip-172-25-33-187.us-east-2.compute.internal
  Normal  SuccessfulMountVolume  9m    kubelet, ip-172-25-33-187.us-east-2.compute.internal  MountVolume.SetUp succeeded for volume "alertmanager-main-db"
  Normal  SuccessfulMountVolume  9m    kubelet, ip-172-25-33-187.us-east-2.compute.internal  MountVolume.SetUp succeeded for volume "config-volume"
  Normal  SuccessfulMountVolume  9m    kubelet, ip-172-25-33-187.us-east-2.compute.internal  MountVolume.SetUp succeeded for volume "default-token-28zcn"
  Normal  Pulling                9m    kubelet, ip-172-25-33-187.us-east-2.compute.internal  pulling image "quay.io/prometheus/alertmanager:v0.15.0-rc.1"
  Normal  Pulled                 9m    kubelet, ip-172-25-33-187.us-east-2.compute.internal  Successfully pulled image "quay.io/prometheus/alertmanager:v0.15.0-rc.1"
  Normal  Created                9m    kubelet, ip-172-25-33-187.us-east-2.compute.internal  Created container
  Normal  Started                9m    kubelet, ip-172-25-33-187.us-east-2.compute.internal  Started container
  Normal  Pulling                9m    kubelet, ip-172-25-33-187.us-east-2.compute.internal  pulling image "quay.io/coreos/configmap-reload:v0.0.1"
  Normal  Pulled                 9m    kubelet, ip-172-25-33-187.us-east-2.compute.internal  Successfully pulled image "quay.io/coreos/configmap-reload:v0.0.1"
  Normal  Created                9m    kubelet, ip-172-25-33-187.us-east-2.compute.internal  Created container
  Normal  Started                9m    kubelet, ip-172-25-33-187.us-east-2.compute.internal  Started container
```

**Environment**

* Kubernetes version information:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.11", GitCommit:"1df6a8381669a6c753f79cb31ca2e3d57ee7c8a3", GitTreeState:"clean", BuildDate:"2018-04-05T17:16:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 

`kops`

* Prometheus Operator Logs:

```
ts=2018-04-17T07:39:04.135750535Z caller=operator.go:338 component=alertmanageroperator msg="Alertmanager updated" key=monitoring/main
ts=2018-04-17T07:39:04.135838797Z caller=operator.go:394 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main

```
