### ISSUE TITLE
Tolerations not set for prometheus-operator/templates/get-crd-job.yaml

### ISSUE THREAD

**Issue by ayk33** [coreos/prometheus-operator#1234]
**What did you do?**
I am trying to deploy prometheus-operator (and soon kube-prometheus) onto my master nodes. The master nodes are tainted to block pods from from deploying onto them. I set the tolerations field in my values file for prometheus-operator, and part of the helm install is successful. The job `prometheus-operator-create-sm-job` gets created successfully but `prometheus-operator-get-crd` does not. 
After looking at the code for a little bit I see that in the file `prometheus-operator/templates/deployment.yaml`, the `tolerations` value is being used and wondering if the same should be happening for  `prometheus-operator/templates/get-crd-job.yaml`
 
**What did you expect to see?**
See the resources get deployed onto my master node. 

**What did you see instead? Under which circumstances?**
The job `prometheus-operator-get-crd` failed to create with the error `0/6 nodes are available: 3 MatchNodeSelector, 3 PodToleratesNodeTaints.`

**Environment**

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-16T19:13:55Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
Kubernetes cluster created via kops in AWS.

* Manifests:
Here is the values file I am using to install prometheus-operator. Same as default except for nodeselector and tolerations fields have been set. 
```
global:
  ## Hyperkube image to use when getting ThirdPartyResources & cleaning up
  ##
  hyperkube:
    repository: quay.io/coreos/hyperkube
    tag: v1.7.6_coreos.0
    pullPolicy: IfNotPresent

## Prometheus-config-reloader image to use for config and rule reloading
##
prometheusConfigReloader:
  repository: quay.io/coreos/prometheus-config-reloader
  tag: v0.0.3

## Configmap-reload image to use for reloading configmaps
##
configmapReload:
  repository: quay.io/coreos/configmap-reload
  tag: v0.0.1

## Prometheus-operator image
##
image:
  repository: quay.io/coreos/prometheus-operator
  tag: v0.18.0
  pullPolicy: IfNotPresent

## If enabled, prometheus-operator will create a service for scraping kubelets
##
kubeletService:
  enable: true
  namespace: kube-system
  name: kubelet

## Node labels for prometheus-operator pod assignment
##
nodeSelector:
  dedicated: master

## Tolerations for use with node taints
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations:
- key: node-role.kubernetes.io/master
  effect: NoSchedule

## If true, create & use RBAC resources
##
rbacEnable: true

## Prometheus-operator resource limits & requests
## Ref: https://kubernetes.io/docs/user-guide/compute-resources/
##
resources: {}
  # limits:
  #   cpu: 200m
  #   memory: 100Mi
  # requests:
  #   cpu: 100m
  #   memory: 50Mi

jobLabel: prometheus-operator

```
