### ISSUE TITLE
Alertmanager TPR is broken when using api v1.5.2

### ISSUE THREAD

**Issue by jescarri** [coreos/prometheus-operator#126]
I have installed a v1.5.2 cluster and installed latest prometheus operator

```
cat 01_kubeServices/prometheus-operator.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-operator
  labels:
    operator: prometheus
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        operator: prometheus
    spec:
      containers:
       - name: prometheus-operator
         image: quay.io/coreos/prometheus-operator:v0.2.3
         resources:
           requests:
             cpu: 100m
             memory: 50Mi
           limits:
             cpu: 200m
             memory: 100Mi
```

when I try to add an Alertmanager It fails, using an old client v1.4.4 works 

```
$ kctl $k8scluster get thirdpartyresources
NAME                                    DESCRIPTION                           VERSION(S)
alertmanager.monitoring.coreos.com      Managed Alertmanager cluster          v1alpha1
prometheus.monitoring.coreos.com        Managed Prometheus server             v1alpha1
service-monitor.monitoring.coreos.com   Prometheus monitoring for a service   v1alpha1
✔ ~/workspace/dns-prometheus-monitoring/dev1.cs.us-east-1/dev1 [master|✔]
13:05 $ kctl $k8scluster version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2+coreos.0", GitCommit:"3ed7d0f453a5517245d32a9c57c39b946e578821", GitTreeState:"clean", BuildDate:"2017-01-13T00:23:19Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
✔ ~/workspace/dns-prometheus-monitoring/dev1.cs.us-east-1/dev1 [master|✔]
13:06 $ kctl $k8scluster apply -f /cfg/alertmanager/alertmanager.yaml
E0130 21:09:47.324629       1 kubectl_wrapper.go:20] Error executing kubectl Exit Status: 1
E0130 21:09:47.324866       1 kubectl_wrapper.go:21] Exit Code: 1
error: unable to decode "/cfg/alertmanager/alertmanager.yaml": no kind "Alertmanager" is registered for version "monitoring.coreos.com/v1alpha1"
✘-255 ~/workspace/dns-prometheus-monitoring/dev1.cs.us-east-1/dev1 [master|✔]
13:09 $ cat alertmanager/alertmanager.yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: Alertmanager
metadata:
  name: alertmanager-dev1
  namespace: prd122
  labels:
    alertmanager: alertmanager-dev1
spec:
  replicas: 3
  version: v0.5.1
  externalUrl: http://foo/bar
```
