### ISSUE TITLE
[ support ] not working but I don't know why

### ISSUE THREAD

**Issue by gogeof** [coreos/prometheus-operator#1272]
**What did you do?**
from [The Prometheus Operator: Managed Prometheus setups for Kubernetes](https://coreos.com/blog/the-prometheus-operator.html) to deploy prometheus in k8s cluster, but failed when deploy prometheus resouce

**What did you expect to see?**
success

**What did you see instead? Under which circumstances?**
```
$ kubectl apply -f prometheus.yaml
service "prometheus-k8s" configured
error: unable to recognize "prometheus.yaml": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1alpha1"
```

**Environment**

* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

use kubeadm to install k8s cluster.

* Manifests:

```
# cat etcd.yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --advertise-client-urls=https://127.0.0.1:2379
    - --client-cert-auth=true
    - --peer-client-cert-auth=true
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --listen-client-urls=https://127.0.0.1:2379
    - --data-dir=/var/lib/etcd
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    image: k8s.gcr.io/etcd-amd64:3.1.12
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -ec
        - ETCDCTL_API=3 etcdctl --endpoints=127.0.0.1:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt
          --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt --key=/etc/kubernetes/pki/etcd/healthcheck-client.key
          get foo
      failureThreshold: 8
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: etcd
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd-data
    - mountPath: /etc/kubernetes/pki/etcd
      name: etcd-certs
  hostNetwork: true
  volumes:
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
  - hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
    name: etcd-certs
status: {}

# cat kube-apiserver.yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --insecure-port=0
    - --enable-bootstrap-token-auth=true
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --allow-privileged=true
    - --requestheader-allowed-names=front-proxy-client
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    - --secure-port=6443
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --service-cluster-ip-range=10.96.0.0/12
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --requestheader-username-headers=X-Remote-User
    - --advertise-address=192.168.64.128
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --authorization-mode=Node,RBAC
    - --etcd-servers=https://127.0.0.1:2379
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
    image: k8s.gcr.io/kube-apiserver-amd64:v1.10.1
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 192.168.64.128
        path: /healthz
        port: 6443
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-apiserver
    resources:
      requests:
        cpu: 250m
    volumeMounts:
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
status: {}

# cat kube-controller-manager.yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-controller-manager
    - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    - --controllers=*,bootstrapsigner,tokencleaner
    - --kubeconfig=/etc/kubernetes/controller-manager.conf
    - --root-ca-file=/etc/kubernetes/pki/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    - --address=127.0.0.1
    - --leader-elect=true
    - --use-service-account-credentials=true
    image: k8s.gcr.io/kube-controller-manager-amd64:v1.10.1
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-controller-manager
    resources:
      requests:
        cpu: 200m
    volumeMounts:
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/kubernetes/controller-manager.conf
      name: kubeconfig
      readOnly: true
    - mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      name: flexvolume-dir
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/kubernetes/controller-manager.conf
      type: FileOrCreate
    name: kubeconfig
  - hostPath:
      path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      type: DirectoryOrCreate
    name: flexvolume-dir
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
status: {}

# cat kube-scheduler.yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-scheduler
    - --address=127.0.0.1
    - --leader-elect=true
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    image: k8s.gcr.io/kube-scheduler-amd64:v1.10.1
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
status: {}
```

* Prometheus Operator Logs:

```
$ kubectl logs -f prometheus-operator-74799957fd-4f2rm
ts=2018-04-27T10:17:28.360594955Z caller=operator.go:170 component=alertmanageroperator msg="connection established" cluster-version=v1.10.1
ts=2018-04-27T10:17:28.361390121Z caller=operator.go:269 component=prometheusoperator msg="connection established" cluster-version=v1.10.1
ts=2018-04-27T10:17:28.36618667Z caller=operator.go:184 component=alertmanageroperator msg="CRD API endpoints ready"
ts=2018-04-27T10:17:28.440964629Z caller=operator.go:283 component=prometheusoperator msg="CRD API endpoints ready"
ts=2018-04-27T10:17:28.448547688Z caller=operator.go:319 component=prometheusoperator msg="Prometheus added" key=default/prometheus
ts=2018-04-27T10:17:28.449569281Z caller=operator.go:339 component=prometheusoperator msg="Prometheus updated" key=default/prometheus
ts=2018-04-27T10:17:28.449503297Z caller=operator.go:684 component=prometheusoperator msg="sync prometheus" key=default/prometheus
ts=2018-04-27T10:17:28.457807736Z caller=operator.go:1024 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-04-27T10:17:28.588016535Z caller=operator.go:684 component=prometheusoperator msg="sync prometheus" key=default/prometheus
ts=2018-04-27T10:17:28.593928954Z caller=operator.go:1024 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-04-27T10:19:06.770025749Z caller=operator.go:684 component=prometheusoperator msg="sync prometheus" key=default/prometheus
ts=2018-04-27T10:19:06.776306715Z caller=operator.go:1024 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-04-27T10:19:21.802331777Z caller=operator.go:339 component=prometheusoperator msg="Prometheus updated" key=default/prometheus
ts=2018-04-27T10:19:21.802557867Z caller=operator.go:684 component=prometheusoperator msg="sync prometheus" key=default/prometheus
ts=2018-04-27T10:19:21.806284724Z caller=operator.go:1024 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-04-27T10:20:28.407405614Z caller=operator.go:684 component=prometheusoperator msg="sync prometheus" key=default/prometheus
ts=2018-04-27T10:20:28.439442559Z caller=operator.go:1024 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-04-27T10:20:34.930775038Z caller=operator.go:339 component=prometheusoperator msg="Prometheus updated" key=default/prometheus
ts=2018-04-27T10:20:34.93085489Z caller=operator.go:684 component=prometheusoperator msg="sync prometheus" key=default/prometheus
ts=2018-04-27T10:20:34.93633399Z caller=operator.go:1024 component=prometheusoperator msg="updating config skipped, no configuration change"
```

**Comment by brancz** [comment]
The blog post is outdated, sorry about that, it happens easily to blog posts to go stale. Please try the [getting started guide](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md) and see if you still run into problems.

**Comment by gogeof** [comment]
just this problem: 

```
level=error ts=2018-04-28T02:43:34.390567729Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:270: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:default:default\" cannot list pods in the namespace \"default\""
level=error ts=2018-04-28T02:43:34.390781165Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:269: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:default:default\" cannot list services in the namespace \"default\""
level=error ts=2018-04-28T02:43:34.394814697Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:268: Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:default:default\" cannot list endpoints in the namespace \"default\""
```

and can be solve by：

```bash
kubectl apply -f default-privilege-add.yaml
```

default-privilege-add.yaml look like:
```
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: default-privilege-add
rules:
- apiGroups: [""]
  resources:
  - endpoints
  - services
  - pods
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: default-privilege-add
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: default-privilege-add
subjects:
- kind: ServiceAccount
  name: default
  namespace: default

```
