### ISSUE TITLE
Failed to watch *v1.Namespace: unknown (get namespaces)

### ISSUE THREAD

**Issue by mzupan** [coreos/prometheus-operator#1324]
**What did you do?**

I'm trying to get the operator running and running into this error

```
E0504 06:12:05.789554       1 reflector.go:322] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:300: Failed to watch *v1.Namespace: unknown (get namespaces)
```

That's in the prometheus operator logs

This is all running in a `services` namespace and my prometheus config when I load the deployment is only monitoring default it seems like

```
/prometheus $ cat /etc/prometheus/config_out/prometheus.env.yaml
global:
  evaluation_interval: 30s
  scrape_interval: 30s
  external_labels:
    prometheus: services/prometheus
    prometheus_replica: prometheus-prometheus-0
scrape_configs: []
alerting:
  alert_relabel_configs:
  - action: labeldrop
    regex: prometheus_replica
  alertmanagers:
  - path_prefix: /
    scheme: http
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - default
    relabel_configs:
    - action: keep
      source_labels:
      - __meta_kubernetes_service_name
      regex: alertmanager
    - action: keep
      source_labels:
      - __meta_kubernetes_endpoint_port_name
      regex: web
```

* Manifests:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-operator
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - prometheuses
  - servicemonitors
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs: ["*"]
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  verbs: ["*"]
- apiGroups: [""]
  resources:
  - pods
  verbs: ["list", "delete"]
- apiGroups: [""]
  resources:
  - services
  - endpoints
  verbs: ["get", "create", "update"]
- apiGroups: [""]
  resources:
  - nodes
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources:
  - namespaces
  verbs: ["list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operator
  namespace: services
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: services
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-operator
  namespace: services
  labels:
    operator: prometheus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        operator: prometheus
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator
      containers:
      - name: prometheus-operator
        image: quay.io/coreos/prometheus-operator:v0.19.0
        args:
          - --kubelet-service=kube-system/kubelet
          - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: services

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: services

---

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: services
  labels:
    prometheus: prometheus
spec:
  replicas: 2
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  alerting:
    alertmanagers:
    - namespace: default
      name: alertmanager
      port: web

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: services
  annotations:
    avi_proxy: '{"virtualservice": {"east_west_placement": false}}'
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus

```

* Prometheus Operator Logs:

```
ts=2018-05-04T06:11:53.099266021Z caller=operator.go:345 component=prometheusoperator msg="Prometheus updated" key=services/prometheus
ts=2018-05-04T06:11:53.099313987Z caller=operator.go:690 component=prometheusoperator msg="sync prometheus" key=services/prometheus
ts=2018-05-04T06:11:53.106353471Z caller=operator.go:1053 component=prometheusoperator msg="updating config skipped, no configuration change"
E0504 06:11:53.688249       1 reflector.go:322] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:300: Failed to watch *v1.Namespace: unknown (get namespaces)
E0504 06:11:54.691215       1 reflector.go:322] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:300: Failed to watch *v1.Namespace: unknown (get namespaces)
E0504 06:11:55.695893       1 reflector.go:322] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:300: Failed to watch *v1.Namespace: unknown (get namespaces)
E0504 06:11:56.698611       1 reflector.go:322] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:300: Failed to watch *v1.Namespace: unknown (get namespaces)
```

**Comment by jescarri** [comment]
Need to update the prometheus operator rbac rules.

**Comment by mzupan** [comment]
Thanks issue solved not sure how i missed it

```
- apiGroups: [""]
  resources:
  - namespaces
  verbs: ["list","watch"]
```

**Comment by jolson490** [comment]
I'm using [kube-prometheus v0.19.0](https://github.com/coreos/prometheus-operator/tree/v0.19.0/contrib/kube-prometheus), and I too am getting the following in prometheus-operator logs:
`E0517 17:06:40.310569       1 reflector.go:322] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:300: Failed to watch *v1.Namespace: unknown (get namespaces)
`

hi @mzupan , can you please further explain your most recent comment above? i.e. what change did you make to which `*.yaml` manifest file to get past this issue? 

--------

I found #1292 , which added `, "watch"` to the following snippet from [helm/prometheus-operator/clusterrole.yaml](https://github.com/coreos/prometheus-operator/blob/c1314db/helm/prometheus-operator/templates/clusterrole.yaml):
```
- apiGroups: [""]
  resources:
  - namespaces
  verbs: ["list", "watch"]
```

Does an equivalent change need to be made to [kube-prometheus/0prometheus-operator-clusterRole.yaml](https://github.com/coreos/prometheus-operator/blob/4263ea0/contrib/kube-prometheus/manifests/0prometheus-operator-clusterRole.yaml)? Here's the corresponding snippet from that file:
```
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
```
