### ISSUE TITLE
nodeSelector not configurable in coreos/exporter-kube-state chart

### ISSUE THREAD

**Issue by Wenzil** [coreos/prometheus-operator#1330]
**What did you do?**
`helm install coreos/exporter-kube-state -f my_chart_values.yaml`

**What did you expect to see?**
Pods deployed on the nodes specified by the `nodeSelector` in my yaml file

**What did you see instead? Under which circumstances?**
Pods deployed on a random node  

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.6-gke.1", GitCommit:"cb151369f60073317da686a6ce7de36abe2bda8d", GitTreeState:"clean", BuildDate:"2018-04-07T22:06:59Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

GKE

* Manifests:

```
# my_chart_values.yaml
# nodeSelector not supported yet by coreos/exporter-kube-state chart
nodeSelector:
  dedicated: monitoring
tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "monitoring"
    effect: "NoSchedule"
replicaCount: 1
```
