### ISSUE TITLE
Unable to add a new service to be monitored

### ISSUE THREAD

**Issue by bryanlarsen** [coreos/prometheus-operator#1348]
**What did you do?**

 Created a new servicemonitor

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: blue-statsd-exporter
    prometheus: kube-prometheus
  name: blue-statsd-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: scrape
  namespaceSelector:
    matchNames:
    - blue
  selector:
    matchLabels:
      chart: statsd-exporter
```

which should match

```
apiVersion: v1
kind: Service
metadata:
  labels:
    chart: statsd-exporter
  name: statsd-exporter
  namespace: blue
spec:
  clusterIP: 10.233.55.229
  ports:
  - name: scrape
    port: 9102
    protocol: TCP
    targetPort: 9102
  - name: statsd
    port: 8125
    protocol: UDP
    targetPort: 8125
  selector:
    app: statsd-exporter
  sessionAffinity: None
  type: ClusterIP
```

**What did you expect to see?**

 I expected to see it appear in the prometheus dashboard under targets

**What did you see instead? Under which circumstances?**

It does show up in /etc/prometheus/config_out/prometheus_env.yaml:

```
- job_name: monitoring/blue-statsd-exporter/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - blue
  scrape_interval: 30s
  relabel_configs:
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_chart
    regex: statsd-exporter
  - action: keep
    source_labels:
    - __meta_kubernetes_endpoint_port_name
    regex: scrape
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: service
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: job
    replacement: ${1}
  - target_label: endpoint
    replacement: scrape
```

it just never shows up in targets.

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

kubespray on metal

* Manifests:

prometheus deployed by using `kubectl apply -f .` in the contrib/kube-prometheus/manifests directory of 43795dec5464872cf28ec093ebc4e9702e25ca4d

with the following diff:

```
diff --git a/contrib/kube-prometheus/manifests/0prometheus-operator-clusterRole.yaml b/contrib/kube-prometheus/manifests/0prometheus-operator-clusterRole.yaml
index 76f943d..8c85391 100644
--- a/contrib/kube-prometheus/manifests/0prometheus-operator-clusterRole.yaml
+++ b/contrib/kube-prometheus/manifests/0prometheus-operator-clusterRole.yaml
@@ -67,3 +67,4 @@ rules:
   - namespaces
   verbs:
   - list
+  - watch
diff --git a/contrib/kube-prometheus/manifests/prometheus-clusterRole.yaml b/contrib/kube-prometheus/manifests/prometheus-clusterRole.yaml
index d5c4598..e856257 100644
--- a/contrib/kube-prometheus/manifests/prometheus-clusterRole.yaml
+++ b/contrib/kube-prometheus/manifests/prometheus-clusterRole.yaml
@@ -3,12 +3,18 @@ kind: ClusterRole
 metadata:
   name: prometheus-k8s
 rules:
-- apiGroups:
-  - ""
+- apiGroups: [""]
   resources:
-  - nodes/metrics
-  verbs:
-  - get
+  - nodes
+  - services
+  - endpoints
+  - pods
+  - namespaces
+  verbs: ["get", "list", "watch"]
+- apiGroups: [""]
+  resources:
+  - configmaps
+  verbs: ["get"]
 - nonResourceURLs:
   - /metrics
   verbs:
```

* Prometheus Operator Logs:

```
ts=2018-05-16T18:45:25.870907076Z caller=operator.go:274 component=prometheusoperator msg="connection established" cluster-version=v1.10.2
ts=2018-05-16T18:45:25.871408854Z caller=operator.go:170 component=alertmanageroperator msg="connection established" cluster-version=v1.10.2
ts=2018-05-16T18:45:25.895600617Z caller=operator.go:184 component=alertmanageroperator msg="CRD API endpoints ready"
ts=2018-05-16T18:45:25.898642554Z caller=operator.go:318 component=alertmanageroperator msg="Alertmanager added" key=monitoring/main
ts=2018-05-16T18:45:25.89868303Z caller=operator.go:394 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
ts=2018-05-16T18:45:25.899478527Z caller=operator.go:338 component=alertmanageroperator msg="Alertmanager updated" key=monitoring/main
ts=2018-05-16T18:45:25.954731026Z caller=operator.go:288 component=prometheusoperator msg="CRD API endpoints ready"
ts=2018-05-16T18:45:26.053748648Z caller=operator.go:325 component=prometheusoperator msg="Prometheus added" key=monitoring/k8s
ts=2018-05-16T18:45:26.053848915Z caller=operator.go:690 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2018-05-16T18:45:26.154090846Z caller=operator.go:345 component=prometheusoperator msg="Prometheus updated" key=monitoring/k8s
ts=2018-05-16T18:45:26.470117132Z caller=operator.go:1056 component=prometheusoperator msg="current config or current configmaps has changed"
ts=2018-05-16T18:45:26.470179939Z caller=operator.go:1062 component=prometheusoperator msg="updating configuration"
ts=2018-05-16T18:45:26.554913359Z caller=operator.go:394 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
ts=2018-05-16T18:45:26.557071623Z caller=operator.go:690 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2018-05-16T18:45:26.652982768Z caller=operator.go:1053 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-05-16T18:45:26.762798937Z caller=operator.go:690 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2018-05-16T18:45:26.773758064Z caller=operator.go:1056 component=prometheusoperator msg="current config or current configmaps has changed"
ts=2018-05-16T18:45:26.773783742Z caller=operator.go:1062 component=prometheusoperator msg="updating configuration"
ts=2018-05-16T18:45:26.863180389Z caller=operator.go:690 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2018-05-16T18:45:26.874174661Z caller=operator.go:1053 component=prometheusoperator msg="updating config skipped, no configuration change"
```
