### ISSUE TITLE
node_exporters are using the IP as instance name (should be hostname?)

### ISSUE THREAD

**Issue by galexrt** [coreos/prometheus-operator#135]
Is it wanted that the `instance` name of the node-exporter are the IPs and not the hostnames of the server they are running on?
As it is a bit difficult when looking through Grafana and having to "remember" which IP is which host.

***

Submitting this issue to get this documented and cleared up.

**Comment by brancz** [comment]
The `instance` label is what Prometheus uses to scrape metrics from the targets HTTP server, as kubernetes `Endpoints` are filled with `Pod` IPs rather than the nodes IPs this is not possible via the instance label. However, it should be possible to join the `node_info` metric exposed by `kube-state-metrics` onto the available `node_exporter` targets and retrieve the hostname that way.

Generally it is probably not what or how you want to look at the single nodes dashboard. To be fair the way the dashboards are layed out it may not be super obvious, but you generally want to look at your cluster state and only dig into nodes once you have identified a particular problem, for example of a specific `Pod` that is running on that very node, but grafana also does not make that very easy as a workflow. The dashboards need an overhaul either way.

**Comment by galexrt** [comment]
The node_exporter's is using the `hostNetwork` option ([see here](https://github.com/coreos/prometheus-operator/blob/master/example/node-exporter-bundle.yaml#L38) so shouldn't the IP then be of the host system or is it because of the service in front of them?

**Comment by brancz** [comment]
The node_exporter's are discovered using the `Endpoints` object which is automatically populated by the `Service`. I'm actually unsure, but I'm guessing that the `Pod`'s IP is the HostIP in that case. This in turn means we can build a query that selects the `Node` with that IP and takes the `Node`'s name instead of the IP.

**Comment by galexrt** [comment]
How would a query look for doing that? Is there a way this can be specified in the ServiceMonitor?

**Comment by eviln1** [comment]
Hi,
Bumping this issue for interest. I haven't been able to find a work-around for this, and using IP adresses in alerts seems like poor ux.
Thx :)

**Comment by atombender** [comment]
If you're using Prometheus' `role: endpoints` to discover node_exporter, you will only get the service metadata.

You should use `role: node` instead, i.e. go directly against the node port for every exporter; that will give you host names, via the `__meta_kubernetes_node_name` label. Here's what we use on Google Cloud:

```
    - job_name: kubernetes-node-exporter
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      scheme: https
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - source_labels: [__address__]
        regex: ^(.*):\d+$
        target_label: __address__
        replacement: $1:9100
      - target_label: __scheme__
        replacement: http
      # Host name
      - source_labels: [__meta_kubernetes_node_name]
        target_label: instance
      # Extract some labels
      - source_labels: [__meta_kubernetes_node_label_failure_domain_beta_kubernetes_io_zone]
        target_label: zone
      - source_labels: [__meta_kubernetes_node_label_cloud_google_com_gke_nodepool]
        target_label: gke_nodepool
```

**Comment by brancz** [comment]
Sorry for not answering here. This would also be a PromQL query that would allow you to do that without having to use a custom config just to see the nodes name instead of the IP:

```
node_boot_time *
on(instance) group_right()
label_replace(max by(pod_ip,node) (kube_pod_info{pod=~"node-exporter.*"}), "instance", "$1:9100", "pod_ip", "(.*)")
```

I'm pretty sure it is possible to do this less complex, but this is what I was able to come up with for now.

I'll make sure to update the grafana dashboard accordingly.

**Comment by galexrt** [comment]
Thanks for the help @brancz!
Closing for now as there is a solution.

**Comment by DonMartin76** [comment]
I also had this issue, but solved it via relabelling, mapping the `instance` label to the kubernetes node name in my pod scraping configuration:

```
- job_name: 'kubernetes-pods'

  kubernetes_sd_configs:
  - role: pod

  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    action: replace
    target_label: __metrics_path__
    regex: (.+)
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    action: replace
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
    target_label: __address__
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_pod_name]
    action: replace
    target_label: kubernetes_pod_name
  # map node name to instance label <-- THIS
  - source_labels: [__meta_kubernetes_pod_node_name]
    action: replace
    target_label: instance
```

Thought it might help somebody.

**Comment by brancz** [comment]
@DonMartin76 thanks for sharing!

Just to make sure this doesn't confuse anyone. The sample posted by @DonMartin76 is only possible if one writes the Prometheus configuration themselves, which is supposed to be automated by the Prometheus Operator, which is why I would recommend doing it at query time, but both works.

**Comment by DonMartin76** [comment]
@brancz Thanks for clarifying. Indeed, we are not (yet) using the Prometheus Operator.

**Comment by sylr** [comment]
I spent one hour trying to figure how to graph CPU of agents based on @brancz comment, came out with :

```
avg(
   rate(node_cpu{mode!="idle"}[2m]) 
   * on(instance) group_left(nodename) 
   node_uname_info{nodename="$k8sagent"} * 100
) by (mode)
```

$k8sagent is a grafana var on which I repeat the panel, it's populated with :

``label_values(node_uname_info, nodename)``

Hope it helps someone at some point.

**Comment by brancz** [comment]
Thanks for sharing @sylr !

**Comment by gdmello** [comment]
Based on @brancz's amazing query above, I discovered that the vector `node_uname_info` has both the ip address and the hostname (at least for my kubespray setup on AWS). So this PromQL works very nicely for me-
`sum by ( instance,nodename)  (node_load5 * on(instance) group_left(nodename) node_uname_info) `.

It would be much better if node_exporter could include the hostname as another label, as queries get quite long, and complex when doing vector multiplication (as above).

**Comment by brancz** [comment]
@gdmello you can create a recording rule for this, to attach that label to your metrics automatically: https://prometheus.io/docs/querying/rules/

**Comment by dimm0** [comment]
Is there a working solution yet? The ones listed seems to be too complex.

**Comment by brancz** [comment]
@dimm0 what are you trying to accomplish? PromQL is very powerful and can probably do everything you need it to do, I'm happy to help. Not sure what's too complex about a single line query.

**Comment by dimm0** [comment]
Hi! I'd like to have the hostname instead of IP and port in the dropdown field in standard Nodes dashboard (and some others I've added). I already could change the template field to show hostnames based on previous examples, but now I have to rewrite all queries in all panels in this dashboard. I can't yet figure out ho to change the $server field in queries like: `100 - (avg by (cpu) (irate(node_cpu{mode="idle", instance="$server"}[5m])) * 100)`

Also if it's working great, why not change it in the code in the project?

Relabeling also looks like a good option, but looks like it's hidden somewhere in the operator's code, and I couldn't find it yet.

**Comment by brancz** [comment]
We've been trying to hide relabeling for as long as we could :slightly_smiling_face:, but it seems that a lot of people actually do end up needing it, so I am considering adding an `extraRelabelingRules` field to the `ServiceMonitor` object, but have to think the design through a bit. This will still have its limitations at some point though, which is why I'm hesitant to draw the line here. In this particular problem it would not even work, as the node-exporter metrics are not gathered with the node discovery, but rather with the endpoints discovery (which is good for many reasons, but irrelevant here).

As I mentioned above the problem is solvable with recording rules today. I have been playing with this lately and will probably publish the recording rules and updated dashboards accordingly, although I believe the node name is most useful here, as it's modifiable to contain whatever you want and typically defaults to the hostname. Does that sound ok?

**Comment by dimm0** [comment]
Yep, I think that's the best option. Thanks!

**Comment by rocketraman** [comment]
@brancz Since this issue is closed, is there somewhere else we can follow for updates on the recording rules and dashboards?

**Comment by brancz** [comment]
@rocketraman that sounds good to me. It'll allow me to track that better, thanks for suggesting!

**Comment by dimm0** [comment]
@whypro Is any magic required to have `__meta_kubernetes_node_name` appear other than adding Node targetRef? Didn't work for me, with recent prometheus.

**Comment by whypro** [comment]
@dimm0 The second step is my hacking way to add node name to relabel_configs for every endpoint if its `targetRef` is `Node`. It is just a forked and private commit.
I am not sure if it is a common requirement. If so I could create a PR for this.
cc @brancz

**Comment by brancz** [comment]
The thing is that `__meta_kubernetes_node_name` nor the target ref node is available because you're not discovering nodes, but endpoints (and the underlying thing is not a node, but pods). And more generally it is much easier to add non identifying labels at query time, then mess with identifying labels, because that will cause breaks in your graphs as Prometheus will treat them as different time-series.

**Comment by avdhoot** [comment]
Other way do it.

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: node-exporter
    monitoredBy: prometheus-infra
  name: node-exporter
  namespace: node-exporter
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    relabelings:
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance
  jobLabel: name
  selector:
    matchLabels:
      k8s-app: node-exporter

**Comment by vsxen** [comment]
> Other way do it.
> 
> ```
> apiVersion: monitoring.coreos.com/v1
> kind: ServiceMonitor
> metadata:
>   labels:
>     k8s-app: node-exporter
>     monitoredBy: prometheus-infra
>   name: node-exporter
>   namespace: node-exporter
> spec:
>   endpoints:
>   - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
>     interval: 30s
>     port: https
>     scheme: https
>     tlsConfig:
>       insecureSkipVerify: true
>     relabelings:
>     - action: replace
>       sourceLabels:
>       - __meta_kubernetes_pod_node_name
>       targetLabel: instance
>   jobLabel: name
>   selector:
>     matchLabels:
>       k8s-app: node-exporter
> ```


```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: node-exporter
    monitoredBy: prometheus-infra
  name: node-exporter
  namespace: node-exporter
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    relabelings:
    - action: replace
      sourceLabels:
      - __address__ # or__meta_kubernetes_pod_ip
      targetLabel: instance
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: node # same with kube_pod_info etc.
  jobLabel: name
  selector:
    matchLabels:
      k8s-app: node-exporter
```

**Comment by dss010101** [comment]
this is an old issue but yet after so many years, google headed me this way....hoped there was a solution by now. Doesn't seem like it.   If i have nodeexporter deployed as containers on several machines, is there no way to add the hostname as one of the fields that is sent to prometheus?
the examples here resolve to the name of my container service as defined in the docker-compose, not the hostname itself.

**Comment by ebuildy** [comment]
@dss010101 using `kube-prometheus-stack` Helm chart from prometheus-community.github.io

My values.yaml:

```yaml
prometheus-node-exporter:
    prometheus:
      monitor:
        attachMetadata: true
        relabelings:
          - action: replace
            sourceLabels:
              - __meta_kubernetes_node_name
            targetLabel: node
          - action: replace
            sourceLabels:
              - __meta_kubernetes_node_label_beta_kubernetes_io_instance_type
            targetLabel: vm_type
          - action: replace
            sourceLabels:
              - __meta_kubernetes_node_label_failure_domain_beta_kubernetes_io_region
            targetLabel: vm_region
          - action: replace
            sourceLabels:
              - __meta_kubernetes_node_label_failure_domain_beta_kubernetes_io_zone
            targetLabel: vm_zone
          - action: replace
            sourceLabels:
              - __meta_kubernetes_node_label_kubernetes_azure_com_agentpool
            targetLabel: vm_pool
          - regex: "container|service|endpoint"
            action: labeldrop
```

Give me:

<img width="2127" alt="Capture d’écran, le 2024-01-24 à 17 03 11" src="https://github.com/prometheus-operator/prometheus-operator/assets/1219817/636974bc-bac9-4c7a-a686-0e415e029b70">
