### ISSUE TITLE
[kube-prometheus] Best practice for overriding serviceMonitorSelector

### ISSUE THREAD

**Issue by ResDiaryLewis** [coreos/prometheus-operator#1359]
**What did you do?**

I attempted to set the `serviceMonitorsSelector` to `{}` with both the `--set` flag (I don't think is possible via the command line): 
`helm upgrade kube-prometheus coreos/kube-prometheus --version 0.0.67 --set prometheus.serviceMonitorsSelector={}`

and a values .yaml file:
`helm upgrade kube-prometheus coreos/kube-prometheus --version 0.0.67 -f .\customValues.yaml --debug --dry-run >> kube-prometheus.log`

where customValues:

```
prometheus:
  serviceMonitorSelector: {}
  serviceMonitorsSelector: {}
```

**What did you expect to see?**

I expected to see the Prometheus object to have the property `serviceMonitorSelector: {}`, so that it selects every ServiceMonitor instance in the namespace.

**What did you see instead? Under which circumstances?**

The default that is generated without any intervention:
```
serviceMonitorSelector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - alertmanager
      - exporter-coredns
      - exporter-kube-controller-manager
      - exporter-kube-dns
      - exporter-kube-etcd
      - exporter-kube-scheduler
      - exporter-kube-state
      - exporter-kubelets
      - exporter-kubernetes
      - exporter-node
      - grafana
      - prometheus
      - prometheus-operator
```

**Environment**

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	With Azure AKS `az aks create ...`

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

- What is the best practice for overriding this value, can it be done via Helm or only edited afterwards?
- Why does the default serviceMonitorSelector manually specify every ServiceMonitor it wishes to track rather than selecting every ServiceMonitor?

**Comment by lostick** [comment]
> I expected to see the Prometheus object to have the property serviceMonitorSelector: {}, so that it selects every ServiceMonitor instance in the namespace.

**Comment by ResDiaryLewis** [comment]
Correct me if I'm wrong but I think that `serviceMonitorSelector: {}` does select all of them

**Comment by brancz** [comment]
An empty selector in Kubernetes is the "all" selector, so this behavior just follows Kubernetes norm.

**Comment by ResDiaryLewis** [comment]
So how can I override the `serviceMonitorSelector` value via Helm?

**Comment by brancz** [comment]
That's a question for @gianrubio

**Comment by gianrubio** [comment]
@ResDiaryLewis you can override the serviceMonitorSelector in the [prometheus](https://github.com/olvesh/prometheus-operator/blob/66001c5ae64cd86de177dea4ab1acf6ac90b3dbf/helm/prometheus/templates/prometheus.yaml#L63) chart
ex.
```
kube-prometheus:
  prometheus:
    serviceMonitorsSelector:
      prometheus: operator

```
