### ISSUE TITLE
Prometheus not discovering ServiceMonitor

### ISSUE THREAD

**Issue by dgeorgievski** [coreos/prometheus-operator#1370]
**What did you do?**
Created ServiceMonitor for a custom app. Followed guidelines in https://itnext.io/kubernetes-monitoring-with-prometheus-in-15-minutes-8e54d1de2e13

**What did you expect to see?**
Automatic ServiceMonitor discovery by Prometheus, and scraping of the /metrics endpoint

**What did you see instead? Under which circumstances?**
I didn't see anything in Prometheus that the new ServiceMonitor was discovered.

**Environment**

* Kubernetes version information:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:12Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	Cluster created with kops. Using k8s version 1.9.5 with RBAC enabled.

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: myapp
    chart: myapp-0.1.0
    heritage: Tiller
    release: rousing-moth
  name: myapp-service-prometheus
  namespace: mco
spec:
  endpoints:
  - interval: 10s
    port: metrics
  namespaceSelector:
    matchNames:
    - mco
  selector:
    matchLabels:
      app: myapp
      release: rousing-moth

apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
    chart: myapp-0.1.0
    heritage: Tiller
    release: rousing-moth
  name: myapp-service
  namespace: mco
spec:
  ports:
  - name: myapp-service
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: metrics
    port: 6080
    protocol: TCP
    targetPort: 6080
  selector:
    app: myapp
    release: rousing-moth
  type: ClusterIP

I've also updated the serviceMonitorSelector of Prometheus object in the monitoring namespace to try to match myapp
.....
serviceMonitorSelector:
      matchExpressions:
      - key: app
        operator: In
        values:
        - myapp
        - alertmanager
        - exporter-coredns
....
```

* Prometheus Operator Logs:

```
prometheus-operator-5d564c684d-4pncq prometheus-operator ts=2018-05-22T01:00:40.052544274Z caller=operator.go:690 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus-prometheus
prometheus-operator-5d564c684d-4pncq prometheus-operator ts=2018-05-22T01:00:40.064521757Z caller=operator.go:1053 component=prometheusoperator msg="updating config skipped, no configuration change"
prometheus-operator-5d564c684d-4pncq prometheus-operator ts=2018-05-22T01:01:10.861805Z caller=operator.go:690 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus-prometheus
prometheus-operator-5d564c684d-4pncq prometheus-operator ts=2018-05-22T01:01:10.873418966Z caller=operator.go:1053 component=prometheusoperator msg="updating config skipped, no configuration change"
prometheus-operator-5d564c684d-4pncq prometheus-operator ts=2018-05-22T01:01:10.89477652Z caller=operator.go:690 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus-prometheus
prometheus-operator-5d564c684d-4pncq prometheus-operator ts=2018-05-22T01:01:10.907538955Z caller=operator.go:1053 component=prometheusoperator msg="updating config skipped, no configuration change"
prometheus-operator-5d564c684d-4pncq prometheus-operator ts=2018-05-22T01:01:43.774290702Z caller=operator.go:345 component=prometheusoperator msg="Prometheus updated" key=monitoring/kube-prometheus-prometheus
prometheus-operator-5d564c684d-4pncq prometheus-operator ts=2018-05-22T01:01:43.774350679Z caller=operator.go:690 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus-prometheus
prometheus-operator-5d564c684d-4pncq prometheus-operator ts=2018-05-22T01:01:43.786801817Z caller=operator.go:1053 component=prometheusoperator msg="updating config skipped, no configuration change"
prometheus-operator-5d564c684d-4pncq prometheus-operator ts=2018-05-22T01:02:07.27549147Z caller=operator.go:338 component=alertmanageroperator msg="Alertmanager updated" key=monitoring/kube-prometheus
prometheus-operator-5d564c684d-4pncq prometheus-operator ts=2018-05-22T01:02:07.275571759Z caller=operator.go:394 component=alertmanageroperator msg="sync alertmanager" key=monitoring/kube-prometheus
prometheus-operator-5d564c684d-4pncq prometheus-operator ts=2018-05-22T01:03:05.001586831Z caller=operator.go:690 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus-prometheus
prometheus-operator-5d564c684d-4pncq prometheus-operator ts=2018-05-22T01:03:05.014554396Z caller=operator.go:1053 component=prometheusoperator msg="updating config skipped, no configuration change"
prometheus-operator-5d564c684d-4pncq prometheus-operator ts=2018-05-22T01:03:05.03473155Z caller=operator.go:690 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus-prometheus
prometheus-operator-5d564c684d-4pncq prometheus-operator ts=2018-05-22T01:03:05.04603426Z caller=operator.go:1053 component=prometheusoperator msg="updating config skipped, no configuration change"
prometheus-operator-5d564c684d-4pncq prometheus-operator ts=2018-05-22T01:03:13.275954014Z caller=operator.go:345 component=prometheusoperator msg="Prometheus updated" key=monitoring/kube-prometheus-prometheus
prometheus-operator-5d564c684d-4pncq prometheus-operator ts=2018-05-22T01:03:13.276020941Z caller=operator.go:690 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus-prometheus
prometheus-operator-5d564c684d-4pncq prometheus-operator ts=2018-05-22T01:03:13.289735221Z caller=operator.go:1053 component=prometheusoperator msg="updating config skipped, no configuration change"
prometheus-operator-5d564c684d-4pncq prometheus-operator ts=2018-05-22T01:03:35.845379941Z caller=operator.go:338 component=alertmanageroperator msg="Alertmanager updated" key=monitoring/kube-prometheus
prometheus-operator-5d564c684d-4pncq prometheus-operator ts=2018-05-22T01:03:35.845436124Z caller=operator.go:394 component=alertmanageroperator msg="sync alertmanager" key=monitoring/kube-prometheus

```

**Comment by gianrubio** [comment]
could you paste your prometheus object and the endpoints of the service?

**Comment by dgeorgievski** [comment]
### Prometheus object
kubectl -n monitoring  get prometheus kube-prometheus-prometheus -o yaml
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  clusterName: ""
  creationTimestamp: 2018-05-21T21:54:03Z
  generation: 0
  labels:
    app: prometheus
    chart: prometheus-0.0.38
    heritage: Tiller
    prometheus: kube-prometheus-prometheus
    release: kube-prometheus
  name: kube-prometheus-prometheus
  namespace: monitoring
  resourceVersion: "9275831"
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/prometheuses/kube-prometheus-prometheus
  uid: 79a9c91d-5d41-11e8-b1c0-0a16827fdf08
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app: prometheus
              prometheus: kube-prometheus
          topologyKey: kubernetes.io/hostname
        weight: 100
  alerting:
    alertmanagers:
    - name: kube-prometheus-alertmanager
      namespace: monitoring
      port: http
  baseImage: quay.io/prometheus/prometheus
  externalUrl: http://kube-prometheus-prometheus.monitoring:9090
  logLevel: info
  paused: false
  replicas: 1
  resources: {}
  retention: 24h
  routePrefix: /
  ruleSelector:
    matchLabels:
      prometheus: kube-prometheus
      role: alert-rules
  serviceAccountName: kube-prometheus-prometheus
  serviceMonitorSelector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - lei
      - alertmanager
      - exporter-coredns
      - exporter-kube-controller-manager
      - exporter-kube-dns
      - exporter-kube-etcd
      - exporter-kube-scheduler
      - exporter-kube-state
      - exporter-kubelets
      - exporter-kubernetes
      - exporter-node
      - grafana
      - prometheus
      - prometheus-operator
  version: v2.2.1
```

### Service being monitored
 kubectl describe svc lei-service
```
Name:              lei-service
Namespace:         mco
Labels:            app=lei
                   chart=lei-0.1.0
                   heritage=Tiller
                   release=rousing-moth
Annotations:       <none>
Selector:          app=lei,release=rousing-moth
Type:              ClusterIP
IP:                100.68.132.77
Port:              lei-service  8000/TCP
TargetPort:        8000/TCP
Endpoints:         100.100.0.23:8000,100.104.0.4:8000,100.106.0.7:8000
Port:              metrics  6080/TCP
TargetPort:        6080/TCP
Endpoints:         100.100.0.23:6080,100.104.0.4:6080,100.106.0.7:6080
Session Affinity:  None
Events:            <none>
```

### Test of /metrics endpoint
kubectl port-forward svc/lei-service 6080
curl http://localhost:6080/metrics
```
uwsgi_listen_queue_count{service=lei,uwsgi=2.0.14} 0 20180525141638
uwsgi_listen_queue_errors_count{service=lei,uwsgi=2.0.14} 0 20180525141638
uwsgi_signal_queue_count{service=lei,uwsgi=2.0.14} 0 20180525141638
uwsgi_load_count{service=lei,uwsgi=2.0.14} 0 20180525141638
....
```

**Comment by dgeorgievski** [comment]
In the meantime I had a chance to scrutinize the documentation of the operator and find a solution for my issue. For the benefit of the others the following is the outline of the resolution:
- Deploy ServiceMonitor in the **monitoring** namespace. Initially, by mistake, it was deployed in the same namespaces as the Service object.
- Use label _app: prometheus_ for the ServiceMonitor to include it in metrics scrapping.
   This one is interesting. I tried adding my condition under `serviceMonitorSelector` section, but that didn't work
First attempt causing all targets to disappear from Prometheus monitoring
```
 serviceMonitorSelector:
    serviceMonitorSelector:
       matchLabels:
            monitor: prometheus
    matchExpressions:
    - key: app
      operator: In
      values:
      - alertmanager
      - exporter-coredns
 ```

Second attempt to create another custom `matchExpressions` didn't work as well.
```
serviceMonitorSelector:
    matchExpressions:
     - key: monitor
      operator: In
      values:
      - prometheus
    - key: app
      operator: In
      values:
      - alertmanager
      - exporter-coredns
      - exporter-kube-controller-manager
```

Eventually I had to use one of the existing app labels recognized by the operator as a label for the ServiceMonitor
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus
  name: lei-service-monitor
  namespace: monitoring
```

This change finally made the new ServiceMonitor visible to the operator.
