### ISSUE TITLE
Add generic "Monitor" TPR for all Kubernetes objects

### ISSUE THREAD

**Issue by aerokite** [coreos/prometheus-operator#144]
We can have a single generic TPR "Monitor" to support all kubernetes objects. 

We can provide following information:

* Kubernetes Object Type 
* Kubernetes Object Name
* Kubernetes Namespace

Prometheus configuration will be updated to get metrics from these objects.

In this case, we do not need to provide labels. We can get metrics from multiple pods under different Kubernetes Object Types (like: ReplicationController, StatefulSet, ReplicaSet, Service etc.). 

Currently this can be done only if there is service behind these pods. 

Pods can be handled implementing [this issue](https://github.com/coreos/prometheus-operator/issues/38) too. 

But proposed approach will be more handy.

Example of generic  Monitor instance:

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: Monitor
metadata:
  labels:
    app: example
  name: example
spec:
  resource:
  - 
    type: statefulsets
    name: example-statefulset
    namespace: default
    endpoints:
    - interval: 30s
      port: web
  -
    type: services
    name: example-service
    namespace: kube-system
    endpoints:
    - interval: 60s
      port: db
```

Prometheus configuration will be updated to be monitor these two Kubernetes objects.

We can also set separate endpoints for each object.
