### ISSUE TITLE
Add documentation on using persistent storage and/or fix it

### ISSUE THREAD

**Issue by benmathews** [coreos/prometheus-operator#146]
The only documentation I can find on persistent storage is at https://github.com/coreos/prometheus-operator/blob/0e6ed120261f101e6f0dc9581de025f136508ada/Documentation/prometheus.md. My attempts at using the Prometheus operator w/ persistent storage have been unsuccessful. 

Based on what I understood, I created a PersistentVolume

```
kind: PersistentVolume
metadata:
  name: ceph.kube.prometheusdata
...
```

Then referenced it in a Prometheus object

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: prometheus-k8s
  labels:
    prometheus: k8s
spec:
  version: v1.3.0
storage:
  selector: ceph.kube.prometheusdata
```

Creating the prometheus-k8s object is successful and a pod is created, but it still uses the emptyDir volume. 

Am I doing something wrong? In which case, some better documents and examples would be great.
Or, is this not working as designed?

**Comment by brancz** [comment]
Your TPR seems a bit off, `storage` needs to be under `spec` and the `selector` is a [labelselector](https://kubernetes.io/docs/api-reference/v1/definitions/#_unversioned_labelselector). Generally you will want to be familiar with [`PersistentVolumeClaim`s](https://kubernetes.io/docs/user-guide/persistent-volumes/#persistentvolumeclaims), because that's how volumes are handled by the Prometheus Operator.

**Comment by benmathews** [comment]
Changing to 

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: prometheus-k8s
  labels:
    prometheus: k8s
spec:
  version: v1.3.0
  storage:
    selector: {
      "name" : "ceph.kube.prometheusdata"
    }
```

results in no prometheus-prometheus-k8s-0 pod being created. No error was returned on create though.

**Comment by brancz** [comment]
That's mixing yaml and json, I'm not sure why this was even accepted by the apiserver, but it should be

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: prometheus-k8s
  labels:
    prometheus: k8s
spec:
  version: v1.3.0
  storage:
    selector:
      name: "ceph.kube.prometheusdata"
```

My guess is that there should be some errors in the logs of the prometheus-operator. Unfortunately there is no way to perform validations on third party resources yet.

**Comment by fabxc** [comment]
JSON is a subset of YAML. This is a valid manifest.

**Comment by brancz** [comment]
Interesting, I wasn't aware that that allows mixing the two, I thought their data model is just compatible. Either way, it would be interesting to see whether the logs are saying something.

**Comment by gianrubio** [comment]
@benmathews I'm successfully running the storage class with this config

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: prometheus-k8s
  labels:
    prometheus: k8s
spec:
  version: v1.4.1
  retention: 360h
  storage:
      class: ssd
      resources:
        requests:
          storage: 40Gi
  resources:
    requests:
      memory: 2Gi
```

## Storage class
```
$ kubectl get storageclass -o yaml
apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1beta1
  kind: StorageClass
    name: ssd
  parameters:
    type: gp2
    zone: eu-west-1a
  provisioner: kubernetes.io/aws-ebs

```
