### ISSUE TITLE
Unable to view default prometheus consoles visualization

### ISSUE THREAD

**Issue by xinau** [coreos/prometheus-operator#1460]
**What did you do?**
Try to view the default [prometheus consoles](https://prometheus.io/docs/visualization/consoles/) in my browser. I did try:
- `<prometheus.url>/consoles/index.html.example`
- `<prometheus.url>/consoles/node.html`

**What did you expect to see?**
I expected to see dashboards as mentioned at [https://resin.io/blog](https://resin.io/blog/monitoring-linux-stats-with-prometheus-io/#scraping)

**What did you see instead? Under which circumstances?**
I saw a single line of text containing `open consoles/index.html.example: no such file or directory`
Then i tried to open `<prometheus.url>/consoles`, where i got this response `open consoles: no such file or directory`. So i assumed prometheus at least knows about the `consoles` directory. A quick debugging session in the pod showed me the following files and directories.
```console
$ kubectl exec -it -n monitoring prometheus-k8s-0 sh
Defaulting container name to prometheus.
Use 'kubectl describe pod/prometheus-k8s-0 -n monitoring' to see all of the containers in this pod.
/prometheus $ find / -name 'consoles'
/etc/prometheus/consoles
/usr/share/prometheus/consoles
find: /proc/tty/driver: Permission denied
/proc/consoles
/prometheus $ find / -name 'console_libraries'
/etc/prometheus/console_libraries
/usr/share/prometheus/console_libraries
find: /proc/tty/driver: Permission denied
/prometheus $ ls /etc/prometheus/consoles
index.html.example        node-cpu.html             node-disk.html            node-overview.html        node.html                 prometheus-overview.html  prometheus.html
/prometheus $ ls /usr/share/prometheus/consoles
index.html.example        node-cpu.html             node-disk.html            node-overview.html        node.html                 prometheus-overview.html  prometheus.html
/prometheus $ ls /etc/prometheus/console_libraries/
menu.lib  prom.lib
/prometheus $ ls /usr/share/prometheus/console_libraries/
menu.lib  prom.lib
```

**Environment**

Manifests:

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: prometheus
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpressions:
    - key: k8s-app
      operator: Exists
  version: v2.2.1
```
```yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: k8s
  name: prometheus-k8s
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
    app: prometheus
    prometheus: k8s
```
