### ISSUE TITLE
Remote Write "queue_config" Options Exposure

### ISSUE THREAD

**Issue by midnightconman** [coreos/prometheus-operator#1488]
Would it be possible to expose some of the `queue_config` knobs available for remote write in the `RemoteWriteSpec` object? We have a use case where we need to tweak these settings and we would like to use the prometheus-operator to do so.

- https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write

**Comment by brancz** [comment]
Thanks for opening this issue! Yes I think we should expose these options. Would you like to shoot us a PR to add these? :slightly_smiling_face:

**Comment by midnightconman** [comment]
Sure, let me see if I can get one out today. :D

**Comment by midnightconman** [comment]
Verified with the following prometheus remoteWrite config:
```
  remoteWrite:
    - url: http://prometheus/prometheus
      queueConfig:
        capacity: 1
        maxShards: 10000
        maxSamplesPerSend: 1000
        batchSendDeadline: 1s
        maxRetries: 1
        minBackoff: 10ms
        maxBackoff: 30ms
```
