### ISSUE TITLE
Helm does not update files based on the actual configmap values , similar to #833

### ISSUE THREAD

**Issue by airwolfnh** [coreos/prometheus-operator#1523]
**What did you do?**
In helm/kube-prometheus, I have created a values override file for kube-prometheus to add a custom rule using prometheusRules. I can see my rule under the rules tab, but when I change something on my values.yaml, I don't see my change being propagated. For instance, I changed the "for:10m" to "for:5m" , I can see my change on the Configmap kube-prometheus-rules, but not on the file inside the pod  prometheus-kube-prometheus-0 on /etc/prometheus/rules/monitoring-kube-prometheus-rules-test1a.yaml

Similarly deleting the rule or removing the prometheusRules config from my values file does not result in the removal of rule that was previously specified.

I have also tried to delete the pod and that did not worked.
I have also tried this in 2 other clusters and I have found the same behaviour. 

**What did you expect to see?**
I expected to see my changes after the configmap was updated.

**What did you see instead? Under which circumstances?**
No changes

** Environment 
```
    Image:         quay.io/prometheus/alertmanager:v0.14.0
    Image:         quay.io/coreos/configmap-reload:v0.0.1
    Image:          gcr.io/google_containers/kube-state-metrics:v1.2.0
    Image:         gcr.io/google_containers/addon-resizer:1.7
    Image:         quay.io/prometheus/node-exporter:v0.15.2
    Image:          grafana/grafana:5.0.0
    Image:         quay.io/coreos/grafana-watcher:v0.0.8
    Image:         quay.io/prometheus/prometheus:v2.2.1
    Image:         quay.io/coreos/prometheus-config-reloader:v0.20.0
    Image:         quay.io/coreos/configmap-reload:v0.0.1
    Image:         quay.io/coreos/prometheus-operator:v0.20.0
```

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
```
AKS
```
* Manifests:
```
prometheus:
    # default rules are in templates/general.rules.yaml
    prometheusRules:
      test1a: |-
        groups:
        - name: test1a.rules
          rules:
          - alert: test1alert
            expr: prometheus_config_last_reload_successful == 0
            for: 5m
            labels:
              severity: warning
            annotations:
              description: Something{{$labels.namespace}}/{{$labels.pod}}
              summary: Testing alerts.
```

* Prometheus Operator Logs:

insert Prometheus Operator logs relevant to the issue here
```
...
level=info ts=2018-06-25T15:00:53.014598909Z caller=operator.go:731 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
...
```

The logs are with the same content as above.
