### ISSUE TITLE
Set Namespace Label on ServiceMonitor

### ISSUE THREAD

**Issue by antoinne85** [coreos/prometheus-operator#1531]
**What did you do?**
I created a `ServiceMonitor` in the `monitoring` namespace with `honorLabels: true`. It is monitoring a `Service` in the `infrastructure` namespace. Additionally, my `/metrics` endpoint produces series like `queue_length{namespace=platinum, queue_name=some-queue-name}`. 

**What did you expect to see?**
After ingestion, `honorLabels` would have resulted in the `namespace` label to have the value `platinum` (the label applied to the metric).

**What did you see instead? Under which circumstances?**
After ingestion, the value of the `namespace` label was still `infrastructure` (the namespace where the `Service` being monitored is located).

**Environment**
* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: Azure AKS cluster

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: queue-monitor
  name: queue-monitor
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    port: http
  namespaceSelector:
    matchNames:
    - infrastructure
  selector:
    matchLabels:
      app: queue-monitor
      class: api
  targetLabels:
  - app
```

* Prometheus Operator Logs: _None relevant, I don't believe_

### Additional Information
I'm attempting to use a `HorizontalPodAutoscaler` to scale a `Deployment` based on custom metrics. I'm using the [k8s-prometheus-adapter](https://github.com/directXMan12/k8s-prometheus-adapter), which has some set-in-stone requirements about its label expectations, specifically regarding namespace. 

There's a high probability that this is simply a configuration issue on my end, but I'm having difficulty sorting out what the appropriate configuration is.

Because I'm running on `1.9.6` I'm attempting to use this as a workaround for External Metrics. (Even if I were on `1.10`, I'm not sure there's an adapter ready yet.) 

If someone could point me in the proper direction (or tell me that I'm just going about things entirely wrong), I would greatly appreciate it.
