### ISSUE TITLE
Disabling the K8SControllerManagerDown alert

### ISSUE THREAD

**Issue by jalateras** [coreos/prometheus-operator#1533]
**What did you do?**
I am running a K8 cluster on GKE where the control plane is managed by google. I have read the documentation but cannot see how to disable the alarm or the observations.  I tried setting the following the values files but that did not work at all.

```
exporter-kube-scheduler:
  prometheusRules:
   kube-scheduler.rules: |-
```
**What did you expect to see?**
I expected that the alert to not fire 

**What did you see instead? Under which circumstances?**
I see the alert is still firing

```
alert: K8SControllerManagerDown
expr: absent(up{job="kube-controller-manager"}
  == 1)
for: 5m
labels:
  severity: critical
annotations:
  description: There is no running K8S controller manager. Deployments and replication
    controllers are not making progress.
  runbook: https://coreos.com/tectonic/docs/latest/troubleshooting/controller-recovery.html#recovering-a-controller-manager
  summary: Controller manager is down
```

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.4-gke.0", GitCommit:"c08fe9548257472151a8fa298bd6c3e9ea1b8c09", GitTreeState:"clean", BuildDate:"2018-06-06T11:34:07Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 
Running on gks
	
* Manifests:

```
grafana:
  image:
    repository: grafana/grafana
    tag: 5.2.0-beta1
  adminUser: "xxxxx"
  adminPassword: "xxxxx"
  routePrefix: "/*"
  auth:
    anonymous:
      enabled: false
  service:
    type: NodePort    
  ingress:
    enabled: true
    hosts:
      - monitor.falabella.netwrk.co
    tls:
      - secretName: grafana-tls
        hosts:
          - monitor.falabella.netwrk.co

alertmanager:
  config:
    global:
      resolve_timeout: 5m
    receivers:
    - name: 'slack-snab'
      slack_configs:
      - api_url: 'xxxxx'
        text: "{{ range .Alerts }}{{ .Annotations.summary }} {{ .Annotations.description }}\n{{ end }}"
        channel: '#snab-support-staging'
    route:
      group_by:
      - job
      group_interval: 5m
      group_wait: 30s
      receiver: "slack-snab"
      repeat_interval: 12h
      routes:
      - match:
          alertname: DeadMansSwitch
        receiver: "slack-snab"

exporter-kubelets:
  https: false

exporter-kube-scheduler:
  prometheusRules:
    kube-scheduler.rules: |-

exporter-kube-controller-manager:
  prometheusRules:
    kube-controller-manager.rules: |-
```

* Prometheus Operator Logs:
