### ISSUE TITLE
Thanos with kube-prometheus can't access prometheus servers

### ISSUE THREAD

**Issue by argonmist** [coreos/prometheus-operator#1549]
**What did you do?**
I modify /prometheus-operator/contrib/kube-prometheus/manifests/prometheus-prometheus.yaml to enable Thanos sidecar :
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  podMetadata:
    labels:
      thanos-peer: 'true'
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpressions:
    - key: k8s-app
      operator: Exists
  version: v2.3.1
  thanos:
    peers: thanos-peers.default.svc:10900
    version: v0.1.0-rc.1
    baseImage: improbable/thanos
```
and follow the thanos example create thanos query deployment as following :
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  namespace: monitoring
  labels:
    app: thanos-query
    thanos-peer: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-query
      thanos-peer: "true"
  template:
    metadata:
      labels:
        app: thanos-query
        thanos-peer: "true"
    spec:
      containers:
      - name: thanos-query
        image: improbable/thanos:v0.1.0-rc.1
        args:
        - "query"
        - "--log.level=debug"
        - "--query.replica-label=prometheus_replica"
        - "--cluster.peers=thanos-peers.default.svc:10900"
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        - name: cluster
          containerPort: 10900
```
query service:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-query
  name: thanos-query
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: thanos-query
  ports:
  - port: 9090
    protocol: TCP
    targetPort: http
    name: http-query
```
thanos-peers-svc.yaml:
```
apiVersion: v1
kind: Service
metadata:
  name: thanos-peers
  namespace: monitoring
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: cluster
    port: 10900
    targetPort: cluster
  selector:
    thanos-peer: "true"
```
**What did you expect to see?**

Make Thanos query prometheus servers correctly

**What did you see instead? Under which circumstances?**

After all, I open thanos UI, no metric can be selected, it seems like thanos query can't access prometheus servers

**Environment**

* Kubernetes version information:

	insert output of `Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
` here

* Kubernetes cluster kind: 

kubeadm
