### ISSUE TITLE
Grafana error using persisten storage

### ISSUE THREAD

**Issue by jalberto** [coreos/prometheus-operator#1559]
kubernetes 1.10.3 with granafa 5.2.1 in AKS
on a clean kube-prometheus install

```
 GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
mkdir: cannot create directory '/var/lib/grafana/plugins': Permission denied 
```

My config:

```
grafana:
  image:
    tag: 5.2.1

  storageSpec:
    class: default
    accessMode: "ReadWriteOnce"
    resources:
      requests:
        storage: 2Gi
```

I guess related to url in error msg: http://docs.grafana.org/installation/docker/#user-id-changes

rel: #966 #541

**Comment by brancz** [comment]
#966 #541 are unrelated, they are about Prometheus and Alertmanager objects, which are managed by the Prometheus Operator, the Grafana deployment is completely unmanaged. It's a simple deployment. You need to mount some writable storage into that Grafana container (a simple emptydir would work already).

Are you trying to install this via helm?

**Comment by jalberto** [comment]
@brancz I am using kube-prometheus helm to deploy grafana, it use grafana helm hosted by prometheus operator, for that reason I related those issues too.

kube-prometheus uses by default grafana 5.0, while latest version is 5.2 and that is where the userID change happened. I though it will not be affected as it was a clean deployment.

Also, emptydir is great, but I will like to persist my custom dashboards between deployments.

**Comment by brancz** [comment]
> Also, emptydir is great, but I will like to persist my custom dashboards between deployments. I don't see grafana as a stateless service, it needs lot of state persistence to be useful

I disagree with this, but I do think that the helm chart should allow configuring persistent storage, however the kube-prometheus stack was designed with a completely stateless Grafana, so this may be a more involved effort.

**Comment by jalberto** [comment]
but using grafan in a stateless way also means, even the simplest change
like selecting the default dashboard or ideal time period, will be lost in
next deploy

**Comment by brancz** [comment]
Right but if those are things that you want to do (we run Grafana even without users and just do authentication via the oauth proxy so there is 0 state in Grafana for us) then you should rather make Grafana use an external database than make Grafana itself stateful. Apart from that the Grafana folks are putting a lot of great work into their provisioning features so a local Grafana database can be populated with things from disk at startup, that covers all use cases we have for a database connected to Grafana without having to run a database :slightly_smiling_face: .

**Comment by jalberto** [comment]
you are right!, just a missunderstanding as for me an external DB also
counts as "stateful" :)

**Comment by jalberto** [comment]
@brancz are you using PG as grafana storage?

When I use PG as DB type in grafana config, each time grafana is deployed (for example on upgrading) every custom dashboard is lost

**Comment by brancz** [comment]
No we don’t even use a backing database :)

**Comment by den-is** [comment]
+1 here

```
grafana:
  image:
    tag: 5.2.3
  storageSpec:
     class: cephdev
     accessMode: ReadWriteOnce
     resources:
       requests:
         storage: 2Gi
     selector: {}
```

**Comment by sc250024** [comment]
@brancz I'm having the same issue as @jalberto, which is that we're both installing the `kube-prometheus` chart from scratch, and still running into the permissions issue with Grafana itself. Reading through the issue, I totally agree with you that Grafana should be stateless, and all config stored in revision control.

For this issue though, since Grafana changed the UID / GID of their user in newer versions, I think the Grafana chart should be updated, right?

**Comment by brancz** [comment]
> For this issue though, since Grafana changed the UID / GID of their user in newer versions, I think the Grafana chart should be updated, right?

Correct, the charts are outdated from the jsonnet stack, which is essentially the upstream. The helm stack is currently being migrated to the upstream charts to be moved outside of this repository. @gianrubio is working on this.

**Comment by sc250024** [comment]
Ah ok, perfect. Thanks for the quick reply, and to @gianrubio for the updating.

**Comment by emzfuu** [comment]
im currently experiencing this GF_PATHS_DATA='/var/lib/grafana' is not writable in kubernete.
i already added the 472 permission but still get the error. here is my yaml file 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-ewan
  namespace: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      securityContext:
            runAsUser: 472
            fsGroup: 472
      containers:
      - name: grafana
        # command: ['sh', '-c', 'chown -R 472:472 /var/lib/grafana']
        image: grafana/grafana:5.4.2
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
      volumes:
        - name: grafana-storage
          hostPath:
                  path: /home/ec2-user
                  type: Directory
          #persistentVolumeClaim:
          #        claimName: allow
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources
      nodeSelector:
               node: host1

**Comment by paulfantom** [comment]
Prometheus-operator is not shipping grafana nor any other grafana installation mechanisms are present in this repository. If you encountered any issues with grafana installation please open issue in a project responsible for it (ex. helm chart or kube-prometheus).

**Comment by cucker0** [comment]
In kube-prometheus-0.10.0

## I update the manifests/grafana-deployment.yaml file line 132 to 136 like this,
```yaml
...
      securityContext:
        runAsGroup: 0
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 472
...
```

## Add a job to change the owner of the PVC mount directory
cat ./grafana-chown-job.yaml
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-chown
  namespace: monitoring
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: grafana-chown
        command: ["chown", "-R", "472:0", "/var/lib/grafana"]
        image: busybox
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: storage
          # subPath: grafana
          mountPath: /var/lib/grafana
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: grafana-storage-claim
```

```bash
kubectl apply -f ./grafana-chown-job.yaml
```

##  Delete the Pod of grafana
```bash
kubectl -n monitoring pods grafana-xxxxxxxxxx-xxxxx
```
