### ISSUE TITLE
Data backup via thanos s3 api is not working

### ISSUE THREAD

**Issue by argonmist** [coreos/prometheus-operator#1563]
**What did you do?**
I deploy a aio ceph enviroment, and make sure I can upload files via s3 api, then I modify /prometheus-operator/contrib/kube-prometheus/manifests/prometheus-prometheus.yaml to enable thanos s3 data backup, but the prometheus-0 pod no show by command: kubectl get po -n monitoring
```
NAME                                   READY     STATUS    RESTARTS   AGE
alertmanager-main-0                    2/2       Running   0          3d
alertmanager-main-1                    2/2       Running   0          3d
alertmanager-main-2                    2/2       Running   0          3d
grafana-6c5d4c5b66-c8gnz               1/1       Running   0          3d
kube-state-metrics-7564964b9f-cg6bl    4/4       Running   0          3d
node-exporter-9k5bz                    2/2       Running   0          3d
node-exporter-fwjc9                    2/2       Running   0          3d
node-exporter-q58zp                    2/2       Running   0          3d
node-exporter-z6b4c                    2/2       Running   0          3d
prometheus-operator-6bb868644b-npmmp   1/1       Running   0          3d
thanos-query-6f8b699bd8-95xxw          1/1       Running   0          3d
```
Here is my prometheus-prometheus.yaml
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  podMetadata:
    labels:
      thanos-peer: 'true'
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpressions:
    - key: k8s-app
      operator: Exists
  version: v2.3.1
  thanos:
    peers: thanos-peers.default.svc:10900
    s3:
      bucket: files
      endpoint: http://172.16.35.100:8080
      accessKey:
        key: <redacted>
      secretKey:
        key: <redacted>
      insecure: true
```

**What did you expect to see?**
Prometheus pods running correctly, and backup prometheus data by using s3 api

**Environment**

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
kubeadm

**Comment by brancz** [comment]
Even though this might be in your environment, just out of security I redacted your keys.

The way the `accessKey` and `secretKey` fields work is that they are a pointer to a "key" within a Kubernetes Secret. So what you are looking for is something like this:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  podMetadata:
    labels:
      thanos-peer: 'true'
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpressions:
    - key: k8s-app
      operator: Exists
  version: v2.3.1
  thanos:
    peers: thanos-peers.default.svc:10900
    s3:
      bucket: files
      endpoint: http://172.16.35.100:8080
      accessKey:
        name: "thanos-s3-credentials"
        key: "s3AccessKey"
      secretKey:
        name: "thanos-s3-credentials"
        key: "s3SecretKey"
      insecure: true
```

Meaning you will also need a Kubernetes `Secret` that is called `thanos-s3-credentials` that has the `s3AccessKey` and `s3SecretKey` keys.
