### ISSUE TITLE
Want to setup persistent storage for Prometheus  

### ISSUE THREAD

**Issue by subinmt** [coreos/prometheus-operator#1567]
**What did you do?**
Followed the manifest for deploying the Prometheus on Kubernetes.
**What did you expect to see?**
Please let me know How can I setup persistent storage for Prometheus. My intention is to keep the Promethues  data safe.
**What did you see instead? Under which circumstances?**

**Environment**
Kubernetes
* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
We have a [user guide on storage](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/storage.md).

I will close this issue, but should you run into any issues with this document feel free to keep commenting or open a new issue if you think the documentation is wrong or you think there might be a problem with the Prometheus Operator! :slightly_smiling_face:

**Comment by manuprometheus** [comment]
Hi brancz, I am sorry for reopening a closed Issue. But I need a small help. I have followed the guide you provided but got some error. I got the error "Failed to provision volume with StorageClass "standard": claim.Spec.Selector is not supported for dynamic provisioning on GCE". I understand this issue is already reported and fixed. But in my case, I would like to know where the storage class "StorageClass "standard" is specified in the yaml, Since my SC "standard" is already used. I want to use another Storage class. Can I specify this in yaml?

**Comment by manuprometheus** [comment]
Sorry, I got it. Thanks

**Comment by andrewsav-datacom** [comment]
@brancz is it possible to use an existing PVC (as opposed to PV) to configure persistent storage?

**Comment by brancz** [comment]
@andrewsav-datacom no, as we use the volumeClaimTemplate feature of the StatefulSet for this.

**Comment by akshayrathod2** [comment]
> We have a [user guide on storage](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/storage.md).
> 
> I will close this issue, but should you run into any issues with this document feel free to keep commenting or open a new issue if you think the documentation is wrong or you think there might be a problem with the Prometheus Operator! 🙂

Hey this link you mentioned is not working. Can you please provide some document on setting up prometheus with persistent storage. My issue right now is each time I delete my pod I loose all my data.

**Comment by metalmatze** [comment]
@akshayrathod2, can you elaborate a bit about what you have done and tried? That would be helpful.

**Comment by romanvog** [comment]
@metalmatze ,

I've updated the following in prometheusCustomResourceDefinition:

```
                        devicePath:
                          description: devicePath is the path inside of the container
                            that the device will be mapped to.
                          type: /prometheus
                        name:
                          description: name must match the name of a persistentVolumeClaim
                            in the pod
                          type: prometheus-pvc

                        mountPath:
                          description: Path within the container at which the volume
                            should be mounted.  Must not contain ':'.
                          type: /prometheus

                        name:
                          description: This must match the Name of a Volume.
                          type: prometheus-pvc

                        volumeName:
                          description: VolumeName is the binding reference to the
                            PersistentVolume backing this claim.
                          type: prometheus-pvc

                        accessModes:
                          description: 'AccessModes contains the actual access modes
                            the volume backing the PVC has. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1'
                          items:
                            type: "RWM"
                          type: array
                        capacity:
                          description: Represents the actual resources of the underlying
                            volume.
                          type: "250Gi"
```


pvc was created, but it doesn't include the capacity and access modes that I've specified. In addition, it's not used by prometheus-k8s pods.

```
k describe pv pvc-7f988c90-6693-11e9-b9e9-021e740f96d0  
Name:            pvc-7f988c90-6693-11e9-b9e9-021e740f96d0
Labels:          failure-domain.beta.kubernetes.io/region=us-west-2
                 failure-domain.beta.kubernetes.io/zone=us-west-2b
Annotations:     kubernetes.io/createdby=aws-ebs-dynamic-provisioner
                 pv.kubernetes.io/bound-by-controller=yes
                 pv.kubernetes.io/provisioned-by=kubernetes.io/aws-ebs
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    gp2
Status:          Bound
Claim:           monitoring/prometheus-pvc
Reclaim Policy:  Delete
Access Modes:    RWO
Capacity:        124Gi
Node Affinity:   <none>
Message:         
Source:
    Type:       AWSElasticBlockStore (a Persistent Disk resource in AWS)
    VolumeID:   aws://us-west-2b/vol-0dfa96aa7d3c7836f
    FSType:     ext4
    Partition:  0
    ReadOnly:   false
Events:         <none>
```

Can't figure out what is missing, and having a guide on setting up a persistent storage for prometheus would be helpful.
