### ISSUE TITLE
Basic auth fails due to introduction of newline

### ISSUE THREAD

**Issue by gokart23** [coreos/prometheus-operator#1568]
**What did you do?**
I was working on deploying a ServiceMonitor for an endpoint which required authentication. The configuration was along the lines of:
```
apiVersion: v1
kind: Secret
metadata:
  name: endpoint-creds
  namespace: monitoring
data:
  username: 'dXNlcm5hbWUK' # username
  apitoken: 'cGFzc3dvcmQK' # password
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: svcmon
  name: svcmon
  namespace: monitoring
spec:
  endpoints:
  - port: access
    path: '/endpoint'
    params:
      format: 
      - prometheus
    interval: '30s'
    basicAuth:
      username: 
        name: endpoint-creds
        key: username
      password:
        name: endpoint-creds
        key: apitoken
  namespaceSelector:
    matchNames:
      - ns-service
  selector:
    matchLabels:
        app: rbin-service
```
I also tried setting up the secret with yaml block stripping, but observed the same results.

**What did you expect to see?**
I expected prometheus to collect metrics by polling the endpoint using the provided credentials

**What did you see instead? Under which circumstances?**
The endpoint repeatedly returned 401 (Unauthorized) status code. On inspecting the object registered with prometheus, I found that the username and password were successfully being extracted:
```
$ kubectl get secret prometheus-k8s -n monitoring -ojson | jq -r '.data["prometheus.yaml"]' | base64 -d | grep svcmon -A 20
- job_name: monitoring/svcmon/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - ns-service
  scrape_interval: 30s
  metrics_path: /endpoint
  params:
    format:
    - prometheus
  basic_auth:
    username: |
      username
    password: |
      password
...
```
On inspecting the actual request headers being received by the endpoint, I observed that the auth header contained a newline between the username and password:
```
Authorization: Basic dXNlcm5hbWUKOnBhc3N3b3JkCg==
```
the credentials of which decode to:
```
username
:password
```

**Environment**

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
* Prometheus operator version
```
prometheus-operator:v0.19.0
```
* Kubernetes cluster kind: kubeadm

* Prometheus Operator Logs: Operator logs do not reflect anything out of the ordinary
