### ISSUE TITLE
Service Monitor - empty namespaceSelector (any: true) only uses default namespace

### ISSUE THREAD

**Issue by aranair** [coreos/prometheus-operator#1593]
**What did you do?**

I have pods running in default namespace AND custom namespaces. 

Created a ServiceMonitor for all namespaces. (manifests below)

**What did you expect to see?**

Expected all of them to show up in Prometheus targets.

**What did you see instead? Under which circumstances?**

Only the ones in `default` namespace are showing up.

If i pin the `namespaceSelector` down, those targets show up properly.

```
namespaceSelector
  matchNames:
    - xxx
```

**Environment**

prometheus-0.0.38

* Kubernetes version information:

1.8.7

* Kubernetes cluster kind: 

kops

* Manifests:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus
    chart: prometheus-0.0.38
    heritage: Tiller
    prometheus: ...
    release: ...
  name: ...
  namespace: monitoring
spec:
    ...
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: factory
```

* Prometheus Operator Logs:

Not relevant I believe.
