### ISSUE TITLE
update to v0.22.0: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.

### ISSUE THREAD

**Issue by r0bj** [coreos/prometheus-operator#1602]
**What did you do?**

Update prometheus-operator version from 0.21.0 to 0.22.0.

**What did you expect to see?**

prometheus-operator works and doesn't log errors

**What did you see instead? Under which circumstances?**

prometheus-operator log errors after update:
```
ts=2018-07-10T14:28:52.946172806Z caller=main.go:115 msg="Starting Prometheus Operator version '0.22.0'."
level=info ts=2018-07-10T14:28:53.06458421Z caller=operator.go:293 component=prometheusoperator msg="connection established" cluster-version=v1.10.5
level=info ts=2018-07-10T14:28:53.065586765Z caller=operator.go:172 component=alertmanageroperator msg="connection established" cluster-version=v1.10.5
level=info ts=2018-07-10T14:28:53.651032595Z caller=operator.go:560 component=alertmanageroperator msg="CRD updated" crd=Alertmanager
level=info ts=2018-07-10T14:28:53.799728545Z caller=operator.go:1140 component=prometheusoperator msg="CRD updated" crd=Prometheus
level=info ts=2018-07-10T14:28:53.860727161Z caller=operator.go:1140 component=prometheusoperator msg="CRD updated" crd=ServiceMonitor
level=info ts=2018-07-10T14:28:53.881357556Z caller=operator.go:1140 component=prometheusoperator msg="CRD updated" crd=PrometheusRule
level=info ts=2018-07-10T14:28:56.671310977Z caller=operator.go:186 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2018-07-10T14:28:56.749566071Z caller=operator.go:396 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
E0710 14:28:56.846066       1 operator.go:272] Sync "monitoring/main" failed: updating statefulset failed: StatefulSet.apps "alertmanager-main" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.
level=info ts=2018-07-10T14:28:56.948586107Z caller=operator.go:396 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
E0710 14:28:56.971821       1 operator.go:272] Sync "monitoring/main" failed: updating statefulset failed: StatefulSet.apps "alertmanager-main" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.
level=info ts=2018-07-10T14:28:56.971895007Z caller=operator.go:396 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
E0710 14:28:56.985815       1 operator.go:272] Sync "monitoring/main" failed: updating statefulset failed: StatefulSet.apps "alertmanager-main" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.
```
[...]
```
E0710 14:29:04.774183       1 operator.go:646] Sync "monitoring/k8s" failed: updating statefulset failed: StatefulSet.apps "prometheus-k8s" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.
```

**Environment**

* Kubernetes version information:

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

K8s cluster build in-house.

* Manifests:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: prometheus-operator
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
    spec:
      serviceAccountName: prometheus-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
      - name: prometheus-operator
        image: quay.io/coreos/prometheus-operator:v0.21.0
        args:
        - --kubelet-service=kube-system/kubelet
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.21.0
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
```
```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: main
  labels:
    alertmanager: main
  namespace: monitoring
spec:
  replicas: 3
  version: v0.15.0
  externalUrl: http://alertmanager.example.com
  storage:
    volumeClaimTemplate:
      metadata:
        name: alertmanager-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
```
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  labels:
    app: prometheus
    prometheus: k8s
  namespace: monitoring
spec:
  replicas: 2
  version: v2.3.1
  externalUrl: http://prometheus.example.com
  externalLabels:
    prometheus_cluster: prometheus-k8s
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpressions:
    - key: k8s-app
      operator: Exists
  ruleSelector:
    matchLabels:
      role: alert-rules
      prometheus: k8s
  resources:
    limits:
      memory: 12Gi
    requests:
      memory: 12Gi
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-main
      port: web
  secrets:
  - etcd-certs
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: prometheus
            operator: In
            values:
            - k8s
        topologyKey: kubernetes.io/hostname
  retention: 3d
  storage:
    volumeClaimTemplate:
      metadata:
        name: prometheus-k8s-data
      spec:
        storageClassName: local-disks
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
```
