### ISSUE TITLE
how to use labels parameter in /bin/operator

### ISSUE THREAD

**Issue by fumanne** [coreos/prometheus-operator#1614]
**What did you do?**
use -labels option  with /bin/operator 

**What did you expect to see?**
add customs labels into labels

**Environment**
prometheus-operator version: v0.18.0
kubernetes: v1.9

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

In my prometheus-operator deployment.yml look like this:
```
containers:
        - name: {{ template "prometheus-operator.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          args:
          {{- if .Values.kubeletService.enable }}
            - --kubelet-service={{ .Values.kubeletService.namespace }}/{{ .Values.kubeletService.name }}
          {{- end }}
            - --prometheus-config-reloader={{ .Values.prometheusConfigReloader.repository }}:{{ .Values.prometheusConfigReloader.tag }}
            - --config-reloader-image={{ .Values.configmapReload.repository }}:{{ .Values.configmapReload.tag }}
            - --labels cluster=mon
```
I add - --labels cluster=mon
but is show the following error log

* Prometheus Operator Logs:

```
Sync "monitoring/mon-prometheus" failed: synchronizing governing service failed: updating service object failed: Service "prometheus-operated" is invalid: [metadata.labels: Invalid value: "\"cluster": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), metadata.labels: Invalid value: "mon\"": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]
```
so what is the correct syntax??
