### ISSUE TITLE
[helm/kuber-prometheus] Can't control nodeSelector for all services

### ISSUE THREAD

**Issue by ozbillwang** [coreos/prometheus-operator#1617]
**What did you do?**

I need use helm to deploy prometheus operator and kube-prometheus and nominate nodeSelector (for example, function=monitoring).

Since there are more dependency services under `kuber-prometheus` (https://github.com/coreos/prometheus-operator/blob/master/helm/kube-prometheus/requirements.yaml), the key `nodeSelector` are not set for all within default values.yaml

**What did you expect to see?**

all services running in nominated nodeSelector.

**What did you see instead? Under which circumstances?**

It is deployed to all workers. 

**Environment**

AWS EKS (should be same for others)

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

```
$ kk version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:13:43Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

I run with own `values.yaml` , but it doesn't work

```
alertmanager:
  nodeSelector:
    function: monitoring

prometheus:
  nodeSelector:
    function: monitoring

exporter-coredns:
  nodeSelector:
    function: monitoring

exporter-kube-controller-manager:
  nodeSelector:
    function: monitoring

exporter-kube-dns:
  nodeSelector:
    function: monitoring

exporter-kube-etcd:
  nodeSelector:
    function: monitoring

exporter-kube-scheduler:
  nodeSelector:
    function: monitoring

exporter-kube-state:
  nodeSelector:
    function: monitoring

exporter-kubelets:
  nodeSelector:
    function: monitoring

exporter-kubernetes:
  nodeSelector:
    function: monitoring

exporter-node:
  nodeSelector:
    function: monitoring

grafana:
  nodeSelector:
    function: monitoring
```
