### ISSUE TITLE
Inconsistent job labels between prometheus-operator and exporter rules

### ISSUE THREAD

**Issue by kevtaylor** [coreos/prometheus-operator#1643]
**What did you do?**
Installed all helm charts

**What did you expect to see?**
The rules for exporter-kube-controller to be consistent in the prometheus operator configmap

**What did you see instead? Under which circumstances?**
An inconsistent naming convention of the job

**Environment**
AWS / Coreos 1745.7.0

* Kubernetes version information:

	insert output of `kubectl version` here
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.
kube-aws

* Manifests:

In the helm chart for exporter-kube-controller-manager, the servicemonitor.yaml says:
`jobLabel: component` which gives it a job=kube-controller-manager

And the corresponding rules in `kube-controller-manager.rules.yaml` is
`expr: absent(up{job="kube-controller-manager"} == 1)`

However, when the prometheus-operator builds `prometheus-mantle-prometheus-rulefiles`
where `mantle` is the helm release name, it alters the rules inside the configmap to read
`expr: absent(up{job="mantle-exporter-kube-controller-manager"} == 1)` and therefore fires
this alert

**Comment by kevtaylor** [comment]
Bit more detail:
These are the configmaps created
```
mantle-alertmanager                       1         20m
mantle-exporter-kube-controller-manager   1         20m
mantle-exporter-kube-etcd                 1         20m
mantle-exporter-kube-scheduler            1         20m
mantle-exporter-kube-state                1         20m
mantle-exporter-kubelets                  1         20m
mantle-exporter-kubernetes                1         20m
mantle-exporter-node                      1         20m
mantle-grafana                            10        20m
mantle-kube-prometheus                    1         20m
mantle-nginx-ingress-controller           6         20m
mantle-prometheus-rules                   1         20m
mantle.v1                                 1         20m
prometheus-mantle-prometheus-rulefiles    12        20m
prometheus-mantle-rules                   1         20m
```

And the servicemonitors
```
mantle-alertmanager                       32m
mantle-exporter-kube-controller-manager   32m
mantle-exporter-kube-dns                  32m
mantle-exporter-kube-etcd                 32m
mantle-exporter-kube-scheduler            32m
mantle-exporter-kube-state                32m
mantle-exporter-kubelets                  32m
mantle-exporter-kubernetes                32m
mantle-exporter-node                      32m
mantle-grafana                            32m
mantle-prometheus                         32m
```
The labels from the controller
```
labels:
    app: exporter-kube-controller-manager
    chart: exporter-kube-controller-manager-0.1.9
    component: kube-controller-manager
    heritage: Tiller
    prometheus: mantle
    release: mantle
```
And the controller config map
```
apiVersion: v1
data:
  kube-controller-manager.rules: |-
    groups:
    - name: kube-controller-manager.rules
      rules:
      - alert: K8SControllerManagerDown
        expr: absent(up{job="kube-controller-manager"} == 1)
        for: 5m
        labels:
          severity: critical
        annotations:
          description: There is no running K8S controller manager. Deployments and replication
            controllers are not making progress.
          runbook: https://coreos.com/tectonic/docs/latest/troubleshooting/controller-recovery.html#recovering-a-controller-manager
          summary: Controller manager is down
kind: ConfigMap
metadata:
  creationTimestamp: 2018-07-20T07:32:23Z
  labels:
    app: prometheus
    chart: exporter-kube-controller-manager-0.1.9
    heritage: Tiller
    prometheus: mantle
    release: mantle
    role: alert-rules
  name: mantle-exporter-kube-controller-manager
  namespace: mantle
  resourceVersion: "40565607"
  selfLink: /api/v1/namespaces/mantle/configmaps/mantle-exporter-kube-controller-manager
  uid: 0b390565-8bef-11e8-9700-0670e5e01e6e
```
And the full definition from the operator
```
 mantle-mantle-exporter-kube-controller-manager-kube-controller-manager.rules.yaml: |
    groups:
    - name: kube-controller-manager.rules
      rules:
      - alert: K8SControllerManagerDown
        annotations:
          description: There is no running K8S controller manager. Deployments and replication
            controllers are not making progress.
          runbook: https://coreos.com/tectonic/docs/latest/troubleshooting/controller-recovery.html#recovering-a-controller-manager
          summary: Controller manager is down
        expr: absent(up{job="mantle-exporter-kube-controller-manager"} == 1)
        for: 5m
        labels:
          severity: critical
```
