### ISSUE TITLE
alertmanager unable to send alerts via email_configs

### ISSUE THREAD

**Issue by ohmanandam** [coreos/prometheus-operator#1660]
**What did you do?**
I added a new receiver and edited the default receiver in kube-promethes values.yaml

```
 config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 30s
      repeat_interval: 30s
      receiver: 'email-receiver'
      #receiver: 'null'
      #routes:
      #- match:
          #alertname: DeadMansSwitch
        #receiver: 'email-receiver'
        #receiver: 'null'
    receivers:
    - name: email-receiver
      email_configs:
      - to: 'hello@flockgroups.com'
        from: 'abc@gmail.com'
        smarthost: smtp.gmail.com:587
        auth_username: "abc@gmail.com"
        auth_identity: "abc@gmail.com"
        auth_password: "***$"
        send_resolved: true
    - name: 'null'
```

**What did you expect to see?**
I expected to see the alerts routed via new email_configs. The above changed email_configs works in a stand alone alertmanager mode.

**What did you see instead? Under which circumstances?**
The alert manager is unable to send the alerts.

level=error ts=2018-07-22T13:54:59.652339422Z caller=notify.go:303 component=dispatcher msg="Error on notify" err="dial tcp: lookup smtp.gmail.com on 10.96.0.10:53: read udp 172.17.0.10:38143->10.96.0.10:53: i/o timeout"
level=error ts=2018-07-22T13:54:59.652367357Z caller=dispatch.go:266 component=dispatcher msg="Notify for alerts failed" num_alerts=2 err="dial tcp: lookup smtp.gmail.com on 10.96.0.10:53: read udp 172.17.0.10:38143->10.96.0.10:53: i/o timeout"

**Environment**
Prometheus Operator downloaded from master on 7/9/2018

helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

* Prometheus Operator version:

	insert image tag or Git SHA here

* Kubernetes version information:

	insert output of kubectl version here
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	minikube
* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by Paxa** [comment]
May be firewall blocking outgoing connection?

I use it with mailgun.com and it works great:
```yaml
global:
  smtp_smarthost: smtp.mailgun.org:587
  smtp_from: alerts@my-host
  smtp_auth_username: xxx@myapp.mailgun.org
  smtp_auth_password: yyy
```
