### ISSUE TITLE
Why service in custom namespace is not being detected?

### ISSUE THREAD

**Issue by manuprometheus** [coreos/prometheus-operator#1690]
**What did you do?**
Created service monitor,service account for an application in a custom metrics. But the same is not being detected by prometheus
**What did you expect to see?**
Need to detect the application by Prometheus target. When I deploy the app in default name space or in the  namespace where the whole Prometheus is deployed,then it is working.
**What did you see instead? Under which circumstances?**
The Target in custom namespace is not being detected.
**Environment**
Kubernetes
* Prometheus Operator version:

	insert image tag or Git SHA here

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
Can you see configuration for your `ServiceMonitor` in `/config` of the Prometheus UI? Could also you check the Prometheus logs, this might just be an RBAC permission issue.

**Comment by manuprometheus** [comment]
Sure. Let me check.

**Comment by manuprometheus** [comment]
My Prometheus /config is not showing the confguration for my custom namespace. I have created the service monitor and service account. Is there any other configuration is needed to setup?

**Comment by brancz** [comment]
That means that the Prometheus object is not selecting your `ServiceMonitor`. Can you share the `serviceMonitorSelector` and `serviceMonitorNamespaceSelector` of your Prometheus object as well as the labels on the `ServiceMonitor` you are intending to select?

**Comment by manuprometheus** [comment]
Please find my ServiceMonitor as follows:

--------------------------
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
     labels:
        k8s-app: my-app
     name: my-app
     namespace: mynamespace
spec:
    endpoints:
    - interval: 5s
      port: prometheus
    namespaceSelector:
         matchNames:
         - mynamespace
    selector:
        matchLabels:
             k8s-app: my-app
--------------------------
Also my Serviceaccount is as follow:
-------------------------------
apiVersion: v1
kind: ServiceAccount
metadata:
      name:  my-app
      namespace: mynamespace
---------------------------------

Service yaml
--------------------------
apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: mynamespace
  labels:
    k8s-app: my-app
    
spec:
  ports:
  - name: prometheus
    port: 2181
    protocol: TCP
  selector:
      k8s-app: my-app
------------------------

**Comment by brancz** [comment]
You need to use three back-ticks around the code/yaml to render it as code.

```
start --> ```
end --> ```
```

Could you also share your Prometheus object?

**Comment by manuprometheus** [comment]
Thank you for the reply. Please find my Prometheus object yaml as follows:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      port: web
  baseImage: quay.io/prometheus/prometheus
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpressions:
    - key: k8s-app
      operator: Exists
  namespaceSelector:
    matchNames: 
    -  mynamespace
  version: v2.3.1
```
