### ISSUE TITLE
Kube-Prometheus config file via helm chart

### ISSUE THREAD

**Issue by weeco** [coreos/prometheus-operator#1713]
I am using the helm charts to deploy kube-prometheus. I'd like to scrape all pods in my cluster if they have the following pod annotations added:

```yaml
    prometheus.io/scrape: true
    prometheus.io/port: 8080
    prometheus.io/path: /metrics
```

As far as I got I need to add a kubernetes_sd_config to achieve this, which would look similiar to this:

```yaml
- job_name: 'kubernetes-pods'
  kubernetes_sd_configs:
    - role: pod
  relabel_configs:
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: (.+):(?:\d+);(\d+)
      replacement: ${1}:${2}
      target_label: __address__
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name
```

**My question:**

How can I set this config via your helm chart? Unfortunately the documentation is in lack of examples for the configuration part for the helm chart, see https://github.com/coreos/prometheus-operator/blob/master/helm/kube-prometheus/values.yaml#L183

An example with above configuration is highly appreciated.
