### ISSUE TITLE
Add NodeMonitor TPR to enable scraping kubelets

### ISSUE THREAD

**Issue by whereisaaron** [coreos/prometheus-operator#173]
[ServiceMonitor](https://github.com/coreos/prometheus-operator/blob/master/Documentation/service-monitor.md) can be used to scrape any Services (or Pods/Deployments/Daemonsets by creating  a Service to find their endpoints). This enables all the targets monitored by the [custom config](https://github.com/coreos/kube-prometheus/blob/master/assets/prometheus/prometheus.yaml) used by 'kube-prometheus' to be [configured using Prometheus Operator](https://github.com/whereisaaron/kubernetes-prometheus-operator-deployment/tree/master/prometheus-operator-config) *except for one*. AFAIK, the kubelets cannot be [discovered](https://github.com/prometheus/prometheus/blob/master/discovery/kubernetes/kubernetes.go#L204-L215) and scraped because they require a `scrape_configs` entry with `kubernetes_sd_configs: { "role": "node" }` and ServiceMonitor only supports `kubernetes_sd_configs: { "role": "endpoints" }`.

One option with be to add a 'NodeMonitor' ThirdPartyResource which has only the `jobLabel`, `interval`, `scheme`, `tlsConfig`, and `bearerToken` keys of ServiceMonitor. If such a resource is created in the same namespace as Prometheus Operator, the prometheus config would be updated to include a `scape_configs` entry something like:

```
- job_name: prometheus/kubelets/0
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  kubernetes_sd_configs:
  - role: node
```
