### ISSUE TITLE
Support for raw PersistentVolumeClaims or way to handle NFS in Prometheus TPR

### ISSUE THREAD

**Issue by rrix** [coreos/prometheus-operator#175]
**What did you do?**

Brought up a two-node kubernetes cluster on bare-metal, as a home infrastructure lab.

One node, the kubes master, has a bunch of docker containers with manually scheduled, including a prometheus with a volume mounted on the host's raw disk. This same disk is exported via NFS. I would like to replace that manually scheduled prom with a setup orchestrated by prometheus-operator.

I have my NFS specified thusly:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.100
    path: /srv/files/files
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    pv-name: nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
        storage: 1Mi
```

I would like to be able to access this within prom-operator, but I cannot figure out how to do so. 

**What did you expect to see?**

Some documentation on how to mount non-dynamically generated persistent volumes like NFS or hostPath.

**What did you see instead? Under which circumstances?**

It appears from [documentation](https://github.com/coreos/prometheus-operator/blob/master/Documentation/prometheus.md) that it supports only storageclasses, unless I am misreading this; I can't figure out how to build a spec that will create a PVC for my nfs.

Is it possible to just label my NFS PV and pass those labels in to the configuration somehow? 

**Environment**

* Kubernetes version information:

```
bash-4.3$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-18T10:52:03Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

two bare-metal nodes brought up by kubeadm

```
bash-4.3$ kubectl -n kube-system get no
NAME                           STATUS         AGE
hypervisor01                   Ready,master   3d
kubes01.pss9.kickass.systems   Ready          3d
bash-4.3$ kubectl -n kube-system get po
NAME                                   READY     STATUS    RESTARTS   AGE
dummy-2088944543-2p3zf                 1/1       Running   1          3d
etcd-hypervisor01                      1/1       Running   2          3d
kube-apiserver-hypervisor01            1/1       Running   4          3d
kube-controller-manager-hypervisor01   1/1       Running   1          3d
kube-discovery-1769846148-v8h50        1/1       Running   1          3d
kube-dns-2924299975-3s26d              4/4       Running   4          3d
kube-proxy-vpw73                       1/1       Running   1          3d
kube-proxy-zfh13                       1/1       Running   0          3d
kube-registry-proxy-6hhk9              1/1       Running   1          3d
kube-registry-proxy-nl1s1              1/1       Running   0          3d
kube-registry-v0-4d94t                 1/1       Running   0          3d
kube-scheduler-hypervisor01            1/1       Running   1          3d
```

* Manifests:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: prometheus-k8s
  labels:
    prometheus: k8s
spec:
  version: v1.5.2
  retention: 30d
  resources:
    requests:
      storage: 1Mi
  storage:
    selectors:
      pv-name: nfs
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus-k8s
```

* Prometheus Operator Logs:

Controller-manager logs:
```
I0226 17:34:17.945506       1 pet_set.go:332] StatefulSet prometheus-prometheus-k8s blocked from scaling on pod prometheus-prometheus-k8s-0
E0226 17:34:17.952238       1 pet_set.go:272] Error syncing StatefulSet default/prometheus-prometheus-services, requeuing: Failed to create prometheus-prometheus-services-db-prometheus-prometheus-services-0: PersistentVolumeClaim "prometheus-prometheus-services-db-prometheus-prometheus-services-0" is invalid: spec.resources[storage]: Required value
I0226 17:34:17.952349       1 event.go:217] Event(api.ObjectReference{Kind:"StatefulSet", Namespace:"default", Name:"prometheus-prometheus-services", UID:"1899b833-fbd2-11e6-9ae6-a0481cb808c8", APIVersion:"apps", ResourceVersion:"304733", FieldPath:""}): type: 'Warning' reason: 'FailedCreate' pvc: prometheus-prometheus-services-db-prometheus-prometheus-services-0, error: PersistentVolumeClaim "prometheus-prometheus-services-db-prometheus-prometheus-services-0" is invalid: spec.resources[storage]: Required value
```

**Comment by gianrubio** [comment]
I'm not sure if it's possible, but try to create the pvc like this

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-class: ssd
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs #change to nfs provisionier
  labels:
    app: prometheus
    prometheus: prometheus-k8s
  name: prometheus-k8s-db-prometheus-k8s-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  volumeName: pvc-a7feb441-23-11e6-32-21
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 40Gi
  phase: Bound
```

Now create the storageClass similar to https://github.com/coreos/prometheus-operator/issues/146#issuecomment-280376182

**Comment by rrix** [comment]
That at least got the Pod to be created, but I'm still seeing issues.

```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-nfs
  labels:
    pv-name: prometheus-nfs
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 10.0.0.100
    path: /srv/files/files/containers/prometheus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-class: ssd
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/nfs
  labels:
    app: prometheus
    prometheus: prometheus-k8s
  name: prometheus-k8s-db-prometheus-k8s-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  volumeName: prometheus-nfs
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 40Gi
  phase: Bound
---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: prometheus-nfs
provisioner: kubernetes.io/nfs
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: prometheus-k8s
  labels:
    prometheus: k8s
spec:
  version: v1.5.2
  retention: 30d
  resources:
    requests:
      memory: 2Gi
      storage: 1Gi
  storage:
    class: prometheus-nfs
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus-k8s
```

```
bash-4.3$ kubectl get events | grep  prometheus-prometheus-k8s-0 | tail -10
<invalid>   5h          1086      prometheus-prometheus-k8s-0          Pod                                 Warning   FailedScheduling   {default-scheduler }             [SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "prometheus-prometheus-k8s-db-prometheus-prometheus-k8s-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "prometheus-prometheus-k8s-db-prometheus-prometheus-k8s-0", which is unexpected.]
```
