### ISSUE TITLE
Error loading config after update to version 0.23.0

### ISSUE THREAD

**Issue by r0bj** [coreos/prometheus-operator#1764]
**What did you do?**
Updated to version 0.23.0.

**What did you expect to see?**
Working prometheus instances without issues.

**What did you see instead? Under which circumstances?**
Prometheus instances failed to start:
```
level=error ts=2018-08-07T13:19:59.457381344Z caller=main.go:596 err="Error loading config couldn't load configuration (--config.file=/etc/prometheus/config_out/prometheus.env.yaml): open /etc/prometheus/config_out/prometheus.env.yaml: no such file or directory"
```

**Environment**

* Prometheus Operator version:

0.23.0

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:37:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:
prometheus-operator:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: prometheus-operator
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
    spec:
      serviceAccountName: prometheus-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
      - name: prometheus-operator
        image: quay.io/coreos/prometheus-operator:v0.23.0
        args:
        - --kubelet-service=kube-system/kubelet
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.21.0
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
```
prometheus:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  labels:
    app: prometheus
    prometheus: k8s
  namespace: monitoring
spec:
  replicas: 2
  version: v2.3.2
  externalUrl: http://prometheus.example.com
  externalLabels:
    prometheus_cluster: prometheus-k8s
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpressions:
    - key: k8s-app
      operator: Exists
  ruleSelector:
    matchLabels:
      role: alert-rules
      prometheus: k8s
  resources:
    limits:
      memory: 12Gi
    requests:
      memory: 12Gi
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-main
      port: web
  secrets:
  - etcd-certs
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: prometheus
            operator: In
            values:
            - k8s
        topologyKey: kubernetes.io/hostname
  retention: 3d
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: local-disks
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
```

* Prometheus Logs:

```
level=info ts=2018-08-07T13:19:52.18002352Z caller=main.go:222 msg="Starting Prometheus" version="(version=2.3.2, branch=HEAD, revision=71af5e29e815795e9dd14742ee7725682fa14b7b)"
level=info ts=2018-08-07T13:19:52.180107989Z caller=main.go:223 build_context="(go=go1.10.3, user=root@5258e0bd9cc1, date=20180712-14:02:52)"
level=info ts=2018-08-07T13:19:52.180148852Z caller=main.go:224 host_details="(Linux 4.13.0-36-generic #40-Ubuntu SMP Fri Feb 16 20:07:48 UTC 2018 x86_64 prometheus-k8s-1 (none))"
level=info ts=2018-08-07T13:19:52.180293818Z caller=main.go:225 fd_limits="(soft=524288, hard=1048576)"
level=info ts=2018-08-07T13:19:52.182724112Z caller=main.go:533 msg="Starting TSDB ..."
level=info ts=2018-08-07T13:19:52.182741135Z caller=web.go:415 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2018-08-07T13:19:52.183197416Z caller=repair.go:39 component=tsdb msg="found healthy block" mint=1533362400000 maxt=1533384000000 ulid=01CM2Q7VYHFGKB05356JSY7V40
level=info ts=2018-08-07T13:19:52.183343393Z caller=repair.go:39 component=tsdb msg="found healthy block" mint=1533384000000 maxt=1533405600000 ulid=01CM3BV2MS7T8A1ZQ9T9VFGQW0
level=info ts=2018-08-07T13:19:52.183477955Z caller=repair.go:39 component=tsdb msg="found healthy block" mint=1533405600000 maxt=1533427200000 ulid=01CM40E7SFHHX88KFE1AESJ8N2
level=info ts=2018-08-07T13:19:52.183597109Z caller=repair.go:39 component=tsdb msg="found healthy block" mint=1533427200000 maxt=1533448800000 ulid=01CM4N1DKYA4P5YT92QJFP8CCX
level=info ts=2018-08-07T13:19:52.183720424Z caller=repair.go:39 component=tsdb msg="found healthy block" mint=1533448800000 maxt=1533470400000 ulid=01CM59MJH9BN03TQFVW240BSCT
level=info ts=2018-08-07T13:19:52.183842293Z caller=repair.go:39 component=tsdb msg="found healthy block" mint=1533470400000 maxt=1533492000000 ulid=01CM5Y7QM3G66R2B51JR5KAEQ6
level=info ts=2018-08-07T13:19:52.183969521Z caller=repair.go:39 component=tsdb msg="found healthy block" mint=1533492000000 maxt=1533513600000 ulid=01CM6JTY4JBZK4RS41ZMGVA1JZ
level=info ts=2018-08-07T13:19:52.184089577Z caller=repair.go:39 component=tsdb msg="found healthy block" mint=1533513600000 maxt=1533535200000 ulid=01CM77E3PRC0EBF9TWZ14587HG
level=info ts=2018-08-07T13:19:52.184211532Z caller=repair.go:39 component=tsdb msg="found healthy block" mint=1533535200000 maxt=1533556800000 ulid=01CM7W1A6HSMJ6A7E83FPSJA95
level=info ts=2018-08-07T13:19:52.184330611Z caller=repair.go:39 component=tsdb msg="found healthy block" mint=1533556800000 maxt=1533578400000 ulid=01CM8GMFJMNGWQWH54ZEXH3H37
level=info ts=2018-08-07T13:19:52.184456993Z caller=repair.go:39 component=tsdb msg="found healthy block" mint=1533578400000 maxt=1533600000000 ulid=01CM957P9V66Z3K76NG78C5BHD
level=info ts=2018-08-07T13:19:52.184568494Z caller=repair.go:39 component=tsdb msg="found healthy block" mint=1533621600000 maxt=1533628800000 ulid=01CM9STK8BBCK08C89YC7Y1TVA
level=info ts=2018-08-07T13:19:52.184688395Z caller=repair.go:39 component=tsdb msg="found healthy block" mint=1533600000000 maxt=1533621600000 ulid=01CM9STVFXP0QJ6W1XHP64PQJW
level=info ts=2018-08-07T13:19:52.184899175Z caller=repair.go:39 component=tsdb msg="found healthy block" mint=1533628800000 maxt=1533636000000 ulid=01CMA0PAGCKW0ZH1Q6MWP0WWBF
level=info ts=2018-08-07T13:19:52.185014613Z caller=repair.go:39 component=tsdb msg="found healthy block" mint=1533636000000 maxt=1533643200000 ulid=01CMA7J1RBDTJMCEJYCN0GXSEM
level=info ts=2018-08-07T13:19:59.452697695Z caller=main.go:543 msg="TSDB started"
level=info ts=2018-08-07T13:19:59.452805191Z caller=main.go:603 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2018-08-07T13:19:59.453037572Z caller=main.go:402 msg="Stopping scrape discovery manager..."
level=info ts=2018-08-07T13:19:59.453079622Z caller=main.go:416 msg="Stopping notify discovery manager..."
level=info ts=2018-08-07T13:19:59.453120092Z caller=main.go:438 msg="Stopping scrape manager..."
level=info ts=2018-08-07T13:19:59.453155279Z caller=main.go:412 msg="Notify discovery manager stopped"
level=info ts=2018-08-07T13:19:59.453169975Z caller=main.go:398 msg="Scrape discovery manager stopped"
level=info ts=2018-08-07T13:19:59.453254263Z caller=main.go:432 msg="Scrape manager stopped"
level=info ts=2018-08-07T13:19:59.453318917Z caller=manager.go:464 component="rule manager" msg="Stopping rule manager..."
level=info ts=2018-08-07T13:19:59.453352398Z caller=manager.go:470 component="rule manager" msg="Rule manager stopped"
level=info ts=2018-08-07T13:19:59.45715383Z caller=notifier.go:512 component=notifier msg="Stopping notification manager..."
level=info ts=2018-08-07T13:19:59.457246904Z caller=main.go:587 msg="Notifier manager stopped"
level=error ts=2018-08-07T13:19:59.457381344Z caller=main.go:596 err="Error loading config couldn't load configuration (--config.file=/etc/prometheus/config_out/prometheus.env.yaml): open /etc/prometheus/config_out/prometheus.env.yaml: no such file or directory"
```
