### ISSUE TITLE
Getting what looks like duplicate data from Prometheus related to kubernetes node exporter

### ISSUE THREAD

**Issue by michaelgeorgeattard** [coreos/prometheus-operator#1767]
For the following query for example:

```
node_memory_MemFree{instance="$server"}
```

I am getting duplicate data:

```
node_memory_MemFree{endpoint="metrics",instance="172.20.101.55:9100",job="kube-prometheus-exporter-node",namespace="monitoring",pod="kube-prometheus-exporter-node-dt49c",service="kube-prometheus-exporter-node"}
```
```
node_memory_MemFree{endpoint="metrics",instance="172.20.101.55:9100",job="node-exporter",namespace="monitoring",pod="kube-prometheus-exporter-node-dt49c",service="kube-prometheus-exporter-node"}
```

Looks like I am seeing this issue throughout my node exporter data graphs. Any idea what might be happening?

**Comment by brancz** [comment]
That looks like you have two jobs that are scraping the same target(s). Check your `/targets` page, you should see a `node-exporter` and a `kube-prometheus-exporter-node` job.

**Comment by michaelgeorgeattard** [comment]
@brancz Indeed I found both `node-exporter` and `kube-prometheus-exporter-node` under `/targets`. What does this mean? I installed `prometheus-operator` and `kube-prometheus` using helm.

**Comment by michaelgeorgeattard** [comment]
Maybe this configuration is double matching?

```
- job_name: monitoring/kube-prometheus-exporter-node/0
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - api_server: null
    role: endpoints
    namespaces:
      names:
      - monitoring
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_label_app]
    separator: ;
    regex: exporter-node
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_service_label_component]
    separator: ;
    regex: node-exporter
    replacement: $1
    action: keep
```

As both `app` and `component` labels match.
