### ISSUE TITLE
prometheus secret not found / "sync prometheus" 

### ISSUE THREAD

**Issue by aaron-trout** [coreos/prometheus-operator#1768]
**What did you do?**

- Deploy prometheus operator
- Create a `Prometheus` object (along with `ServiceAccount` and appropriate bindings)

**What did you expect to see?**

- No errors in operator logs

**What did you see instead? Under which circumstances?**

- Error about missing secret and incredibly spammy 'sync' logs

**Environment**

* Prometheus Operator version:

	`quay.io/coreos/prometheus-operator:v0.22.2`

* Kubernetes version information:

	v1.10.5-gke.3

* Kubernetes cluster kind: 

	GKE

* Manifests:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: aaron
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: aaron
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: aarons-prometheus
  namespace: aaron
spec:
  baseImage: quay.io/prometheus/prometheus
  version: v2.3.2
  replicas: 1
  retention: 24h
  serviceAccountName: prometheus
  storage:
    volumeClaimTemplate:
      metadata:
        name: prometheus-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: pd-ssd
        resources:
          requests:
            storage: 200Gi
  resources:
    requests:
      cpu: 0.2
      memory: 1Gi
```

* Prometheus Operator Logs:

```
E0808 10:27:39.565930       1 operator.go:651] Sync "aaron/aarons-prometheus" failed: secrets "prometheus-aarons-prometheus" not found
level=info ts=2018-08-08T10:27:39.56596763Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:39.586073713Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:39.612902054Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:39.646669946Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:39.679170339Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:39.720191612Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:39.743930766Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:39.765038779Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:39.785360052Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:39.811804394Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:39.834387638Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:39.866339016Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:39.88700967Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:39.910234149Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:39.929636763Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:39.950043501Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:39.970237526Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:39.996423722Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.017274246Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.037909776Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.057914443Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.096271366Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.120401141Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.144732839Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.205965804Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.226672608Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.247791291Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.268708474Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.2976729Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.31936984Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.340438527Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.364102271Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.396560624Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.419668003Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.442480333Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.472795979Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.498100976Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.52561951Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.548155108Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.571921659Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.599004914Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.64964934Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.698388852Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.761135153Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.798714836Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
level=info ts=2018-08-08T10:27:40.848854927Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=aaron/aarons-prometheus
```

As I see it there are two problems here:

1) The error message about the service account. Not sure what it is expecting to find there... (Note this also happens when using the `kube-prometheus` manifests)
2) Incredibly spammy "sync prometheus" logs. IMO this polling loop happens too often. It should be an API watch if possible or make it less often. But also the logs are not very helpful and are too spammy.

The prometheus server does seem to be created ok (i.e. the `StatefulSet` is created and the pod starts ok.) but the sync messages continue with at least 10 or 20 messages per second!
