### ISSUE TITLE
How to specify the host of k8s apiserver

### ISSUE THREAD

**Issue by Kevin-P-Huang** [coreos/prometheus-operator#1817]
**What did you do?**

Want to specify the host of apiserver. 
URL of apiserver in my k8s environment  is "http://192.168.1.4:8080"

**Environment**

* Prometheus Operator version:

quay.io/coreos/prometheus-operator:v0.15.0

* Kubernetes version information:

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Thanks.

**Comment by brancz** [comment]
The Prometheus Operator runs within the Kubernetes cluster itself, and the conformant way of running Kubernetes has the apiserver available at `kubernetes.default.svc`. Can you explain why this is not the case?

**Comment by Kevin-P-Huang** [comment]
To simplify installation, TLS Certificates is not used in our k8s environment( 3 master and 5 node in cluster), and URL of apiserver in our k8s environment is "http://192.168.1.4:8080" and is not “https://10.10.10.1:443”.

It will sometimes bring us trouble when deploy.Because some containers will automatically connect apiserver by  https' URL when  be deployed, and error occur. 
For example, when we deploy prometheus-operator, error info will be printed in pod's log.
```
E0822 07:08:00.590624       1  1 config.go:322] Ex] Expected to load root CA config from /var/run/secrets/ts/kubernetes.io/serviceaccount/ca.crt, but but got err: open /var/run/secrets/ts/kubernetes.io/serviceaccount/ca.crt: no  no such file or directory
failed to run migrations: Get et https://10.10.10.1:443/version: x50 x509: certificate signed by unknown authority
```

To avoid connecting to the https url of apiserver, we will find the arg or env of container to specify the host of apiserver. For example, we add an env of container which name "APISERVER_HOST"  to specify the host of apiserver when deploy elasticsearch of [k8s addon fluentd-elasticsearch](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch)
```
  spec:
      containers:
      - image: k8s.gcr.io/elasticsearch:v6.2.4
        name: elasticsearch-logging
        resources:
          limits:
            cpu: 1000m
        [...]
        env:
        - name: APISERVER_HOST
          value: "http://192.168.1.4:8080"
```

**Comment by brancz** [comment]
It is possible to set the apiserver to use with the `--apiserver` flag, but as the description says, there is no stability guarantees for this as it is primarily meant for testing.

https://github.com/coreos/prometheus-operator/blob/0a32704063513c9a7b35697f35ee3246cfc61663/cmd/operator/main.go#L110

**Comment by Kevin-P-Huang** [comment]
@brancz according to your adivce, I add the `--apiserver` flag in yaml of prometheus-operator as below and deploy. It work fine!

```
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        - --apiserver=http://192.168.1.4:8080
        image: quay.io/coreos/prometheus-operator:v0.15.0
```


Thank you very much!  u make my day.
