### ISSUE TITLE
[kube-prometheus]: KubeControllerManagerDown  & KubeSchedulerDown w/ kubeadm

### ISSUE THREAD

**Issue by bitva77** [coreos/prometheus-operator#1859]
**What did you do?**
Installed kube-prometheus onto cluster setup via kubeadm

**What did you expect to see?**
KubeControllerManagerDown  & KubeSchedulerDown not firing

**What did you see instead? Under which circumstances?**

ALERTS:
KubeControllerManagerDown (1 active)
KubeSchedulerDown (1 active)

**Environment**

* Prometheus Operator version:

> 01676d7f4dbb230b5db04874ea51242241cb782a

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

kubeadm

* Manifests:

Let's take ControllerManager as an example:

As I understand it, the ServiceMonitor label for the ControllerManager by default is `k8s-app: kube-controller-manager`

But in my cluster the label is `component: kube-controller-manager`:

> kubectl get pod -n kube-system -l component=kube-controller-manager
> NAME                                   READY     STATUS    RESTARTS   AGE
> kube-controller-manager-servera146   1/1       Running   0          85d

so I updated `prometheus-serviceMonitorKubeControllerManager.yaml` accordingly:

```
  selector:
    matchLabels:
      component: kube-controller-manager
```

I then applied this new ServiceMonitor, however it's still a no go and is still showing as down.

Webhook stuff is enabled in kubelet per the docs and both scheduler and controller are listening on 0.0.0.0.

Any ideas where I've gone wrong?

Thanks!

**Comment by brancz** [comment]
You need to make use of the mixin that we provide for kubeadm. See here: https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#cluster-creation-tools. That will create two additional `Service` objects that will select the respective scheduler or controller-manager Pods. The `ServiceMonitor` should not need to be adapted.

**Comment by voki** [comment]
@brancz My cluster was created with kubeadm. I have installed prometheus-operator and kube-prometheus with Helm. How to apply that mixin, could you point me in the right direction?

**Comment by brancz** [comment]
@voki I don't think helm has a concept to set it for each cluster type, but a generic one. Sorry I'm not familiar enough with the helm charts. @gianrubio maintains them.

**Comment by bitva77** [comment]
@brancz, you happen to have any documentation for that mixin?  No worries if not.

Thanks!

**Comment by brancz** [comment]
I recommend looking at the jsonnet based stack, it allows arbitrary customization: https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/README.md

**Comment by bitva77** [comment]
Alighty, got it working.  Documenting here for future reference on how I set this up for kubeadm.  I have a fairly basic Kubernetes installation via kubeadm running on RHEL 7.5:

**First, install go:**
```
cd $HOME
wget https://dl.google.com/go/go1.11.linux-amd64.tar.gz
tar -xvzf go1.11.linux-amd64.tar.gz
PATH=$PATH:$HOME/go/bin
export PATH
```

Verify it works:

`go env`

**Create a place for go to download stuff:**

```
mkdir gocode
GOPATH=$HOME/gocode
export GOPATH
```

**You'll want to put go stuff in your path too:**

```
PATH=$PATH:$HOME/gocode/bin
export PATH
```

**Install jb/jsonnet/gojsontoyaml**
_make sure you have git installed first_

```
go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
go get github.com/google/go-jsonnet/jsonnet
go get github.com/brancz/gojsontoyaml
```

**Create a directory to put kube-prometheus:**

`mkdir my-kube-prometheus && cd my-kube-prometheus`

**Create the initial jsonnetfile.json file:**

`jb init`

**Create a file called example.jsonnet with this in it:**

```
// Modified version of:
// https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/example.jsonnet

local kp = (import 'kube-prometheus/kube-prometheus.libsonnet') +
           (import 'kube-prometheus/kube-prometheus-kubeadm.libsonnet') +
           (import 'kube-prometheus/kube-prometheus-node-ports.libsonnet') {
  _config+:: {
    namespace: 'monitoring',
  },
};

{ ['00namespace-' + name + '.json']: kp.kubePrometheus[name] for name in std.objectFields(kp.kubePrometheus) } +
{ ['0prometheus-operator-' + name + '.json']: kp.prometheusOperator[name] for name in std.objectFields(kp.prometheusOperator) } +
{ ['node-exporter-' + name + '.json']: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
{ ['kube-state-metrics-' + name + '.json']: kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics) } +
{ ['alertmanager-' + name + '.json']: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
{ ['prometheus-' + name + '.json']: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
{ ['grafana-' + name + '.json']: kp.grafana[name] for name in std.objectFields(kp.grafana) }
```

**Create a build.sh file with this in it:**

```
#!/usr/bin/env bash

# This script uses arg $1 (name of *.jsonnet file to use) to generate the manifests/*.yaml files.

set -e
set -x
# only exit with zero if all commands of the pipeline exit successfully
set -o pipefail

# Make sure to start with a clean 'manifests' dir
rm -rf manifests
mkdir manifests

                                               # optional, but we would like to generate yaml, not json
jsonnet -J vendor -m manifests "${1-example.jsonnet}" | xargs -I{} sh -c 'cat {} | gojsontoyaml > {}.yaml; rm -f {}' -- {}
```

**Make that build script executable and then run it:**

```
chmod +x build.sh
./build.sh
```
this will have created a directory called manifests and put the appropriate YAML files in it.

**Now install the kubeadm configured version of kube-prometheus:**

`kubectl apply -f manifests/`


**You'll next likely want to create ingresses for Grafana and Prometheus and Alertmanager:**

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alertmanager-main
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: alertmanager-mydomain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: alertmanager-main
          servicePort: web
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: grafana-mydomain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-k8s
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: prometheus-mydomain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus-k8s
          servicePort: 9090
```
_update the spec.rules.host URL accordingly to your domain_

**Comment by voki** [comment]
For a quick win:
kubectl edit service kube-prometheus-exporter-kube-scheduler  -n kube-system
kubectl edit service kube-prometheus-exporter-kube-controller-manager -n kube-system 

Update selector "k8s-app:" to "component:"

**Comment by wilmardo** [comment]
@bitva77 The ingress can be generated as well [see the readme](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/exposing-prometheus-alertmanager-grafana-ingress.md)

**Comment by VinceMD** [comment]
I think the above might be fixed, isn't it? the jsonnet for kubeadm looks correct.

For kube-aws though, the right one is:

```
local k = import 'ksonnet/ksonnet.beta.3/k.libsonnet';
local service = k.core.v1.service;
local servicePort = k.core.v1.service.mixin.spec.portsType;

{
  prometheus+: {
    kubeControllerManagerPrometheusDiscoveryService:
      service.new('kube-controller-manager-prometheus-discovery', { 'k8s-app': 'kube-controller-manager' }, servicePort.newNamed('http-metrics', 10252, 10252)) +
      service.mixin.metadata.withNamespace('kube-system') +
      service.mixin.metadata.withLabels({ 'k8s-app': 'kube-controller-manager' }) +
      service.mixin.spec.withClusterIp('None'),
    kubeSchedulerPrometheusDiscoveryService:
      service.new('kube-scheduler-prometheus-discovery', { 'k8s-app': 'kube-scheduler' }, servicePort.newNamed('http-metrics', 10251, 10251)) +
      service.mixin.metadata.withNamespace('kube-system') +
      service.mixin.metadata.withLabels({ 'k8s-app': 'kube-scheduler' }) +
      service.mixin.spec.withClusterIp('None'),
  },
}
```

@brancz sorry I might be a bit tired but I want to make a merge request with this new file for kube-aws. Can you tell me where this file should go? And any doc page I should write to support it

**Comment by brancz** [comment]
There are similar files in “contrib/kube-prometheus/jsonnet/kube-prometheus” and an example in “contrib/kube-prometheus/examples” would be good as well. Documentation would just go into the kube-prometheus readme like the other platforms. Thanks! :)

**Comment by VinceMD** [comment]
https://github.com/coreos/prometheus-operator/pull/2111

**Comment by lzbgt** [comment]
instead of using the jb tool, a quick gotcha is just create two services in kube-system for kube-controller-manager and kube-scheduler for the discovery of prometheus if you used the generated default static yamls in this repo:
```
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-scheduler-prometheus-discovery
  labels:
    k8s-app: kube-scheduler
spec:
  selector:
    component: kube-scheduler
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10251
    targetPort: 10251
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-controller-manager-prometheus-discovery
  labels:
    k8s-app: kube-controller-manager
spec:
  selector:
    component: kube-controller-manager
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10252
    targetPort: 10252
    protocol: TCP
```

**Comment by LuisRG-GIG** [comment]
I used the izbgt's services and I change "address=127.0.0.1" for "address=0.0.0.0" in the kube-scheduler and kube-controller-manager manifests and worked fine :-)

**Comment by gavin-guo** [comment]
> instead of using the jb tool, a quick gotcha is just create two services in kube-system for kube-controller-manager and kube-scheduler for the discovery of prometheus if you used the generated default static yamls in this repo:
> 
> ```
> apiVersion: v1
> kind: Service
> metadata:
>   namespace: kube-system
>   name: kube-scheduler-prometheus-discovery
>   labels:
>     k8s-app: kube-scheduler
> spec:
>   selector:
>     component: kube-scheduler
>   type: ClusterIP
>   clusterIP: None
>   ports:
>   - name: http-metrics
>     port: 10251
>     targetPort: 10251
>     protocol: TCP
> ---
> apiVersion: v1
> kind: Service
> metadata:
>   namespace: kube-system
>   name: kube-controller-manager-prometheus-discovery
>   labels:
>     k8s-app: kube-controller-manager
> spec:
>   selector:
>     component: kube-controller-manager
>   type: ClusterIP
>   clusterIP: None
>   ports:
>   - name: http-metrics
>     port: 10252
>     targetPort: 10252
>     protocol: TCP
> ```

awesome, thank you so much.

**Comment by gavin-guo** [comment]
@lzbgt worked fine for me, thank you so much

**Comment by andrewsav-datacom** [comment]
@brancz I'd like to revisit this with you if possible. We have a working workaround here in this thread, could we integrate it to the code base of kube-prometheus, so that every kubeadm user does not have [to do this](https://github.com/coreos/prometheus-operator/issues/1859#issuecomment-437740104) manually?

**Comment by AndrewSav** [comment]
@brancz I'd like to revisit this with you if possible. We have a working workaround here in this thread, could we integrate it to the code base of kube-prometheus, so that every kubeadm user does not have [to do this](https://github.com/coreos/prometheus-operator/issues/1859#issuecomment-437740104) manually?

**Comment by xpepermint** [comment]
The see same alerts of a fresh version of Kubernetes 1.20 created with `kops`.

Refs:
- https://github.com/prometheus-operator/kube-prometheus/issues/1089
- https://github.com/kubernetes/kops/issues/11211

**Comment by agermain** [comment]
I'm also seeing the same on 1.19

**Comment by jgagnon44** [comment]
I think I'm having the same issue. I am using the following:

- Kubernetes 1.24
- Helm 3.10.0
- `kube-prometheus-stack` Helm chart 41.7.4 (app version 0.60.1)

When I check the alerts, there are a lot that are firing, including the ones mentioned in this thread. It is not clear to me what is going on here as to why these alerts are constantly firing. Are there K8s components that are missing (services, volumes, etc.)? Since this was installed via Helm, I don't have a good view into what is going on behind the scenes. I am also still quite new to K8s and Helm.

If it's of any help, here is my `values.yaml`:

```
defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: true
    configReloaders: true
    general: true
    k8s: true
    kubeApiserverAvailability: true
    kubeApiserverBurnrate: true
    kubeApiserverHistogram: true
    kubeApiserverSlos: true
    kubeControllerManager: true
    kubelet: true
    kubeProxy: true
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    kubeSchedulerAlerting: true
    kubeSchedulerRecording: true
    kubeStateMetrics: true
    network: true
    node: true
    nodeExporterAlerting: true
    nodeExporterRecording: true
    prometheus: true
    prometheusOperator: true

prometheus:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - <hidden>
    paths:
      - /
    pathType: ImplementationSpecific

grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - <hidden>
    path: /
  persistence:
    enabled: true
    size: 10Gi

alertmanager:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - <hidden>
    paths:
      - /
    pathType: ImplementationSpecific
  config:
    global:
      slack_api_url: '<hidden>'
    route:
      receiver: "slack-default"
      group_by:
        - alertname
        - cluster
        - service
      group_wait: 30s
      group_interval: 5m # 5m
      repeat_interval: 2h # 4h
      routes:
        - receiver: "slack-warn-critical"
          matchers:
            - severity =~ "warning|critical"
          continue: true
    receivers:
      - name: "null"
      - name: "slack-default"
        slack_configs:
          - send_resolved: true # false
            channel: "#grafana-test"
            # title: '{{ .Status | toUpper }}'
            # text: '{{ range .Alerts }}'
      - name: "slack-warn-critical"
        slack_configs:
          - send_resolved: true # false
            channel: "#grafana-test"
            title: '{{ .Status | toUpper }}'
            text: '{{ range .Alerts }}'
```

Here are the alerts firing for TargetDown:

![image](https://user-images.githubusercontent.com/56738211/203111938-13de47c5-0326-4409-8a99-8a8ddf546649.png)
