### ISSUE TITLE
Prometheus Operator Failed to generate Kubelet Service

### ISSUE THREAD

**Issue by salilgupta1** [coreos/prometheus-operator#1863]
**What did you do?**
Deployed the Prometheus Operator

**What did you expect to see?**
The kubelet service with the associated endpoints

**What did you see instead? Under which circumstances?**
Two of our instances did not have an External IP or Internal IP registered with K8s while the AWS console reported an External IP and Internal IP. 

The Prometheus operator tried to generate endpoints for all the Kubelets but failed since the Kubelets on the two instances didn't have valid IPs associated with them. Ultimately, we restarted the kubelets on the instances and K8s reported IPs for the instances.

I wonder if the better behavior should be to log this error and continue to generate endpoints for the remaining Kubelets so that a user can have some visibility.

**Environment**
CloudProvider: AWS

* Prometheus Operator version:

	quay.io/coreos/prometheus-operator:v0.23.1

* Kubernetes version information:

	v1.11

* Kubernetes cluster kind: 

Deployed via Kops on AWS

* Manifests:
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: prometheus-operator
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --logtostderr=true
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.23.1
        image: quay.io/coreos/prometheus-operator:v0.23.1
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      nodeSelector:
        nodePool: admin
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator
```

* Prometheus Operator Logs:

![screen shot 2018-09-06 at 9 37 09 am](https://user-images.githubusercontent.com/5280219/45165417-65844200-b1ba-11e8-8b77-4510758688f9.png)
