### ISSUE TITLE
mysql-exporter for kube-prometheus

### ISSUE THREAD

**Issue by deboshrestha** [coreos/prometheus-operator#1868]
**What did you do?**
I am trying to set up an exporter for mysql inside the kube-prometheus set up . I am planning to use this docker image - https://hub.docker.com/r/prom/mysqld-exporter/ 

**What did you expect to see?**
A mysql-exporter in the UI with the mysql-service being monitored

**What did you see instead? Under which circumstances?**
Nothing is showing up in the front end

**Environment**

* Prometheus Operator version:

	v0.18.1 tag

* Kubernetes version information:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T20:00:41Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2+coreos.0", GitCommit:"b427929b2982726eeb64e985bc1ebb41aaa5e095", GitTreeState:"clean", BuildDate:"2018-01-18T22:56:14Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	Created using kubespray

* Manifests:

`mysql-exporter/mysql-exporter-deployment.yaml`
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
      - image: prom/mysqld-exporter
        imagePullPolicy: "IfNotPresent"
        env:
          - name: DATA_SOURCE_NAME
            value: "exporter:xxxxx@(<IP of mysql-service>:3306)/<db-name>"
        name: mysql-exporter
        ports:
        - containerPort: 9104
          name: metrics
```
`mysql-exporter-service.yaml`
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-exporter
  name: mysql-exporter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: https
    port: 9104
    protocol: TCP
  selector:
    app: mysql-exporter

```

`prometheus/prometheus-k8s-service-monitor-mysql-exporter.yaml`

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-exporter
  labels:
    k8s-app: mysql-exporter
spec:
  jobLabel: k8s-app
  selector:
    app: mysql-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  static_configs:
      - targets:
        - <mysql-service-ip>:9104

```
* Prometheus Operator Logs:

Nothing in the logs so far
```
kubectl logs -f prometheus-operator-945d468db-6t7gj -n monitoring
ts=2018-09-06T22:25:36.27798723Z caller=operator.go:269 component=prometheusoperator msg="connection established" cluster-version=v1.9.2+coreos.0
ts=2018-09-06T22:25:36.27799398Z caller=operator.go:170 component=alertmanageroperator msg="connection established" cluster-version=v1.9.2+coreos.0
ts=2018-09-06T22:25:36.281810967Z caller=operator.go:184 component=alertmanageroperator msg="CRD API endpoints ready"
ts=2018-09-06T22:25:36.283737184Z caller=operator.go:283 component=prometheusoperator msg="CRD API endpoints ready"
ts=2018-09-06T22:26:00.05789232Z caller=operator.go:319 component=prometheusoperator msg="Prometheus added" key=monitoring/k8s
ts=2018-09-06T22:26:00.057987551Z caller=operator.go:684 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2018-09-06T22:26:00.072996556Z caller=operator.go:1013 component=prometheusoperator msg="creating configuration"
ts=2018-09-06T22:26:00.164472506Z caller=operator.go:358 component=alertmanageroperator msg="update handler" old=28429138 cur=28429144
ts=2018-09-06T22:26:00.164709635Z caller=operator.go:684 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2018-09-06T22:26:00.167618011Z caller=operator.go:649 component=prometheusoperator msg="update handler" old=28429138 cur=28429144
ts=2018-09-06T22:26:00.2671956Z caller=operator.go:1024 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-09-06T22:26:00.284500591Z caller=operator.go:684 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2018-09-06T22:26:00.295945718Z caller=operator.go:1024 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-09-06T22:26:02.833955091Z caller=operator.go:684 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2018-09-06T22:26:02.865666939Z caller=operator.go:1024 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-09-06T22:26:03.361463723Z caller=operator.go:318 component=alertmanageroperator msg="Alertmanager added" key=monitoring/main
ts=2018-09-06T22:26:03.361557135Z caller=operator.go:394 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
ts=2018-09-06T22:26:03.373894941Z caller=operator.go:394 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
ts=2018-09-06T22:26:03.388293566Z caller=operator.go:649 component=prometheusoperator msg="update handler" old=28429190 cur=28429194
ts=2018-09-06T22:26:03.388353114Z caller=operator.go:358 component=alertmanageroperator msg="update handler" old=28429190 cur=28429194
ts=2018-09-06T22:26:03.388406931Z caller=operator.go:394 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
ts=2018-09-06T22:26:04.338172779Z caller=operator.go:684 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2018-09-06T22:26:04.369067167Z caller=operator.go:1024 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-09-06T22:26:10.580905839Z caller=operator.go:358 component=alertmanageroperator msg="update handler" old=28429194 cur=28429356
ts=2018-09-06T22:26:10.580977563Z caller=operator.go:394 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
ts=2018-09-06T22:26:10.661296853Z caller=operator.go:649 component=prometheusoperator msg="update handler" old=28429194 cur=28429356
ts=2018-09-06T22:26:11.412254308Z caller=operator.go:649 component=prometheusoperator msg="update handler" old=28429144 cur=28429368
ts=2018-09-06T22:26:11.41232261Z caller=operator.go:684 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2018-09-06T22:26:11.412306544Z caller=operator.go:358 component=alertmanageroperator msg="update handler" old=28429144 cur=28429368
ts=2018-09-06T22:26:11.4646929Z caller=operator.go:1024 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-09-06T22:26:17.357010223Z caller=operator.go:358 component=alertmanageroperator msg="update handler" old=28429356 cur=28429389
```

Any help on this would be very much appreciated.

**Comment by brancz** [comment]
“static_configs” does not exist on the ServiceMonitor, what you probably want is a selector selecting Services with the “app: mysql-exporter” label. Let us know if that works :)

**Comment by deboshrestha** [comment]
Thanks @brancz ! I was able to figure this out. Here are the manifests -

`mysql-exporter-cluster-role-binding.yaml`
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: mysql-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mysql-exporter
subjects:
- kind: ServiceAccount
  name: mysql-exporter
  namespace: monitoring
```
`mysql-exporter-cluster-role.yaml`
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: mysql-exporter
rules:
- apiGroups: ["authentication.k8s.io"]
  resources:
  - tokenreviews
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources:
  - subjectaccessreviews
  verbs: ["create"]
```
`mysql-exporter-deployment.yaml` 
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mysql-exporter
  template:
    metadata:
      labels:
        k8s-app: mysql-exporter
      name: mysql-exporter
    spec:
      containers:
      - image: prom/mysqld-exporter:latest
        imagePullPolicy: "IfNotPresent"
        env:
          - name: DATA_SOURCE_NAME
            value: "exporter:xxxxxx@(mysql-service-IP:3306)/"
        args:
          - "--collect.info_schema.processlist"
          - "--collect.info_schema.innodb_metrics"
          - "--collect.info_schema.tablestats"
          - "--collect.info_schema.userstats"
          - "--collect.engine_innodb_status"
          - "--collect.slave_hosts"
        name: mysql-exporter
        ports:
          - containerPort: 9104
            name: mysql-metrics
```
`mysql-exporter-service-account.yaml`
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-exporter
```
`mysql-exporter-service.yaml`
```
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: mysql-exporter
  name: mysql-exporter
spec:
  ports:
    - name: mysql-metrics
      port: 9104
      protocol: TCP
      targetPort: 9104
  selector:
    k8s-app: mysql-exporter
```
`prometheus/prometheus-k8s-service-monitor-mysql-exporter.yaml`
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  labels:
    k8s-app: node-exporter
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: node-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: https
    scheme: https
    interval: 30s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      insecureSkipVerify: true
```

**Comment by deboshrestha** [comment]
ok, thanks I will remove the clusterRole and clusterRolebinding .

Also I am sorry this is the right one - 
`prometheus/prometheus-k8s-service-monitor-mysql-exporter.yaml`
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-exporter
  labels:
    k8s-app: mysql-exporter
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: mysql-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
   - port: mysql-metrics
     scheme: http
     interval: 30s
     bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
     tlsConfig:
       insecureSkipVerify: true
```

does this ^^ looks right?
