### ISSUE TITLE
Support initContainers on `kind: Prometheus`

### ISSUE THREAD

**Issue by kuznero** [coreos/prometheus-operator#1888]
This is missing as in some cases when using `hostPath` volumes with non-root it is important to be able to `chown -R ...` on the init container.

**Comment by brancz** [comment]
Aside from resource and security concerns, using hostpath for Prometheus data is rather fragile, as you don't know whether future pods will be scheduled onto the same nodes, so you would be leaving around data and starting new time-series databases on every deploy anyways, which doesn't sound like what you are looking for. I would recommend you to look into local volumes, if you don't have a dynamic provisioner available through a cloud provider for example. Local volumes have the same support by the kubelet as any other volumes, meaning the kubelet will properly prepare permissions and ownership before attaching the volume to your Pod.

**Comment by kuznero** [comment]
Here is fairly typical use case that makes it very much possible to ensure new/restored Prometheus pod is not starting over.

```yaml
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
```

In the end of the day it should be about covering as many different options there might be and not limiting?
