### ISSUE TITLE
Missing Alertmanager endpoint

### ISSUE THREAD

**Issue by mgoodness** [coreos/prometheus-operator#190]
**What did you do?**
Instantiated a Prometheus TPR with AlertingSpec

**What did you expect to see?**
An Alertmanager endpoint listed on the Prometheus `/status` page

**What did you see instead? Under which circumstances?**
No Alertmanager endpoint

**Environment**

* Kubernetes version information:
Helm v2.2.1, Kubernetes v1.5.3

* Manifests:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  labels:
    app: prometheus
    chart: prometheus-0.6.0-1
    heritage: Tiller
    prometheus: youthful-leopard
    release: youthful-leopard
  name: youthful-leopard
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: precise-salamander-alertmanager
      namespace: monitoring
      port: 9093
      scheme: http
  baseImage: quay.io/prometheus/prometheus
  externalUrl: http://prom-test.aws.opsgoodness.net
  paused: false
  replicas: 1
  resources: {}
  retention: 24h
  routePrefix: /
  storage:
    class: standard
    resources:
      requests:
        storage: 16Gi
  version: v1.5.2
```

The `youthful-leopard` ConfigMap is created, but it's empty:
```
apiVersion: v1
data:
  prometheus.yaml: ""
kind: ConfigMap
metadata:
  name: prometheus-youthful-leopard
  namespace: monitoring
```
