### ISSUE TITLE
Add datasource by configuration to Grafana does not work 

### ISSUE THREAD

**Issue by oded-dd** [coreos/prometheus-operator#1909]
**What did you do?**
Updated helm chart for kube-prometheus with the following:
```
# Grafana
deployGrafana: True

grafana:
  image:
    tag: latest
  keepOriginalDashboards: false
  keepOriginalDatasources: false
  dataSource:
    datasource.yaml: |+
      apiVersion: "1"
      datasources:
      - name: "prod"
        access: "proxy"
        type: "prometheus"
        url: "http://kube-prometheus-prod:9090"
        editable: "false"
      - name: "stage"
        access: "proxy"
        type: "prometheus"
        url: "http://kube-prometheus-stage:9090"
        editable: "false"
      - name: "mgmt"
        access: "proxy"
        type: "prometheus"
        url: "http://kube-prometheus:9090"
        editable: "false"
```

**What did you expect to see?**
Datasources should be added to grafana

**What did you see instead? Under which circumstances?**
No Datasource appears

**Environment**

* Prometheus Operator version:

	0.20.0

* Kubernetes version information:

	v1.10.3

* Kubernetes cluster kind: 

       kops

* Manifests:

* Prometheus Operator Logs:

**Comment by gabrielmcf** [comment]
Having the same problem. I'm using Grafana 5.0.4 (but tried with 5.0.0) as well. The grafana-watcher container returns an error message continuously in log: cannot unmarshal object into Go value of type []grafana.Grafana Datasource.
The grafana container logs an 403 HTTP error in path /api/datasources

**Comment by vsliouniaev** [comment]
@gabrielmcf The charts have been merged into helm/charts, and use the official grafana helm chart, this should allow you to load additional datasources from configmaps using the sidecar

**Comment by galindro** [comment]
I'm facing the same problem as well. I'm using prometheus-operator helm chart version 8.5.2. In my scenario, I've added a new value on grafana.additionalDataSources array and  the change wasn't being reflected on grafana.

#### BEFORE
```yaml
grafana:
  sidecar:
    datasources:
      enabled: true
      label: grafana_datasource
      searchNamespace: ALL
      defaultDatasourceEnabled: true
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki-stack.loki-stack:3100/
      access: proxy
```

#### AFTER
```yaml
grafana:
  sidecar:
    datasources:
      enabled: true
      label: grafana_datasource
      searchNamespace: ALL
      defaultDatasourceEnabled: false
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki-stack.loki-stack:3100/
      access: proxy
    - name: VictoriaMetrics
      type: prometheus
      url: http://victoria-metrics-single-server.victoria-metrics-single:8428
      access: proxy
```

**Comment by galindro** [comment]
I just figured out how to implement a workaround for it. The datasource will never being added because the method used to add datasources to grafana is being done by an init-container called `grafana-sc-datasource` which is part of the grafana statefulset. This container will run only at the creation of the statefulset's pod.

To force the pod's recreation, I just added an annotation called timestamp with a timestamp value that should be updated each time a helm upgrade runs. I copy this approach from [here](https://github.com/helm/helm/issues/5218#issuecomment-458794628).

In my case I'm using [helmsman](https://github.com/Praqma/helmsman/) for helm chart management. So, I can define a shell an environment variable that controls its value.

```yaml
grafana:
  enabled: true
  podAnnotations:
    timestamp: "${PROMETHEUS_OPERATOR_GRAFANA_POD_ANNOTATION_TIMESTAMP}"
```

Then, I just need to do this:

`export PROMETHEUS_OPERATOR_GRAFANA_POD_ANNOTATION_TIMESTAMP=$(date +%s) && helmsman  -force-upgrades -apply -subst-env-values -target prometheus-operator -f main.yaml`

But I figured out that the datasources are only being added not replaced or removed.
