### ISSUE TITLE
Problem setting up grafana Ingress on GCE 

### ISSUE THREAD

**Issue by Piusdan** [coreos/prometheus-operator#1910]
**What I did?**
I installed grafana on GCE using helm, with a global static IP and domain name
this are my values
```yaml
grafana:
  service:
      type: NodePort
  auth:
    anonymous:
      enabled: "false"
  adminPassword: "mypassword"
  adminUser: "myuser"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "gce"
      kubernetes.io/ingress.global-static-ip-name: [MY-GLOBAL-STATIC-IP]
      kubernetes.io/tls-acme: "true"
      certmanager.k8s.io/acme-http01-edit-in-place: "true"
      certmanager.k8s.io/acme-challenge-type: "http01"
      certmanager.k8s.io/cluster-issuer: [MY-CLUSTER-ISSURER]
    hosts:
      - [MY-DOMAIN-NAME]
    tls:
      - secretName: [MY-TLS-CERT]
        hosts:
          - [MY-DOMAIN-NAME]
```

**What I expected to see**
Heading to [MY-DOMAIN-NAME] is supposed to take me to the my grafana dashboard.
Instead my request times out. 

**Environment**

* Prometheus Operator version:

	`image tag: v0.20.0`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.6-gke.2", GitCommit:"384b4eaa132ca9a295fcb3e5dfc74062b257e7df", GitTreeState:"clean", BuildDate:"2018-08-15T00:10:14Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	`gke`

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

Output of `$ kubectl describe ing -n monitoring`
```
Name:             cluster-monitor-grafana
Namespace:        monitoring
Address:          [MY-IP-ADDRESS]
Default backend:  default-http-backend:80 (10.0.2.10:8080)
TLS:
  [MY-TLS-CERT] terminates  [MY-DOMAIN-NAME] 
Rules:
  Host                       Path  Backends
  ----                       ----  --------
 [MY-DOMAIN-NAME]  
                                                                                                       cluster-monitor-grafana:80 (<none>)
                             /.well-known/acme-challenge/NWlJWG0yF2ZqPY_NkGM-eeBL-mutK_HbafbSyDUvhLw   cm-acme-http-solver-2m7kq:8089 (<none>)
Annotations:
  certmanager.k8s.io/acme-http01-edit-in-place:  true
  certmanager.k8s.io/cluster-issuer:             [MY-CLUSTER-ISSURER]
  ingress.kubernetes.io/backends:                {"k8s-be-30902--912e3a354e8534b8":"HEALTHY","k8s-be-31653--912e3a354e8534b8":"HEALTHY","k8s-be-32488--912e3a354e8534b8":"HEALTHY"}
  ingress.kubernetes.io/https-forwarding-rule:   k8s-fws-monitoring-cluster-monitor-grafana--912e3a354e8534b8
  ingress.kubernetes.io/ssl-cert:                k8s-ssl-af37c676614723cb-795d0ed43abba0f1--912e3a354e8534b8
  ingress.kubernetes.io/target-proxy:            k8s-tp-monitoring-cluster-monitor-grafana--912e3a354e8534b8
  kubernetes.io/ingress.global-static-ip-name:   [MY-GLOBAL-STATIC-IP-NAME]
  certmanager.k8s.io/acme-challenge-type:        http01
  kubernetes.io/tls-acme:                        true
  ingress.kubernetes.io/https-target-proxy:      k8s-tps-monitoring-cluster-monitor-grafana--912e3a354e8534b8
  ingress.kubernetes.io/url-map:                 k8s-um-monitoring-cluster-monitor-grafana--912e3a354e8534b8
  kubernetes.io/ingress.class:                   gce
  ingress.kubernetes.io/forwarding-rule:         k8s-fw-monitoring-cluster-monitor-grafana--912e3a354e8534b8
Events:
  Type    Reason             Age   From                     Message
  ----    ------             ----  ----                     -------
  Normal  ADD                46m   loadbalancer-controller  monitoring/cluster-monitor-grafana
  Normal  CreateCertificate  46m   cert-manager             Successfully created Certificate [MY-TLS-CERT]
  Normal  CREATE             45m   loadbalancer-controller  ip: [MY-IP-ADDRESS]

```
