### ISSUE TITLE
Cross Namespace Monitoring using namespaceSelector with kube-prometheus manifests

### ISSUE THREAD

**Issue by RakV1342** [coreos/prometheus-operator#1921]
**What did you do?**
I have a pod and a corresponding service running in the ```monitoring```, ```default``` and ```trial``` namespaces. Using the "namespaceSelector.matchLabels" I am trying to use a serviceMonitor to detect this pod/service from all three namespaces. 

**What did you expect to see?**
I expected prometheus to detect the pods from all three namespaces rak-app (monitoring ns), rak-app-def (default ns) and rak-app-trial (trial ns).

**What did you see instead? Under which circumstances?**
Prometheus is only able to detect pods from the monitoring and default namespaces. The pod running in the trial namespace goes undetected. Although it should not matter, I tried running the serviceMonitor in the ```monitoring```, ```default```, and ```trial``` namespace. The pod in the ```trial``` namespace was not detected in any of the three cases.

**Environment**
I have deployed prometheus operator using the kube-prometheus manifests. A minor change to ```serviceMonitorNamespaceSelector``` and ```serviceMonitorSelector``` fields of prometheus-prometheus.yaml  was made (seen in yaml below)

* Prometheus Operator version: 0.22.2

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T09:56:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 
	Using kubeadm

* Manifests:
prometheus-prometheus.yaml
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: v2.3.1
```

rak-app-serviceMonitoring-default.yaml
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: rak-app
  name: rak-app
#  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: rakport
#  jobLabel: app
  selector:
    matchLabels:
      k8s-app: rak-app
  namespaceSelector:
    matchNames:
    - monitoring
    - default
    - trial
```

rak-app-service-trial.yaml
```
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: rak-app
  name: rak-app-trial
  namespace: trial
spec:
  clusterIP: None
  ports:
  - name: rakport
    port: 8080
    targetPort: 8080
  selector:
    app: rak-app
```

**Comment by brancz** [comment]
If you look at the logs of the Prometheus server you are likely going to find RBAC errors. The default namespaces are listed [here](https://github.com/coreos/prometheus-operator/blob/2c6ac20c1f032f4f5d0d8d1a4fd55a68158fdfea/contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet#L24) and you can merge any additional namespaces you want to monitor into that. Or alternatively you can create a ClusterRole giving Prometheus permission to read everything in the cluster, however that would violate the least privilege principle.

**Comment by ekarlso** [comment]
I have the same problem using the helm charts for kube-prometheus, any idea on that @brancz ?

**Comment by brancz** [comment]
I don’t know whether this is possible with the helm charts, we don’t maintain them, they are separately maintained.

**Comment by ekarlso** [comment]
Well I am trying something like 
```
repositories:
  - name: coreos
    url: https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/

releases:
- name: prometheus-operator
  namespace: monitoring
  chart: coreos/prometheus-operator
  version: 0.0.29
  values: 
    - image:
        tag: v0.23.2
    - prometheusConfigReloader:
        tag: v0.23.2
    - configmapReload:
        tag: v0.0.1
  
- name: kube-prometheus
  namespace: monitoring
  chart: coreos/kube-prometheus
  values:
    - prometheus:
        ingress:
          enabled: false
          hosts:
            - "prometheus.test.jqs.evry.site"
          annotations:
            kubernetes.io/ingress.class: traefik
        # serviceMonitorsSelector: {}
        serviceMonitorNamespaceSelector: {}
        imagePullSecrets:
          - name: foo
    - grafana:
        ingress:
          enabled: false
          hosts:
            - "monitor.test.jqs.evry.site"
          annotations:
            kubernetes.io/ingress.class: traefik
  set:
    - name: deployKubeScheduler
      value: true
    - name: deployKubeControllerManager
      value: true
```

So I wonder what happens since it doesnt work.

**Comment by ekarlso** [comment]
@brancz how is it that maintains the charts in that case ?

**Comment by brancz** [comment]
I don't know, as I don't use or maintain the helm charts. @gianrubio maintains them.

**Comment by admoriarty** [comment]
I'm also interesting in knowing if the current helm charts (or possibly those coming under https://github.com/helm/charts/pull/6765) will support additional namespaces as an install time param...any clues would be appreciated @gianrubio :)

**Comment by RakV1342** [comment]
@brancz , As you mentioned, there were rbac errors with the prometheus and on providing prometheus with full access to the cluster (yaml given below) prometheus could collect stats from the pod in the "trial" namespace. 

Is there a **recommended way** for prometheus to detect pods across different user created namespaces, without breaking the least privilege principle and without having to edit any [code](https://github.com/coreos/prometheus-operator/blob/2c6ac20c1f032f4f5d0d8d1a4fd55a68158fdfea/contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet#L24) from the repo?


```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-k8s
rules:
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  - namespaces
  - services
  - endpoints
  - pods
  verbs:
  - get
- nonResourceURLs:
  - /metrics
  verbs:
  - get
```
