### ISSUE TITLE
Persistentvolume Not Creating 

### ISSUE THREAD

**Issue by manuprometheus** [coreos/prometheus-operator#1922]
**What did you do?**
We are planing to create a persistent storage for Prometheus.
**What did you expect to see?**
We need Persistent storage for prometheus.
**What did you see instead? Under which circumstances?**
While describing the pod, we are getting the following error:

Warning  FailedScheduling  7s (x5 over 14s)  default-scheduler  persistentvolume "prometheus" not found (repeated 6 times)

**Environment**

* Prometheus Operator version:

	insert image tag or Git SHA here

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by manuprometheus** [comment]
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  retention: 4320h
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: ssd
        resources:
          requests:
             storage: 400Gi

  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: v2.3.2
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ssd
provisioner: kubernetes.io/gce-pd 
parameters:
  type: pd-ssd 
  zone: us-east1-b
```

**Comment by manuprometheus** [comment]
Also I have tried the following yamlś and I am getting the following errors:

```
kind: Prometheus

metadata:

  labels:

    prometheus: k8s

  name: k8s

  namespace: monitoring

spec:

  retention: 4320h

  alerting:

    alertmanagers:

    - name: alertmanager-main

      namespace: monitoring

      port: web

  baseImage: quay.io/prometheus/prometheus

  nodeSelector:

    beta.kubernetes.io/os: linux

  replicas: 1

  storage:

    volumeClaimTemplate:

      spec:

        selector:

          matchLabels: 

            app: k8s

        resources: 

          requests:

            storage: 400Gi
        storageClassName:  prometheustest

 

  resources:

    requests:

      memory: 400Mi

  ruleSelector:

    matchLabels:

      prometheus: k8s

      role: alert-rules

  serviceAccountName: prometheus-k8s
 
  serviceMonitorNamespaceSelector: {}

  serviceMonitorSelector:

    matchExpressions:

    - key: k8s-app

      operator: Exists

  version: v2.3.1

---

apiVersion: v1

kind: PersistentVolume

metadata:

  name: prometheus

  labels:

    app: k8s

spec:
  storageClassName: prometheustest
  capacity:

    storage: 400Gi

  accessModes:

  - ReadWriteOnce # required
  gcePersistentDisk:
    fsType: "ext4"
    pdName: pd-ssd
```
ERROR:

Error from server (Forbidden): error when creating "prometheus-prometheus.yaml": persistentvolumes "prometheus" is forbidden: error querying GCE PD volume pd-ssd: disk is not found

**Comment by manuprometheus** [comment]
This is a Kops based GCE cluster.

**Comment by andrealmar** [comment]
@manuprometheus I see that you've defined `storageClassName: prometheustest`
Have you created this `StorageClass` ?

In my tests I've came across this error when I was trying to create a `StorageClass`. I've decided to go with the `standard` Storage class instead of creating a new one for Prometheus. 

So, in my `custom-values.yml` file there is something like this: 

```
prometheus:
  storageSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: standard
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
```
