### ISSUE TITLE
Clarification on labels and relabling

### ISSUE THREAD

**Issue by sc250024** [coreos/prometheus-operator#1928]
Greetings,

Sorry again for the n00b question. I've seen countless issues regarding labels and relabeling:

- https://github.com/coreos/prometheus-operator/issues/242
- https://github.com/coreos/prometheus-operator/issues/1166
- https://github.com/coreos/prometheus-operator/issues/1548
- https://github.com/coreos/prometheus-operator/issues/1805

And I'm not sure if my case fits into those or not. I'm having an issue with the SNMP exporter; I actually first posted this as an issue in the `snmp_exporter` repo (https://github.com/prometheus/snmp_exporter/issues/336), but I believe it applies more to Prometheus operator, and how the `ServiceMonitor` handles labels / relabeling. I also thoroughly read this issue, [How to use snmp_exporter with prometheus-operator?](https://github.com/coreos/prometheus-operator/issues/1177), but it did not contain information about this use case. **I would be happy to add documentation for this since I know the `blackbox_exporter` works in a similar way.**

I'm deploying the `snmp_exporter` using the `snmp-exporter-deployment.yaml` and `snmp-exporter-service.yaml` manifests below. Basically I'm creating a `ServiceMonitor` resource to monitor two (and later many more) SNMP targets: `10.161.XX.YY` and `10.161.XX.YZ`. While this "works" (i.e. the targets are being scraped), from what I can tell, Prometheus cannot distinguish between these two targets because the labels are exactly the same. As I understand it, every target needs a unique set of labels.

@SuperQ was nice enough to suggest a solution https://github.com/prometheus/snmp_exporter/issues/336#issuecomment-423690018. He suggested the the Prometheus config should look like this, in the end:

```yaml
  - job_name: monitoring/snmp-exporter/0
    ...
    static_configs:
    - targets:
      - 10.161.XX.YY
      - 10.161.XX.YZ
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter.monitoring.svc.cluster.local:9116
```

Something similar is mentioned on this page (https://www.robustperception.io/icmp-pings-with-the-blackbox-exporter), which is a blog from the `snmp_exporter` maintainer, I believe.

**What did you do?**

I tried to replicate @SuperQ 's suggestion by using the `ServiceMonitor` manifest `snmp-exporter-servicemonitor.yaml` below. 

**What did you expect to see?**

The Prometheus operator reads the `ServiceMonitor` manifest, and appropriately renders the relabelings according to @SuperQ 's suggestion above.

**What did you see instead? Under which circumstances?**

The Prometheus config contains none of the relabelings.

<details><summary>prometheus-config-after.yaml</summary><p>

```yaml
- job_name: monitoring/snmp-exporter/0
  params:
    module:
    - if_mib_ifdescr
    target:
    - 10.161.XX.YY
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /snmp
  scheme: http
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - monitoring
  relabel_configs:
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: http-metrics
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_service_label_snmp_exporter]
    separator: ;
    regex: (.+)
    target_label: job
    replacement: ${1}
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: http-metrics
    action: replace
- job_name: monitoring/snmp-exporter/1
  params:
    module:
    - if_mib_ifdescr
    target:
    - 10.161.XX.YZ
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /snmp
  scheme: http
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - monitoring
  relabel_configs:
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: http-metrics
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_service_label_snmp_exporter]
    separator: ;
    regex: (.+)
    target_label: job
    replacement: ${1}
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: http-metrics
    action: replace
```

</p></details>

**Environment**

* Prometheus Operator version: **quay.io/coreos/prometheus-operator:v0.23.2**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:36Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.8", GitCommit:"7eab6a49736cc7b01869a15f9f05dc5b49efb9fc", GitTreeState:"clean", BuildDate:"2018-09-14T15:54:20Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: **kops**

* Manifests:

<details><summary>snmp-exporter-deployment.yaml</summary><p>

```yaml
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: snmp-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snmp-exporter
  template:
    metadata:
      labels:
        app: snmp-exporter
    spec:
      containers:
      - image: prom/snmp-exporter:v0.13.0
        args:
          - --config.file=/etc/snmp_exporter/snmp.yml
          - --log.level=debug
        name: snmp-exporter
        imagePullPolicy: Always
        ports:
        - containerPort: 9116
          name: metrics

```

</p></details>

<details><summary>snmp-exporter-service.yaml</summary><p>

```yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: snmp-exporter
  name: snmp-exporter
spec:
  ports:
  - name: http-metrics
    port: 9116
    protocol: TCP
    targetPort: metrics
  selector:
    app: snmp-exporter
```

</p></details>

<details><summary>snmp-exporter-servicemonitor.yaml</summary><p>

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: kube-prometheus
  name: snmp-exporter
spec:
  jobLabel: snmp-exporter
  selector:
    app: snmp-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  metricRelabelings:
    - sourceLabels: [__address__]
      targetLabel: __param_target
    - sourceLabels: [__param_target]
      targetLabel: instance
    - sourceLabels: __address__
      replacement: snmp-exporter.monitoring.svc.cluster.local:9116
  endpoints:
  - interval: 60s
    port: http-metrics
    params:
      module:
      - if_mib_ifdescr
      target:
      - 10.161.XX.YY
    path: "/snmp"
    scrapeTimeout: 10s
    targetPort: 9116
  - interval: 60s
    port: http-metrics
    params:
      module:
      - if_mib_ifdescr
      target:
      - 10.161.XX.YZ
    path: "/snmp"
    scrapeTimeout: 10s
    targetPort: 9116
```

</p></details>

* Prometheus Operator Logs:

<details><summary>Example scrape logs of the two targets</summary><p>

```
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:00Z" level=debug msg="Scraping target '10.161.XX.YY' with module 'if_mib_ifdescr'" source="main.go:86"
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:00Z" level=debug msg="Getting 1 OIDs from target \"10.161.XX.YY\"" source="collector.go:103"
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:01Z" level=debug msg="Get of 1 OIDs completed in 411.884103ms" source="collector.go:109"
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:01Z" level=debug msg="Walking target \"10.161.XX.YY\" subtree \"1.3.6.1.2.1.2\"" source="collector.go:133"
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:02Z" level=debug msg="Walk of target \"10.161.XX.YY\" subtree \"1.3.6.1.2.1.2\" completed in 1.378478029s" source="collector.go:143"
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:02Z" level=debug msg="Walking target \"10.161.XX.YY\" subtree \"1.3.6.1.2.1.31.1.1\"" source="collector.go:133"
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:03Z" level=debug msg="Walk of target \"10.161.XX.YY\" subtree \"1.3.6.1.2.1.31.1.1\" completed in 1.039587585s" source="collector.go:143"
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:03Z" level=debug msg="Scrape of target '10.161.XX.YY' with module 'if_mib_ifdescr' took 2.836433 seconds" source="main.go:97"
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:16Z" level=debug msg="Scraping target '10.161.XX.YZ' with module 'if_mib_ifdescr'" source="main.go:86"
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:16Z" level=debug msg="Getting 1 OIDs from target \"10.161.XX.YZ\"" source="collector.go:103"
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:17Z" level=debug msg="Get of 1 OIDs completed in 781.99541ms" source="collector.go:109"
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:17Z" level=debug msg="Walking target \"10.161.XX.YZ\" subtree \"1.3.6.1.2.1.2\"" source="collector.go:133"
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:19Z" level=debug msg="Walk of target \"10.161.XX.YZ\" subtree \"1.3.6.1.2.1.2\" completed in 1.974728038s" source="collector.go:143"
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:19Z" level=debug msg="Walking target \"10.161.XX.YZ\" subtree \"1.3.6.1.2.1.31.1.1\"" source="collector.go:133"
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:19Z" level=debug msg="Scraping target '10.161.XX.YZ' with module 'if_mib_ifdescr'" source="main.go:86"
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:19Z" level=debug msg="Getting 1 OIDs from target \"10.161.XX.YZ\"" source="collector.go:103"
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:20Z" level=debug msg="Get of 1 OIDs completed in 120.038903ms" source="collector.go:109"
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:20Z" level=debug msg="Walking target \"10.161.XX.YZ\" subtree \"1.3.6.1.2.1.2\"" source="collector.go:133"
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:20Z" level=debug msg="Walk of target \"10.161.XX.YZ\" subtree \"1.3.6.1.2.1.31.1.1\" completed in 1.131724596s" source="collector.go:143"
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:20Z" level=debug msg="Scrape of target '10.161.XX.YZ' with module 'if_mib_ifdescr' took 3.894816 seconds" source="main.go:97"
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:21Z" level=debug msg="Walk of target \"10.161.XX.YZ\" subtree \"1.3.6.1.2.1.2\" completed in 1.375522601s" source="collector.go:143"
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:21Z" level=debug msg="Walking target \"10.161.XX.YZ\" subtree \"1.3.6.1.2.1.31.1.1\"" source="collector.go:133"
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:22Z" level=debug msg="Walk of target \"10.161.XX.YZ\" subtree \"1.3.6.1.2.1.31.1.1\" completed in 1.110019915s" source="collector.go:143"
monitoring snmp-exporter-79f7877df5-n5pd7 snmp-exporter time="2018-09-24T08:57:22Z" level=debug msg="Scrape of target '10.161.XX.YZ' with module 'if_mib_ifdescr' took 2.610892 seconds" source="main.go:97"
```

</p></details>

Screenshot of the targets, with the same labels:

<img width="1172" alt="screen shot 2018-09-24 at 10 58 48" src="https://user-images.githubusercontent.com/8792243/45944096-3444a800-bfe9-11e8-891b-9b30f49affbc.png">

**Comment by brancz** [comment]
metric relabelling is performed on metrics at ingestion time, whereas you are looking for relabelling of targets, for which we just merged #1879, this will be part of the next release. However, same as @metalmatze's comment, target relabelling will also be a field of an endpoint.

**Comment by sc250024** [comment]
@metalmatze @brancz Thanks for the replies, and for your help! 

Some final questions:

1. For a documentation update, should I put this under `Documentation/user-guides/` ?

2. If I needed to add `n` more endpoints, would I then need to add the block...

```diff
  - interval: 60s
    port: http-metrics
    params:
      module:
      - if_mib_ifdescr
      target:
      - 10.161.XX.YY
    path: "/snmp"
    scrapeTimeout: 10s
    targetPort: 9116
+   metricRelabelings:
+    - sourceLabels: [__address__]
+      targetLabel: __param_target
+    - sourceLabels: [__param_target]
+      targetLabel: instance
+    - sourceLabels: __address__
+      replacement: snmp-exporter.monitoring.svc.cluster.local:9116
```

...`n` more times, or is there a better way to add multiple targets, each with the same config (save for the endpoint address) ?

3. @brancz How would the above snippet change with the next release?

**Comment by sc250024** [comment]
Hmm, with @metalmatze 's suggestion, it throws a validation error:

```
The ServiceMonitor "snmp-exporter" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"monitoring.coreos.com/v1", "kind":"ServiceMonitor", "metadata":map[string]interface {}{"generation":1, "uid":"6dba1ddf-c006-11e8-b266-020952d98990", "selfLink":"", "labels":map[string]interface {}{"prometheus":"kube-prometheus"}, "name":"snmp-exporter", "namespace":"monitoring", "annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"monitoring.coreos.com/v1\",\"kind\":\"ServiceMonitor\",\"metadata\":{\"annotations\":{},\"labels\":{\"prometheus\":\"kube-prometheus\"},\"name\":\"snmp-exporter\",\"namespace\":\"monitoring\"},\"spec\":{\"endpoints\":[{\"interval\":\"60s\",\"metricRelabelings\":[{\"sourceLabels\":[\"__address__\"],\"targetLabel\":\"__param_target\"},{\"sourceLabels\":[\"__param_target\"],\"targetLabel\":\"instance\"},{\"replacement\":\"snmp-exporter.monitoring.svc.cluster.local:9116\",\"sourceLabels\":\"__address__\"}],\"params\":{\"module\":[\"if_mib_ifdescr\"],\"target\":[\"10.161.XX.YY\"]},\"path\":\"/snmp\",\"port\":\"http-metrics\",\"scrapeTimeout\":\"10s\",\"targetPort\":9116}],\"jobLabel\":\"snmp-exporter\",\"namespaceSelector\":{\"matchNames\":[\"monitoring\"]},\"selector\":{\"app\":\"snmp-exporter\"}}}\n"}, "creationTimestamp":"2018-09-24T14:30:47Z", "clusterName":""}, "spec":map[string]interface {}{"namespaceSelector":map[string]interface {}{"matchNames":[]interface {}{"monitoring"}}, "selector":map[string]interface {}{"app":"snmp-exporter"}, "endpoints":[]interface {}{map[string]interface {}{"params":map[string]interface {}{"module":[]interface {}{"if_mib_ifdescr"}, "target":[]interface {}{"10.161.XX.YY"}}, "path":"/snmp", "port":"http-metrics", "scrapeTimeout":"10s", "targetPort":9116, "interval":"60s", "metricRelabelings":[]interface {}{map[string]interface {}{"sourceLabels":[]interface {}{"__address__"}, "targetLabel":"__param_target"}, map[string]interface {}{"sourceLabels":[]interface {}{"__param_target"}, "targetLabel":"instance"}, map[string]interface {}{"replacement":"snmp-exporter.monitoring.svc.cluster.local:9116", "sourceLabels":"__address__"}}}}, "jobLabel":"snmp-exporter"}}: validation failure list:
spec.endpoints.metricRelabelings.sourceLabels in body must be of type array: "string"
```

Here is the `ServiceMonitor` definition exactly:

<details><summary>snmp-exporter-servicemonitor-v2.yaml</summary><p>

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: kube-prometheus
  name: snmp-exporter
spec:
  jobLabel: snmp-exporter
  selector:
    app: snmp-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - interval: 60s
    port: http-metrics
    params:
      module:
      - if_mib_ifdescr
      target:
      - 10.161.XX.YY
    metricRelabelings:
      - sourceLabels: [__address__]
        targetLabel: __param_target
      - sourceLabels: [__param_target]
        targetLabel: instance
      - sourceLabels: __address__
        replacement: snmp-exporter.monitoring.svc.cluster.local:9116
    path: "/snmp"
    scrapeTimeout: 10s
    targetPort: 9116
```

</p></details>

**Comment by prasadbhagwat93** [comment]
@sc250024 Did above solution work you? I have below code, I do not see target label?

`apiVersion: test-monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: snmp-exporter
  labels:
    test-app: snmp-exporter
  namespace: test-monitoring
spec:
  jobLabel: test-app
  endpoints:
  - interval: 60s 
    port: http
    metricRelabelings:
    - sourceLabels: [__address__]
      targetLabel: __param_target
    - sourceLabels: [__param_target]
      targetLabel: instance
    - sourceLabels: [__address__]
      replacement: snmp-exporter.test-monitoring.svc.cluster.local:9116
    scheme: http
    params:
      module:
      - isilon8
      target:
      - 10.40.28.41
    path: "/snmp"
  - interval: 60s 
    port: http
    metricRelabelings:
    - sourceLabels: [__address__]
      targetLabel: __param_target
   - sourceLabels: [__param_target]
      targetLabel: instance
    - sourceLabels: [__address__]
      replacement: snmp-exporter.test-monitoring.svc.cluster.local:9116
    scheme: http
    params:
      module:
      - isilon8
      target:
      - 10.40.28.42
    path: "/snmp"
  selector:
    matchLabels:
      test-app: snmp-exporter
  namespaceSelector:
    matchNames:
    - test-monitoring`

**Comment by brancz** [comment]
As I said above the snippet above does not what you want. It rewrites metrics not targets. Target relabeling is why we just merged in the referenced PR.

**Comment by sc250024** [comment]
@prasadbhagwat93 It did not work, no, but it looks like from the comment from @brancz that it will be included in the next release (whatever is coming after 0.23.2)

**Comment by prasadbhagwat93** [comment]
@sc250024 Did you add documentation? 
```
metricRelabelings:
    - sourceLabels: [__address__]
      targetLabel: __param_target
   - sourceLabels: [__param_target]
      targetLabel: instance
    - sourceLabels: [__address__]
      replacement: snmp-exporter.test-monitoring.svc.cluster.local:9116
```
In the above, I think right way of third labeling is `targetLabel: __address__` ?
Also should `metricRelabelings` be changed to `hostRelabeling` or something similar?

**Comment by sc250024** [comment]
@prasadbhagwat93 No not yet. I see that they realeased today, so this weekend I will have a look, and add it. 

@brancz For a documentation update, should I put this under Documentation/user-guides/ ?

**Comment by sc250024** [comment]
@@prasadbhagwat93 Just tried with the new Prom operator v0.24.0, and couldn't get it to work. If I take out the `metricRelabelings` section, Prometheus picks it up; if I include them, it does not.

Did you have any luck?

**Comment by brancz** [comment]
Can you share your ServiceMonitor?

**Comment by sc250024** [comment]
@brancz Thanks for the quick response. I noticed something about my original post that may have been misunderstood. I'll explain as best I can.

This post (https://www.robustperception.io/icmp-pings-with-the-blackbox-exporter) explains basically what I was initially trying to do. I'm really looking to implement `relabel_configs` because, I'm not looking to rename / drop metrics; I was really just trying to ensure that my `instance` labels were re-written with the `__param_target` label so that metrics were not grouped together, and were properly separated by my SNMP target.

The `servicemonitor.yaml` file below works fine actually; it's just that, when it gets applied to Prometheus, that section is going to `metric_relabel_configs` (as it should) instead of `relabel_configs` as I initially wanted.

<details><summary>servicemonitor.yaml</summary><p>

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: kube-prometheus
  name: snmp-exporter
spec:
  jobLabel: snmp-exporter
  selector:
    app: snmp-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - interval: 60s
    port: http-metrics
    params:
      module:
      - teltonika
      target:
      - 10.161.XX.YY
    metricRelabelings:
      - action: replace
        sourceLabels: [__param_target]
        targetLabel: instance
    path: "/snmp"
    scrapeTimeout: 30s
    targetPort: 9116
  - interval: 60s
    port: http-metrics
    params:
      module:
      - teltonika
      target:
      - 10.161.XX.YZ
    metricRelabelings:
      - action: replace
        sourceLabels: [__param_target]
        targetLabel: instance
    path: "/snmp"
    scrapeTimeout: 30s
    targetPort: 9116
```

</p></details>

<details><summary>prometheus-result-config.yaml</summary><p>

```yaml
- job_name: monitoring/snmp-exporter/0
  params:
    module:
    - teltonika
    target:
    - 10.161.XX.YY
  scrape_interval: 1m
  scrape_timeout: 30s
  metrics_path: /snmp
  scheme: http
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - monitoring
  relabel_configs:
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: http-metrics
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    regex: Node;(.*)
    target_label: node
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    regex: Pod;(.*)
    target_label: pod
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_service_label_snmp_exporter]
    separator: ;
    regex: (.+)
    target_label: job
    replacement: ${1}
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: http-metrics
    action: replace
  metric_relabel_configs:
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
- job_name: monitoring/snmp-exporter/1
  params:
    module:
    - teltonika
    target:
    - 10.161.XX.YZ
  scrape_interval: 1m
  scrape_timeout: 30s
  metrics_path: /snmp
  scheme: http
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - monitoring
  relabel_configs:
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: http-metrics
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    regex: Node;(.*)
    target_label: node
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    regex: Pod;(.*)
    target_label: pod
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_service_label_snmp_exporter]
    separator: ;
    regex: (.+)
    target_label: job
    replacement: ${1}
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: http-metrics
    action: replace
  metric_relabel_configs:
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
```

</p></details>

**Comment by metalmatze** [comment]
@sc250024 
You can specify relabel_configs per endpoint for a ServiceMonitor. They are called `relabelings`. 
https://github.com/coreos/prometheus-operator/blob/master/pkg/client/monitoring/v1/types.go#L495

**Comment by prasadbhagwat93** [comment]
Hi @sc250024 , I did not have any luck either with new operator, instead made use of `additionalScrapeConfigs` to find the way out. (as static targets)

**Comment by brancz** [comment]
Unless you want to probe pods, you likely don't want to use the ServiceMonitor to do this but the `additionalScrapeConfigs` instead.

**Comment by swaroopkundeti** [comment]
Is it possible to put the straight forward config for having targets replaced with their ip address or names instead of snmp exporters ip address? If you look at the attached picture you'd see the endpoints are pointing to snmp exporter ip address instead of targets. 
<img width="1427" alt="screen shot 2018-11-20 at 12 59 45 pm" src="https://user-images.githubusercontent.com/4454285/48793232-4f1f5a00-ecc4-11e8-8e64-db73d21e37c5.png">

**Comment by brancz** [comment]
I don’t know the snmp exporter well enough to answer your question, I’d suggest you to ask on the Prometheus users mailing list, there are lots of people much more knowledgeable around the snmp exporter there that can competently answer you :)

**Comment by swaroopkundeti** [comment]
@brancz Thank you for your response. SNMP exporter is working on my sand box as expected when I run it with Prometheus. 

<b>Prometheus+SNMP exporter:</b>
See below screen shots. In labels section instance is pointing to target ip address and not to the export ip address. 

My configuration with prometheus + snmp 
<pre>
global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'snmp'
    metrics_path: /snmp
    params:
      module: [if_mib]
    static_configs:
      - targets:
        - 10.94.148.223  # SNMP device - add your IPs here
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116  # SNMP exporter.
</pre>
<img width="597" alt="screen shot 2018-11-21 at 11 46 40 am" src="https://user-images.githubusercontent.com/4454285/48856023-59ecf400-ed83-11e8-971f-792df9ac3278.png">
<img width="1429" alt="screen shot 2018-11-21 at 11 46 53 am" src="https://user-images.githubusercontent.com/4454285/48856024-59ecf400-ed83-11e8-8a55-f587a0244a25.png">

<b>Prometheus-operator + SNMP exportter</b>

Configuration file:
<pre>
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: kube-prometheus
  name: snmp-exporter
spec:
  jobLabel: snmp-exporter
  selector:
    app: snmp-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - interval: 60s
    params:
      module: [if_mib]
    static_config:
      - target:
        - 10.94.148.223
    metricRelabelings:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: snmp-exporter.monitoring.svc:9116
    metrics_path: "/snmp"
    scrapeTimeout: 30s
- interval: 60s
    #port: http-metrics
    params:
      module: [if_mib]
    static_configs:
      - targets:
        - 10.94.148.220
    metricRelabelings:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: snmp-exporter.monitoring.svc:9116
    metrics_path: "/snmp"
    scrapeTimeout: 30s
</pre>
 
<img width="1432" alt="screen shot 2018-11-21 at 11 50 30 am" src="https://user-images.githubusercontent.com/4454285/48856178-bf40e500-ed83-11e8-89cc-13fe1ef8b845.png">

If you see label section in above screenshot you will notice instance is actually pointing to snmp exporter. Can you tell me where these labels are coming from and how I can change it to have target device ip address instead of snmp exporter pod ip?

**Comment by brancz** [comment]
```
    static_config:
      - target:
        - 10.94.148.223
```

This does not exist in the servicemonitor object. You want to use the `additionalScrapeConfigs` feature.

**Comment by swaroopkundeti** [comment]
@prasadbhagwat93 Can you help me with your `additionalScrapeConfigs`? appreciate if you could upload your configs.

**Comment by prasadbhagwat93** [comment]
add `additionalScrapeConfigs` like below in prometheus object defining file
```
    matchExpressions:
    - key: k8s-app
      operator: Exists
  version: v2.3.1
  additionalScrapeConfigs:
    name: prom-custom
    key: secret.yaml
```
Create secret `prom-custom` with scrape info, sample is below
```
- job_name: 'snmp'
  scrape_timeout: 300s
  scrape_interval: 300s
  static_configs:
    - targets:
      - 10.40.28.41
  metrics_path: /snmp
  params:
    module: [xxxxx]
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: snmp-exporter.test-monitoring.svc.cluster.local:9116  # The SNMP exporter's real hostname:port.
```
Hope this helps!
