### ISSUE TITLE
Empty ServiceMonitorSelector injects match labels block

### ISSUE THREAD

**Issue by agolomoodysaada** [coreos/prometheus-operator#1937]
**What did you do?**

Installed the vanilla default prometheus operator. I also attempted to override it. The operator insists on injecting `match labels` under `service monitor selector`.

The defaults in both `kube-prometheus` and `prometheus` charts

```yaml
serviceMonitorsSelector: {}
```

```yaml
  Service Monitor Selector:
    Match Labels:
      Prometheus:  prometheus
```

**What did you expect to see?**

I want all service monitors to be picked up.

`kubectl describe prometheus prometheus -n monitoring`

```
  Service Monitor Selector: {}
```

**What did you see instead? Under which circumstances?**

Only system monitors matching labels get picked up.

`kubectl describe prometheus prometheus -n monitoring`

```yaml
  Service Monitor Selector:
    Match Labels:
      Prometheus:  prometheus
```

**Environment**

* Prometheus Operator version: 

	0.0.29

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	azure kubernetes service

* Manifests:

```yaml
kube-prometheus:
  global:
    rbacEnable: false
    pspEnable: false
  # Kube-scheduler
  deployKubeScheduler: Flase
  # grafana
  deployGrafana: False

  # Controller Manager
  deployKubeControllerManager: False
  prometheus:
    externalUrl: ""
    resources:
      requests:
        memory: 9G
        cpu: 2
      limits:
        memory: 9G
        cpu: 2
    ### retention of data
    retention: 200d
    ### promtheus storage
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: default
         #  accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 500Gi
  additionalScrapeConfigs: True
  serviceMonitorsSelector: {}
```

**Comment by sebastien-prudhomme** [comment]
Same problem with all other selectors.

For instance i want to use serviceMonitorNamespaceSelector with an empty selector {} to enable monitoring ServiceMonitor in all other namespaces and it doesn't work as the Helm chart use an "if" statement on that value and the result of the "if" is false in case of empty list:

```
{{- if .Values.serviceMonitorNamespaceSelector }}
  serviceMonitorNamespaceSelector:
{{ toYaml .Values.serviceMonitorNamespaceSelector | indent 4 }}
{{- end }}
```

There should not be any "if" at all.

This Helm chart simply don't follow Kubernetes convention on using selectors.

See also #1053

**Comment by sebastien-prudhomme** [comment]
@agolomoodysaada Seems that the chart is migrating in "stable" helm repo, and that the problem is solved helm/charts#6765

Just need to wait

**Comment by vsliouniaev** [comment]
@sebastien-prudhomme @agolomoodysaada this has now been merged. If you find bugs, you can create PRs / issues against helm/charts

**Comment by agolomoodysaada** [comment]
I was able to resolve this by setting `serviceMonitorSelectorNilUsesHelmValues: false`
For example
```yaml
prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
```
