### ISSUE TITLE
prometheus-operator restart complaining about namespaces

### ISSUE THREAD

**Issue by nrobert13** [coreos/prometheus-operator#1944]
**What did you do?**
installed kube-prometheus.
**What did you expect to see?**
no error messages during prometheus-operator startup.
**What did you see instead? Under which circumstances?**
when I kill the operator pod and it gets restarted, it is complaining about all the existing namespaces with the following error. After a while the error messages are gone.

````
level=error ts=2018-09-27T09:06:44.594291197Z caller=operator.go:734 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"monitoring\" does not exist" err=null
````

**Environment**
dev
* Prometheus Operator version:
````
    Image:         quay.io/coreos/prometheus-operator:v0.23.2
    Image ID:      docker-pullable://quay.io/coreos/prometheus-operator@sha256:8211b3eb30cb8591ddf536f1cf62100f5c97659c14d18dd45001acf94dafd713
````
* Kubernetes version information:
````
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
````

* Kubernetes cluster kind: 

kubespray

* Manifests:

```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: prometheus-operator
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --logtostderr=true
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.23.2
        image: quay.io/coreos/prometheus-operator:v0.23.2
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator

```

* Prometheus Operator Logs:

for every existing namespace the following message many times ( but not the same count for all nmaepsaces ) ..

```
level=error ts=2018-09-27T09:06:44.594291197Z caller=operator.go:734 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"monitoring\" does not exist" err=null


```
