### ISSUE TITLE
Obtaining data from a grpc microservice using Prometheus Operator

### ISSUE THREAD

**Issue by deboshrestha** [coreos/prometheus-operator#1969]
We are currently running our application in a Kubernetes cluster along with the Prometheus Operator. The application has some endpoints which when queried provides information on the resource utilization. 

The task here is to use Prometheus Operator and some exporter along with it to query the endpoints of the application and scrape the data in a time series format so that we can analyze it, do some kind of  visualization, predictive analytics  etc.

The application exposes them in a grpc format and we are expected to scrape the data in that manner. 

I wanted to explore the following -

1. Is it even possible for prometheus / prometheus operator to scrape something which is exposed in a grpc format?
2. If so, how can that be achieved, do we need to write an exporter and use a service monitor along with the Prometheus Operator? Or is there already some kind of exporter out there for this? 

Note - We at this point cannot do any kind of direct instrumentation inside the application code and that is strictly a black box for us except for whatever it is exposing via the grpc APIs. 

Any pointer or help in this matter would be extremely appreciated.

**Comment by metalmatze** [comment]
The Prometheus docs say:

> NOTE: Some earlier versions of Prometheus supported an exposition format based on Protocol Buffers (aka Protobuf) in addition to the current text-based format. As of version 2.0, however, Prometheus no longer supports the Protobuf-based format. You can read about the reasoning behind this change in this document.

However, I think that you are not talking about such a exposition format and thus using an exporter seems like the only option. Maybe you can find an exporter that already does what you need: 
https://prometheus.io/docs/instrumenting/exporters/

Otherwise you might need to write an exporter. Please take a look at this page in the docs outlining best practices for writing exporters:
https://prometheus.io/docs/instrumenting/writing_exporters/

**Comment by brancz** [comment]
GRPC is just served with an http server, just have that http server expose the `/metrics` endpoint.

**Comment by deboshrestha** [comment]
@brancz We don't have an http server anywhere in the grpc object exposed by the development team. We need to write a custom exporter to get the data from the grpc object via a custom client , write an exporter and then expose it through a `/metrics` endpoint for Prometheus to read from .

**Comment by brancz** [comment]
gRPC is served by a http2 server, so there is definitely an http server somewhere to serve gRPC.

**Comment by deboshrestha** [comment]
@brancz I was able to get a `/metrics` endpoint expose the metrics we need via a custom python exporter, right now I am doing the following to use that docker image which has the custom exporter -
`zncp-exporter-deployment.yaml`

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: zncp-metrics-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: zncp-metrics-exporter
  template:
    metadata:
      labels:
        k8s-app: zncp-metrics-exporter
      name: zncp-metrics-exporter
    spec:
      containers:
      - image: xxxx/zncp_metrics_exporter:0.2
        imagePullPolicy: "IfNotPresent"
        env:
          - name: IP_DESTINATION
            value: "x.x.x.x"
        name: zncp-metrics-exporter
        ports:
          - containerPort: 9333
            name: zncp-metrics
      imagePullSecrets:
        - name: xxxx
```
`zncp-metrics-exporter-service.yaml`

```
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: zncp-metrics-exporter
  name: zncp-metrics-exporter
spec:
  ports:
    - name: http-metrics
      port: 9333
      protocol: TCP
      targetPort: metrics
  selector:
    k8s-app: zncp-metrics-exporter
```

`zncp-metrics-exporter-service-account.yaml`
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zncp-metrics-exporter
```

And finally - `prometheus-k8s-service-monitor-zncp-metrics-exporter.yaml`
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zncp-metrics-exporter
  labels:
    k8s-app: zncp-metrics-exporter
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: zncp-metrics-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
   - port: zncp-metrics
     scheme: http
     path: "/metrics"
     targetPort: 9333
     interval: 60s
     honorLabels: true
     bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
     tlsConfig:
       insecureSkipVerify: true
```

The deployment above succeeds and creates a pod, where if I manually go in and curl like this , I get the response I am looking for - 
```
curl http://localhost:9333/metrics
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 252022784.0
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 23166976.0
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1541176926.34
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.27
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 6.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1048576.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="7",patchlevel="1",version="3.7.1"} 1.0
# HELP python_gc_collected_objects Objects collected during gc
# TYPE python_gc_collected_objects histogram
...
```

However, somehow Prometheus operator isn't picking this up, and from the Targets dashboard I don't see the endpoint being scraped. Do you have any idea what I might be missing here?
