### ISSUE TITLE
KubeVersionMismatch will always fire on EKS

### ISSUE THREAD

**Issue by willtrking** [coreos/prometheus-operator#1977]
**What did you do?**
Stood up Alertmanager with alerts from kube-prometheus on a fresh AWS EKS cluster

**What did you expect to see?**
KubeVersionMismatch to not fire

**What did you see instead? Under which circumstances?**
KubeVersionMismatch firing

**Environment**

EKS

Hey everyone,

On EKS it seems like the KubeVersionMismatch will always fire, this is due to the fact that on the EKS master nodes, the gitVersion of Kubernetes running comes back as v1.10.3-eks. This is different then what comes back from the kubelet's provided by the standard AWS EKS AMI used to run nodes.

See the following screenshot for an illustration:

![image](https://user-images.githubusercontent.com/1226924/46504698-8bb1f780-c7e3-11e8-9b62-668d140337bf.png)

**Comment by metalmatze** [comment]
Thank you for opening this issue.
The alert rule is defined in another repository and kube-prometheus is depending on this. Could you please open an issue there? Thanks 
https://github.com/kubernetes-monitoring/kubernetes-mixin

**Comment by eduardobaitello** [comment]
https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/144 is fixed. Maybe this issue can be closed.

**Comment by metalmatze** [comment]
Yep, it also trickled down into kube-prometheus by now:

https://github.com/coreos/prometheus-operator/blob/99e5661f8d46ec2173f65b69eeb97f6e52d38e0d/contrib/kube-prometheus/manifests/prometheus-rules.yaml#L710

**Comment by danghung-dev** [comment]
@eduardobaitello  @metalmatze hi, it fired again for me. What should I do? 

![image](https://user-images.githubusercontent.com/5670932/62803083-b8c1eb80-bb13-11e9-9b9c-9cf5c25cf4d5.png)

**Comment by brancz** [comment]
Probably open a ticket against EKS support. Kubernetes should always be deployed with consistent versions.

**Comment by jwhitcraft** [comment]
@danghung-dev the problem is that your masters were updated, but your nodes were not.  Just upgrade your nodes to the latest AMI and you'll be fine.  It's super annoying that AWS doesn't let you know that they have updated your masters.

**Comment by iptizer** [comment]
> @danghung-dev the problem is that your masters were updated, but your nodes were not. Just upgrade your nodes to the latest AMI and you'll be fine. It's super annoying that AWS doesn't let you know that they have updated your masters.

Actually it is even worse. At the moment EKS updated to 1.14.9 but there are no AMIs for 1.14.9 available at the moment...

**Comment by keeganwitt** [comment]
Dumb question: What version of the chart has the fixes for kube-prometheus and kubernetes-mixin?  Or am I misunderstanding how to get the fix?

**Comment by onisim-iacob** [comment]
Hi,

I was facing this issue and after lots of trials and errors, I managed to see that:

- "ROUTES" are processed in sequential order, so I had to place the "Watchdog" and "KubeVersionMismatch" on top of the list. 🛈 Your rule may get ignored if another label matches first. In my case "KubeVersionMismatch" is a "Severity=warning" so my "match severity: warning" rule was applied first. 

![image](https://github.com/prometheus-operator/prometheus-operator/assets/122359339/b2fe8f28-b8e8-4cf3-b984-f79425ce75ba)

This is my whole configuration after switching order of the rules. It behaves as:

- If 1 alert with Alertname is matched, it gets sent to "null".
- If another alert is found the is inhibited.

```
route:
      group_by: [job, alertname, severity, cluster]
      group_wait: 30s
      group_interval: 1m
      repeat_interval: 12h
      receiver: 'email'
      routes:
        - match:
            alertname: Watchdog
          receiver: 'null'
        - match:
            alertname: KubeVersionMismatch
          receiver: 'null'
        - match:
            severity: warning
          receiver: 'email'
          repeat_interval: 6h
          continue: true
        - match:
            severity: critical
          receiver: 'email'
          repeat_interval: 1h
          continue: true
    receivers:
    - name: 'null'
    - name: 'email'
      email_configs:
        - to: alertmanager@domain.com # <--- CHANGE THIS
          send_resolved: true
          headers:
            subject: "[FIRING:{{ len .Alerts }}] {{ .CommonLabels.alertname }} ({{ .CommonLabels.cluster }} {{ .CommonLabels.severity | toUpper }})"
    inhibit_rules:
      - target_match:
          alertname: Watchdog # Watchdog alert is meant to test that everything works as expected, but is not meant to be used by the users
      - target_match:
          alertname: KubeVersionMismatch #  if you are using EKS, you'll probably have an KubeVersionMismatch, because Kubernetes allows a certain version skew -> https://kubernetes.io/releases/version-skew-policy/
```

Going to the Alertmanager you can validate it with: 

![image](https://github.com/prometheus-operator/prometheus-operator/assets/122359339/7f4bb8a7-f51a-4802-b2dd-2af251aa170a)

KR,
