### ISSUE TITLE
 v0.24.0 Kube-prometheus: matching labels must be unique on one side

### ISSUE THREAD

**Issue by mitchellmaler** [coreos/prometheus-operator#2000]
Upgraded the Operator to the latest version v0.24.0 and now prometheus is complaining about a rule that is provided by the kube-prometheus manifests.

```
level=warn ts=2018-10-11T14:46:48.584387904Z caller=manager.go:389 component="rule manager" group=alertmanager.rules msg="Evaluating rule failed" rule="alert: AlertmanagerConfigInconsistent\nexpr: count_values by(service) (\"config_hash\", alertmanager_config_hash{job=\"alertmanager-main\"})\n  / on(service) group_left() label_replace(prometheus_operator_spec_replicas{job=\"prometheus-operator\"},\n  \"service\", \"alertmanager-$1\", \"alertmanager\", \"(.*)\") != 1\nfor: 5m\nlabels:\n  severity: critical\nannotations:\n  message: The configuration of the instances of the Alertmanager cluster `{{$labels.service}}`\n    are out of sync.\n" err="many-to-many matching not allowed: matching labels must be unique on one side"
```

The rule that is set is: 
```
- alert: AlertmanagerConfigInconsistent
  annotations:
    message: The configuration of the instances of the Alertmanager cluster `{{$labels.service}}`
      are out of sync.
  expr: |
    count_values("config_hash", alertmanager_config_hash{job="alertmanager-main"}) BY (service) / ON(service) GROUP_LEFT() label_replace(prometheus_operator_spec_replicas{job="prometheus-operator"}, "service", "alertmanager-$1", "alertmanager", "(.*)") != 1
  for: 5m
  labels:
    severity: critical
```
