### ISSUE TITLE
Issue with Blackbox-exporter

### ISSUE THREAD

**Issue by manuprometheus** [coreos/prometheus-operator#2010]
**What did you do?**
Configured a Blackbox exporter for monitoring URL
**What did you expect to see?**
Exporter configured successfully and able to see the status of my domain. But issue while adding more than  one target
**What did you see instead? Under which circumstances?**
When I add more than one target on service monitor, I am not able to see the probe query for both of my targets at a time.
**Environment**

* Prometheus Operator version:

	insert image tag or Git SHA here

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by manuprometheus** [comment]
black box-exporter deployment yaml.
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blackbox-exporter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blackbox-exporter
        k8s-app: blackbox-exporter
        version: "v0.2.0"
    spec:
      containers:
      - name: blackbox-exporter
        image: quay.io/prometheus/blackbox-exporter:v0.2.0
        ports:
        - name: http
          containerPort: 9115

```

Service yaml

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: blackbox-exporter
 labels:
    app: blackbox-exporter
    k8s-app: blackbox-exporter
spec:
  ports:
  - name: blackbox-exporter
    port: 80
    targetPort: http
  - name: http
    port: 9115
    protocol: TCP
  selector:
    app: blackbox-exporter
    k8s-app: blackbox-exporter
```
Service monitor yaml 

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox-exporter
  labels:
    app: blackbox-exporter
    k8s-app: blackbox-exporter
spec:
  selector:
    matchLabels:
      app: blackbox-exporter
      k8s-app: blackbox-exporter
  endpoints:
  - port: http
 # - port: blackbox-exporter
    path: /probe
    params:
      module:
        - http_2xx
      target:
        - https://example.com
        - https://example1.com

    relabelings:
      - sourceLabels:
          - __param_target
        targetLabel: target
      - sourceLabels:
          - __param_module
        targetLabel: module

```

**Comment by manuprometheus** [comment]
The issue is I am not able to query the "probe_duration_seconds" for my all targets from the Prometheus.

**Comment by bernyemmanuel** [comment]
Even I am having the same issue. I need to add staticConfigs:  target in Service monitor so that I am able to monitor multiple web urls using Prometheus.

It is possible with normal prometheus where I can mention the staticConfigs: targets directly in my prometheus.yml file and able to probe the status.

Please advise how we can add this in prometheus-operator

**Comment by brancz** [comment]
If you are looking to add static targets, you want to use the additionalScrapeConfigs feature, not a ServiceMonitor.

**Comment by bernyemmanuel** [comment]
@brancz Thank you so much for giving the right idea.. I think that will do it.. once again thanks..

**Comment by manuprometheus** [comment]
I have followed the method of "additional-scrape-configs"  for adding my static static targets. But the prometheus.yaml file is not loading with the new configuration. Do i need to recreate the whole setup?

**Comment by manuprometheus** [comment]
My prometheus-additional.yaml is as follows:

```
- job_name: 'blackbox-exporter'
    metrics_path: /probe
    scrape_interval: 1m
    params:
      module: ['http_2xx']
    static_configs:
      - targets:                             # targets to be tested by the blackbox exporter
          - https://google.com/
          - https://mydomain.com/
    relabel_configs:
          - source_labels: [__address__]     # set param 'target' to the original target
            regex: (.*)
            target_label: __param_target
            replacement: ${1}
          - source_labels: [__param_target]  # set label 'instance' to it as well
            regex: (.*)
            target_label: instance
            replacement: ${1}
          - source_labels: []                # set __address__ to the blackbox exporter
            regex: .*
            target_label: __address__
            replacement: 100.96.23.231:9115
```

But my prometheus statefulset is not creating. Getting error 

> "level=info ts=2018-10-22T07:08:00.094617055Z caller=operator.go:732 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
> E1022 07:08:00.282284       1 operator.go:646] Sync "monitoring/k8s" failed: creating config failed: generating config failed: unmarshalling additional scrape configs failed: yaml: line 1: did not find expected key"

**Comment by bernyemmanuel** [comment]
@brancz Even I am stuck with the same thing. tried to follow the configuration under : https://github.com/coreos/prometheus-operator/tree/master/example/additional-scrape-configs

But the Prometheus still not showing the new configuration for my custom url targets. Do I need to do anything rather than the above additionalScrapeConfigs within the manifest operator configs?

**Comment by metalmatze** [comment]
You need to encode the configuration as Kubernetes secret.

You can run this command on your plain YAML file:
```
kubectl -n monitoring create secret generic prometheus-additional --from-file prometheus-additional.yaml --dry-run -oyaml > prometheus-additional-secret.yaml
```

You'll then have a Kubernetes Secret which you have to apply with your cluster. Then the Operator should be able to merge the config with the rest.

**Comment by manuprometheus** [comment]
@metalmatze I have configured my configuration as secret and then created the prometheus. But getting the above error.

**Comment by metalmatze** [comment]
Did you try the command I posted earlier? Because you configuration looks similar to what I have in plain YAML.
Maybe it's simply the indentation of you YAML?
```diff
  - job_name: 'blackbox-exporter'
+   metrics_path: /probe
-     metrics_path: /probe
```

**Comment by manuprometheus** [comment]
@metalmatze  Thank you very much for the hint. It was related to the indentation issue. It is working now. +1:

**Comment by manuprometheus** [comment]
This is my corrected prometheus-additional.yaml.

```
- job_name: 'blackbox'
  metrics_path: /probe
  scrape_interval: 1m
  static_configs:
    - targets:                             # targets to be tested by the blackbox exporter
        - https://example.com
        - https://example1.com
  relabel_configs:
        - source_labels: [__address__]     # set param 'target' to the original target
          regex: (.*)
          target_label: __param_target
          replacement: ${1}
        - source_labels: [__param_target]  # set label 'instance' to it as well
          regex: (.*)
          target_label: instance
          replacement: ${1}
        - source_labels: []                # set __address__ to the blackbox exporter
          regex: .*
          target_label: __address__
          replacement: blackbox-exporter:9115

It may help others.
```
