### ISSUE TITLE
How to automatically generate altermanager templates file in the altermanager container by modifying example.jsonnet

### ISSUE THREAD

**Issue by boxuan666** [coreos/prometheus-operator#2014]
**What did you do?**
copy my own template file in to altermanager container（statefulset）.
**What did you expect to see?**
Automatically generate templates in the altermanager container by modifying example.jsonnet（Customizing Kube-Prometheus）

there is my example.json file:
```
local kp = 
(import 'kube-prometheus/kube-prometheus.libsonnet') +
(import 'kube-prometheus/kube-prometheus-kubeadm.libsonnet') +
(import 'kube-prometheus/kube-prometheus-node-ports.libsonnet') +
(import 'kube-prometheus/kube-prometheus-static-etcd.libsonnet') + {

  _config+:: {
    namespace: 'monitoring',

    etcd+:: {
      ips: ['10.15.4.253','10.15.4.254','10.15.4.255'],

      clientCA: importstr 'ca.pem',
      clientKey: importstr 'etcd-key.pem',
      clientCert: importstr 'etcd.pem',

      insecureSkipVerify: true,    
    },


    kubeStateMetrics+:: {
      baseCPU: '200m',
      cpuPerNode: '50m',
      baseMemory: '300Mi',
      memoryPerNode: '100Mi',
    },


    alertmanager+:: {
      name: 'main',
      config: |||
        global:
          resolve_timeout: 5m
          wechat_api_corp_id: '1000002'
          wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
          wechat_api_secret: '*********************'
        templates:
        - '/etc/alertmanager/wechat.tmpl'
        route:
          receiver: 'wechat'
          group_by: ['alertname']
          group_wait:      30s
          group_interval:  3m
          repeat_interval: 3m
        receivers:
        - name: 'wechat'
          wechat_configs:
          - send_resolved: true
            corp_id: '******************'
            to_party: '14'
            agent_id: '1000002'
            api_secret: '**********************'

      |||,
    },

  },
};

{ ['00namespace-' + name + '.json']: kp.kubePrometheus[name] for name in std.objectFields(kp.kubePrometheus) } +
{ ['0prometheus-operator-' + name + '.json']: kp.prometheusOperator[name] for name in std.objectFields(kp.prometheusOperator) } +
{ ['node-exporter-' + name + '.json']: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
{ ['kube-state-metrics-' + name + '.json']: kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics) } +
{ ['alertmanager-' + name + '.json']: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
{ ['prometheus-' + name + '.json']: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
{ ['grafana-' + name + '.json']: kp.grafana[name] for name in std.objectFields(kp.grafana) }

```

**Environment**

* Prometheus Operator version:

```
image: quay.io/coreos/prometheus-operator:v0.23.2
```

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

```
kubeadm
```

**Comment by brancz** [comment]
You're right, this is not possible today out of the box with the jsonnet setup. My suggestion would be to create an additional secret that contains your template and then add that secret to the `.spec.secrets` list in the Alertmanager object. For convenience we could expose this in the `_config.alertmanager` object.

**Comment by boxuan666** [comment]
@brancz

**Comment by boxuan666** [comment]
@brancz 

Thanks, I got it.

**Comment by boxuan666** [comment]
@brancz 
there is a another problem.
why my Alertmanager sent duplicate alert in one time ?
i expect to see one alert in one time.

can u help me to resolve this ? :)

my config file as follow
```
global:
  resolve_timeout: 5m
  wechat_api_corp_id: '1000002'
  wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
  wechat_api_secret: '*****'
route:
  receiver: 'wechat'
  group_by: ['alertname']
  group_wait:      30s
  group_interval:  5m
  repeat_interval: 4h
receivers:
- name: 'wechat'
  wechat_configs:
  - send_resolved: true
    corp_id: '*****'
    to_party: '14'
    agent_id: '1000002'
    api_secret: '*****'
templates:
- '/etc/alertmanager/config/wechat.tmpl'
```

**Comment by brancz** [comment]
There can be various reasons for this. It would be better to open an issue on the upstream Alertmanager repo about this.

**Comment by metacyclic** [comment]
> You're right, this is not possible today out of the box with the jsonnet setup. My suggestion would be to create an additional secret that contains your template and then add that secret to the `.spec.secrets` list in the Alertmanager object. For convenience we could expose this in the `_config.alertmanager` object.

@brancz or @boxuan666 - Could either of you explain a bit more how to achieve this?  My attempt leaves me with a file `manifests/alertmanager-spec.yaml` that looks like
```
secrets:
- apiVersion: v1
  data:
    templates.tmpl: BASE64OFSECRET
  kind: Secret
  metadata:
    name: alertmanager-templates
    namespace: monitoring
  type: Opaque
```

I create the secret in example.jsonnet like this:
```
local k = import 'ksonnet/ksonnet.beta.3/k.libsonnet';
local tmplsecret = k.core.v1.secret;
local kp = (import 'kube-prometheus/kube-prometheus.libsonnet') + {
  _config+:: {
<snip>
  },
  alertmanager+: {
    spec+: {
        secrets+: [
          tmplsecret.new('alertmanager-templates', { 'templates.tmpl': std.base64(std.manifestYamlDoc(  importstr 'path/to/template/file.txt' )) }) +
          tmplsecret.mixin.metadata.withNamespace('monitoring')
      ],
    },
  },
```

Any help would be greatly appreciated, and I agree that exposing it in `_config.alertmanager` would be awesome.
