### ISSUE TITLE
No node points for kube-prometheus deployment

### ISSUE THREAD

**Issue by BostjanBozic** [coreos/prometheus-operator#2021]
**What did you do?**
I have deployed latest kube-prometheus (commit: a2e8cd504c32c1fb1d30eb955a49b3d79a8121cd) on my bear-metal cluster. Most metrics are visible apart node metrics themselves.
Only thing that I changed was to set Grafana service as `NodePort`.

**What did you expect to see?**
Expected to see node metrics.

**What did you see instead? Under which circumstances?**
Node metrics are not shown in Grafana, other metrics are visible (namespace, pod levels)

**Environment**
```Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
 CPE OS Name: cpe:/o:redhat:enterprise_linux:7.3:GA:server
 Kernel: Linux 3.10.0-327.el7.x86_64
 Architecture: x86-64
```

* Prometheus Operator version:

	`a2e8cd504c32c1fb1d30eb955a49b3d79a8121cd`

* Kubernetes version information:

`Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind: 

	`kubeadm`was used

* Manifests:

I just did `kubectl apply -f .` in `manifest` folder

* Prometheus Operator Logs:

There seems to be no issues in operator:
```
ts=2018-10-16T14:19:05.074623979Z caller=main.go:165 msg="Starting Prometheus Operator version '0.24.0'."
level=info ts=2018-10-16T14:19:05.176599288Z caller=operator.go:209 component=alertmanageroperator msg="connection established" cluster-version=v1.11.2
level=info ts=2018-10-16T14:19:05.176598983Z caller=operator.go:371 component=prometheusoperator msg="connection established" cluster-version=v1.11.2
level=info ts=2018-10-16T14:19:05.671607588Z caller=operator.go:627 component=alertmanageroperator msg="CRD updated" crd=Alertmanager
level=info ts=2018-10-16T14:19:05.772432596Z caller=operator.go:1412 component=prometheusoperator msg="CRD updated" crd=Prometheus
level=info ts=2018-10-16T14:19:05.7816443Z caller=operator.go:1412 component=prometheusoperator msg="CRD updated" crd=ServiceMonitor
level=info ts=2018-10-16T14:19:05.789312551Z caller=operator.go:1412 component=prometheusoperator msg="CRD updated" crd=PrometheusRule
level=info ts=2018-10-16T14:19:08.673666626Z caller=operator.go:225 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2018-10-16T14:19:08.874079234Z caller=operator.go:180 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2018-10-16T14:19:08.874216053Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2018-10-16T14:19:08.886389445Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2018-10-16T14:19:08.891485126Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2018-10-16T14:19:14.805075199Z caller=operator.go:387 component=prometheusoperator msg="CRD API endpoints ready"
level=info ts=2018-10-16T14:19:15.670087632Z caller=operator.go:322 component=prometheusoperator msg="successfully synced all caches"
level=info ts=2018-10-16T14:19:15.670288848Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-10-16T14:19:15.886475994Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-10-16T14:19:16.089644676Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-10-16T14:19:27.094299245Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2018-10-16T14:19:43.437950021Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2018-10-16T14:19:44.348263422Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-10-16T14:20:01.172976054Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2018-10-16T14:20:11.333489782Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-10-16T14:20:34.913847866Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
level=info ts=2018-10-16T14:22:10.740807756Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
```

Sorry if this is not the right channel to address this, in that case just let me know who to turn to.

Thank you and best regards,
Bostjan

**Comment by brancz** [comment]
Are the node exporters successfully scraped? You can see this on the `/targets` page of the Prometheus UI.

**Comment by BostjanBozic** [comment]
Hello brancz.

Thank you for fast response. They are indeed down with following error:
`Get https://10.2.56.29:9100/metrics: http: server gave HTTP response to HTTPS client`

What I forgot to mention is that I changed in `node-exporter-daemonset.yaml` port to:
`--secure-listen-address=:9200`
Same goes for `node-exporter-service.yaml`: `port: 9200`.

Reason is that exporters were failing if I left that as default port. I wonder, do I have to change this somewhere else as well as it seems it is still trying to scrape from port 9100.
I though everything is ok on exporter side, as logs are indicating no errors:
```
time="2018-10-16T14:18:55Z" level=info msg="Starting node_exporter (version=0.16.0, branch=HEAD, revision=d42bd70f4363dced6b77d8fc311ea57b63387e4f)" source="node_exporter.go:82"
time="2018-10-16T14:18:55Z" level=info msg="Build context (go=go1.9.6, user=root@a67a9bc13a69, date=20180515-15:52:42)" source="node_exporter.go:83"
time="2018-10-16T14:18:55Z" level=info msg="Enabled collectors:" source="node_exporter.go:90"
time="2018-10-16T14:18:55Z" level=info msg=" - arp" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - bcache" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - bonding" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - conntrack" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - cpu" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - diskstats" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - edac" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - entropy" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - filefd" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - filesystem" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - hwmon" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - infiniband" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - ipvs" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - loadavg" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - mdadm" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - meminfo" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - netdev" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - netstat" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - nfs" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - nfsd" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - sockstat" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - stat" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - textfile" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - time" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - timex" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - uname" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - vmstat" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - wifi" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - xfs" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg=" - zfs" source="node_exporter.go:97"
time="2018-10-16T14:18:55Z" level=info msg="Listening on 127.0.0.1:9101" source="node_exporter.go:111"
```

**Comment by brancz** [comment]
Can you share the daemonset, service and servicemonitor you applied?

**Comment by BostjanBozic** [comment]
Hello,

daemonset YAML:
```
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  labels:
    app: node-exporter
  name: node-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
      - args:
        - --web.listen-address=127.0.0.1:9101
        - --path.procfs=/host/proc
        - --path.sysfs=/host/sys
        - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)
        - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
        image: quay.io/prometheus/node-exporter:v0.16.0
        name: node-exporter
        resources:
          limits:
            cpu: 102m
            memory: 180Mi
          requests:
            cpu: 102m
            memory: 180Mi
        volumeMounts:
        - mountPath: /host/proc
          name: proc
          readOnly: false
        - mountPath: /host/sys
          name: sys
          readOnly: false
        - mountPath: /host/root
          mountPropagation: HostToContainer
          name: root
          readOnly: true
      - args:
        - --secure-listen-address=:9200
        - --upstream=http://127.0.0.1:9101/
        image: quay.io/coreos/kube-rbac-proxy:v0.3.1
        name: kube-rbac-proxy
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: https
        resources:
          limits:
            cpu: 20m
            memory: 40Mi
          requests:
            cpu: 10m
            memory: 20Mi
      hostNetwork: true
      hostPID: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: node-exporter
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - hostPath:
          path: /proc
        name: proc
      - hostPath:
          path: /sys
        name: sys
      - hostPath:
          path: /
        name: root
```

Service YAML:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: node-exporter
  name: node-exporter
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: https
    port: 9200
    targetPort: https
  selector:
    app: node-exporter
```

ServiceMonitor YAML:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: node-exporter
  name: node-exporter
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: node-exporter
```

Is the reason that I am setting ports in service/servicemonitor as https?

**Comment by BostjanBozic** [comment]
Hello,

I found the issue. Reason that I was not getting any metrics was because metrics from `node-exporter` were begin scraped on port 9100 instead 9200 (which I changed in .yaml files).
So initially I only changed following:
```--secure-listen-address=:9200```

I forgot to update container ports as well, as following:
```
 - args:
        - --secure-listen-address=:9200
        - --upstream=http://127.0.0.1:9101/
        image: quay.io/coreos/kube-rbac-proxy:v0.3.1
        name: kube-rbac-proxy
        ports:
        - containerPort: 9200
          hostPort: 9200
          name: https
```

Sorry to bother you with such issue, I just had to look more into yaml files.

Best regards
