### ISSUE TITLE
Federate from source outside Kubernetes using DNS not IP 

### ISSUE THREAD

**Issue by cloudshapes** [coreos/prometheus-operator#2036]
Hi,
Not sure if anyone can help.

I've successfully setup federation from an external source, i.e. from a source outside Kubernetes - using an approach similar to https://github.com/coreos/prometheus-operator/issues/1201#issuecomment-387452888.

However, that approach relies upon providing IP addresses of endpoints to federate from.

I'd like to do this using a DNS name instead of an IP. Is this possible and if so how?

I did spot issue posts that discussed "staticTargets" (see https://github.com/coreos/prometheus-operator/issues/1201), however, I'm not sure if "staticTargets" ever got rolled out into master.

So, without "staticTargets", is there a way anyone know of how to do this?

Many thanks.

**Comment by metalmatze** [comment]
The `externalName` of Kubernetes Services are able to use DNS as well:
https://kubernetes.io/docs/concepts/services-networking/service/#externalname

If you don't want to do it via a Service you should be able to do the same by providing `additionalScrapeConfigs` in your Prometheus. 
https://github.com/coreos/prometheus-operator/blob/d0cf2eed390f65a11ad434667d4721bb1d425f3b/example/additional-scrape-configs/prometheus.yaml#L18
This needs parts of a normal Prometheus configuration as Kubernetes Secret and it is concatenated to the generated configuration by the Prometheus Operator.

**Comment by cloudshapes** [comment]
Many thanks for the speedy reply.

How might an `externalName` be used in a `ServiceMonitor` ?
Do you by any chance have an example?

**Comment by metalmatze** [comment]
You don't use `externalName` within a ServiceMonitor but within a Service:

```diff
kind: Service
apiVersion: v1
metadata:
  name: external
  namespace: monitoring
  labels:
    k8s-app: external
spec:
- externalName: 1.1.1.1
+ externalName: my.dns.record.example.com
  type: ExternalName
  ports:
  - name: http
    port: 9100
    protocol: TCP
    targetPort: 9100
```

**Comment by cloudshapes** [comment]
To expand a little on my previous question, if you had a `ServiceMonitor` as follows:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thing-sm
  namespace: thingy-namespace
  labels:
    thing-app: thing-sm
spec:
  jobLabel: thing-sm
  selector:
    matchLabels:
      plat-eng-app: thing-svc
  namespaceSelector:
    matchNames:
    - thingy-namespace
  endpoints:
  - port: thing-port
    targetPort: 9200
    path: "/federate/"
    interval: "30s"
    honorLabels: true
    params:
      match[]:
      - thing-tomatch

```

how would you use an `externalName` to specify where to federate from?
