### ISSUE TITLE
additionalScrapeConfigs not ending up in Configuration. 

### ISSUE THREAD

**Issue by pault84** [coreos/prometheus-operator#2041]
**What did you do?**
First of my ultimate goal is to federate multiple prometheus' this way.
After looking at this folder: 
`https://github.com/coreos/prometheus-operator/tree/master/example/additional-scrape-configs`

I created the prometheus-additional and then a secret out of the following content:
```
global:
  scrape_interval: 10s
  scrape_timeout: 10s
scrape_configs:
- job_name: pxc_prometheus
  honor_labels: true
  metrics_path: /federate
  static_configs:
  - targets:
    - http://70.0.78.112:30900
```

**What did you expect to see?**
a configuration with both my sm scrape_config and my additional federate scrape_config

**What did you see instead? Under which circumstances?**
I only see my service monitor scrape configs and my rules.
My additionalScrapeConfig settings are not present in the configuration

**Environment**
Ubuntu

* Prometheus Operator version:
`quay.io/coreos/prometheus-operator:v0.17.0`

* Kubernetes version information:
 `Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}` 

* Kubernetes cluster kind: 
plain k8s

* Manifests:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator
subjects:
  - kind: ServiceAccount
    name: prometheus-operator
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-operator
  namespace: kube-system
rules:
  - apiGroups:
      - extensions
    resources:
      - thirdpartyresources
    verbs: ["*"]
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs: ["*"]
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - alertmanagers
      - prometheuses
      - prometheuses/finalizers
      - servicemonitors
    verbs: ["*"]
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs: ["*"]
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
    verbs: ["*"]
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["list", "delete"]
  - apiGroups: [""]
    resources:
      - services
      - endpoints
    verbs: ["get", "create", "update"]
  - apiGroups: [""]
    resources:
      - nodes
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources:
      - namespaces
    verbs: ["list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operator
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
    spec:
      containers:
        - args:
            - --kubelet-service=kube-system/kubelet
            - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
          image: quay.io/coreos/prometheus-operator:v0.17.0
          name: prometheus-operator
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: kube-system
  name: portworx-prometheus-sm
  labels:
    name: portworx-prometheus-sm
spec:
  selector:
    matchLabels:
      name: portworx
  namespaceSelector:
    any: true
  endpoints:
    - port: px-api
      targetPort: 9001
    - port: px-kvdb
      targetPort: 9019
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: portworx #This name is important since the Alertmanager pods wont start unless a secret named alertmanager-${ALERTMANAGER_NAME} is created. in this case if would expect alertmanager-portworx secret in the kube-system namespace
  namespace: kube-system
  labels:
    alertmanager: portworx
spec:
  replicas: 3
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-portworx
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - name: web
      nodePort: 30903
      port: 9093
      protocol: TCP
      targetPort: web
  selector:
    alertmanager: portworx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]
  - nonResourceURLs: ["/metrics", "/federate"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: kube-system
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: kube-system
spec:
  replicas: 3
  logLevel: debug
  serviceAccountName: prometheus
  alerting:
    alertmanagers:
      - namespace: kube-system
        name: alertmanager-portworx
        port: web
  serviceMonitorSelector:
    matchLabels:
      name: portworx-prometheus-sm
    namespaceSelector:
      matchNames:
        - kube-system
    resources:
      requests:
        memory: 400Mi
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
    namespaceSelector:
      matchNames:
        - kube-system
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - name: web
      nodePort: 30900
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    prometheus: prometheus
```

* Prometheus Operator Logs:

```
ts=2018-10-24T00:24:36.460024018Z caller=operator.go:258 component=prometheusoperator msg="connection established" cluster-version=v1.11.3
ts=2018-10-24T00:24:36.460618409Z caller=operator.go:158 component=alertmanageroperator msg="connection established" cluster-version=v1.11.3
ts=2018-10-24T00:24:36.463853233Z caller=operator.go:172 component=alertmanageroperator msg="CRD API endpoints ready"
ts=2018-10-24T00:24:36.467247569Z caller=operator.go:272 component=prometheusoperator msg="CRD API endpoints ready"
ts=2018-10-24T00:24:36.467349357Z caller=operator.go:305 component=alertmanageroperator msg="Alertmanager added" key=kube-system/portworx
ts=2018-10-24T00:24:36.467408646Z caller=operator.go:381 component=alertmanageroperator msg="sync alertmanager" key=kube-system/portworx
ts=2018-10-24T00:24:36.553301975Z caller=operator.go:325 component=alertmanageroperator msg="Alertmanager updated" key=kube-system/portworx
ts=2018-10-24T00:24:36.753452323Z caller=operator.go:308 component=prometheusoperator msg="Prometheus added" key=kube-system/prometheus
ts=2018-10-24T00:24:36.753563056Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
ts=2018-10-24T00:24:36.851331966Z caller=operator.go:328 component=prometheusoperator msg="Prometheus updated" key=kube-system/prometheus
ts=2018-10-24T00:24:37.053010141Z caller=operator.go:381 component=alertmanageroperator msg="sync alertmanager" key=kube-system/portworx
ts=2018-10-24T00:24:37.054231912Z caller=operator.go:345 component=alertmanageroperator msg="update handler" old=5652566 cur=5652569
ts=2018-10-24T00:24:37.150670264Z caller=operator.go:970 component=prometheusoperator msg="creating configuration"
ts=2018-10-24T00:24:37.152062183Z caller=operator.go:637 component=prometheusoperator msg="update handler" old=5652566 cur=5652569
ts=2018-10-24T00:24:37.164509651Z caller=operator.go:381 component=alertmanageroperator msg="sync alertmanager" key=kube-system/portworx
ts=2018-10-24T00:24:37.178399123Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
ts=2018-10-24T00:24:37.251750777Z caller=operator.go:345 component=alertmanageroperator msg="update handler" old=5652583 cur=5652592
ts=2018-10-24T00:24:37.253311316Z caller=operator.go:637 component=prometheusoperator msg="update handler" old=5652583 cur=5652592
ts=2018-10-24T00:24:37.352855506Z caller=operator.go:984 component=prometheusoperator msg="current config or current configmaps has changed"
ts=2018-10-24T00:24:37.352996423Z caller=operator.go:990 component=prometheusoperator msg="updating configuration"
ts=2018-10-24T00:24:37.378674597Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
ts=2018-10-24T00:24:37.458530051Z caller=operator.go:981 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-10-24T00:24:41.935620979Z caller=operator.go:345 component=alertmanageroperator msg="update handler" old=5652592 cur=5652669
ts=2018-10-24T00:24:41.936014566Z caller=operator.go:637 component=prometheusoperator msg="update handler" old=5652592 cur=5652669
ts=2018-10-24T00:24:41.936140694Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
ts=2018-10-24T00:24:41.956932507Z caller=operator.go:981 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-10-24T00:24:42.093230932Z caller=operator.go:345 component=alertmanageroperator msg="update handler" old=5652669 cur=5652674
ts=2018-10-24T00:24:42.093554648Z caller=operator.go:637 component=prometheusoperator msg="update handler" old=5652669 cur=5652674
ts=2018-10-24T00:24:42.093660197Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
ts=2018-10-24T00:24:42.110447475Z caller=operator.go:981 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-10-24T00:24:46.850760679Z caller=operator.go:345 component=alertmanageroperator msg="update handler" old=5652569 cur=5652697
ts=2018-10-24T00:24:46.850822198Z caller=operator.go:637 component=prometheusoperator msg="update handler" old=5652569 cur=5652697
ts=2018-10-24T00:24:46.850860428Z caller=operator.go:381 component=alertmanageroperator msg="sync alertmanager" key=kube-system/portworx
ts=2018-10-24T00:24:53.353889916Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
ts=2018-10-24T00:24:53.460406085Z caller=operator.go:981 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-10-24T00:24:55.367867991Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
ts=2018-10-24T00:24:55.462633125Z caller=operator.go:981 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-10-24T00:24:57.385499853Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
ts=2018-10-24T00:24:57.461959215Z caller=operator.go:981 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-10-24T00:24:59.396625727Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
ts=2018-10-24T00:24:59.46351199Z caller=operator.go:981 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-10-24T00:25:00.433195776Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
ts=2018-10-24T00:25:00.459966701Z caller=operator.go:981 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-10-24T00:25:00.480425203Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
ts=2018-10-24T00:25:00.556952676Z caller=operator.go:981 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-10-24T00:25:00.606985385Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
ts=2018-10-24T00:25:00.663078827Z caller=operator.go:981 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-10-24T00:25:00.757084128Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
ts=2018-10-24T00:25:00.774363591Z caller=operator.go:981 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-10-24T00:25:01.398733508Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
ts=2018-10-24T00:25:01.462813095Z caller=operator.go:981 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-10-24T00:25:01.484320883Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
ts=2018-10-24T00:25:01.554022465Z caller=operator.go:981 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-10-24T00:25:02.414138252Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
ts=2018-10-24T00:25:02.459626624Z caller=operator.go:981 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2018-10-24T00:25:02.479109Z caller=operator.go:672 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
ts=2018-10-24T00:25:02.557728655Z caller=operator.go:981 component=prometheusoperator msg="updating config skipped, no configuration change"
```

**Comment by brancz** [comment]
The `additionalScrapeConfigs` feature was introduced in `v0.19.0` https://github.com/coreos/prometheus-operator/blob/master/CHANGELOG.md#0190--2018-04-25

**Comment by pault84** [comment]
I changed the operator to version 0.19.0
No change still don't see the federation config i put in additionScrapeConfig

Any idea where i should look next?

**Comment by pault84** [comment]
Alright figured it out.

upgrade to 0.25.0
and changed config to:

```
- job_name: pxc_prometheus
  honor_labels: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /federate
  scheme: http
  static_configs:
  - targets:
    - 70.0.78.112:30900
```
