### ISSUE TITLE
AlertmanagerDown and PrometheusNotConnectedToAlertmanagers

### ISSUE THREAD

**Issue by VinceMD** [coreos/prometheus-operator#2062]
**What did you do?**
Install latest version of prometheus operator and check the Prometheus web UI

**What did you expect to see?**
I expected to see no critical alert apart from DeadMansSwitch

**What did you see instead? Under which circumstances?**

Under Alerts of Prometheus:

- AlertmanagerDown
- CPUThrottlingHigh
- KubeControllerManagerDown
- KubeSchedulerDown
- PrometheusNotConnectedToAlertmanagers

Under target, no unhealthy target. All green.

When visiting the Alert Manager UI, there is nothing listed. None of the above alerts are there. Alert manager should show the same alerts.
This is a new Kubernetes cluster. 
On a previous cluster, I was using Prometheus Operator v0.20.0 and didn't face the issue with Alert Manager

**Environment**

* Prometheus Operator version:
v0.25.0
kube-prometheus `a7eb782ea174af819bd82c72be54946ed83bd7b3`
* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

kube-aws

* Manifests:

Alert manager manifest:

alertmanageralert-manager.yaml
```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
spec:
  baseImage: quay.io/prometheus/alertmanager
  externalUrl: https://alertmanager.monitoring.csna-k8s-red.assn.restest.nbn-aws.local
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 3
  serviceAccountName: alertmanager-main
  version: v0.15.2
```

* Prometheus Operator Logs:

```
level=info ts=2018-10-29T00:02:43.54405564Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-10-29T00:02:44.448176525Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-10-29T00:02:54.460478418Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-10-29T00:02:55.322934874Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-10-29T00:03:05.342996517Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2018-10-29T00:03:06.372311291Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
```

In previous version of Prometheus Operator (v0.20.0), the alert manager seemed to work fine. 
I would like to know if I'm doing something wrong and if I should revert to older version of Prometheus Operator.
Any more info I can provide?
