### ISSUE TITLE
Permission for secrets and configmaps - Kube-Prometheus

### ISSUE THREAD

**Issue by jakirpatel** [coreos/prometheus-operator#2064]
I wanted the help regarding the permissions with prometheus-operator with respect to the cluster-role.
I am using the Kube-prometheus to deploy this solution. 
While deploying the Prometheus-operator I needed this option as the cluster role: 

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*' 

```

Why we required the "*" permission for verbs? Is it the potential risk ?
