### ISSUE TITLE
helm/prometheus: Allow PSP to be defined externally when RBAC is on

### ISSUE THREAD

**Issue by jkrcma** [coreos/prometheus-operator#2077]
**What did you do?**
I'm trying to set up a common environment so our dev teams can spawn per-project/team Prometheus instances respecting their own tiller instances with restricted access.

**What did you expect to see?**
Working `helm install` command, which doesn't try to define its own `ClusterRole` and `ClusterRoleBinding` for PodSecurityPolicy purposes.

**What did you see instead? Under which circumstances?**
Helm ServiceAccount bothering with `ClusterRole`.

**Environment**

* Prometheus Operator version:

	v0.20.0

* Kubernetes version information:

	```
	Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
	Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
	```

* Kubernetes cluster kind: 

	kubeadm self-hosted

**From helm values:**

```yaml
global:
  rbacEnable: true
  pspEnable: true
  # I miss something like pspCreate: false

serviceAccount:
  create: false
  name: prometheus
```
