### ISSUE TITLE
`relabelings` not working?

### ISSUE THREAD

**Issue by cin** [coreos/prometheus-operator#2123]
**What did you do?**
Trying to get pod labels as labels into prometheus by using the `relabelings` feature add [here](https://github.com/coreos/prometheus-operator/pull/1879)

relevant portion of values.yaml in superchart.
```yaml
  serviceMonitors:
    - name: $HELM_RELEASE-cassandra
      selector:
        matchLabels:
          app: cassandra
          release: $HELM_RELEASE
          role: prometheus-monitoring
      endpoints:
        - port: metrics
          relabelings:
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - sourceLabels: [__meta_kubernetes_pod_name]
              action: replace
              targetLabel: host
```

kubectl get servicemonitors.monitoring.coreos.com gaq-cassandra -o yaml
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: 2018-11-13T01:43:34Z
  generation: 1
  labels:
    app: prometheus
    chart: prometheus-0.0.51
    heritage: Tiller
    prometheus: gaq
    release: gaq
  name: gaq-cassandra
  namespace: gaq-prod
  resourceVersion: "7052666"
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/gaq-prod/servicemonitors/gaq-cassandra
  uid: 8835f806-e6e5-11e8-9149-ba898d75ec73
spec:
  endpoints:
  - port: metrics
    relabelings:
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_name
      targetLabel: host
  selector:
    matchLabels:
      app: cassandra
      release: gaq
      role: prometheus-monitoring
```

**What did you expect to see?**
pod labels included as labels in prometheus...essentially same output as below but with `environment`, `data_center`, and `host` included.

for example, here's the `describe pod` output.
```
kubectl describe po gaq-cassandra-dal10-0
Name:               gaq-cassandra-dal10-0
Namespace:          gaq-prod
Start Time:         Mon, 12 Nov 2018 20:44:42 -0500
Labels:             app=gaq-cassandra
                    billingType=monthly
                    controller-revision-hash=gaq-cassandra-dal10-899bdddff
                    data_center=dal10
                    dc=dal10
                    environment=gaq
                    statefulset.kubernetes.io/pod-name=gaq-cassandra-dal10-0
```

**What did you see instead? Under which circumstances?**
```
org_apache_cassandra_metrics_Storage_Load{endpoint="metrics",instance="172.30.142.127:8090",job="gaq-monitoring-cassandra",namespace="gaq-prod",pod="gaq-cassandra-dal12-1",service="gaq-monitoring-cassandra",unit="Count"}
```
* Prometheus Operator version:

```
image: quay.io/coreos/prometheus-operator:v0.20.0
```

shouldn't this be 0.25.0?

* Kubernetes version information:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:16Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3+IKS", GitCommit:"ada755932025320d0c249486935c2aa31eea55d1", GitTreeState:"clean", BuildDate:"2018-09-27T20:52:21Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
Multizone cluster on IBM Cloud

The lack of documentation on this operator is frustrating. Why are there no examples on relabel configs? What am a missing here? I think the problem here is that I'm somehow not getting the `latest` image, but I'm not sure how to define that. Any help would be greatly appreciated.
