### ISSUE TITLE
Prometheus rules disappear when using additional scrapeConfigs.

### ISSUE THREAD

**Issue by pault84** [coreos/prometheus-operator#2129]
**What did you do?**
Run Prometheus operator with a ruleSelector and additionalScrapeconfigs.

**What did you expect to see?**
Rules being applied to my federation config.

**What did you see instead? Under which circumstances?**
I see federation happening but no more rule files.
When i look at my configmaps i see a new rules file being created with -0 at the end.
on my other cluster without federation i don't see this file.

**Environment**
2 x 3 node environments.
1 is a central management cluster
1 is a development cluster

prometheus operator
grafana
alertmanager

* Prometheus Operator version:
v0.25.0

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
kubeadm

* Manifests:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator
subjects:
  - kind: ServiceAccount
    name: prometheus-operator
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-operator
  namespace: kube-system
rules:
  - apiGroups:
      - extensions
    resources:
      - thirdpartyresources
    verbs: ["*"]
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs: ["*"]
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - alertmanagers
      - prometheuses
      - prometheuses/finalizers
      - servicemonitors
      - prometheusrules
    verbs: ["*"]
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs: ["*"]
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
    verbs: ["*"]
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["list", "delete"]
  - apiGroups: [""]
    resources:
      - services
      - endpoints
    verbs: ["get", "create", "update"]
  - apiGroups: [""]
    resources:
      - nodes
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources:
      - namespaces
    verbs: ["list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operator
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
    spec:
      containers:
        - args:
            - --kubelet-service=kube-system/kubelet
            - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
          image: quay.io/coreos/prometheus-operator:v0.25.0
          name: prometheus-operator
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: kube-system
  name: portworx-prometheus-sm
  labels:
    name: portworx-prometheus-sm
spec:
  selector:
    matchLabels:
      name: portworx
  namespaceSelector:
    any: true
  endpoints:
    - port: px-api
      targetPort: 9001
    - port: px-kvdb
      targetPort: 9019
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: portworx #This name is important since the Alertmanager pods wont start unless a secret named alertmanager-${ALERTMANAGER_NAME} is created. in this case if would expect alertmanager-portworx secret in the kube-system namespace
  namespace: kube-system
  labels:
    alertmanager: portworx
spec:
  replicas: 3
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-portworx
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - name: web
      nodePort: 30903
      port: 9093
      protocol: TCP
      targetPort: web
  selector:
    alertmanager: portworx
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-portworx-rules
  namespace: kube-system
  labels:
    role: prometheus-portworx-rulefiles
    prometheus: portworx
data:
  portworx.rules.yaml: |+
    groups:
    - name: portworx.rules
      rules:
      - alert: PortworxVolumeUsageCritical
        expr: 100 * (px_volume_usage_bytes / px_volume_capacity_bytes) > 80
        for: 5m
        labels:
          issue: Portworx volume {{$labels.volumeid}} usage on {{$labels.host}} is high.
          severity: critical
        annotations:
          description: Portworx volume {{$labels.volumeid}} on {{$labels.host}} is over
            80% used for more than 10 minutes.
          summary: Portworx volume capacity is at {{$value}}% used.
      - alert: PortworxVolumeUsage
        expr: 100 * (px_volume_usage_bytes / px_volume_capacity_bytes) > 70
        for: 5m
        labels:
          issue: Portworx volume {{$labels.volumeid}} usage on {{$labels.host}} is critical.
          severity: warning
        annotations:
          description: Portworx volume {{$labels.volumeid}} on {{$labels.host}} is over
            70% used for more than 10 minutes.
          summary: Portworx volume {{$labels.volumeid}} on {{$labels.host}} is at {{$value}}%
            used.
      - alert: PortworxVolumeWillFill
        expr: (px_volume_usage_bytes / px_volume_capacity_bytes) > 0.7 and predict_linear(px_cluster_disk_available_bytes[1h],
          14 * 86400) < 0
        for: 10m
        labels:
          issue: Disk volume {{$labels.volumeid}} on {{$labels.host}} is predicted to
            fill within 2 weeks.
          severity: warning
        annotations:
          description: Disk volume {{$labels.volumeid}} on {{$labels.host}} is over 70%
            full and has been predicted to fill within 2 weeks for more than 10 minutes.
          summary: Portworx volume {{$labels.volumeid}} on {{$labels.host}} is over 70%
            full and is predicted to fill within 2 weeks.
      - alert: PortworxStorageUsageCritical
        expr: 100 * (1 - px_cluster_disk_utilized_bytes / px_cluster_disk_total_bytes) < 20
        for: 5m
        labels:
          issue: Portworx storage {{$labels.volumeid}} usage on {{$labels.host}} is high.
          severity: critical
        annotations:
          description: Portworx storage {{$labels.volumeid}} on {{$labels.host}} is over
            80% used for more than 10 minutes.
          summary: Portworx storage capacity is at {{$value}}% used.
      - alert: PortworxStorageUsage
        expr: 100 * (1 - (px_cluster_disk_utilized_bytes / px_cluster_disk_total_bytes)) < 30
        for: 5m
        labels:
          issue: Portworx storage {{$labels.volumeid}} usage on {{$labels.host}} is critical.
          severity: warning
        annotations:
          description: Portworx storage {{$labels.volumeid}} on {{$labels.host}} is over
            70% used for more than 10 minutes.
          summary: Portworx storage {{$labels.volumeid}} on {{$labels.host}} is at {{$value}}%
            used.
      - alert: PortworxStorageWillFill
        expr: (100 * (1 - (px_cluster_disk_utilized_bytes / px_cluster_disk_total_bytes))) < 30 and predict_linear(px_cluster_disk_available_bytes[1h], 14 * 86400) < 0
        for: 10m
        labels:
          issue: Portworx storage {{$labels.volumeid}} on {{$labels.host}} is predicted
            to fill within 2 weeks.
          severity: warning
        annotations:
          description: Portworx storage {{$labels.volumeid}} on {{$labels.host}} is over
            70% full and has been predicted to fill within 2 weeks for more than 10 minutes.
          summary: Portworx storage {{$labels.volumeid}} on {{$labels.host}} is over 70%
            full and is predicted to fill within 2 weeks.
      - alert: PortworxStorageNodeDown
        expr: max(px_cluster_status_nodes_storage_down) > 0
        for: 5m
        labels:
          issue: Portworx Storage Node is Offline.
          severity: critical
        annotations:
          description: Portworx Storage Node has been offline for more than 5 minutes.
          summary: Portworx Storage Node is Offline.
      - alert: PortworxQuorumUnhealthy
        expr: max(px_cluster_status_cluster_quorum) > 1
        for: 5m
        labels:
          issue: Portworx Quorum Unhealthy.
          severity: critical
        annotations:
          description: Portworx cluster Quorum Unhealthy for more than 5 minutes.
          summary: Portworx Quorum Unhealthy.
      - alert: PortworxMemberDown
        expr: (max(px_cluster_status_cluster_size) - count(px_cluster_status_cluster_size)) > 0
        for: 5m
        labels:
          issue: Portworx cluster member(s) is(are) down.
          severity: critical
        annotations:
          description: "Portworx cluster member(s) has(have) been down for
            more than 5 minutes."
          summary: Portworx cluster member(s) is(are) down.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]
  - nonResourceURLs: ["/metrics", "/federate"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: kube-system
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: kube-system
spec:
  replicas: 2
  logLevel: debug
  serviceAccountName: prometheus
  alerting:
    alertmanagers:
      - namespace: kube-system
        name: alertmanager-portworx
        port: web
  serviceMonitorSelector:
    matchLabels:
      name: portworx-prometheus-sm
    namespaceSelector:
      matchNames:
        - kube-system
    resources:
      requests:
        memory: 400Mi
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
  ruleSelector:
    matchLabels:
      role: prometheus-portworx-rulefiles
      prometheus: portworx
    namespaceSelector:
      matchNames:
        - kube-system
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - name: web
      nodePort: 30900
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    prometheus: prometheus
```

* Prometheus Operator Logs:

```
ts=2018-11-13T23:26:37.255058762Z caller=main.go:165 msg="Starting Prometheus Operator version '0.25.0'."
level=info ts=2018-11-13T23:26:37.276601168Z caller=operator.go:371 component=prometheusoperator msg="connection established" cluster-version=v1.11.3
level=info ts=2018-11-13T23:26:37.280322665Z caller=operator.go:209 component=alertmanageroperator msg="connection established" cluster-version=v1.11.3
level=info ts=2018-11-13T23:26:37.856427053Z caller=operator.go:627 component=alertmanageroperator msg="CRD updated" crd=Alertmanager
level=info ts=2018-11-13T23:26:38.033214405Z caller=operator.go:1417 component=prometheusoperator msg="CRD updated" crd=Prometheus
level=info ts=2018-11-13T23:26:38.055275575Z caller=operator.go:1417 component=prometheusoperator msg="CRD updated" crd=ServiceMonitor
level=info ts=2018-11-13T23:26:38.075323422Z caller=operator.go:1417 component=prometheusoperator msg="CRD updated" crd=PrometheusRule
level=info ts=2018-11-13T23:26:40.866452333Z caller=operator.go:225 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2018-11-13T23:26:41.067792832Z caller=operator.go:180 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2018-11-13T23:26:41.068138654Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=kube-system/portworx
level=info ts=2018-11-13T23:26:41.161228586Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=kube-system/portworx
level=info ts=2018-11-13T23:26:41.260058537Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=kube-system/portworx
level=info ts=2018-11-13T23:26:47.090460018Z caller=operator.go:387 component=prometheusoperator msg="CRD API endpoints ready"
level=info ts=2018-11-13T23:26:47.793522361Z caller=operator.go:322 component=prometheusoperator msg="successfully synced all caches"
level=info ts=2018-11-13T23:26:47.793970964Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
level=info ts=2018-11-13T23:26:47.954961504Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
level=info ts=2018-11-13T23:26:48.069547554Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
level=info ts=2018-11-13T23:26:50.299933103Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=kube-system/portworx
level=info ts=2018-11-13T23:26:55.559285917Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
level=info ts=2018-11-13T23:26:58.144736662Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=kube-system/portworx
level=info ts=2018-11-13T23:27:00.393589285Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
level=info ts=2018-11-13T23:27:02.402034171Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
level=info ts=2018-11-13T23:27:04.411356394Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
level=info ts=2018-11-13T23:27:04.744127337Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
level=info ts=2018-11-13T23:27:04.918264153Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
level=info ts=2018-11-13T23:27:04.983413915Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
level=info ts=2018-11-13T23:27:06.424873223Z caller=operator.go:956 component=prometheusoperator msg="sync prometheus" key=kube-system/prometheus
level=info ts=2018-11-13T23:27:08.135665218Z caller=operator.go:448 component=alertmanageroperator msg="sync alertmanager" key=kube-system/portworx
```
