### ISSUE TITLE
Service monitor CRD does not affect adding job scrape

### ISSUE THREAD

**Issue by ev4ern** [coreos/prometheus-operator#2138]
I have created service monitor resource

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pushgateway
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: http
  jobLabel: pushgateway
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: prometheus-pushgateway
```

I have not see any changes in prometheus.yaml

```
k get secret prometheus-kube-prometheus -ojson | jq -r '.data["prometheus.yaml"]' | base64 -D | grep pushgateway | wc -l
       0
```

I tried to remove operator pod but it is still not working  

Besides your "troubleshoting" is not really troubleshoting, cause you don't give us any receipt to fix it, only shell command to see that problem is really exist :(

https://github.com/coreos/prometheus-operator/blob/master/Documentation/troubleshooting.md#troubleshooting-servicemonitor-changes

Prometheus operator version is 0.20.0
Helm chart version is 0.0.29
