### ISSUE TITLE
how to use an existed PersistentVolumeClaim

### ISSUE THREAD

**Issue by shangjin92** [coreos/prometheus-operator#2150]
**What did you do?**
I have already created PV and PVC, and I want to use the existed PVC for prometheus server. But in prometheus-operator, I found that value.yaml in helm chart only has volumeClaimTemplate configuration. In prometheus-operator storage's user-guide, it seems like volumeClaimTemplate is used to create PVC dynamic. So I wander how to use the PVC which I have created, like volumeMounts in prometheus.

**What did you expect to see?**
I want to use PVC that I have created

* Prometheus Operator version:
v0.25.0

* Kubernetes version information:
v1.11.2

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brancz** [comment]
As described here: https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/storage.md#manual-storage-provisioning

It's perfectly possible to use an existing PV with a PVC template :slightly_smiling_face: .

**Comment by shangjin92** [comment]
> As described here: https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/storage.md#manual-storage-provisioning
> 
> It's perfectly possible to use an existing PV with a PVC template 🙂 .

Thank you so much. I have read the storage usage before, but when I try to use the existing PV, the prometheus pod cannot start. For some reason, the OSS which I used cannot support dynamic storage volume. It need to create PV and PVC, then bind the existing PVC by volumes and persistentVolumeClaim. Can I use the existing PVC like this?

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: "flexvolume-oss-example"
spec:
  containers:
    - name: "nginx"
      image: "nginx"
      volumeMounts:
          - name: pvc-oss
            mountPath: "/data"
  volumes:
  - name: pvc-oss
    persistentVolumeClaim:
        claimName: pvc-oss
```
