### ISSUE TITLE
Bad insert of container environment variable in grafana deployment

### ISSUE THREAD

**Issue by Shini31** [coreos/prometheus-operator#2151]
**What did you do?**
I want to add grafana-piechart-panel plugin with a custom kube-prometheus
Here is the jsonnet:
```
local kp = (import 'kube-prometheus/kube-prometheus.libsonnet') +
           (import 'kube-prometheus/kube-prometheus-node-ports.libsonnet') +
           (import 'kube-prometheus/kube-prometheus-kubespray.libsonnet') {
  _config+:: {
    versions+:: {
      grafana: "5.3.4"
    },
    grafana+:: {
      plugins: ['grafana-piechart-panel'],
    },
  },
};

{ ['00namespace-' + name + '.json']: kp.kubePrometheus[name] for name in std.objectFields(kp.kubePrometheus) } +
{ ['0prometheus-operator-' + name + '.json']: kp.prometheusOperator[name] for name in std.objectFields(kp.prometheusOperator) } +
{ ['node-exporter-' + name + '.json']: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
{ ['kube-state-metrics-' + name + '.json']: kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics) } +
{ ['alertmanager-' + name + '.json']: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
{ ['prometheus-' + name + '.json']: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
{ ['grafana-' + name + '.json']: kp.grafana[name] for name in std.objectFields(kp.grafana) }
```

**What did you expect to see?**
Example with a functional manually modified grafana-deployment.json.yaml
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: grafana/grafana:5.3.4
        name: grafana
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: GF_INSTALL_PLUGINS
          value: grafana-piechart-panel
....
```

**What did you see instead? Under which circumstances?**
After compilation, here is the grafana-deployment.json.yaml 
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - env:
        - name: GF_INSTALL_PLUGINS
          value: grafana-piechart-panel
        image: grafana/grafana:5.3.4
        name: grafana
        ports:
        - containerPort: 3000
          name: http
...
```

**Environment**

* Prometheus Operator version:
0.25

* Kubernetes version information:
1.12

* Kubernetes cluster kind: 
kubespray
