### ISSUE TITLE
Monitor All Namespaces (kube-prometheus)

### ISSUE THREAD

**Issue by brondum** [coreos/prometheus-operator#2155]
**What did you do?**
applied the manifest folder for kube-promtheus

**What did you expect to see?**
Is it possible to monitor all namespaces (or listen for serviceMonitors).

**What did you see instead? Under which circumstances?**
I only have the possibility to append an item to the namespaces array.

**Environment**

* Prometheus Operator version:

	31f621c4

* Kubernetes version information:

	Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.7-gke.11", GitCommit:"fa90543563c9cfafca69128ce8cd9ecd5941940f", GitTreeState:"clean", BuildDate:"2018-11-08T20:22:21Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	GKE

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by brondum** [comment]
@metalmatze Thank you for the quick answer.
The problem i am facing is that i dont care about the specific namespaces, meaning that i cannot add a list of namespaces to the rolebindings.  Is it possible to have an "all" selector somehow ?

Thanks.

**Comment by metalmatze** [comment]
Not sure if a ClusterRole and ClusterRoleBinding might do the trick here, but that's more a RBAC thing now. I am also unsure if that's a good thing to do.

**Comment by brondum** [comment]
@metalmatze I agree in a multi tenancy cluster it might be a sketchy move.
Should i add a seperate clusterRole and RoleBinding outside the jsonnet templates ?

**Comment by brondum** [comment]
@metalmatze Yeah by overwriting the cluster roles it is possible. Thank you for the hint.
I will take in considerations that this might not be the best idea and not the intention of kube-promtheus.

**promtheus-clusterRole.yaml**
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-k8s
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- nonResourceURLs:
  - /metrics
  verbs:
  - get

```
