### ISSUE TITLE
How to add volumeMount for alertmanager and prometheus container

### ISSUE THREAD

**Issue by shangjin92** [coreos/prometheus-operator#2164]
**What did you do?**
I want to add volumeMount for alertmanager and prometheus container to change timezone. Because the UTC timezone is not friendly to me. While I edit alertmanager statefulset like this.

```bash
kubectl edit StatefulSet alertmanager-prometheus-operator-alertmanager -n monitor
```

```yaml
volumeMounts:
- name: host-time
   mountPath: /etc/localtime
   readOnly: true

volumes:
- name: host-time
        hostPath:
          path: /etc/localtime
```

But it reported 'error: statefulsets.apps "alertmanager-prometheus-operator-alertmanager" is invalid'. Is there any way to add volumeMount to slove this error?

**What did you expect to see?**
I want to add volumeMount to alertmanager and prometheus container, to change timezone from UTC to GMT.

**Environment**

* Prometheus Operator version:
v0.25.0

* Kubernetes version information:
v1.11.2
