### ISSUE TITLE
Work with externalName of Kubernetes service

### ISSUE THREAD

**Issue by fabxc** [coreos/prometheus-operator#218]
Kubernetes services have an `externalName` field  as part of their spec (https://kubernetes.io/docs/api-reference/v1/definitions/#_v1_servicespec), which maps to a DNS record instead of having an associated endpoints object.
Prometheus's K8S discovery only works with endpoint objects and probably should keep doing so.

Instead the operator could generate a DNS discovery config for the Prometheus instance if a ServiceMonitor references a service with an `externalName`.

**Comment by tonglil** [comment]
Are there any updates on this? It would be a huge blessing for using Prometheus operator more generally for easy operations to support the collection of any metrics, not just ones from in the cluster.

**Comment by max-lobur** [comment]
What's the current status? I've been trying to get this working on latest prometheus-operator, using serviceMonitor which selector points to the externalName type svc - no luck :(

**Comment by brancz** [comment]
External type services are not possible to be monitored in a general whitebox style. If this is what you want to do, I recommend using a separate service discovery mechanism offered by Prometheus to discover the whitebox targets of the external service.

**Comment by max-lobur** [comment]
@brancz thanks for pointing.
Yeah I realized that ELB won't show up the internals so you don't know the targets.
So I end up with a EC2 discovery based scraper:
```
additionalScrapeConfigs:
      - job_name: 'mypp'
        metrics_path: '/metrics'
        ec2_sd_configs:
          - region: us-east-2
            access_key: 
            secret_key: 
            port: 80
        relabel_configs:
          - source_labels: [__meta_ec2_tag_Name]
            regex: MyApp.*
            action: keep
          - source_labels: [__meta_ec2_private_ip]
            target_label: instance
```
