### ISSUE TITLE
Upgrading to version 0.26.0 breaks PV access

### ISSUE THREAD

**Issue by vsliouniaev** [coreos/prometheus-operator#2182]
Suspect that this is _possibly_ the result of https://github.com/coreos/prometheus-operator/pull/2109

**What did you do?**
Upgraded from prometheus-operator v0.25 to v0.26

**What did you expect to see?**
Prometheus pods should come up with Prometheus v0.25

**What did you see instead? Under which circumstances?**
Pods crashlooping with
```
level=error ts=2018-11-30T13:20:02.660393999Z caller=main.go:625 err="opening storage failed: open /prometheus/wal/00000949: permission denied"
```

This may be only apparent when using persistent volumes

**Environment**
Azure

* Prometheus Operator version:

v0.26

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

kubeadm

**Comment by brancz** [comment]
Can you share your PV configuration?

**Comment by vsliouniaev** [comment]
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
spec:
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: prometheus
        resources:
          requests:
            storage: 150Gi
```
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: prometheus
provisioner: kubernetes.io/azure-disk
parameters:
  kind: Managed
  storageaccounttype: Standard_LRS
allowVolumeExpansion: true
reclaimPolicy: Delete
```
Running on Ubuntu 16-LTS

Previously the wal files were created with `1000 2000`, now they are created with `root root`
Previously prometheus ran as `1000`, now it runs as `root`
Creating a new prometheus on operator 0.26.0 with prometheus 2.5.0 works fine

This is pretty surprising to me too, so I hope you might have some ideas how I could try get more information for you next.

**Comment by brancz** [comment]
That’s odd, typically the kubelet ensures correct ownership on content of a volume before mounting it. Could you explicitly set the security context to what it was before? That would at least fix your situation.

**Comment by vsliouniaev** [comment]
Thanks for the info, I'll give it a try. 

I'm concerned that this isn't a safe upgrade to push without breaking the Helm charts for folks who already have persistent storage provisioned, so I wanted to find out what could cause it.

It's odd that prometheus finds WAL files but isn't able to read them

**Comment by sc250024** [comment]
^^ Having the same problem

**Comment by brancz** [comment]
That seems like a bug with the volume provider though, this doc says that before mounting the kubelet sets the owner/permissions recursively. https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/volume-ownership-management.md

**Comment by kasunt84** [comment]
So whats the solution ? not very clear in the post. Is it just to roll back to the previous version ?

**Comment by nixgadget** [comment]
I was having the same issue. Based on @brancz comments I added and it appears to work fine.
```
securityContext:
  runAsNonRoot: false
  runAsUser: 0
  fsGroup: 0
```
