### ISSUE TITLE
Snmp exporter doesn't appear in prometheus target

### ISSUE THREAD

**Issue by swaroopkundeti** [coreos/prometheus-operator#2195]
**What did you do?**
Integrated snmp-exporter with prometheus-operator
**What did you expect to see?**
Should see snmp-exporter in targets but I could see snmp in prometheus configuration file. 

**What did you see instead? Under which circumstances?**
I don't see snmp target in targets.  Am I missing anything? 

* Kubernetes version information:
`Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:16Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}`
`Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2+coreos.0", GitCommit:"b427929b2982726eeb64e985bc1ebb41aaa5e095", GitTreeState:"clean", BuildDate:"2018-01-18T22:56:14Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}`
* Kubernetes cluster kind: 

	insert how you created your cluster: kubespray

* Manifests:
Service-Monitor:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: snmp-exporter
  labels:
    k8s-app: snmp-exporter
    prometheus: kube-prometheus
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: snmp-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
   - interval: 60s
     params:
       module: [if_mib]
     static_config:
       - target:
         - 10.94.148.223
     metrics_path: "/snmp"
     scrapeTimeout: 30s
     bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
     tlsConfig:
        insecureSkipVerify: true
   - interval: 60s
     params:
       module: [if_mib]
     static_configs:
       - targets:
         - 10.94.148.220
     metrics_path: "/snmp"
     scrapeTimeout: 30s
     bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
     tlsConfig:
        insecureSkipVerify: true
```
Service Deployment
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: snmp-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: snmp-exporter
  template:
    metadata:
      labels:
        k8s-app: snmp-exporter
      name: snmp-exporter
    spec:
      containers:
      - image: prom/snmp-exporter
        command: ["/bin/snmp_exporter"]
        args: ["--config.file=/etc/snmp_exporter/snmp.yml"]
        name: snmp-exporter
        ports:
        - containerPort: 9116
          name: metrics
```

**Comment by brancz** [comment]
static_targets does not exists, you will want to use the additional scrape configs feature for using the snmp exporter.

**Comment by swaroopkundeti** [comment]
@brancz Thank you for your response. I removed static config and changed to below config which isn't working. Is this something only works with additional scape configs?

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: snmp-exporter
  labels:
    k8s-app: snmp-exporter
    app: snmp-exporter
spec:
  jobLabel: k8s-app
  selector:
    matchExpressions:
      - {key: k8s-app, operator: Exists}
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: snmp-metrics
    interval: 60s
    params:
      module: [if_mib]
      target:
        - 10.94.148.223
    metrics_path: "/snmp"
    scrapeTimeout: 30s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      insecureSkipVerify: true
```
