### ISSUE TITLE
Alertmanager CrashLoopBackOff 

### ISSUE THREAD

**Issue by yaminisridaran** [coreos/prometheus-operator#2200]
**What did you do?**
I want to create Alertmanager in prometheus operator.
Kubectl create -f alert.yaml

apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: example
  name: example
spec:
  baseImage: quay.io/prometheus/alertmanager
  replicas: 3
  version: v0.15.2
  nodeSelector: {}

Kubectl get pods shows Alertmanager pod status as CrashLoopBackOff
 
Pod logs
Error from server (BadRequest): a container name must be specified for pod alertmanager-example-0, choose one of: [alertmanager config-reloader]

**What did you expect to see?**
expect to create Alertmanager Pods

**What did you see instead? Under which circumstances?**
Kubectl get pods shows Alertmanager pod status as CrashLoopBackOff
 
Pod logs
Error from server (BadRequest): a container name must be specified for pod alertmanager-example-0, choose one of: [alertmanager config-reloader]

**Environment**
k8s
* Prometheus Operator version:
0.25.0

	
```
insert Prometheus Operator logs relevant to the issue here
```

**Comment by harshal-shah** [comment]
Hey @yaminisridaran Can you please paste output of 

`kubectl logs alertmanager-example-0 -c alertmanager`

What you have pasted above is an error since the logs command does not know which container to show logs from.

**Comment by yaminisridaran** [comment]
[kuberadmin@yamini-sridaran-k8-master-1-a00016-4b2c09f7b029c1b8 ~]$ kc -n fed-prometheus-dbg logs alertmanager-example-0 -c alertmanager
Error from server (BadRequest): container "alertmanager" in pod "alertmanager-example-0" is waiting to start: ContainerCreating

**Comment by yaminisridaran** [comment]
can you please provide me the Alertmanager yaml

**Comment by harshal-shah** [comment]
@yaminisridaran  You need to wait for the image to be pulled and container to be started before trying to get logs. 
So far this does not seem like a generic issue and it would be better if you join the kubernetes slack and ask this on #prometheus channel there.

**Comment by yaminisridaran** [comment]
6hrs it is same error.
This is happening only for Alertmanager other resources are working fine.
Why Kubernetes slack?
I am using Prometheus operator and other Prometheus operator crd like Prometheus works fine.
Can you please verify whether Alertmanager in your setup.
Can you please provide me your Alertmanager object creation yaml

**Comment by brancz** [comment]
We're successfully using:

```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
spec:
  baseImage: quay.io/prometheus/alertmanager
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 3
  serviceAccountName: alertmanager-main
  version: v0.15.3
```

We're going to need Alertmanager logs and prometheus-operator logs if that doesn't work for you, just like @harshal-shah said.
