### ISSUE TITLE
kube-Prometheus installation failed on K8 initiated with kubeadm, maybe due to problem in prometheus-adapter-apiService.yaml ??

### ISSUE THREAD

**Issue by hshtel** [coreos/prometheus-operator#2211]
**What did you do?**
try to deploy kube-Prometheus on K8 cluster iniated with kubeadm with "kubectl create -f manifests/ || true" with no luck. 

I am not fully aware of how APIservice object work, but is there any relation  between prometheus-adapter-apiService.yaml and metrics-apiservice.yaml which is deployed before with metric-server. or it is another problem.

**What did you expect to see?**
kube-Prometheus installed successfully.

**What did you see instead? Under which circumstances?**
the kube-state-metrics and prometheus-operator pods keep crashing as below, 
```
NAMESPACE     NAME                                        READY   STATUS    RESTARTS   AGE     IP           NODE      NOMINATED NODE   READINESS GATES
monitoring    pod/grafana-6689854d5-7npcp                 1/1     Running   0          86s     10.46.0.3    worker2   <none>           <none>
monitoring    pod/kube-state-metrics-86bc74fd4c-j7c7h     4/4     Error     2          86s     10.40.0.2    master    <none>           <none>
monitoring    pod/node-exporter-6b6d9                     2/2     Running   0          86s     172.1.1.11   worker2   <none>           <none>
monitoring    pod/node-exporter-lfsw8                     2/2     Running   0          86s     172.1.1.9    master    <none>           <none>
monitoring    pod/node-exporter-zzcth                     2/2     Running   0          86s     172.1.1.10   worker1   <none>           <none>
monitoring    pod/prometheus-adapter-5d7cff4b-2gqg9       1/1     Running   0          85s     10.32.0.6    worker1   <none>           <none>
monitoring    pod/prometheus-operator-5cfb7f4c54-kfl4r    1/1     Error     2          90s     10.40.0.1    master    <none>           <none>
```

**Environment**

* Prometheus Operator version:
```
Prometheus Operator version '0.26.0'."
```

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	kubeadm.

* Manifests:

```
### prometheus-adapter-apiService.yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
spec:
  group: metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: prometheus-adapter
    namespace: monitoring
  version: v1beta1
  versionPriority: 100
```

```
###metrics-apiservice.yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
spec:
  service:
    name: metrics-server
    namespace: kube-system
  group: metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100

```
* Prometheus Operator Logs:

```
root@master:~# kubectl logs pod/prometheus-operator-5cfb7f4c54-kfl4r -n monitoring
ts=2018-12-11T13:27:48.738481288Z caller=main.go:165 msg="Starting Prometheus Operator version '0.26.0'."
ts=2018-12-11T13:28:18.826524292Z caller=main.go:253 msg="Unhandled error received. Exiting..." err="communicating with server failed: Get https://10.96.0.1:443/version?timeout=32s: dial tcp 10.96.0.1:443: i/o timeout"

```

**Comment by metalmatze** [comment]
> I am not fully aware of how APIservice object work, but is there any relation between prometheus-adapter-apiService.yaml and metrics-apiservice.yaml which is deployed before with metric-server. or it is another problem.

Yes, there is relation between both. An APIService tells the Kubernetes apiserver which Kubernetes Service (like a normal Service that you deploy with other apps) are responsible for handling requests to that specific API group.
The Prometheus Adapter replaces the metrics server, both implement the same API: `metrics.k8s.io`.
If you want to run the Prometheus Adapter, which you should when also running Prometheus on your cluster, then you can simply remove all traces of the metrics server. Things like `kubectl top` and Horizontal Pod Autoscaler should still work afterwards and be served by Prometheus Adapter from there on.

**Comment by hshtel** [comment]
@metalmatze thanks, I have deleted metric-server but actually the problem still exists. the deployment stops "not all the pods were created" when error occurred on  prometheus-operator,, prometheus-adapter and kube-state-metrics as below:
```
NAME                                   READY   STATUS             RESTARTS   AGE    IP             NODE      NOMINATED NODE   READINESS GATES
grafana-6689854d5-r68gt                1/1     Running            0          7m3s   10.46.0.2      worker2   <none>           <none>
kube-state-metrics-86bc74fd4c-zwwh8    3/4     CrashLoopBackOff   5          7m2s   10.40.0.2      master    <none>           <none>
node-exporter-89ch4                    2/2     Running            0          7m2s   10.205.28.9    master    <none>           <none>
node-exporter-blw5l                    2/2     Running            0          7m2s   10.205.28.11   worker2   <none>           <none>
node-exporter-nkngb                    2/2     Running            0          7m2s   10.205.28.10   worker1   <none>           <none>
prometheus-adapter-7899dcdf87-9hdlf    0/1     CrashLoopBackOff   5          7m1s   10.40.0.3      master    <none>           <none>
prometheus-operator-5cfb7f4c54-x96vf   0/1     CrashLoopBackOff   5          7m4s   10.40.0.1      master    <none>           <none>
```
the current log of prometheus-adapter:
```
root@master:~/prometheus-operator/contrib/kube-prometheus# kubectl logs pod/prometheus-adapter-7899dcdf87-9hdlf -n monitoring
I1211 18:54:40.597247       1 adapter.go:86] successfully using in-cluster auth
F1211 18:55:10.598081       1 adapter.go:230] unable to install resource metrics API: unable to construct dynamic discovery mapper: unable to populate initial set of REST mappings: Get https://10.96.0.1:443/api?timeout=32s: dial tcp 10.96.0.1:443: i/o timeout
```
the current log of Prometheus Operator:
```

root@master:~/prometheus-operator/contrib/kube-prometheus# kubectl logs pod/prometheus-operator-5cfb7f4c54-x96vf -n monitoring
ts=2018-12-11T18:54:49.739414344Z caller=main.go:165 msg="Starting Prometheus Operator version '0.26.0'."
ts=2018-12-11T18:55:19.744455411Z caller=main.go:253 msg="Unhandled error received. Exiting..." err="communicating with server failed: Get https://10.96.0.1:443/version?timeout=32s: dial tcp 10.96.0.1:443: i/o timeout"
```
the current log of kube-state-metrics
```
root@master:~/prometheus-operator/contrib/kube-prometheus# kubectl logs pod/kube-state-metrics-86bc74fd4c-zwwh8  -n monitoring -c kube-state-metrics
I1211 18:54:52.729131       1 main.go:76] Using default collectors
I1211 18:54:52.729181       1 main.go:90] Using all namespace
I1211 18:54:52.729187       1 main.go:96] No metric whitelist or blacklist set. No filtering of metrics will be done.
W1211 18:54:52.729201       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1211 18:54:52.731024       1 main.go:145] Testing communication with server
F1211 18:55:22.731429       1 main.go:112] Failed to create client: ERROR communicating with apiserver: Get https://10.96.0.1:443/version?timeout=32s: dial tcp 10.96.0.1:443: i/o timeout
```
just to make sure I am doing everything right, how to ensure that "--authentication-token-webhook=true" and "--authorization-mode=Webhook" is set correctly. and if not how to set these flags in kubeadm cluster.

**Comment by hshtel** [comment]
@metalmatze I have below error when getting the APIservices:
```
NAME                                                                     SERVICE                         AVAILABLE                  AGE
apiservice.apiregistration.k8s.io/v1beta1.metrics.k8s.io                 monitoring/prometheus-adapter   False (MissingEndpoints)   9m
```

and below is status from "kubectl get apiservice v1beta1.metrics.k8s.io -o yaml":
```
status:
  conditions:
  - lastTransitionTime: "2018-12-12T07:59:47Z"
    message: endpoints for service/prometheus-adapter in "monitoring" have no addresses
    reason: MissingEndpoints
    status: "False"
    type: Available
```
