### ISSUE TITLE
Using `labeldrop` on remoteWrite config breaks Prometheus

### ISSUE THREAD

**Issue by alebsack** [coreos/prometheus-operator#2218]
**What did you do?**

I supplied a remoteWrite config like so:
```
  remoteWrite:
    - url: "http://influxdb:8086/api/v1/prom/write?db=prometheus"
      writeRelabelConfigs:
        - action: labeldrop
          regex: prometheus
        - action: labeldrop
          regex: prometheus_replica
```

**What did you expect to see?**

I expected this to configure Prometheus' remote write config so that it would drop the existing `prometheus` and `prometheus_replica` labels from metrics that are scraped from another Prometheus.

**What did you see instead? Under which circumstances?**

Under all circumstances, I got this error from Prometheus:

```
Error loading config couldn't load configuration (--config.file=/etc/prometheus/config_out/prometheus.env.yaml): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: labeldrop action requires only 'regex', and no other fields
```

**Environment**

* Prometheus Operator version:

	0.25.0

* Kubernetes version information:

	1.10.6

* Kubernetes cluster kind: 

	KOPS on AWS
