### ISSUE TITLE
Can't find metrics from other namespaces

### ISSUE THREAD

**Issue by oguzyildiz1991** [coreos/prometheus-operator#2241]
**What did you do?**
I added the other namespaces to example.jsonnet:
```prometheus+:: {
      namespaces+: ['address-server', ...]
...
```

**What did you expect to see?**
When I port-forward one of the prometheus pods, I expected to see the metrics I exposed in /metrics path in the address-server namespace's pods. 
this is from address server pods' config:
```  template:
    metadata:
      labels:
        app: address-server
      annotations:
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
```
**What did you see instead? Under which circumstances?**
I'm seeing the default metrics from 'monitoring' namespace (I'm assuming that's what they are) in that dropdown, but any metrics from address-server namespace.

**Environment**
AWS
* Prometheus Operator version:
latest
	

* Kubernetes version information:

	1.11.3

* Kubernetes cluster kind: 

	not sure what this is

* Manifests:
```
config map:
apiVersion: v1
data:
  config.yaml: |
    rules:
    - seriesQuery: 'rpc_getLocationAddressWithLocalizationsRequestsInFlight{kubernetes_namespace!="",kubernetes_pod_name!=""}'
      resources:
        overrides:
          kubernetes_namespace: {resource: "namespace"}
          kubernetes_pod_name: {resource: "pod"}
      name:
        matches: "^(.*)"
        as: "${1}_max"
      metricsQuery: 'max(<<.Series>>{<<.LabelMatchers>>}[2m]) by (<<.GroupBy>>)'
    resourceRules:
      cpu:
        containerQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)
        nodeQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>, id='/'}[1m])) by (<<.GroupBy>>)
        resources:
          overrides:
            node:
              resource: node
            namespace:
              resource: namespace
            pod_name:
              resource: pod
        containerLabel: container_name
      memory:
        containerQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>}) by (<<.GroupBy>>)
        nodeQuery: sum(container_memory_working_set_bytes{<<.LabelMatchers>>,id='/'}) by (<<.GroupBy>>)
        resources:
          overrides:
            node:
              resource: node
            namespace:
              resource: namespace
            pod_name:
              resource: pod
        containerLabel: container_name
      window: 1m
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: monitoring

```

I can see this output in my pod's /metrics 
```
# HELP rpc_getLocationAddressWithLocalizationsRequestsInFlight Number of requests currently being handled by the endpoint '/rpc/getLocationAddressWithLocalizations'
# TYPE rpc_getLocationAddressWithLocalizationsRequestsInFlight gauge
rpc_getLocationAddressWithLocalizationsRequestsInFlight 10
# HELP rpc_getLocationAddressWithLocalizationsRequestsInFlightSUMMARY Number of requests currently being handled by the endpoint '/rpc/getLocationAddressWithLocalizations'
# TYPE rpc_getLocationAddressWithLocalizationsRequestsInFlightSUMMARY summary
rpc_getLocationAddressWithLocalizationsRequestsInFlightSUMMARY{quantile="0.5"} 22
rpc_getLocationAddressWithLocalizationsRequestsInFlightSUMMARY{quantile="0.9"} 32
rpc_getLocationAddressWithLocalizationsRequestsInFlightSUMMARY{quantile="0.99"} 45
rpc_getLocationAddressWithLocalizationsRequestsInFlightSUMMARY{quantile="1"} 79
rpc_getLocationAddressWithLocalizationsRequestsInFlightSUMMARY_sum 3.8862344e+07
rpc_getLocationAddressWithLocalizationsRequestsInFlightSUMMARY_count 3.434369e+06
```

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

when I go to /service-discovery webpage, I can see my service in there, but it says 0 active targets. When I expand its section, I see 2 columns:
Discovered Labels | Target Labels

All of the TargetLabels are "Dropped".

I just thought this could help narrowing down the problem

Any tips on how to troubleshoot this?
