### ISSUE TITLE
[ Helm ] Proposal for better alert management and configuration

### ISSUE THREAD

**Issue by AndresPineros** [coreos/prometheus-operator#2245]
**Issue**
Currently the way that Helm exposes the configuration for the PrometheusRules is located in the template files "prometheusrule.yaml". The logic to fetch the default or custom rules is:
```
spec:
{{- if .Values.prometheusRules }}
  groups:
{{ toYaml .Values.prometheusRules | indent 4 }}
{{ else }}
{{ include "kube-state-metrics.rules.yaml.tpl" . | indent 2}}
{{ end }}
```
This is great because we have the option to work with the default rules or to define custom rules. But here are the downsides I've seen with this strategy:

1) What if I want to add one single custom rule for the `exporter-kube-state` Chart but at the same time keep all the default rules? 
I would have to add all the rules from the `kube-state-metrics.rules.yaml` into my `values.yaml` file in order to add just one rule! The `kube-state-metrics.rules.yaml` file is 60 lines long. I don't want to see all those default rules in my `values.yaml` file.

2) What if I just want to tweak a single rule from the default rules? 
Again, let's say I just want to tweak the `for` field in the `DeploymentGenerationMismatch` rule from 15m to 5m. Same problem as above.

Basically, modifying default rules or adding custom rules implies adding all the default rules to the `values.yaml` file. This means adding ~500 lines to the `values.yaml` file when the `prometheusrule.yaml` files from all the Charts are considered.

**Proposal**

For my proposal, we have to first divide what we consider "custom" rules from "default" rules.

These are the steps to follow:

1) Default rules can be turned on or off as a whole.
Nothing has to be done here. This means having a flag called `useDefaultPrometheusRules` with `true` as the default value.

2) Default rules can be turned off independently.
Each alert inside the default rules file would have a flag specifying if it will be turned on or off.

3) Custom rules can be added independently from default rules.
This means having a field `customPrometheusRules` per Chart.

**Implementation**
The logic inside the `prometheusrule.yaml` files would be:
```
spec:
{{- if or (.Values.useDefaultPrometheusRules) (.Values.customPrometheusRules) }}
  groups:
{{- end }}
{{- if .Values.useDefaultPrometheusRules | default true}}
{{ include "kube-state-metrics.rules.yaml.tpl" . | indent 2}}
{{- end }}
{{- if .Values.customPrometheusRules }}
{{ toYaml .Values.customPrometheusRules | indent 4 }}
{{ end }}
```

And each default rule would have a surrounding condition:
```
{{ define "kube-state-metrics.rules.yaml.tpl" }}
kube-state-metrics.rules: kube-state-metrics.rules
  rules:
{{- if .Values.prometheusRulesFlags.DeploymentGenerationMismatch | default true}}
  - alert: DeploymentGenerationMismatch
    expr: kube_deployment_status_observed_generation != kube_deployment_metadata_generation
    for: 15m
    labels:
      severity: warning
    annotations:
      description: Observed deployment generation does not match expected one for
        deployment {{`{{$labels.namespace}}`}}/{{`{{$labels.deployment}}`}}
      summary: Deployment is outdated
{{- end }}
```

**Result**

1) If I want to add a custom rule, I don't have to worry about the default rules. I can just add it under the `customPrometheusRules` field.

2) If I want to edit the rule `DeploymentGenerationMismatch` I only have to turn that one off with `.Values.prometheusRulesFlags.DeploymentGenerationMismatch: false` and add my custom rule that replaces that one.

**Downsides of the proposal**
1) It would be harder to move from the Contrib rules to these rules because it isn't just a copy&paste anymore, but maybe a simple script that adds the conditions to the yaml.tpl file could help.

2) This adds complexity for the configuration because users would have to understand this. But, if someone is already adding custom rules or tweaking default rules, it means they are already very involved with the Chart and they'll be willing to understand this complexity. Also, they'll be grateful by knowing they don't have to copy&paste 500 lines of default rules into their configuration files.
