### ISSUE TITLE
seems like priorityClassName doesn't work

### ISSUE THREAD

**Issue by msafarisc** [coreos/prometheus-operator#2254]
**What did you do?**
tried to apply something similar to this:
```
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: highpriority
value: 10000
globalDefault: false
description: "This priority class should be used for XYZ service pods only."
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    prometheus: prometheus
spec:
  replicas: 1
  version: v2.4.3
  priorityClassName: highpriority
  serviceAccountName: prometheus-operator
```
but nothing changes to priorityClassName of prometheus.

**What did you expect to see?**
priority to change to 10000

**What did you see instead? Under which circumstances?**
no change in priority. it's 0.

**Environment**
=prometheus: `v2.4.3`

* Prometheus Operator version:

`v0.25.0`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-07-26T20:40:11Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
EKS
