### ISSUE TITLE
Getting 'Permission denied' while updating the alertmanager.yml

### ISSUE THREAD

**Issue by vrathore18** [coreos/prometheus-operator#2268]
I am trying to edit the /etc/alertmanager/alertmanager.yml so that I can add a new webhook for Microsoft team.

```
/etc/alertmanager $ cat alertmanager.yml
global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
```
But after updating the alertmanager.yml file, when I try to save the file I got **permission denied**.

I am accessing the file in the below container 

`kubectl exec -it  alertmanager-kube-prometheus-0 -c alertmanager /bin/sh -n monitoring`

How  can I modify alertmanager.yml, prometheus.yml for adding new rules and receivers.
I installed it via Using Helm chart

helm install coreos/prometheus-operator --name prometheus-operator --namespace monitoring
helm install coreos/kube-prometheus --name kube-prometheus --namespace monitoring
