### ISSUE TITLE
kube-prometheus: invalid manifest, labels tag in wrong location

### ISSUE THREAD

**Issue by jonomacd** [coreos/prometheus-operator#2277]
**What did you do?**
Followed the [kube-prometheus customisation example](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus#installing). I wanted to add further namespaces to monitor as well as change the namespace that it is installed to. This was the jsonnet file used 
```
local kp = (import 'kube-prometheus/kube-prometheus.libsonnet') + 
  {
  _config+:: {
    namespace: 'monitoring-prometheus',

    prometheus+:: {
      namespaces+: ['backend'],
    },
  },
};

{ ['00namespace-' + name]: kp.kubePrometheus[name] for name in std.objectFields(kp.kubePrometheus) } +
{ ['0prometheus-operator-' + name]: kp.prometheusOperator[name] for name in std.objectFields(kp.prometheusOperator) } +
{ ['node-exporter-' + name]: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
{ ['kube-state-metrics-' + name]: kp.kubeStateMetrics[name] for name in std.objectFields(kp.kubeStateMetrics) } +
{ ['alertmanager-' + name]: kp.alertmanager[name] for name in std.objectFields(kp.alertmanager) } +
{ ['prometheus-' + name]: kp.prometheus[name] for name in std.objectFields(kp.prometheus) } +
{ ['grafana-' + name]: kp.grafana[name] for name in std.objectFields(kp.grafana) }
``` 

**What did you expect to see?**
I expected the manifest files to be generated correctly.

**What did you see instead? Under which circumstances?**
The manifest files were generate but grafana-service.yaml was invalid. It returned the following error when attempting to deploy with kubectl:
```
error: error validating "manifests/grafana-service.yaml": error validating data: ValidationError(Service): unknown field "labels" in io.k8s.api.core.v1.Service; if you choose to ignore these errors, turn validation off with --validate=false```
```
And the content was as follows:
```
apiVersion: v1
kind: Service
labels:
  app: grafana
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: monitoring-prometheus
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: grafana
```

The root level labels field is invalid. Removing the field manually fixes the issue. 

**Environment**
The manifest generation was done on Mac OSX. The manifests were attempted to be applied to GKE. 

* Prometheus Operator version:

    `image: quay.io/coreos/prometheus-operator:v0.27.0`

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:30:58Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-gke.5", GitCommit:"9aba9c1237d9d2347bef28652b93b1cba3aca6d8", GitTreeState:"clean", BuildDate:"2018-12-11T02:36:50Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

* Manifests:

```
apiVersion: v1
kind: Service
labels:
  app: grafana
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: monitoring-prometheus
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: grafana
```

* Prometheus Operator Logs:

No relevant logs.
