### ISSUE TITLE
kube-prometheus:  CoreDNSDown

### ISSUE THREAD

**Issue by bitva77** [coreos/prometheus-operator#2278]
**What did you do?**

Compiled/Installed kube-prometheus

**What did you expect to see?**

No alerts

**What did you see instead? Under which circumstances?**

`alert: CoreDNSDown
expr: absent(up{job="kube-dns"}
  == 1)`

**Environment**

Kubernetes 1.13.0 - installed via kubeadm.

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

kubeadm

* Manifests:

```
cat prometheus-serviceMonitorCoreDNS.json.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: coredns
  name: coredns
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: metrics
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: kube-dns
```
``` 
   - alert: CoreDNSDown
      annotations:
        message: CoreDNS has disappeared from Prometheus target discovery.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-corednsdown
      expr: |
        absent(up{job="kube-dns"} == 1)
      for: 15m
      labels:
        severity: critical
 ```

The labels are correct:

```
kubectl get pods -l k8s-app=kube-dns -n kube-system
NAME                       READY   STATUS    RESTARTS   AGE
coredns-86c58d9df4-bhdln   1/1     Running   0          19d
coredns-86c58d9df4-pwrts   1/1     Running   0          19d
```

Not sure what the deal is.  Any thoughts?

**Comment by bitva77** [comment]
From my investigation here, in the `prometheus-serviceMonitorCoreDNS.json.yaml` ServiceMonitor, `spec.endpoints.port` is set to `metrics` but I don't see CoreDNS pods using that name for port 9153/TCP.

And I can't seem to change it manually to 9153.

That sound about right?

**Comment by brancz** [comment]
Yes that sounds like it's the crooks of it. Maybe make sure that kubeadm is creating coredns as recommended by their deploy repo: https://github.com/coredns/deployment/blob/c5670bf0d2c5c7964a68f1ef7dc20376602bfa2a/kubernetes/coredns.yaml.sed#L173-L175

(we made sure to have that port there :wink: https://github.com/coredns/deployment/pull/112)

**Comment by bitva77** [comment]
looks like kubeadm is configured correctly:

`kubectl get deployment coredns -o yaml -n kube-system`
```
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 9153
          name: metrics
          protocol: TCP
```

I'll keep poking around...

(by the way, great seeing/hearing the presentations at kubecon this year - thanks for that :)
