### ISSUE TITLE
NetworkPolicy doesn't work on a NodePort or hostPort

### ISSUE THREAD

**Issue by eugene-chow** [coreos/prometheus-operator#228]
**What did you do?**
Applied NetworkPolicy definitions specified [here](https://github.com/coreos/prometheus-operator/blob/master/Documentation/network-policies.md).

**What did you expect to see?**
That the NetworkPolicy-es work for the specified Pods.

**What did you see instead? Under which circumstances?**
The NetworkPolicy for `node-exporter` permits access by all hosts instead of limiting it to the `prometheus` Pods as specified.

It turns out that NodePort and HostPort aren't affected bypasses the NetworkPolicy. See [this](https://github.com/kubernetes/kubernetes/issues/22469#issuecomment-200335981) and [this](https://github.com/kubernetes/kubernetes/issues/22469#issuecomment-269389038).

**Environment**
Self-hosted k8s

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3+coreos.0", GitCommit:"8fc95b64d0fe1608d0f6c788eaad2c004f31e7b7", GitTreeState:"clean", BuildDate:"2017-02-15T19:52:15Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

Manually using BASH scripts

* Manifests:

```
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: node-exporter
spec:
  ingress:
  - from:
    - podSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - prometheus
        - key: prometheus
          operator: In
          values:
          - prometheus-k8s
    ports:
    - port: 9100
      protocol: tcp
  podSelector:
    matchLabels:
      app: node-exporter
```

* Prometheus Operator Logs:
N/A
