### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vivekgarg20** [coreos/prometheus-operator#2280]
**What did you do?**
Deployed prometheus operator and created a invalid servicemonitor

**What did you expect to see?**
Operator to discard invalid servicemonitor.

**What did you see instead? Under which circumstances?**
Prometheus operator started crashing.

**Environment**

* Prometheus Operator version:

	v0.26.0

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	kops

* Manifests:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: alertmanager
  name: alertmanager-staging
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
  namespaceSelector:
    matchNames:
    - staging
    port: web . #this part is wrong
  selector:
    matchLabels:
      alertmanager: staging
```
```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1045366]

goroutine 76 [running]:
github.com/coreos/prometheus-operator/pkg/prometheus.(*configGenerator).generateServiceMonitorConfig(0xc00023f630, 0x2, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/promcfg.go:385 +0x7d6
github.com/coreos/prometheus-operator/pkg/prometheus.(*configGenerator).generateConfig(0xc00023f630, 0xc000157880, 0xc0001bf230, 0xc000348cf0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/promcfg.go:166 +0x1dab
github.com/coreos/prometheus-operator/pkg/prometheus.(*Operator).createOrUpdateConfigurationSecret(0xc000484700, 0xc000157880, 0xc00247c130, 0x1, 0x1, 0x0, 0x0)
	/home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:1299 +0x39c
github.com/coreos/prometheus-operator/pkg/prometheus.(*Operator).sync(0xc000484700, 0xc00016a440, 0xe, 0x1134f00, 0xc0003827a0)
	/home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:977 +0x14b8
github.com/coreos/prometheus-operator/pkg/prometheus.(*Operator).processNextWorkItem(0xc000484700, 0x0)
	/home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:859 +0xfc
github.com/coreos/prometheus-operator/pkg/prometheus.(*Operator).worker(0xc000484700)
	/home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:848 +0x2b
created by github.com/coreos/prometheus-operator/pkg/prometheus.(*Operator).Run
	/home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:398 +0x23a

```
insert Prometheus Operator logs relevant to the issue here
```
