### ISSUE TITLE
Could you give me a demo of custom-configuration.

### ISSUE THREAD

**Issue by zhangguanzhang** [coreos/prometheus-operator#2298]
I want to config it by myself
Should I use the `additionalScrapeConfigs` or try other

**Comment by zhangguanzhang** [comment]
Thanks, and how could I can  edit the global variables

**Comment by metalmatze** [comment]
Not sure what you mean by "global variables". Can you elaborate?

**Comment by zhangguanzhang** [comment]
for example:
```yaml
global:
  scrape_interval: 30s
  scrape_timeout: 30s
  evaluation_interval: 1m
```
I want to change the  30 to the 20
