### ISSUE TITLE
shared storage for additional prometheus config | AWS ECS dockers metrics

### ISSUE THREAD

**Issue by ArturZurawski** [coreos/prometheus-operator#2304]
I have prometheus-operator running in k8s created by kops on top of AWS. I'm trying to gather metrics from various tasks running on ECS. Tasks are placed on random container instance so metrics are available under random $IP:$PORT/metrics. To generate list of those tasks I've used https://github.com/signal-ai/prometheus-ecs-sd . Python script in prometheus-ecs-sd container generates following JSON

```
~ # cat 1m-tasks.json
[
    {
        "labels": {
            "instance": "10.112.0.144:41007",
            "ecs_task_id": "920f786643a2de",
            "metrics_path": "/metrics",
            "instance_id": "i-07e2d1fb084f",
            "ecs_task_version": "22",
            "job": "jobname",
            "ecs_cluster": "stage",
            "ecs_container_id": "36020d488",
            "port": "41007"
        },
        "targets": [
            "10.112.0.144:41007"
        ]
    },
    {
        "labels": {
            "instance": "10.112.0.153:33251",
            "ecs_task_id": "114cf40a-0f304585",
            "metrics_path": "/metrics",
            "instance_id": "i-02717222d7bc5",
            "ecs_task_version": "22",
            "job": "jobname",
            "ecs_cluster": "stage",
            "ecs_container_id": "343145093",
            "port": "33251"
        },
        "targets": [
            "10.112.0.153:33251"
        ]
    }
```
which should be loaded (and checked for changes once in a while) by prometheus. 

My idea was to use some shared storage and mount it both in prometheus-ecs-sd container and prometheus. Since there are no shared storages in AWS that are natively supported by k8s I've used [efs-provisioner](https://github.com/kubernetes-incubator/external-storage/tree/master/aws/efs) and created pv and pvc:
```
kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM         STORAGECLASS   REASON   AGE
pvc-07e09798-19f2-11e9-a16a-02ebebe129b0   10Gi       RWX            Delete           Bound    default/efs   aws-efs                 1h
```
```
kubectl get pvc
NAME   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
efs    Bound    pvc-07e09798-19f2-11e9-a16a-02ebebe129b0   10Gi       RWX            aws-efs        1h
```
Now I'm having big problem generating manifest (or even modifying things on the fly) to be able to mount that shared storage to prometheus, to be able to load generated JSONs. I'm running 2 replicas so each of them should have same volume mounted. Could you provide me some hints how to modify `example.jsonnet` to have that efs volume mounted under let's say `/etc/prometheus/conf/extras`?

Since I'm quite new in prometheus and k8s maybe there is some easier way of doing what I'm trying to do.

**Comment by brancz** [comment]
You'll want to just add the service discovery container as a sidecar, which is possible via the `containers` field in the `Prometheus` object.

**Comment by ArturZurawski** [comment]
Thanks @brancz . Unfortunately I cannot find any examples of such a setup. Thing is that this SD will create JSON with multiple services and task definitions. I just don't know how to load that into prometheus. Do you have any examples that I could base on?

**Comment by ArturZurawski** [comment]
OK, I think I'm getting closer ... 

statefulset-controller is returning following error

```
create Pod prometheus-k8s-0 in StatefulSet prometheus-k8s failed error: Pod "prometheus-k8s-0" is invalid: spec.containers[2].volumeMounts[0].name: Not found: "opt-prometheus-ecs"
```

Looks like I don't have volume correctly defined :( 

I started to modify `manifests/prometheus-prometheus.yaml` directly, later on I will try to adjust `jsonnet` one working

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  volumes:
    - name: opt-prometheus-ecs
      emptyDir: {}
  containers:
    - name: prometheus-ecs-sd
      image: 111111111.dkr.ecr.eu-west-1.amazonaws.com/prometheus-sd-ecs:latest
      env:
      - name: AWS_ACCESS_KEY_ID
        value: ""
      - name: AWS_SECRET_ACCESS_KEY
        value: ""
      volumeMounts:
      - name: opt-prometheus-ecs
        mountPath: /opt/prometheus-ecs/
        readOnly: false
  volumeMounts:
  - name: opt-prometheus-ecs
    mountPath: /opt/prometheus-ecs/
    readOnly: true
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  scrape_configs:    
  - job_name: 'ecs-15s'
    scrape_interval: 15s
    file_sd_configs:
      - files:
          - /opt/prometheus-ecs/15s-tasks.json
    relabel_configs:
      - source_labels: [metrics_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
  - job_name: 'ecs-30s'
    scrape_interval: 30s
    file_sd_configs:
      - files:
          - /opt/prometheus-ecs/30s-tasks.json
    relabel_configs:
      - source_labels: [metrics_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
  - job_name: 'ecs-1m'
    scrape_interval: 1m
    file_sd_configs:
      - files:
          - /opt/prometheus-ecs/1m-tasks.json
    relabel_configs:
      - source_labels: [metrics_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
  - job_name: 'ecs-5m'
    scrape_interval: 5m
    file_sd_configs:
      - files:
          - /opt/prometheus-ecs/5m-tasks.json
    relabel_configs:
      - source_labels: [metrics_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
  baseImage: quay.io/prometheus/prometheus
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: v2.5.0
```

Could anyone please point out what I'm doing wrong here?
