### ISSUE TITLE
Config file name out of sync between secret and reloader

### ISSUE THREAD

**Issue by abursavich** [coreos/prometheus-operator#2310]
**What did you do?**
Use prometheus-operator:master in a dev cluster.

**What did you expect to see?**
Everything working.

**What did you see instead? Under which circumstances?**

The config file in the generated secret is named `prometheus.yaml.gz` but prometheus-config-reloader is looking for a file named `prometheus.yaml`, so prometheus is crash looping.  I skimmed through the code and don't immediately see how these values should be out of sync.  It looks like the reloader flag value and the secret file name come from the same constant?

**Environment**

* Prometheus Operator version:

	Git: 0714fe498018819fa790fc040319210d00e46e7b

* Kubernetes version information:

	Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-01-16T18:55:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	Openshift

* Manifests:

Relevant manifests that I created:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-operator
  namespace: monitoring
  labels:
    app: prometheus-operator
    prometheus: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-operator
  template:
    metadata:
      labels:
        app: prometheus-operator
        prometheus: default
    spec:
      serviceAccountName: prometheus-operator
      containers:
        - name: prometheus-operator
          image: quay.io/coreos/prometheus-operator:master
          imagePullPolicy: Always
          args:
            - --kubelet-service=kube-system/kubelet
            - --log-format=json
            - --logtostderr
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: default
  namespace: monitoring
  labels:
    app: prometheus
    prometheus: default
spec:
  podMetadata:
    annotations:
      iam.amazonaws.com/role: k8s-dev-thanos
    labels:
      app: prometheus
      prometheus: default
      thanos-peer: "true"
  image: quay.io/prometheus/prometheus:v2.6.0
  version: v2.6.0
  resources:
      limits:
        cpu: 2
        memory: 12Gi
      requests:
        cpu: 2
        memory: 12Gi
  replicas: 2
  retention: "3d"
  serviceAccountName: prometheus-default
  serviceMonitorNamespaceSelector:
    any: true
  serviceMonitorSelector:
    matchLabels:
      prometheus: default
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: "gp2"
        resources:
          requests:
            storage: "40G"
  additionalScrapeConfigs:
    name: prometheus-scrape-config
    key: config
  thanos:
    image: improbable/thanos:v0.2.1
    objectStoreConfig:
      key: objstore.yaml
      name: thanos-config
    peers: thanos-peers.monitoring.svc:10900
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 1
        memory: 2Gi
```

Relevant manifests that prometheus-operator created:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-default
  annotations:
    prometheus-operator-input-hash: '8487623394879341828'
  creationTimestamp:
  generation: 1
  labels:
    app: prometheus
    prometheus: default
  ownerReferences:
    - name: default
      apiVersion: monitoring.coreos.com/v1
      blockOwnerDeletion: true
      controller: true
      kind: Prometheus
      uid: 5585c20a-1a27-11e9-b6de-0289343d814a
  selfLink: /apis/apps/v1/namespaces/monitoring/statefulsets/prometheus-default
spec:
  podManagementPolicy: Parallel
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus
      prometheus: default
      thanos-peer: 'true'
  serviceName: prometheus-operated
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: k8s-dev-thanos
      creationTimestamp:
      labels:
        app: prometheus
        prometheus: default
        thanos-peer: 'true'
    spec:
      containers:
        - name: prometheus
          args:
            - --web.console.templates=/etc/prometheus/consoles
            - --web.console.libraries=/etc/prometheus/console_libraries
            - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
            - --storage.tsdb.path=/prometheus
            - --storage.tsdb.retention=3d
            - --web.enable-lifecycle
            - --storage.tsdb.no-lockfile
            - --web.route-prefix=/
            - --storage.tsdb.min-block-duration=2h
            - --storage.tsdb.max-block-duration=2h
          image: quay.io/prometheus/prometheus:v2.6.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /-/healthy
              port: web
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          ports:
            - name: web
              containerPort: 9090
              protocol: TCP
          readinessProbe:
            failureThreshold: 120
            httpGet:
              path: /-/ready
              port: web
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: '2'
              memory: 12Gi
            requests:
              cpu: '2'
              memory: 12Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: config-out
              mountPath: /etc/prometheus/config_out
              readOnly: true
            - name: prometheus-default-db
              mountPath: /prometheus
              subPath: prometheus-db
            - name: prometheus-default-rulefiles-0
              mountPath: /etc/prometheus/rules/prometheus-default-rulefiles-0
        - name: prometheus-config-reloader
          args:
            - --log-format=json
            - --reload-url=http://localhost:9090/-/reload
            - --config-file=/etc/prometheus/config/prometheus.yaml  ### CONFIG FILE NAME MISSING .gz
            - --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml
          command:
            - /bin/prometheus-config-reloader
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          image: quay.io/coreos/prometheus-config-reloader:v0.27.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/config
            - name: config-out
              mountPath: /etc/prometheus/config_out
        - name: rules-configmap-reloader
          args:
            - --webhook-url=http://localhost:9090/-/reload
            - --volume-dir=/etc/prometheus/rules/prometheus-default-rulefiles-0
          image: quay.io/coreos/configmap-reload:v0.0.1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 25m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: prometheus-default-rulefiles-0
              mountPath: /etc/prometheus/rules/prometheus-default-rulefiles-0
        - name: thanos-sidecar
          args:
            - sidecar
            - --prometheus.url=http://localhost:9090
            - --tsdb.path=/prometheus
            - --cluster.address=[$(POD_IP)]:10900
            - --grpc-address=[$(POD_IP)]:10901
            - --cluster.peers=thanos-peers.monitoring.svc:10900
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          image: improbable/thanos:v0.2.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 10902
              protocol: TCP
            - name: grpc
              containerPort: 10901
              protocol: TCP
            - name: cluster
              containerPort: 10900
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: '1'
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: prometheus-default-db
              mountPath: /prometheus
              subPath: prometheus-db
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: prometheus-default
      serviceAccountName: prometheus-default
      terminationGracePeriodSeconds: 600
      volumes:
        - name: config
          secret:
            defaultMode: 420
            secretName: prometheus-default
        - name: config-out
          emptyDir: {}
        - name: prometheus-default-rulefiles-0
          configMap:
            name: prometheus-default-rulefiles-0
            defaultMode: 420
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: prometheus-default-db
        creationTimestamp:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 40G
        storageClassName: gp2
      status:
        phase: Pending
status:
  replicas: 0
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: prometheus-default
  annotations:
    generated: 'true'
  creationTimestamp:
  labels:
    managed-by: prometheus-operator
  ownerReferences:
    - name: default
      apiVersion: monitoring.coreos.com/v1
      blockOwnerDeletion: true
      controller: true
      kind: Prometheus
      uid: 5585c20a-1a27-11e9-b6de-0289343d814a
  selfLink: /api/v1/namespaces/monitoring/secrets/prometheus-default
data:
  prometheus.yaml.gz: [CONTENT OMITTED]  ### CONFIG FILE NAME INCLUDES .gz
```

* Prometheus Operator Logs:

prometheus-config-reloader:
```
{"caller":"main.go:70","msg":"Starting prometheus-config-reloader version '0.27.0'.","ts":"2019-01-17T15:57:02.058113481Z"}
add config file watch: no such file or directory
```

prometheus:
```
level=info ts=2019-01-17T16:58:37.563982067Z caller=main.go:243 msg="Starting Prometheus" version="(version=2.6.0, branch=HEAD, revision=dbd1d58c894775c0788470944b818cc724f550fb)"
level=info ts=2019-01-17T16:58:37.564052849Z caller=main.go:244 build_context="(go=go1.11.3, user=root@bf5760470f13, date=20181217-15:14:46)"
level=info ts=2019-01-17T16:58:37.56407383Z caller=main.go:245 host_details="(Linux 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 prometheus-default-1 (none))"
level=info ts=2019-01-17T16:58:37.564092521Z caller=main.go:246 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2019-01-17T16:58:37.564110633Z caller=main.go:247 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2019-01-17T16:58:37.564621042Z caller=main.go:561 msg="Starting TSDB ..."
level=info ts=2019-01-17T16:58:37.564657795Z caller=web.go:429 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2019-01-17T16:58:37.568953208Z caller=main.go:571 msg="TSDB started"
level=info ts=2019-01-17T16:58:37.568993603Z caller=main.go:631 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2019-01-17T16:58:37.569033743Z caller=main.go:430 msg="Stopping scrape discovery manager..."
level=info ts=2019-01-17T16:58:37.569047524Z caller=main.go:444 msg="Stopping notify discovery manager..."
level=info ts=2019-01-17T16:58:37.569054701Z caller=main.go:466 msg="Stopping scrape manager..."
level=info ts=2019-01-17T16:58:37.569067869Z caller=main.go:440 msg="Notify discovery manager stopped"
level=info ts=2019-01-17T16:58:37.569096232Z caller=main.go:426 msg="Scrape discovery manager stopped"
level=info ts=2019-01-17T16:58:37.569117338Z caller=manager.go:664 component="rule manager" msg="Stopping rule manager..."
level=info ts=2019-01-17T16:58:37.569149319Z caller=manager.go:670 component="rule manager" msg="Rule manager stopped"
level=info ts=2019-01-17T16:58:37.56911525Z caller=main.go:460 msg="Scrape manager stopped"
level=info ts=2019-01-17T16:58:37.570080633Z caller=notifier.go:521 component=notifier msg="Stopping notification manager..."
level=info ts=2019-01-17T16:58:37.570100456Z caller=main.go:615 msg="Notifier manager stopped"
level=error ts=2019-01-17T16:58:37.570137192Z caller=main.go:624 err="error loading config from \"/etc/prometheus/config_out/prometheus.env.yaml\": couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): open /etc/prometheus/config_out/prometheus.env.yaml: no such file or directory"
```

**Comment by abursavich** [comment]
My best guess at the moment is that the input hash didn't change, so the StatefulSet wasn't updated with the new config file name, even though the secret was.

https://github.com/coreos/prometheus-operator/blob/bf4d65eeec4f26b079e406c79925fd3c586cb214/pkg/prometheus/operator.go#L1033

Deleting the prometheus StatefulSet and letting the operator recreate it resolved the issue.

**Comment by abursavich** [comment]
But now I have a different one, probably still something to do with gzip :(

level=error ts=2019-01-17T17:34:05.947101629Z caller=main.go:624 err="error loading config from \"/etc/prometheus/config_out/prometheus.env.yaml\": couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: yaml: control characters are not allowed"

**Comment by abursavich** [comment]
Bumping prometheus-config-reloader to master fixed the new issue.

```
--prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:master
```

**Comment by abursavich** [comment]
Bumping the version of the prometheus-config-reloader appears to have changed the input hash and triggered a StatefulSet update, so I'm gonna chalk this issue up to me running on master. I don't think the original issue will happen when a new release is cut, so I'm closing this out.

Please cut a new release soon so I can get off master! :)

**Comment by Deshke** [comment]
just ran into this with the operator 0.29, manually edit of the statefull set and removing the `.gz` from the prometheus.out file worked


```json
          {
            "name": "prometheus-config-reloader",
            "image": "quay.io/coreos/prometheus-config-reloader:v0.29.0",
            "command": [
              "/bin/prometheus-config-reloader"
            ],
            "args": [
              "--log-format=logfmt",
              "--reload-url=http://localhost:9090/-/reload",
              "--config-file=/etc/prometheus/config/prometheus.yaml", # no .gz !
              "--config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml"
            ],
```

**Comment by brancz** [comment]
@Deshke that sounds odd. Are you sure you're using consistent versions of the reloader and prometheus operator?

**Comment by Deshke** [comment]
jep, updated the operator and wondered why all the prometheus instances would not come up. got the error `add config file watch: no such file or directory` and started digging...

**Comment by Deshke** [comment]
this could have to do something with additonal configurations within configmaps or the whole configuration for prometheus being present within a secret, not sure. But soon as i add the `.gz` to the config file, the reloader refuses to start

**Comment by brancz** [comment]
@Deshke could you be more specific about your setup. This should not be happening.

**Comment by Deshke** [comment]
* operator is from https://github.com/coreos/prometheus-operator/blob/ea976ee1b7ba69c3d401e2b18cb4a8ff4800b427/bundle.yaml


* prometheus configuration is stored within a secret 

```
kubectl -n monitoring get secret  prometheus-external-services -o yaml
apiVersion: v1
data:
  configmaps.json: .....==
  prometheus.yaml: ......
kind: Secret
metadata:
  annotations:
    generated: "true"
  creationTimestamp: 2018-01-22T14:03:43Z
  labels:
    managed-by: prometheus-operator
  name: prometheus-external-services
  namespace: monitoring
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Prometheus
    name: external-services
    uid: 0e4e66f4-ff7d-11e7-8de2-0a6a481823d0
  resourceVersion: "141329007"
  selfLink: /api/v1/namespaces/monitoring/secrets/prometheus-external-services
  uid: 0e4f1f3e-ff7d-11e7-8872-02006b47629a
type: Opaque
```

* prometheus
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
....
spec:
  ExternalURL: .....
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  replicas: 1
  resources:
    requests:
      memory: 12G
  retention: 48h
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        metadata:
          annotations:
            volume.alpha.kubernetes.io/storage-class: gp2
          labels:
            prometheus: ingest-webrtc
        resources:
          requests:
            storage: 20Gi
  version: v2.7.0
```

* pod discription

```
Name:           prometheus-external-services-2
Namespace:      monitoring
Node:           ip-172-25-126-26.us-east-2.compute.internal/172.25.126.26
Start Time:     Thu, 28 Feb 2019 11:52:49 +0100
Labels:         app=prometheus
                controller-revision-hash=prometheus-external-services-5595b687bf
                prometheus=external-services
                statefulset.kubernetes.io/pod-name=prometheus-external-services-2
Annotations:    <none>
Status:         Running
IP:             100.88.12.180
Controlled By:  StatefulSet/prometheus-external-services
Containers:
  prometheus:
    Container ID:  docker://295f153afb2dbaa30e26a963a25ba424a9b57eec4f2d593c037ca520fa42da5c
    Image:         registry.tld/sysad/prometheus-azure:v2.7.0
    Image ID:      docker-pullable://registry.tld/sysad/prometheus-azure@sha256:69ce9a518f8da14c317b3f2e101e1004d80a01c18a28e9ea0dc0a5a312f6169c
    Port:          9090/TCP
    Host Port:     0/TCP
    Args:
      --web.console.templates=/etc/prometheus/consoles
      --web.console.libraries=/etc/prometheus/console_libraries
      --config.file=/etc/prometheus/config_out/prometheus.env.yaml
      --storage.tsdb.path=/prometheus
      --storage.tsdb.retention=21d
      --web.enable-lifecycle
      --storage.tsdb.no-lockfile
      --web.route-prefix=/
    State:          Running
      Started:      Thu, 28 Feb 2019 11:53:23 +0100
    Ready:          False
    Restart Count:  0
    Requests:
      memory:     12G
    Liveness:     http-get http://:web/-/healthy delay=0s timeout=3s period=5s #success=1 #failure=6
    Readiness:    http-get http://:web/-/ready delay=0s timeout=3s period=5s #success=1 #failure=120
    Environment:  <none>
    Mounts:
      /etc/prometheus/config_out from config-out (ro)
      /etc/prometheus/rules/prometheus-external-services-rulefiles-0 from prometheus-external-services-rulefiles-0 (rw)
      /prometheus from prometheus-external-services-db (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-28zcn (ro)
  prometheus-config-reloader:
    Container ID:  docker://e1452c83ed8347335160ec0d658d13a2928e9ecd8be6c27d1d68bb491fa8cc4a
    Image:         quay.io/coreos/prometheus-config-reloader:v0.29.0
    Image ID:      docker-pullable://quay.io/coreos/prometheus-config-reloader@sha256:d4b5c90b0937b568d25baa38d8ca61ac927069f30f02e8757f0eae9ee335be23
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/prometheus-config-reloader
    Args:
      --log-format=logfmt
      --reload-url=http://localhost:9090/-/reload
      --config-file=/etc/prometheus/config/prometheus.yaml
      --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml
    State:          Running
      Started:      Thu, 28 Feb 2019 11:53:24 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     50m
      memory:  50Mi
    Requests:
      cpu:     50m
      memory:  50Mi
    Environment:
      POD_NAME:  prometheus-external-services-2 (v1:metadata.name)
    Mounts:
      /etc/prometheus/config from config (rw)
      /etc/prometheus/config_out from config-out (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-28zcn (ro)
  rules-configmap-reloader:
    Container ID:  docker://b2f006b422a66d00e4ac93ebc19a41494627418e061edd4a557dd5355645cf20
    Image:         quay.io/coreos/configmap-reload:v0.0.1
    Image ID:      docker-pullable://quay.io/coreos/configmap-reload@sha256:e2fd60ff0ae4500a75b80ebaa30e0e7deba9ad107833e8ca53f0047c42c5a057
    Port:          <none>
    Host Port:     <none>
    Args:
      --webhook-url=http://localhost:9090/-/reload
      --volume-dir=/etc/prometheus/rules/prometheus-external-services-rulefiles-0
    State:          Running
      Started:      Thu, 28 Feb 2019 11:53:24 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  25Mi
    Requests:
      cpu:        100m
      memory:     25Mi
    Environment:  <none>
    Mounts:
      /etc/prometheus/rules/prometheus-external-services-rulefiles-0 from prometheus-external-services-rulefiles-0 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-28zcn (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  prometheus-external-services-db:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  prometheus-external-services-db-prometheus-external-services-2
    ReadOnly:   false
  config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-external-services
    Optional:    false
  config-out:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  prometheus-external-services-rulefiles-0:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      prometheus-external-services-rulefiles-0
    Optional:  false
  default-token-28zcn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-28zcn
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age               From                                                  Message
  ----     ------                  ----              ----                                                  -------
  Normal   Scheduled               2m                default-scheduler                                     Successfully assigned prometheus-external-services-2 to ip-172-25-126-26.us-east-2.compute.internal
  Normal   SuccessfulMountVolume   2m                kubelet, ip-172-25-126-26.us-east-2.compute.internal  MountVolume.SetUp succeeded for volume "config-out"
  Normal   SuccessfulMountVolume   2m                kubelet, ip-172-25-126-26.us-east-2.compute.internal  MountVolume.SetUp succeeded for volume "default-token-28zcn"
  Normal   SuccessfulMountVolume   2m                kubelet, ip-172-25-126-26.us-east-2.compute.internal  MountVolume.SetUp succeeded for volume "config"
  Normal   SuccessfulMountVolume   2m                kubelet, ip-172-25-126-26.us-east-2.compute.internal  MountVolume.SetUp succeeded for volume "prometheus-external-services-rulefiles-0"
  Normal   SuccessfulAttachVolume  2m                attachdetach-controller                               AttachVolume.Attach succeeded for volume "pvc-4fa77ec1-1ec7-11e8-a796-06a2bab0bcbc"
  Normal   Created                 2m                kubelet, ip-172-25-126-26.us-east-2.compute.internal  Created container
  Normal   SuccessfulMountVolume   2m                kubelet, ip-172-25-126-26.us-east-2.compute.internal  MountVolume.SetUp succeeded for volume "pvc-4fa77ec1-1ec7-11e8-a796-06a2bab0bcbc"
  Normal   Pulled                  2m                kubelet, ip-172-25-126-26.us-east-2.compute.internal  Container image "registry.tld/sysad/prometheus-azure:v2.7.0" already present on machine
  Normal   Started                 2m                kubelet, ip-172-25-126-26.us-east-2.compute.internal  Started container
  Normal   Pulled                  2m                kubelet, ip-172-25-126-26.us-east-2.compute.internal  Container image "quay.io/coreos/prometheus-config-reloader:v0.29.0" already present on machine
  Normal   Created                 2m                kubelet, ip-172-25-126-26.us-east-2.compute.internal  Created container
  Normal   Started                 2m                kubelet, ip-172-25-126-26.us-east-2.compute.internal  Started container
  Normal   Pulled                  2m                kubelet, ip-172-25-126-26.us-east-2.compute.internal  Container image "quay.io/coreos/configmap-reload:v0.0.1" already present on machine
  Normal   Created                 2m                kubelet, ip-172-25-126-26.us-east-2.compute.internal  Created container
  Normal   Started                 2m                kubelet, ip-172-25-126-26.us-east-2.compute.internal  Started container
  Warning  Unhealthy               1m (x11 over 2m)  kubelet, ip-172-25-126-26.us-east-2.compute.internal  Readiness probe failed: HTTP probe failed with statuscode: 503
```
