### ISSUE TITLE
How do I configure alertmanager in prometheus-operator

### ISSUE THREAD

**Issue by jianzzz** [coreos/prometheus-operator#2317]
I have executed the following order:
kubectl -n monitoring get pod alertmanager-main-0  -o yaml
and it's output:
```
spec:
  containers:
  - args:
    - --config.file=/etc/alertmanager/config/alertmanager.yaml
    - --cluster.listen-address=[$(POD_IP)]:6783
    - --storage.path=/alertmanager
    - --data.retention=120h
    - --web.listen-address=:9093
    - --web.route-prefix=/
    - --cluster.peer=alertmanager-main-0.alertmanager-operated.monitoring.svc:6783
    - --cluster.peer=alertmanager-main-1.alertmanager-operated.monitoring.svc:6783
    - --cluster.peer=alertmanager-main-2.alertmanager-operated.monitoring.svc:6783
```
This will cause alertmanager listens at [xxx.xxx.xxx.xxx]:6783, not xxx.xxx.xxx.xxx:6783.
Is this the reason that cause alertmanager  can not find each other in cluster?
