### ISSUE TITLE
kube-state-metrics pod restarts on delete/join node in k8s cluster

### ISSUE THREAD

**Issue by Shini31** [coreos/prometheus-operator#2320]
**What did you do?**
Join a node in the K8s cluster, delete a node in the k8s cluster

**What did you expect to see?**
kube-state-metrics provides metrics without interruption 

**What did you see instead? Under which circumstances?**
kube-state-metrics pod restarts, a new replicaset is created and metrics are missing in Grafana

**Environment**

* Prometheus Operator version:

0.26.0

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

kubespray

* Manifests:

```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: kube-state-metrics
    name: kube-state-metrics
    namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-state-metrics
  template:
    metadata:
      labels:
        app: kube-state-metrics
    spec:
      containers:
      - args:
        - --secure-listen-address=:8443
        - --upstream=http://127.0.0.1:8081/
        image: quay.io/coreos/kube-rbac-proxy:v0.4.0
        name: kube-rbac-proxy-main
        ports:
        - containerPort: 8443
          name: https-main
        resources:
          limits:
            cpu: 20m
            memory: 40Mi
          requests:
            cpu: 10m
            memory: 20Mi
      - args:
        - --secure-listen-address=:9443
        - --upstream=http://127.0.0.1:8082/
        image: quay.io/coreos/kube-rbac-proxy:v0.4.0
        name: kube-rbac-proxy-self
        ports:
        - containerPort: 9443
          name: https-self
        resources:
          limits:
            cpu: 20m
            memory: 40Mi
          requests:
            cpu: 10m
            memory: 20Mi
      - args:
        - --host=127.0.0.1
        - --port=8081
        - --telemetry-host=127.0.0.1
        - --telemetry-port=8082
        image: quay.io/coreos/kube-state-metrics:v1.4.0
        name: kube-state-metrics
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 150Mi
      - command:
        - /pod_nanny
        - --container=kube-state-metrics
        - --cpu=100m
        - --extra-cpu=2m
        - --memory=150Mi
        - --extra-memory=30Mi
        - --threshold=5
        - --deployment=kube-state-metrics
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/coreos/addon-resizer:1.0
        name: addon-resizer
        resources:
          limits:
            cpu: 50m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 30Mi
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: kube-state-metrics
```

* Prometheus Operator Logs:
**Before the node delete:**
```
kubectl get replicasets.
NAME                             DESIRED   CURRENT   READY   AGE
...
kube-state-metrics-b954b8d45     1         1         1       2d21h
...

kubectl get pods
NAME                                   READY   STATUS    RESTARTS   AGE
...
kube-state-metrics-b954b8d45-c66w8     4/4     Running   0          2d21h
...
```

**After the node delete:**
```
kubectl get replicasets.
NAME                             DESIRED   CURRENT   READY   AGE
...
kube-state-metrics-54b8479bc7    1         1         1       23s
kube-state-metrics-b954b8d45     0         0         0       2d21h
...

kubectl get pods
NAME                                   READY   STATUS    RESTARTS   AGE
...
kube-state-metrics-54b8479bc7-rdncs    4/4     Running   0          23s
...
```

The behaviour is the same when i add a new node.
