### ISSUE TITLE
Error while deploying custom prometheus operator

### ISSUE THREAD

**Issue by psapozhnikov** [coreos/prometheus-operator#2333]
We are using OpenShift 3.11 Enterprise and we have deployed the openshift-monitoring project which includes prometheus operator and Grafana.

We would like to scrape metrics from our application pods running in different namespace. I have followed the documentation given here to deploy custom prometheus operator with service monitor.

The error I am getting is this:

```
create Pod prometheus-consumers-0 in StatefulSet prometheus-consumers failed error: pods "prometheus-consumers-0" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{2000}: 2000 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1000080000, 1000089999] spec.containers[1].securityContext.securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1000080000, 1000089999] spec.containers[2].securityContext.securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1000080000, 1000089999]]  
```

What am I doing wrong? I believe that i created all necessary service accounts and roles as listed in documentation.

**Comment by abursavich** [comment]
SecurityContextConstraints are the biggest pain in the ass part of OpenShift (sorry CoreOS/RedHat people). I really hope they will be migrated to upstream [PodSecurityPolicies](https://kubernetes.io/docs/concepts/policy/pod-security-policy/).

The easiest way around this is to set a serviceAccountName in your [PrometheusSpec](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec), create an SCC with runAsUser and fsGroup set to type:RunAsAny, and attach it to your prometheus service account (e.g. users: ["system:serviceaccount:$NAMESPACE:$SERVICE_ACCOUNT_NAME"]).

https://blog.openshift.com/understanding-service-accounts-sccs/
https://godoc.org/github.com/openshift/api/security/v1#SecurityContextConstraints

**Comment by abursavich** [comment]
I don't guarantee it's the best, but here's an SCC that works.

```
apiVersion: v1
kind: SecurityContextConstraints
metadata:
  name: prometheus
users:
- system:serviceaccount:${NAMESPACE}:${SERVICE_ACCOUNT_NAME}
requiredDropCapabilities:
- MKNOD
- SYS_CHROOT
runAsUser:
  type: MustRunAs
  uid: 1000
fsGroup:
  type: MustRunAs
  ranges:
    - min: 2000
      max: 2000
seLinuxContext:
  type: MustRunAs
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
```
