### ISSUE TITLE
Deleted namespace - Prometheus operator not recovered data from persistence storage (Cinder)

### ISSUE THREAD

**Issue by raz5** [coreos/prometheus-operator#2336]
**What did you do?**
Deployed Prometheus operator with persistence storage. (Cinder -  created storage class and mapped as shown below)

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: persisted
spec:
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: ssd
        resources:
          requests:
            storage: 40Gi

**What did you expect to see?**
After deleting namespace(where prometheus operator is running), It should be able to recover the data from perstistence storage. but its not

**What did you see instead? Under which circumstances?**
data not reclaimed
**Environment**
k8s
* Prometheus Operator version:

	insert image tag or Git SHA here

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
name: persisted
spec:
storage:
volumeClaimTemplate:
spec:
storageClassName: ssd
resources:
requests:
storage: 40Gi

  storage:
    volumeClaimTemplate:
      #name: prometheus-vct
      metadata:
        name: prometheus-vct
        annotations:
          volume.beta.kubernetes.io/storage-class: "persisted"
      spec:
        #storageClassName: persisted
        resources:
          requests:
            storage: 1Gi


```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```
