### ISSUE TITLE
Updating a persistent volume size (GKE 1.11) does nothing

### ISSUE THREAD

**Issue by aiman-alsari** [coreos/prometheus-operator#2357]
**What did you do?**

I had a volume claim set up in my Prometheus resource:
```
    storage:
      volumeClaimTemplate:
        metadata:
          labels:
            prometheus: k8s
          name: prometheus-storage
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 150Gi
          storageClassName: prometheus-ssd
```
I tried updating the storage.volumeClaimTemplate.spec.resources.requests.storage from 150Gi to 250Gi. The operator restarted my Prometheus statefulset pods, but the associated persistent volume claim stayed at 150Gi.

**What did you expect to see?**

I have defined my persistent storage to have `allowVolumeExpansion: true`. This is a kubernetes 1.11 feature. I expected that the PVC that is managed by prometheus-operator would get updated with the new value of 250Gi, and that the pods would then restart and re-mount with the expanded volumes.

**Environment**

* Prometheus Operator version: 0.26.0

* Kubernetes version information: v1.11.6-gke.3

* Kubernetes cluster kind: GKE
