### ISSUE TITLE
AlertmanagerMembersInconsistent is firing even though targets are up and healthy

### ISSUE THREAD

**Issue by Aracki** [coreos/prometheus-operator#2368]
Why **AlertmanagerMembersInconsistent** is firing? What does alert variable `alertmanager_cluster_members` represents?

I commented [kube-scheduler](https://github.com/Aracki/gobernetes/blob/master/k8s_manifests/monitoring/prometheus-serviceMonitorKubeScheduler.yaml) and [kube-controller-manager](https://github.com/Aracki/gobernetes/blob/master/k8s_manifests/monitoring/prometheus-serviceMonitorKubeControllerManager.yaml) ServiceMonitors because prometheus cannot see them as running. I fixed CoreDNS by editing coredns service like suggested here #2278. So when I check `prometheus-url/targets` every ServiceMonitor is up and healthy.

Beside this, alerts DeadMansSwitch and KubeVersionMismatch are also firing which I understand why.

**Environment**

* Prometheus Operator version:

`quay.io/coreos/prometheus-operator:v0.27.0`

* Kubernetes version info:

```
Client Version: "v1.13.1"
Server Version: "v1.13.2"
```

* Manifests I am using:

https://github.com/Aracki/gobernetes/tree/master/k8s_manifests/monitoring

**Comment by brancz** [comment]
It means for some reason your alertmanager instances have different configurations loaded, which should never happen, and you need to have a look and fix it :slightly_smiling_face: .

**Comment by brancz** [comment]
Would you like to add this to the description of the alert? I'm sure more people could benefit from that :slightly_smiling_face:

**Comment by Aracki** [comment]
What do you mean by description? I'm using a default manifests with default alert rule: 
```
    - alert: AlertmanagerMembersInconsistent
      annotations:
        message: Alertmanager has not found all other members of the cluster.
      expr: |
        alertmanager_cluster_members{job="alertmanager-main"}
          != on (service) GROUP_LEFT()
        count by (service) (alertmanager_cluster_members{job="alertmanager-main"})
      for: 5m
      labels:
        severity: critical
```

The only things I customized are alertmanager secret for sending slack notifications and deleted those two ServiceMonitors.
