### ISSUE TITLE
Question - how to correctly squash Kubernetes Metadata

### ISSUE THREAD

**Issue by benemon** [coreos/prometheus-operator#2370]
**What did you do?**
I am attempting to squash the Kubernetes metadata metrics published by the PrometheusOperator, apparently by default - for my usecase I don't care about them, and they are clutter that I just don't need.

As an experiment, I added the following ServiceMonitor definition:
```
apiVersion: app.monitoring.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: monitoring
  name: my-app-metrics
spec:
  endpoints:
  - interval: 30s
    path: /api/metrics
    port: http
    metricRelabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: drop
  namespaceSelector: {}
  selector:
    matchLabels:
      app: my-app
```

This results in: 
```
  metric_relabel_configs:
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    replacement: $1
    action: drop
```
..being appended to my prometheus config. However, that label is not squashed.

In addition, I tried the following because maybe once the relabelling from __meta_kubernetes_pod_name to 'pod' has occurred, I need to squash 'pod' instead:

```
apiVersion: app.monitoring.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: monitoring
  name: my-app-metrics
spec:
  endpoints:
  - interval: 30s
    path: /api/metrics
    port: http
    metricRelabelings:
    - sourceLabels: [pod]
      action: drop
  namespaceSelector: {}
  selector:
    matchLabels:
      app: my-app
```
...same result.

**What did you expect to see?**
I would have expected to see the __meta_kubernetes_pod_name metric dropped.

How can I effectively squash those Kubernetes metrics?

**What did you see instead? Under which circumstances?**
When the configuration was automatically refreshed, nothing changed in terms of labels being ingested.

**Environment**
OpenShift Container Platform 3.11

* Prometheus Operator version:

`registry.redhat.io/openshift3/ose-prometheus-operator:v3.11'`

* Kubernetes version information:

```
oc v4.0.0-0.79.0
kubernetes v1.11.0+d4cacc0
features: Basic-Auth

Server <nope>
openshift v3.11.51
kubernetes v1.11.0+d4cacc0
```

* Kubernetes cluster kind: 

OpenShift

**Comment by brancz** [comment]
Metric relabelling is just about when Prometheus actually scraped data from targets, which will never have the pod label. What you are looking for is just `relabelings`, and instead of the meta label, you would just do `pod`. That said, I highly encourage you not to drop these labels, they are extremely useful when you actually get an alert and need to debug something.

**Comment by glasswalk3r** [comment]
@brancz , that means that `pod` is being added as a label by Prometheus itself, using service discovery, right?
I'm experimenting something like @benemon, but I'm trying to get rid only of the labels, not the metrics. That is the configuration I used:

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-scraper
  namespace: monitoring
spec:
  jobLabel: component
  selector:
    matchLabels:
      scrape_metrics: "enabled"
  namespaceSelector:
    matchNames:
      - forno
  endpoints:
  - port: http
    interval: 10s
    relabelings:
      #instance="100.107.209.231:9090"
      #pod="test-59bbbb77b5-26tg9"
      #service="test"
      - regex: 'instance|pod|service'
        action: labeldrop
```
The result is that I can get ride of `pod` and `service`, but not `instance`:

```
python_info{endpoint="http",implementation="CPython",instance="100.107.209.247:9090",job="test",major="3",minor="6",namespace="dev",patchlevel="8",version="3.6.8"}
```

Looking from Prometheus dashboard (http://SERVER/config), I can see the configuration added under `scrape_configs:`, but there is also a lot of relabeling that I guess was added by Prometheus Operator itself. Maybe that is the reason I can still see `instance` as a label?

Thanks!
