### ISSUE TITLE
Service monitor not talking to service

### ISSUE THREAD

**Issue by dent50cent** [coreos/prometheus-operator#2388]
**What did you do?**
I'm trying to set up some custom metrics on our Kubernetes cluster. I'm using the Kube-Prometheus set up if that helps at all. I've created a service monitor and the `/metrics` endpoint on the service via the [Prometheus Python Client](https://github.com/prometheus/client_python).
**What did you expect to see?**
In the service discovery section of the Prometheus web UI, I was expecting to see the services that have been created show up with some target labels.
**What did you see instead? Under which circumstances?**
Target labels all say "Dropped", unsure of the cause.

**Environment**

* Prometheus Operator version:

	quay.io/coreos/prometheus-operator:v0.27.0

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:38Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.6-gke.2", GitCommit:"04ad69a117f331df6272a343b5d8f9e2aee5ab0c", GitTreeState:"clean", BuildDate:"2019-01-04T16:19:46Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	Using a GCE cluster

* Manifests:
service monitor yaml
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aimmo-game
  namespace: default
spec:
  endpoints:
    - port: tcp
      interval: 15s
  selector:
    matchLabels:
      app: aimmo-game    
```
service yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aimmo-game
    game_id: "49"
  name: game-49
  namespace: default
spec:
  ports:
  - nodePort: 30256
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: aimmo-game
    game_id: "49"
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```
prometheus config for the service monitor
```yaml
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
  external_labels:
    prometheus: monitoring/k8s
    prometheus_replica: prometheus-k8s-0
alerting:
  alert_relabel_configs:
  - separator: ;
    regex: prometheus_replica
    replacement: $1
    action: labeldrop
  alertmanagers:
  - kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - monitoring
    scheme: http
    path_prefix: /
    timeout: 10s
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      separator: ;
      regex: alertmanager-main
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_endpoint_port_name]
      separator: ;
      regex: web
      replacement: $1
      action: keep
rule_files:
- /etc/prometheus/rules/prometheus-k8s-rulefiles-0/*.yaml
scrape_configs:
- job_name: default/aimmo-game/0
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - default
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_label_app]
    separator: ;
    regex: aimmo-game
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: tcp
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    regex: Node;(.*)
    target_label: node
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    regex: Pod;(.*)
    target_label: pod
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: ${1}
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: tcp
    action: replace
```
