### ISSUE TITLE
prometheus-k8s Pods CrashLoopBackoff in kube-prometheus  

### ISSUE THREAD

**Issue by bsakweson** [coreos/prometheus-operator#2413]
**What did you do?**
Installed kube-prometheus on my cluster.

**What did you expect to see?**
I expected to see a successful monitoring system up and running.

**What did you see instead? Under which circumstances?**
I noticed that the third container in prometheus is failing on both pods of the stateful set. Also, alertmanager is failing.
```
NAME                                   READY   STATUS             RESTARTS   AGE
alertmanager-main-0                    1/2     CrashLoopBackOff   7          11m
grafana-5d8f767-rrxzp                  1/1     Running            0          11m
kube-state-metrics-5447bd9c76-r598b    4/4     Running            0          10m
node-exporter-blg9l                    2/2     Running            0          11m
node-exporter-hv5kk                    2/2     Running            0          11m
node-exporter-kcrkz                    2/2     Running            0          11m
node-exporter-mdz9w                    2/2     Running            0          11m
node-exporter-rmlzj                    2/2     Running            0          11m
node-exporter-x72cf                    2/2     Running            0          11m
node-exporter-xgttt                    2/2     Running            0          11m
prometheus-adapter-66fc7797fd-lhd7s    1/1     Running            0          11m
prometheus-k8s-0                       2/3     CrashLoopBackOff   8          11m
prometheus-k8s-1                       2/3     CrashLoopBackOff   8          11m
prometheus-operator-6c88446b98-b4kz8   1/1     Running            0          11m
```
**Environment**
`Centos7 kernel 4.20.8-1.el7.elrepo.x86_64`

* Prometheus Operator version:
`v0.27.0-199-g633daa0f`
* Kubernetes version information:
`v1.13.3`
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 
`kubespray ansible playbook`
* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: v2.5.0
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
spec:
  baseImage: quay.io/prometheus/alertmanager
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 3
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-main
  version: v0.16.0
```

* Prometheus Operator Logs:
` kubctl logs prometheus-k8s-0  -n monitoring  -c prometheus-config-reloader`
```
ts=2019-02-16T12:43:05.664042359Z caller=main.go:68 msg="Starting prometheus-config-reloader version '0.28.0'."
level=info ts=2019-02-16T12:43:05.664248187Z caller=reloader.go:81 msg="started watching config file for changes" in=/etc/prometheus/config/prometheus.yaml.gz out=/etc/prometheus/config_out/prometheus.env.yaml
level=error ts=2019-02-16T12:43:05.777488513Z caller=runutil.go:49 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post http://localhost:9090/-/reload: dial tcp 127.0.0.1:9090: connect: connection refused"
level=info ts=2019-02-16T12:43:10.825724866Z caller=reloader.go:208 msg="Prometheus reload triggered" cfg_in=/etc/prometheus/config/prometheus.yaml.gz cfg_out=/etc/prometheus/config_out/prometheus.env.yaml rule_dirs=
```

`kubctl logs prometheus-k8s-1  -n monitoring  -c prometheus-config-reloader`
```
ts=2019-02-16T12:43:05.117039295Z caller=main.go:68 msg="Starting prometheus-config-reloader version '0.28.0'."
level=info ts=2019-02-16T12:43:05.214593111Z caller=reloader.go:81 msg="started watching config file for changes" in=/etc/prometheus/config/prometheus.yaml.gz out=/etc/prometheus/config_out/prometheus.env.yaml
level=error ts=2019-02-16T12:43:05.216990126Z caller=runutil.go:49 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post http://localhost:9090/-/reload: dial tcp 127.0.0.1:9090: connect: connection refused"
level=info ts=2019-02-16T12:43:10.374869669Z caller=reloader.go:208 msg="Prometheus reload triggered" cfg_in=/etc/prometheus/config/prometheus.yaml.gz cfg_out=/etc/prometheus/config_out/prometheus.env.yaml rule_dirs=
```

**Comment by brancz** [comment]
Is there anything special about your cluster? This is the first time we're seeing this and we continuously test the setup in our end to end tests, so my guess is that there is some particular setting of your cluster that is causing this.

**Comment by vsliouniaev** [comment]
@bsakweson Since the reloader is getting a connection refused, this suggests that the prometheus container isn't starting up. Would you mind posting the logs from that?

**Comment by scottslowe** [comment]
Seeing the same behaviors here on a test cluster. K8s 1.13.2, Docker CE 18.09.2, Ubuntu 18.04, cluster bootstrapped using `kubeadm` with AWS cloud provider integration. Exact same pods are in CrashLoopBackOff, and `kubectl logs` is showing the same error messages as @bsakweson.

**Comment by scottslowe** [comment]
Just tested it again with Docker CE 18.06, K8s 1.13.2, Ubuntu 18.04, on a `kubeadm`-bootstrapped cluster. Same behavior, same log messages from the `prometheus-config-reloader` container.

**Comment by peterska** [comment]
I have the same experience and have tracked down the issue to the memory resource limit values of 10Mi for the reload pods causing an error when configuring the cgroup limits. Changing the value to 50Mi allows the pods to come up. This is best described by the error message below:

`starting container process caused "process_linux.go:424: container init caused \"process_linux.go:390: setting cgroup config for procHooks process caused \\\"failed to write 10485760 to memory.limit_in_bytes: write /sys/fs/cgroup/memory/kubepods/burstable/poddfec0272-2c2c-11e9-a484-7085c232df3b/config-reloader/memory.limit_in_bytes: device or resource busy\\\"\"": unknown`

My theory is that a changed in the recent version of Docker has caused this issue to surface.

**Comment by bsakweson** [comment]
My apologies for the late response, I had some other challenges with my Storage backend. I decided to tear my it down and ran  my scripts to crank it up oncemore. That time every thing came up. If I run into it again, I will definitely revert back to this issue. For those who are seeing the same issue,  @peterska’s workaround maybe something to try out.

**Comment by vsliouniaev** [comment]
Could you try the 0.29 version of prometheus-operator?

**Comment by mkey-cdx** [comment]
I had the exact same issue in my side. This looks ok with v0.29.0 for both prometheus and alertmanager pods.

**Comment by bsakweson** [comment]
So, just tried that stable/prometheus operator helm by replacing this section in my `values.yaml` to look like: 

```
## Prometheus-operator image
  ##
  image:
    repository: quay.io/coreos/prometheus-operator
    tag: v0.29.0
    pullPolicy: IfNotPresent
```
But still got this:

```
NAME                                                     READY   STATUS             RESTARTS   AGE
alertmanager-metrics-prometheus-operato-alertmanager-0   1/2     CrashLoopBackOff   14         49m
cm-acme-http-solver-bmgrw                                1/1     Running            0          13m
metrics-grafana-fcdfd5d7b-4ml9b                          3/3     Running            0          10m
metrics-kube-state-metrics-55d4cc6b4d-b62rd              1/1     Running            0          10m
metrics-prometheus-node-exporter-485s8                   1/1     Running            0          10m
metrics-prometheus-node-exporter-4bvj6                   1/1     Running            0          10m
metrics-prometheus-node-exporter-f4lfc                   1/1     Running            0          10m
metrics-prometheus-node-exporter-krnp9                   1/1     Running            0          10m
metrics-prometheus-node-exporter-sndpr                   1/1     Running            0          10m
metrics-prometheus-node-exporter-sr57z                   1/1     Running            0          10m
metrics-prometheus-node-exporter-zt4rf                   1/1     Running            0          10m
metrics-prometheus-operato-operator-5bcd9b447b-2srdn     1/1     Running            0          10m
prometheus-metrics-prometheus-operato-prometheus-0       2/3     CrashLoopBackOff   6          10m
```
What am I missing?

**Comment by bsakweson** [comment]
Also updated the `configReloaderImage` also to v.0.29.0 to look like this:

```
image:
    repository: quay.io/coreos/prometheus-operator
    tag: v0.29.0
    pullPolicy: IfNotPresent

  ## Configmap-reload image to use for reloading configmaps
  ##
  configmapReloadImage:
    repository: quay.io/coreos/configmap-reload
    tag: v0.0.1

  ## Prometheus-config-reloader image to use for config and rule reloading
  ##
  prometheusConfigReloaderImage:
    repository: quay.io/coreos/prometheus-config-reloader
    tag: v0.29.0
```

Still no luck.

```
NAME                                                     READY   STATUS             RESTARTS   AGE
alertmanager-metrics-prometheus-operato-alertmanager-0   1/2     CrashLoopBackOff   6          6m25s
cm-acme-http-solver-bmgrw                                1/1     Running            0          33m
metrics-grafana-fcdfd5d7b-8mdjs                          3/3     Running            0          6m31s
metrics-kube-state-metrics-55d4cc6b4d-mwk97              1/1     Running            0          6m31s
metrics-prometheus-node-exporter-59n8z                   1/1     Running            0          6m31s
metrics-prometheus-node-exporter-5hgxd                   1/1     Running            0          6m31s
metrics-prometheus-node-exporter-79d4z                   1/1     Running            0          6m31s
metrics-prometheus-node-exporter-7k782                   1/1     Running            0          6m31s
metrics-prometheus-node-exporter-8jv7g                   1/1     Running            0          6m31s
metrics-prometheus-node-exporter-brn9w                   1/1     Running            0          6m31s
metrics-prometheus-node-exporter-n9bbp                   1/1     Running            0          6m31s
metrics-prometheus-operato-operator-695b6bd4f8-ff4pp     1/1     Running            0          6m31s
prometheus-metrics-prometheus-operato-prometheus-0       2/3     CrashLoopBackOff   6          6m18s

```
