### ISSUE TITLE
etcd no data porint

### ISSUE THREAD

**Issue by billy98** [coreos/prometheus-operator#2423]
**What did you do?**
Using helm, install stable/ Prometheus -operator

Here is the  configuration
```
nameOverride: "p"
fullnameOverride: ""
commonLabels: {}
defaultRules:
  create: true
  labels: {}
  annotations: {}
global:
  rbac:
    create: true
    pspEnabled: true
  imagePullSecrets: []
alertmanager:
  enabled: true
  serviceAccount:
    create: true
    name: ""
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
    maxUnavailable: ""
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
      - match:
          alertname: DeadMansSwitch
        receiver: 'null'
    receivers:
    - name: 'null'
  templateFiles: {}
  ingress:
    enabled: true
    annotations: 
      nginx.ingress.kubernetes.io/rewrite-target: /
      kubernetes.io/ingress.class: nginx
    labels: {}
    hosts: 
      - alert.cnlinux.club
    tls: []
  service:
    annotations: {}
    labels: {}
    clusterIP: ""
    nodePort: 30903
    externalIPs: []
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    type: ClusterIP
  serviceMonitor:
    selfMonitor: true
  alertmanagerSpec:
    podMetadata: {}
    image:
      repository: quay.io/prometheus/alertmanager
      tag: v0.15.3
    secrets: []
    configMaps: []
    logLevel: info
    replicas: 1
    retention: 120h
    storage: 
     volumeClaimTemplate:
       spec:
         storageClassName: gluster-heketi
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 30Gi
       selector: {}
    externalUrl:
    routePrefix: /
    paused: false
    nodeSelector: {}
    resources: {}
    podAntiAffinity: ""
    tolerations: []
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 2000
    listenLocal: false
    containers: []
    priorityClassName: ""
    additionalPeers: []
grafana:
  enabled: true
  defaultDashboardsEnabled: true
  adminPassword: admin
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
    labels: {}
    hosts: 
      - grafana.cnlinux.club
    tls: []
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
    datasources:
      enabled: true
      label: grafana_datasource
kubeApiServer:
  enabled: true
  tlsConfig:
    serverName: kubernetes
    insecureSkipVerify: false
  serviceMonitor:
    jobLabel: component
    selector:
      matchLabels:
        component: apiserver
        provider: kubernetes
kubelet:
  enabled: true
  namespace: kube-system
  serviceMonitor:
    https: true
kubeControllerManager:
  enabled: true
  endpoints: []
  service:
    port: 10252
    targetPort: 10252
    selector:
      k8s-app: kube-controller-manager
coreDns:
  enabled: true
  service:
    port: 9153
    targetPort: 9153
    selector:
      k8s-app: kube-dns
kubeDns:
  enabled: false
  service:
    selector:
      k8s-app: kube-dns
kubeEtcd:
  enabled: true
  endpoints: []
  service:
    port: 4001
    targetPort: 4001
    selector:
      k8s-app: etcd-server
  
  serviceMonitor:
    scheme: http
    insecureSkipVerify: false
    serverName: ""
    caFile: ""
    certFile: ""
    keyFile: ""
kubeScheduler:
  enabled: true
  endpoints: []
  service:
    port: 10251
    targetPort: 10251
    selector:
      k8s-app: kube-scheduler
kubeStateMetrics:
  enabled: true
kube-state-metrics:
  rbac:
    create: true
nodeExporter:
  enabled: true
  jobLabel: jobLabel
prometheus-node-exporter:
  podLabels:
    jobLabel: node-exporter
  extraArgs:
    - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)
    - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
prometheusOperator:
  enabled: true
  serviceAccount:
    create: true
    name: ""
  service:
    annotations: {}
    labels: {}
    clusterIP: ""
    nodePort: 38080
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    type: ClusterIP
    externalIPs: []
  createCustomResource: true
  crdApiGroup: monitoring.coreos.com
  cleanupCustomResource: false
  podLabels: {}
  kubeletService:
    enabled: true
    namespace: kube-system
  serviceMonitor:
    selfMonitor: true
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
  image:
    repository: quay.io/coreos/prometheus-operator
    tag: v0.26.0
    pullPolicy: IfNotPresent
  configmapReloadImage:
    repository: quay.io/coreos/configmap-reload
    tag: v0.0.1
  prometheusConfigReloaderImage:
    repository: quay.io/coreos/prometheus-config-reloader
    tag: v0.26.0
  hyperkubeImage:
    repository: k8s.gcr.io/hyperkube
    tag: v1.12.1
    pullPolicy: IfNotPresent
prometheus:
  enabled: true
  serviceAccount:
    create: true
    name: ""
  service:
    annotations: {}
    labels: {}
    clusterIP: ""
    externalIPs: []
    nodePort: 39090
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    type: ClusterIP
  rbac:
    roleNamespaces:
      - kube-system
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
    maxUnavailable: ""
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      kubernetes.io/ingress.class: nginx
    labels: {}
    hosts:
      - prom.cnlinux.club
    tls: []
  serviceMonitor:
    selfMonitor: true
  prometheusSpec:
    scrapeInterval: ""
    evaluationInterval: ""
    listenLocal: false
    image:
      repository: quay.io/prometheus/prometheus
      tag: v2.5.0
    tolerations: []
    alertingEndpoints: []
    externalLabels: {}
    externalUrl: ""
    nodeSelector: {}
    secrets: []
    configMaps: []
    ruleNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: true
    ruleSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: true
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    retention: 10d
    paused: false
    replicas: 1
    logLevel: info
    routePrefix: /
    podMetadata: {}
    podAntiAffinity: ""
    remoteRead: {}
    remoteWrite: {}
    resources: {}
    storageSpec: 
      volumeClaimTemplate:
        spec:
          storageClassName: gluster-heketi
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 30Gi
        selector: {}
    additionalScrapeConfigs: []
    additionalAlertManagerConfigs: []
    additionalAlertRelabelConfigs: []
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 2000
    priorityClassName: ""
    thanos: {}
    containers: []
    additionalScrapeConfigsExternal: false
  additionalServiceMonitors: []
```
**What did you expect to see?**
Hopefully grafana has the monitoring data for the etcd
**What did you see instead? Under which circumstances?**
At present, other monitoring data are normal, only the monitoring data of etcd is not
**Environment**

* Prometheus Operator version:

stable/ Prometheus-operator Version : V1.8.0
Prometheus Operator image ：quay.io/coreos/prometheus-operator:v0.26.0

* Kubernetes version information:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
```
helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

* Kubernetes cluster kind: 

Create a kubernetes cluster using kubeadm.
Etcd runs in pod mode.

![image](https://user-images.githubusercontent.com/13307862/53140324-4b52ea80-35c7-11e9-8e34-59144d13922d.png)

**Comment by billy98** [comment]
![image](https://user-images.githubusercontent.com/13307862/53151220-94b63080-35ed-11e9-980a-b9095346a914.png)
My certificate is ok. Why did it fail to verify

**Comment by billy98** [comment]
Modified configuration
```
kubeEtcd:
  enabled: true
  endpoints: []
  service:
    port: 2379
    targetPort: 2379
    selector:
      component: etcd
  serviceMonitor:
    scheme: https
    insecureSkipVerify: true
    serverName: p-kube-etcd
    caFile: /etc/kubernetes/pki/etcd/ca.crt 
    certFile: /etc/kubernetes/pki/etcd/healthcheck-client.crt
    keyFile: /etc/kubernetes/pki/etcd/healthcheck-client.key
```
