### ISSUE TITLE
Custom prometheusrule not working

### ISSUE THREAD

**Issue by zidex** [coreos/prometheus-operator#2428]
**What did you do?**
I try add custom prometheusrule to helm chart elasticsearch-exporter

after install this chart prometheusrule present in system:

```
kubectl get prometheusrule --all-namespaces
NAMESPACE    NAME                                                       AGE
monitoring   devel-elasticsearch-exporter                               51m
monitoring   prometheus-operator-alertmanager.rules                     15d
monitoring   prometheus-operator-etcd                                   15d
monitoring   prometheus-operator-general.rules                          15d
monitoring   prometheus-operator-k8s.rules                              15d
monitoring   prometheus-operator-kube-apiserver.rules                   15d
monitoring   prometheus-operator-kube-prometheus-node-alerting.rules    15d
monitoring   prometheus-operator-kube-prometheus-node-recording.rules   15d
monitoring   prometheus-operator-kube-scheduler.rules                   15d
monitoring   prometheus-operator-kubernetes-absent                      15d
monitoring   prometheus-operator-kubernetes-apps                        15d
monitoring   prometheus-operator-kubernetes-resources                   15d
monitoring   prometheus-operator-kubernetes-storage                     15d
monitoring   prometheus-operator-kubernetes-system                      15d
monitoring   prometheus-operator-node.rules                             15d
monitoring   prometheus-operator-prometheus-operator                    15d
monitoring   prometheus-operator-prometheus.rules                       15d
```

But in Web UI rules list present only default rules

* Prometheus Operator version:
 
        0.26.0

	installed from helm chart stable\prometheus-operator 2.1.5

* Kubernetes version information:

	Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:10:00Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	kops

* Manifests:

```
# Source: prometheusrule.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: devel-elasticsearch-exporter
  labels:
    chart: elasticsearch-exporter-1.1.1
    app: elasticsearch-exporter
    release: "devel-elasticsearch-exporter"
    heritage: "Tiller"
    role: aleret-rules
    
  namespace: monitoring
spec:
  groups:
  - name: elasticsearch
    rules:
    - record: elasticsearch_filesystem_data_used_percent
      expr: 100 * (elasticsearch_filesystem_data_size_bytes - elasticsearch_filesystem_data_free_bytes)
        / elasticsearch_filesystem_data_size_bytes
    - record: elasticsearch_filesystem_data_free_percent
      expr: 100 - elasticsearch_filesystem_data_used_percent
    - alert: ElasticsearchTooFewNodesRunning
      expr: elasticsearch_cluster_health_number_of_nodes < 3
      for: 5m
      labels:
        severity: critical
      annotations:
        description: There are only {{$value}} < 3 ElasticSearch nodes running
        summary: ElasticSearch running on less than 3 nodes
    - alert: ElasticsearchHeapTooHigh
      expr: elasticsearch_jvm_memory_used_bytes{area="heap"} / elasticsearch_jvm_memory_max_bytes{area="heap"}
        > 0.9
      for: 15m
      labels:
        severity: critical
      annotations:
        description: The heap usage is over 90% for 15m
        summary: ElasticSearch node {{$labels.node}} heap usage is high

```

```
defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: true
    general: true
    k8s: true
    kubeApiserver: true
    kubePrometheusNodeAlerting: true
    kubePrometheusNodeRecording: true
    kubeScheduler: true
    kubernetesAbsent: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    node: true
    prometheusOperator: true
    prometheus: true
  labels:
    role: alert-rules

prometheus:
  enabled: true
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    ruleNamespaceSelector: {}
    ruleSelector:
      matchLabels:
        role: alert-rules
```
