### ISSUE TITLE
runAsGroup securityContext not getting passed to prometheus pods

### ISSUE THREAD

**Issue by awwithro** [coreos/prometheus-operator#2439]
**What did you do?**
Created a prometheus object with a securityContext of 
```
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
```

**What did you expect to see?**
I expected the prometheus pod that was created to have a securityContext of
```
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
```

**What did you see instead? Under which circumstances?**
Instead, the `runAsGroup` was missing from the pod's securityContext
```
  securityContext:
    runAsUser: 1000
```

I saw the same behavior if I removed the securityContext entirely from the prometheus object.

I can work around the issue by adding supplementalGroups to the securityContext
```
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
    supplementalGroups:
      - 2000
```

**Environment**

* Prometheus Operator version:
  `Image:         quay.io/coreos/prometheus-operator:v0.29.0`
    `Image ID:      docker-pullable://quay.io/coreos/prometheus-operator@sha256:5abe9bdfd93ac22954e3281315637d9721d66539134e1c7ed4e97f13819e62f7`

* Kubernetes version information:

```
k version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:16Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	Cluster is built/managed via terraform + kubeadm

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: prom
  name: prom
  namespace: mynamespace
spec:
  replicas: 1
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
    supplementalGroups:
      - 2000
  serviceAccountName: prometheus
```

* Prometheus Operator Logs:

N/A

**Comment by brancz** [comment]
Do you actually have the `RunAsGroup` feature gate enabled? This is an alpha feature https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by awwithro** [comment]
That would explain it. Didn't realize that was gated. Thanks!

**Comment by brancz** [comment]
Please let us know what you find, so we know if we can close this or not :slightly_smiling_face: . Thanks!

**Comment by awwithro** [comment]
I don't have it enable, this can be closed

**Comment by qqbuby** [comment]
pls try to set pod's security context with runAsUser, runAsGroup and fsGroup with 65534.



```yaml
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
```

- - -

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-demo
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false
```

In the configuration file, the runAsUser field specifies that for any Containers in the Pod, all processes run with user ID 1000. The runAsGroup field specifies the primary group ID of 3000 for all processes within any containers of the Pod. If this field is omitted, the primary group ID of the containers will be root(0). Any files created will also be owned by user 1000 and group 3000 when runAsGroup is specified. Since fsGroup field is specified, all processes of the container are also part of the supplementary group ID 2000. The owner for volume `/data/demo` and any files created in that volume will be Group ID 2000.

ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
