### ISSUE TITLE
Thanos IAM configuration

### ISSUE THREAD

**Issue by r0fls** [coreos/prometheus-operator#2442]
Is it possible to use thanos with an iam role instead of aws credentials? I see the example here only references access/secret keys: https://github.com/coreos/prometheus-operator/blob/master/Documentation/thanos.md#configuring-thanos-object-storage

```
type: s3
config:
  bucket: thanos
  endpoint: ams3.digitaloceanspaces.com
  access_key: XXX
  secret_key: XXX
```
