### ISSUE TITLE
Prometheus rules not working anymore after moving from 0.25.0 to 0.29.0

### ISSUE THREAD

**Issue by pault84** [coreos/prometheus-operator#2443]
**What did you do?**
Moved from prometheus-operator 0.25.0 to 0.29.0 so i don't run into the memory issue created by the CVE vulnerability fix.

**What did you expect to see?**
I expected the Prometheus operator to come up and deploy my new Prometheus instances.

**What did you see instead? Under which circumstances?**
My Prometheus pods get deployed but error out. and the log has a couple of these:

`level=error ts=2019-02-28T20:23:46.322471904Z caller=manager.go:754 component="rule manager" msg="loading groups failed" err="group \"custom.rules\", rule 0, \"CustomUsageCritical\": msg=template: __alert_CustomUsageCritical:1: missing value for command"`

**Environment**

* Prometheus Operator version:

	0.29.0

* Kubernetes version information:

	1.11.3

* Kubernetes cluster kind: 

	kubeadm

* Manifests:

```
- alert: CustomUsageCritical
      annotations:
        description: Volume {{.volumeid}} on {{.host}} is over 80% used for
          more than 10 minutes.
        summary: Volume capacity is at {{}}% used.
      expr: 100 * (volume_usage_bytes / volume_capacity_bytes) > 80
      for: 5m
      labels:
        issue: Volume {{.volumeid}} usage on {{.host}} is high.
        severity: critical
```

* Prometheus Operator Logs:

Operator is running fine.
