### ISSUE TITLE
Helm Chart: NodeExporter Instance is IP address and not pod_node_name

### ISSUE THREAD

**Issue by mitchellmaler** [coreos/prometheus-operator#2467]
**What did you do?**
Installed latest Helm Chart with Grafana

**What did you expect to see?**
Expected to get metrics with the instance of pod_node_name for the exporter and not the IP address. IP address is not useful to us as all where all nodes are referenced by name.

**What did you see instead? Under which circumstances?**
Expected to see the instance value be the discovered pod node name since the node exporter runs on all nodes and discovery returns the __meta_kubernetes_pod_node_name for each found instance. You like to use that label as discovery time and relabel to the instance label.

**Comment by mitchellmaler** [comment]
Since the Helm Chart does not provide a template for adding relabelings to the different service monitors my workaround is to manually add it to the service monitor after it is installed.

```yaml
relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance
```
