### ISSUE TITLE
Prometheus failing to create persistent storage on AWS

### ISSUE THREAD

**Issue by igoratencompass** [coreos/prometheus-operator#2469]
**What did you do?**
Trying to create persistent storage for Prometheus DB in AWS as per the storage document https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/storage.md#storage-provisioning-on-aws

**What did you expect to see?**
Expected a new PV and PVC to get created and the `prometheus-k8s` StatefulSet get updated accordingly.

**What did you see instead? Under which circumstances?**
I saw the error from the Operator as shown below in the log section.

**Environment**

* Prometheus Operator version:

   prometheus-operator-v0.19.0

* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

   kops

* Manifests:

```
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  retention: 180d
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: gp2
        resources:
          requests:
            storage: 2000Gi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpressions:
    - key: k8s-app
      operator: Exists
  version: v2.2.1
```

* Prometheus Operator Logs:

```
E0308 03:23:36.413689       1 operator.go:597] Sync "monitoring/k8s" failed: updating statefulset failed: StatefulSet.apps "prometheus-k8s" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.
```
