### ISSUE TITLE
Validate endpoint port

### ISSUE THREAD

**Issue by gianrubio** [coreos/prometheus-operator#247]
**What did you do?**

Monitor object using ServiceMonitor, I created this file below

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-controller
  labels:
    class: intern
spec:
  selector:
    matchLabels:
      class: intern
  endpoints:
  - port: 80
```

**What did you expect to see?**

Monitor my service, but looks like the port should be string not number. 

**What did you see instead? Under which circumstances?**

```
E0329 10:01:20.883012       1 reflector.go:199] github.com/coreos/prometheus-operator/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1alpha1.ServiceMonitor: json: cannot unmarshal number into Go value of type string
```

**Environment**

operator v0.7.0

**How I fixed**

Changed port ```- port: 80```  ```- port: web```. 

**Suggestion**

 Validate yaml before creating service monitor.
