### ISSUE TITLE
installing operator in new cluster error

### ISSUE THREAD

**Issue by SofiaTa** [coreos/prometheus-operator#2484]
Im trying to  create Prometheus with operator in fresh new k8s cluster
I use the following files , 

im using operator - 0.29 
Prometheus - 2.7.1

1. First step I’m creating a namespace  monitoring 
2. apply this file , which works ok
```

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: prometheus-operator
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
    spec:
      priorityClassName: "operator-critical"
      tolerations:
      - key: "WorkGroup"
        operator: "Equal"
        value: "operator"
        effect: "NoSchedule"
      - key: "WorkGroup"
        operator: "Equal"
        value: "operator"
        effect: "NoExecute"
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --logtostderr=true
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.29.0
        image: quay.io/coreos/prometheus-operator:v0.29.0
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      nodeSelector:
      serviceAccountName: prometheus-operator
```

Now I want  to apply this file (CRD)
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
  labels: 
    prometheus: prometheus
spec:
  replica: 1
  priorityClassName: "operator-critical"
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      role: observeable
  tolerations:
  - key: "WorkGroup"
    operator: "Equal"
    value: "operator"
    effect: "NoSchedule"
  - key: "WorkGroup"
    operator: "Equal"
    value: "operator"
    effect: "NoExecute"
```

And Im getting error :

error: unable to recognize "1500-prometheus-crd.yaml": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1"

I found this https://github.com/coreos/prometheus-operator/issues/1866 , but I try to do it as mentioned, I.e. 
Wait a few second and deploy again but it doesn’t help. Any idea ? 

Also we tried to delete the ns and create it again with the configs and I got the same issue. please advice

**Comment by SofiaTa** [comment]
HI Again,

what I did is created those yaml `crd` before 
https://github.com/coreos/prometheus-operator/tree/master/example/prometheus-operator-crd
is it OK? 

and I was able to deploy it without error. but I see that the operator doesnt start pods 0/0 , any idea what it could be ?

![image](https://user-images.githubusercontent.com/34491236/54367178-9f0e9c00-467a-11e9-9a91-93947ddba6b6.png)

**Comment by SofiaTa** [comment]
wwhen I go to the event of the prom operator I see the following Error `creating: pods "prometheus-operator-6944778645-" is forbidden: no PriorityClass with name operator-critical was found replicaset-controller , any idea ?

**Comment by brancz** [comment]
`priorityClassName: "operator-critical"` is probably not a priority class that you have installed by default, and we don't define it, so I'm not sure where it's coming from. The race that you were seeing initially is that the Prometheus Operator will attempt to create the CRDs, but will only do so after a couple of seconds after startup, so if the speed matters for you, you should indeed create the CRDs from those files.

**Comment by SofiaTa** [comment]
@brancz  - thank you very much! today we have high load of the system and the operator is running just good, the problem is with Prometheus memory , we have 900 pods running in our cluster and we saw that prom memory is using `17.gb` out of `24 gb` and its **growing** consistently , any idea what it could be ? how to avoid it ? 
is there a way to optimize it ? 

of course I can remove the limt but I think that in will be get OOM soon. please advice . my configs are in the post

**Comment by metalmatze** [comment]
If you have 900 pods and then also run kube-state-metrics I'd say that the memory consumption is pretty much what we would expect.
Every 2 hours Prometheus writes a block of data to disk and you should then see a bunch of memory being freed. If that doesn't happen, then we should take another look.

**Comment by SofiaTa** [comment]
@metalmatze - the memory is always high, here is my `kube-state-metrics` config file, do you see any issue? should I share something else ? 

```

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: kube-state-metrics
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-state-metrics
    spec:
      priorityClassName: "operator-critical"
      serviceAccountName: kube-state-metrics
      tolerations:
      - key: "WorkGroup"
        operator: "Equal"
        value: "operator"
        effect: "NoSchedule"
      - key: "WorkGroup"
        operator: "Equal"
        value: "operator"
        effect: "NoExecute"
      nodeSelector:
        worker.aws.io/group: operator
      containers:
      - name: kube-state-metrics
        image: quay.io/coreos/kube-state-metrics:v1.5.0
        ports:
        - name: metrics
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
      - name: addon-resizer
        image: k8s.gcr.io/addon-resizer:1.8.3
        resources:
          limits:
            cpu: 8000m
            memory: 8000Mi
          requests:
            cpu: 4000m
            memory: 4000Mi
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        command:
          - /pod_nanny
          - --container=kube-state-metrics
          - --cpu=100m
          - --extra-cpu=3m
          - --memory=1500Mi
          - --extra-memory=100Mi
          - --threshold=10
          - --deployment=kube-state-metrics
```

**Comment by brancz** [comment]
Can you share your memory usage graph over an extended period of time (say 12 hours)? Because typically every 2 hours the memory usage drops because it starts a new storage block. Within the latest 2 hours, it is normal for the memory usage to grow.

**Comment by SofiaTa** [comment]
@brancz - sorry I deployed the Prometheus (trying to adjust the limits....) 1.5 hour ago and all the previous data was deleted.
I will provide the last 12 tomorrow. see below the from the last hour. (don't show the real picture) 
Meanwhile, is there a reference for configuration for high load system, some best practice ?   ( I dont want to remove the limits...)

![image](https://user-images.githubusercontent.com/34491236/54554980-6b0ae200-49be-11e9-91e8-28ee472349eb.png)
 I will provide soon the two hours graph to verify that the memory is dropped ...

Thanks!

**Comment by brancz** [comment]
Overall that seems normal. Let's see once you have the 12 hours graphs. At least for now if you don't want to entirely remove the limits, set it a lot higher, like 5Gi.

**Comment by SofiaTa** [comment]
@brancz - sorry I cannot provide this kind of data(last 12 hours) , for some reason I saw that Prometheus is restarting (not by user) and all the past data are not available ?  :( , is there a way to config Prometheus to keep the data even if its restarting ?  volume?

**Comment by metalmatze** [comment]
Do you have a PVC (Persistent Volume Claim) for your Prometheuses? If you don't, then the obvious answer is to add those volumes and on the next restart Prometheus will continue with the previously written data.

**Comment by SofiaTa** [comment]
@metalmatze - do you mean like this?

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
  labels: 
    prometheus: prometheus
spec:
  replicas: 1
  priorityClassName: "operator-critical"
  serviceAccountName: prometheus
  nodeSelector:
        work.aws.io/group: oper
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      role: observeable
  tolerations:
  - key: "WorkGroup"
    operator: "Equal"
    value: "operator"
    effect: "NoSchedule"
  - key: "WorkGroup"
    operator: "Equal"
    value: "operator"
    effect: "NoExecute"
  resources:
    limits:
      cpu: 16000m
      memory: 32000Mi
    requests:
      cpu: 2000m
      memory: 2000Mi
  volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/
        - name: prometheus-storage-volume
          mountPath: /prometheus/
  volumes:
  - name: prometheus-config-volume    

```
