### ISSUE TITLE
ServiceMonitor endpoints port and targetPort ambiguity

### ISSUE THREAD

**Issue by nrvnrvn** [coreos/prometheus-operator#2515]
**What did you do?**
We spent a huge amount of time trying to understand why we could not scrape a newly added service metrics until we discovered the following:
- You have a container (as a part of a Pod controlled by deployment/statefulset/etc.) and you don't specify a container port because `Exposing a port here gives the system additional information about the network connections a container uses, but is primarily informational` as stated in [the API docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#container-v1-core).
- You have got a service which covers the aforementioned container(s) and you haven't given a name to it because when you have a single port exposed you are allowed to omit the name.
- You assume that ServiceMonitor watches the Services(according to [this](https://github.com/coreos/prometheus-operator/blob/bd8293a9b448c3bd40d1627d7f43ee66d86ac94b/Documentation/user-guides/getting-started.md#related-resources), Endpoints to be precise). 
- [API docs](https://github.com/coreos/prometheus-operator/blob/bd8293a9b448c3bd40d1627d7f43ee66d86ac94b/Documentation/api.md#endpoint) state that:
  - port is a `Name of the service port this endpoint refers to. Mutually exclusive with targetPort.`
  - targetPort is a `Name or number of the target port of the endpoint. Mutually exclusive with port.`
- You create a ServiceMonitor in which you set the `targetPort` equal to the number of your `Service`'s `port`.
- You get no metrics...

**What did you expect to see?**
Metrics
**What did you see instead? Under which circumstances?**
Instead we discovered that ServiceMonitor's targetPort actually transforms to `__meta_kubernetes_pod_container_port_number` which means that Prometheus is told to scrape not the Endpoints resources but the Container resources. See https://github.com/coreos/prometheus-operator/blob/v0.28.0/pkg/prometheus/promcfg.go#L378-L399
This creates a lot of confusion...
**Environment**

* Prometheus Operator version:
v0.28.0@sha256:62c5fe0246d88746001f071bfc764d3480dc1fc6516af52bde9d2416778dc843

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.12", GitCommit:"06f08e60069231bd21bdf673cf0595aac80b99f6", GitTreeState:"clean", BuildDate:"2019-02-25T20:37:10Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 
GKE

* Manifests:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      # please replace this with something that actually serves some metrics in order to reproduce the issue
      - image: k8s.gcr.io/pause-amd64:3.1
        name: pause-amd64
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
  name: test
spec:
  ports:
  - port: 8000
  selector:
    app: test
---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: test
  name: test
subsets:
- addresses:
  - ip: 10.20.9.31
    nodeName: somenodename
    targetRef:
      kind: Pod
      name: test-555dbcb98f-7ds92
      namespace: test-prometheus
      resourceVersion: "81073517"
      uid: e6556903-5075-11e9-9584-4201c0a8000b
  ports:
  - port: 8000
    protocol: TCP
---
# ServiceMonitor lives in the same namespace as Prometheus and Prometheus Operator of course
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: test
  name: test
  namespace: monitoring
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    targetPort: 8000
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: test
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Proposal**

Documentation should be amended to clearly state how the []Endpoints' `port` and `targetPort` work.

Since transforming the `targetPort` to `__meta_kubernetes_pod_container_port_number`/`__meta_kubernetes_pod_container_port_name` has been there for a long while a lot of users rely on this and this should not be removed for backwards compatibility.

Instead `__meta_kubernetes_endpoint_port_number` should be taken into consideration as well.

**P.S.**
_While I was writing all the above_
I haven't yet dug deeply into Prometheus itself but at first glance it seems like this is an upstream issue since I don't see `__meta_kubernetes_endpoint_port_number ` [here](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#endpoints)

Two questions here then:
- should we raise the issue with Prometheus about the Endpoint port number and adding support for it?
- what were the initial considerations for using `__meta_kubernetes_endpoint_port*` instead of [`__meta_kubernetes_service_port_*`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#service)? I assume this was done because endpoints contain actual target information but I still ask this question because ServiceMonitor as we assumed should have grabbed Port number/name from Services.

**Comment by brancz** [comment]
You're absolutely right, the documentation is faulty here. The `targetPort` field doesn't refer to the `Service`s fields, it refers to the port name or port number defined on the underlying selected Pods. Clarifying this in the docs is step 1.

Step 2 as you also already mentioned, we should treat `port` as a IntOrStr just like `targetPort` and select either the port name or port number, in the same fashion. And in order to do that, Prometheus should expose the `__meta_kubernetes_endpoint_port_number` meta label.

> what were the initial considerations for using __meta_kubernetes_endpoint_port* instead of __meta_kubernetes_service_port_*? I assume this was done because endpoints contain actual target information but I still ask this question because ServiceMonitor as we assumed should have grabbed Port number/name from Services.

This is because the Endpoints object is what Prometheus actually uses for discovery purposes, and a `Service` is not necessarily always present. So going with the Endpoints object whenever possible is the safe bet.

**Comment by brancz** [comment]
Is there something left to be answered?

**Comment by nrvnrvn** [comment]
The issue is still unresolved if I am not mistaken

**Comment by brancz** [comment]
I believe the docs still need to be adapted here.

**Comment by jecnua** [comment]
Please remove the stale label again.

**Comment by brancz** [comment]
Contributions on improving the docs would be very welcome! :)

**Comment by vincent-pli** [comment]
@brancz @nrvnrvn 
If I don't specify a container port, then use `targetPort` in `serviceMonitor` and point to right port of container (not specify a container port but truly existed), could it work?

**Comment by brancz** [comment]
yes that should work, when you specify the actual port number

**Comment by vincent-pli** [comment]
@brancz 
Based on my case, it's not work until I specify `container port` in my pod, see the details here:
https://github.com/coreos/prometheus-operator/issues/3354

**Comment by galindro** [comment]
Guys, I'm getting an issue to scrape metrics via PodMonitor and I found this issue, so, I would like to know if it has something to do with it.

I'm defining a PodMonitor like this to scrape some openebs pods metrics:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: openebs-cstor-pool-metrics
  namespace: openebs
spec:
  selector:
    matchLabels:
      app: cstor-pool
  podMetricsEndpoints:
  - port: "9500"
    interval: 10s
```

The problem is that the generated prometheus.yaml has the bellow content. It isn't working properly. Prometheus isn't being able to scrape any metrics because it can't find any targets.

```yaml
- job_name: openebs/openebs-cstor-pool-metrics/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
      - openebs
  scrape_interval: 10s
  relabel_configs:
  - action: keep
    source_labels:
    - __meta_kubernetes_pod_label_app
    regex: cstor-pool
  - action: keep
    source_labels:
    - __meta_kubernetes_pod_container_port_name
    regex: "9500"
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - target_label: job
    replacement: openebs/openebs-cstor-pool-metrics
  - target_label: endpoint
    replacement: "9500"
```

But now, if I change the PodMonitor to the bellow one, it works:

```yaml

apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: openebs-cstor-pool-metrics
  namespace: openebs
spec:
  selector:
    matchLabels:
      app: cstor-pool
  podMetricsEndpoints:
  - targetPort: 9500
    interval: 10s
```

Note that I changed from port to targetPort (and I informed an integer in place of a string). This was the generated prometheus.yaml:

```yaml
- job_name: openebs/openebs-cstor-pool-metrics/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
      - openebs
  scrape_interval: 10s
  relabel_configs:
  - action: keep
    source_labels:
    - __meta_kubernetes_pod_label_app
    regex: cstor-pool
  - action: keep
    source_labels:
    - __meta_kubernetes_pod_container_port_number   # THIS IS DIFFERENT
    regex: "9500"
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - target_label: job
    replacement: openebs/openebs-cstor-pool-metrics
  - target_label: endpoint
    replacement: "9500"
```

The only difference between the two prometheus.yaml generated is the following: 

```bash
diff /tmp/prometheus.yaml /tmp/prometheus_2.yaml 
1056c1056
<     - __meta_kubernetes_pod_container_port_name
---
>     - __meta_kubernetes_pod_container_port_number
```

My concern about it is that targetPort was deprecated by https://github.com/prometheus-operator/prometheus-operator/pull/3078. But by using port in place of targetPort doesn't works probably because I'm not using a name for the port, because that openebs pods doesn't has a name for it.

**Comment by bricef** [comment]
@galindro I have the exact same issue. I can't seem to configure a way to reach an _unnamed_ port from a PodMonitor. That seems like a massive oversight. I'm not always in control of the naming of ports on pods. I should be able to configure scraping at an arbitrary numerical port.

**Comment by galindro** [comment]
Well, your case is even worse... I have no clues how to help you to workaround it. Sorry

**Comment by funkypenguin** [comment]
My workaround in this case has been to use the (deprecated) `targetPort` field, to point to the arbitrary numerical port on the pod.

Note that this works:

```
  podMetricsEndpoints:
  - targetPort: 8080
```

While this doesn't:

```
  podMetricsEndpoints:
  - targetPort: "8080"
```

.. presumably because by encapsulating the port number in quotes, you're instructing Prometheus to look for a container port **named** "8080".

**Comment by funkypenguin** [comment]
Also worth noting that the above workaround doesn`t work when using `port: 8080`, but errors with:

```
 * spec.podMetricsEndpoints.port: Invalid value: "integer": spec.podMetricsEndpoints.port in body must be of type string: "integer
 *
```

**Comment by weibeld** [comment]
For the situation that the Pod does not declare _any_ ports (as mentioned by @bricef), a workaround can be implemented as follows:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: rook-ceph-operator
spec:
  selector:
    matchLabels:
      app: rook-ceph-operator
  namespaceSelector:
    matchNames: 
      - rook-ceph
  podMetricsEndpoints:
    - relabelings:
      - action: replace
        targetLabel: __address__
        sourceLabels:
          - __address__
        replacement: $1:8080
```

That means, you don't try to define the port to scrape with `port` or `targetPort` at all, but manually redefine the `__address__` label to include the desired target port.
