### ISSUE TITLE
prometheus-k8s statefulsets' rules have invalid syntax

### ISSUE THREAD

**Issue by coryodaniel** [coreos/prometheus-operator#2516]
**What did you do?**
Applied kube-prometheus manifests from master

**What did you expect to see?**
All the things.

**What did you see instead? Under which circumstances?**
statefulset/prometheus-k8s' pods were stuck in a crash loop

**Environment**
GKE 1.12

* Prometheus Operator version:

* quay.io/coreos/prometheus-operator:v0.29.0
* quay.io/prometheus/prometheus:v2.5.0

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:36:43Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.5-gke.5", GitCommit:"2c44750044d8aeeb6b51386ddb9c274ff0beb50b", GitTreeState:"clean", BuildDate:"2019-02-01T23:53:25Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

GKE

* Prometheus Operator Logs:

```
 level=info ts=2019-03-27T16:55:33.915207685Z caller=notifier.go:512 component=notifier msg="Stopping notification manager..."
 E 
 level=info ts=2019-03-27T16:55:33.915274506Z caller=main.go:616 msg="Notifier manager stopped"
 E 
 level=error ts=2019-03-27T16:55:33.915496831Z caller=main.go:625 err="error loading config from \"/etc/prometheus/config_out/prometheus.env.yaml\": one or more errors occurred while applying the new configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\")"
```

* Running `promtool check`

It appears that invalid rules are being created.

```shell
Checking /etc/prometheus/rules/prometheus-k8s-rulefiles-0/monitoring-prometheus-k8s-rules.yaml
  FAILED:
group "kubernetes-apps", rule 7, "KubeDaemonSetRolloutStuck": msg=template: __alert_KubeDaemonSetRolloutStuck:1: missing value for command
group "kubernetes-apps", rule 8, "KubeDaemonSetNotScheduled": msg=template: __alert_KubeDaemonSetNotScheduled:1: missing value for command
group "kubernetes-apps", rule 9, "KubeDaemonSetMisScheduled": msg=template: __alert_KubeDaemonSetMisScheduled:1: missing value for command
group "kubernetes-system", rule 1, "KubeVersionMismatch": msg=template: __alert_KubeVersionMismatch:1: missing value for command
group "kubernetes-system", rule 4, "KubeletTooManyPods": msg=template: __alert_KubeletTooManyPods:1: missing value for command
group "kubernetes-system", rule 5, "KubeAPILatencyHigh": msg=template: __alert_KubeAPILatencyHigh:1: missing value for command
group "kubernetes-system", rule 6, "KubeAPILatencyHigh": msg=template: __alert_KubeAPILatencyHigh:1: missing value for command
group "kubernetes-system", rule 7, "KubeAPIErrorsHigh": msg=template: __alert_KubeAPIErrorsHigh:1: missing value for command
group "kubernetes-system", rule 8, "KubeAPIErrorsHigh": msg=template: __alert_KubeAPIErrorsHigh:1: missing value for command
group "kubernetes-system", rule 9, "KubeAPIErrorsHigh": msg=template: __alert_KubeAPIErrorsHigh:1: missing value for command
group "kubernetes-system", rule 10, "KubeAPIErrorsHigh": msg=template: __alert_KubeAPIErrorsHigh:1: missing value for command
group "general.rules", rule 0, "TargetDown": msg=template: __alert_TargetDown:1: missing value for command
group "prometheus.rules", rule 5, "PrometheusTSDBReloadsFailing": msg=template: __alert_PrometheusTSDBReloadsFailing:1: unexpected "|" in command
group "prometheus.rules", rule 6, "PrometheusTSDBCompactionsFailing": msg=template: __alert_PrometheusTSDBCompactionsFailing:1: unexpected "|" in command
```

When inspecting the rules, values are missing. 

Note: `{{ }}` in `annotations.message`:

```yaml
  - alert: KubeDaemonSetRolloutStuck
    annotations:
      message: Only {{  }}% of the desired Pods of DaemonSet {{ .namespace }}/{{ .daemonset
        }} are scheduled and ready.
      runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubedaemonsetrolloutstuck
    expr: |
      kube_daemonset_status_number_ready{job="kube-state-metrics"}
        /
      kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics"} * 100 < 100
    for: 15m
    labels:
      severity: critical
```
