### ISSUE TITLE
Prometehus configure db

### ISSUE THREAD

**Issue by SofiaTa** [coreos/prometheus-operator#2521]
Hi,

Since my Prometheus is restarting over and over again (still investigating ...) in the last few days we want to bound to volume that even if the pods will be restarted the data will be kept.
we are using the operator with version `0.29`
and we do this according to the docs we need to provide `pv` and in the config of Prometheus 
to define the following configs which claims the volume, currently its not working , the data is not kept in `db`.
please see my config files, did I miss something ? 

https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/storage.md

```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: prometheus-operator
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --logtostderr=true
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.29.0
        image: quay.io/coreos/prometheus-operator:v0.29.0
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http

This is the config of the Prometheus

    apiVersion: monitoring.coreos.com/v1
    kind: Prometheus
    metadata:
      name: prometheus
      namespace: monitoring
      labels: 
        prometheus: prometheus
    spec:
      replica: 2
      serviceAccountName: prometheus
      serviceMonitorNamespaceSelector: {}
      serviceMonitorSelector:
        matchLabels:
          role: observeable
      tolerations:
      - key: "WorkGroup"
        operator: "Equal"
        value: "operator"
        effect: "NoSchedule"
      - key: "WorkGroup"
        operator: "Equal"
        value: "operator"
        effect: "NoExecute"
      resources:
        limits:
          cpu: 8000m
          memory: 24000Mi
        requests:
          cpu: 6000m
          memory: 6000Mi
     storage:
       volumeClaimTemplate:
         spec:
        selector:
          matchLabels:
            app: prometheus
        resources:
          requests:
            storage: 100Gi


````
this is the `pv`
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
    prometheus: prometheus
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce # required
  nfs:
    server: myServer
    path: "/path/to/prom/db"
```

**Im not sure what to put in the following lines**
1.  what is my server? how should I create this server ?
2. what is path, just to provide some any path and reuse it when the pods is down 

```
  nfs:
    server: myServer
    path: "/path/to/prom/db"

```

please advice .
