### ISSUE TITLE
storageSpec.VolumeClaim is not respected

### ISSUE THREAD

**Issue by auhlig** [coreos/prometheus-operator#2535]
**What happened?**
Configured a Prometheus with
```
storage:
  volumeClaimTemplate:
    metadata:
      name: "k8s-prometheus"
    spec:
      accessModes:
        - "ReadWriteMany"
      resources:
        requests:
          storage: "100Gi"
```

However, the operator ignores the VolumeClaimTemplate and creates the PVC with `spec.accessModes: ["ReadWriteOnce"]`.

Cause: The access mode is hardcoded [here](https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/statefulset.go#L213).

**Did you expect to see some different?**

Operator creates PVC according to pvc template.

**Environment**

* Prometheus Operator version:

    `v0.29.0`
