### ISSUE TITLE
Prometheus Secret Config Empty

### ISSUE THREAD

**Issue by Tzrlk** [coreos/prometheus-operator#2547]
**What did you do?**
I standardised the metadata labels for all my deployment entities when converting from loose manifests to local helm charts. After that, the prometheus config secret always has no data in it.

**Did you expect to see some different?**
I expected the configuration secret to contain data as it did on the default deployment.

**Environment**

* Prometheus Operator version:

    `v0.29.0`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCom
mit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:
"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"windows/a
md64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c3
4c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean"
, BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platfor
m:"linux/amd64"}
```

* Kubernetes cluster kind:

    Amazon EKS via CloudFormation

* Manifests:

```yaml
---
# Source: monitoring/charts/prometheus-operator/templates/deployment.yml
apiVersion: apps/v1
kind:       Deployment

metadata:
  namespace: monitoring
  name:      prometheus-operator

  labels:
    app.kubernetes.io/name:       prometheus-operator
    app.kubernetes.io/instance:   monitoring
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/version:    v0.29.0
    helm.sh/chart:                prometheus-operator-0.1.0

spec:
  replicas:             1
  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app.kubernetes.io/name:       prometheus-operator
      app.kubernetes.io/instance:   monitoring

  template:

    metadata:
      labels:
        app.kubernetes.io/name:       prometheus-operator
        app.kubernetes.io/instance:   monitoring
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/version:    v0.29.0
        helm.sh/chart:                prometheus-operator-0.1.0

    spec:
      serviceAccountName: prometheus-operator
      securityContext:
        runAsNonRoot: true
        runAsUser:    65534
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:

        - name:  prometheus-operator
          image: quay.io/coreos/prometheus-operator:v0.29.0
          args:
            - --kubelet-service=kube-system/kubelet
            - --logtostderr=true
            - --log-level=debug
            - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
            - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.29.0
          ports:
            - { name: http, containerPort: 8080 }
          resources:
            requests: { cpu: 100m, memory: 100Mi }
            limits:   { cpu: 200m, memory: 200Mi }
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem:   true
```
```yaml
---
# Source: monitoring/charts/prometheus-operator/templates/cluster-role.yml
apiVersion: rbac.authorization.k8s.io/v1
kind:       ClusterRole

metadata:
  name: monitoring::prometheus-operator

  labels:
    app.kubernetes.io/name:       prometheus-operator
    app.kubernetes.io/instance:   monitoring
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/version:    v0.29.0
    helm.sh/chart:                prometheus-operator-0.1.0

rules:

  - apiGroups: [ apiextensions.k8s.io ]
    verbs:     [ '*' ]
    resources:
      - customresourcedefinitions

  - apiGroups: [ monitoring.coreos.com ]
    verbs:     [ '*' ]
    resources:
      - alertmanagers
      - prometheuses
      - prometheuses/finalizers
      - alertmanagers/finalizers
      - servicemonitors
      - prometheusrules

  - apiGroups: [ apps ]
    verbs:     [ '*' ]
    resources:
      - statefulsets

  - apiGroups: [ '' ]
    verbs:     [ '*' ]
    resources:
      - configmaps
      - secrets

  - apiGroups: [ '' ]
    verbs:     [ list, delete ]
    resources:
      - pods

  - apiGroups: [ '' ]
    verbs:     [ get, create, update, delete ]
    resources:
      - services
      - services/finalizers
      - endpoints

  - apiGroups: [ '' ]
    verbs:     [ list, watch ]
    resources:
      - nodes

  - apiGroups: [ '' ]
    verbs:     [ get, list, watch ]
    resources:
      - namespaces
```
```yaml
---
# Source: monitoring/charts/prometheus/templates/prometheus.yml
apiVersion: monitoring.coreos.com/v1
kind:       Prometheus

metadata:
  namespace: monitoring
  name:      prometheus

  labels:
    app.kubernetes.io/name:       prometheus
    app.kubernetes.io/instance:   monitoring
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/version:    v2.8.0
    helm.sh/chart:                prometheus-0.1.0

spec:

  baseImage: quay.io/prometheus/prometheus
  version:   v2.8.0

  podMetadata:
    labels:
      app.kubernetes.io/name:       prometheus
      app.kubernetes.io/instance:   monitoring
      app.kubernetes.io/managed-by: prometheus-operator
      app.kubernetes.io/version:    v2.8.0

  serviceAccountName: prometheus
  securityContext:
    fsGroup:      2000
    runAsNonRoot: true
    runAsUser:    1000
  resources:
    requests: { memory: 400Mi }

  replicas: 2
  nodeSelector:
    beta.kubernetes.io/os: linux

  alerting:
    alertmanagers:
      - name:      alertmanager
        namespace: monitoring
        port:      web

  ruleSelector:
    matchLabels:
      app.kubernetes.io/name:       prometheus
      app.kubernetes.io/instance:   monitoring
```
```yaml
---
# Source: kubectl -n monitoring get secret prometheus-prometheus -o yaml
apiVersion: v1
data:
  prometheus.yaml.gz: ""
kind: Secret
metadata:
  annotations:
    empty: "true"
  creationTimestamp: 2019-04-10T00:41:50Z
  labels:
    managed-by: prometheus-operator
  name: prometheus-prometheus
  namespace: monitoring
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Prometheus
    name: prometheus
    uid: 06314314-5b16-11e9-8595-0215d269c2a8
  resourceVersion: "7770783"
  selfLink: /api/v1/namespaces/monitoring/secrets/prometheus-prometheus
  uid: 6e01243a-5b29-11e9-a5dd-1272726ae138
type: Opaque
```

* Prometheus Operator Logs:

```
level=debug ts=2019-04-10T00:41:50.863670406Z caller=operator.go:682 component=prometheusoperator msg="Secret deleted"
level=debug ts=2019-04-10T00:41:50.881489797Z caller=rules.go:69 component=prometheusoperator msg="no PrometheusRule changes" namespace=monitoring prometheus=prometheus
level=debug ts=2019-04-10T00:41:50.894191929Z caller=operator.go:706 component=prometheusoperator msg="Secret added"
level=debug ts=2019-04-10T00:41:50.903930996Z caller=operator.go:1036 component=prometheusoperator msg="new statefulset generation inputs match current, skipping any actions"
level=info ts=2019-04-10T00:41:50.903964156Z caller=operator.go:970 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=debug ts=2019-04-10T00:41:50.903976561Z caller=rules.go:152 component=prometheusoperator msg="selected RuleNamespaces" namespaces=monitoring namespace=monitoring prometheus=prometheus
level=debug ts=2019-04-10T00:41:50.909271899Z caller=rules.go:194 component=prometheusoperator msg="selected Rules" rules=monitoring-prometheus.yaml namespace=monitoring prometheus=prometheus
level=debug ts=2019-04-10T00:41:50.927313855Z caller=rules.go:69 component=prometheusoperator msg="no PrometheusRule changes" namespace=monitoring prometheus=prometheus
level=debug ts=2019-04-10T00:41:50.942350918Z caller=operator.go:1036 component=prometheusoperator msg="new statefulset generation inputs match current, skipping any actions"
```

**Anything else we need to know?**:
Omitting `ruleSelector` on the `Prometheus` config caused the rules to go missing, rather than accept any rule. Expected the same behaviour as service monitor selection.
