### ISSUE TITLE
creating service monitor can only scrape service in monitoring namespace?

### ISSUE THREAD

**Issue by sloppycoder** [coreos/prometheus-operator#2557]
I created a [test project on github](https://github.com/sloppycoder/profile-svc/blob/master/k8s/gke/README.md) here.

When I create deployment and service in the monitoring namespace, then created the service monitor as following

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: profile-svc
  labels:
    app: profile-svc
    k8s-app: profile-svc
spec:
  selector:
    matchLabels:
      app: profile-svc
  endpoints:
    - port: web
      scheme: http
      path: '/actuator/prometheus'
      interval: 15s
      honorLabels: true

```

Operator picked up the service monitor and I saw the following configuration in Prometheus dashboard. 

```

- job_name: monitoring/profile-svc/0
  honor_labels: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /actuator/prometheus
  scheme: http
  kubernetes_sd_configs:
  - api_server: null
    role: endpoints
    namespaces:
      names:
      - monitoring
  relabel_configs:
    - blah
    - blah

```

Everything seems to be fine, Prometheus scrapes my metrics endpoints and I can then see the data in the dashboard. So it appears that my deployment and service configuration are wired up correctly.

However, if I create deployment and service in my own project namespace, and then create the same service monitor, my pod does not receive any scraping requests. I checked the configuration, it's the same as before:

```

- job_name: monitoring/profile-svc/0
  honor_labels: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /actuator/prometheus
  scheme: http
  kubernetes_sd_configs:
  - api_server: null
    role: endpoints
    namespaces:
      names:
      - monitoring  <- is this correct? shouldn't this be my project namespace?
  relabel_configs:
    - blah
    - blah
    
```

Is the above configuration correct? Is this a bug in the Operator?

Also, I found that if I create the service monitor in my own project namespace, Operator does not detect it and no changes are made to Prometheus configuration. Is this the intended behavior?
