### ISSUE TITLE
Does Grafana has persistent storage?

### ISSUE THREAD

**Issue by jehos** [coreos/prometheus-operator#2558]
**What did you do?**

`helm install prometheus-operator -f my-override-value.yaml`

working well, but when i delete the pod of grafana, everything on grafana resetted

**Did you expect to see some different?**

actually, i cannot find persistence storage setting on grafana section..

as i know, grafana has sqlite3 database.

can prometheus-operator using this by edit value.yaml?

Or, is grafana not recommended to use persistence storage?

How do you usually use grafana in this situation?

**Environment**

* Prometheus Operator version:

prometheus-operator-5.0.11, 0.29.0

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`

```
jehos@node1:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

`kubeadm`

* Manifests:

```
grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
    hosts:
      - grafana.k8s.*****.com
    path: /
    tls:
      - secretName: grafana-general-tls
        hosts:
        - grafana.k8s.*****com
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by brancz** [comment]
> prometheus-operator-5.0.11

We don't use or maintain the helm charts, please open an issue on the upstream helm repo.

Generally speaking though we deploy Grafana in a 100% stateless way, and only provision the dashboards at startup from files. After that it's entirely read-only. This is intentional.

**Comment by llech** [comment]
> > prometheus-operator-5.0.11
> 
> We don't use or maintain the helm charts, please open an issue on the upstream helm repo.
> 
> Generally speaking though we deploy Grafana in a 100% stateless way, and only provision the dashboards at startup from files. After that it's entirely read-only. This is intentional.

Hello,
I have a bit problems understanding what do you mean. Could you explain it a bit what do you mean by 100% stateless?
You can edit dashboards in grafana web interface. How stateless is that? I've noticed, that all my changes have disappeared after Grafana restart, although the grafana.db is placed on the persistent volume.
Does 100% stateless mean that all changes you make, including data source configuration, will survive only until next restart? What is the purpose of having save option then? It's quite misleading. Or I've understand something wrong?

**Comment by metalmatze** [comment]
> Does 100% stateless mean that all changes you make, including data source configuration, will survive only until next restart? 
Yes, that's exactly what it means.

**Comment by metalmatze** [comment]
It is totally legitimate to run another Grafana and point it against your Prometheus and not using the one we ship. Or use both, one for cluster monitoring and one for your own needs. :man_shrugging:

**Comment by aashishkoirala** [comment]
@llech This is a parent Helm chart with Grafana as own of its subcharts - you can define values for that subchart to do this in the parent values.yaml, e.g. the following should reuse the PVC used for Prometheus persistence if that is enabled (assuming name of Helm release is `prometheus-operator`):

```yaml
grafana:
  persistence:
    enabled: true
    storageClassName: prometheus
    existingClaim: prometheus-prometheus-operator-prometheus-db-prometheus-prometheus-operator-prometheus-0
```

**Comment by laoshufeifei** [comment]
prometheus-pv.yaml:
grafana:
  ...
  persistence:
    enabled: true
    storageClassName: grafana-rwo
    size: 10Gi
    accessModes:
      - ReadWriteOnce

**Comment by laoshufeifei** [comment]
first create your pv for grafana, such as name is grafana-rwo,
than  modify prometheus-operator.yaml like this:
```
grafana:
  ...
  persistence:
    enabled: true
    storageClassName: grafana-rwo
    size: 10Gi
    accessModes:
      - ReadWriteOnce
```

**Comment by dobber** [comment]
Thanks @laoshufeifei 
In order to create the resource, you need something like this (change the provisioned to whatever you use:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: grafana-rwo
  namespace: monitoring
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: pd-standard
volumeBindingMode: WaitForFirstConsumer
```

Then you can add the grafana.persistence: settings in the above comment.

**Comment by dobber** [comment]
I would suggest putting this in the documentation.

**Comment by bibincatchme** [comment]
Hello,

For grafan persistent storage on prometheus-operator, I've tried the above code in values.yml file but the volume gets deleting when I uninstalling the prometheus-operator helm chart.

```
grafana:
  persistence:
    enabled: true
    storageClassName: ssd-promethus
    size: 10Gi
    accessModes:
      - ReadWriteOnce
```

Storageclass.yml
```
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: ssd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
```

Why it happened, ?
