### ISSUE TITLE
Error while adding jsonpath as parameter in scrape_configs:

### ISSUE THREAD

**Issue by manuprometheus** [coreos/prometheus-operator#2559]
**What did you do?**
I have configured a json exporter that will collect the metrics from a Json URL. I have passed the target and the json as a parameter using relabelling. But getting error.
**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```
level=error ts=2019-04-16T06:05:24.395218368Z caller=main.go:597 err="Error loading config couldn't load configuration (--config.file=/etc/prometheus/config_out/prometheus.env.yaml): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: yaml: unmarshal errors:\n  line 3871: cannot unmarshal !!str `value` into model.LabelNames"
**Anything else we need to know?**:

**Comment by manuprometheus** [comment]
My additional-scrape-configs.yaml is as follows:

```
- job_name: 'json'
  metrics_path: /probe
  params:
    jsonpath: [$.details.db.details.hello] # Look for the nanoseconds field
  static_configs:
    - targets:
      - https://URL path
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: jsonexporter:9116  # Json exporter.
  metric_relabel_configs:
    - source_labels: value
      target_label:  hello
```

**Comment by manuprometheus** [comment]
I have fixed the issue. Modified the configuration as follows;

```
- job_name: 'json'
  metrics_path: /probe
  params:
    jsonpath: [$.details.db.details.hello] # 
  static_configs:
    - targets:
      - https://URL path
  relabel_configs:
        - source_labels: [__address__]     # set param 'target' to the original target
          target_label: __param_target
          replacement: ${1}
        - source_labels: [__param_target]  # set label 'instance' to it as well
          target_label: instance
          replacement: ${1}
        - target_label: __address__
          replacement: jsonexporter:9116
```
