### ISSUE TITLE
Need to add custom webhook configuration in alertmanager

### ISSUE THREAD

**Issue by manuprometheus** [coreos/prometheus-operator#2564]
**What did you do?**
I have a custom webhook URL and I need to configure the same in alertmanager for getting alert notification. But my configuration is not working as expected. Can anyone help?
**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by manuprometheus** [comment]
My configuration is as follows,

```
global:


  resolve_timeout: 1m
route:
  receiver: custom
  group_by:
  - alertname
  routes:
  - receiver:   custom
    continue: true
  group_wait: 1m
  group_interval: 5m
  repeat_interval: 1h
receivers:
- name: custom
  webhook_configs:
  - send_resolved: true
    url: 'webhook url'
```
