### ISSUE TITLE
node-exporter prevents docker from removing monitored containers

### ISSUE THREAD

**Issue by leo1515416043** [coreos/prometheus-operator#2578]
**What happened?**
```pod terminating -> device or resource busy```
> Apr 30 09:15:10 kubelet[24584]: E0430 09:15:10.712138   24584 remote_runtime.go:246] RemoveContainer "cf6e4c381a150eb2ba5bae4bf05ceb1b04a1a23b604ea67fdcbe38a9fb6b0c41" from runtime service failed: rpc error: code = Unknown desc = failed to remove container "cf6e4c381a150eb2ba5bae4bf05ceb1b04a1a23b604ea67fdcbe38a9fb6b0c41": Error response from daemon: driver "overlay" failed to remove root filesystem for cf6e4c381a150eb2ba5bae4bf05ceb1b04a1a23b604ea67fdcbe38a9fb6b0c41: remove /home/data/docker/overlay/b2b961718b2346141227b39cdc09f0872a2bbe3a5673b3e974c315730198b475/merged: device or resource busy

```
grep -nr b2b9617 /proc/*/mountinfo
```
> /proc/118860/mountinfo:259:3661 3385 0:942 / /host/root/home/data/docker/overlay/b2b961718b2346141227b39cdc09f0872a2bbe3a5673b3e974c315730198b475/merged rw,relatime - overlay overlay rw,lowerdir=/home/data/docker/overlay/4ea881aaa75dae2919ea2800aedae372e2b10aeddff96feaa4c0bf97e6f365af/root,upperdir=/home/data/docker/overlay/b2b961718b2346141227b39cdc09f0872a2bbe3a5673b3e974c315730198b475/upper,workdir=/home/data/docker/overlay/b2b961718b2346141227b39cdc09f0872a2bbe3a5673b3e974c315730198b475/work

```ps -ef |grep 118860```
> root     118860 118834  0 Apr29 ?        00:07:35 /bin/node_exporter --web.listen-address=127.0.0.1:9100 --path.procfs=/host/proc --path.sysfs=/host/sys --path.rootfs=/host/root --collector.filesystem.ignored-mount-points=^(/host/root)/(dev|proc|sys|var|home)($|/) --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$

**Did you expect to see some different?**
other containers can be removed normally
**How to reproduce it (as minimally and precisely as possible)**:
apply this [official manifest](https://github.com/coreos/kube-prometheus/blob/master/manifests/node-exporter-daemonset.yaml)
**Environment**
* kernel 
3.10.0
* Prometheus Operator version:
quay.io/coreos/prometheus-operator:v0.29.0
* Kubernetes version information:
1.9.4
* Kubernetes cluster kind:
kubeadm
* Manifests:

```
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  labels:
    app: node-exporter
  name: node-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
      - args:
        - --web.listen-address=127.0.0.1:9100
        - --path.procfs=/host/proc
        - --path.sysfs=/host/sys
        - --path.rootfs=/host/root
        - --collector.filesystem.ignored-mount-points=^(/host/root)/(dev|proc|sys|var|home)($|/)
        - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
        image: quay.io/prometheus/node-exporter:v0.17.0
        name: node-exporter
        resources:
          limits:
            memory: 180Mi
          requests:
            cpu: 102m
            memory: 180Mi
        volumeMounts:
        - mountPath: /host/proc
          name: proc
          readOnly: false
        - mountPath: /host/sys
          name: sys
          readOnly: false
        - mountPath: /host/root
          mountPropagation: HostToContainer
          name: root
          readOnly: true
      - args:
        - --logtostderr
        - --secure-listen-address=$(IP):9100
        - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
        - --upstream=http://127.0.0.1:9100/
        env:
        - name: IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: quay.io/coreos/kube-rbac-proxy:v0.4.1
        name: kube-rbac-proxy
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: https
        resources:
          limits:
            memory: 40Mi
          requests:
            cpu: 10m
            memory: 20Mi
      hostNetwork: true
      hostPID: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        runAsUser: 0
      serviceAccountName: node-exporter
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /proc
        name: proc
      - hostPath:
          path: /sys
        name: sys
      - hostPath:
          path: /
        name: root
```

* Prometheus Operator Logs:
no relevant log
