### ISSUE TITLE
nil values for serviceMonitorSelector in Prometheus spec prevents configuration generation

### ISSUE THREAD

**Issue by taharah** [coreos/prometheus-operator#2583]
**What happened?**

When generating a manifest for a Prometheus CRD with jsonnet I ran the function `std.prune(...)` to remove null values, empty lists, etc. However, this resulted in Prometheus failing to start since `serviceMonitorSelector` was an empty list and thus removed. The Prometheus configuration was not being generated, which was the root cause for the service failures.

As evident in the code: [pkg/prometheus/operator.go#L992-L999](https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/operator.go#L992-L999)

**Did you expect to see some different?**

I expect the Prometheus configuration to still be generated when `serviceMonitorSelector` is null.

**How to reproduce it (as minimally and precisely as possible)**:

Generate a Prometheus spec with a null value (as shown below) and the associated Secret will have an empty configuration.

**Environment**

* Prometheus Operator version:

v0.29.0

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

EKS

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: monitoring
  name: prometheus
  namespace: monitoring
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
              app.kubernetes.io/part-of: monitoring
          topologyKey: failure-domain.beta.kubernetes.io/zone
  alerting:
    alertmanagers:
      - name: alertmanager
        namespace: monitoring
        pathPrefix: /
        port: web
  externalLabels:
    namespace: monitoring
  image: quay.io/prometheus/prometheus:v2.9.2
  listenLocal: false
  logFormat: json
  logLevel: info
  paused: false
  podMetadata: {}
  replicas: 2
  resources:
    limits:
      cpu: 200m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 1Gi
  retention: 7d
  routePrefix: /
  securityContext:
    fsGroup: 65534
    runAsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534
  serviceAccountName: prometheus
  serviceMonitorSelector: null  # This is the root cause of the issue
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 16Gi
        storageClassName: gp2
  thanos:
    image: quay.io/improbable/thanos:v0.3.2
    objectStorageConfig:
      key: bucket.yaml
      name: thanos-storage-config
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
    version: 0.3.2
  version: 2.9.2
```

* Prometheus Operator Logs:

N/A

**Anything else we need to know?**:

The configuration generation requirements should either be documented or feature gated instead of depending on a seemingly unrelated property.
