### ISSUE TITLE
Prometheus not loading rules

### ISSUE THREAD

**Issue by cyperplex** [coreos/prometheus-operator#2588]
**What did you do?**

1. Installed the prom operator using the latest helm chart.

2. Created a sample rule file :

```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    app: prometheus
    role: alert-rules
  name: prometheus-example-rules
spec:
  groups:
  - name: ./example.rules
    rules:
    - alert: ExampleAlert
      expr: vector(1)
```

3.  Applied the rule kubectl apply -f example-rule.yaml

**Did you expect to see some different?**

Expected to see the rule loaded into the Prometheus operator and the configmap updated 
prometheus-prometheus-operator-prometheus-rulefiles-0, which remains empty. 

**Environment**
Dev

* Prometheus Operator version:
prometheus-operator-5.5.1

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:22:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
➜  kuard

* Kubernetes cluster kind:

kops created cluster

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

Referencing :

http://www.programmersought.com/article/4625111511/
