### ISSUE TITLE
Servicemonitor not being added to prometheus targets

### ISSUE THREAD

**Issue by s4mur4i** [coreos/prometheus-operator#259]
**What did you do?**

I created a prometheus with following config:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: eponymous-hyena-promserver
  namespace: monitoring
  labels:
    app: eponymous-hyena-uprometheus-operator
    chart: uprometheus-operator
    chartversion: 0.1.0
    component: "promserver"
    release: "eponymous-hyena"
    prometheus: eponymous-hyena-promserver
spec:
  paused: false
  replicas: 1
  version: "v1.5.2"
  retention: 168h
  ruleSelector:
    matchLabels:
      release: "eponymous-hyena"
      prometheus: eponymous-hyena-promserver
  baseImage: "quay.io/prometheus/prometheus"
  storage:
    class: ssd
    resources:
      requests:
        storage: 100Gi
    
  routePrefix: "/"
  serviceMonitorSelector:
    matchExpressions:
    - key: umonitor
      operator: In
      values:
      - "True"
      - "true"
      - "1"
    
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: alertmanager-eponymous-hyena
        port: alertmanager-http
    #      {}
      
  resources:
    null

```

When adding two servicemonitors, one of them is picked up, but the other one not:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  labels:
    umonitor: "True"
    app: example-app-servicemonitor2
  name: example-app-servicemonitor2
spec:
  endpoints:
    - interval: 15s
      port: web
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
    - app: example-app
---
kind: Service
apiVersion: v1
metadata:
  name: example-app
  labels:
    app: example-app
spec:
  selector:
    app: example-app
  ports:
  - name: web
    port: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: fabxc/instrumented_app
        ports:
        - name: web
          containerPort: 8080
```
This one is not listed in prometheus targets
But following is listed:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: k8s-apps-http-monitor
  namespace: monitoring
  labels:
    umonitor: "True"
    k8s-apps: http
spec:
  jobLabel: k8s-app
  selector:
    matchExpressions:
    - {key: k8s-app, operator: Exists}
  namespaceSelector:
    matchNames:
    - kube-system
  endpoints:
  - port: http-metrics
    interval: 15s
  - port: http-metrics-dnsmasq
    interval: 15s
  - port: http-metrics-skydns
    interval: 15s
```
both are in same namespace, and looking at resource list:
```
kubectl get servicemonitors -n monitoring
NAME                          KIND
example-app-servicemonitor2   ServiceMonitor.v1alpha1.monitoring.coreos.com
k8s-apps-http-monitor         ServiceMonitor.v1alpha1.monitoring.coreos.com
k8s-apps-https-monitor        ServiceMonitor.v1alpha1.monitoring.coreos.com
k8s-kube-dns-monitor          ServiceMonitor.v1alpha1.monitoring.coreos.com
kube-apiserver-monitor        ServiceMonitor.v1alpha1.monitoring.coreos.com
```
**What did you expect to see?**

I expected both servicemonitors to be present, or some error to be visible in prometheus console

**What did you see instead? Under which circumstances?**

I see all other servicemonitors, except the application one

**Environment**

* Kubernetes version information:

	Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	cluster was not created y me, don't know. if needed can get information.

* Manifests:

Already done.

* Prometheus Operator Logs:

Found no logs, or info how to look at them, or extract them.
