### ISSUE TITLE
Prometheus.spec.routePrefix exhibits default behaviour that conflicts with upstream Prometheus

### ISSUE THREAD

**Issue by jstangroome** [coreos/prometheus-operator#2603]
**What happened?**
Defined a Prometheus object specifying an alternate externalUrl but not specifying any routePrefix:
```!yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
spec:
  externalUrl: /p8s/
```
This resulted in the Prometheus Pod's prometheus container having args `--web.external-url=/p8s/ --web.route-prefix=/`

**Did you expect to see some different?**
Upstream prometheus specifies that if the `--web.route-prefix` argument is omitted, then it will default to the value of the `--web.external-url` argument. See code [here](https://github.com/prometheus/prometheus/blob/c790d7658cecf379bf95a6d6d25ea7fcef54bcf1/cmd/prometheus/main.go#L152-L153) and [here](https://github.com/prometheus/prometheus/blob/c790d7658cecf379bf95a6d6d25ea7fcef54bcf1/cmd/prometheus/main.go#L266-L268).

I therefore expected the Prometheus Operator to follow the same guidelines. I.e. if I omit the `routePrefix` member from the Prometheus object, it would either not append the `--web.route-prefix` argument to the command line, or it would append it with the same value as specified for the external URL.

I.e. the command line should have been one of these two possibilities:
* `--web.external-url=/p8s/ --web.route-prefix=/p8s/`
* `--web.external-url=/p8s/`

The responsible code is here:
https://github.com/coreos/prometheus-operator/blob/868123aae9b73be40e42a9f2611fee22632af2db/pkg/prometheus/statefulset.go#L409-L413

Moving line 413 (`promArgs = append(...)`) up inside the immediately preceeding `if`-block would resolve the issue.

**How to reproduce it (as minimally and precisely as possible)**:

Set the Prometheus spec `externalUrl` to a non-default value but do not set any `routePrefix` value.

**Environment**

* Prometheus Operator version:

    `quay.io/coreos/prometheus-operator:v0.29.0`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind:

    minikube and kubeadm

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  externalUrl: /p8s/
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: v2.5.0
```
