### ISSUE TITLE
NGINX Metrics not scraping

### ISSUE THREAD

**Issue by DJAyth** [coreos/prometheus-operator#2606]
First off, here is what I'm trying to do in case someone has quick advice. Need to use HPA to scale wordpress instances based on connections to the site. In a nutshell that's it.

**What did you do?**

Created k8s cluster, used helm charts to deploy prometheus-operator and create the custom metrics. The example-app works for me, I can deploy that, generate connections and it works. However, trying to do it with anything else fails for me miserably.

I have the following containers setup within a POD:

NGINX reverse proxy(with stub_status enabled)
Wordpress image providing the website
Container running the nginx-prometheus-exporter(to provide a site for prometheus to grab metrics.

When I run the deployment, creating the necessary items, the HPA complains that it can't find the metric, and I looked at the custom metrics myself with kubectl get --raw and cannot see them being added.

**Did you expect to see some different?**

Expected to see metrics shown and autoscale the app when connections reach high levels.

**Environment**

Cluster running on an OpenStack provider, running Rancher 2.2. No other customizations made other than what's needed to support the custom metrics(ie helm chart install).

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:

   Rancher 2.2 created cluster on Openstack Queens.

* Manifests:

```
apiVersion: v1
kind: Service
metadata:
  name: mywebsite #change to shortened name of the site
  labels:
    app: mywebsite #change to shortened name of the site
    release: mon
spec:
  ports:
    - port: 80
      name: web
    - port: 9113
      name: nginx-export
  selector:
    app: mywebsite #change to shortened name of the site
  type: LoadBalancer
---
kind: ConfigMap
metadata: 
  name: nginx-config
apiVersion: v1
data: 
  nginx.conf: |-
    events {
      }
    http {
      server {
      listen 80;
      listen [::]:80;
      server_name staging.mysite.com;
      location / {
        proxy_pass http://localhost:8080/;
      }
      location = /basic_status {
        stub_status;
      } 
    }   
    }            
---
kind: ConfigMap
metadata:
  name: apache-config
apiVersion: v1
data:
  000-default.conf: |-
    <VirtualHost *:8080>
      ServerAdmin webmaster@localhost
      DocumentRoot /var/www/html
      ErrorLog ${APACHE_LOG_DIR}/error.log
      CustomLog ${APACHE_LOG_DIR}/access.log combined
      </VirtualHost>
---
kind: ConfigMap
metadata:
  name: apache-ports-config
apiVersion: v1
data:
  ports.conf: |-
    # If you just change the port or add more ports here, you will likely also
    # have to change the VirtualHost statement in
    # /etc/apache2/sites-enabled/000-default.conf
    Listen 8080
    <IfModule ssl_module>
       Listen 4443
    </IfModule>
    <IfModule mod_gnutls.c>
       Listen 4443
    </IfModule>
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mywebsite #change to shortened name of the site
  labels:
    app: mywebsite #change to shortened name of the site
    release: mon
spec:
  selector:
    matchLabels:
      app: mywebsite #change to shortened name of the site
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mywebsite #change to shortened name of the site
        release: mon
    spec:
      containers:
      - image: nginx:1.16.0-alpine
        name: stage-mywebsite-proxy #change to site name, replacing the periods with dashes
        ports:
        - containerPort: 80
          name: kdb-proxy-port # change to a shortened version of the site-name
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      - image: wordpress:4.8-apache
        name: stage-mywebsite-com #change to site name, replacing the periods with dashes
        env:
        - name: WORDPRESS_DB_HOST
          value: '172.23.1.17' # If database server changes, update this IP with the name/IP of the db server.
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: WORDPRESS_DB_USER
          value: 'wp' # User the wordpress site will use to access the DB.
        - name: WORDPRESS_DB_NAME
          value: 'www_mywebsite_com' # Set to the name of the DB you imported to.
        ports:
        - containerPort: 8080
          name: stage-kdb-port # change to a shortened version of the site-name
        volumeMounts:
        - name: mywebsite-content-storage #change this to the shortened site name with -content-storage appended.
          mountPath: /var/www/html
        - name: mywebsite-plugins-storage # Change to the shortened site name with -plugins-storage appended.
          mountPath: /var/www/html/wp-content/plugins
          readOnly: true
        - name: apache-ports-config
          mountPath: /etc/apache2/ports.conf
          subPath: ports.conf
        - name: apache-config
          mountPath: /etc/apache2/sites-enabled/000-default.conf
          subPath: 000-default.conf
      - image: nginx/nginx-prometheus-exporter:0.3.0
        name: nginx-exporter
        env:
        - name: SCRAPE_URI
          value: 'http://localhost/basic_status'
        - name: NGINX_RETRIES
          value: '50'
        ports:
        - containerPort: 9113
          name: nginx-export
      volumes:
      - name: mywebsite-content-storage #Use name above under volumeMounts for the content storage.
        nfs:
          server: 172.23.2.15
          path: /content/stage_mywebsite_com # Change to where you put the site content
      - name: mywebsite-plugins-storage #Use name above under volumeMounts for the plugins storage.
        nfs:
          server: 172.23.2.15
          path: /plugins/stage_mywebsite_com # Change to where you put the site plugins
      - name: apache-ports-config
        configMap:
          name: apache-ports-config
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: apache-config
        configMap:
          name: apache-config
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mywebsite-sm
  namespace: monitoring
  labels:
    app: mywebsite
    release: mon
spec:
  jobLabel: kdb-metrics
  selector:
    matchLabels:
      app: mywebsite
      release: mon
  endpoints:
  - port: nginx-export
    interval: 10s
    path: /metrics
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: mywebsite-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mywebsite
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      target:
        kind: Service
        name: mywebsite
      metricName: nginx_connections_active
      targetValue: 10

```
