### ISSUE TITLE
custom container support in PrometheusSpec

### ISSUE THREAD

**Issue by wadadli** [coreos/prometheus-operator#2607]
I'm curious,  is there a way to pass a custom image to `PrometheusSpec.containers` according to the documentation 
> prometheus, prometheus-config-reloader, rules-configmap-reloader, and thanos-sidecar

are the current supported containers.

If this isn't supported could someone point me to the relevant lines of code that implements these containers?  We want to add the stack driver side-car to the operator and think others might find this useful as well,  it's possible to do this today using a `hook` in helm but I'm not sure if that is the best route,  any thoughts?

**Comment by brancz** [comment]
You can use that field to add any additional containers you'd like.

**Comment by wadadli** [comment]
how does that actually look?

Are you saying I can literally do 
```
- name: sidecar
        image: ${SIDECAR_IMAGE_NAME}:${SIDECAR_IMAGE_TAG}
        imagePullPolicy: Always
        args:
        - \"--stackdriver.project-id=${GCP_PROJECT}\"
        - \"--prometheus.wal-directory=${DATA_DIR}/wal\"
        - \"--stackdriver.kubernetes.location=${GCP_REGION}\"
        - \"--stackdriver.kubernetes.cluster-name=${KUBE_CLUSTER}\"
        #- \"--stackdriver.generic.location=${GCP_REGION}\"
        #- \"--stackdriver.generic.namespace=${KUBE_CLUSTER}\"
        ports:
        - name: sidecar
          containerPort: 9091
        volumeMounts:
        - name: ${DATA_VOLUME}
          mountPath: ${DATA_DIR}
```
