### ISSUE TITLE
How can I install prometheus-operator:v0.30.0 at offline?

### ISSUE THREAD

**Issue by ighack** [coreos/prometheus-operator#2632]
I want download image at A then load image and push to my private warehouse.

but "docker pull quay.io/coreos/prometheus-operator:v0.30.0" at A
I get "Error response from daemon: Get https://quay.io/v1/_ping: dial tcp: lookup quay.io: no such host"
 ```
spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --logtostderr=true
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.30.0
        image: quay.io/coreos/prometheus-operator:v0.30.0
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
```
this is in the bundle.yaml
