### ISSUE TITLE
How does one utilize externalLabels

### ISSUE THREAD

**Issue by jtslear** [coreos/prometheus-operator#2650]
**What happened?**

I'm trying to figure out how to utilize [`externalLabels` as documented](https://github.com/coreos/prometheus-operator/blob/ca400fdc3edd0af0df896a338eca270e115b74d7/Documentation/api.md#prometheusspec), but I do not see the desired configuration inside of the generated `prometheus.yml` configuration of the running container.

**Did you expect to see some different?**

Based on the documented details, I would've expected the prometheus.yml file to contain something like this:

```yaml
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  external_labels:
    env: pre
...
```

Instead, the `external_labels` item is missing entirely.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

`v0.30.1`

* Kubernetes version information:

`1.13.6`

* Kubernetes cluster kind:

GKE

* Manifests:

```
 apiVersion: monitoring.coreos.com/v1
 kind: Prometheus
 metadata:
   name: release-name-prometheus-op-prometheus
   labels:
     app: prometheus-operator-prometheus

     chart: prometheus-operator-5.12.1
     release: "release-name"
     heritage: "Tiller"
 spec:
   alerting:
     alertmanagers:
       - namespace: monitor
         name: release-name-prometheus-op-alertmanager
         port: web
         pathPrefix: "/"
   baseImage: quay.io/prometheus/prometheus
   version: v2.9.1
   externalLabels:
     env: pre
```

**Anything else we need to know?**:

I am using the [stable/prometheus-operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator) helm chart to deploy this.  The latest version contains support for supplying the `externalLabels` into the prometheus-operator.
