### ISSUE TITLE
CRD PodMonitors unable to be created

### ISSUE THREAD

**Issue by dmyerscough** [coreos/prometheus-operator#2656]
**What happened?**

I just tried the latest version of the Prometheus Operator and I am receiving the following error:-

```bash
$ kubectl -n monitoring logs prometheus-prometheus-oper-operator-7dd5bdcccc-fdg6v
ts=2019-06-21T07:53:33.283312865Z caller=main.go:181 msg="Starting Prometheus Operator version '0.31.0'."
ts=2019-06-21T07:53:33.296616454Z caller=main.go:97 msg="Staring insecure server on :8080"
level=info ts=2019-06-21T07:53:33.309979163Z caller=operator.go:419 component=prometheusoperator msg="connection established" cluster-version=v1.13.6-gke.6
level=info ts=2019-06-21T07:53:33.311433198Z caller=operator.go:213 component=alertmanageroperator msg="connection established" cluster-version=v1.13.6-gke.6
level=info ts=2019-06-21T07:53:33.419776359Z caller=operator.go:635 component=alertmanageroperator msg="CRD updated" crd=Alertmanager
level=info ts=2019-06-21T07:53:33.462361559Z caller=operator.go:1593 component=prometheusoperator msg="CRD updated" crd=Prometheus
level=info ts=2019-06-21T07:53:33.479247628Z caller=operator.go:1593 component=prometheusoperator msg="CRD updated" crd=ServiceMonitor
level=info ts=2019-06-21T07:53:33.494134267Z caller=operator.go:1593 component=prometheusoperator msg="CRD updated" crd=PodMonitor
level=info ts=2019-06-21T07:53:33.511255581Z caller=operator.go:1593 component=prometheusoperator msg="CRD updated" crd=PrometheusRule
level=info ts=2019-06-21T07:53:36.43727806Z caller=operator.go:229 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2019-06-21T07:53:36.637764612Z caller=operator.go:184 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2019-06-21T07:53:36.638057629Z caller=operator.go:456 component=alertmanageroperator msg="sync alertmanager" key=monitoring/prometheus-prometheus-oper-alertmanager
level=info ts=2019-06-21T07:53:36.665789529Z caller=operator.go:456 component=alertmanageroperator msg="sync alertmanager" key=monitoring/prometheus-prometheus-oper-alertmanager
ts=2019-06-21T07:53:42.554252068Z caller=main.go:292 msg="Unhandled error received. Exiting..." err="creating CRDs failed: waiting for PodMonitor crd failed: timed out waiting for Custom Resource: failed to list CRD: podmonitors.monitoring.coreos.com is forbidden: User \"system:serviceaccount:monitoring:prometheus-prometheus-oper-operator\" cannot list resource \"podmonitors\" in API group \"monitoring.coreos.com\" at the cluster scope"
```

**Did you expect to see some different?**

The previous version did not complain about the podmonitors CRD

**How to reproduce it (as minimally and precisely as possible)**:

Install the latest version of the Prometheus Operator:-

```bash

kubectl create -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/alertmanager.crd.yaml
kubectl create -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/prometheus.crd.yaml
kubectl create -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/prometheusrule.crd.yaml
kubectl create -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/servicemonitor.crd.yaml
kubectl create -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/podmonitor.crd.yaml

helm template --name prometheus --namespace monitoring prometheus-operator-5.12.3.tgz \
    --set prometheusOperator.image.tag="v0.31.0" \
    --set prometheus.ingress.enabled=false \
    --set prometheus.prometheusSpec.replicas=2 \
    --set prometheus.prometheusSpec.retention=2w \
    --set prometheus.resources.requests.memory=7Gi \
    --set alertmanager.ingress.enabled=false \
    --set alertmanager.alertmanagerSpec.replicas=2 \
    --set grafana.ingress.enabled=false \
    --set grafana.adminPassword="XXXXXXX" \
    --set grafana.additionalDataSources[0].name="Thanos" \
    --set grafana.additionalDataSources[0].access="proxy" \
    --set grafana.additionalDataSources[0].orgId="1" \
    --set grafana.additionalDataSources[0].type="prometheus" \
    --set grafana.additionalDataSources[0].editable="false" \
    --set grafana.additionalDataSources[0].version="1" \
    --set grafana.additionalDataSources[0].url="http://thanos-query.monitoring.svc.cluster.local:9090" \
    --set kubeEtcd.enabled=false \
    --set coreDns.enabled=false \
    --set kubeDns.enabled=true \
    --set defaultRules.rules.etcd=false \
    --set prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.storageClassName="ssd" \
    --set prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.accessModes={"ReadWriteOnce"} \
    --set prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.resources.requests.storage="100Gi" \
    --set prometheus.prometheusSpec.thanos.baseImage="improbable/thanos" \
    --set prometheus.prometheusSpec.thanos.version="v0.5.0" \
    --set prometheus.prometheusSpec.thanos.peers="thanos-peers.monitoring.svc.cluster.local:10900" \
    --set prometheus.prometheusSpec.thanos.objectStorageConfig.key="thanos.yaml" \
    --set prometheus.prometheusSpec.thanos.objectStorageConfig.name="thanos-objstore-config" | kubectl -n monitoring create -f-
```

**Environment**

k8s in GCP

* Prometheus Operator version:

v0.31.0
  
* Kubernetes version information:

```bash
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.6-gke.6", GitCommit:"fcbc1d20b6bca1936c0317743055ac75aef608ce", GitTreeState:"clean", BuildDate:"2019-05-23T11:42:40Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

GKE

* Manifests:

You can get this from the Helm template command

* Prometheus Operator Logs:

```
$ kubectl -n monitoring logs prometheus-prometheus-oper-operator-7dd5bdcccc-fdg6v
ts=2019-06-21T07:53:33.283312865Z caller=main.go:181 msg="Starting Prometheus Operator version '0.31.0'."
ts=2019-06-21T07:53:33.296616454Z caller=main.go:97 msg="Staring insecure server on :8080"
level=info ts=2019-06-21T07:53:33.309979163Z caller=operator.go:419 component=prometheusoperator msg="connection established" cluster-version=v1.13.6-gke.6
level=info ts=2019-06-21T07:53:33.311433198Z caller=operator.go:213 component=alertmanageroperator msg="connection established" cluster-version=v1.13.6-gke.6
level=info ts=2019-06-21T07:53:33.419776359Z caller=operator.go:635 component=alertmanageroperator msg="CRD updated" crd=Alertmanager
level=info ts=2019-06-21T07:53:33.462361559Z caller=operator.go:1593 component=prometheusoperator msg="CRD updated" crd=Prometheus
level=info ts=2019-06-21T07:53:33.479247628Z caller=operator.go:1593 component=prometheusoperator msg="CRD updated" crd=ServiceMonitor
level=info ts=2019-06-21T07:53:33.494134267Z caller=operator.go:1593 component=prometheusoperator msg="CRD updated" crd=PodMonitor
level=info ts=2019-06-21T07:53:33.511255581Z caller=operator.go:1593 component=prometheusoperator msg="CRD updated" crd=PrometheusRule
level=info ts=2019-06-21T07:53:36.43727806Z caller=operator.go:229 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2019-06-21T07:53:36.637764612Z caller=operator.go:184 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2019-06-21T07:53:36.638057629Z caller=operator.go:456 component=alertmanageroperator msg="sync alertmanager" key=monitoring/prometheus-prometheus-oper-alertmanager
level=info ts=2019-06-21T07:53:36.665789529Z caller=operator.go:456 component=alertmanageroperator msg="sync alertmanager" key=monitoring/prometheus-prometheus-oper-alertmanager
ts=2019-06-21T07:53:42.554252068Z caller=main.go:292 msg="Unhandled error received. Exiting..." err="creating CRDs failed: waiting for PodMonitor crd failed: timed out waiting for Custom Resource: failed to list CRD: podmonitors.monitoring.coreos.com is forbidden: User \"system:serviceaccount:monitoring:prometheus-prometheus-oper-operator\" cannot list resource \"podmonitors\" in API group \"monitoring.coreos.com\" at the cluster scope"
```

**Anything else we need to know?**:

**Comment by adamarnold-msm** [comment]
Can confirm, we are experiencing this bug. Adding podmonitors to the cluster role binding fixes

- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - prometheuses
  - prometheuses/finalizers
  - alertmanagers/finalizers
  - servicemonitors
  - prometheusrules
  - **podmonitors**

**Comment by brancz** [comment]
Did you update the ClusterRole? This should not occur with the latest bundle:

https://github.com/coreos/prometheus-operator/blob/852a9aa995e279ce31fc2ad3e7fe8882ad5b2244/bundle.yaml#L33-L50

**Comment by adamarnold-msm** [comment]
Thanks, waiting on a PR to be merged in the helm config https://github.com/helm/charts/pull/14943

**Comment by lubouski** [comment]
Greetings @brancz have the similar issue with `podmonitors`
Here my `rbac` config:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - prometheuses
  - prometheuses/finalizers
  - alertmanagers/finalizers
  - servicemonitors
  - podmonitors
  - prometheusrules
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - services
  - services/finalizers
  - endpoints
  verbs:
  - get
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: monitoring
```
And deployment config:
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: prometheus-operator
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --logtostderr=true
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.31.0
        image: quay.io/coreos/prometheus-operator:v0.31.0
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator
```

But facing error:
```
level=info ts=2019-06-24T10:02:48.649080391Z caller=operator.go:184 component=alertmanageroperator msg="successfully synced all caches"
ts=2019-06-24T10:02:54.567136116Z caller=main.go:292 msg="Unhandled error received. Exiting..." err="creating CRDs failed: waiting for PodMonitor crd failed: timed out waiting for Custom Resource: failed to list CRD: podmonitors.monitoring.coreos.com is forbidden: User \"system:serviceaccount:monitoring:prometheus-operator\" cannot list resource \"podmonitors\" in API group \"monitoring.coreos.com\" at the cluster scope"
```
