### ISSUE TITLE
Adding write_relabel_configs in additionalScrapeConfigs doesn't work

### ISSUE THREAD

**Issue by Aracki** [coreos/prometheus-operator#2658]
* Prometheus Operator version:

    `v0.23.2`

* Kubernetes version information:

    `v1.11.7`

* Manifests:

My prometheus operator manifest last few lines in `.spec`: 

```
  remoteWrite:
    - url: "http://influxdb:8086/api/v1/prom/write?db=prometheus"
  additionalScrapeConfigs:
    key: prometheus-additional-public-api.yaml
    name: prometheus-additional-public-api
  version: v2.4.2
```

My **_prometheus-additional-public-api_** secret:

```
prometheus:
  remote_write:
    - url: http://influxdb:8086/api/v1/prom/write?db=prometheus
      write_relabel_configs:
        - source_labels: [__name__]
          regex:         jvm.*
          action:        drop
```
_Prometheus Operator Logs:_

```
E0621 14:49:45.104915       1 operator.go:816] Sync "staging/public-api" failed: creating config failed: generating config failed: unmarshalling additional scrape configs failed: yaml: unmarshal errors:
  line 1: cannot unmarshal !!map into []yaml.MapSlice
```
---

My second try of **_prometheus-additional-public-api_** secret:
```
- remote_write:
    - url: http://influxdb:8086/api/v1/prom/write?db=prometheus
      write_relabel_configs:
        - source_labels: [__name__]
          regex:         jvm.*
          action:        drop
```
_Prometheus instances logs:_ 
```
 err="error loading config from \"/etc/prometheus/config_out/prometheus.env.yaml\": couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: yaml: unmarshal errors:\n  line 87: field remote_write not found in type config.plain"
```
