### ISSUE TITLE
How can I troubleshoot PrometheusRule CRDs?

### ISSUE THREAD

**Issue by jtslear** [coreos/prometheus-operator#2665]
**What did you do?**

How does one verify that PrometheusRule objects are being picked up and utilized by the prometheus operator correctly?  I've added 63 rule objects to kubernetes:

```
% k get prometheusrules.monitoring.coreos.com
NAME                                                              AGE
alertmanager                                                      1m
chefs                                                             59s
commit-workers                                                    58s
dashboard-gitlab-com-status                                       57s
deadman-switch-alerts                                             57s
dev-gitlab-orgs                                                   56s
error-rates                                                       55s
<snip>
```

Looking at the logs of the operator, we see this line item every time a file is applied: 

```
level=info ts=2019-07-06T14:21:29.889515026Z caller=operator.go:1050 component=prometheusoperator msg="sync prometheus" key=monitoring/gitlab-monitoring-promethe-prometheus
```

However, I can't find a rule files in the prometheus Pod, and going to the prometheus `/rules` endpoint confirms that my rules are not being applied to the running Pod.

The running prometheus instance only has one location specified to look for rules files:

```
/etc/prometheus $ head config_out/prometheus.env.yaml
<snip>
rule_files:
- /etc/prometheus/rules/prometheus-gitlab-monitoring-promethe-prometheus-rulefiles-0/*.yaml
<snip>
```

I see the rules that get shipped with the operator helm chart here but not any of my custom rules:

```
/etc/prometheus/rules/prometheus-gitlab-monitoring-promethe-prometheus-rulefiles-0 $ ls
monitoring-gitlab-monitoring-promethe-alertmanager.rules.yaml                    monitoring-gitlab-monitoring-promethe-kubernetes-resources.yaml
<snip>
```

**Environment**

* Prometheus Operator version:

    `v0.31.1`

* Kubernetes version information:

    `v1.13.6-gke.13`

* Kubernetes cluster kind:

    `GKE`

* Manifests:

Example rule:
```
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alertmanager
spec:
  groups:
  - name: alertmanager.rules
    rules:
    - alert: AlertmanagerNotificationsFailing
      expr: rate(alertmanager_notifications_failed_total[1m]) > 0
      for: 1m
      labels:
        pager: pagerduty
        service: alertmanager
        severity: s1
      annotations:
        title: Alertmanager is failing sending notications
        runbook: troubleshooting/alertmanager-notification-failures.md
        description: Alertmanager is seeing errors for integration {{$labels.integration}}
```

**Anything else we need to know?**:

Prometheus Operator installed via `stable/prometheus-operator` helm chart version `5.14.1`.  The custom rule files were manually created.  All rules were correctly entered into Kubernetes without error.  Only the rules that ship with the helm chart are being inserted into prometheus.

I'm unable to determine a few things:
1. How long does it take the operator to recognize and insert a new rule into prometheus, from `kubectl apply -f custom-rule-file.yaml` to the rules endpoint of prometheus telling me it's processing my rule?
1. Are there other logs I should be looking at to determine where my rules may be?  I suspect maybe there's a validation/format problem with my rules, but I can't find this type of detail.
1. Does the namespace for which rules live matter?  Currently they all reside in the same namespace as the operator.
