### ISSUE TITLE
Unable to modify storage class nor size after installation

### ISSUE THREAD

**Issue by jtslear** [coreos/prometheus-operator#2668]
**What happened?**

I created a storage configuration:

```
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: standard-regional-east1
```

Then when things weren't working, discovered a problem with GKE's use of small volumes.  So I needed to recreate the same thing, but a larger disk:

```
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        storageClassName: standard-regional-east1
```

Upon doing so, the operator does not appear to do anything to help us along in recreating the PV's.  The replicas never get restarted, new volume claims never show up, and nothing in the logs of the operator telling me whether or not it's attempting to do anything.  **The same things happens if I modify the `storageClassName` to be utilized.**  I toyed with deleting various things at various stages.   What I thought was odd, was that even deleting the operator configuration, followed by the pods and the operator itself, the operator would start up again (minus the prometheus pods), and after repopulating the operators configuration, it would _continue_ to utilize the incorrect storage configuration.  This makes me think there's a configuration somewhere else I don't know about that is impacting my ability to figure out how to cleanly roll this type of configuration change.  The only method I can get to work, is removing the entire prometheus-operator installation.  I prefer to avoid this with the goal of maintaining uptime for the monitoring infrastructure of my cluster.

**Did you expect to see some different?**

* When modifying the size of the volume claim, create a new PV with the appropriate size and ensure the new prometheus pod(s) has it bound
* When modifying the storage class of the volume claim, create a new PV with the appropriate class and ensure the new prometheus pod(s) has it bound
* bonus points for automatically cleaning up the old PV/PVC's and performing this in a rolling manner when more than one replica is being utilized

**How to reproduce it (as minimally and precisely as possible)**:

I'm using the `stable/prometheus-operator` helm chart version `5.14.1`. Create a storage spec, and modify either the storage size or storage class name options

**Environment**

* Prometheus Operator version:

    `v0.31.1`

* Kubernetes version information:

    `v1.13.6-gke.13`

* Kubernetes cluster kind:

    GKE
