### ISSUE TITLE
How to scrape multiple redis targets

### ISSUE THREAD

**Issue by eddycharly** [coreos/prometheus-operator#2687]
On the redis exporter, the configuration to scrape multiple redis targets is described like this :

https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts

```
scrape_configs:
  ## config for the multiple Redis targets that the exporter will scrape
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis://first-redis-host:6379
        - redis://second-redis-host:6379
        - redis://second-redis-host:6380
        - redis://second-redis-host:6381
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: <<REDIS-EXPORTER-HOSTNAME>>:9121
```

How can we achieve the same thing with `ServiceMonitor` ?

I tried to add a `target` in `params` of my endpoint (https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint) but it didn't work.

Is it possible at all ? Or are we supposed to deploy one redis exporter per redis target ?

Any help apreciated.

**Comment by brancz** [comment]
> Is it possible at all ? Or are we supposed to deploy one redis exporter per redis target ?

This is typically the recommendation, as we want to do whitebox monitoring, hence the exporter should be as close as possible to the redis server itself.

**Comment by eddycharly** [comment]
Thanks @brancz
I see your point but in the end it doesn't really answer my question.

I finally got it working yesterday.

The first main difference with the `redis-exporter` example is the service discovery of course.
As we use service discovery in k8s, the `static_configs` is useless in our  case.
Consequently, the relabeling can be simplified, we just need to specify the target in endpoint params and relabel `instance` with the target, like this :
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-cache
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: prometheus-redis-exporter
      release: redis-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - honorLabels: true
      path: /scrape
      targetPort: 9121
      params:
        target:
          - redis://cache.infra:6379
      relabelings:
        - sourceLabels: [__param_target]
          targetLabel: instance
```

Not sure if i will use that or stick with one exporter per redis but at least it's clear how the `ServiceMonitor` can be used for this kind of use cases.
