### ISSUE TITLE
Readiness probe - configured values not reflecting in Prometheus server pod

### ISSUE THREAD

**Issue by raz5** [coreos/prometheus-operator#2703]
**What happened?**
I  have configured readiness probe but it is not reflecting in pod prometheus.

**Did you expect to see some different?**
When I do describe pod on prometheus pod it shows different readiness probe config.  

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:
v0.30.0
    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: prometheus
  name: prometheus
  namespace:monitoring
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/monitoring/prometheuses/prometheus
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-prometheus-alerts
      namespace: monitoring
      port: web
  baseImage: prometheus-prometheus_prometheus-dbg
  livenessProbe:
    httpGet:
      path: /-/healthy
      port: web
      scheme: HTTP
    initialDelaySeconds: 40
    timeoutSeconds: 3
  readinessProbe:
    httpGet:
      path: /-/ready
      port: web
    initialDelaySeconds: 30
    timeoutSeconds: 3
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  retention: 3d
  ruleSelector: {}
  serviceMonitorSelector: {}


```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
Prometheus server was getting restarted first time.
 logs
```
error loading config from \"/etc/prometheus/config_out/prometheus.env.yaml\": couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): open /etc/prometheus/config_out/prometheus.env.yaml: no such file or directory
```
