### ISSUE TITLE
Additional Scrape when multiple prometheus replica existing

### ISSUE THREAD

**Issue by atangger** [coreos/prometheus-operator#2717]
**What did you do?**

I followed the https://github.com/coreos/prometheus-operator/blob/master/Documentation/additional-scrape-config.md to config the additional scrape target. I have 2 Prometheus replicas running in the cluster.

**Did you expect to see some different?**

At the scrape endpoint, I can see both replicas scrape the data all almost the same time.  This is not the desired behavior. Because I buffered some data at the endpoint so this will cause some race condition.

**Environment**

* Prometheus Operator version:

    `quay.io/coreos/prometheus-operator:v0.30.0`
    

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.8-eks-a977ba", GitCommit:"a977bab148535ec195f12edc8720913c7b943f9c", GitTreeState:"clean", BuildDate:"2019-07-29T20:47:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}`

    

* Kubernetes cluster kind:
   AWS EKS

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    prometheus: prometheus
spec:
  replicas: 2
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
...
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
I can see that the config of the additional scrape config will come to all replica of Prometheus. Is there any way that I can config different replica separately?
