### ISSUE TITLE
alertmanager volumeClaimTemplate silently being ignored

### ISSUE THREAD

**Issue by starcry** [coreos/prometheus-operator#2725]
**What did you do?**
trying to setup persistent volumes in GKE for alertmanager and prometheus

**Did you expect to see some different?**
I was expecting to see a volume claim and that to be connected to /alertmanager in the pod

**Environment**
GKE
baseImage: quay.io/prometheus/alertmanager

* Prometheus Operator version:
$ /bin/alertmanager --version
alertmanager, version 0.15.0 (branch: HEAD, revision: 462c969d85cf1a473587754d55e4a3c4a2abc63c)
  build user:       root@bec9939eb862
  build date:       20180622-11:58:41
  go version:       go1.10.3

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T16:54:35Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.15", GitCommit:"b5da7fc8c38f582ab965295358bbcf867f9b791e", GitTreeState:"clean", BuildDate:"2019-06-28T23:34:22Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:
kind: Alertmanager

* Manifests:

```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: map-service-pv
  labels:
    app: my-example-prometheus
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  gcePersistentDisk:
    pdName: ..........
    readOnly: true
    fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: alertmanager-main-db-claim
  labels:
    app: my-example-prometheus
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
spec:
  version: v0.15.0
  serviceAccountName: alertmanager-main
  baseImage: quay.io/prometheus/alertmanager
  externalUrl: https://.........com/
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 3
  logLevel: debug
  storage:
    volumeClaimTemplate:
      spec:
        selector:
          matchLabels:
            app: my-example-prometheus
        resources:
          requests:
            storage: 10Gi
```

* Prometheus Operator Logs:

```
kubectl logs alertmanager-main-0 alertmanager
level=info ts=2019-08-20T15:47:39.632602665Z caller=main.go:174 msg="Starting Alertmanager" version="(version=0.15.0, branch=HEAD, revision=462c969d85cf1a473587754d55e4a3c4a2abc63c)"
level=info ts=2019-08-20T15:47:39.632672539Z caller=main.go:175 build_context="(go=go1.10.3, user=root@bec9939eb862, date=20180622-11:58:41)"
level=info ts=2019-08-20T15:47:39.686968176Z caller=main.go:311 msg="Loading configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=info ts=2019-08-20T15:47:39.687671684Z caller=cluster.go:561 component=cluster msg="Waiting for gossip to settle..." interval=2s
level=info ts=2019-08-20T15:47:39.691842966Z caller=main.go:387 msg=Listening address=:9093
level=info ts=2019-08-20T15:47:41.688124877Z caller=cluster.go:586 component=cluster msg="gossip not settled" polls=0 before=0 now=3 elapsed=2.000155321s
level=info ts=2019-08-20T15:47:49.689176306Z caller=cluster.go:578 component=cluster msg="gossip settled; proceeding" elapsed=10.001215167s
```

**Anything else we need to know?**:
I was using this guide as a base
https://coreos.com/operators/prometheus/docs/latest/user-guides/storage.html

I've tried a veriety of options but I'm unable to get alertmanager to map to a persistent volume. Does anyone have any insight on what I'm doing wrong?
