### ISSUE TITLE
Bad PrometheusRule prevented prometheus operator from starting

### ISSUE THREAD

**Issue by corlettb** [coreos/prometheus-operator#2727]
The prometheus operator was failing to start with the following error:

```
msg="Unhandled error received. Exiting..." 
err="creating CRDs failed: waiting for PrometheusRule crd failed: timed out waiting for Custom Resource: failed to list CRD: v1.PrometheusRuleList.Items: []*v1.PrometheusRule: v1.PrometheusRule.Spec: v1.PrometheusRuleSpec.Groups: []v1.RuleGroup: v1.RuleGroup.Rules: []v1.Rule: v1.Rule.Annotations: ReadString: expects \" or n, but found f, error found in #10 byte of ...|summary\":false},\"exp|..., bigger context ...|un successfully in the last 24 hours.\",\"summary\":false},\"expr\":\"job:last_success:hours_ago{ exported|..."
```

This turned out to be a problem with the following rule:

```
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
...
spec:
  groups:
    - name: fakerule.rules
      rules:
        - alert: SomeAlert
          expr: someexpression > 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: No
            description: some alert
```

The problem part of this is the "summary: No". No is special in yaml and will be resolved as a boolean that is false.

Now granted this is bad config, but the operator should deal with this better.

- The operator should log the namespace and path for the invalid crd in the error message.
- A bad prometheusrule should not prevent the operator from starting. Invalid rules should just be skipped over.
- The operator should update a "status" field on the crd to inform the user that their prometheusrule has been rejected and why.
- The operator should expose a metric to prometheus to show failing rules.
