### ISSUE TITLE
External AlertManager doesn't work

### ISSUE THREAD

**Issue by qurname2** [coreos/prometheus-operator#2732]
**What did you do?**
I try to use external alertmanager, placed not in k8s cluster, for kube-prometheus, but he doesn't work..
I deleted alertmanager from k8s cluster ( if I using internal alertmanager, all work perfectly ) and create endpoint with external for k8s cluster ip-address.
* Manifests:
part in prometheus-prometheus.yaml
```
spec:
 alerting:
   alertmanagers:
     - name: alertmanager-main
       namespace: monitoring
       port: 9093
       scheme: http
```
```
kubectl -n monitoring get ep
NAME                  ENDPOINTS                                                              AGE
alertmanager-main     1.2.3.4:9093                                                    2d20h
```

* Prometheus Operator version:
    `0.31.1`
* Kubernetes version information:
    `1.14.3`
* Kubernetes cluster kind:
    `kubeadm`

* Prometheus Operator Logs:
In prom-operator logs I don't see smth about alertmanager

* Prometheus config inside prometheus-k8s-0 pod:
```
/etc/prometheus/config_out $ cat prometheus.env.yaml | grep alerting -A 14
alerting:
  alert_relabel_configs:
  - action: labeldrop
    regex: prometheus_replica
  alertmanagers:
  - path_prefix: /
    scheme: http
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - monitoring
```
Access from pod with Prometheus to external alertmanager exist.
```
/prometheus $ wget -O- alertmanager-main:9093
Connecting to alertmanager-main:9093 (1.2.3.4:9093)
writing to stdout
<!DOCTYPE html>
<html lang="en">
    <head>
```
To my mind, this scheme must work, but I am not seeing smth alert’s in my alertmanager.
Anyone have any ideas what I’m doing wrong?

**Comment by qurname2** [comment]
@brancz, maybe you know the answer?

**Comment by qurname2** [comment]
I will answer my own question)
If you would like to send alert's from kube-prometheus to external alertmanager, you should define this:
```
---
apiVersion: v1
kind: Service
  labels:
    alertmanager: main
  name: alertmanager
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: 9093
  type: ClusterIP

---
apiVersion: v1
kind: Endpoints
  name: alertmanager
  namespace: monitoring
subsets:
- addresses:
  - ip: <you_external_ip_here>
  ports:
  - name: web
    port: 9093
    protocol: TCP

---
prometheus-prometheus.yml
spec:
  alerting:
    alertmanagers:
    - name: alertmanager
      namespace: monitoring
      port: web
```
