### ISSUE TITLE
spec.prometheusExternalLabelName looks broken

### ISSUE THREAD

**Issue by HaveFun83** [coreos/prometheus-operator#2736]
**What happened?**
i will change the external label from the managed prometheus to something like
```
prometheusExternalLabelName: test/cluster
```
but instead the prometheus configuration get invalid and could not be loaded
```
level=error ts=2019-08-26T17:08:23.695Z caller=main.go:584 msg="Error reloading config" err="couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: \"test/cluster\" is not a valid label name"
```
looking at the `/etc/prometheus/config_out/prometheus.env.yaml` shows me
```
/prometheus $ cat /etc/prometheus/config_out/prometheus.env.yaml 
global:
  evaluation_interval: 30s
  scrape_interval: 30s
  external_labels:
    prometheus: test/cluster: monitoring/cluster
```
monitoring/cluster is the default label
**Did you expect to see some different?**
The external_label should be configured properly

**How to reproduce it (as minimally and precisely as possible)**:
Configure an external_label via `spec.prometheusExternalLabelName`
**Environment**

* Prometheus Operator version:
prometheus-operator:v0.31.1

* Kubernetes version information:
k8s v1.15.0

* Kubernetes cluster kind:
bare-metal

* Manifests:
none

* Prometheus Operator Logs:
nothing suspicious
 
**Anything else we need to know?**:
