### ISSUE TITLE
Invalid ServiceMonitor can cause panic in operator

### ISSUE THREAD

**Issue by justinwalz** [coreos/prometheus-operator#2776]
Hi. Thanks for the great project. I've installed via helm and noticed the following after creating an invalid ServiceMonitor.

**What happened?**

When creating a ServiceMonitor without a `port`, the operator crashes.

**Did you expect to see some different?**

Yes, no crash. Bonus points for a log output indicating invalid config.

**How to reproduce it (as minimally and precisely as possible)**:

Apply the file provided below.

**Environment**

* Prometheus Operator version:
quay.io/coreos/prometheus-operator:v0.26.0

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.9", GitCommit:"e09f5c40b55c91f681a46ee17f9bc447eeacee57", GitTreeState:"clean", BuildDate:"2019-05-27T15:58:45Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:

kops

* Manifests:

The invalid config
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus-operator
    serviceapp: test-app-servicemonitor
  name: test-app-servicemonitor
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    # port: foobar
  namespaceSelector:
    matchNames:
    - prod
  selector:
    matchLabels:
      app: test-app
```

* Prometheus Operator Logs:

The panic:
```
level=info ts=2019-09-25T03:38:56.993422769Z caller=operator.go:966 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus-operator-prometheus
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1045366]

goroutine 132 [running]:
github.com/coreos/prometheus-operator/pkg/prometheus.(*configGenerator).generateServiceMonitorConfig(0xc000277200, 0x2, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/promcfg.go:385 +0x7d6
github.com/coreos/prometheus-operator/pkg/prometheus.(*configGenerator).generateConfig(0xc000277200, 0xc00085ea80, 0xc00095d470, 0xc00080e5a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/promcfg.go:166 +0x1dab
github.com/coreos/prometheus-operator/pkg/prometheus.(*Operator).createOrUpdateConfigurationSecret(0xc0001fc380, 0xc00085ea80, 0xc000222f10, 0x1, 0x1, 0x0, 0x0)
        /home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:1299 +0x39c
github.com/coreos/prometheus-operator/pkg/prometheus.(*Operator).sync(0xc0001fc380, 0xc000748150, 0x29, 0x1134f00, 0xc0003045d0)
        /home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:977 +0x14b8
github.com/coreos/prometheus-operator/pkg/prometheus.(*Operator).processNextWorkItem(0xc0001fc380, 0x0)
        /home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:859 +0xfc
github.com/coreos/prometheus-operator/pkg/prometheus.(*Operator).worker(0xc0001fc380)
        /home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:848 +0x2b
created by github.com/coreos/prometheus-operator/pkg/prometheus.(*Operator).Run
        /home/travis/gopath/src/github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:398 +0x23a
```

**Anything else we need to know?**:
