### ISSUE TITLE
[Feature] The prometheus-operator should scrape prometheus and alertmanager metrics by default

### ISSUE THREAD

**Issue by sdurrheimer** [coreos/prometheus-operator#278]
or at least in the `contrib/kube-prometheus` example.

@fabxc @brancz

**Comment by brancz** [comment]
Yes it's probably a good idea to add `ServiceMonitor`s for Prometheuses and Alertmanagers. Do you want to add them? We wanted to do more sophisticated meta monitoring for Prometheus but having a `ServiceMonitor` will be required either way, so I think it's a good idea to add to kube-prometheus.

**Comment by gianrubio** [comment]
I did the ServiceMonitor for both service,  I'm just waiting a reply on #298 to submit a PR. 

It's necessary to add labels, on alert manager and prometheus services, to match the expression and create this services monitor below.

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: prometheus
  labels:
    k8s-apps: prometheus
spec:
  endpoints:
  - port: web
  jobLabel: prometheus
  selector:
    matchExpressions:
    - {key: prometheus, operator: In, values: [k8s]}
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  labels:
    k8s-apps: alertmanager
  name: alertmanager
spec:
  endpoints:
  - port: web
  jobLabel: alertmanager
  selector:
    matchExpressions:
    - {key: alertmanager, operator: In, values: [main]}
```
