### ISSUE TITLE
Cannot get prometheus to get nginx ingress stats

### ISSUE THREAD

**Issue by blasrodri** [coreos/prometheus-operator#2809]
**What did you do?**
Installed `prometheus-operator` using `helm`, and having an already installed `nginx-ingress`

**Did you expect to see some different?**
I expected/hoped to have `nginx ingress` metrics out of the box.
**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    prometheus-operator-6.11.0

* Kubernetes version information:

    `kubectl version`
    Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-825e5d", GitCommit:"825e5de08cb05714f9b224cd6c47d9514df1d1a7", GitTreeState:"clean", BuildDate:"2019-08-18T03:58:32Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:

    Not sure. cluster was created.

* Manifests:

```yaml
Name:                   nginx-ingress-controller
Namespace:              ingress-nginx
CreationTimestamp:      Wed, 12 Sep 2018 10:28:10 +0200
Labels:                 app.kubernetes.io/name=ingress-nginx
                        app.kubernetes.io/part-of=ingress-nginx
Annotations:            deployment.kubernetes.io/revision: 2
                        kubectl.kubernetes.io/last-applied-configuration:
                          {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"ingress-nginx","ap...
Selector:               app.kubernetes.io/name=ingress-nginx,app.kubernetes.io/part-of=ingress-nginx
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:           app.kubernetes.io/name=ingress-nginx
                    app.kubernetes.io/part-of=ingress-nginx
  Annotations:      prometheus.io/port: 10254
                    prometheus.io/scrape: true
  Service Account:  nginx-ingress-serviceaccount
  Containers:
   nginx-ingress-controller:
    Image:       quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.24.1
    Ports:       80/TCP, 443/TCP
    Host Ports:  0/TCP, 0/TCP
    Args:
      /nginx-ingress-controller
      --default-backend-service=$(POD_NAMESPACE)/default-http-backend
      --configmap=$(POD_NAMESPACE)/nginx-configuration
      --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
      --udp-services-configmap=$(POD_NAMESPACE)/udp-services
      --publish-service=$(POD_NAMESPACE)/ingress-nginx
      --annotations-prefix=nginx.ingress.kubernetes.io
    Liveness:   http-get http://:10254/healthz delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:10254/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      POD_NAME:        (v1:metadata.name)
      POD_NAMESPACE:   (v1:metadata.namespace)
    Mounts:           <none>
  Volumes:            <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   nginx-ingress-controller-6d58cdfdc4 (1/1 replicas created)
Events:          <none>
```
```yaml
Name:         calling-snail-prometheus-o-prometheus
Namespace:    monitoring
Labels:       app=prometheus-operator-prometheus
              chart=prometheus-operator-6.11.0
              heritage=Tiller
              release=calling-snail
Annotations:  <none>
API Version:  monitoring.coreos.com/v1
Kind:         ServiceMonitor
Metadata:
  Creation Timestamp:  2019-10-04T11:43:04Z
  Generation:          1
  Resource Version:    73213778
  Self Link:           /apis/monitoring.coreos.com/v1/namespaces/monitoring/servicemonitors/calling-snail-prometheus-o-prometheus
  UID:                 20990c66-e69c-11e9-9839-02dee883fad0
Spec:
  Endpoints:
    Path:  /metrics
    Port:  web
  Namespace Selector:
    Match Names:
      monitoring
      ingress-nginx
  Selector:
    Match Labels:
      App:      prometheus-operator-prometheus
      Release:  calling-snail
Events:         <none>
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
