### ISSUE TITLE
Unable to add new Scrape target 

### ISSUE THREAD

**Issue by samsja** [coreos/prometheus-operator#2812]
**What did you do?**

I deployed prometheus-operator with helm.

```shell
helm install stable/prometheus-operator --name prometheus-operator --namespace monitoring
```

I want to add an external scrap source via a ServiceMonitor. The target is a [Kong-ingress](https://github.com/Kong/kubernetes-ingress-controller) deployement.

I have a service that point to an ingress-kong pod that have a /metrics route configure for prometheus scrapping :

```yaml
apiVersion: v1
kind: Service
metadata:
  name: ingress-kong
  namespace: kong
  labels:
    k8s-app: ingress-kong
spec:
  ports:
  - name: metrics
    port: 9542
    protocol: TCP
    targetPort: metrics
  selector:
    app: ingress-kong
```

then I create a ServiceMonitor for this service:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name:  ingress-kong
  namespace: monitoring
  labels:
    Release:  prometheus-operator
spec:
  namespaceSelector:
    matchNames:
      - kong
  selector:
    matchLabels:
      k8s-app: kong-ingress-service
  endpoints:
  - port: metrics
```

But I am no seeing any  kong target on the prometheus console (targets part). I don't know what is happening and I am not able to add my kong metrics to prometheus

**Environment**

* Prometheus Operator version:
```shell
prometheus-operator     1               Tue Oct  1 10:52:38 2019        DEPLOYED        prometheus-operator-6.11.0      0.32.0                  monitoring
```

PS: if you want to test, kong is install with
```shell
 kubectl apply -f https://bit.ly/kong-ingress
```
* Kubernetes version information:

```shell
kubectl version                                                                    
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.9-gke.15", GitCommit:"b48a8d693e191192e27c2f807daa51b54d0b0a61", GitTreeState:"clean", BuildDate:"2019-08-12T17:49:30Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

The kubernete cluster is a gcp cluster

**Comment by brancz** [comment]
Do the Prometheus logs say anything?

**Comment by samsja** [comment]
I don't see any abnormal things in the logs ...

**Comment by brancz** [comment]
Can you share the generated config? It’s in the secret named the same as your Prometheus server.

**Comment by samsja** [comment]
```shell

kb get secret

NAME                                                       TYPE
  DATA   AGE
alertmanager-prometheus-operator-alertmanager              Opaque
  1      18h
default-token-hq2pz                                        kubernetes.io/service-account-token
  3      19h
prometheus-operator-admission                              Opaque
  3      19h
prometheus-operator-alertmanager-token-2tl2c               kubernetes.io/service-account-token
  3      18h
prometheus-operator-grafana                                Opaque
  3      18h
prometheus-operator-grafana-test-token-j62p7               kubernetes.io/service-account-token
  3      18h
prometheus-operator-grafana-token-x8kfz                    kubernetes.io/service-account-token
  3      18h
prometheus-operator-kube-state-metrics-token-qznh8         kubernetes.io/service-account-token
  3      18h
prometheus-operator-operator-token-v2lkr                   kubernetes.io/service-account-token
  3      18h
prometheus-operator-prometheus-node-exporter-token-mmz2v   kubernetes.io/service-account-token
  3      18h
prometheus-operator-prometheus-token-cnbtr                 kubernetes.io/service-account-token
  3      18h
prometheus-prometheus-operator-prometheus                  Opaque
  1      18h

```

which secret it is ?

**Comment by brancz** [comment]
I would assume `prometheus-prometheus-operator-prometheus`, but I can also only guess. The scheme is `prometheus-<your-prometheus-object-name>`. You can find the prometheus object name with `kubectl -n <namespace> get prometheus`.

**Comment by samsja** [comment]
here it is

```yaml
apiVersion: v1
data:
  prometheus.yaml.gz: 
  
kind: Secret
metadata:
  annotations:
    generated: "true"
  creationTimestamp: "2019-10-16T14:52:57Z"
  labels:
    managed-by: prometheus-operator
  name: prometheus-prometheus-operator-prometheus
  namespace: monitoring
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Prometheus
    name: prometheus-operator-prometheus
    uid: 
  resourceVersion: "128241125"
  selfLink: /api/v1/namespaces/monitoring/secrets/prometheus-prometheus-operator-prometheus
  uid:
type: Opaque
```

**Comment by samsja** [comment]
I try to set up kong monitoring via the helm chart values.yaml.

```yaml
# adds additional scrape configs to prometheus.yml
# must be a string so you have to add a | after extraScrapeConfigs:
# example adds prometheus-blackbox-exporter scrape config
extraScrapeConfigs: |
    - job_name: 'prometheus-kong-exporter'
      metrics_path: /metrics
      params:
        module: [http_2xx]
      static_configs:
        - targets:
          - https://ingress-kong.kong

```

the url uses the intern kubernetes dns ( service.namespace).

But it is still not wokring...

**Comment by samsja** [comment]
Finaly i figure it out, I look at the .yaml that helm use to instance the prometheus operator. And I modify it to match kong.

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-kong
  namespace: monitoring
  labels:
    app: prometheus-operator-alertmanager

    chart: prometheus-operator-6.18.0
    release: "prometheus-operator"
    heritage: "Tiller"
spec:
  selector:
    matchLabels:
      k8s-app: kong-ingress-service
  namespaceSelector:
    matchNames:
      - "kong"
  endpoints:
  - port: metrics
    path: "/metrics"
```
I think that the additional labels make the difference.
