### ISSUE TITLE
Admission Hooks Don't Support humanizePercentage Introduced in Prometheus 2.11 (Needs a new release)

### ISSUE THREAD

**Issue by vsliouniaev** [coreos/prometheus-operator#2837]
Works on the master branch, so it should be solved by just making another release.

**What happened?**
The `humanizePercentage` function was [added to Prometheus in 2.11](https://github.com/prometheus/prometheus/releases/tag/v2.11.0). Trying to create alerts with this function should pass admission hooks, but it does not on operator version 0.33.0.
**Did you expect to see some different?**
Should work

**How to reproduce it (as minimally and precisely as possible)**:
Sample alert from kubernetes-mixin that does not pass validation:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: broken-alerts
spec:
  groups:
  - name: kubernetes-storage
    rules:
    - alert: KubePersistentVolumeUsageCritical
      annotations:
        message: The PersistentVolume claimed by {{ $labels.persistentvolumeclaim
          }} in Namespace {{ $labels.namespace }} is only {{ $value | humanizePercentage
          }} free.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepersistentvolumeusagecritical
      expr: |-
        kubelet_volume_stats_available_bytes{job="kubelet"}
          /
        kubelet_volume_stats_capacity_bytes{job="kubelet"}
          < 0.03
      for: 1m
      labels:
        severity: critical
```

* Prometheus Operator version:
0.33.0
