### ISSUE TITLE
Generates too long PVC name

### ISSUE THREAD

**Issue by haf-afa** [coreos/prometheus-operator#2853]
**What happened?**

![prom-op-bug-6](https://user-images.githubusercontent.com/56340843/68694959-682ab600-057a-11ea-9ff7-b1a9b40a6a58.PNG)

This hits Windows silly 246 char path length limit, causing the operator to fail.

**Did you expect to see some different?**

I expected the name of the pvc to be something like `prometheus-0` for the main server's database.

**How to reproduce it (as minimally and precisely as possible)**:

Apply this kustomize patch to a quickstart:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prom-prometheus-operator-prometheus
spec:
  storage:
    volumeClaimTemplate:
      spec:
        # storageClassName: ssd
        resources:
          requests:
            storage: 5Gi
```

(as done with `helm install --name prom --namespace monitoring stable/prometheus-operator`)

**Environment**

* Prometheus Operator version: 7.1.0
* Kubernetes version information: 1.14
* Kubernetes cluster kind: docker desktop
* Manifests: see above for repro
* Prometheus Operator Logs:

From `kubectl get events --all-namespaces`
```
55s         Normal    Pulled                    pod/prometheus-prom-prometheus-operator-prometheus-0                                                                       Container image "quay.io/prometheus/prometheus:v2.12.0" already present on machine
5m50s       Warning   Failed                    pod/prometheus-prom-prometheus-operator-prometheus-0                                                                       Error: stat /host_mnt/c/Users/hefe01/.docker/Volumes/prometheus-prom-prometheus-operator-prometheus-db-prometheus-prom-prometheus-operator-prometheus-0/pvc-226d6a76-0571-11ea-94f3-00155dfa1319: no such file or directory
```

**Anything else we need to know?**: it would be great if you provide a composable operator (i.e. I don't have to go hunting for all bits and pieces I have to use to use it IRL, like the Helm chart composes but does not make composable in turn)

I would MUCH rather point to a bunch of kustomization directories (as bases) than do the surgery I've just performed to get this far. Because this is untractable to work with:

![prom-op-bug-7](https://user-images.githubusercontent.com/56340843/68695868-1c790c00-057c-11ea-8eb8-fa394788ecb8.PNG)

![prom-op-bug-7b](https://user-images.githubusercontent.com/56340843/68695945-49c5ba00-057c-11ea-8dc6-3b67709543f0.PNG)
