### ISSUE TITLE
Existing Azure volume for persistent 

### ISSUE THREAD

**Issue by franrebo84** [coreos/prometheus-operator#2854]
I'm trying to use an existing volume with helm chart. The only example values I found of something similar is this:

```
prometheus:
  server:
    persistentVolume:
      enabled: true
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi 
```

How can I reference my PV and PVC in this values.yaml file?  I cant find any documantation of this.

Thanks!
