### ISSUE TITLE
High CPU/Memory when monitoring 1000+ ServiceMonitor/Endpoints/Service objects

### ISSUE THREAD

**Issue by christidis** [coreos/prometheus-operator#2866]
**What happened?**
I have configured many (1000+) external services to an operator-managed Prometheus using Kubernetes resources (Service/Endpoint/ServiceMonitor) and I have noticed very high CPU and Memory usage in Prometheus (10 cores and 25GB RAM) as well as instability (Liveness errors and restarts).

I then changed targets provider from ServiceMonitor to static files using `additionalScrapeConfigs` and manually copied the targets to the `config_out` source mount dir. 
```
    additionalScrapeConfigs:
    - job_name: 'foo'
      file_sd_configs:
        - files:
          - /etc/prometheus/config_out/targets/foo/*.json
```
Then CPU load and memory dropped dramatically (less than 0.5 core and 3GB RAM).

**Did you expect to see some different?**
I was not expecting to see high CPU and Memory usage when using K8s ServiceMonitor objects to monitor the very same targets. 

**How to reproduce it (as minimally and precisely as possible)**:
Bootstrap many ServiceMonitor objects in order to monitor external services and monitor CPU and RAM consumption. Compare this with static files.

**Environment**

* Prometheus Operator version:

    `6.7.3`
    I have verified this with Prometheus `2.10.0` and `2.14.0`.
    

* Kubernetes version information:

    `Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6", GitCommit:"abdda3f9fefa29172298a2e42f5102e777a8ec25", GitTreeState:"clean", BuildDate:"2019-05-08T13:46:28Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}`

    

* Kubernetes cluster kind:

    Pharos.

**Anything else we need to know?**:
When using K8s ServiceMonitor objects, `/etc/prometheus/config_out/prometheus.env.yaml` was very big (1000+ line) compared to 186 lines when using the `additionalScrapeConfigs`.

Also, not sure if this is helpful or not but in Prometheus, under the _targets_ page:
* All targets were under a common group when using static files.
* Each target was under its own group when using serviceMonitor objects. I tried using the `jobLabel` spec attribute but I didn't manage to group them all to one group.

I have also managed to retrieve pprof output when using serviceMonitor objects
```
(pprof) top30
Showing nodes accounting for 7.07mins, 82.28% of 8.59mins total
Dropped 930 nodes (cum <= 0.04mins)
Showing top 30 nodes out of 105
      flat  flat%   sum%        cum   cum%
  1.93mins 22.46% 22.46%   1.93mins 22.46%  runtime.memclrNoHeapPointers
  0.78mins  9.02% 31.49%   1.60mins 18.59%  runtime.scanobject
  0.61mins  7.07% 38.56%   0.83mins  9.61%  runtime.findObject
  0.45mins  5.20% 43.76%   0.45mins  5.20%  runtime.futex
  0.39mins  4.53% 48.29%   0.39mins  4.53%  cmpbody
  0.34mins  3.96% 52.26%   0.34mins  3.96%  runtime.(*mspan).base
  0.28mins  3.21% 55.47%   0.28mins  3.21%  runtime.procyield
  0.24mins  2.81% 58.28%   0.24mins  2.81%  runtime.markBits.isMarked
  0.20mins  2.28% 60.56%   0.21mins  2.47%  runtime.heapBitsSetType
  0.19mins  2.22% 62.78%   0.40mins  4.66%  runtime.mapiternext
  0.14mins  1.67% 64.45%   1.32mins 15.40%  runtime.sweepone
  0.14mins  1.66% 66.11%   0.58mins  6.81%  sort.doPivot
  0.14mins  1.65% 67.76%   6.17mins 71.86%  github.com/prometheus/prometheus/scrape.targetsFromGroup
  0.12mins  1.45% 69.22%   0.38mins  4.38%  sort.insertionSort
  0.11mins  1.22% 70.44%   0.12mins  1.45%  runtime.spanOf
  0.10mins  1.18% 71.62%   0.29mins  3.33%  runtime.(*mTreap).insert
  0.09mins  1.07% 72.69%   0.61mins  7.08%  runtime.lock
  0.09mins  1.06% 73.75%   0.09mins  1.06%  runtime.heapBits.bits
  0.08mins  0.91% 74.66%   0.08mins  0.91%  runtime.aeshashbody
  0.07mins  0.86% 75.52%   0.52mins  6.06%  runtime.wbBufFlush1
  0.07mins  0.85% 76.37%   0.07mins  0.85%  runtime.(*mSpanList).remove
  0.07mins  0.81% 77.17%   0.21mins  2.46%  runtime.(*mheap).coalesce
  0.07mins  0.79% 77.96%   0.50mins  5.88%  runtime.gcWriteBarrier
  0.07mins  0.78% 78.74%   0.07mins  0.78%  runtime.nextFreeFast
  0.07mins  0.76% 79.50%   4.96mins 57.74%  runtime.mallocgc
  0.05mins  0.59% 80.09%   0.08mins  0.95%  runtime.mapaccess2_faststr
  0.05mins  0.58% 80.68%   0.05mins  0.58%  runtime.(*gcSweepBuf).pop
  0.05mins  0.54% 81.21%   0.05mins  0.54%  runtime.mapaccess1_fast64
  0.05mins  0.54% 81.75%   0.05mins  0.54%  memeqbody
  0.05mins  0.53% 82.28%   0.14mins  1.59%  runtime.(*mTreap).removeSpan
```

There is so much CPU spent on scraping targets (github.com/prometheus/prometheus/scrape.targetsFromGroup, runtime.futex), on clearing non heap pointers (runtime.memclrNoHeapPointers), finding objects in the non-heap area (runtime.scanobject), finding stack object containing a specific address (runtime.findObject) and comparing labels in time series (cmpbody, sort.doPivot, sort.InsertionsSort).

**Comment by christidis** [comment]
>I then changed targets provider from ServiceMonitor to static files using `additionalScrapeConfigs` and manually copied the targets to the `config_out` source mount dir. 
> ``` additionalScrapeConfigs:
>    - job_name: 'foo'
>      file_sd_configs:
>       - files:
>          - /etc/prometheus/config_out/targets/foo/*.json```

Also, any suggestion on how to configure and dynamically update targets from static files with prometheus-operator in order to overcome this issue is more than welcome.

**Comment by simonpasquier** [comment]
> Also, not sure if this is helpful or not but in Prometheus, under the targets page:
>  *   All targets were under a common group when using static files.
>  *  Each target was under its own group when using serviceMonitor objects. I tried using the jobLabel spec attribute but I didn't manage to group them all to one group.

The targets page shows targets grouped by `job_name`. Prometheus operator creates one scrape configuration per `endpoints` item in the ServiceMonitor while your static configuration defines only one scrape configuration.

How many namespaces do you monitor? How many targets do you end up with?

You can have a look at a few metrics to see the activity of service discovery and target updates:
* rate(prometheus_sd_kubernetes_events_total[5m])
* rate(prometheus_sd_received_updates_total[5m])
* rate(prometheus_sd_updates_total[5m])
* sum by(scrape_job) (rate(prometheus_target_scrape_pool_sync_total[5m]))

**Comment by christidis** [comment]
>Would you be able to share an example of `ServiceMonitor` as well as a snippet of the job configuration generated by the Prometheus operator?

Sure. I have the following objects for each external service.

service
```
master01 ~ $ kubectl -n prom-monitoring get svc foo-testing-app-cl02-srv01-8080 -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    ClusterName: testing-app-cl02
    DC: DC
    Role: foo
    envtype: testing
    instanceoverwrite: srv01:8080
    joboverwrite: app
  creationTimestamp: "2019-11-19T09:00:21Z"
  labels:
    ClusterName: testing-app-cl02
    DC: DC
    Role: foor
    envtype: testing
  name: foo-testing-app-cl02-srv01-8080
  namespace: prom-monitoring
  resourceVersion: "60969763"
  selfLink: /api/v1/namespaces/prom-monitoring/services/foo-testing-app-cl02-srv01-8080
  uid: 0404fab5-0aab-11ea-8325-566fd2bf0012
spec:
  clusterIP: None
  ports:
  - name: foo-testing-app-cl02-srv01-8080p
    port: 8080
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

endpoint
```
master01 ~ $ kubectl -n prom-monitoring get ep foo-testing-app-cl02-srv01-8080 -o yaml
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2019-11-19T09:00:29Z"
  name: foo-testing-app-cl02-srv01-8080
  namespace: prom-monitoring
  resourceVersion: "60969967"
  selfLink: /api/v1/namespaces/prom-monitoring/endpoints/foo-testing-app-cl02-srv01-8080
  uid: 08e520ae-0aab-11ea-8325-566fd2bf0012
subsets:
- addresses:
  - ip: 10.0.0.2
  ports:
  - name: foo-testing-app-cl02-srv01-8080p
    port: 8080
    protocol: TCP
```

servicemonitor
```
master01 ~ $ kubectl -n prom-monitoring get servicemonitor foo-testing-app-cl02-srv01-8080 -o yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: "2019-11-19T09:00:37Z"
  generation: 1
  labels:
    k8s-app: foo-testing-app-cl02-srv01-8080
    prometheus: prometheus-cl01
  name: foo-testing-app-cl02-srv01-8080
  namespace: prom-monitoring
  resourceVersion: "60970173"
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/prom-monitoring/servicemonitors/foo-testing-app-cl02-srv01-8080
  uid: 0d84092f-0aab-11ea-8325-566fd2bf0012
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: foo-testing-app-cl02-srv01-8080p
    relabelings:
    - sourceLabels:
      - __meta_kubernetes_service_annotation_instanceoverwrite
      targetLabel: instance
    - sourceLabels:
      - __meta_kubernetes_service_annotation_joboverwrite
      targetLabel: job
    - sourceLabels:
      - __meta_kubernetes_service_annotation_envtype
      targetLabel: envtype
    - sourceLabels:
      - __meta_kubernetes_service_annotation_ClusterName
      targetLabel: ClusterName
    - sourceLabels:
      - __meta_kubernetes_service_annotation_Role
      targetLabel: Role
    - sourceLabels:
      - __meta_kubernetes_service_annotation_DC
      targetLabel: DC
  namespaceSelector:
    matchNames:
    - prom-monitoring
  selector:
    app: foo-testing-app-cl02-srv01-8080
```

Prometheus operator generates the following job configuration in Prometheus
```
- job_name: prom-monitoring/foo-testing-app-cl02-srv01-8080/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - prom-monitoring
  scrape_interval: 30s
  metrics_path: /metrics
  relabel_configs:
  - action: keep
    source_labels:
    - __meta_kubernetes_endpoint_port_name
    regex: foo-testing-app-srv01-8080p
  - source_labels:
    - __meta_kubernetes_endpoint_address_target_kind
    - __meta_kubernetes_endpoint_address_target_name
    separator: ;
    regex: Node;(.*)
    replacement: ${1}
    target_label: node
  - source_labels:
    - __meta_kubernetes_endpoint_address_target_kind
    - __meta_kubernetes_endpoint_address_target_name
    separator: ;
    regex: Pod;(.*)
    replacement: ${1}
    target_label: pod
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: service
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: job
    replacement: ${1}
  - target_label: endpoint
    replacement: foo-testing-app-srv01-8080p
  - source_labels:
    - __meta_kubernetes_service_annotation_instanceoverwrite
    target_label: instance
  - source_labels:
    - __meta_kubernetes_service_annotation_joboverwrite
    target_label: job
  - source_labels:
    - __meta_kubernetes_service_annotation_envtype
    replacement: foo-testing-app-srv01-8080p
  - source_labels:
    - __meta_kubernetes_service_annotation_instanceoverwrite
    target_label: instance
  - source_labels:
    - __meta_kubernetes_service_annotation_joboverwrite
    target_label: job
  - source_labels:
    - __meta_kubernetes_service_annotation_envtype
    target_label: envtype
  - source_labels:
    - __meta_kubernetes_service_annotation_ClusterName
    target_label: ClusterName
  - source_labels:
    - __meta_kubernetes_service_annotation_Role
    target_label: Role
  - source_labels:
    - __meta_kubernetes_service_annotation_DC
    target_label: DC
```

`instanceoverwrite` is being used to relabel IP in `instance:port` field with a meaningful `hostname:port`.

>Out of curiosity, I suppose that you have a custom-made program that generates the target files for you?

Yes, I use an Ansible playbook to bootstrap and manage my targets as Kubernetes resources.

**Comment by christidis** [comment]
I have modified the logic a bit.
I am bootstrapping a single `ServiceMonitor` object for all `Service`/`Endpoints` objects. In my case, this was possible.
Now Prometheus groups the targets in a single group and the load dropped to less than 0.5 CPU.

I am closing this, however, the problem when using many `ServiceMonitor` objects is still valid.

**Comment by simonpasquier** [comment]
@christidis thanks for the heads-up and sharing the numbers with your new setup. I agree that the issue is still relevant.

**Comment by kam1kaze** [comment]
The same issue here. When I added ServiceMonitor per each Statefulset (156 targets), CPU utilization dramatically increased (from 0.8 cpu to 4 cpu). I've switched to use only one ServiceMonitor for all Statefulset service and the load has dropped back. 

![image](https://user-images.githubusercontent.com/2952868/91328399-90189c80-e7cf-11ea-9cb3-21d2f33bba3f.png)


BTW, prometheus_target_sync_length_seconds_sum metric has dropped too. WTF? 

![image](https://user-images.githubusercontent.com/2952868/91328282-5e073a80-e7cf-11ea-8605-297c5a08bf2f.png)

Looks like it's a bug, so the issue should be reopened.

Could anyone explain why does it happen?

**Comment by rbs4ba** [comment]
Also seeing the same behavior. We specifically went from 51 serviceMonitors to 1 serviceMonitor and saw the CPU drop by a factor of 10x. We can workaround it for now with just the 1 serviceMonitor, but it does feel like this should be reopened.

**Comment by brancz** [comment]
Could you take a CPU profile of the Prometheus Operator in question with the "large" number of ServiceMonitors?

**Comment by parberge** [comment]
We ran to very high memory usage when we tried with around 1000 serviceMonitor objects.

This is the docker image of the operator we used: `quay.io/prometheus-operator/prometheus-operator:v0.50.0`

**Comment by simonpasquier** [comment]
@parberge i assume that you're talking about high memory usage for Prometheus and not the operator?

**Comment by parberge** [comment]
> @parberge i assume that you're talking about high memory usage for Prometheus and not the operator?

Oh right. Yeah that's correct. I assumed it was related but yeah that might be another issue then.

**Comment by jimethn** [comment]
We have the same problem. We have about 400 servicemonitors across 3 prometheus shards, which are maxing out 15 CPU despite each shard only being responsible for about 1 million metrics. CPU profile below:

![image](https://user-images.githubusercontent.com/89885/211854522-77c26dcb-f9ff-4c08-8a66-e38a4eadd530.png)

**Comment by jimethn** [comment]
Can this issue be reopened or should I make a new one?

**Comment by jimethn** [comment]
For anyone else hitting this issue, the answer is to use [this hidden flag](https://github.com/prometheus/prometheus/pull/10634) (requires prometheus-operator >= 0.59.0)

```
kind: Prometheus
spec:
  additionalArgs:
  - name: scrape.discovery-reload-interval
    value: 30s
```

![image](https://user-images.githubusercontent.com/89885/212161484-1c651fba-8cea-422e-a3da-89aaebc97e17.png)

(pictured: big CPU reduction)
