### ISSUE TITLE
Labels on volumeClaimTemplate require explicit quoting

### ISSUE THREAD

**Issue by onitake** [coreos/prometheus-operator#2867]
**What happened?**

When deploying a Prometheus resource with a volumeClaimTemplate, any custom labels aren't quoted internally. This leads to prometheus-operator refusing to deploy, and even exit/crash with error when started while such a resource is present.

**Did you expect to see some different?**

prometheus-operator should quote label values automatically.

**How to reproduce it (as minimally and precisely as possible)**:

See Prometheus resource below.

**Environment**

* Prometheus Operator version:

    `v0.33.0`
    

* Kubernetes version information:

    `v1.16.1`
    

* Kubernetes cluster kind:

    Custom k8s distribution (based on [Kubernetes The Hard Way](https://github.com/kelseyhightower/kubernetes-the-hard-way) / current best practices)

* Manifests:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
spec:
  baseImage: quay.io/prometheus/prometheus
  version: v2.11.0
  replicas: 2
  storage:
    volumeClaimTemplate:
      metadata:
        labels:
          billed: false
      spec:
        storageClassName: nfs
        resources:
          requests:
            storage: 20Gi
```

* Prometheus Operator Logs:

```
E1118 16:46:41.838104       1 reflector.go:125] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:448: Failed to list *v1.Prometheus: v1.PrometheusList.Items: []*v1.Prometheus: v1.Prometheus.Spec: v1.PrometheusSpec.Storage: v1.StorageSpec.VolumeClaimTemplate: v1.PersistentVolumeClaim.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects " or n, but found f, error found in #10 byte of ...|"billed":false}},"sp|..., bigger context ...|meClaimTemplate":{"metadata":{"labels":{"billed":false}},"spec":{"resources":{"requests":{"storage":|...
```

**Anything else we need to know?**:

When quoting the label value as `"false"`, the deployment works.
    
It's unclear if the lack of quoting is a result of the string `false` being misinterpreted as boolean, or a general issue of missing quotes.
