### ISSUE TITLE
Bearertoken not used to scrape targets

### ISSUE THREAD

**Issue by balusarakesh** [coreos/prometheus-operator#2868]
**What happened?**
bearerTokenFile parameter not used when scrapping targets
**Did you expect to see some different?**
bearerTokenFile must be used in the authorization headers

**How to reproduce it (as minimally and precisely as possible)**:
I followed the documentation here to deploy vault monitioring with prometheus - https://medium.com/@mwieczorek/yet-another-vault-monitoring-with-prometheus-blog-post-f525c862baca

* Prometheus Operator version:
`v0.31.1`
    `quay.io/coreos/prometheus-operator:v0.31.1`

* Kubernetes version information:

    `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:38:36Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

    kops + EC2

* Manifests:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: vault
  name: vault
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
  endpoints:
    - interval: 30s
      path: /v1/sys/metrics
      params:
        format: 
          - prometheus
      port: http
      scheme: http
      scrapeTimeout: 30s
      bearerTokenFile: /etc/prometheus/config_out/.vault-token
```

* Prometheus Operator Logs:

I don't see any relevant logs for this issue

These are the logs I see in prometheus when I enable debug logging
```
level=debug ts=2019-11-18T17:56:54.883Z caller=scrape.go:920 component="scrape manager" scrape_pool=default/vault/0 target="http://172.18.27.231:8200/v1/sys/metrics?format=prometheus" msg="Scrape failed" err="server returned HTTP status 400 Bad Request"
level=debug ts=2019-11-18T17:57:09.189Z caller=scrape.go:920 component="scrape manager" scrape_pool=default/vault/0 target="http://172.18.23.16:8200/v1/sys/metrics?format=prometheus" msg="Scrape failed" err="server returned HTTP status 400 Bad Request"
```

**Comment by balusarakesh** [comment]
I've also tried with `bearerToken` parameter by setting the value as string

**Comment by balusarakesh** [comment]
```
/prometheus $ wget --header='Authorization: Bearer {TOKEN_HERE}'  http://172.18.18.0:8200/v1/sys/metrics
Connecting to 172.18.18.0:8200 (172.18.18.0:8200)
saving to 'metrics'
metrics              100% |************************************************************************************************************************************|  3804  0:00:00 ETA
'metrics' saved
/prometheus $ cat metrics
{"Timestamp":"2019-11-18 19:32:50 +0000 UTC","Gauges":[{"Name":"vault.expire.num_leases","Value":5,"Labels":{}},{"Name":"vault.runtime.alloc_bytes","Value":10974728,"Labels":{}},{"Name":"vault.runtime.free_count","Value":332709820,"Labels":{}},{"Name":"vault.runtime.heap_objects","Value":127931,"Labels":{}},{"Name":"vault.runtime.malloc_count","Value":332837760,"Labels":{}},{"Name":"vault.runtime.num_goroutines","Value":40,"Labels":{}},{"Name":"vault.runtime.sys_bytes","Value":72810744,"Labels":{}},{"Name":"vault.runtime.total_gc_pause_ns","Value":177744140,"Labels":{}},{"Name":"vault.runtime.total_gc_runs","Value":4311,"Labels":{}}],"Points":[],"Counters":[{"Name":"vault.audit.log_request_failure","Count":3,"Rate":0,"Sum":0,"Min":0,"Max":0,"Mean":0,"Stddev":0,"Labels":{}},{"Name":"vault.audit.log_response_failure","Count":3,"Rate":0,"Sum":0,"Min":0,"Max":0,"Mean":0,"Stddev":0,"Labels":{}}],"Samples":[{"Name":"vault.audit.file/.log_request","Count":3,"Rate":0.0303336001932621,"Sum":0.303336001932621,"Min":0.09005700051784515,"Max":0.11613599956035614,"Mean":0.101112000644207,"Stddev":0.013484927189637399,"Labels":{}},{"Name":"vault.audit.file/.log_response","Count":3,"Rate":0.021696600317955016,"Sum":0.21696600317955017,"Min":0.07181700319051743,"Max":0.07284999638795853,"Mean":0.07232200105985005,"Stddev":0.0005168804492554416,"Labels":{}},{"Name":"vault.audit.log_request","Count":3,"Rate":0.03361479938030243,"Sum":0.3361479938030243,"Min":0.0997299998998642,"Max":0.12788799405097961,"Mean":0.11204933126767476,"Stddev":0.014405118148166167,"Labels":{}},{"Name":"vault.audit.log_response","Count":3,"Rate":0.023918500542640685,"Sum":0.23918500542640686,"Min":0.07892200350761414,"Max":0.08036699891090393,"Mean":0.07972833514213562,"Stddev":0.0007369445798612183,"Labels":{}},{"Name":"vault.barrier.get","Count":7,"Rate":0.021520200092345475,"Sum":0.21520200092345476,"Min":0.012885999865829945,"Max":0.049674998968839645,"Mean":0.030743142989064966,"Stddev":0.016484250757804866,"Labels":{}},{"Name":"vault.core.check_token","Count":3,"Rate":0.14637649655342103,"Sum":1.4637649655342102,"Min":0.4302220046520233,"Max":0.5466349720954895,"Mean":0.48792165517807007,"Stddev":0.05821310322352802,"Labels":{}},{"Name":"vault.core.fetch_acl_and_token","Count":3,"Rate":0.14314689934253694,"Sum":1.4314689934253693,"Min":0.4215349853038788,"Max":0.5340549945831299,"Mean":0.47715633114178974,"Stddev":0.05627087858960184,"Labels":{}},{"Name":"vault.core.handle_request","Count":3,"Rate":0.19816790223121644,"Sum":1.9816790223121643,"Min":0.5883790254592896,"Max":0.7193819880485535,"Mean":0.6605596741040548,"Stddev":0.06651524547999713,"Labels":{}},{"Name":"vault.expire.fetch-lease-times","Count":3,"Rate":0.0005019999924115836,"Sum":0.005019999924115837,"Min":0.0015030000358819962,"Max":0.001979999942705035,"Mean":0.0016733333080386121,"Stddev":0.00026612462696492373,"Labels":{}},{"Name":"vault.expire.fetch-lease-times-by-token","Count":3,"Rate":0.003106199949979782,"Sum":0.03106199949979782,"Min":0.010173999704420567,"Max":0.01056899968534708,"Mean":0.01035399983326594,"Stddev":0.00019981236624123572,"Labels":{}},{"Name":"vault.policy.get_policy","Count":6,"Rate":0.0018434000201523304,"Sum":0.018434000201523304,"Min":0.0016120000509545207,"Max":0.00521400012075901,"Mean":0.003072333366920551,"Stddev":0.0015284751765389216,"Labels":{}},{"Name":"vault.route.read.sys-","Count":3,"Rate":0.014147599786520004,"Sum":0.14147599786520004,"Min":0.04553699865937233,"Max":0.0491349995136261,"Mean":0.04715866595506668,"Stddev":0.0018250325080156017,"Labels":{}},{"Name":"vault.token.lookup","Count":3,"Rate":0.049469698965549466,"Sum":0.4946969896554947,"Min":0.16008299589157104,"Max":0.17430999875068665,"Mean":0.16489899655183157,"Stddev":0.00815091601865003,"Labels":{}}]}
```

**Comment by simonpasquier** [comment]
You have at least 2 issues here:
* the endpoint returns a `400 Bad Request` response to Prometheus (see log `server returned HTTP status 400 Bad Request`) so authentication isn't the issue.
* the endpoint doesn't return metrics using  Prometheus exposition format. Even if Prometheus was scraping the endpoint successfully, it would fail to parse the result.

**Comment by balusarakesh** [comment]
yeah, you are right, the metrics are returned in JSON format even though `?format=prometheus` is appended to the URL

**Comment by balusarakesh** [comment]
@simonpasquier please take a look at this - https://www.vaultproject.io/docs/configuration/telemetry.html
```
Vault does not use the default Prometheus path, so Prometheus must be configured as follows. Note that using ?format=prometheus in the path won't work as "?" will be escaped, so it must be specified as a parameter. Additionally a Vault token is required to access /v1/sys/metrics.
```
but looks like prometheus-operator is adding `?format=prometheus` to the URL which doesn't seem to work according to vault. Is there any other way we can fix this?

**Comment by simonpasquier** [comment]
> but looks like prometheus-operator is adding ?format=prometheus to the URL which doesn't seem to work according to vault.

No the Prometheus operator configures Prometheus as described in the Vault documentation using the `params` field. Try checking the Vault logs. If it doesn't help, you'd have to use tcpdump (or similar tool).

**Comment by riuvshyn** [comment]
@balusarakesh 
try to use `path: /v1/sys/metrics?format=prometheus` in `ServiceMonitor`

**Comment by riuvshyn** [comment]
I can get it to work with pure prom using this config:

```
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: vault
    static_configs:
      - targets: ["vault:8200"]
    metrics_path: /v1/sys/metrics
    scheme: https
    params:
      format: ["prometheus"]
    bearer_token: <TOKEN>
```
