### ISSUE TITLE
objectStorageConfig not working in ThanosSpec

### ISSUE THREAD

**Issue by boxuan666** [coreos/prometheus-operator#2869]
operator version: v0.33.0

my promethues config like this:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  generation: 1
  labels:
    prometheus: app
  name: app
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  nodeSelector:
    kubernetes.io/os: linux
  replicas: 1
  resources:
    requests:
      cpu: "4"
      memory: 32Gi
  retention: 30d
  ruleSelector:
    matchLabels:
      prometheus: app
  secrets:
  - kube-etcd-client-certs
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  thanos:
    baseImage: thanosio/thanos
    version: v0.8.1
    objectStorageConfig:
      key: thanos.yaml
      name: thanos-objstore-config
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  version: v2.13.1
```

but there is not objstore-config in yaml generic by operator 
```
  - args:
    - sidecar
    - --prometheus.url=http://localhost:9090/
    - --tsdb.path=/prometheus
    - --grpc-address=[$(POD_IP)]:10901
    - --http-address=[$(POD_IP)]:10902
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    image: thanosio/thanos:v0.8.1
    imagePullPolicy: IfNotPresent
    name: thanos-sidecar
    ports:
    - containerPort: 10902
      name: http
      protocol: TCP
    - containerPort: 10901
      name: grpc
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /prometheus
      name: prometheus-app-db
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: prometheus-k8s-token-vsz62
      readOnly: true
```
why ?

**Comment by boxuan666** [comment]
@brancz do u know any about this?

**Comment by boxuan666** [comment]
@LiliC

**Comment by boxuan666** [comment]
There is still a question, can promtheus-operator add domain name binding?
like is
```
hostAliases:
- hostnames:
  - my.fqdn.com
  ip: 10.15.4.119
```

**Comment by abursavich** [comment]
@boxuan666, repeating what I said in the other thread: I don't see anything wrong with the thanos config you posted, but I'm unable to reproduce the issue.

My next steps would be to confirm that your Prometheus StatefulSet is actually synced with your Prometheus custom resource object. Check the prometheus-operator logs and make sure there isn't an RBAC issue preventing it from updating... Those kind of things.

**Comment by boxuan666** [comment]
@abursavich

**Comment by abursavich** [comment]
I could not reproduce it with v0.33.0.

**Comment by boxuan666** [comment]
@abursavich 
I found the root of the problem. Only the first prometheus configuration thanos ojbstore parameters will take effect, the second prometheus seems to ignore this parameter. Do you know why?

**Comment by abursavich** [comment]
I'm not sure I understand. Please provide steps to reproduce if you have them.

**Comment by boxuan666** [comment]
now in my k8s cluster have only one promethues named main
```
kubectl -n monitoring get prometheus
NAME   AGE
main   29d
```
i'm addition thanos config in prometheus-main (by prometheus-operator) is take effect. 
```
      name: thanos-sidecar
      - args:
        - sidecar
        - --prometheus.url=http://localhost:9090/
        - --tsdb.path=/prometheus
        - --grpc-address=[$(POD_IP)]:10901
        - --http-address=[$(POD_IP)]:10902
        - --objstore.config=$(OBJSTORE_CONFIG)
```
then i create new prometheus named app. the yaml config like is:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  generation: 1
  labels:
    prometheus: app
  name: app
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
      cpu: "4"
      memory: 32Gi
  replicas: 1
  retention: 30d
  ruleSelector:
    matchLabels:
      prometheus: app
  secrets:
  - kube-etcd-client-certs
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  thanos:
    baseImage: thanosio/thanos
    objectStorageConfig:
      key: thanos.yaml
      name: thanos-objstore-config
    version: v0.8.1
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  version: v2.13.1
```
after i creating second prometheus in my cluster. 
promtheus-app is not generic thanos ojbstore config in yaml, like is
```
      name: thanos-sidecar
      - args:
        - sidecar
        - --prometheus.url=http://localhost:9090/
        - --tsdb.path=/prometheus
        - --grpc-address=[$(POD_IP)]:10901
        - --http-address=[$(POD_IP)]:10902

there is lost config --objstore.config=$(OBJSTORE_CONFIG) 
```
my questions is: why `objectStorageConfig` not working in prometheus-app which is second create prometheus
