### ISSUE TITLE
Unable to View/Create Graphs in UI

### ISSUE THREAD

**Issue by alexanderbez** [coreos/prometheus-operator#287]
**What did you do?**
Installed Prometheus via `prometheus-operator` using the docs found [here](https://coreos.com/operators/prometheus/docs/latest/user-guides/cluster-monitoring.html).

**What did you expect to see?**
A working and functional Prometheus setup with Alertmanager and a working UI for each.

**What did you see instead? Under which circumstances?**
Both components seem to be functional and operating correctly as I can see all my exposed targets (kubelets, nodes, etc...). However, for the Prom dashboard, there seems to be an issue loading one of the assets.

Note, I'm browsing to this via the Kubernetes API forwarding to the internal service. And the service is of type `NodePort`.
![](https://d3dr1ze7164817.cloudfront.net/items/0P391F2F2M3O260y1Q2U/Image%202017-04-13%20at%209.11.21%20AM.png?X-CloudApp-Visitor-Id=2736136&v=865a5851)

**Environment**
* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T23:37:53Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.6", GitCommit:"114f8911f9597be669a747ab72787e0bd74c9359", GitTreeState:"clean", BuildDate:"2017-03-28T13:36:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
Single master/private topology in AWS installed via `kops`

* Manifests:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: k8s
```

* Prometheus Operator Logs:
Nothing alarming.
