### ISSUE TITLE
Cross namespace monitoring using Prometheus operator

### ISSUE THREAD

**Issue by rajat23495** [coreos/prometheus-operator#2888]
**What did you do?**
I created a service monitor in devo namespace and assigned some cluster level permissions in prometheus cluster role file to fetch metrics.
My metrics are exposed on /prometheus path
When i went into one of the containers and used curl pod-ip:8080/prometheus it showed 401 unauthorised error.
Am i missing something?
**Did you expect to see some different?**
I expected to see my metrics and some targets available as i can see for other pods for whom servicemonitors were already present like grafana.
PFA
<img width="1669" alt="Screenshot 2019-11-28 at 7 48 15 PM" src="https://user-images.githubusercontent.com/52070535/69814108-88fd3780-1219-11ea-8191-828ce9907413.png">
<img width="785" alt="Screenshot 2019-11-28 at 8 01 19 PM" src="https://user-images.githubusercontent.com/52070535/69814306-eb563800-1219-11ea-9dc9-0c944e227d66.png">

* Kubernetes version information:

    `kubectl version`
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}

I am attaching my servicemonitor file
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-svc-monitor
  namespace: monitoring
spec:
  endpoints:
    - port: api
      scheme: http
      path: '/prometheus'
      interval: 15s
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: api

```
