### ISSUE TITLE
prometheus-operator via OperatorHub installation only watches a single namespace

### ISSUE THREAD

**Issue by btleedev** [coreos/prometheus-operator#2892]
**What happened?**
I'm not sure if this is the right place to post this, but I believe ownership of the operator on OperatorHub.io lies here. 

As per https://github.com/coreos/prometheus-operator/blob/v0.32.0/bundle.yaml and https://github.com/coreos/prometheus-operator/blob/v0.32.0/Documentation/user-guides/getting-started.md, it seems the default behavior for the prometheus operator is to deploy with a ClusterRole and a ClusterRoleBinding. 

Installing the operator with `kubectl create -f https://operatorhub.io/install/prometheus.yaml` seems to instead create a Role and a RoleBinding.

```
kubectl get role -n my-prometheus
NAME                              AGE
prometheusoperator.0.32.0-pxzdl   39m
prometheusoperator.0.32.0-tjblb   39m
```
```
kubectl get rolebinding -n my-prometheus
NAME                                                        AGE
prometheusoperator.0.32.0-pxzdl-prometheus-operator-7wt6r   38m
prometheusoperator.0.32.0-tjblb-prometheus-k8s-g7jb2        38m
```

**Did you expect to see some different?**
I'd like to have the operator be able to watch the whole cluster so I can deploy prometheus instances in several namespaces. Thus I think Role and RoleBinding should be changed to ClusterRole and ClusterRoleBinding.

**How to reproduce it (as minimally and precisely as possible)**:

https://operatorhub.io/operator/prometheus

**Environment**

macOS Mojave 10.14.6, docker desktop 2.1.0.5

* Prometheus Operator version:

    `quay.io/coreos/prometheus-operator@sha256:ed3ec0597c2d5b7102a7f62c661a23d8e4b34d910693fc23fd40bfb1d9404dcf`
    

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}`
    

* Kubernetes cluster kind:

    Default cluster from docker desktop.

**Comment by brancz** [comment]
I believe this is just a matter of allowing all namespaces to be watched with the catalog entry. The Prometheus Operator itself perfectly supports this, just the catalog entry needs to be adapted if this is not already possible.

**Comment by David-Igou** [comment]
This can be done, but it's a little hard to find examples (I worked through this on Openshift 4.2):

First off, for your `prometheus` to scrape services in other namespaces, it needs permission to do that:

Kubernetes:

Extracting the cluster roles out of the bundle.yml from this repo and kubectl applying should be enough

Openshift:

```
oc adm policy add-cluster-role-to-user view system:serviceaccount:application-monitoring:prometheus-k8s
```

Doesn't have to be cluster scoped, though:

```
oc adm policy add-role-to-user view system:serviceaccount:application-monitoring:prometheus-k8s -n nginx-website
```

is a little cleaner.

This is a starting point, but if you want the operator to pick up servicemonitors from other namespaces:

(Once again, done on Openshift)

`oc get operatorgroup, oc edit operatorgroup`

You will see the targetNamespaces section, add your new namespace:

```
  targetNamespaces:
  - application-monitoring
  - nginx-website
```

You'll then have to edit spec.installModes in the ClusterServiceVersion, setting MultiNamespace from `false` to `true`

`oc edit csv prometheusoperator.0.32.0`

```
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
```

I had to restart (delete) the operator pod after this.

I don't have a regular k8s cluster with the OLM to verify this on, but hopefully this helps

**Comment by brancz** [comment]
The ClusterRole in the bundle is just for the prometheus operator, not for the Prometheus servers it might deploy. We're applying the principle of least privilege here. We expect users that want their services monitored to explicitly grant Prometheus access to that namespace.

Note that the OLM team has deprecated the multi-namespace option, for those inconvenience reasons and more OpenShift will be shipping application monitoring starting 4.3 as an out of the box (starting as tech preview) feature where the user doesn't need to setup the Prometheus stack at all and instead just provision the ServiceMonitor and PrometheusRule objects self-service style.

**Comment by David-Igou** [comment]
If the OLM is depreciating the multi-namespace option, how will users not running on Openshift achieve this behaviour?

**Comment by brancz** [comment]
I think it would be best to solve it outside of OLM just like OpenShift is.

**Comment by btleedev** [comment]
Closing this issue. Was able to use @David-Igou steps above to patch the csv with the following command against Kubernetes.

`kubectl patch csv prometheusoperator.0.32.0 --type=merge -p '{"spec":{"installModes":[{"supported":true, "type":"OwnNamespace"},{"supported":true, "type":"SingleNamespace"},{"supported":true, "type":"MultiNamespace"},{"supported":true, "type":"AllNamespaces"}]}}'`

**Comment by brancz** [comment]
Note on open shift the catalog has allnamespaces intentionally not available because that would clash with the out of the box included cluster monitoring prometheus operator. Doing this will result in a cluster with unknown and unexpected state.

**Comment by fdammeke** [comment]
Bumped into this issue also on OpenShift, for the record, if you don't want to conflict with the built-in OpenShift.

Prometheus, you can patch the `ClusterServiceVersion` to allow `installModes` -> `MultiNamespace`
```
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: prometheusoperator.0.56.3
  namespace: dedicated-prometheus
spec:
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
```

Create a new `OperatorGroup` or patch the existing one in the namespace where you activate the Prometheus Subscription
```
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: dedicated-prometheus
  namespace: dedicated-prometheus
spec:
  selector:
    matchLabels:
      dedicated.monitoring/managed: 'true'
  upgradeStrategy: Default
```

Ensure that all the `Namespace` that need to be monitored have the label attached and you're set.
```
apiVersion: v1
kind: Namespace
metadata:
  name: dummy-exporter
  labels:
    dedicated.monitoring/managed: 'true'
```

This is basically the same way Red Hat built-in Prometheus works.
