### ISSUE TITLE
ServiceMonitor error: the server does not allow access to the requested resource

### ISSUE THREAD

**Issue by klinakuf** [coreos/prometheus-operator#290]
**What did you do?**

- I deployed the bundle.yaml in the default namespace. 
- I deployed the Prometheus TPR:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: prometheus-mqs
  labels:
    prometheus: mqs
spec:
  # Define that all ServiceMonitor TPRs with the label `tier = frontend` should be included
  # into the server's configuration.
  serviceMonitorSelector:
      matchLabels:
        queue: rabbit
```
- When I deploy the **ServiceMonitor** then inside the logs of Prometheus pod I see the following error: 
```
2017-04-16T21:55:14.749575321Z time="2017-04-16T21:55:14Z" level=info msg="Using pod service account via in-cluster config" source="kubernetes.go:94" 
2017-04-16T21:55:14.793099473Z time="2017-04-16T21:55:14Z" level=error msg="github.com/prometheus/prometheus/vendor/k8s.io/client-go/1.5/tools/cache/reflector.go:109: Failed to list *v1.Endpoints: the server does not allow access to the requested resource (get endpoints)" component="kube_client_runtime" source="kubernetes.go:73" 
```

Is there something extra to be configured regarding the ClusterRoles and ServiceAccounts?

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.1", GitCommit:"176eb0e509a255dd520de135cda31096f8796be5", GitTreeState:"clean", BuildDate:"2017-04-06T20:00:18Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

kubeadm
