### ISSUE TITLE
Support more thanos sidecar args

### ISSUE THREAD

**Issue by yeya24** [coreos/prometheus-operator#2900]
**What is missing?**
In current thanos spec,  I don't find a place to configure thanos sidecar args. I want to add more additional args like log.level=debug or sth else. 

I think adding an `additionalArgs []string` in  thanos spec is enough for this feature. WDYT @brancz 

**Why do we need it?**

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

**Anything else we need to know?**:

**Comment by yeya24** [comment]
If this feature makes sense, I think I can file a PR for it.

**Comment by brancz** [comment]
You can already modify arbitrary things about the flags by specifying a container with the same container name as the sidecar. That said, log level is propagated I believe so if you set debug logs in the top level spec, then the thanos sidecar will also be in debug log level.

**Comment by yeya24** [comment]
@brancz  Thanks, the log level works.

**Comment by brancz** [comment]
Can we close this?

**Comment by yeya24** [comment]
How to specify other args like --shipper.upload-compacted? If I add it in the yaml, it will overwrite. Did I miss something? Sorry, I am not sure if I misunderstood your answer.
``` yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  containers:
  - name: thanos-sidecar
     args: ["--shipper.upload-compacted"]
  thanos:
    version: v0.8.1
    objectStorageConfig:
      key: thanos.yaml
      name: thanos-objectstorage
  baseImage: quay.io/prometheus/prometheus
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  logLevel: debug
  serviceAccountName: prometheus-k8s
  version: v2.14.0
````
