### ISSUE TITLE
AlertManager unable to start - CrashLoopBackOff ! 

### ISSUE THREAD

**Issue by agrajm** [coreos/prometheus-operator#2902]
**What did you do?**
Installed Prometheus & Grafana successfully but when trying to use AlertManager - getting **CrashLoopBackOff** error. 
AlertManager.yaml looks like

```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager
  labels:
    app: strimzi
spec:
  replicas: 1
  logLevel: debug
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  labels:
    app: strimzi
spec:
  ports:
    - name: alertmanager
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    alertmanager: alertmanager
  type: ClusterIP
```

Created a secret with name `alertmanager-alertmanager` before deploying the above alert-manager. Example config file used for the secret looks like

```
global:
  resolve_timeout: 5m
route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: email
receivers:
- name: email
  email_configs:
  - to: agraj.mng@gmail.com
    text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
```
```
kubectl create secret generic alertmanager-alertmanager --from-file=alert-manager-config-email-reciever.yaml -n monitoring
```

Now when I deploy AlertManager using the above yaml, it always fails. Changing loglevel to debug gives:
```
$kubectl logs alertmanager-alertmanager-0 -c alertmanager
level=info ts=2019-12-09T03:47:51.029909615Z caller=main.go:140 msg="Starting Alertmanager" version="(version=0.17.0, branch=HEAD, revision=c7551cd75c414dc81df027f691e2eb21d4fd85b2)"
level=info ts=2019-12-09T03:47:51.029967315Z caller=main.go:141 build_context="(go=go1.12.4, user=root@932a86a52b76, date=20190503-09:10:07)"
level=debug ts=2019-12-09T03:47:51.049892059Z caller=cluster.go:149 component=cluster msg="resolved peers to following addresses" peers=alertmanager-alertmanager-0.alertmanager-operated.monitoring.svc:9094
level=debug ts=2019-12-09T03:47:51.050436861Z caller=delegate.go:213 component=cluster received=NotifyJoin node=01DVMCAFM97M7BBXTMTR2FHG3P addr=10.244.1.20:9094
level=debug ts=2019-12-09T03:47:51.251421509Z caller=cluster.go:304 component=cluster memberlist="2019/12/09 03:47:51 [WARN] memberlist: Failed to resolve alertmanager-alertmanager-0.alertmanager-operated.monitoring.svc:9094: lookup alertmanager-alertmanager-0.alertmanager-operated.monitoring.svc on 10.0.0.10:53: no such host\n"
level=warn ts=2019-12-09T03:47:51.251455609Z caller=cluster.go:226 component=cluster msg="failed to join cluster" err="1 error occurred:\n\t* Failed to resolve alertmanager-alertmanager-0.alertmanager-operated.monitoring.svc:9094: lookup alertmanager-alertmanager-0.alertmanager-operated.monitoring.svc on 10.0.0.10:53: no such host\n\n"     
level=info ts=2019-12-09T03:47:51.251489409Z caller=cluster.go:228 component=cluster msg="will retry joining cluster every 10s"
level=warn ts=2019-12-09T03:47:51.251523309Z caller=main.go:230 msg="unable to join gossip mesh" err="1 error occurred:\n\t* Failed to resolve alertmanager-alertmanager-0.alertmanager-operated.monitoring.svc:9094: lookup alertmanager-alertmanager-0.alertmanager-operated.monitoring.svc on 10.0.0.10:53: no such host\n\n"
level=info ts=2019-12-09T03:47:51.25176181Z caller=cluster.go:613 component=cluster msg="Waiting for gossip to settle..." interval=2s
level=info ts=2019-12-09T03:47:51.279822672Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=error ts=2019-12-09T03:47:51.279985273Z caller=coordinator.go:124 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="open /etc/alertmanager/config/alertmanager.yaml: no such file or directory"
level=debug ts=2019-12-09T03:47:51.280056673Z caller=cluster.go:529 component=cluster msg="leaving cluster"
level=debug ts=2019-12-09T03:47:51.280091773Z caller=delegate.go:219 component=cluster received=NotifyLeave node=01DVMCAFM97M7BBXTMTR2FHG3P addr=10.244.1.20:9094
level=info ts=2019-12-09T03:47:51.280200973Z caller=cluster.go:622 component=cluster msg="gossip not settled but continuing anyway" polls=0 elapsed=28.314663ms
level=debug ts=2019-12-09T03:47:51.280304073Z caller=cluster.go:482 component=cluster msg="peer left" peer=01DVMCAFM97M7BBXTMTR2FHG3P
level=debug ts=2019-12-09T03:47:51.280359973Z caller=silence.go:348 component=silences msg="Running maintenance"
level=debug ts=2019-12-09T03:47:51.280329273Z caller=nflog.go:334 component=nflog msg="Running maintenance"
level=debug ts=2019-12-09T03:47:51.297337311Z caller=silence.go:350 component=silences msg="Maintenance done" duration=16.977538ms size=0
level=debug ts=2019-12-09T03:47:51.305237929Z caller=nflog.go:336 component=nflog msg="Maintenance done" duration=24.908156ms size=0
```

* Prometheus Operator version:

```
0.34.0
```

* Kubernetes version information:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"524c3a1238422529d62f8e49506df658fa9c8b8c", GitTreeState:"clean", BuildDate:"2019-11-14T05:26:24Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

cc @brancz @simonpasquier @mxinden please let me know if you need more details and help in resolving this !
