### ISSUE TITLE
RuleSelector doesn't work with no ServiceMonitor selector, custom configurations broken

### ISSUE THREAD

**Issue by snarlysodboxer** [coreos/prometheus-operator#291]
**What did you do?**
I defined the following Prometheus TPR without a defined `ServiceMonitor` selector:
```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: custom
spec:
  version: v1.5.2
  replicas: 2
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: custom
```
I created the following secret, (relevant parts:)
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-custom
data:
  prometheus.yaml: '<base64 encoded config>'
```
I created the following configMap (again, relevant parts):
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-rulefiles-custom
  labels:
    role: prometheus-rulefiles
    prometheus: custom
data:
  up.rules: |-
    ALERT BackendPrometheusDown
      IF up{job="backend-prometheus"} == 0
      FOR 1m
      LABELS { severity = "page" }
      ANNOTATIONS {
        summary = "Instance {{ $labels.instance }} down",
        description = "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute",
      }
```
I then applied these with `kubectl create -f prometheus.yml -f configMap.yml -f secrets.yml`.

**What did you expect to see?**
Visiting the prometheus's UI, I expected to see it configured with my custom configuration and rules.

**What did you see instead? Under which circumstances?**
Initially, I saw empty configurations in `/config` and `/rules`, and I saw `Rule files updated` in the config-reloader container logs.

However, if I `kubectl replace -f secrets.yml`, the configuration gets loaded and shows up in `/config`, but `/rules` is still empty.
If I `kubectl replace -f configMap.yml`, nothing changes.

From a fresh start, if I `kubectl create -f configMap.yml -f secrets.yml`, and then `kubectl create -f prometheus.yml`, I see the following in the config-reloader container logs, and again, my configuration is in `/config` in the UI, but `/rules` is empty:
```
Updating rule files failed." err="open /etc/prometheus/config/configmaps.json: no such file or directory
```

**Environment**
`quay.io/coreos/prometheus-operator:v0.8.1`

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.6", GitCommit:"114f8911f9597be669a747ab72787e0bd74c9359", GitTreeState:"clean", BuildDate:"2017-03-28T13:54:20Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.6", GitCommit:"114f8911f9597be669a747ab72787e0bd74c9359", GitTreeState:"clean", BuildDate:"2017-03-28T13:36:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	kops on AWS

* Prometheus Operator Logs:
All normal.
Please let me know if there's any additional info I can provide.

Thanks! :)

**Comment by fabxc** [comment]
The reason for this is, that we initially wanted a way for users to only use the Prometheus TPR but define scrape configs themselves. For some advanced use cases that likely will always be necessary and it especially was in the beginning, when the operator didn't cover Alertmanager discovery or rule file includes at all.

We just took existance of a service monitor selector as a signal whether or not to generarte a config. This approach obviously did not age well as we added more config generation capabilities. 

Frankly, I'm still not quite sure how to address this. We can just make it more explicit by having a `generateConfig` boolean in the Prometheus TPR. In your case, you'd just get empty scrape configs but the rest would be generated as expected.  
That does not cover users though, who want to generate their own scrape configs but still use rule file selection and Alertmanger discovery as generated by the operator.

In general, what is your use case here? If you are not monitoring anything, including rules does not buy you much for a production setup, no?

**Comment by snarlysodboxer** [comment]
We have legacy external services that are not in our k8s cluster and therefore can't be selected by a `serviceMonitor` selector. Thus, our need is to manually configure both rules and scrape configs in one of our `prometheus` setups. (Which I named "custom".)

This was working well in prometheus-operator v0.4.0, all I had to do was not define a `serviceMonitor` selector in my `prometheus`, and manually define **properly named** `configMap`s for scrape configs and rule files. promethues-operator would then load these configs into the pods.

I thought that worked well, but being more explicit would be fine too.

**Comment by fabxc** [comment]
Generally, have you considered creating Kubernetes services and manually populating their endpoints so they can be treated as any other service and thereby integrate with ServiceMonitors as usual?

What you did in operator v0.4.0 should still work. Just that you won't be able to make use of the `ruleSelector` as it's not feasible to do a mix of user-provided configs and auto-generated ones.

**Comment by snarlysodboxer** [comment]
@fabxc That's a good idea about manually creating static services that could then be picked up by a `ServiceMonitor`. I think I'll do that, thanks!

Re: doing the same thing as in `v0.4.0`, I just tried that, by creating a `configMap` named `prometheus-rulefiles-custom` (named after the ones I see created by my non-custom prometheus-operator setups.) No matter what order I `kubectl create` things  in, the rules do not get loaded. Only the scrape configs get loaded, and then only if I create them before creating the `prometheus` TPR.

I noticed in my prometheus-operator auto-generate secrets (that contain the scrape configs), there's a second piece of data `configmaps.json` which is added, containing data like `{"items":[{"key":"monitoring/prometheus-rulefiles-frontend","checksum":"9bd5c9BLAHBLAHBLAH"}]}`. I tried adding this data to my manually created `prometheus-custom` secret without the checksum, (as I didn't know how to get that,) and it still doesn't fix the problem.

I can imagine some, including possibly my future self, may still want to be able to use custom configurations, but my immediate problem is solved with the idea of using manually configured k8s `service`s + `serviceMonitor` selectors.

**Comment by brancz** [comment]
@snarlysodboxer to clear up what's happening here is that the Prometheus Operator and the [prometheus-config-reloader sidecar](https://github.com/coreos/prometheus-operator/tree/master/contrib/prometheus-config-reloader) we developed have a contract. The Prometheus Operator (re-)generates the configuration for the Prometheus instances based on the ConfigMaps it is able to find with the specified label selector. It then writes the names of those ConfigMaps into the Secret used for configuring Prometheus, this is the `configmaps.json` you found. Depending on how many configmaps the Prometheus Operator found it generates something like this in to the Prometheus configuration:

```
rule_files:
- /etc/prometheus/rules/rules-0/*
- /etc/prometheus/rules/rules-1/*
- /etc/prometheus/rules/rules-2/*
...
```

The sidecar then retrieves the ConfigMaps specified in the `configmaps.json` file and writes them into the directories as stated in the generated configuration.

The reason why we did this is to allow more dynamic reconfiguration without having to re-deploy the entire Pod as otherwise we have to mount the ConfigMaps into the Pods which cannot be dynamically added/removed. In addition to that the PodTemplate of the StatefulSet cannot be modified after creation, which makes this even more difficult.

What this means in terms of a solution for you is that if you know the number of rule configmaps you want to use you can just follow the convention the Prometheus Operator and config-reloader have and it should work.

Additionally it might be worth replacing the `rules-{number}` scheme with the actual configmap name, as I think every configmap name is a valid directory name, that should work for us, just like we did with mounting custom secrets. Wdyt @fabxc @mxinden ?

**Comment by snarlysodboxer** [comment]
@brancz: Thanks! You're right, that worked. I created a secret named `prometheus-custom` with data like:
```yaml
data:
  configmaps.json: 'BLAHBLAH' # `echo -n '{"items":[{"key":"monitoring/prometheus-rulefiles-custom"}]}' | base64`
  prometheus.yaml: 'BLAHBLAH'
```
with:
```yaml
rule_files:
- /etc/prometheus/rules/rules-0/*.rules
```
in the `prometheus.yaml`, and it worked. I have no `RuleSelector` and no `ServiceMonitor` defined in the `prometheus` TPR, and my rules `configMap` is named `prometheus-rulefiles-custom`.

There are two caveats, 1) the `configMap` and `secret` must be created _before_ creating the `prometheus` TPR or it won't work, and 2) when you delete the `prometheus` TPR the `secret` gets deleted as well, so you have to remember to recreate it before recreating the `prometheus` if that's your plan.
