### ISSUE TITLE
PodMonitor doesn't working on operator version 0.34.0

### ISSUE THREAD

**Issue by betorvs** [coreos/prometheus-operator#2910]
**What did you do?**

I tried to created a podMonitor in a different namespace, but I cannot find anything in prometheus UI. I looked in Targets/Service Discovery. I tried prometheus config itself. 

Any ideas why I cannot scrape metrics from a pod using podMonitor?

**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:

prometheus-operator: quay.io/coreos/prometheus-operator:v0.34.0
prometheus: quay.io/prometheus/prometheus:v2.12.0

* Kubernetes version information:

v1.14.9

* Kubernetes cluster kind:

kops

* Manifests:

podMonitor.yaml:
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:   
  name: pod-monitor
  namespace: test
  labels:
     app: staging
spec:
  jobLabel: pod-monitor
  selector:
    matchLabels:
      app: staging
      tier: fe
  podMetricsEndpoints:
  - interval: 15s
    path: /metrics
    port: "10002" 
```

And created these roles:
```
  apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: prometheus-k8s
    namespace: test
  rules:
  - apiGroups:
    - ""
    resources:
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
    - watch
```

These roleBinding:
```
  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: prometheus-k8s
    namespace: test
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: prometheus-k8s
  subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: monitoring
```

* Prometheus Operator Logs:

```
level=info ts=2019-12-12T14:14:35.114754885Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
```

**Anything else we need to know?**:

I used kube-prometheus to install prometheus-operator: https://github.com/coreos/kube-prometheus
