### ISSUE TITLE
Default prometheus-operator deployment spec invalid

### ISSUE THREAD

**Issue by davisford** [coreos/prometheus-operator#2919]
**What happened?**

Trying to deploy prometheus-operator -- k8s returns an error:

```
The Deployment "prometheus-operator" is invalid: 

spec.selector: Invalid value: 
    v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"controller", "app.kubernetes.io/name":"prometheus-operator", "domain":"prometheus"}, 
    
MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

I'm using the [same yaml](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md#example-prometheus-operator-manifest) you have in your example / getting started:

Here it is:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: v0.34.0
  name: prometheus-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: prometheus-operator
        app.kubernetes.io/version: v0.34.0
    spec:
      containers:
        - args:
            - --kubelet-service=kube-system/kubelet
            - --logtostderr=true
            - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
            - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.34.0
          image: quay.io/coreos/prometheus-operator:v0.34.0
          name: prometheus-operator
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator
```

The only _minor_ difference is I've removed the `namespace` b/c I use `Kustomize` to override the namespace and set it to the value `monitoring`.

**Did you expect to see some different?**

Yes, expected it to deploy without an error.  The bizarre thing is that it still spun up an operator....logs are below.

**How to reproduce it (as minimally and precisely as possible)**:

Try to deploy that yaml above

**Environment**

EKS

* Prometheus Operator version:

v0.34.0

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

```
$ kc version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b8860f", GitCommit:"b8860f6c40640897e52c143f1b9f011a503d6e46", GitTreeState:"clean", BuildDate:"2019-11-25T00:55:38Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

    Terraform VPC/EKS modules

* Manifests:

See above

* Prometheus Operator Logs:

```
ts=2019-12-18T16:38:10.40184824Z caller=main.go:199 msg="Starting Prometheus Operator version '0.34.0'."
ts=2019-12-18T16:38:10.404806136Z caller=main.go:96 msg="Staring insecure server on :8080"
level=info ts=2019-12-18T16:38:10.492053915Z caller=operator.go:441 component=prometheusoperator msg="connection established" cluster-version=v1.14.8-eks-b8860f
level=info ts=2019-12-18T16:38:10.492053693Z caller=operator.go:219 component=alertmanageroperator msg="connection established" cluster-version=v1.14.8-eks-b8860f
level=info ts=2019-12-18T16:38:11.192817813Z caller=operator.go:641 component=alertmanageroperator msg="CRD updated" crd=Alertmanager
level=info ts=2019-12-18T16:38:11.197565205Z caller=operator.go:1870 component=prometheusoperator msg="CRD updated" crd=Prometheus
level=info ts=2019-12-18T16:38:11.211271627Z caller=operator.go:1870 component=prometheusoperator msg="CRD updated" crd=ServiceMonitor
level=info ts=2019-12-18T16:38:11.22237144Z caller=operator.go:1870 component=prometheusoperator msg="CRD updated" crd=PodMonitor
level=info ts=2019-12-18T16:38:11.297956878Z caller=operator.go:1870 component=prometheusoperator msg="CRD updated" crd=PrometheusRule
level=info ts=2019-12-18T16:38:14.202062343Z caller=operator.go:235 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2019-12-18T16:38:14.402384295Z caller=operator.go:190 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2019-12-18T16:38:23.327251162Z caller=operator.go:457 component=prometheusoperator msg="CRD API endpoints ready"
level=info ts=2019-12-18T16:38:24.128536001Z caller=operator.go:387 component=prometheusoperator msg="successfully synced all caches"
level=info ts=2019-12-18T16:38:24.129965157Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-12-18T16:38:24.16135889Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-12-18T16:39:29.653665346Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-12-18T16:39:29.701859837Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-12-18T16:39:29.739345592Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-12-18T16:39:59.735398491Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-12-18T16:39:59.796468742Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-12-18T16:39:59.827104825Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-12-18T16:39:59.880560996Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-12-18T16:40:49.092391259Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-12-18T16:40:49.384007741Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-12-18T16:40:49.559354495Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-12-18T16:40:49.592647115Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-12-18T16:43:23.994140861Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-12-18T16:43:24.028330928Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-12-18T16:43:24.063285495Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-12-18T16:43:24.131280439Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-12-18T16:43:29.303146779Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-12-18T16:43:29.499172376Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-12-18T16:43:29.70248507Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-12-18T16:43:29.737847135Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
W1218 16:45:30.332779       1 reflector.go:299] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:468: watch of *v1.ConfigMap ended with: too old resource version: 1029028 (1031142)
level=info ts=2019-12-18T16:52:20.723029644Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-12-18T16:52:20.955716083Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-12-18T16:52:21.1286078Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2019-12-18T16:52:21.165590861Z caller=operator.go:1072 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
W1218 16:52:51.339506       1 reflector.go:299] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:468: watch of *v1.ConfigMap ended with: too old resource version: 1031621 (1034203)
W1218 16:58:53.344907       1 reflector.go:299] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:468: watch of *v1.ConfigMap ended with: too old resource version: 1034706 (1036733)
```

**Anything else we need to know?**:
