### ISSUE TITLE
Possible bug in exec probes with wget localhost:9090 to Prometheus if listenLocal?

### ISSUE THREAD

**Issue by kallomat** [coreos/prometheus-operator#2921]
**What happened?**

After upgrading prometheus-operator from v0.33.0 to v0.34.0 the prometheus pods are crashlooping.
prometheus configured with listenLocal: true

**Did you expect to see some different?**

Running prometheus pods.

**How to reproduce it (as minimally and precisely as possible)**:

clean git checkout of https://github.com/coreos/kube-prometheus
Apply the manifests unchanged, prometheus is running fine.
Add listenLocal: true to prometheus-prometheus.yaml and apply it.
After a short time, prometheus pods are crashlooping.

wget creates the files healthy and ready in the container on the first call
and errors out in the following calls, see logs below
Liveness probe failed: wget: can't open 'healthy': File exists
Readiness probe failed: wget: can't open 'ready': File exists

Maybe something like this could work:
```
/prometheus $ wget -O - -q 'http://localhost:9090/-/healthy' 2>&1 > /dev/null
/prometheus $ echo $?
0

wget -O - 'http://localhost:9090/-/healthy' 
Connecting to localhost:9090 (127.0.0.1:9090)
writing to stdout
Prometheus is Healthy.
```

**Environment**

* Prometheus Operator version:

    quay.io/coreos/prometheus-operator:v0.34.0

* Prometheus version:

    quay.io/prometheus/prometheus:v2.11.0

* Kubernetes version information:

    `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:11:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

    rancher v2.3.3 (without rancher prometheus installed/enabled)

* Manifests:

```
prometheus-prometheus.yaml

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  listenLocal: true
  nodeSelector:
    kubernetes.io/os: linux
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: v2.11.0
```

* Prometheus Operator Logs:

```
kubectl logs prometheus-operator-6685db5c6-bnw95
ts=2019-12-19T15:43:14.480612987Z caller=main.go:199 msg="Starting Prometheus Operator version '0.34.0'."
ts=2019-12-19T15:43:14.486660217Z caller=main.go:96 msg="Staring insecure server on :8080"
... the rest seems to be normal
```

* Prometheus Pod Logs:

```
kubectl describe pod prometheus-k8s-1
...
  Normal   Created    17m (x2 over 17m)     kubelet, worker2.example.org  Created container prometheus
  Warning  Unhealthy  17m (x5 over 17m)     kubelet, worker2.example.org  Readiness probe failed: wget: can't open 'ready': File exists
  Normal   Pulled     17m (x3 over 17m)     kubelet, worker2.example.org  Container image "quay.io/prometheus/prometheus:v2.11.0" already present on machine
  Warning  Unhealthy  17m (x6 over 17m)     kubelet, worker2.example.org  Liveness probe failed: wget: can't open 'healthy': File exists
  Normal   Killing    17m                   kubelet, worker2.example.org  Container prometheus failed liveness probe, will be restarted
  Warning  BackOff    2m34s (x57 over 16m)  kubelet, worker2.example.org  Back-off restarting failed container
```

**Anything else we need to know?**:

exec probes with wget seemed to be added here:
https://github.com/coreos/prometheus-operator/pull/2763
