### ISSUE TITLE
ARM images

### ISSUE THREAD

**Issue by rhuss** [coreos/prometheus-operator#2946]
**What did you do?**

I tried to install the operator on an RaspberryPi 4 cluster (k3s). However, its doesn't seem that ARM variants of the operator are available (as I get an exec error, so it doesn't look that manifests for ARM images are deployed). 

**Did you expect to see some different?**

'would love to use the operator on an ARM architecture.

**Environment**

K3s v1.17.0+k3s.1

* Prometheus Operator version: v0.34.0

    `sha256:9fac37195cffbddb2762245033e36f40a33f7e127de0c1933bc4164727f4abf8`
    

* Kubernetes version information:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:20Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0+k3s.1", GitCommit:"0f644650f5d8e9f091629f860b342f221c46f6d7", GitTreeState:"clean", BuildDate:"2020-01-06T23:20:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/arm"}
```

**Comment by metalmatze** [comment]
Hey, for my talk during KubeCon I recently ported (compiled) this Operator for ARM. I have a local branch that I never got to push publicly. Let me do that right. :blush: 
Thanks for reminding me by opening this issue. :sweat_smile:

**Comment by metalmatze** [comment]
I created an initial PR at #2947 :blush:

**Comment by rhuss** [comment]
@metalmatze cool, thanks ! Looking forward to try it out ...

**Comment by olvesh** [comment]
It also looks like quay.io does not support docker manifest lists (aka multi-arch) so that you cannot push one image that works on multiple architectures. So in order to make multi arch work in quay.io I think you need to maintain multiple separate images.

E.g. 
```   
$ docker manifest inspect quay.io/coreos/prometheus-operator:latest
unsupported manifest media type and no default available: application/vnd.docker.distribution.manifest.v1+prettyjws
```
while the same against e.g nginx gives the following:
```
$ docker manifest inspect nginx
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 948,
         "digest": "sha256:89a42c3ba15f09a3fbe39856bddacdf9e94cd03df7403cad4fc105088e268fc9",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
[...]
```

Also when pulling from quay.io I get this warning:
`[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the quay.io registry NOW to avoid future disruption.`

**Comment by rhuss** [comment]
The multi-stage build from https://github.com/coreos/prometheus-operator/pull/2947#issuecomment-573419338 with quay.io and I get the following error:

```
#20 pushing layers 20.0s done
#20 pushing manifest for quay.io/rhuss/prometheus-operator:v0.34.0
#20 pushing manifest for quay.io/rhuss/prometheus-operator:v0.34.0 0.2s done
#20 ERROR: failed commit on ref "manifest-sha256:706572e8d8a60eec845bb3823ad885ba007da9f1fd116602a4fd5ce6ee42fcf1": unexpected status: 415 Unsupported Media Type
------
 > exporting to image:
------
failed to solve: rpc error: code = Unknown desc = failed commit on ref "manifest-sha256:706572e8d8a60eec845bb3823ad885ba007da9f1fd116602a4fd5ce6ee42fcf1": unexpected status: 415 Unsupported Media Type
```

So at least buildkit doesn't seem to be compatible with quay.io

**Comment by rhuss** [comment]
The operator runs now smoothly on ARM, but unfortunately the Prometheus images from quay are not multi-arch, too. I switched over to the official Prometheus image hosted on Docker, but then I have the issue that the sidecars (configmap reloader) are not mulitarch either, and there is no way to change those images in a `Prometheus` installation.

That's my `Prometheus` CR with which I tried:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  baseImage: prom/prometheus
  version: v2.15.2
  containers: []
```

but the sidecars get still in injected. 

Any ideas how to move on from here ?

**Comment by rhuss** [comment]
Does anyone knows where I find the source to quay.io/coreos/prometheus-config-reloader:v0.34.0 and `quay.io/coreos/configmap-reload:v0.0.1` ?

Interestingly I can't find some on the web interface of `quay.io` (no coreos images at all). Seems to be coming from a private repo ?

**Comment by rhuss** [comment]
Ok, found  https://github.com/jimmidyson/configmap-reload by @jimmidyson (oh my, should have known that ;-), which also has nice ARM support. BTW, also a very good blueprint for howto generate ARM images via circleci.

**Comment by rhuss** [comment]
With 

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  baseImage: prom/prometheus
  version: v2.15.2
  nodeSelector:
    tichny.org/local-storage-size: "big"
  containers:
  - name: prometheus-config-reloader
    image: maxromanovsky/prometheus-config-reloader:v0.34.0
  - name: rules-configmap-reloader
    image: jimmidyson/configmap-reload:v0.3.0
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
```

I got Prometheus up and running. 

Of course, it would be awesome if we could get Quay Prometheus images to be also multi-arch. But I have no idea how to contribute (as there is no indication where the Quay Prometheus source are)
