### ISSUE TITLE
Allow to specify alert manager configuration path

### ISSUE THREAD

**Issue by omerlh** [coreos/prometheus-operator#2957]
**What is missing?**
The path to alert manager config file is hardcoded (`/etc/alertmanager/config/alertmanager.yaml`), and by default there is a volume mount to `/etc/alertmamager/config`, making it impossible to mount something else to this directory.

**Why do we need it?**
I wanted to use [Kamus](https://kamus.soluto.io) for creating a template configuration file, with a place holder for encrypted data, something like that:
```yaml
receivers:
- name: team-devops-low
  pagerduty_configs:
  - service_key: <%- secrets["pd-team-devops-low"] %>
route:
  group_by:
  - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: team-devops-low
  repeat_interval: 12h
  routes:
  - match:
      namespace: default
    receiver: team-devops-low
```

Everything works, the config file is generated correctly and the place-holder is replaced with the decrypted value - but I can't mount the config file into alert manager.

**Environment**
Kubernetes 1.14
* Prometheus Operator version:

    `quay.io/coreos/prometheus-operator:v0.34.0'

**Anything else we need to know?**:

**Comment by chancez** [comment]
Im currently struggling with this as well. We're using SealedSecrets and currently it seems our only solution is to either encrypt the entire file, making it extremely annoying to modify, or to generate the alertmanager secret in in a separate pod/job from a template and the secret containing the credentials.

**Comment by brancz** [comment]
Can you elaborate on how modifying the alertmanager config file fixes this?

**Comment by chancez** [comment]
We can already use extra volume mounts + initContainers to generate the alertmanager configuration file, but there's no way to actually use it without being able to customize the path, as it's not possible to overwrite the mounted alertmanager configuration.

**Comment by omerlh** [comment]
Exactly, for me everything worked using kube-prometheus and some Jsonnet magic, but I couldn't make alert manager to point to the right configuration path. Ideally, adding to the spec something like:
```yaml
spec:
  configFilePath: <>
<or>
  args: <>
```
