### ISSUE TITLE
Prometheus rule validator admits rules with invalid label types

### ISSUE THREAD

**Issue by jonathanpauda** [coreos/prometheus-operator#2962]
**What happened?**

Prometheus rule validator allowed Prometheus rule with an incorrect label type to pass the validating webhook validation, this caused prometheus operator failing to start after the pod bounced.

I believe the testSeverity: off is causing the type not to be set correctly as a string. It came through as a boolean and should have been a string. We have seen similar behavior for numbers as well. 

**Did you expect to see some different?**

The prometheus rule with invalid type for the label should have been rejected by rule validator. 

**How to reproduce it (as minimally and precisely as possible)**:
Make a prometheus rule with an alert that has labels with non string values.

Alert that caused this example:

```
- alert: ‘testalert’
        annotations:
          description: This is an alert description
          summary: '{{ $labels.type }} has an error’
        expr: (sum by (type) (increase(metric{type=~”myservice(Carrier|Device)"}[5m]))
          < 1)
        labels:
          env: TEST
          prodSeverity: warning
          team: service-team
          testSeverity: off
```

**Environment**

Openshift 3.11

* Prometheus Operator version:

prometheus-operator:v0.34.0

* Kubernetes version information:

    v1.10.0+b81c8f8

* Kubernetes cluster kind:

    Openshift

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
E0115 22:42:33.889919       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:467: Failed to list *v1.PrometheusRule: v1.PrometheusRuleList.Items: []*v1.PrometheusRule: v1.PrometheusRule.Spec: v1.PrometheusRuleSpec.Groups: []v1.RuleGroup: v1.RuleGroup.Rules: []v1.Rule: v1.Rule.Labels: ReadString: expects " or n, but found f, error found in #10 byte of ...|everity":off}},{"a|..., bigger context ...|,"team":"service-team","testSeverity":off}},{"alert":"testalert","annota|...
```

**Anything else we need to know?**:
