### ISSUE TITLE
Getting KubeDeploymentReplicasMismatch alerts continuously 

### ISSUE THREAD

**Issue by vrathore18** [coreos/prometheus-operator#2963]
I am getting KubeDeploymentReplicasMismatch alert for almost all deployments. I think their is something wrong with kube-state-metrics.

```
[FIRING:7] Prometheus Event Notification
Alert:  - critical
 Description: 
 Details:
   - alertname: KubeDeploymentReplicasMismatch
   - deployment: aws-alb-ingress-controller (I am getting for other deployments as well)
   - endpoint: http
   - instance: 172.17.23.88:8080
   - job: kube-state-metrics
   - namespace: kube-system
   - pod:prometheus-operator-kube-state-metrics-7f5bff855d-pjvzk
   - prometheus: monitoring/prometheus-operato-prometheus
   - service:prometheus-operator-kube-state-metrics
   - severity: critical
```

Is anyone facing the same issue?
