### ISSUE TITLE
Prometheus --> Metadata --> labels (kind: Prometheus) are implemented?

### ISSUE THREAD

**Issue by christiangda** [coreos/prometheus-operator#2976]
**What did you do?**

If I set the Label `environment: staging` on my manifest `kind: Prometheus` it doesn't apply my label to the pod

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    environment: staging # <-- The label I want to set
    prometheus: visibility
  name: visibility
  namespace: ms-visibility

```
**Did you expect to see some different?**
```yaml
kind: Pod
apiVersion: v1
metadata:
  name: prometheus-visibility-0
  generateName: prometheus-visibility-
  namespace: ms-visibility
  selfLink: /api/v1/namespaces/ms-visibility/pods/prometheus-visibility-0
  uid: dfeca7ce-414f-11ea-aadd-069f5ba39158
  resourceVersion: '1507677'
  creationTimestamp: '2020-01-27T21:56:30Z'
  labels:
    app: prometheus
    controller-revision-hash: prometheus-visibility-594cdb6fdb
    # environment: staging # <------------------- prometheus-operator doesn't put this label after deploy
    prometheus: visibility
    statefulset.kubernetes.io/pod-name: prometheus-visibility-0
  annotations:
    kubernetes.io/psp: eks.privileged
````
**Environment**
AWS EKS 1.14.9

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    
```yaml
   prometheus-operator:
    Image:      quay.io/coreos/prometheus-operator:v0.34.0
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/kubelet
      --logtostderr=true
      --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
      --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.34.0
```
* Kubernetes version information:

    `kubectl version`
    
```bash
kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind:

AWS EKS 1.14.9

* Manifests:

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    environment: staging
    prometheus: visibility
  name: visibility
  namespace: ms-visibility
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-visibility
      namespace: ms-visibility
      port: web
  baseImage: quay.io/prometheus/prometheus
  enableAdminAPI: true
  nodeSelector:
    kubernetes.io/os: linux
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  replicas: 1
  resources:
    requests:
      memory: 400Mi
  retention: 1d
  ruleSelector:
    matchLabels:
      prometheus: visibility
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: v2.15.2
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

The Prometheus --> Metadata --> Labels are implemented or this is a Bug?
