### ISSUE TITLE
Add ability (or how) to customize target 

### ISSUE THREAD

**Issue by gianrubio** [coreos/prometheus-operator#298]
As I understand, the operator generate the name of the prometheus target based on the value of the service label. This  generate a weird name ```main``` for a service like alertmanager. To illustrate this I created this service monitor below.

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  labels:
    k8s-apps: alertmanager
  name: alertmanager
spec:
  endpoints:
  - port: web
  jobLabel: alertmanager
  selector:
    matchExpressions:
    - {key: alertmanager, operator: In, values: [main]}
```

## Generated target
![screen shot 2017-04-20 at 09 09 00](https://cloud.githubusercontent.com/assets/5694860/25217935/12f9cbb6-25a9-11e7-8443-d685cf99d8c9.png)

It's possible to customize this target name? If it's not, what about to add a field ```targetName``` in the service monitor to customize this name. Same as 

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  labels:
    k8s-apps: alertmanager
  name: alertmanager
spec:
  targetName: alertmanager
  endpoints:
  - port: web

```
