### ISSUE TITLE
How can I add my custom grafana dashboard?

### ISSUE THREAD

**Issue by vrathore18** [coreos/prometheus-operator#2996]
I am trying to add a new dashboard to the below helm chart
https://github.com/helm/charts/tree/master/stable/prometheus-operator

I am having all my dashboards in .json files. Could you please help me out I can I edit my values.yaml in such a way that everytime I install prometheus-operator I will have my dashboard imported. 

P.S I know I have to create a configmap and there is some setting I need to modify in values.yaml. But could some please help me out the the best way to do this?

**Comment by sc250024** [comment]
I can comment on this. There are a couple of ways to inject Grafana dashboards, but here's the general flow:

1. Make sure you have a `dashboardProvider` configured. This is actually part of the Grafana chart that comes bundled with the Prometheus operator Helm chart:

```yaml
grafana:
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'myprovider'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: true
        editable: false
        options:
          path: /var/lib/grafana/dashboards/myprovider
```

2. Once you have your provider (named `myprovider` in this case), you can add dashboards one of the followings ways:

**Via the official Grafana website**:

```yaml
grafana:
  dashboards:
    myprovider:
      nginx-ingress-controller:
        datasource: Prometheus
        gnetId: 9614
        revision: 1
```

**Via raw JSON**:

```yaml
grafana:
  dashboards:
    myprovider:
      some-custom-chart:
        json: |
          {
            "annotations": {
              "list": [
                {
                  "builtIn": 1,
                  "datasource": "Prometheus",
                  "enable": true,
                  "hide": true,
                  "iconColor": "rgba(0, 211, 255, 1)",
                  "name": "Annotations & Alerts",
                  "type": "dashboard"
                }
              ]
            }
<.....>
```

Those are the two basic methods, but the Grafana chart has other methods (see here: https://github.com/helm/charts/blob/master/stable/grafana/values.yaml#L345-L360)
