### ISSUE TITLE
Using external dns with alert manager

### ISSUE THREAD

**Issue by omerlh** [coreos/prometheus-operator#3010]
**What is missing?**
I want to expose alert manager stateful using external dns support for headless services. For this to work, I need to add annotation on the headless service - which is not possible currently.

**Why do we need it?**
For sending alerts from a Prometheus running on one cluster to alert manager running on another cluster. The architecture of alert manager requires that all the instances will get the alert, and (to the best of my knowledge) the best way to do this is with external DNS support for headless service. An a-record should be created, with the IPs of all the alert managers in the cluster.

**Comment by brancz** [comment]
The headless service is really just an implementation detail, I would suggest to create a new headless service, that doesn't select every Alertmanager pod in a namespace created by the Prometheus Operator, but instead the exact one's from the Alertmanager cluster you intend to expose.

**Comment by abelal83** [comment]
How would one specify to the operate to use an additional alertmanager via DNS?
for example, by default the operator creates this

```
spec:
  containers:
  - args:
    - --cluster.peer=alertmanager-prometheus-operator-stg-alertmanager-0.alertmanager-operated.monitoring.svc:6783
```

how would I be able to setup like this

```
spec:
  containers:
  - args:
    - --cluster.peer=alertmanager-prometheus-operator-stg-alertmanager-0.alertmanager-operated.monitoring.svc:6783
    - --cluster.peer=https://myother.alertmanageronanothercluster.com:6783
```

Looking through values.yaml it expects me to supply alertingEndpoints resulting in operator attempting to find within same cluster. Have I missed something obvious?
