### ISSUE TITLE
"sourceLabels" for metricRelabelings is lose

### ISSUE THREAD

**Issue by artemsre** [coreos/prometheus-operator#3016]
I defined new ServiceMonitor with metricRelabelings section:

```
spec:
  endpoints:
  - metricRelabelings:
    - action: keep
      regex: (executed.+|insert.+)
      source_labels: [__name__]
    port: http
```

But I got prometheus config without "source_labels" keys:
```
  metric_relabel_configs:
  - separator: ;
    regex: (executed.+|inspectorio.+)
    replacement: $1
    action: keep
```

Kubernetes secret also wrong: 

```
kubectl get secrets prometheus-prometheus-operator-prometheus -n de...... | base64 --decode|zcat
...
  metric_relabel_configs:
  - regex: (executed.+|inspectorio.+)
    action: keep
...
```

How I could fix this. I tried 0.34.0 and 0.35.1 operator image.
