### ISSUE TITLE
Auto discovery for ExternalName services

### ISSUE THREAD

**Issue by dr460neye** [coreos/prometheus-operator#3020]
Hi there,

i would like to bring up the topic about implementing support for services with external name configuration again.

I know this has been discussed in the past multiple times, and the current workaround is a single "scrape config" file. This makes it hard to scale and administate for future proof scenrarios.
Meanwhile prometheus kubernetes module supports auto discovery for this use case:

See:
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config

> Available meta labels:
> 
> __meta_kubernetes_namespace: The namespace of the service object.
> __meta_kubernetes_service_annotation_<annotationname>: Each annotation from the service object.
> __meta_kubernetes_service_annotationpresent_<annotationname>: "true" for each annotation of the service object.
> __meta_kubernetes_service_cluster_ip: The cluster IP address of the service. (Does not apply to services of type ExternalName)
> **__meta_kubernetes_service_external_name: The DNS name of the service. (Applies to services of type ExternalName)**
> __meta_kubernetes_service_label_<labelname>: Each label from the service object.
> __meta_kubernetes_service_labelpresent_<labelname>: true for each label of the service object.
> __meta_kubernetes_service_name: The name of the service object.
> __meta_kubernetes_service_port_name: Name of the service port for the target.
> __meta_kubernetes_service_port_protocol: Protocol of the service port for the target.

So it would be great to support this feature now in prometheus operator too. This would really help in case of IAC settings. A long term solution, if this is getting to complicated, would also be to support multiple scrape configurations, which will be merged. F.e. a label could be used for this.

**Comment by dr460neye** [comment]
Reference for tickets about this topic:

https://github.com/coreos/prometheus-operator/issues?utf8=%E2%9C%93&q=is%3Aissue+ExternalName+
in specific:

https://github.com/coreos/prometheus-operator/issues/2036

Like mentioned sometimes, for managed services or in clouds, its hard to get a stable ip and way easier to get a dns address provided by your provider.

**Comment by brancz** [comment]
Prometheus requires to scrape each individual target for white box monitoring so even if we discovered these, it would be the wrong strategy.

**Comment by askainet** [comment]
@brancz consider a scenario like this:

- A Prometheus Operator in a Kubernetes cluster managed by the core infrastructure team
- Multiple projects deployed to that cluster, managed by their respective development teams, responsible for their own cloud resources, but sharing the same Prometheus for their monitoring needs
- These projects use cloud resources like Amazon MSK, which already provide individual metrics targets for each Kafka broker, ready to scrape from Prometheus for white box monitoring https://docs.aws.amazon.com/msk/latest/developerguide/monitoring.html#open-monitoring

To be able to delegate setup of these monitoring targets to each team in highly dynamic environments, using a static, centrally managed `additionalScrapeConfigs` is not an option.

Using DNS service discovery is also not a good option, as the team in charge of Prometheus Operator still needs to pre-setup every single service to be discovered, losing the opportunity to benefit from ServiceMonitors discovery, and creating an unnecessary dependency on the core infra team for something that should be much more simple.

Creating Kubernetes Services and Endpoints only supports IP addresses, but they are expected to change without notice (as in any cloud environment), and an extra mechanism to monitor and update them would be required.

Your proposal to introduce a ScrapeConfig CRD would get closer to a good solution, but I'm afraid it will take a long time to implement, and it could introduce the potential for anyone breaking the Prometheus configuration if not handled properly.

As I understand this, the simple and optimal solution would be to just allow them to create Service objects of type ExternalName for each individual target, to be able to autodiscover these targets using their DNS names. And as mentioned earlier, these targets are already individual instances for white box monitoring.

Please, would you reconsider reopening this discussion to understand the use cases and find together better solutions?

Many thanks in advance!

**Comment by askainet** [comment]
> To be able to delegate setup of these monitoring targets to each team in highly dynamic environments, using a static, centrally managed `additionalScrapeConfigs` is not an option.

Currently I'm using this solution to discover ExternalName services from any namespace, with a custom kubernetes_sd_configs using the service role and matching services with a specific label. @dr460neye maybe this can give you some inspiration:

```yaml
additionalScrapeConfigs:
  # scrape external services provided by ExternalName service objects
  - job_name: "external-services"
    honor_timestamps: true
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    kubernetes_sd_configs:
      - role: service
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_monitoring]
        separator: ;
        regex: prometheus-external
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_service_external_name]
        separator: ;
        regex: (.*)
        target_label: instance
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_namespace]
        separator: ;
        regex: (.*)
        target_label: namespace
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: service
        replacement: $1
        action: replace
```

And create an ExternalName service object per target for white box monitoring. For instance, Amazon MSK provides a dedicated metric target per broker, so using Terraform:

```hcl
resource "kubernetes_service" "prometheus_jmx" {
  count = var.broker_count

  metadata {
    name      = "${module.naming.name_prefix_customer}-msk-prometheus-jmx-${count.index}"
    namespace = module.naming.k8s_namespace_customer
    labels = {
      monitoring = "prometheus-external"
    }
  }

  spec {
    type = "ExternalName"
    external_name = local.msk_broker_hosts[count.index]
    port {
      name = "metrics"
      port = 11001
    }
  }
}
```
