### ISSUE TITLE
Is there any way to alter stock relabelling rule?

### ISSUE THREAD

**Issue by rjshrjndrn** [coreos/prometheus-operator#3046]
Hi,
I just want to `drop` pod label, which is not useful for our case. This relabel config is coming from, default prometheus-operator. I tried `relablings` and `metricsRelabelings`. Both turned futile.

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kafka-topic-exporter
    release: prometheus-operator
  name: kafka-topic-exporter
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    port: metrics
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      regex: ^kafka(.*)$
      action: drop
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: kafka-topic-exporter
```
When I apply this SM(with relabelings), my job says `0/0`

**Comment by brancz** [comment]
Relabelings should work just fine but exchange the meta label for the concrete “pod” label.

**Comment by rjshrjndrn** [comment]
@brancz Thank you for your response. But after changing `meta` to `pod`, targets are coming as `0/0` previously there was 1 target.

**Comment by brancz** [comment]
You also want to use the droplabel action instead of just drop.

**Comment by rjshrjndrn** [comment]
oh... Is there any documentation for that @brancz

**Comment by s-urbaniak** [comment]
See https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config, it is called `labeldrop`

**Comment by rjshrjndrn** [comment]
Okay... Finaly figured out. Big thanks for @brancz @s-urbaniak 
Correct one
```
spec:
  endpoints:
  - honorLabels: true
    port: metrics
    relabelings:
    - action: labeldrop
      regex: ^pod$
```
Even if you give wrong as I did 
wrong
```
spec:
  endpoints:
  - honorLabels: true
    port: metrics
    relabelings:
    - action: labeldrop
      sourceLabel: pod
      regex: ^pod$
````
Prometheus was not giving any error, but simply my rules were not reflecting. Then after restarting the Prometheus pod, it became clear, because of some crash loop.
