### ISSUE TITLE
Upgrade to v2.16.0 image with s390x support

### ISSUE THREAD

**Issue by mchoma** [coreos/prometheus-operator#3050]
We are testing EAP on s390x architecture and we have test where EAP and Prometheus are used together. We use this prometheus operator to start up Prometheus.

Please provide release of Prometheus Operator with s390x image support v2.16.0 [2].

We believe it is enough to update [1]. Also consider to expose [1] to any arbitrary image version, which would also help in our case.

[1] https://github.com/coreos/prometheus-operator/blob/release-0.29/pkg/prometheus/statefulset.go#L89
[2] https://quay.io/repository/prometheus/prometheus?tab=tags

**Comment by mchoma** [comment]
@pgier ^ could you help us with this?

**Comment by pgier** [comment]
@mchoma You should be able to set arbitrary images of Prometheus using either the `image` or the `version` field in your Prometheus custom resource (https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec).
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
  image: quay.io/prometheus/prometheus:v2.16.0
```

I'll also create a new PR to add v2.16.0 to the list of supported versions.
