### ISSUE TITLE
Prometheus is showing the target but without endpoint

### ISSUE THREAD

**Issue by NajemAyadi** [coreos/prometheus-operator#3053]
I installed the prometheus-operator using helm. I created a Prometheus CRD
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: prometheus
    prometheus: service-prometheus
  name: service-prometheus
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  logLevel: info
  paused: false
  replicas: 2
  retention: 2d
  routePrefix: /
  ruleSelector:
    matchLabels:
      prometheus: service-prometheus
      role: alert-rules
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpressions:
    - key: serviceapp
      operator: Exists
```
And a ServiceMonitor
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: netcoreapp-servicemonitor
    serviceapp: netcoreapp-servicemonitor
    release: prometheus
  name: netcoreapp-servicemonitor
  namespace: monitoring
spec:
  endpoints:
  - path: /metrics
    port: netcoreappport
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s        
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: netcoreapp-service
      release: monitoring
```
I wanted to monitor the metrics of a sample .netcore application, for that i created a service
```
kind: Service
apiVersion: v1
metadata:
  name: netcoreapp-service
  namespace: monitoring
  labels:
    app: netcoreapp-service
    relase: prometheus
  annotations:
    prometheus.io/scrape: "true"    
    prometheus.io/path: /metrics
    prometheus.io/port: "80"
spec:
    selector:
        app: netcoreapp  
        release: prometheus
    ports:
    - name: netcoreappport
      port: 80      
      targetPort: 80            
    type: ClusterIP
```
And a deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcoreapp-deployment
spec:
  selector:
    matchLabels:
      app: netcoreapp
  replicas: 2 
  template:
    metadata:
      labels:
        app: netcoreapp
    spec:
      containers:
      - name: netcoreapp
        image: najem1/monitoringpocv2:latest
        ports:
        - containerPort: 80
```
I expected to see the target in prometheus including the endpoint, state, labels etc...
but i can see only the target:
![image](https://user-images.githubusercontent.com/27897703/75621946-2199af80-5b9b-11ea-8a83-378c3652cc1a.png)

My cluster is running on Docker for Desktop
- prometheus-operator version: prometheus-operator-8.9.3
- kubectl client version: v1.17.1
- kubectl server version: v1.15.5

I struggeling with this problem since a while, i hope someone could help.
