### ISSUE TITLE
ThanosRuler pod won't attempt to start

### ISSUE THREAD

**Issue by jamesla** [coreos/prometheus-operator#3070]
I'm trying to deploy a thanosruler into my stack following the examples and documentation in this repository. 

When deploying the admission controller fires up and disappears however the thanos ruler pod never even attempts to start and I cannot find an error message to actually troubleshoot this. 

```
---
apiVersion: monitoring.coreos.com/v1
kind: ThanosRuler
metadata:
  name: thanos-ruler
  namespace: default
  labels:
    app: thanos-ruler
spec:
  image: quay.io/thanos/thanos:v0.11.0
  ruleSelector:
    matchLabels:
      role: thanos-ruler
  queryEndpoints:
  - dnssrv+_http._tcp.thanos-query.default.svc.cluster.local
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheus: example-alert
    role: thanos-ruler
  name: prometheus-example-alerts
  namespace: default
spec:
  groups:
  - name: ./example-alert.rules
    rules:
    - alert: ExampleAlert
      expr: vector(1)
```

I simplified this down to make a nice example for this github so to try and bait an error message out of it I just deployed this example without the rest of my stack (expecting it to fail) and I still can't see an error anywhere. I have looked in the kube event stream, the pod logs for all of the running pods and also in the event log of `kubectl describe thanosruler thanos-ruler.` (output below):

```
Name:         thanos-ruler
Namespace:    default
Labels:       app=thanos-ruler
Annotations:  <none>
API Version:  monitoring.coreos.com/v1
Kind:         ThanosRuler
Metadata:
  Creation Timestamp:  2020-03-09T06:12:41Z
  Generation:          2
  Resource Version:    13794
  Self Link:           /apis/monitoring.coreos.com/v1/namespaces/default/thanosrulers/thanos-ruler
  UID:                 e388f9af-4754-4558-9b4a-69628ffe9dde
Spec:
  Image:  quay.io/thanos/thanos:v0.11.0
  Query Endpoints:
    dnssrv+_http._tcp.thanos-query.default.svc.cluster.local
  Rule Selector:
    Match Labels:
      Role:  thanos-ruler
Events:      <none>
```

I'm sure I have just done something silly but without knowing where to find an error message it makes it very difficult to debug.

When deploying the above file (after installing the operator) can somebody tell me where I can find an error message
