### ISSUE TITLE
Enable basic auth on ServiceMonitor

### ISSUE THREAD

**Issue by gianrubio** [coreos/prometheus-operator#308]
The current ServiceMonitor [Endpoint](https://github.com/coreos/prometheus-operator/blob/master/pkg/client/monitoring/v1alpha1/types.go#L176) doesn't support basic auth. On the previous version I had a basic_auth for one of my jobs.

```
- job_name: graylog
  kubernetes_sd_configs:
  static_configs:
    - targets: ['graylog-metrics.logging:9100']

  basic_auth:
    username: prometheus
    password: <hidden>

  metrics_path: '/api/plugins/org.graylog.plugins.metrics.prometheus/metrics'
```

Should I do a PR to enable basic_auth on `ServiceMonitor`?

**Comment by brancz** [comment]
I would be careful about putting secrets into plaintext Endpoint objects, but unfortunately there is no way of reading the basic auth password from disk in Prometheus today. I feel the ideal way would be to implement this functionality in upstream Prometheus and then enable it in the ServiceMonitor. Wdyt @fabxc ?

**Comment by fabxc** [comment]
FWIW, I don't think this in scope of upstream. The configuration is a file, just like a file holding secrets would be. So the upstream answer is to ensure your config file has the sufficiently restricted access.

**Comment by brancz** [comment]
Gotcha. As we're already list/watching secrets we could also enable a way to template secrets into the prometheus config then (currently not possible, but maybe worth a feature).

**Comment by gianrubio** [comment]
I'm willing to implement the basic auth inside a secret. The ideia is to add a string field`secretBasicAuth` into `serviceMonitorSpec`. It has the secret of the basic auth same as:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: graylog
  namespace: monitoring
spec:
  endpoints:
  - port: web
  secretBasicAuth: monitoring/basic-auth-1
  namespaceSelector:
    matchNames:
    - logging
  selector:
    matchLabels:
      component: graylog
```

The secret should be 

```
apiVersion: v1
data:
  username: NDQzYQo=
  password: NDQzYQo=
kind: Secret
metadata:
  name: basic-auth-1
  namespace: monitoring
type: Opaque
```

WDYT?
