### ISSUE TITLE
Thanos Ruler Statefulset does not update

### ISSUE THREAD

**Issue by jalev** [coreos/prometheus-operator#3081]
**What happened?**

With #3065 we fixed the Thanos Ruler Operator so it wouldn't constantly generate new StatefulSets and keep recreating the pods. The issue now is when you go from N number of PrometheusRules objects to 0, the StateFulset does not get updated to remove the volume mounts. We also see the StatefulSet not being updated when the ThanosRuler object is updated.

**Did you expect to see something different?**

- ThanosRuler StatefulSet updated with new command line arguments.
- ThanosRuler StatefulSet updated with new list of volume mounts.

**How to reproduce it (as minimally and precisely as possible)**:

For the CLI args:
1. Create a ThanosRuler object without `logFormat` key.
1. Wait for deployment of pod.
1. Add  `logFormat` to Thanos Ruler spec.

For VolumeMounts:
1. Create a new namespace called `thanos-ruler-tests`. 
1. Create 2000 `PrometheusRule` objects. 
1. Wait for Operator to trigger a Thanos Ruler reload.
1. Delete the namespace. 
1. Restart Thanos-Ruler pod.

**Environment**

* Prometheus Operator version:

`083909fd519084fda6a39fc388462ebc81142007`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:31:31Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:24:46Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

Self made

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: ThanosRuler
metadata:
  labels:
    app: thanos-ruler
    team: observability
  name: thanos-ruler
  namespace: thanos-ruler
spec:
  podMetadata:
    labels:
      prometheus-instance: "false"
      replica-index: 1
      team: observability
      ruler: "true"
  queryEndpoints:
    - xyz:19193
  alertmanagersUrl: "http://something-internal.xyz:9093"
  ruleSelector:
    matchLabels:
      thanos_ruler_global: "true"
  ruleNamespaceSelector: {}
  resources:
    limits:
      memory: 2000Mi
  labels:
    prometheus: prometheus
    cluster: "main01.transferwise.domain"
    replica: "thanos-ruler-1.main01.transferwise.domain"
  logFormat: json
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 2000
  containers:
    - name: thanos-ruler
      image: quay.io/thanos/thanos:v0.11.0
    - name: rules-configmap-reloader
      image: quay.io/coreos/configmap-reload:v0.0.1
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 50Gi
        storageClassName: standard
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:
