### ISSUE TITLE
Alertmanager missing config

### ISSUE THREAD

**Issue by carlpett** [coreos/prometheus-operator#3090]
**What happened?**
After deploying an `Alertmanager` manifest, the pods do not start, staying in `ContainerCreating` forever. The following events are logged:
```
  Warning  FailedMount  12m (x167 over 5h37m)    kubelet, gke-lab-pool-1-n1-standard-1-9c52a450-01xj  MountVolume.SetUp failed for volume "config-volume" : secret "alertmanager-alertmanager" not found
  Warning  FailedMount  2m28s (x148 over 5h35m)  kubelet, gke-lab-pool-1-n1-standard-1-9c52a450-01xj  Unable to mount volumes for pod "alertmanager-alertmanager-0_monitoring(66a9d367-e273-4a89-b15c-9b80fd4050a6)": timeout expired waiting for volumes to attach or mount for pod "monitoring"/"alertmanager-alertmanager-0". list of unmounted volumes=[config-volume]. list of unattached volumes=[config-volume alertmanager-alertmanager-db alertmanager-token-vvvwl]
```

Note `list of unmounted volumes=[config-volume]`. In the statefulset, this corresponds to
```yaml
      volumes:
      - name: config-volume
        secret:
          defaultMode: 420
          secretName: alertmanager-alertmanager
```

**Did you expect to see something different?**
Yes, the necessary secrets should exist

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:
v0.37.0

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.8", GitCommit:"a9973cbb2722793e2ea08d20880633ca61d3e669", GitTreeState:"clean", BuildDate:"2020-02-07T00:50:57Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:
GKE

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    app: alertmanager
  name: alertmanager
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: alertmanager
            # Our labelling scheme
        topologyKey: failure-domain.beta.kubernetes.io/zone
  baseImage: quay.io/prometheus/alertmanager
  externalUrl: https://our-url
  listenLocal: false
  logFormat: json
  logLevel: info
  paused: false
  podMetadata:
    labels:
      app: alertmanager
      # Our labelling scheme
  portName: http
  replicas: 3
  resources:
    limits:
      cpu: 200m
      memory: 400Mi
    requests:
      cpu: 100m
      memory: 100Mi
  retention: 120h
  routePrefix: /
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager
  version: v0.20.0
```

* Prometheus Operator Logs:
No logs mentioning this

**Anything else we need to know?**:
