### ISSUE TITLE
PrometheusNotIngestingSamples: not firing, when tsbd cannot store metrics

### ISSUE THREAD

**Issue by ulikl** [coreos/prometheus-operator#3096]
**What happened?**

When the Storage for the TSBD files is not writeable, e.g. due to access problems or device full, the Prometheus continues working, but it cannot store metrics in the TSDB.

The Alert "PrometheusNotIngestingSamples" is not firing.
I can only see the TSDB write problems in the Prometheus logs files and via false alerts for other cluster component, which use absent expressions. E..g
``` 
KubeletDown
expr: absent(up{job="kubelet"}
  == 1)
for: 15m
...
```

This is very confusing.

**Did you expect to see something different?**

I would have expected the Alert "PrometheusNotIngestingSamples" to alert on this case.

This could be detected by converting the alert to an absent expressing. e.g.

```
    - alert: PrometheusNotIngestingSamples
      annotations:
        description: Prometheus {{$labels.namespace}}/{{$labels.pod}} is not ingesting
          samples.
        summary: Prometheus is not ingesting samples.
      expr: |
        absent(prometheus_tsdb_head_samples_appended_total) == 1
      for: 10m
      labels:
        severity: warning
```

**How to reproduce it (as minimally and precisely as possible)**:

The storage path for the TSDB files must be nearly full or not available.

**Environment**

* Prometheus Operator version:

   Occured with v0.34.1
   Any version should be effected.

* Kubernetes version information:

    v1.16.2
   Any version should should be effected.

* Kubernetes cluster kind:

    OpenShift 4.3

* Manifests:
.../manifests/prometheus-rules.yaml:
```
...
    - alert: PrometheusNotIngestingSamples
      annotations:
        description: Prometheus {{$labels.namespace}}/{{$labels.pod}} is not ingesting
          samples.
        summary: Prometheus is not ingesting samples.
      expr: |
        rate(prometheus_tsdb_head_samples_appended_total{job="prometheus-k8s",namespace="monitoring"}[5m]) <= 0
      for: 10m
      labels:
        severity: warning
...
```

**Anything else we need to know?**:
