### ISSUE TITLE
Allow specifying remote write TLSConfig from secretkey and configmapkey selectors

### ISSUE THREAD

**Issue by brancz** [coreos/prometheus-operator#3118]
**What happened?**

The API exposes configuration of CA, cert, and key via secret or configmap key selectors, but does not actually make use of it.

**Did you expect to see something different?**

When defined the remote write TLS config is configured according to the values in the specified secret or configmap key selectors.

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: test
spec:
  remoteWrite:
  - url: "https://test.com/" # url doesn't actually matter
    tlsConfig:
      ca:
        configMap:
          name: ca
          key: ca.crt
```

The content of `ca.crt` should be provisioned and referenced in the Prometheus container.

**Environment**

* Prometheus Operator version:

Any

* Kubernetes version information:

Any

* Kubernetes cluster kind:

Any

**Anything else we need to know?**:

The API surface was accidentally introduced when this feature was created for ServiceMonitors so it can be argued that this is a feature just as much as a bug.
