### ISSUE TITLE
Tolerations not passed to pods 

### ISSUE THREAD

**Issue by elisiano** [coreos/prometheus-operator#3127]
**What happened?**
I applied tolerations to CR (prometheus and alertmanager).

**Did you expect to see something different?**
I expected to see those tolerations passed onto the managed pods (I checked the code and they should indeed).

**How to reproduce it (as minimally and precisely as possible)**:
I only have one cluster with dedicated nodes for monitoring so I'm not sure how to reproduce it but I've recently updated to kubernetes 1.16 and kube-prometheus to the release-0.4 branch which installs prometheus-operator 0.34.1 and I still see the issue (same behavior was observed with 0.34.0).

**Environment**

* Prometheus Operator version:

    `v0.34.1`
    

* Kubernetes version information:

    `1.16.8`
    

* Kubernetes cluster kind:

    kops

* Manifests:
AlertManager manifest (the prometheus one gets the same tolerations) -- just cleared the metadata section:
```
➭ k get alertmanagers.monitoring.coreos.com main -o yaml
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kops.k8s.io/instancegroup
            operator: In
            values:
            - monitoring
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: alertmanager
              operator: In
              values:
              - main
          namespaces:
          - monitoring
          topologyKey: kubernetes.io/hostname
        weight: 100
  baseImage: quay.io/prometheus/alertmanager
  nodeSelector:
    kubernetes.io/os: linux
  paused: false
  replicas: 3
  resources:
    limits:
      cpu: 6m
      memory: 200Mi
    requests:
      cpu: 3m
      memory: 20Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-main
  version: v0.18.0
tolerations:
- effect: NoSchedule
  key: sugarcrm.io/dedicated
  operator: Equal
  value: monitoring
```

* Prometheus Operator Logs:
There are no prometheus operator relevant logs here but this is what the manifest of the pod created by the alertmanager CR
```
➭ k get po -l app=alertmanager
NAME                  READY   STATUS    RESTARTS   AGE
alertmanager-main-0   2/2     Running   0          2d8h
alertmanager-main-1   2/2     Running   0          2d8h
alertmanager-main-2   0/2     Pending   0          22h # <-- unable to be scheduled because missing necessary tolerations

➭ k describe po alertmanager-main-2
Name:           alertmanager-main-2
Namespace:      monitoring
Priority:       0
Node:           <none>
Labels:         alertmanager=main
                app=alertmanager
                controller-revision-hash=alertmanager-main-b6496d998
                statefulset.kubernetes.io/pod-name=alertmanager-main-2
Annotations:    kubernetes.io/psp: base-psp
Status:         Pending
IP:
Controlled By:  StatefulSet/alertmanager-main
Containers:
  alertmanager:
    Image:       quay.io/prometheus/alertmanager:v0.18.0
    Ports:       9093/TCP, 9094/TCP, 9094/UDP
    Host Ports:  0/TCP, 0/TCP, 0/UDP
    Args:
      --config.file=/etc/alertmanager/config/alertmanager.yaml
      --cluster.listen-address=[$(POD_IP)]:9094
      --storage.path=/alertmanager
      --data.retention=120h
      --web.listen-address=:9093
      --web.route-prefix=/
      --cluster.peer=alertmanager-main-0.alertmanager-operated.monitoring.svc:9094
      --cluster.peer=alertmanager-main-1.alertmanager-operated.monitoring.svc:9094
      --cluster.peer=alertmanager-main-2.alertmanager-operated.monitoring.svc:9094
    Limits:
      cpu:     6m
      memory:  200Mi
    Requests:
      cpu:      3m
      memory:   20Mi
    Liveness:   http-get http://:web/-/healthy delay=0s timeout=3s period=10s #success=1 #failure=10
    Readiness:  http-get http://:web/-/ready delay=3s timeout=3s period=5s #success=1 #failure=10
    Environment:
      POD_IP:   (v1:status.podIP)
    Mounts:
      /alertmanager from alertmanager-main-db (rw)
      /etc/alertmanager/config from config-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from alertmanager-main-token-lvqxm (ro)
  config-reloader:
    Image:      quay.io/coreos/configmap-reload:v0.0.1
    Port:       <none>
    Host Port:  <none>
    Args:
      -webhook-url=http://localhost:9093/-/reload
      -volume-dir=/etc/alertmanager/config
    Limits:
      cpu:     100m
      memory:  25Mi
    Requests:
      cpu:        100m
      memory:     25Mi
    Environment:  <none>
    Mounts:
      /etc/alertmanager/config from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from alertmanager-main-token-lvqxm (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  config-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  alertmanager-main
    Optional:    false
  alertmanager-main-db:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  alertmanager-main-token-lvqxm:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  alertmanager-main-token-lvqxm
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s  # <-- missing the tolerations from the CR
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  2m51s (x934 over 22h)  default-scheduler  0/22 nodes are available: 19 node(s) didn't match node selector, 3 node(s) had taints that the pod didn't tolerate.
```

**Anything else we need to know?**:
Just for completeness sake, let me show the taints that the instance group dedicated to monitoring has:
```
➭ k describe no -l kops.k8s.io/instancegroup=monitoring | grep Taints:
Taints:             sugarcrm.io/dedicated=monitoring:NoSchedule
Taints:             sugarcrm.io/dedicated=monitoring:NoSchedule
Taints:             sugarcrm.io/dedicated=monitoring:NoSchedule
```

So far, the only way I have to schedule prometheus and alertmanager on the desired nodes is if I edit both CRs manually, adding `.spec.paused: "true"` and then add the tolerations manually to the statefulsets.
