### ISSUE TITLE
Prometheus trying to scrape outside configured namespaces

### ISSUE THREAD

**Issue by FelixRodriguezJara** [coreos/prometheus-operator#3139]
Hello, Prometheus Team.

We have deployed two Prometheus within the same cluster, each of them in a different namespace and monitoring different namespaces (prod/noprod).

We are using Prometheus Operator v0.34.0, with Prometheus v2.11.0

This is our "prod" Prometheus configuration regarding Service Monitors and our attempt of limiting the namespaces where Prometheus should be scraping from, by using "serviceMonitorNamespaceSelector" config:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
spec:
  serviceMonitorNamespaceSelector:
    matchNames:
    - tracing
    - metrics
    - logging
    - applications
[..]
```
On the Service Monitors side, we have used the "namespaceSelector" like this:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-metrics
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - argocd
```
Prometheus is able of getting metrics from the services the service monitors are pointing to, within the configured namespaces, however, on top of it, it is trying to get services and pods from other namespaces. We have realized about this scenario because of Prometheus is continuously throwing the following error (replicated with the other noprod namespaces):

> level=error ts=2020-04-13T17:46:11.806Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:265: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:metrics:prometheus-k8s\" cannot list resource \"pods\" in API group \"\" in the namespace \"noprod-argocd\""

In the error, as you can see, "prod" Prometheus is trying to access elements in the "noprod" namespaces.

We have verified that each and every Service Monitor contains the namespace selector and we have tried using the top level namespace selector configuration, with no success.

Could you please guide us to the configuration we need to use in order to avoid this situation?

Any other information you may required, don´t hesitate to letting me know.

Thank you very much.

Kind regards.
