### ISSUE TITLE
How to skip metrics from ingestion?

### ISSUE THREAD

**Issue by ikarlashov** [coreos/prometheus-operator#3140]
**What did you do?**

**Did you expect to see some different?**

**Environment**

* Prometheus Operator version:

    `v0.36.0`
    

* Kubernetes version information:

    `Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6"}`
    

* Kubernetes cluster kind:

    kubespray

I've asked question in Slack, but no one replied :) So, I'm asking here:
We're using prometheus-operator helm chart to install prometheus monitoring. We have high cardinality metrics node_ipvs_backend_connections_inactive/node_ipvs_backend_connections_active coming from **node-exporter** servicemonitor. We're trying to stop metrics from ingestion by adding to values.yaml:

```
additionalScrapeConfigs:
      - job_name: 'node-exporter'
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: (node_ipvs_backend_connections_inactive)
            action: drop
```

But that doesn't work out and metrics are still ingested. Can you pls point what we're missing? Thank you.
