### ISSUE TITLE
Prometheus not finding ServiceMonitor in other namespace

### ISSUE THREAD

**Issue by Cottonglow** [coreos/prometheus-operator#3151]
I am having some problems with getting my Prometheus talking to the ServiceMonitor  in a different namespace on OpenShift. I've managed to get it working on my local kubernetes so I am wondering if it's to do with some RBAC permissions or in the way that the operator is installed (or just something else I completely missed).

The scenario is that the Prometheus Operator and Prometheus itself are in the `monitoring` namespace and the ServiceMonitor and application are in the `test` namespace.

On OpenShift, I can't get Prometheus to find the ServiceMonitor in a different namespace. When i place them in the same namespace, it works. It also works fine on local kubernetes when I use the same yaml files. Anyone have any ideas what I am missing?

**What did you do?**
I've added the `serviceMonitorSelector` and `serviceMonitorNamespaceSelector` to Prometheus to point to the ServiceMonitor and added the labels where necessary. 
Prometheus however does not find the ServiceMonitor:
```
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
  external_labels:
    prometheus: monitoring/prometheus
    prometheus_replica: prometheus-prometheus-0
alerting:
  alert_relabel_configs:
  - separator: ;
    regex: prometheus_replica
    replacement: $1
    action: labeldrop
rule_files:
- /etc/prometheus/rules/prometheus-prometheus-rulefiles-0/*.yaml
```

**Did you expect to see some different?**
Prometheus finds the ServiceMonitor.

**Environment**

* Prometheus Operator version:

    0.32.0

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"4320e48", GitTreeState:"clean", BuildDate:"2020-01-21T19:50:59Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind:

    OpenShift 4.3
    (Local one is Docker Desktop 2.2.0.5)

* Prometheus Operator Logs:

```
ts=2020-04-17T10:33:49.004859093Z caller=main.go:187 msg="Starting Prometheus Operator version '0.32.0'."
ts=2020-04-17T10:33:49.104214334Z caller=main.go:95 msg="Staring insecure server on :8080"
level=info ts=2020-04-17T10:33:49.202184996Z caller=operator.go:222 component=alertmanageroperator msg="connection established" cluster-version=v1.16.2
level=info ts=2020-04-17T10:33:49.202288857Z caller=operator.go:238 component=alertmanageroperator msg="CRD API endpoints ready"
level=info ts=2020-04-17T10:33:49.203658775Z caller=operator.go:425 component=prometheusoperator msg="connection established" cluster-version=v1.16.2
level=info ts=2020-04-17T10:33:49.207135634Z caller=operator.go:441 component=prometheusoperator msg="CRD API endpoints ready"
level=info ts=2020-04-17T10:33:49.895537572Z caller=operator.go:193 component=alertmanageroperator msg="successfully synced all caches"
level=info ts=2020-04-17T10:33:50.71201381Z caller=operator.go:371 component=prometheusoperator msg="successfully synced all caches"
level=info ts=2020-04-17T10:34:11.169135675Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2020-04-17T10:34:11.498540799Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2020-04-17T10:34:11.822965926Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
level=info ts=2020-04-17T10:34:24.870444237Z caller=operator.go:1056 component=prometheusoperator msg="sync prometheus" key=monitoring/prometheus
W0417 10:41:50.705285       1 reflector.go:302] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:452: watch of *v1.ConfigMap ended with: too old resource version: 1536877 (1540579)
W0417 10:48:15.716984       1 reflector.go:302] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:452: watch of *v1.ConfigMap ended with: too old resource version: 1540800 (1543532)
```

**Anything else we need to know?**:

* Prometheus Operator Installation when on OpenShift:
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  channel: beta
  name: prometheus
  source: community-operators 
  sourceNamespace: openshift-marketplace 
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: monitoring-operator-group
  namespace: monitoring
spec:
  targetNamespaces:
    - monitoring
```
* Prometheus Operator installation when testing locally:
https://github.com/coreos/prometheus-operator/blob/master/bundle.yaml (with the namespaces replaced to use `monitoring`)

* Application Namespace:
```
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    monitoring: enabled
```
* ServiceMonitor:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-service-monitor
  labels:
    app: prometheus
  namespace: test
spec:
  selector:
    matchLabels:
      strimzi.io/kind: Kafka
  namespaceSelector:
    matchNames:
      - test
  endpoints: [...]
```
* Prometheus:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  serviceAccountName: prometheus-serviceaccount
  serviceMonitorSelector:
    matchLabels:
      app: prometheus
  serviceMonitorNamespaceSelector:
    matchLabels:
      monitoring: enabled
```
* Prometheus Clusterrole:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-clusterrole
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - extensions
    resources:
      - ingresses
  - verbs:
      - get
    nonResourceURLs:
      - /metrics
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: prometheus-serviceaccount
    namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-clusterrole
```
* Prometheus Logs:
```
level=info ts=2020-04-17T10:34:22.855262553Z caller=main.go:302 msg="Starting Prometheus" version="(version=2.7.1, branch=HEAD, revision=62e591f928ddf6b3468308b7ac1de1c63aa7fcf3)"
level=info ts=2020-04-17T10:34:22.855349084Z caller=main.go:303 build_context="(go=go1.11.5, user=root@f9f82868fc43, date=20190131-11:16:59)"
level=info ts=2020-04-17T10:34:22.855389284Z caller=main.go:304 host_details="(Linux 4.18.0-147.3.1.el8_1.x86_64 #1 SMP Wed Nov 27 01:11:44 UTC 2019 x86_64 prometheus-prometheus-0 (none))"
level=info ts=2020-04-17T10:34:22.855432765Z caller=main.go:305 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2020-04-17T10:34:22.855464214Z caller=main.go:306 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2020-04-17T10:34:22.85678778Z caller=main.go:620 msg="Starting TSDB ..."
level=info ts=2020-04-17T10:34:22.856909132Z caller=web.go:416 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2020-04-17T10:34:22.866221303Z caller=main.go:635 msg="TSDB started"
level=info ts=2020-04-17T10:34:22.869135167Z caller=main.go:695 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2020-04-17T10:34:22.869902321Z caller=main.go:722 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2020-04-17T10:34:22.869957571Z caller=main.go:589 msg="Server is ready to receive web requests."
level=info ts=2020-04-17T10:34:25.807710385Z caller=main.go:695 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2020-04-17T10:34:25.808252258Z caller=main.go:722 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
```
* Prometheus Operator Clusterroles:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-operator
rules:
  - verbs:
      - '*'
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
  - verbs:
      - '*'
    apiGroups:
      - monitoring.coreos.com
    resources:
      - alertmanagers
      - prometheuses
      - prometheuses/finalizers
      - alertmanagers/finalizers
      - servicemonitors
      - podmonitors
      - prometheusrules
  - verbs:
      - '*'
    apiGroups:
      - apps
    resources:
      - statefulsets
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - configmaps
      - secrets
  - verbs:
      - list
      - delete
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - create
      - update
      - delete
    apiGroups:
      - ''
    resources:
      - services
      - services/finalizers
      - endpoints
  - verbs:
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - namespaces
```

**Comment by brancz** [comment]
As you're creating a subscription, presumably on OpenShift you're installing the Prometheus Operator via OLM/Marketplace? That setup can only watch the same namespace it runs in. It can't use a global watch, because OpenShift's cluster-monitoring already watches certain namespaces of openshift cluster components, meaning the two controllers would interfere with each other.

As you're already on 4.3, I actually recommend using the OpenShift User Workload Monitoring feature (tech preview), which sets up the entire stack for you and all you need to do is create the ServiceMonitor :)

**Comment by Cottonglow** [comment]
Thank you @brancz . That makes sense. I managed to get it to a working state by updating the Prometheus CSV to allow for `MultiNamespace` installation and then adding the `test` namespace as a target namespace in the OperatorGroup.

I will have a look at the User Workload Monitoring feature next and see how it works. Will this feature be the recommended way to do monitoring on OpenShift? As opposed to setting up your own Prometheus.

**Comment by brancz** [comment]
> Will this feature be the recommended way to do monitoring on OpenShift? As opposed to setting up your own Prometheus.

Yes.

**Comment by Cottonglow** [comment]
So I have tested the User Workload Monitoring feature on a new cluster. I deployed the following ConfigMap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    techPreviewUserWorkload:
      enabled: true
```
and used the same ServiceMonitor as previously:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-service-monitor
  labels:
    app: prometheus
  namespace: test
spec:
  selector:
    matchLabels:
      strimzi.io/kind: Kafka
  namespaceSelector:
    matchNames:
      - test
  endpoints:
  - port: prometheus
    honorLabels: true
    interval: 10s
    scheme: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_endpoints_name]
      separator: ;
      regex: prometheus-kube-state-metrics
      replacement: $1
      action: keep
```
and this is the Kafka yaml that I want to scrape:
```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  namespace: test
spec:
  kafka:
    version: 2.4.0
    replicas: 1
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.3"
    storage:
      type: ephemeral
    metrics:
      lowercaseOutputName: true
      rules:
      - pattern : kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+), partition=(.*)><>Value
        name: kafka_server_$1_$2
        type: GAUGE
        labels:
          clientId: "$3"
          topic: "$4"
          partition: "$5"
[...]
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
```
Once Kafka is deployed, it's services will receive the `strimzi.io/kind: Kafka` label:
```bash
$ kubectl describe svc/my-cluster-kafka-bootstrap -n test
Name:              my-cluster-kafka-bootstrap
Namespace:         test
Labels:            app.kubernetes.io/instance=my-cluster
                   app.kubernetes.io/managed-by=strimzi-cluster-operator
                   app.kubernetes.io/name=strimzi
                   strimzi.io/cluster=my-cluster
                   strimzi.io/discovery=true
                   strimzi.io/kind=Kafka
                   strimzi.io/name=my-cluster-kafka-bootstrap
Annotations:       prometheus.io/path: /metrics
                   prometheus.io/port: 9404
                   prometheus.io/scrape: true
                   strimzi.io/discovery:
                     [ {
                       "port" : 9092,
                       "tls" : false,
                       "protocol" : "kafka",
                       "auth" : "none"
                     }, {
                       "port" : 9093,
                       "tls" : true,
                       "protocol" : "kafka",
                       "auth" : "none"
                     } ]
Selector:          strimzi.io/cluster=my-cluster,strimzi.io/kind=Kafka,strimzi.io/name=my-cluster-kafka
Type:              ClusterIP
IP:                172.30.52.57
Port:              tcp-replication  9091/TCP
TargetPort:        9091/TCP
Endpoints:         10.254.16.23:9091
Port:              tcp-clients  9092/TCP
TargetPort:        9092/TCP
Endpoints:         10.254.16.23:9092
Port:              tcp-clientstls  9093/TCP
TargetPort:        9093/TCP
Endpoints:         10.254.16.23:9093
Port:              prometheus  9404/TCP
TargetPort:        9404/TCP
Endpoints:         10.254.16.23:9404
Session Affinity:  None
Events:            <none>
```

The ServiceMonitor still doesn't appear in the configuration. I think I might be missing a step somewhere? 

I followed the OpenShift documentation here - https://docs.openshift.com/container-platform/4.3/monitoring/monitoring-your-own-services.html#enabling-monitoring-of-your-own-services_monitoring-your-own-services
