### ISSUE TITLE
"namespace <...> does not exist" errors in the logs

### ISSUE THREAD

**Issue by simonpasquier** [coreos/prometheus-operator#3181]
**What happened?**

Seeing errors like this in the logs when starting prometheus-operator with different values for the `--prometheus-instance-namespaces` and `--namespaces` arguments.

```
level=error ts=2020-04-29T09:04:15.585008464Z caller=operator.go:907 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"default\" does not exist"
level=error ts=2020-04-29T09:04:15.585030323Z caller=operator.go:907 component=prometheusoperator msg="get namespace to enqueue Prometheus instances failed: namespace \"default\" does not exist"
```

**Did you expect to see something different?**

Yes, no error.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Prometheus Operator version:

`master`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

minikube

* Manifests:

```
...
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: prometheus-operator
        app.kubernetes.io/version: v0.38.0
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --logtostderr=true
        - --config-reloader-image=jimmidyson/configmap-reload:v0.3.0
        - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.38.0
        - --prometheus-instance-namespaces=default
        - --namespaces=ns1
        image: quay.io/coreos/prometheus-operator:master
        imagePullPolicy: IfNotPresent
        name: prometheus-operator
...
```

* Prometheus Operator Logs:

See above
