### ISSUE TITLE
Bundle fails RBAC 

### ISSUE THREAD

**Issue by avestuk** [coreos/prometheus-operator#3183]
**What happened?**

Deploying the Prometheus Operator using the latest bundle.yaml from master gives issues with RBAC permissions. 

`kubectl apply -f  https://raw.githubusercontent.com/coreos/prometheus-operator/master/bundle.yaml`

Master currently at: https://github.com/coreos/prometheus-operator/commit/d1c3b3f6e6e2c29420a49404a943004ae3460bba

```
kl prometheus-operator-7676db7c9-sj7g2                                                                                                                                                                                                                         
ts=2020-04-29T13:42:44.77404249Z caller=main.go:209 msg="Starting Prometheus Operator version '0.38.0'."
ts=2020-04-29T13:42:44.779862337Z caller=main.go:99 msg="Staring insecure server on :8080"
level=info ts=2020-04-29T13:42:44.848251485Z caller=operator.go:452 component=prometheusoperator msg="connection established" cluster-version=v1.17.0
level=info ts=2020-04-29T13:42:44.934005052Z caller=operator.go:214 component=alertmanageroperator msg="connection established" cluster-version=v1.17.0
level=info ts=2020-04-29T13:42:45.03476712Z caller=operator.go:294 component=thanosoperator msg="connection established" cluster-version=v1.17.0
ts=2020-04-29T13:42:45.436600855Z caller=main.go:305 msg="Unhandled error received. Exiting..." err="getting CRD: Alertmanager: customresourcedefinitions.apiextensions.k8s.io \"alertmanagers.monitoring.coreos.com\" is forbidden: User \"system:serviceaccount:default:prometheus-operator\" cannot get resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope"
```

Fixed by adding `apiextensions.k8s.io` and `customerresourcedefinitions` to ClusterRole

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: v0.38.0
  name: prometheus-operator
rules:
- apiGroups:
  - monitoring.coreos.com
  - apiextensions.k8s.io
  resources:
  - alertmanagers
  - alertmanagers/finalizers
  - customresourcedefinitions
  - prometheuses
  - prometheuses/finalizers
  - thanosrulers
  - thanosrulers/finalizers
  - servicemonitors
  - podmonitors
  - prometheusrules
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - services
  - services/finalizers
  - endpoints
  verbs:
  - get
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
```
* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    <!-- Try kubectl -n monitoring describe deployment prometheus-operator -->

* Kubernetes version information:

v1.17.0
