### ISSUE TITLE
Prometheus Operator does not set livenessProbe initialDelaySeconds

### ISSUE THREAD

**Issue by jescarri** [coreos/prometheus-operator#319]
**What did you do?**

Running a prometheus with attached EBS to persist data.
If the prometheus pod restarts, the default grace period does not allow prometheus to properly close the data files, then when the pod gets restarted, prometheus will try to recover the datafiles and after a few seconds k8s will mark the pod as unhealthy, the pod will get killed and then it will enter into a crash loopback

**What did you expect to see?**

Prometheuses with persistent storage will terminate and start correctly.

**What did you see instead? Under which circumstances?**

450gb EBS volume.
It is a federation prometheus.

**Environment**

* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3+coreos.0", GitCommit:"8fc95b64d0fe1608d0f6c788eaad2c004f31e7b7", GitTreeState:"clean", BuildDate:"2017-02-15T19:52:15Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

tectonic-installer.

* Manifests:

```
alerting:
  alertmanagers:
  - kubernetes_sd_configs:
    - role: endpoints
    relabel_configs:
    - action: keep
      regex: (?i)alertmanager-operated
      source_labels:
      - __meta_kubernetes_service_name
    - action: keep
      regex: (?i)(prd355-federation)
      source_labels:
      - __meta_kubernetes_namespace
    - action: keep
      regex: (?i)web
      source_labels:
      - __meta_kubernetes_endpoint_port_name
    scheme: http
    timeout: 20s
global:
  scrape_interval: 60s
  scrape_timeout:  59s
  evaluation_interval: 15s
  external_labels:
    src_prometheus: 'prd355-prod1'
rule_files:
- /etc/prometheus/config/*.rules
scrape_configs:

    - job_name: 'federate'
      scrape_interval: 60s
      scrape_timeout: 60s
      honor_labels: true
      metrics_path: '/federate'
      params:
        'match[]':
          - '{job=~".+"}'
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - action: keep
        regex: (?i)prometheus-operated
        source_labels:
        - __meta_kubernetes_service_name
      - action: keep
        regex: (?i)web
        source_labels:
        - __meta_kubernetes_endpoint_port_name
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
        regex: federation.*
        action: drop
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      scheme: http
    - job_name: 'alert-managers'
      scrape_interval: 30s
      scrape_timeout: 30s
      honor_labels: true
      metrics_path: '/metrics'
      kubernetes_sd_configs:
        - role: endpoints
      relabel_configs:
        - action: keep
          regex: (?i)alertmanager-operated
          source_labels:
          - __meta_kubernetes_service_name
        - action: keep
          regex: (?i)web
          source_labels:
          - __meta_kubernetes_endpoint_port_name
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
          regex: (?i)(prd355-federation)
          action: keep
      scheme: http
```

* Prometheus Operator Logs:

```
N/A
```

**Comment by fabxc** [comment]
Thanks for the report. We are totally open to adjust the settings.
Do you want to file a pull request with limits that you would consider
appropriate?

**Comment by jescarri** [comment]
Ah, my bad, it seems that already sets 10 minutes it is plenty of time, I have been checking the code, the problem maybe is related to the liveness prove initialDelaySeconds, I do not see  being set anywhere.

I will submit a PR shortly to allow the initialDelaySeconds and terminationGracePeriodSeconds being user configurable.

**Comment by gianrubio** [comment]
@jescarri add `initialDelaySeconds` on `livenessProbe` will not solve this issue. `livenessProbe` only start after the pod is healthy (covered by `readinessProbe` )

The current time to prometheus-k8s start is 
```
    readinessProbe:
      failureThreshold: 100
      httpGet:
        path: /status
        port: web
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
```

`failureThreshold (100 )* periodSeconds (5) * timeoutSeconds (3)` = 1500 seconds ~= 25 min

I already had this issue of prometheus recovering but I didn't realise what are the issue. 
What is the version of your operator? Do you have the logs of your prometheus-k8s (not operator logs)?
