### ISSUE TITLE
Discovery of alertmanagers is undocumented

### ISSUE THREAD

**Issue by ds0nt** [coreos/prometheus-operator#322]
**What did you do?**
Try and link a prometheus with alertmanagers, but having trouble. It's not mentioned in the documentation that it discovers via regex on the service's name.

https://github.com/coreos/prometheus-operator/blob/88f90dc68f2e47e2b7ff7ad753396e891b23f8dd/pkg/prometheus/promcfg.go#L300

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: example
spec:
  replicas: 2
  alerting:
    alertmanagers: # this bit isn't described in the docs
    - namespace: default
      name: alertmanager-example
      port: web
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: example
```
