### ISSUE TITLE
thanos sidecar log level and log format double definition

### ISSUE THREAD

**Issue by ston1th** [coreos/prometheus-operator#3222]
**What happened?**
#3112 introduced a double definition of log level and log format in the thanos sidecar container if logLevel and logFormat are set directly in the prometheus spec:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
...
spec:
  logFormat: logfmt
  logLevel: info
  thanos:
    logLevel: debug
    logFormat: logfmt
```

resulting container:

```
      - args:
        - sidecar
        - --prometheus.url=http://127.0.0.1:9090/
        - --tsdb.path=/prometheus
        - --grpc-address=[$(POD_IP)]:10901
        - --http-address=[$(POD_IP)]:10902
        - --log.level=debug
        - --log.format=logfmt
        - --objstore.config=$(OBJSTORE_CONFIG)
        - --log.level=info
        - --log.format=logfmt
```

The other main log levels are appended here: https://github.com/coreos/prometheus-operator/blob/01f49eb0a4896091fca6af0aa7b42a3d437fb015/pkg/prometheus/statefulset.go#L820-L826
