### ISSUE TITLE
Having trouble using GKE Persistent Disk

### ISSUE THREAD

**Issue by ds0nt** [coreos/prometheus-operator#323]
**What did you do?**

Attempt to add an gce-persistent-disk for storage on a prometheus operator.

I end up with an error like this:

```
kubectl describe pvc prometheus-prometheus-db-prometheus-prometheus-0
Name:		prometheus-prometheus-db-prometheus-prometheus-0
Namespace:	default
StorageClass:	standard
Status:		Pending
Volume:		
Labels:		app=prometheus
		prometheus=prometheus
Annotations:	volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/gce-pd
Capacity:	
Access Modes:	
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  1m		7s		6	persistentvolume-controller			Warning		ProvisioningFailed	
Failed to provision volume with StorageClass "standard": claim.Spec.Selector is not supported for dynamic provisioning on GCE

# ^^^ error
```

Which is strange because I seem to have an available persistent disk:

```
kubectl get pv
NAME                  CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS      CLAIM     STORAGECLASS   REASON    AGE
gce-persistent-disk   100Gi      RWO           Retain          Available                                      15h
```

My prometheus operator was set up with emptyDir before, and now I'm attempting to move it to this disk above. My configs look like this:

```
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: gce-persistent-disk
  labels:
    app: actourex
    tier: metrics
    environment: develop
spec:
  capacity:
    storage: "100Gi"
  accessModes:
    - "ReadWriteOnce"
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "gke-develop-ssd-2"
```

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      app: actourex
      environment: develop   
  resources:
    requests:
      memory: 400Mi
  # ruleSelector:
  #   matchLabels:
  #     role: prometheus-rulefiles
  #     prometheus: prometheus
  storage:
    selector:
      matchLabels:
        app: actourex
        tier: metrics
        environment: develop
    resources:
      requests:
        storage: 50Gi
```

Am I supposed to use a StorageClass of GCE? Or perhaps I need to delete the correct resources to ge tthe configuration to take hold? Should this happen automatically after applying the files with the changes?

My pod is unhappy with: 
```
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  7m		49s		26	default-scheduler			Warning		FailedScheduling	[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: 
"prometheus-prometheus-db-prometheus-prometheus-0", which is unexpected., 
SchedulerPredicates failed due to PersistentVolumeClaim is not bound: 
"prometheus-prometheus-db-prometheus-prometheus-0", which is unexpected., 
SchedulerPredicates failed due to PersistentVolumeClaim is not bound: 
"prometheus-prometheus-db-prometheus-prometheus-0", which is unexpected.]

 # manually added some line-breaks in that ^^
```

Any pointers would be most appreciated!

**Comment by ds0nt** [comment]
Alright, I think I'm onto something...

I checked out the code here, and it looks all fine and good. The class is only added if the configuration has the len(vc.Class) > 0.

But, I think my default class should be set to an empty string:

```
kc get storageclasses
NAME                 TYPE
standard (default)   kubernetes.io/gce-pd   
```

**Comment by brancz** [comment]
If you have figured out what the issue was, would it be possible for you to add a guide specific to GCE to our [storage user-guide](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/storage.md)?

**Comment by brancz** [comment]
You either need to create `PersistentVolume`s that satisfy the requirements and selector of the `PersistentVolumeClaim`s, or use a `StorageClass` which would make the cluster create the `PersistentVolumeClaim`s as you need them, which in turn automatically provision the underlying `PersistentVolume`.

**Comment by ds0nt** [comment]
Hey, sure. I did end up figuring out what the issue was.

> StorageClass pre-installed and set as default on Azure, AWS, GCE, OpenStack, and vSphere.
This is something to pay close attention to if you’ve been using Kubernetes for a while, because it changes the default behavior of PersistentVolumeClaim objects on these clouds.
Marking a StorageClass as default makes it so that even a PersistentVolumeClaim without a StorageClass specified will trigger dynamic provisioning (instead of binding to an existing pool of PVs).
If you depend on the old behavior of volumes binding to existing pool of PersistentVolume objects then modify the StorageClass object and set storageclass.beta.kubernetes.io/is-default-class to false.

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#volumes

Kubernetes 
```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: standard 
  annotations:
    # this file exists solely to disable this default storage class.
    storageclass.beta.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zone: us-east1-d
```

applying this resource got the PVC and PV to bind to eachother.

I'd be willing to write up a section for it in the docs. Got a place in mind for it? Another .md file or perhaps a secion in an existing .md file.

I can also figure out where to put it if you want. I'll likely get some time to do so this evening.
