### ISSUE TITLE
How does resources requests/limits defined for CRD component?

### ISSUE THREAD

**Issue by lechen26** [coreos/prometheus-operator#3237]
if i have Prometheus object after installing the operator, how can i define specific resources requests/limits for each container?

setting the spec.resources like the folowing:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  image: quay.io/prometheus/prometheus:v2.17.2
  nodeSelector:
    kubernetes.io/os: linux
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  replicas: 2
  enableAdminAPI: true
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: v2.17.2
```
will only set them on the main prometheus container.
so what about the config reloader container resources?
i see it has his own resources requests/limits which i assume came from the CRD.

i assume edit the statefulset itself is not vary smart as it will be overwritten by the operator no?

thanks!
Chen
