### ISSUE TITLE
Q: How to provide a custom prometheus.yaml?

### ISSUE THREAD

**Issue by Bekt** [coreos/prometheus-operator#324]
Maybe I'm missing something, but how do I go about providing my own config (prometheus.yaml) file to Prometheus? Looking at the source code, it is a [hardcoded value](https://github.com/coreos/prometheus-operator/blob/88e3e919a53024161a8409320ca714d969b53b4c/pkg/prometheus/statefulset.go#L194) of empty byte. I know it was possible to do so in previous versions.

I have tried providing it via a volume in prometheus-operator deployment, but no luck.

```
volumes:
- name: config
  configMap:
    name: prometheus-config
```

**Comment by Bekt** [comment]
The only way I was able to work around this was:

- base64 the config file
- patch the secret resource generated by prometheus-operator

**Comment by Bekt** [comment]
@brancz thanks for the response. That did it for me. I don't think I've seen this described in the docs anywhere (I've seen when it was a ConfigMap before though), so maybe it makes sense to leave a note in the getting started page.

I have two comments on that:

1. I manually created the Secret. When I delete the `Prometheus` object, the Secrete is resource is deleted as well. Not sure if intentional or not, but since the Secret is not created by Prometheus Operator, I believe it shouldn't be deleted.

2. Do you think it makes sense to provide a selector for the config, maybe something like `configFileSelector`? `prometheus-<prometheus-object-name>` may not be as intuitive.

**Comment by brancz** [comment]
1) We are definitely aware of, and by now would actually deserve an issue. It should be fixed.
2) While I agree that it might be more intuitive to use let's say a `ConfigMapKeySelector`, where a user could specify the `ConfigMap` and key the config should come from, it is operationally a lot more complicated as a change of the ConfigMap name requires a PodTemplate change in the StatefulSet which is not possible (it is being worked on but is likely not going into 1.7 but 1.8) and even if it was possible it would require a completely new deployment Pods as the Mounts can't be changed during runtime.

**Comment by brancz** [comment]
Furthermore the intention of the Prometheus Operator is for that name to be purely an implementation detail, a user should not care about it as it is managed by the Prometheus Operator. If you want to use the custom configuration because there is something you can't do with the Prometheus Operator it is likely a missing feature :slightly_smiling_face:

**Comment by Bekt** [comment]
For 2), I was thinking to keep the `Secret` (not ConfigMap) but provide a selector for it. Does this change anything?

I agree that Prometheus Operator should be able to do everything that of a custom config should be able to do, but it should not get in the way if you wanna use a custom config. Maybe you already have a Prometheus config and you're trying out Prometheus Operator, or some features are not there yet (blackbox for example). 

Again thanks for the help, lemme know if you want me to create an issue for 1).

**Comment by brancz** [comment]
> lemme know if you want me to create an issue for 1).

Go ahead! :slightly_smiling_face: 

> For 2), I was thinking to keep the Secret (not ConfigMap) but provide a selector for it. Does this change anything?

If we allow specifying a selector then that selector can be changed after the initial creation of the Prometheus object. And for the StatefulSet (which is generated from the Prometheus object) updating the PodTemplate (which would be necessary when changing the selector) is an illegal action, and would therefore make the Prometheus error in an unrecoverable manner. There is upstream work to allow this but as long as this is not fixed in the StatefulSet I would like to avoid any changes to the PodTemplate.

**Comment by dogopupper** [comment]
Hitting this, but apparently secrets have a requirement of base64? There are no sensitive data, all I need is just some regex to filter a 'name' label that is duplicated and messed up. Ideally there should be an automatic way of configuring it either live in prometheus or by a specific manifest (simply adding something more, rather than having to upload your own whole custom config in a hacky way) @brancz

**Comment by brancz** [comment]
@dogopupper Prometheus configurations can have credentials in them, so we decided to make them Kubernetes `Secret`s. Your CI pipeline or whatever applies the configuration can easily support encoding a plaintext config to base64 and into a secret.

Why do you find this way hacky? This is the way you would configure every Prometheus server, if you weren't using the Prometheus Operator.

**Comment by jithinraj89** [comment]
@brancz Is prometheus.yml in Prometheus-operator capable of scraping application metrics.
Example from my python or Ruby apps in kubernetes pod.?
I have a python app already exposing it's metrics but unable to scrape those metrics by Prometheus, can't query them in Prometheus UI. Help

**Comment by brancz** [comment]
@jithinraj89 a custom prometheus.yaml is not necessary for your application metrics, only if you want to scrape non-Kubernetes targets.

You just need a ServiceMonitor selecting your application's Kubernetes Service object.

**Comment by jithinraj89** [comment]
@brancz I created ServiceMonitor for my app and it is showing in `/config` page but not in `/targets` page. below is my config. It is also showing under `service discovery`.

```
- job_name: monitoring/app-name/0
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  kubernetes_sd_configs:
  - api_server: null
    role: endpoints
    namespaces:
      names:
      - test
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    insecure_skip_verify: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_label_k8s_app]
    separator: ;
    regex: app-name
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: app-name
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_service_label_k8s_app]
    separator: ;
    regex: (.+)
    target_label: job
    replacement: ${1}
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: app-name
    action: replace
```

**Comment by brancz** [comment]
@jithinraj89 can you share the servicemonitor itself as well as the service you are trying to select?

**Comment by jithinraj89** [comment]
@brancz 
Service:
```
apiVersion: v1
kind: Service
metadata:
  name: app-name
  namespace: test
  labels:
    app: app-name
spec:
  selector:
    app: app-name
  ports:
  - name: app-name
    port: 8000
```
ServiceMonitor:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-name
  labels:
    k8s-app: app-name
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: app-name
  namespaceSelector:
    matchNames:
    - test
  endpoints:
  - port: app-name
    scheme: https
    interval: 30s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      insecureSkipVerify: true
```

**Comment by brancz** [comment]
The selector you have is matching for all services with the `k8s-app: app-name` label, but your service actually has `app: app-name`.

**Comment by brancz** [comment]
are you actually serving https on that server, if not you will probably want to either delete the `scheme` field or set it to `http`?

**Comment by jithinraj89** [comment]
@brancz 
Great 👍 
I can now monitor my app with Prometheus-operator.

**Comment by jithinraj89** [comment]
@brancz  So I have to create separate servicemonitor for all of my apps in the cluster..? Or is there a way to make single servicemonitor to monitor multiple services object.?

**Comment by brancz** [comment]
It's very flexible allowing you to do various combinations depending on what suits your organization best.

With sufficient discipline in your organization you can use a single ServiceMonitor for everything your company runs (this is most likely unrealistic though), you can set the `namespaceSelector` of the ServiceMonitor to discover Services from any namespace. This requires you to have a single configuration for all services though, meaning everything must run on either http/https, all authentication is done the exact same way, the port is the exact same for all targets.

However, what I recommend is that each team creates ServiceMonitors in their own namespace, this way you have the control over the individual configuration for each individual application. Potentially within a team all of these can be consistent then that team can utilize the strategy I outlined above for everything that team owns.

**Comment by jithinraj89** [comment]
@brancz 
We have n number of pods running in the cluster, where all the pods are not talking to the service object ( pods running without any services). How can I monitor the metrics from that kind of pods?. How servicemonitor will monitor those?.

**Comment by brancz** [comment]
That's what #38 is all about. In the mean time (until we implement that) the best I can offer right now is for you to define your own scrape job definition using the [`additionalScrapeConfigs`](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec) feature.

**Comment by jithinraj89** [comment]
@brancz 
I tried to create an additionalScrapeConfig ( secret ) prometheus.yml file as mentioned below. I used the same labels (managed-by: prometheus-operator) as the current prometheus.yml file have. restarted the pod. still, don't see any change under the` /configuration`  am I missing something here. 

```
apiVersion: v1
kind: Secret
metadata:
  labels:
    managed-by: prometheus-operator
  name: additional-scrape
  namespace: monitoring
data:
  prometheus.yaml: Z2xvYmFsOgogIGV2YWx1YXRpb25faW50ZXJ2YWw6IDMwcwogIHNjcmFwZV9pbnRlcnZhbDogMzBzCiAgZXh0ZXJuYWxfbGFiZWxzOiB7fQpydWxlX2ZpbGVzOgotIC9ldGMvcHJvbWV0aGV1cy9ydWxlcy9ydWxlcy0wLyoKc2NyYXBlX2NvbmZpZ3M6Ci0gam9iX25hbWU6IG1vbml0b3JpbmcvZnJvbnRlbmQvMAogIHNjcmFwZV9pbnRlcnZhbDogMzBzCiAgc2NyYXBlX3RpbWVvdXQ6IDEwcwogIG1ldHJpY3NfcGF0aDogL21ldHJpY3MKICBzY2hlbWU6IGh0dHAKICBrdWJlcm5ldGVzX3NkX2NvbmZpZ3M6CiAgLSBhcGlfc2VydmVyOiBudWxsCiAgICByb2xlOiBlbmRwb2ludHMKICAgIG5hbWVzcGFjZXM6CiAgICAgIG5hbWVzOgogICAgICAtIGV4YW1wbGUtcHAKICB0bHNfY29uZmlnOgogICAgaW5zZWN1cmVfc2tpcF92ZXJpZnk6IHRydWUKICByZWxhYmVsX2NvbmZpZ3M6CiAgLSBzb3VyY2VfbGFiZWxzOiBbX19tZXRhX2t1YmVybmV0ZXNfc2VydmljZV9sYWJlbF9rOHNfYXBwXQogICAgc2VwYXJhdG9yOiA7CiAgICByZWdleDogZXhhbXBsZS1hcHAKICAgIHJlcGxhY2VtZW50OiAkMQogICAgYWN0aW9uOiBrZWVwCiAgLSBzb3VyY2VfbGFiZWxzOiBbX19tZXRhX2t1YmVybmV0ZXNfZW5kcG9pbnRfcG9ydF9uYW1lXQogICAgc2VwYXJhdG9yOiA7CiAgICByZWdleDogd2ViCiAgICByZXBsYWNlbWVudDogJDEKICAgIGFjdGlvbjoga2VlcAogIC0gc291cmNlX2xhYmVsczogW19fbWV0YV9rdWJlcm5ldGVzX25hbWVzcGFjZV0KICAgIHNlcGFyYXRvcjogOwogICAgcmVnZXg6ICguKikKICAgIHRhcmdldF9sYWJlbDogbmFtZXNwYWNlCiAgICByZXBsYWNlbWVudDogJDEKICAgIGFjdGlvbjogcmVwbGFjZQogIC0gc291cmNlX2xhYmVsczogW19fbWV0YV9rdWJlcm5ldGVzX3BvZF9uYW1lXQogICAgc2VwYXJhdG9yOiA7CiAgICByZWdleDogKC4qKQogICAgdGFyZ2V0X2xhYmVsOiBwb2QKICAgIHJlcGxhY2VtZW50OiAkMQogICAgYWN0aW9uOiByZXBsYWNlCiAgLSBzb3VyY2VfbGFiZWxzOiBbX19tZXRhX2t1YmVybmV0ZXNfc2VydmljZV9uYW1lXQogICAgc2VwYXJhdG9yOiA7CiAgICByZWdleDogKC4qKQogICAgdGFyZ2V0X2xhYmVsOiBzZXJ2aWNlCiAgICByZXBsYWNlbWVudDogJDEKICAgIGFjdGlvbjogcmVwbGFjZQogIC0gc291cmNlX2xhYmVsczogW19fbWV0YV9rdWJlcm5ldGVzX3NlcnZpY2VfbmFtZV0KICAgIHNlcGFyYXRvcjogOwogICAgcmVnZXg6ICguKikKICAgIHRhcmdldF9sYWJlbDogam9iCiAgICByZXBsYWNlbWVudDogJHsxfQogICAgYWN0aW9uOiByZXBsYWNlCiAgLSBzb3VyY2VfbGFiZWxzOiBbX19tZXRhX2t1YmVybmV0ZXNfc2VydmljZV9sYWJlbF9rOHNfYXBwXQogICAgc2VwYXJhdG9yOiA7CiAgICByZWdleDogKC4rKQogICAgdGFyZ2V0X2xhYmVsOiBqb2IKICAgIHJlcGxhY2VtZW50OiAkezF9CiAgICBhY3Rpb246IHJlcGxhY2UKICAtIHNlcGFyYXRvcjogOwogICAgcmVnZXg6ICguKikKICAgIHRhcmdldF9sYWJlbDogZW5kcG9pbnQKICAgIHJlcGxhY2VtZW50OiB3ZWIKICAgIGFjdGlvbjogcmVwbGFjZQo=

```

**Comment by brancz** [comment]
@jithinraj89 you need to specify which secret and key you want to use in the `PrometheusSpec` as linked above. Look for the `additionalScrapeConfigs` field in the `PrometheusSpec`.

**Comment by jithinraj89** [comment]
@brancz I have specified the secret and key in the PrometheusSpec as below, created the secret with `name: additional-scrape-configs  key: prometheus-additional.yaml`. but I am unable to see the `job_name` appended in ` /config`. Please help.

prometheus-k8s.yaml
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  labels:
    prometheus: k8s
spec:
  replicas: 2
  version: v2.2.0-rc.1
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpressions:
    - {key: k8s-app, operator: Exists}
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: k8s
  resources:
    requests:
      # 2Gi is default, but won't schedule if you don't have a node with >2Gi
      # memory. Modify based on your target and time-series count for
      # production use. This value is mainly meant for demonstration/testing
      # purposes.
      memory: 400Mi
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-main
      port: web
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
```

created the secret like this.
`kubectl create secret generic additional-scrape-configs --from-file=prometheus-additional.yaml --dry-run -oyaml > additional-scrape-configs.yaml`

prometheus-additional.yaml 
```
- job_name: "test"
  static_configs:
  - targets: ["localhost:9090"]
```

additional-scrape-configs.yaml
```
apiVersion: v1
data:
  prometheus-additional.yaml: LSBqb2JfbmFtZTogInRlc3QiCiAgc3RhdGljX2NvbmZpZ3M6CiAgLSB0YXJnZXRzOiBbImxvY2FsaG9zdDo5MDkwIl0K
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
 
```
