### ISSUE TITLE
Label not unique

### ISSUE THREAD

**Issue by lechen26** [coreos/prometheus-operator#3266]
Hi

I have a serviceMonitor for simple statefulset application which exist on multiple namespaces.

```
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/component: rabbitmq-server
  endpoints:
  - port: http
    path: /api/metrics
```

it used to work for me until i've upgraded the components version. (after GKE ugpraded to 1.16).
now i'm getting the following error on all targets of that servicemonitor
"label name 'node' is not unique. invalid sample'"

on the configuration i see the following:
```
- source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    regex: Node;(.*)
    target_label: node
    replacement: ${1}
    action: replace
```

i dont even see this source label for Kind Node on these targets, i only see Pod.
any idea what am i missing here?

10x
