### ISSUE TITLE
ServiceMonitor with endpoint.interval uses wrong type for Prometheus

### ISSUE THREAD

**Issue by leifmadsen** [coreos/prometheus-operator#3279]
**What happened?**

ServiceMonitor object doesn't pass validation when loaded with `endpoint.interval` as an integer (requires string type), but string type fails to load into Prometheus v2.7.1

**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl apply -f - <<EOF
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: scrape-exporter
  name: 'testing'
  namespace: 'testing'
spec:
  endpoints:
    - interval: "10"
      metricRelabelings:
        - action: labeldrop
          regex: pod
          sourceLabels: []
        - action: labeldrop
          regex: namespace
          sourceLabels: []
        - action: labeldrop
          regex: instance
          sourceLabels: []
        - action: labeldrop
          regex: job
          sourceLabels: []
      port: prom-http
  selector:
    matchLabels:
      app: scrape-exporter
EOF
```
This will result in Prometheus failing to load the configuration:

```
level=error ts=2020-06-11T19:34:38.614820096Z caller=main.go:688 err="error loading config from \"/etc/prometheus/config_out/prometheus.env.yaml\": couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: not a valid duration string: \"10\""
```

**Environment**

minikube

* Prometheus Operator version: quay.io/coreos/prometheus-operator@sha256:ed3ec0597c2d5b7102a7f62c661a23d8e4b34d910693fc23fd40bfb1d9404dcf

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0-4-g38212b5", GitCommit:"2576e482bf003e34e67ba3d69edcf5d411cfd6f3", GitTreeState:"clean", BuildDate:"2020-05-12T06:26:08Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: minikube
