### ISSUE TITLE
servicemonitor/prometheus-operator-kubelet missing tls config on /metrics/resource/v1alpha1

### ISSUE THREAD

**Issue by teochenglim** [coreos/prometheus-operator#3303]
**What happened?**
The newly added servicemonitor object for kubelet on path /metrics/resource/v1alpha1 missing "token" and "tlsConfig"

1. Current setting when render

$ kubectl edit servicemonitor/prometheus-operator-kubelet -n monitoring

```yaml
  - path: /metrics/resource/v1alpha1
    port: https-metrics
    relabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    scheme: https
```

2. Correct settings

```yaml
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token  # this line is missing
    honorLabels: true  # this line is missing
    path: /metrics/resource/v1alpha1
    port: https-metrics
    relabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    scheme: https
    tlsConfig: # this line is missing
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt  # this line is missing
      insecureSkipVerify: true  # this line is missing
```

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:

```shell
helm install prometheus-operator stable/prometheus-operator --namespace monitoring

```

**Environment**

* Prometheus Operator version:

    `Insert image tag or Git SHA here`
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```

**Anything else we need to know?**:

Also reported here: https://github.com/helm/charts/issues/22972
