### ISSUE TITLE
ServiceMonitorNamespaceSelector doesn't seem to work for Prometheus

### ISSUE THREAD

**Issue by vaishali-prophecy** [coreos/prometheus-operator#3338]
In my prometheus deployment, servicemonitorselector and servicemonitornamespaceselector look like this - 

```
  serviceMonitorNamespaceSelector:
    matchLabels:
      owner: prophecy
  serviceMonitorSelector: {}
  version: v2.15.2
```

And my namespace which has the desired service monitor running is - 

```
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2020-07-15T12:17:33Z"
  labels:
    owner: prophecy
  name: test
  resourceVersion: "361113"
  selfLink: /api/v1/namespaces/test
  uid: 43853d67-eae6-4c43-bc3e-bb1e7d47c33e
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

But still I am not able to get service in service discovery tab of Prometheus UI. I checked Prometheus logs and there doesn't seem to be any RBAC issues.

**Comment by brancz** [comment]
Could you check what's in the generated configuration?

```
kubectl -n monitoring get secret prometheus-k8s -ojson | jq -r '.data["prometheus.yaml.gz"]' | base64 -d | gzip --uncompress
```

**Comment by vaishali-prophecy** [comment]
This is deployed in namespace 'prophecy' and here is the config - 

```
global:
  evaluation_interval: 30s
  scrape_interval: 30s
  external_labels:
    prometheus: prophecy/vaishali-prometheus-operat-prometheus
    prometheus_replica: $(POD_NAME)
rule_files:
- /etc/prometheus/rules/prometheus-vaishali-prometheus-operat-prometheus-rulefiles-0/*.yaml
scrape_configs: []
alerting:
  alert_relabel_configs:
  - action: labeldrop
    regex: prometheus_replica
  alertmanagers:
  - path_prefix: /
    scheme: http
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - prophecy
    api_version: v2
    relabel_configs:
    - action: keep
      source_labels:
      - __meta_kubernetes_service_name
      regex: vaishali-prometheus-operat-alertmanager
    - action: keep
      source_labels:
      - __meta_kubernetes_endpoint_port_name
      regex: web
```
