### ISSUE TITLE
prometheus service nodePort does not work => I cant get the prometheus UI

### ISSUE THREAD

**Issue by ehsanrocket** [coreos/prometheus-operator#3343]
Hi all 
I am new to prometheus-operator 
I have install the prometheus-operator . and I have followed the examples. I have created **deployment** (example-app-deployment.yaml )  and a **service** ( example-app-service.yaml ) then
create a **service monitor** (example-app-service-monitor.yaml) to monitor the service then  
the **prometheus instance** ( prometheus-service-monitor.yaml ) and **prometheus service** ( prometheus-service.yaml ) 

the problem is the node port 30900 does not work 
``` telnet localhost 30900 ``` does not connect to it . so I cant get the prometheus UI
by the way the promotheus instance does not create any pod !! should it be like that ??
Am I doing something wrong ?? 

example-app-deployment.yaml :
``` 
kind: Deployment
metadata:
  name: example-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: fabxc/instrumented_app
        ports:
        - name: web
          containerPort: 8080
```

example-app-service.yaml : 
```
kind: Service
apiVersion: v1
metadata:
  name: example-app
  labels:
    app: example-app
spec:
  selector:
    app: example-app
  ports:
  - name: web
    port: 8080
```
example-app-service-monitor.yaml: 
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: example-app
  endpoints:
  - port: web
```

prometheus-service-monitor.yaml : 
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
```
prometheus-service.yaml : 
```
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus
```
