### ISSUE TITLE
unknown long flag --kubelet-service during deployment

### ISSUE THREAD

**Issue by jpreese** [coreos/prometheus-operator#3349]
**What happened?**

Using the prometheus-operator v0.40.0, the deployment is failing due to the following log line:

```text
Error parsing commandline arguments: unknown long flag '--kubelet-service'
prometheus: error: unknown long flag '--kubelet-service'
```

**How to reproduce it (as minimally and precisely as possible)**:

Using: 
prometheus-operator v0.40.0
prometheus-config-reloader v0.40.0
jimmidyson/configmap-reload v0.4.0
prometheus v2.19.2
alertmanager v0.21.0

**Environment**

* Prometheus Operator version:

prometheus-operator v0.40.0

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-12-04T07:23:47Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:

Kind @v0.7.0

* Manifests:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: v0.40.0
  name: prometheus-operator
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: prometheus-operator
        app.kubernetes.io/version: v0.40.0
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --logtostderr=true
        - --config-reloader-image=jimmidyson/configmap-reload:v0.4.0
        - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.40.0
        image: quay.io/coreos/prometheus-operator:v0.40.0
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator
```

* Prometheus Operator Logs:

```text
Error parsing commandline arguments: unknown long flag '--kubelet-service'
prometheus: error: unknown long flag '--kubelet-service'
```
