### ISSUE TITLE
Customed PodMonitor not working

### ISSUE THREAD

**Issue by vivianforzj** [coreos/prometheus-operator#3350]
**What did you do?**

I wrote podmonitor by myself to monitor pod in defined namespace, the yaml file is:

```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: test-pod-monitor
spec:
  namespaceSelector:
    matchNames:
    - xxxx
  podMetricsEndpoints:
  - interval: 5s
    scheme: http
    path: /metrics
    port: '8080'
  selector:
    matchLabels:
      name: yyyy
```

After I installed the podmonitor, I checked the prometheus web-Status-Target. And I found the target tenant-xdf-aeeg/test-pod-monitor/0, but no endpoint, and the "up" part is 0/0 (tenant-xdf-aeeg is the namespace of the podmonitor)

**Did you expect to see some different?**

I expected to see that the target test-pod-monitor has endpoint and up is "1/1"

**Environment**

* Prometheus Operator version: 0.38.1

* Kubernetes version information: 1.13

* Prometheus Logs:

```
level=error ts=2020-07-20T06:20:07.182Z caller=endpoints.go:131 component="discovery manager scrape" discovery=k8s role=endpoint msg="endpoints informer unable to sync cache"
level=error ts=2020-07-20T06:20:07.182Z caller=endpoints.go:131 component="discovery manager scrape" discovery=k8s role=endpoint msg="endpoints informer unable to sync cache"
level=error ts=2020-07-20T06:20:07.182Z caller=pod.go:85 component="discovery manager scrape" discovery=k8s role=pod msg="pod informer unable to sync cache"
level=error ts=2020-07-20T06:20:07.188Z caller=endpoints.go:131 component="discovery manager notify" discovery=k8s role=endpoint msg="endpoints informer unable to sync cache"
level=error ts=2020-07-20T08:47:45.078Z caller=manager.go:118 component="scrape manager" msg="error reloading target set" err="invalid config id:tenant-xdf-aeeg/test-pod-monitor/0"
```

How can I fix the problem? Thanks for any help

**Comment by vdksystem** [comment]
what was the issue?
I have the same problem

**Comment by rosulg** [comment]
For my case, the PodMonitor started discovering my pod's metrics when I used the deprecated value `targetPort` instead of `port`.  NB! I am doing this for learning purposes, You should NOT use deprecated values.

**Comment by agentreno** [comment]
I came across this because I had the same problem, which is because it's easy to mistake the meaning of `port` in this context.

From the output of `kubectl explain podmonitor.spec.podMetricsEndpoints`:
```
...
   port <string>
     Name of the pod port this endpoint refers to. Mutually exclusive with
     targetPort.
...
```

So give your port a name in the ContainerSpec:
```
spec:
  containers:
  - name: yourapp
    ports:
    - containerPort: 8000
      name: metrics
      protocol: TCP
```

And use it in the PodMonitor:
```
spec:
  podMetricsEndpoints:
  - port: metrics
```

This fixed the issue for me and caused the target to be active in Prometheus.
