### ISSUE TITLE
Adding Additional Scrape Config doesn't work

### ISSUE THREAD

**Issue by odelreym** [coreos/prometheus-operator#3353]
**What did you do?**

I've tried to add the following additional-Scrape-Configs

```
- job_name: 'cAdvisor'
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  kubernetes_sd_configs:
  - role: node
  relabel_configs:
  - action: labelmap
  regex: __meta_kubernetes_node_label_(.+)
  - target_label: __address__
  replacement: kubernetes.default.svc:443
  - source_labels: [__meta_kubernetes_node_name]
  regex: (.+)
  target_label: __metrics_path__
  replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
```

Then I executed: 
**kubectl create secret generic additional-scrape-configs --from-file=prometheus-additional.yaml --dry-run -oyaml > additional-scrape-configs.yaml**

and I applied the secret into the namespace

Then, I updated the Prometheus by adding

```
  additionalScrapeConfigs:
    name: aditional-scrape-configs
    key: prometheus-additional.yaml
```

Lately I restarted the pods, but the config is not applied

**Did you expect to see some different?**
The new config applied

**Environment**

k8s cluster running in Azure. v1.15.11

* Prometheus Operator version:

```
Name:                   prometheus-operator
Namespace:              kube-monitoring
CreationTimestamp:      Tue, 07 Apr 2020 14:38:23 +0200
Labels:                 app.kubernetes.io/component=controller
                        app.kubernetes.io/name=prometheus-operator
                        app.kubernetes.io/version=v0.35.0
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app.kubernetes.io/component=controller,app.kubernetes.io/name=prometheus-operator
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/component=controller
                    app.kubernetes.io/name=prometheus-operator
                    app.kubernetes.io/version=v0.35.0
  Service Account:  prometheus-operator
  Containers:
   prometheus-operator:
    Image:      quay.io/coreos/prometheus-operator:v0.35.0
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/kubelet
      --logtostderr=true
      --config-reloader-image=jimmidyson/configmap-reload:v0.3.0
      --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.35.0
    Limits:
      cpu:     200m
      memory:  200Mi
    Requests:
      cpu:        100m
      memory:     100Mi
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   prometheus-operator-56b59cf4d8 (1/1 replicas created)
Events:          <none>
```

* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"ec831747a3a5896dbdf53f259eafea2a2595217c", GitTreeState:"clean", BuildDate:"2020-05-29T19:56:10Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

AKS
