### ISSUE TITLE
"targetPort" do not work in "ServiceMonitor"

### ISSUE THREAD

**Issue by vincent-pli** [coreos/prometheus-operator#3354]
**What happened?**
Try to use `targetPort` in `serviceMonitor` to retrieval data.
Seems it's not work, so I prepare two SVC point to same pod, one has port name, another not.
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: helloword-1
  name: helloword-service-1
  namespace: helloword
spec:
  ports:
  - port: 10501
    protocol: TCP
    targetPort: 10501
  selector:
    app.kubernetes.io/name: helloword-pod
  type: ClusterIP
```
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: helloword-2
  name: helloword-service-2
  namespace: helloword
spec:
  ports:
  - name: metrics 
    port: 10501
    protocol: TCP
    targetPort: 10501
  selector:
    app.kubernetes.io/name: helloword-pod
  type: ClusterIP
```

Then create two `serviceMonitor` for each:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus
  name: my-hpac-1
  namespace: openshift-monitoring
spec:
  endpoints:
  - interval: 10s
    targetPort: 10501
  namespaceSelector:
    matchNames:
    - helloword
  selector:
    matchLabels:
      app.kubernetes.io/name: helloword-1
```
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-hpac-2
  namespace: openshift-monitoring
  labels:
    k8s-app: prometheus
spec:
  endpoints:
  - interval: 10s
    port: metrics
  namespaceSelector:
    matchNames:
    - helloword
  selector:
    matchLabels:
      app.kubernetes.io/name: helloword-1
```

The second on (with `port`) works, but the first one(with `targetPort` not work)
I checked the status on GUI of Prometheus: status-service discovery
```
openshift-monitoring/my-hpac-1/0 (0/2 active targets)
```

So, any suggestion, thanks.

**Comment by vincent-pli** [comment]
I figure out the issue, when use `targetPort` the related pod must specify a container port, or it will not work.
I'm new for Prometheus, where can I fine document for it, thanks.

**Comment by brancz** [comment]
My apologies, you are correct. What you can still try to relabel the port into the `__address__` meta label, but what you said is indeed how it works, I was wrong. This is indeed how it is intended to work.

**Comment by dntosas** [comment]
> My apologies, you are correct. What you can still try to relabel the port into the `__address__` meta label, but what you said is indeed how it works, I was wrong. This is indeed how it is intended to work.

have you tried this workaround ^^ @vincent-pli ?

**Comment by dntosas** [comment]
a little bit related --> https://github.com/istio/istio/issues/27328

**Comment by weibeld** [comment]
The workaround mentioned by @brancz can be implemented as follows:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-hpac-1
spec:
  namespaceSelector:
    matchNames:
      - helloword
  selector:
    matchLabels:
      app.kubernetes.io/name: helloword-1
  endpoints:
    - relabelings:
      - action: replace
        targetLabel: __address__
        sourceLabels:
          - __address__
        replacement: $1:10501
```

In other words, instead of defining the port for Prometheus to scrape with either `port` or `targetPort`, manually redefine the `__address__` label (which initially just contains the IP address of the Pod, if the Pod does not declare any ports) to include the desired target port. 

I tested the above with a PodMonitor, but I assume it works with a ServiceMonitor too.
