### ISSUE TITLE
How to create serviceMonitor for kubelet 

### ISSUE THREAD

**Issue by perumalla-giridhar** [coreos/prometheus-operator#3359]
**What did you do?**
Trying to scrape metrics from kubelet cadvisor
created serviceMonitor 
yaml file:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubelet
  labels:
    k8s-app: kubelet
spec:
  jobLabel: k8s-app
  endpoints:
  - port: https-metrics
    scheme: https
    interval: 30s
    tlsConfig:
      insecureSkipVerify: true
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  - port: cadvisor
    scheme: https
    path: /metrics/cadvisor
    interval: 30s
    honorLabels: true
    tlsConfig:
      insecureSkipVerify: true
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  selector:
    matchLabels:
      k8s-app: kubelet
  namespaceSelector:
    matchNames:
    - kube-system
```
after creating this i expect to see all the metrics in prometheus. But i dont see any metrics from cadvisor in my prometheus
I wanted to know is this the  way of collecting metrics from cadvisor of kubelet. If not, how do i collect them?

**Did you expect to see some different?**
I expect to see metrics generated by cadvisor in my prometheus setup.
**Environment**
`Ubuntu:18.04.3`
* Prometheus Operator version:

    `quay.io/coreos/prometheus-operator:v0.40.0`
    

* Kubernetes version information:

    `Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:30:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`
    

* Kubernetes cluster kind:

   ` kubeadm`

**Anything else we need to know?**:
currently i can see metrics by following commands
`kubectl proxy --port 8001 &`
`curl http://localhost:8001/api/v1/nodes/<nodename>/proxy/metrics/cadvisor`

**Comment by brancz** [comment]
Have you checked the prometheus UI /targets page?

**Comment by perumalla-giridhar** [comment]
yes, i cant see this target

**Comment by brancz** [comment]
can you take a screenshot and share?

**Comment by perumalla-giridhar** [comment]
Hi , It was my mistake. i was running servicemonitor in different namespace. Now i changed it to correct namespace. After that i can see targets in the UI but status is `DOWN` for all the endpoints with error `Get "https://<nodeip>:4194/metrics/cadvisor": dial tcp 172.31.20.154:4194: connect: connection refused` for endpoint `https://<nodeip>:4194/metrics/cadvisor`
on other side the endpoint `https://<nodeip>:10250/metrics` has error `server returned HTTP status 403 Forbidden`

**Comment by brancz** [comment]
403 is about authentication/authorization yes. The first one it seems you have endpoints in correct, the `/metrics/cadvisor` endpoint is on the same http server as the normal metrics endpoint for the kubelet, so not the `4194` port.

Generally I recommend trying the [kube-prometheus](https://github.com/coreos/kube-prometheus) project as that has all of these things pre-configured and wired up with each other :)

**Comment by perumalla-giridhar** [comment]
so, in the above yaml file `bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token`  
is this location represent the location in master node? Now i see there is no such file in master. 

If required how should I create one for authorization?

 there is  a service account already present for prometheus and it has following privileges given using cluster role
cluster role snippet:
```
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
```
When i run following curl command 
```
curl -k -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Ikx4NzNIMUl5M3pIMGRZYXBLemtHQzd5SkFnTWxpR1VIWFJGQ0I4OE9pV0UifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJwcm9tZXRoZXVzLXRva2VuLTJqY2JiIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InByb21ldGhldXMiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJlOTQ0NDMxNi0wODdkLTRhYzgtYWE0ZC1hN2JhMGJkOWQyZGUiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06cHJvbWV0aGV1cyJ9.Qi9rrqiMNB0-2Ir8ooR5E5PUvB5EcIDoPX1d0lRQaNtsZF9uY0TwNZwnOg7c6ZCtAPfgEErb5xj-cIBaplc0BYKLl-BJAqLr5CjPTxT3KRYKekwSezBgmW8cXldpUuekHO7IaGIwqZ6eEX3csOY1YYWWmoR9HPUYan5udVmbTcMFv9cWN8cq8TG3fvWrZxGUpOBYpAnY68OTL8XOTxPfHU74ajphUFlX3_Zm4vqwHarA9R0-vxILVgq7SYpHpuUbcspK6GYUx1GilU-Pbt1C4o1P1QFmZprTMjZ6CJhzVsXH8hQnBvqycRo6rXu2YRka6bJZTnlHMZkSwSaiGhGcXg" https://<nodeip>:10250/metrics/cadvisor
```
the above bearer token is extracted from the serviceaccount of prometheus. 

output of the curl  is 
```
Forbidden (user=system:serviceaccount:kube-system:prometheus, verb=get, resource=nodes, subresource=metrics)
``` 
with this can i confirm that servicemonitor is using same token as this curl for authentication?  If yes then simply giving the additional privilege required for serviceaccount would solve the problem. in that case what are the changes to be done the above cluster role
