### ISSUE TITLE
Exposing alertmanager through Kubernetes api and alert urls

### ISSUE THREAD

**Issue by tsloughter** [coreos/prometheus-operator#342]
**What did you do?**

Used `kube-prometheus` deploy script and then followed https://coreos.com/operators/prometheus/docs/latest/user-guides/exposing-prometheus-and-alertmanager.html#kubernetes-api for exposing prometheus and alertmanager.

**What did you expect to see?**

Links in alertmanager generated alerts that point to the kubernetes proxy url. Updating the `externalUrl` of the `AlertManager` resource probably does update the links that are contained in alerts to point to the right url but I am unable to verify since configuring the `externalUrl` causes no alerts to be fired.

**What did you see instead? Under which circumstances?**

No alerts when `externalUrl` of `AlertManager` is set.

**Environment**

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

GKE

* Manifests:

```
apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "Alertmanager"
metadata:
  name: "main"
  labels:
    alertmanager: "main"
spec:
  replicas: 3
  version: v0.6.1
```

and:

```
apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "Alertmanager"
metadata:
  name: "main"
  labels:
    alertmanager: "main"
spec:
  replicas: 3
  version: v0.6.1
  externalUrl: https://127.0.0.1:8001/api/v1/proxy/namespaces/monitoring/services/alertmanager-main:web/
```
