### ISSUE TITLE
Simplify monitor selector

### ISSUE THREAD

**Issue by fabxc** [coreos/prometheus-operator#37]
Currently we allow including ServiceMonitors by a list of label selectors (kind of how we allow lists of everything in the Prometheus config). Example:

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: prometheus-frontend
  labels:
    prometheus: frontend
spec:
  version: v1.3.1
  serviceMonitors:
  - selector:
      matchLabels:
        tier: frontend
```
While the most flexible it adds complexity and thus goes against the main goal of the operator. It does not seem aligned with selector occurrences in Kubernetes.

I think 99% of use cases will be covered by
* a simple single-label inclusion like `team=X` or `tier=Y`
* include all ServiceMonitors in this namespace

The first would be sufficiently covered by one single label Selector like:

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: prometheus-frontend
  labels:
    prometheus: frontend
spec:
  version: v1.3.0
  serviceMonitors:
    matchLabels:
      tier: frontend
```

I'd imagine for any use case that could not be covered by label selectors, one would just expect the ServiceMonitors labelling scheme to be adjusted to do so. Monitoring setups generally seem static enough to do it this way.

This of course only works if we are positive that we won't need any additional options on *how* to include service monitors. (Like overwriting some of the attributes defined in there – which I don't expect as people should own both resources.)

For the second, do we need an explicit option for that? Do we just expect labelling to solve that (exists-relation can include monitors just based on a standard label existing, regardless of value)?
 
Thoughts?

@brancz @brian-brazil @grobie @matthiasr
