### ISSUE TITLE
Alertmanager endpoints configured inside Prometheus disappear after a few seconds

### ISSUE THREAD

**Issue by doublek** [coreos/prometheus-operator#374]
**What did you do?**
Configure Prometheus alerting endpoints using `AlertmanagerEndpoints`.
**What did you expect to see?**
Expected alertmanager endpoints to be correctly listed under `status` Prometheus path (Runtime & Build Information).
**What did you see instead? Under which circumstances?**
The Alertmanager Endpoints correctly showed up for a few seconds and disappears. This happens the first time a Prometheus instance is created and every time the Alertmanager service is created/destroyed.
**Environment**

* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	kubeadm cluster

* Manifests:
```
# Pasting only relevant manifests:
# Alertmanager Service:
apiVersion: v1
kind: Service
metadata:
  name: test-am
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30903
    port: 9093
    protocol: TCP
    targetPort: web
  selector:
    alertmanager: test-am
---
# Prometheus
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: test-prom
  namespace: monitoring
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: operator
  version: v1.6.1
  retention: 1h
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      role: prometheus-rules
      prometheus: test-prom
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: test-am
        port: web
```

* Prometheus Operator Logs:
I looked at prometheus operator logs and prometheus logs and didn't find anything out of the ordinary.
