### ISSUE TITLE
Changing retention period deletes all data

### ISSUE THREAD

**Issue by Gouthamve** [coreos/prometheus-operator#375]
**What did you do?**

Add `retention: 360h` to spec and execute `kubectl update -f prom.yaml`.

**What did you expect to see?**

Prometheus is restarted with the new retention flag. All existing data is still there.

**What did you see instead? Under which circumstances?**

All data has been lost.

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:48:59Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:38:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 
A four node cluster created via kubeadm.

* Manifests:
Before:
```
apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "Prometheus"
metadata:
  name: prometheus-5g
  labels:
    prometheus: "prometheus-5g"
spec:
  replicas: 1
  version: v1.6.2
  serviceAccountName: prometheus-5g
  serviceMonitorSelector:
    matchLabels:
      by: goutham 
  resources:
    requests:
      memory: 8Gi 
```

After:
```
apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "Prometheus"
metadata:
  name: prometheus-5g
  labels:
    prometheus: "prometheus-5g"
spec:
  replicas: 1
  version: v1.6.2
  retention: 360h
  serviceAccountName: prometheus-5g
  serviceMonitorSelector:
    matchLabels:
      by: goutham 
  resources:
    requests:
      memory: 8Gi 
```

**Comment by brancz** [comment]
Changing the retention causes a deployment and if your Prometheus instance's data is not backed by a Persisent Volume there is little we can do about this. So the way to go here is to either provision Persisent Volumes yourself that match the criteria of the Persisent Volume Claim. Checkout our [storage documentation](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/storage.md) to see what might fit your use case best.

**Comment by shenshouer** [comment]
I used the Ceph RBD as storage of prometheus, but the prometheus delete all data before at 8:00 AM every day. How to set to keep all data of prometheus ?

**Comment by brancz** [comment]
You just need to set the retention field in the Prometheus object.

**Comment by ryanash999** [comment]
@brancz Can you point me to the correct documentation for setting this retention or other custom settings for the prometheus.yaml?   I have same question for customizing Grafana core configuration to enable auth LDAP, etc.

**Comment by brancz** [comment]
regarding your first point see the API docs and the second: this is not currently possible we're waiting for Grafana 5.1 to be released, where we will be able to use the upstream image again

**Comment by rjanovski** [comment]
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      org: my-org
  serviceAccountName: prometheus-operator
  retention: 30d
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: default
        resources:
          requests:
            storage: 100Gi
```

this TLDR snippet could have saved me some time :)
leaving for others
