### ISSUE TITLE
Missing url/path_prefix option for Alertmanager endpoints

### ISSUE THREAD

**Issue by galexrt** [coreos/prometheus-operator#378]
Prometheus instance doesn't use the `externalURL` path, rendering all requests to the Alertmanager from prometheus a 404:
```
time="2017-05-18T12:21:07Z" level=error msg="Error sending alerts: bad response status 404 Not Found" alertmanager="http://1.1.1.5:9093/api/v1/alerts" count=1 source="notifier.go:370"
```
The path with my set `externalUrl` would need to be: `http://1.1.1.5:9093/example/api/v1/alerts`.

I think there a) should be a `path`/`path_prefix` option added to the alertmanagerendpoints API object [0] or b) the config should automatically set/add the path of the `externalURL` set in the alertmanager(s) in the alertmanager endpoint `path_prefix` option [1].

***

[0] https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#alertmanagerendpoints
[1] [https://prometheus.io/docs/operating/configuration/#<alertmanager_config>](https://prometheus.io/docs/operating/configuration/#<alertmanager_config>)

**Comment by brancz** [comment]
Essentially that means the route prefix and external url should behave the same way as they do in Prometheus. As mentioned in #342 this will first have to actually be implemented in the Alertmanger before we can implement it here. As #342 tracks the same thing as this I'll close this here as a dupe.

**Comment by brancz** [comment]
Actually I think I was a bit too quick here .. while route prefix is necessary this should indeed also be configurable on Prometheus side.

**Comment by galexrt** [comment]
@brancz With the latest version `0.10.0`. This is still happening with `routePrefix` set.
```
time="2017-06-09T12:26:08Z" level=error msg="Error sending alerts: bad response status 404 Not Found" alertmanager="http://1.1.1.1:9093/api/v1/alerts" count=1 source="notifier.go:379"
```
I think an option for the `routePrefix` of Alertmanagers needs to be added in the [AlertmanagerEndpoints](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#alertmanagerendpoints) object. How else can this be fixed in the code?

**Comment by brancz** [comment]
In the latest release of the Alertmanager (v0.7.0) the `-web.route-prefix` flag was introduced. So in the latest Prometheus Operator release we added support for it and default it to root. That way no route prefix has to be configured for any inter cluster communication (including Prometheus itself), while it can still be exposed via ingress for example (with and without path in the external url), kubectl port-forward, or kubectl proxy.

**Comment by galexrt** [comment]
While configuring the Ingress I forgot to add:
```
ingress.kubernetes.io/rewrite-target: "/"
```
But I keep getting 404 on the ingress domain.

***

My Ingress manifest:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zerbytesnet-monitoring-alerts
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: "/"
    ingress.kubernetes.io/auth-type: "basic"
    ingress.kubernetes.io/auth-secret: httpbauth-example-com
    ingress.kubernetes.io/auth-realm: "Authentication Required"
spec:
  tls:
  - hosts:
    - alertmanager.example.net
    secretName: tls-com-example-alertmanager
  rules:
  - host: alertmanager.example.com
    http:
      paths:
      - path: /example
        backend:
          serviceName: alertmanager-example
          servicePort: 9093
```
The alertmanager manifest:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Alertmanager
metadata:
  labels:
    alertmanager: example
  name: main
spec:
  replicas: 2
  version: v0.7.0
  externalUrl: https://alertmanager.example.com/example
```
When I navigate to `https://alertmanager.example.com/example`, I get:
```
404 page not found
```
