### ISSUE TITLE
Add PodMonitor

### ISSUE THREAD

**Issue by fabxc** [coreos/prometheus-operator#38]
We should have a PodMonitor to, using the `pod` role in the Prometheus config. That solves monitoring pods running the same application but which are only partially belong to a service, e.g. quarantined pods.
This should be easy enough and would look exactly like the service monitor only with different selector semantics:

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: PodMonitor
metadata:
  name: frontend
  labels:
    tier: frontend
spec:
  selector:
    # label selector as in ServiceMonitor but doesn't select services of which we discover pods
    # but directly selects pods.
  endpoints:
    # similar to ServiceMonitor, just we don't differentiate between target ports and service ports.
```

This now has to be included into a Prometheus TPR and would happen just like for ServiceMonitors (x-ref: #37).
Now we have two selectors in there (or two lists of selectors) to select different resource types. Another option would be to have a single selector applying to ServiceMonitors and PodMonitors. A single selector applying to two different resource types is quite implicit and hence not too great. OTOH, as a user I don't really care about what type the monitor is.

Another option would be to consolidate both in a single Monitor.

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: Monitor
metadata:
  name: frontend
  labels:
    tier: frontend
spec:
  pods:
    # label selector working on pods
  services:
    # label selector working on service endpoints
  endpoints:
    # similar to ServiceMonitor, just we don't differentiate between target ports and service ports.
```

Seems interesting first but I believe it will constrain us in the long run by colliding options that only apply to either, i.e. I'd like to allow specifying service blackbox probing at some point.

Thoughts on any of these options and ideas?

@matthiasr @grobie @brian-brazil @brancz

**Comment by brian-brazil** [comment]
I'd be a bit wary of mixing in `services` with the other way, as the way things will be done with blackbox will be very different to how they work elsewhere even with a simplified config.

**Comment by brian-brazil** [comment]
Thinking a little more, `PodMonitor` seems sanest to me on the same grounds as why we split out `role` for k8 SD in Prometheus.

**Comment by fabxc** [comment]
Yes, I think mixing both into one `Monitor` is disqualified.
Remains the question of whether the selector(s) in Prometheus should include ServiceMonitor and PodMonitor or there should be separate selector(s) for each.

**Comment by brancz** [comment]
I can see how we can have just one group of selector(s), but I think for a user that's not as easily digestible, as it would be selecting different types of objects. I think having two separate ones is easier to understand and likely less unwanted requests on the k8s API.

**Comment by matthiasr** [comment]
what @brancz says

**Comment by brancz** [comment]
I've been thinking of the `PodMonitor` and `SerivceMonitor` and something I keep coming back to is that actually the only thing that makes them differ is the difference of APIs they use to discover targets, other than that, the definitions seem to be the same. I might be overlooking something but I feel like we should rather than having multiple TPRs (`XMonitor`) have a single `Target` TPR that within itself has a `type` that decides, whether the targets are discovered through `Endpoints` or `Pod`s as the means of [selecting](https://github.com/coreos/prometheus-operator/blob/master/Documentation/service-monitor.md#servicemonitorspec) and [configuration](https://github.com/coreos/prometheus-operator/blob/master/Documentation/service-monitor.md#endpoint) seem to be the same. Thoughts @matthiasr @fabxc @brian-brazil ?

**Comment by brancz** [comment]
In that case a single selector for `Target`s in the Prometheus TPR is what we would want instead.

**Comment by fabxc** [comment]
I had similar thoughts before. What's speaking against unifying them for me is that it forever restricts us to having the same parameters for either. It seems fine now, but the first obvious case coming to mind is blackbox probing.

Probing pods (directly or those backing service endpoints) works for either. But one could also probe the service IP to have a view one it more similar to that of a user.

There could probably be more in the future and I'm not sure folding 2 parameters in the Prometheus TPR into one is enough benefit to justify the rigidness.

**Comment by matthiasr** [comment]
I'd rather have different types than a type value. What would be the
benefit for users from having them one type?

**Comment by brancz** [comment]
I was a bit blinded by trying not to repeat ourselves and not having to maintain and version two different TPRs, but in the end you two are probably right that it would bite us at some point.

**Comment by TamalSaha** [comment]
I wanted to add a note that pod monitors are inadequate when labels are dynamically assigned by Kubernetes. One such example is [CronJobs](https://kubernetes.io/docs/user-guide/cron-jobs/). Please see discussions in #144 .

**Comment by brancz** [comment]
From my understanding (having never used CronJobs so far) you can still specify labels each `Pod` should have, and then you can just select by that subset.

**Comment by TamalSaha** [comment]
Hi,
I just tested with a CronJob is GKE. I want to conform that it is possible to assign labels to dynamically created pods in the CronJob YAML file. So, once pod monitor support is added, CronJobs can be scrapped using this operator. 

The YAML file I tried is:
```yaml
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: hi
  labels:
    app: hi2cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: hijob
    spec:
      template:
        metadata:
          labels:
            app: hipods
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```
