### ISSUE TITLE
All Prometheus' targets are omitted if any single ServiceMonitor is configured incorrectly

### ISSUE THREAD

**Issue by jollinshead** [coreos/prometheus-operator#380]
We had:
- prometheus-operator running in its own namespace
- multiple ServiceMonitors in different namespaces which allowed Prometheus to scrape metrics from various sources

...however, when a new ServiceMonitor was created with a port number used (rather than the port name) all targets are removed from Prometheus. 
```

- apiVersion: monitoring.coreos.com/v1alpha1
  kind: ServiceMonitor
  metadata:
    labels:
      app: seahorse-generic-app
    name: seahorse-generic-app
    namespace: seahorse
  spec:
    endpoints:
    - port: 80
    selector:
      matchLabels:
        release: seahorse
```
We understand port numbers are invalid (only names are valid), but the invalid configuration should not have cleared all targets in Prometheus.

FYI the error we saw in the prometheus-operator pod's logs was:
```
github.com/coreos/prometheus-operator/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1alpha1.ServiceMonitor: json: cannot unmarshal number into Go struct field Endpoint.port of type string
```
