### ISSUE TITLE
[Suggestion] Apply service-monitor labels to the targets

### ISSUE THREAD

**Issue by Karnich** [coreos/prometheus-operator#382]
Since the removal of automatic relabelling of Pod and Service labels onto targets, i have been looking for a new way to get labels to the target without having to join with the kube-state-metrics. 

I have arranged my service monitors by products. Basically the labels the service monitor looks for should not change, and therefore making it possible to apply labels to the targets through the service-monitor wont cause the issue that the automatic relabelling was causing.

I could see it being done either through the standard labels in the metadata (probably filtering the label thats used for discovery) or as a new field in the spec..

thoughts?

**Comment by brancz** [comment]
Are you thinking of a static list of labels that would be added to the targets where you specify both key and value, or were you thinking of while-listing labels of Pods that should be relabeled onto the targets?

**Comment by Karnich** [comment]
i was thinking both the key and the value. maybe prefix the key with sm_ or something like previously where pod_ was prefixed because it was pod labels?

whitelisting could also be a possibility, but i think that approach is tedious when having many labels?

example: 

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: go
  namespace: monitoring
  labels:
    k8s-apps: https // this value doesnt get relabelled since its the selector used for discovery
    product: go  // could go here. label could be sm_product: go
spec:
  jobLabel: k8s-app
  labels
    -  name: product
        value: go    // or like this
  selector:
    matchExpressions:
    - {key: product, operator: In, values: [go]}
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: web
    interval: 30s
```
