### ISSUE TITLE
Namespace constraints

### ISSUE THREAD

**Issue by fabxc** [coreos/prometheus-operator#39]
The Prometheus TPR includes ServiceMonitors via label selection. It only selects ServiceMonitors that are in the same namespace as the Prometheus TPR. That is aligned with semantics of other Kubernetes resources and there seems little reason to diverge from that.

ServiceMonitors select Services by label selection. These label selection work across all namespaces. There are very valid use cases for this, such as meta-monitoring. In the general case however, namespaces are expected to provide isolation and I'd expect my setup to not be negatively affected by actions of other people in their own namespaces.

It seems like we have three use cases:
1. Consider services from same namespace as ServiceMonitor (and transitively Prometheus)
2. Consider services from a subset of namespaces, e.g. a prod and dev namespace
3. Consider services from all namespaces, e.g. meta-monitoring

Currently we only have 3.

How do we want to expose the other options to users? Do we select multiple namespaces by simply providing a list of them or do we also allow selecting them by label, e.g. so that I can select all namespaces belonging to my team?
Label selectors are always more dynamic, but they come with a cost of complexity and should be compared to their likely real-world benefit. For example, Alertmanager services are added to Prometheus TPRs by simple namespace/name references rather than label selection.

I think selecting all namespaces by default, as it is now is potentially dangerous and should only be done explicitly. My current idea looks as follows:

```yaml 
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: frontend
  labels:
    tier: frontend
spec:
  # Simple list of namespaces to select services from.
  namespaces: <string array>
  # Explicit enabling of all namespaces.
  allNamespace: <bool>
  # Dynamic selection could be added later relatively seamlessly
  # if there's an actual need?
  namespaceSelector: <label selector>
  # The above are mutually exclusive. If none is provided, default to just selecting within
  # ServiceMonitors namespace?
  
  # Should this be `serviceSelector` then for explicitness?
  # Other Kubernetes resources stick with just `selector` where reasonable.
  selector:
    # label selector of services
  endpoints:
    # ...
```

This is merely one idea. Would be great if anyone can think of something smarter and can verify what I said against their real-world experience.

@matthiasr @grobie @brancz @brian-brazil

**Comment by matthiasr** [comment]
Yes, the provided config sample looks like what I would expect (except for camelCase vs. snake_case but that's a matter of style and I see that this matches Kubernetes style better). It should be `allNamespaces`. `namespaceSelector` can come later, but I see how it would be useful. In our case, we could do without it by selecting on labels across all namespaces.

The selection of ServiceMonitors in the Prometheus object should allow the same options.

This is not the only way to skin this cat, but here's my use case: I would expect the ServiceMonitor, i.e. the description of the monitored service, to be part of that service and live in its namespace. It is owned by the owners of that service (assume that they _only_ have write access to this one namespace). A Prometheus could be namespace-local (i.e. use default behaviour and be in the same namespace) if it's deployed as an application component.

Or it could be spanning multiple systems and therefore select ServiceMonitor from multiple namespaces (either globally with label-matching or explicitly listed). This Prometheus might be operated by a _different_ team, who are only allowed to write to the namespace Prometheus is in, _not_ the application namespace. This team may also not know about the specifics of how to scrape this service and should not need to, since that is already set in the existing ServiceMonitor.

**Comment by matthiasr** [comment]
So to summarize, both ServiceMonitor and Prometheus should default to the local namespace, that's the best default assumption. Both should offer the option to go beyond that.

**Comment by brancz** [comment]
I can also see the necessity for both and I feel that in highly audited environments it's required to limit the namespaces accessed. Reminds me of openshift [using authz](https://github.com/prometheus/prometheus/issues/1951#issuecomment-249184537) which had previously introduced problems for users. However that would require changes in prometheus/prometheus and here.

**Comment by fabxc** [comment]
I see the point of wanting the same semantics for ServiceMonitors. That's basically the route for full decoupling/normalization, which is appealing in its possibilities but also increases the risk of shooting yourself in the foot. 

In general I think some degree of duplication is fine – it's quite common across Kubernetes core resources. And even with the semantics you suggest, there's theoretically more to decouple. For example, endpoints to monitor a service vs. the scrape interval – including a service monitor from another team doesn't necessarily mean I want their scrape interval too. I also might only want to monitor one of two metric endpoints of service pods, or use different scrape query params, or include different alerting rules into my setup (yet to come).
My original idea leaned towards duplicating the ServiceMonitor and adjusting its specifics as desired for the respective monitoring setup – in favour or being easier to understand. You'd act similar about running your own deployment of an application another team is developing (health checks, resource limits, etc. would just be duplicated and not be canonically provided in their separate resource by authoring team).
I certainly don't want to get into the business of overwrites and precedence levels.

If we decouple and normalize along all axis, we are back at square one where configuration becomes hard to reason about and get right.

Secondly, if I explicitly include services from other namespaces, that's one level to reason about. Including SerivceMonitors from other namespaces I've no control over, that might in return include services from all namespaces, is extremely dangerous IMO. The second level of indirection gives me virtually no ground to reason about what my Prometheus server will actually end up monitoring.
Anyone, with good or bad intent, can at runtime render all Prometheus servers making use of such a feature useless. He doesn't even need a lot of permissions or deploy new pods to increase load cluster-wide.

There's a clear use case today about cross-namespace selection of services from ServiceMonitors. I understand the reasoning to apply the same to Prometheus<>ServiceMonitor relationships but am extremely wary about its implications and would only reconsider after some detailed use case reports.
Defaulting to the safe path certainly helps though.

**Comment by matthiasr** [comment]
Sure, if you consume a ServiceMonitor you don't control you take on some risk. You do that when you consume even a single metrics endpoint you don't control though – they might just blow up their label dimensions in the same way. I would not advocate doing this in an open environment, but in a close-knit one like SoundCloud this would probably work and it would definitely fit our model better.

I see your point about maybe not wanting all the settings the other team chose, but in that case I just need to use my own ServiceMonitor – having the "local vs. all namespaces" choice in both levels makes that still possible. But I should not _have_ to.

**Comment by brian-brazil** [comment]
The use cases I see for allNamespaces are 1) metamon as a centralised service and 2) you control all namespaces in the cluster. For the former what you scrape will be quite locked down, so while there's still a DoS risk from a bad actor you're probably okay. In the latter case you control everything, so no problems there.

For other multi-namespace cases, I think it'd be a simple hardcoded list of namespaces - possibly a regex - as you'd probably want to explicitly whitelist. As each namespace would be assigned from your user/group management system and namespaces may or may not follow a pattern, and may or may not be scoped based on labels.

Needing 3 options for all this feels a bit much. Could the `namespaces` and `namespaceSelector` be squashed together?

**Comment by fabxc** [comment]
Okay, I think we can all agree on namespacing configuration in the Monitors – for the same in Prometheus, we should let some time pass to figure out more people's requirements.

I also feel like 3 is a lot. But the[ label selector type](http://kubernetes.io/docs/api-reference/v1/definitions/#_unversioned_labelselector) is well-known in Kubernetes and what I've seen so far is people just labeling their resources with `name = <resource name>` to access it via label selections.
But I think labeling of namespaces is not super common at this point. It's hard to estimate how inclined people are to consider the Prometheus operator in their labeling practices.

What we could do is extend the [label selector type](http://kubernetes.io/docs/api-reference/v1/definitions/#_unversioned_labelselector) like:

```yaml
namespaceSelector:
  matchLabels: # as usual
  matchExpressions: # as usual
  matchNames: <string array>
```

It would essentially just drag it one level lower. At this point one might just as well include the `allNamespaces` option as well:

```yaml
namespaceSelector:
  any: <bool> # any vs all ...?
  matchLabels: # as usual
  matchExpressions: # as usual
  matchNames: # as above
```

There's probably some simplicity to it as it keeps the top-level spec clean and within the selector it's a more intuitive understanding that all four options are `AND`ed (at least that's how I'd implement it).

**Comment by fabxc** [comment]
Any label selection by the way, will require us to implement this partially in the operator as Prometheus meta labels don't expose namespace labels.

I can see how this would be generally useful to have in the Prometheus upstream integration, though I feel it would take it a bit too far as we'd be pulling in data from another resource. @brian-brazil @jimmidyson

**Comment by brian-brazil** [comment]
I see no problem with exposing this in principle in the k8 SD. Might be best to wait a bit to see if anyone actually requests it though.

**Comment by fabxc** [comment]
Yes, I decided to go with:

```yaml
namespaceSelector:
  any: <bool>
  matchNames: <string array>
```

for the operator for now and wait for label selection to be actually requested for it.
