### ISSUE TITLE
basicAuth secret configuration is backwards

### ISSUE THREAD

**Issue by archSeer** [coreos/prometheus-operator#402]
The [BasicAuth section of the API docs](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#basicauth) says that [v1.SecretKeySelector scheme](https://kubernetes.io/docs/api-reference/v1.6/#secretkeyselector-v1-core) from Kubernetes is used. Based on that spec, the `name` is the name of the secret to use, and `key` is the key inside that secret. I specified it accordingly, and my metrics collection kept silently failing with no errors in any of the logs:

```
spec:
  endpoints:
  - basicAuth:
      password:
        name: prometheus-basic-auth
        key: password
      username:
        name: prometheus-basic-auth
        key: username
# ...
```

Then I came across some of the user guide examples, the `name` and `key` fields are actually reversed in prometheus-operator:

https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/basic-auth.md#basic-auth-for-targets

Swapping the key names, everything started working:

```
spec:
  endpoints:
  - basicAuth:
      password:
        key: prometheus-basic-auth
        name: password
      username:
        key: prometheus-basic-auth
        name: username
# ...
```
