### ISSUE TITLE
Exceptionally high IO for Prometheus  

### ISSUE THREAD

**Issue by hasanatkazmi** [coreos/prometheus-operator#438]
**What did you do?**

Deployed Prometheus operator with 8G memory and 40G persistent volume. Cluster has few more deployments running. In an empty cluster, Prometheus works as expected.

**What did you see instead? Under which circumstances?**

I am seeing high CPU, IO and network usage for Prometheus. 
From within Prometheus pod, I can see upto 50 Mbits/s IO, where as the node where this pods runs show upto 100Mbps IO for Prometheus process. 

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T23:29:08Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

```

* Kubernetes cluster kind: 

	GKE

* Manifests:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: k8s
  namespace: monitoring
  labels:
    prometheus: k8s
spec:
  replicas: 1
  version: v1.6.3
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpression:
    - {key: k8s-apps, operator: Exists}
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: k8s
  resources:
    requests:
      memory: 8Gi
  storage:
    resources:
      requests:
        storage: 40Gi

```

* Prometheus Operator Logs:

```
time="2017-06-21T22:44:21Z" level=info msg="Build context (go=go1.8.1, user=root@a6410e65f5c7, date=20170522-09:15:06)" source="main.go:89" 
time="2017-06-21T22:44:21Z" level=info msg="Loading configuration file /etc/prometheus/config/prometheus.yaml" source="main.go:251" 
time="2017-06-21T22:44:23Z" level=info msg="Loading series map and head chunks..." source="storage.go:421" 
time="2017-06-21T22:44:26Z" level=info msg="135762 series loaded." source="storage.go:432" 
time="2017-06-21T22:44:26Z" level=info msg="Starting target manager..." source="targetmanager.go:61" 
time="2017-06-21T22:44:26Z" level=info msg="Listening on :9090" source="web.go:259" 
time="2017-06-21T22:44:26Z" level=info msg="Using pod service account via in-cluster config" source="kubernetes.go:94" 
time="2017-06-21T22:44:26Z" level=info msg="Using pod service account via in-cluster config" source="kubernetes.go:94" 
time="2017-06-21T22:44:26Z" level=info msg="Using pod service account via in-cluster config" source="kubernetes.go:94" 
time="2017-06-21T22:44:26Z" level=info msg="Using pod service account via in-cluster config" source="kubernetes.go:94" 
time="2017-06-21T22:44:26Z" level=info msg="Using pod service account via in-cluster config" source="kubernetes.go:94" 
time="2017-06-21T22:44:26Z" level=info msg="Using pod service account via in-cluster config" source="kubernetes.go:94" 
time="2017-06-21T22:44:26Z" level=info msg="Using pod service account via in-cluster config" source="kubernetes.go:94" 
time="2017-06-21T22:44:26Z" level=info msg="Using pod service account via in-cluster config" source="kubernetes.go:94" 
time="2017-06-21T22:44:26Z" level=info msg="Using pod service account via in-cluster config" source="kubernetes.go:94" 
time="2017-06-21T22:49:26Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:633" 
time="2017-06-21T22:49:31Z" level=info msg="Done checkpointing in-memory metrics and chunks in 4.558714474s." source="persistence.go:665" 
time="2017-06-21T22:54:31Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:633" 
time="2017-06-21T22:54:35Z" level=info msg="Done checkpointing in-memory metrics and chunks in 4.305984062s." source="persistence.go:665" 
time="2017-06-21T22:59:35Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:633" 
time="2017-06-21T22:59:39Z" level=info msg="Done checkpointing in-memory metrics and chunks in 3.889980669s." source="persistence.go:665" 
time="2017-06-21T23:04:39Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:633" 
time="2017-06-21T23:04:43Z" level=info msg="Done checkpointing in-memory metrics and chunks in 3.869655999s." source="persistence.go:665" 
```
