### ISSUE TITLE
helm/alertmanager: Template renders invalid YAML with resources defined

### ISSUE THREAD

**Issue by bzub** [coreos/prometheus-operator#446]
**What did you do?**
```
helm install --namespace monitoring --name am opsgoodness/alertmanager -f values.yaml
```

**What did you expect to see?**
Successful helm install step.

**What did you see instead? Under which circumstances?**
When I specify resources in values.yaml like so:
```yaml
resources:
  requests:
    memory: 400Mi
```
I get this error installing:
```
Error: YAML parse error on alertmanager/templates/alertmanager.yaml: error converting YAML to JSON: yaml: line 18: did not find expected key
```
And with --debug I can see the YAML that was generated is invalid due to comments in the template:
```yaml
# Source: alertmanager/templates/alertmanager.yaml   
apiVersion: monitoring.coreos.com/v1alpha1           
kind: Alertmanager                                   
metadata:                                            
  labels:                                            
    alertmanager: am                                 
    app: alertmanager                                                                                                                                                                                                    chart: alertmanager-0.0.1                                                                                                                                                                                        
    heritage: Tiller                                                                                                                                                                                                 
    release: am                                                                                                                                                                                                      
  name: am
spec:
  baseImage: "quay.io/prometheus/alertmanager"
  externalUrl: "https://alert.zbrbdl.com"
#
  paused: false
  replicas: 1
#   resources:
#     requests:
      memory: 400Mi

  storage:
    class: rbd
    resources:
      requests:
        storage: 2Gi

  version: "v0.7.1"
```

**Environment**

* Kubernetes version information:
kubectl version
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.5", GitCommit:"490c6f13df1cb6612e0993c4c14f2ff90f8cdbf3", GitTreeState:"clean", BuildDate:"2017-06-14T20:15:53Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.5-dirty", GitCommit:"490c6f13df1cb6612e0993c4c14f2ff90f8cdbf3", GitTreeState:"dirty", BuildDate:"2017-06-15T14:44:51Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

bootkube

* Manifests:
values.yaml
```yaml
## Alertmanager configuration directives
## Ref: https://prometheus.io/docs/alerting/configuration/
##
config:
  global:
    resolve_timeout: 5m

  receivers:
    - name: webhook
      webhook_configs:
        - url: 'https://webhook.alert.zbrbdl.com:30500/'

  route:
    group_by: ['job']
    group_interval: 5m
    group_wait: 30s
    receiver: webhook
    repeat_interval: 12h

## External URL at which Alertmanager will be reachable
##
externalUrl: "https://alert.zbrbdl.com"

## Alertmanager container image
##
image:
  repository: quay.io/prometheus/alertmanager
  tag: v0.7.1

ingress:
  ## If true, Alertmanager Ingress will be created
  ##
  enabled: true

  ## Annotations for Alertmanager Ingress
  ##
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"

  fqdn: "alert.zbrbdl.com"

  ## TLS configuration for Alertmanager Ingress
  ## Secret must be manually created in the namespace
  ##
  tls: []
    # - secretName: alertmanager-general-tls
    #   hosts:
    #     - alertmanager.example.com

## Node labels for Alertmanager pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## If true, the Operator won't process any Alertmanager configuration changes
##
paused: false

## Number of Alertmanager replicas desired
##
replicaCount: 1

## Resource limits & requests
## Ref: https://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 400Mi

service:
  ## Annotations to be added to the Service
  ##
  annotations: {}

  ## Cluster-internal IP address for Alertmanager Service
  ##
  clusterIP: ""

  ## List of external IP addresses at which the Alertmanager Service will be available
  ##
  externalIPs: []

  ## External IP address to assign to Alertmanager Service
  ## Only used if service.type is 'LoadBalancer' and supported by cloud provider
  ##
  loadBalancerIP: ""

  ## List of client IPs allowed to access Alertmanager Service
  ## Only used if service.type is 'LoadBalancer' and supported by cloud provider
  ##
  loadBalancerSourceRanges: []

  ## Port to expose on each node
  ## Only used if service.type is 'NodePort'
  ##
  nodePort: 39093

  ## Service type
  ##
  type: ClusterIP

## Alertmanager StorageSpec for persistent data
## Ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/prometheus.md#storagespec
##
storageSpec:
  class: rbd
  resources:
    requests:
      storage: 2Gi
#   selector: {}
  # volumeClaimTemplate:
  #   storageClassName: rbd
  #   resources:
  #     requests:
  #       storage: 1Gi
```

* Prometheus Operator Logs:
none
