### ISSUE TITLE
error from kube: a container name must be specified for pod

### ISSUE THREAD

**Issue by ketzacoatl** [coreos/prometheus-operator#467]
**What did you do?**

Use `helm install` to install `opsgoodness/prometheus-operator`, and then `kubectl apply -f` to deploy an instance of prometheus using the resource spec included below.

**What did you expect to see?**

The `prometheus-operator` create a PVC and an instance of Prometheus (StatefulSet with pod/etc), and then available for use.

**What did you see instead? Under which circumstances?**

The PVC is created, eventually attached to the pod, and but the pod fails:

```
Error from server (BadRequest): a container name must be specified for pod prometheus-foo-0, choose one of: [prometheus prometheus-config-reloader]
```

**Environment**

* Kubernetes version information:

```
	$ kubectl version
	Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
	Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	kops 1.6.x running kube 1.6.x, no RBAC.

* Manifests:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: foo
  labels:
    prometheus: foo-prod
spec:
  externalLabels:
    prometheus: foo-prod
  serviceMonitorSelector:
    matchLabels:
      env: foo-prod
  version: v1.7.1
  replicas: 1
  resources:
    requests:
      memory: 768Mi
    limits:
      memory: 1792Mi
  retention: '90d'
  storage:
    class: gp2
    resources:
      requests:
        storage: 15Gi
```

* Prometheus Operator Logs:

```
ts=2017-07-06T20:45:32Z caller=operator.go:215 component=prometheusoperator msg="connection established" cluster-version=v1.6.4
ts=2017-07-06T20:45:32Z caller=operator.go:131 component=alertmanageroperator msg="connection established" cluster-version=v1.6.4
ts=2017-07-06T20:45:32Z caller=operator.go:1027 component=prometheusoperator msg="TPR created" tpr=service-monitor.monitoring.coreos.com
ts=2017-07-06T20:45:32Z caller=operator.go:522 component=alertmanageroperator msg="TPR created" tpr=alertmanager.monitoring.coreos.com
ts=2017-07-06T20:45:32Z caller=operator.go:1027 component=prometheusoperator msg="TPR created" tpr=prometheus.monitoring.coreos.com
ts=2017-07-06T20:45:35Z caller=operator.go:145 component=alertmanageroperator msg="TPR API endpoints ready"
ts=2017-07-06T20:45:38Z caller=operator.go:229 component=prometheusoperator msg="TPR API endpoints ready"
ts=2017-07-06T20:46:30Z caller=operator.go:266 component=prometheusoperator msg="Prometheus added" key=ops/foo
ts=2017-07-06T20:46:30Z caller=operator.go:614 component=prometheusoperator msg="sync prometheus" key=ops/foo
ts=2017-07-06T20:46:30Z caller=operator.go:954 component=prometheusoperator msg="creating configuration"
ts=2017-07-06T20:46:31Z caller=operator.go:614 component=prometheusoperator msg="sync prometheus" key=ops/foo
ts=2017-07-06T20:46:31Z caller=operator.go:965 component=prometheusoperator msg="updating config skipped, no configuration change"
```
