### ISSUE TITLE
Cannot remove alert rule from prometheus

### ISSUE THREAD

**Issue by cofyc** [coreos/prometheus-operator#484]
**What did you do?**

Remove a alert rule `K8SApiServerLatency` from config map, `<myname>-exporter-kube-api`.

**What did you expect to see?**

Expect this alert rule is removed from prometheus.

**What did you see instead? Under which circumstances?**

This alert rule is still in prometheus configuration.

**Environment**

Linux.

* Kubernetes version information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T20:41:07Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	kubeadm

* Manifests:

NONE

* Prometheus Operator Logs:

NONE

I entered into prometheus container, and saw two `kube-api` rules:

- /etc/prometheus/rules/rules-0/kube-api.rules # which is old
- /etc/prometheus/rules/rules-1/kube-api.rules # which is new without `K8SApiServerLatency` alert

Why there are two versions of `kube-api` rule rule?
How can I remove alert rule from prometheus?

**Comment by brancz** [comment]
I'm not sure I understand correctly, how are the two files you mentioned different? The filenames seem to be identical, so I don't understand how the files can differ. Prometheus will attempt to load whatever is in the ConfigMaps that are mounted, so I'm guessing you have additional ConfigMaps by accident.

**Comment by cofyc** [comment]
@brancz Sorry, I had a typo, the second file is under `rules-1` directory, not `rules-0`. There are two files with different contents.

I checked all my ConfigMaps by executing `kubectl get --all-namespaces cm`, there is only one `<myname>-exporter-kube-api` ConfigMap object.

**Comment by brancz** [comment]
Could you share your Prometheus manifest?

**Comment by cofyc** [comment]
@brancz 

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  labels:
    app: prometheus
    chart: prometheus-0.0.1
    heritage: Tiller
    prometheus: xxx
    release: xxx
  name: xxx
spec:
  alerting:
    alertmanagers:
      - namespace: default
        name: xxx-alertmanager
        port: http
  baseImage: "quay.io/prometheus/prometheus"
  externalUrl: http://<my-prometheus-url>/
  paused: false
  replicas: 1
  resources:
    requests:
      memory: 150Mi

  retention: "24h"
  routePrefix: "/"
  serviceMonitorSelector:
    matchLabels:
      app: prometheus
      prometheus: xxx
  ruleSelector:
    matchLabels:
      app: prometheus
      prometheus: xxx
  storage:
    accessMode: ReadWriteOnce
    class: rbd
    resources:
      requests:
        storage: 1Gi

  version: "v1.5.2"
```
