### ISSUE TITLE
Stable version for prometheus-operator and prometheus to work with

### ISSUE THREAD

**Issue by linhdsv** [coreos/prometheus-operator#524]
Guys, which versions of both prometheus-operator and prometheus are stable atm?
Because I'm using both latest versions and some function not working properly
e.g Targets page does not show my own service when using ServiceMonitor even though I follow strictly the user guideline, or The config-reloader not auto-reload configuration file whenever I update it.

**Comment by linhdsv** [comment]
- File Prometheus config:
```yml
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      service-monitor: example-app
  version: v1.4.1
  resources:
    requests:
      memory: 400Mi
```
- File ServiceMonitor:
```yml
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: service-monitor-example-app
  labels:
    service-monitor: example-app
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: example-app
  endpoints:
  - port: web
    interval: 10s
```
- My own service:
```yml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: xxx
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  labels:
    app: example-app
  name: example-app
  namespace: staging
spec:
  ports:
  - name: http
    nodePort: 31834
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 31909
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: example-app
  sessionAffinity: None
  type: LoadBalancer
```
- Here's my rules:
```yml
scrape_configs:
- job_name: staging/service-monitor-example-app/0
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - api_server: null
    role: endpoints
    namespaces:
      names: []
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_label_app]
    separator: ;
    regex: example-app
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: staging
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: web
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: ${1}
    action: replace
  - source_labels: []
    separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: web
    action: replace
```
