### ISSUE TITLE
Prometheus Spec Metadata does not propagates to pods

### ISSUE THREAD

**Issue by jescarri** [coreos/prometheus-operator#580]
**What did you do?**

Created a prometheus with the following configuration:

````
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  labels:
    environment: "dev1"
    heritage: Tiller
    inventorycode: ""
    release: foo
    prometheus: bar
    app: prometheus
    productcode: foobar
  name: jesus1
  annotations:
    iam.amazonaws.com/role: access_role_describe_instances
spec:
  version: v1.7.1
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: dev1
  externalUrl: http://foo.bar
  replicas: 1
  retention: 12h
  resources:
    requests:
      memory: 3000Mi
    limits:
      memory: 3000Mi
````

**What did you expect to see?**

Prometheus pods with the annotations defined in the Prometheus.Meta spec.

**What did you see instead? Under which circumstances?**

Only the metadata added by prometheus-operator.

````
kubectl -n prd354-jesus1 get pods -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubernetes.io/created-by: |
        {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"StatefulSet","namespace":"jesus1","name":"prometheus-jesus1","uid":"f2176411-8922-11e7-8c51-0ec01cdb4cce","apiVersion":"apps/v1beta1","resourceVersion":"4620005"}}
    creationTimestamp: 2017-08-24T23:21:24Z
    generateName: prometheus-jesus1-
    labels:
      app: prometheus
      controller-revision-hash: prometheus-jesus1-1876494588
      prometheus: jesus1
    name: prometheus-jesus1-0
    namespace: jesus1
    ownerReferences:
````
**Environment**

* Kubernetes version information:

	tectonic v1.7.1

* Kubernetes cluster kind: 

      tectonic-installer.

* Manifests:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  labels:
    environment: "dev1"
    heritage: Tiller
    inventorycode: ""
    release: foo
    prometheus: bar
    app: prometheus
    productcode: foobar
  name: jesus1
  annotations:
    iam.amazonaws.com/role: access_role_describe_instances
spec:
  version: v1.7.1
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: dev1
  externalUrl: http://foo.bar
  replicas: 1
  retention: 12h
  resources:
    requests:
      memory: 3000Mi
    limits:
      memory: 3000Mi```

* Prometheus Operator Logs:

```
Not relevant, operator creates the prometheus.
```
