### ISSUE TITLE
[ kube-prometheus ] Kubernetes scheduler and controller manager pods have no service which match the related kube-prometheus servicemonitor 

### ISSUE THREAD

**Issue by csahli** [coreos/prometheus-operator#583]
I deployed a kubernetes cluster (v1.6.7 multi master cluster) using kubespray and then deployed the kube-prometheus (v0.11). Everything was fine but I get some alerts visible on promDash UI. Alerts were related to k8s scheduler and controller unavailability.

To solve the problem I just deployed kubernetes service to target kube-scheduler and kube-controller pods with labels matching related servicemonitor label selectors.

This cleared prometheus alerts and make k8s scheduler and controller metrics available.

Here the k8s manifests I have to add:

- kube-controller-manager-service.yml

```
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-controller-manager
  name: kube-controller-manager
  namespace: kube-system
spec:
  ports:
  - name: http-metrics
    port: 10252
    targetPort: 10252
  selector:
    k8s-app: kube-controller
```

- kube-scheduler-service.yml

```
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-scheduler
  name: kube-scheduler
  namespace: kube-system
spec:
  ports:
  - name: http-metrics
    port: 10251
    targetPort: 10251
  selector:
    k8s-app: kube-scheduler
```
