### ISSUE TITLE
prometheus-config-reloader - can't update  / apply rules (main.go:214 | 500)

### ISSUE THREAD

**Issue by hartmut-pq** [coreos/prometheus-operator#597]
**What did you do?**
run Prometheus

**What did you expect to see?**
prometheus-config-reloader working

**What did you see instead? Under which circumstances?**
Config & Rules not applied.

**Environment**
branched from `./contrib/kube-prometheus`

* Kubernetes version information:
v1.7.5

* Kubernetes cluster kind: 
kops, AWS

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  labels:
    prometheus: k8s
spec:
  replicas: 2
  version: v1.7.1
  externalUrl: https://monitoring.mydomain.net/prometheus  # needs to be absolute with v1.7.1
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector:
    matchExpressions:
    - {key: k8s-app, operator: Exists}
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: k8s
  resources:
    requests:
      # 2Gi is default, but won't schedule if you don't have a node with >2Gi
      # memory. Modify based on your target and time-series count for
      # production use. This value is mainly meant for demonstration/testing
      # purposes.
      memory: 500Mi
      cpu: 100m
    limits:
      memory: 500Mi
      # cpu: 500m
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-main
      port: web
```

* Prometheus Operator Logs:
```
ts=2017-09-01T12:33:01Z caller=main.go:214 component=volume-watcher msg="Reloading Prometheus temporarily failed." err="Received response code %!s(int=500), expected 200" next-retry=1m18.352306053s
...
```
