### ISSUE TITLE
Documentation confusion

### ISSUE THREAD

**Issue by dmyerscough** [coreos/prometheus-operator#614]
The documentation for the Prometheus Operator seems to be outdated/incorrect. I was reading the user-guides [1] and they have the following example:-

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: example
spec:
  replicas: 2
  alerting:
    alertmanagers:
    - namespace: default
      name: alertmanager-example
      port: web
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: example
```

The `alertmanagers` block seems to have required fields missing as stated in [2].

| Field | Description | Scheme | Required |
| ----- | ----------- | ------ | -------- |
| namespace | Namespace of Endpoints object. | string | true |
| name | Name of Endpoints object in Namespace. | string | true |
| port | Port the Alertmanager API is exposed on. | intstr.IntOrString | true |
| scheme | Scheme to use when firing alerts. | string | true |
| pathPrefix | Prefix for the HTTP path alerts are pushed to. | string | true |

When running the Prometheus Operator without the required fields no errors are thrown, is this expected?

[1] https://coreos.com/operators/prometheus/docs/0.12.0/user-guides/alerting.html
[2] https://github.com/coreos/prometheus-operator/blob/release-0.12/Documentation/api.md#alertmanagerendpoints

**Comment by dmyerscough** [comment]
Ill attach this here to; the troubleshooting guide [1] isn't really a troubleshooting guide as there are no examples on how to actually troubleshoot the Operator e.g. if X is broken run Y to enable debugging etc.

[1] https://coreos.com/operators/prometheus/docs/0.12.0/troubleshooting.html

**Comment by brancz** [comment]
That's actually just a documentation mistake, those fields are not mandatory. Only truly mandatory are `namespace`, `name`, and `port` (which can either be `web`, which is the port of Alertmanager's API for Alertmanager clusters created with the Prometheus Operator or the port number `9093`, by default).

I'm not sure I understand the troubleshooting concern, the entry we have is a common problem people run into with GKE clusters, seems like a valid entry, but I'm happy to improve if you have suggestions.

**Comment by brancz** [comment]
Just to make sure I understand correctly, what is the issue you're facing or rather what are you trying to do?

**Comment by dmyerscough** [comment]
@brancz I have been using the Prometheus Operator and I have hit a lot of issues and going through the documentation hasn't helped.

Let me give you an example; I was configuring the Prometheus Operator to load some custom rules, I received the following error:-

```
ts=2017-09-12T03:44:53Z caller=main.go:207 component=volume-watcher msg="Updating rule files failed." err="decode error status: payload is not a kubernetes protobuf object"
``` 

I traced this error down in GitHub #490 which mentioned rbac rules might not be configured correctly. This type of error should would be beneficial if it was on the troubleshooting page.

Another issue I ran into was configuring Alert Manager; I specified the following:-

```
  alerting:
    alertmanagers:
      - name: alertmanager-main
        namespace: tectonic-system
        pathPrefix: ''
        port: 9093
        scheme: ''
```

My assumption is that the Prometheus Operator would append the correct Alert Manager configuration to `promethues.yaml`?
