### ISSUE TITLE
How to scrape nginx ingress engine statistics?

### ISSUE THREAD

**Issue by paalkr** [coreos/prometheus-operator#617]
Hi

I have successfully deployed the prometheus operator in my kube-aws built Kubernetes 1.6 cluster on AWS, using kube-prometheus 11.1. All default resources are scraped as expected, and the alertmanager and grafana does function correctly. Now I'm trying to set up a ServiceMonitor to scrape statistics from my nginx ingress engine (0.9.0-beta.13), but without success. The nginx ingress engine endpoints does not show up in the prometheus targets list, and no metrics are scraped.

This is my ingress service definition (with the only purpose of scraping metrics). Another service of type LoadBalancer is handling the regular request to my microservices.

```
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: nginx-ingress-prometheus-discovery
  labels:
    k8s-app: ingress-nginx.addons.k8s.io
  annotations:
spec:
  selector:
    app: ingress-nginx
  type: ClusterIP
  clusterIP: None    
  ports:
  - name: metrics
    port: 10254
    targetPort: 10254
```
The endpoints created by the service does provide metrics if queried from any host in my cluster with for example  `curl http://10.200.62.2:10254/metrics`

My ingress engine ServiceMonitor
PS, the ingress engine runs in the default namespace
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: ingress
  labels:
    k8s-app: ingress
spec:
  jobLabel: k8s-app
  endpoints:
  - targetPort: 10254
    interval: 30s
    honorLabels: true
    path: /metrics
  selector:
    matchLabels:
      k8s-app: ingress-nginx.addons.k8s.io
  namespaceSelector:
    matchNames:
    - kube-system
    - default
```

Prometheus deployment
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        image: quay.io/coreos/prometheus-operator:v0.11.1
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
```

Prometheus Operator 
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: k8s
  labels:
    prometheus: k8s
spec:
  replicas: 2
  version: v1.7.0
  serviceMonitorSelector:
    matchExpressions:
    - key: k8s-app
      operator: Exists    
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: k8s
  resources:
    requests:
      # 2Gi is default, but won't schedule if you don't have a node with >2Gi
      # memory. Modify based on your target and time-series count for
      # production use. This value is mainly meant for demonstration/testing
      # purposes.
      memory: 800Mi
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-main
      port: web
```

Any suggestions?

**Comment by brancz** [comment]
There are some approaches to doing this, one is just converting the metrics, that nginx provides via it's status endpoint using the [nginx-vts-exporter](https://github.com/hnlq715/nginx-vts-exporter). This gives you some metrics pretty quickly:

```
# Upstream Requests
nginx_upstream_requests{code="1xx",upstream="XXX-XXXXX-3000"} 0

# Upstream Bytes
nginx_upstream_bytes{direction="in",upstream="XXX-XXXXX-3000"} 0

# Upstream Response time
nginx_upstream_response{backend="10.2.15.10:3000",upstream="XXX-XXXXX-3000"} 99
```

However all metrics are for the entire backend, it's not possible to dissect for example which is the endpoint that errors a lot or has high latency.

@Gouthamve has worked on some experiments to generate some more metrics with a config of endpoints and extracting the required information from the nginx access log: https://github.com/Gouthamve/ingress-mtail-metrics. This is rather experimental though.

Both approaches are best deployed as a sidecar next to the nginx ingress controller containers.

**Comment by paalkr** [comment]
Thanks for the feedback.

I have configured my nginx ingress engine to provide statistics in vts format, and all endpoints provides metrics when queried manually on port 10254 and the path /metrics.

The problem is that I'm not able to get Prometheus to scrap the endpoints.

**Comment by paalkr** [comment]
Issue solved. I had some errors in my service and ServiceMonitor templates.

**Comment by free8gent** [comment]
@paalkr I have a similar issue do you mind posting what you fixed.

**Comment by paalkr** [comment]
Sure, what platform do you run on? AWS?

**Comment by free8gent** [comment]
@paalkr Yes AWS, we have prometheus-operator deployed and can't seem to get the ingress-controller nginx  vts stats scraped. https://github.com/kubernetes/ingress/tree/master/examples/customization/custom-vts-metrics/nginx

I think we have a similar setup

**Comment by emas80** [comment]
I have a similar issue, my ingress service is not discovered by prometheus for some reason.
Please note that I have exactly the same setup on 2 different clusters - ingress, ingress service for prometheus, service monitor. 
With "same setup" I mean literally the same yaml files, those are 2 clusters we use for development and integration testing, and we apply the same exact configuration to those core resources.
So I don't think there are issues with port mapping or labels etc.

This happened after (on the not-working-cluster) after I upgraded prometheus-operator to 0.13.0 from 0.10.2. It was working properly with 0.10.2 and Kubernetes 1.7.2.
The working cluster is still running 0.10.2 and Kubernetes 1.6.7.

In order to upgrade prometheus-operator from 0.10.2 to 0.13.0 I run the "teardown" script from kube-prometheus 0.10.2, and then deploy from 0.13.0.

Please also note that I added a service monitor for the cluster autoscaler, and that one works properly, on both the clusters and on all the prometheus operator versions.

The configuration appears to be correctly updated by looking at prometheus

`- job_name: monitoring/ingress-external/0
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - api_server: null
    role: endpoints
    namespaces:
      names: []
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_label_app]
    separator: ;
    regex: ingress-external
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: http
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_service_label_ingress_external]
    separator: ;
    regex: (.+)
    target_label: job
    replacement: ${1}
    action: replace
  - source_labels: []
    separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: http
    action: replace`

It would be glad to have a way to debug this.

On the logs on the not-working cluster I can see

> component=prometheusoperator msg="syncing nodes into Endpoints object failed" err="synchronizing kubelet endpoints object failed: updating kubelet endpoints object failed: Endpoints \"kubelet\" is invalid: [subsets[0].addresses[0].nodeName: Forbidden: Cannot change NodeName for 172.25.111.117 to ip-172-25-93-34.eu-west-1.compute.internal, subsets[0].addresses[1].nodeName: Forbidden: Cannot change NodeName for 172.25.119.81 to ip-172-25-93-34.eu-west-1.compute.internal, subsets[0].addresses[2].nodeName: Forbidden: Cannot change NodeName for 172.25.121.60 to ip-172-25-93-34.eu-west-1.compute.internal, subsets[0].addresses[3].nodeName: Forbidden: Cannot change NodeName for 172.25.124.29 to ip-172-25-93-34.eu-west-1.compute.internal, subsets[0].addresses[4].nodeName: Forbidden: Cannot change NodeName for 172.25.55.18 to ip-172-25-93-34.eu-west-1.compute.internal, subsets[0].addresses[5].nodeName: Forbidden: Cannot change NodeName for 172.25.58.203 to ip-172-25-93-34.eu-west-1.compute.internal, subsets[0].addresses[6].nodeName: Forbidden: Cannot change NodeName for 172.25.65.86 to ip-172-25-93-34.eu-west-1.compute.internal, subsets[0].addresses[7].nodeName: Forbidden: Cannot change NodeName for 172.25.76.1 to ip-172-25-93-34.eu-west-1.compute.internal]"

I wonder if it is related.

**Comment by paalkr** [comment]
Sorry for the delayed response. First of all you need to make sure that the nodes running Prometheus have access to the nodes running your ingress engine at port 10254. This is done by configuring security groups correctly.

Second, you need to configure scarping endpoints for your ingress engine, and a set of scarping targets. I have the ingress engine running the default namespace, and my config looks like

Ingress services definition for scarping

```
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: nginx-ingress-prometheus-discovery
  labels:
    k8s-app: ingress
spec:
  selector:
    app: ingress-nginx
  type: ClusterIP
  clusterIP: None    
  ports:
  - name: metrics
    port: 10254
    protocol: TCP
```

Scarping targets
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-scraping
  labels:
    k8s-app: ingress
spec:
  jobLabel: k8s-app
  endpoints:
  - port: metrics
    interval: 30s
  selector:
    matchLabels:
      k8s-app: ingress
  namespaceSelector:
    matchNames:
    - default 
```
