### ISSUE TITLE
alertmanager matched, that should not match

### ISSUE THREAD

**Issue by brancz** [coreos/prometheus-operator#62]
I spun up a fresh minikube

```
minikube start --vm-driver="virtualbox" --kubernetes-version="v1.4.3" --memory 2048 --cpus 2
```

Then built the operator from `HEAD`.

```
make container
```

Edited the `deployment.yaml` to use the appropriate image tag (in this case: 4f0fe2d) and created the deployment.

```
kubectl create -f deployment.yaml
```

Waited for the prometheus TPR to be ready by testing with

```
kubectl get prometheus
```

Once they the TPRs were ready I created all resources in `example/`.

```
kubectl create -f example/
```

And to my surprise, the Alertmanager instances were discovered correctly, even though, the configuration says they are called `alertmanager` even though, the Alertmanager cluster resource name is `alertmanager-main`.

I'm unsure whether this is a problem in the operator or upstream. I'm actually thinking it might be upstream as this is the generated configuration, which looks like what I expected, but should not work.

```
alerting:
  alertmanagers:
  - kubernetes_sd_configs:
    - role: endpoints
    relabel_configs:
    - action: keep
      regex: alertmanager
      source_labels:
      - __meta_kubernetes_service_name
    - action: keep
      regex: default
      source_labels:
      - __meta_kubernetes_namespace
    - action: keep
      regex: web
      source_labels:
      - __meta_kubernetes_endpoint_port_name
    scheme: http
global:
  evaluation_interval: 30s
  scrape_interval: 30s
rule_files:
- /etc/prometheus/rules/*.rules
scrape_configs:
- job_name: default/example-app/0
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - action: keep
    regex: example-app
    source_labels:
    - __meta_kubernetes_service_label_app
  - action: keep
    regex: default
    source_labels:
    - __meta_kubernetes_namespace
  - action: keep
    regex: web
    source_labels:
    - __meta_kubernetes_endpoint_port_name
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - action: labelmap
    regex: __meta_kubernetes_service_label_(.+)
    replacement: svc_$1
  - action: replace
    replacement: ""
    target_label: __meta_kubernetes_pod_label_pod_template_hash
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
    replacement: pod_$1
  - replacement: ${1}-web
    source_labels:
    - __meta_kubernetes_service_name
    target_label: job
  scrape_interval: 30s
- job_name: default/node-exporter/0
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - action: keep
    regex: node-exporter
    source_labels:
    - __meta_kubernetes_service_label_app
  - action: keep
    regex: default
    source_labels:
    - __meta_kubernetes_namespace
  - action: keep
    regex: scrape
    source_labels:
    - __meta_kubernetes_endpoint_port_name
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - action: labelmap
    regex: __meta_kubernetes_service_label_(.+)
    replacement: svc_$1
  - action: replace
    replacement: ""
    target_label: __meta_kubernetes_pod_label_pod_template_hash
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
    replacement: pod_$1
  - replacement: ${1}-scrape
    source_labels:
    - __meta_kubernetes_service_name
    target_label: job
```

@fabxc
