### ISSUE TITLE
Setting up federation using servicemonitor (instead of custom config)

### ISSUE THREAD

**Issue by ptagr** [coreos/prometheus-operator#647]
**What did you do?**
I am trying to create a service monitor that would scrape the `/federate` endpoint of another prometheus service. I want all jobs to be included so I am using the param:
match[]: '{__name__=~".+"}'

My Service monitor looks like this:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus
    chart: exporter-prometheus-blackbox-0.1.0
    component: prometheus-blackbox-exporter
    heritage: Tiller
    prometheus: infra-mon-monitoring-dev-123456789
    release: infra-mon-monitoring-dev-123456789
  name: infra-mon-monitoring-dev-123456789-exporter-prometheus-blackbox
  namespace: monitoring-dev
spec:
  endpoints:
  - interval: 15s
    port: http
    path: /federate
    honorLabels: true
    params:
      match[]: 
      - '%7B__name__%3D%7E%22.%2B%22%7D'
  jobLabel: exporter-prometheus-blackbox
  namespaceSelector:
    matchNames:
    - monitoring-dev
  selector:
    matchLabels:
      app: prometheus-blackbox
```

When I create this, the parent prometheus sees this target but somehow the metrics are not imported. I think the params are not being passed correctly.
This is how the job (of the above service monitor) looks like after the parent prometheus identifies the target:

```
- job_name: monitoring-dev/infra-mon-monitoring-dev-123456789-exporter-prometheus-blackbox/0
  honor_labels: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /federate
  scheme: http
  kubernetes_sd_configs:
  - api_server: null
    role: endpoints
    namespaces:
      names:
      - monitoring-dev
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_label_app]
    separator: ;
    regex: prometheus-blackbox
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: http
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_service_label_exporter_prometheus_blackbox]
    separator: ;
    regex: (.+)
    target_label: job
    replacement: ${1}
    action: replace
  - source_labels: []
    separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: http
    action: replace
```

**What did you expect to see?**
I expect the federation to work using this approach

**What did you see instead? Under which circumstances?**

**Environment**
using 
```
image:
  repository: quay.io/prometheus/prometheus
  tag: v1.7.1
```

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.9", GitCommit:"a3d1dfa6f433575ce50522888a0409397b294c7b", GitTreeState:"clean", BuildDate:"2017-08-23T16:58:45Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 
Running on GKE

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
Nothing in the logs
```
