### ISSUE TITLE
Allow configuring .spec.livenessProbe.initialDelaySeconds > 300

### ISSUE THREAD

**Issue by julianvmodesto** [coreos/prometheus-operator#658]
My prometheus db is crash recovering, but the `livenessProbe` restarts the entire Pod since the recovery is taking long for such a large database (`retention: "720h"`).

https://github.com/coreos/prometheus-operator/blob/630941347fc25215a9746ea19576df2faba58287/pkg/prometheus/statefulset.go#L486-L490

Could we set `initialDelaySeconds` higher than 300? Perhaps 900?

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

kops

* Manifests:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  namespace: default
  name: apps
  labels:
    prometheus: apps
spec:
  replicas: 2
  version: v1.7.2
  serviceAccountName: prometheus-apps
  serviceMonitorSelector:
    matchLabels:
      prometheus: apps
  retention: "720h" # 30 days
  resources:
    requests:
      cpu: "1"
      memory: "3Gi"
    limits:
      cpu: "3"
      memory: "5Gi"
  storage:
    class: default
    resources:
      requests:
        storage: 250Gi

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: monitoring
  name: prometheus-operator
  labels:
    operator: prometheus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        operator: prometheus
    spec:
      serviceAccountName: prometheus-operator
      containers:
       - name: prometheus-operator
         image: quay.io/coreos/prometheus-operator:v0.9.1
         args:
         - "--kubelet-service=kube-system/kubelet"
         - "--config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1"
         resources:
           requests:
             cpu: 100m
             memory: 50Mi
           limits:
             cpu: 200m
             memory: 300Mi
```
