### ISSUE TITLE
Prometheus Operator with custom prometheus.yml

### ISSUE THREAD

**Issue by juiceblender** [coreos/prometheus-operator#671]
Hello guys, I'm trying to better understand the behaviour of Prometheus Operator. There are some things I can't quite explain but all that said I'm in no way good at Kubernetes. 

**What did you do?**
I created a Prometheus Operator on a Tectonic Cluster, and an associated dockerized Graphite Exporter. Using ServiceMonitor and checking targets in Prometheus, it does manage to discover my graphite exporter. However, I want to now use this same operator to also monitor instances outside of the Tectonic cluster which are not managed by Tectonic, and all the information I can find online only demonstrates how to monitor pods managed by Tectonic, which is working fine for me. From what I can tell:

i) There's no way to include another configuration file to Prometheus (I've tried putting my extra scrape_config in a .rules file, it didn't like it). 
```
cassandra.rules: |
    global:
      scrape_interval: 30s
      scrape_timeout: 10s
      evaluation_interval: 30s
    rule_files:
    - /etc/prometheus/rules/rules-0/*.rules
    scrape_configs:
    - job_name: cassandra-nodes
        ec2_sd_configs:
        - region: ap-northeast-2
          profile: tectonic-worker-role
          port: 9100

        relabel_configs:
        - action: keep
          source_labels: [__meta_ec2_tag_K8SCluster]
          regex: ForTheGreaterGood*
```
ii) The prometheus.yaml file is automatically created by the operator based on the definition of ServiceMonitor. 

To that end I created a ConfigMap with Prometheus.yaml to try and get Prometheus to reload, with the default which I copy+pasted from Prometheus with my own custom scrape_config tacked on at the bottom:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-prometheus-configmap
  labels:
    prometheus: cassandra
data:
  prometheus.yaml: |
    global:
      scrape_interval: 30s
      scrape_timeout: 10s
      evaluation_interval: 30s
    rule_files:
    - /etc/prometheus/rules/rules-0/*.rules
    scrape_configs:
    - job_name: default/prometheus-graphite/0
      scrape_interval: 30s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      kubernetes_sd_configs: <---- Seems to be that all this was autogenerated by declaring ServiceMonitor
      - api_server: null
        role: endpoints
        namespaces:
          names:
          - default
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_service]
        separator: ;
        regex: prometheus-graphite
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        separator: ;
        regex: prometheus-graphite
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_namespace]
        separator: ;
        regex: (.*)
        target_label: namespace
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (.*)
        target_label: pod
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: service
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: job
        replacement: ${1}
        action: replace
      - source_labels: []
        separator: ;
        regex: (.*)
        target_label: endpoint
        replacement: prometheus-graphite
        action: replace
    - job_name: cassandra-nodes <----- Start of my custom scrape_config
        ec2_sd_configs:
        - region: ap-northeast-2
          profile: tectonic-worker-role
          port: 9100

        relabel_configs:
        - action: keep
          source_labels: [__meta_ec2_tag_K8SCluster]
          regex: ForTheGreaterGood*
```
I applied to my cluster, checked the logs of Prometheus-config-reloader, it was all good: 
```
ts=2017-10-05T23:02:58Z caller=main.go:244 component=volume-watcher msg="ConfigMap modified."
ts=2017-10-05T23:02:58Z caller=main.go:204 component=volume-watcher msg="Updating rule files..."
ts=2017-10-05T23:02:58Z caller=main.go:209 component=volume-watcher msg="Rule files updated."
ts=2017-10-05T23:02:58Z caller=main.go:212 component=volume-watcher msg="Reloading Prometheus..."
```
Prometheus looked great as well: 
```
time="2017-10-05T23:02:00Z" level=info msg="Done checkpointing in-memory metrics and chunks in 44.599677ms." source="persistence.go:665" 
time="2017-10-05T23:02:58Z" level=info msg="Loading configuration file /etc/prometheus/config/prometheus.yaml" source="main.go:252" 
time="2017-10-05T23:02:58Z" level=info msg="Using pod service account via in-cluster config" source="kubernetes.go:104" 
time="2017-10-05T23:07:00Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:633" 
```

But on closer look at my Prometheus, it still only has the default configuration which I believe was put there by the ServiceMonitor: 
```
global:
      scrape_interval: 30s
      scrape_timeout: 10s
      evaluation_interval: 30s
    rule_files:
    - /etc/prometheus/rules/rules-0/*.rules
    scrape_configs:
        - job_name: default/prometheus-graphite/0
      scrape_interval: 30s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      kubernetes_sd_configs:
      - api_server: null
        role: endpoints
        namespaces:
          names:
          - default
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_service]
        separator: ;
        regex: prometheus-graphite
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        separator: ;
        regex: prometheus-graphite
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_namespace]
        separator: ;
        regex: (.*)
        target_label: namespace
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (.*)
        target_label: pod
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: service
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: job
        replacement: ${1}
        action: replace
      - source_labels: []
        separator: ;
        regex: (.*)
        target_label: endpoint
        replacement: prometheus-graphite
        action: replace
```
**What did you expect to see?**
I was expecting my own custom config to be tacked on at the bottom. My Prometheus Operators/ServiceMonitors are all based on the available getting started/documentation on Prometheus Operator with labels tweaked. This is the deployment if it helps: 
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    deployment: cassandra-prometheus-operator
  name: cassandra-prometheus-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cassandra-prometheus-operator
    spec:
      serviceAccountName: cassandra-prometheus
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.0.2
        image: quay.io/coreos/prometheus-operator:v0.12.0
        name: cassandra-prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
```
**What did you see instead? Under which circumstances?**
My Prometheus Operator doesn't have the updated configuration. I tried destroying and recreating the config map a couple of times and restarted the pod, it still behaved the same way. 

**Environment**

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3+coreos.0", GitCommit:"42de91f04e456f7625941a6c4aaedaa69708be1b", GitTreeState:"clean", BuildDate:"2017-08-07T19:44:31Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 
This was a tectonic cluster installed using the tectonic-installer. 
* Prometheus Operator Logs:

```
ts=2017-10-05T23:03:46Z caller=operator.go:641 component=prometheusoperator msg="sync prometheus" key=tectonic-system/k8s
ts=2017-10-05T23:03:46Z caller=operator.go:999 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-10-05T23:03:52Z caller=operator.go:641 component=prometheusoperator msg="sync prometheus" key=tectonic-system/k8s
ts=2017-10-05T23:03:52Z caller=operator.go:999 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-10-05T23:03:52Z caller=operator.go:309 component=prometheusoperator msg="Prometheus updated" key=tectonic-system/k8s
ts=2017-10-05T23:03:52Z caller=operator.go:309 component=prometheusoperator msg="Prometheus updated" key=default/cassandra-prometheus
```

I'm also just curious if anybody has had any success in getting Prometheus Operator to monitor instances not managed by Kubernetes/Tectonic, if you did, I'd love to hear how. At the moment I unable to get a custom configuration to be used by the Prometheus pod, and ServiceMonitor requires LabelSelector and Endpoints (I want to try to use Prometheus' ec2_sd_config in its scrape_config). I could load *.rules files (or, at least, it certainly tried because it complained: 
```
unexpected <op:-> in record statement, expected "="
```

Which I am attributing to me trying to put a scrape_config into a rules file. It would seem that without the ability to add a custom scrape_config it's not possible? 

If there's a better place to ask about this let me know. Thanks a lot!
