### ISSUE TITLE
Propagate service monitored label

### ISSUE THREAD

**Issue by sebglon** [coreos/prometheus-operator#695]
**What did you do?**
my service have labels pfid.
My servicemonitor use label pfid on selector
But those label is not propagate on prometheus metrics

**What did you expect to see?**
i want to have access on all or select of labels available on service to prometheus metrics

**Comment by brancz** [comment]
While this is generally possible, you can also join all labels of a service onto metrics using the metrics available in kube-state-metrics

https://github.com/kubernetes/kube-state-metrics/blob/master/Documentation/service-metrics.md#service-metrics

Does that work for you?

**Comment by sebglon** [comment]
Sorry.
when i am not clear.
I use mysql_exporter on a pod with label pfid
on my service monitor i have matchExpressions
```
spec:
  jobLabel: k8s-app
  selector:
    matchExpressions:
      - { key: pfid, operator: Exists}
```
But when metrics show metric `mysql_exporter_scrapes_total` on prometheus, fid` label used on selector is not available on metrics.
I have only basic label
`
mysql_exporter_scrapes_total{endpoint="mysqld-exporter",instance="10.0.2.12:9104",job="mysqld-exporter",namespace="srnt-sgl1",pod="mysql-2760336166-hg3rf",service="mysqld-exporter"}
`

My genrated config: 
```
- job_name: monitoring/mysqld-exporter/0
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - api_server: null
    role: endpoints
    namespaces:
      names: []
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_label_pfid]
    separator: ;
    regex: .+
    replacement: $1
    action: keep
```

**Comment by brancz** [comment]
Yes, the excerpt of the Prometheus config only says that a target with that meta label will be kept, not that it will have that target after relabeling. Relabeling is exactly the kind of black magic we want to keep out of the Prometheus Operator in terms of configurability.

What you are seeing is the mix of Prometheus labels and Kubernetes labels. While they can be used in a compatible manner, they are not the same.

**Comment by sebglon** [comment]
Yes i'm right with you. but how can i make to configure or request with Kubernetes labels? i have not found information or example.

**Comment by brancz** [comment]
If you have kube-state-metrics running and are scraping its metrics, then you can join the `kube_service_labels` metric onto the `mysql_exporter_scrapes_total` metric.

```
mysql_exporter_scrapes_total * on(service) group_right() kube_service_labels
```

**Comment by wleese** [comment]
I have the same issue.

We have labels we want to propagate from kubernetes into prometheus. The above solution on a random metric resulted in:

{code}
Error executing query: many-to-many matching not allowed: matching labels must be unique on one side
{code}

But whatever the case, we don't want to always have to write a query that's 3 times longer than it should be, just because we're running prometheus operator.
Any other suggestions?

**Comment by brancz** [comment]
We're aiming to make the majority of common cases very easy with great experience, there will always be a case that's not very well supported, at that point we want to make sure you can achieve what you want, but can't always make it easy. If you disagree with how the Prometheus Operator generates a configuration off of `ServiceMontior` objects, then you can still opt for a [custom configuration](https://github.com/coreos/prometheus-operator/blob/master/Documentation/custom-configuration.md), and handle everything down to relabeling rules yourself :slightly_smiling_face:.

**Comment by wleese** [comment]
I respect your desire to limit the scope of your application.
Of course, I disagree with:

> We're aiming to make the majority of common cases
..which implies that my and @sebglon 's case is not common ;) 
All I need is an on/off switch for kubernetes label propagation for servicemonitors. Going the custom config route is not an option for me (very self service orientated org).

**Comment by yskopets** [comment]
@brancz If we implement such a feature on our own, will you consider accepting a pull request?

**Comment by brancz** [comment]
Considering there seems to be a lot of interest in this, I would like to discuss the design for this to ensure that we're happy with the result. Options that we could do:

* Relabel all labels of a service onto targets
  * With an additional prefix for these labels would mean potential usability concerns, omitting a prefix would allow for possible collisions. We could formally describe the order of how labels are relabeled to targets and document the expected behavior to avoid confusion, but Prometheus reserved labels are still possible to be overridden (again we can document if we forbid to do this, but it's possibly a usability concern).
  * The other option would be to whitelist labels per `ServiceMonitor` to be relabeled onto targets.

Let me know your thoughts.

**Comment by wleese** [comment]
Of the two, whitelisting labels would empower the user the most. Any concerns about keeping your whitelist of labels in sync with changes to the service labels, would be a concern of the deployment tooling.

Personally, I'd like to be able to add custom relabeling configuration to a job. This way you'd gain more flexibility (I'd like to rename labels for example).

**Comment by jonaz** [comment]
Here is an example joining the team label:

```
100*(count by (job) ((up == 0) * on(pod) group_left(label_team) kube_pod_labels))/(count by (job) (up * on(pod) group_left(label_team) kube_pod_labels))
```

Original query looks like this:
```
100 * (count(up == 0) BY (job) / count(up) BY (job)) > 10
```

The original query takes 1500ms to run on on 1h data
The joining takes more than double that time to run. 

So it might be a performance enhancement to allow putting labels on the jobs

I would ideally have a whitelisting on the ServiceMonitor object. Both for pod and service.

**Comment by brancz** [comment]
The performance of a query is something that can easily be fixed with recording rules, but I think it's still fair to relabel white-listed labels onto targets. The next question would be, how do we want this to look like usability wise. I would propose a list of label-names as a field of the `ServiceMonitor` object.

For example:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myteam
  labels:
    team: myteam
spec:
  selector:
    matchLabels:
      team: my-team
  targetLabels:
  - team
  endpoints:
  - port: web
```

This part would be the new part: 

```
  targetLabels:
  - team
```

This would cause the "team" label of services (and pods?) to be relabeled onto the targets discovered through this `ServiceMonitor`. I would still propose the `label_` prefix, just for joins to be easy with metrics from [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/Documentation/service-metrics.md#service-metrics).

How does that sound?

**Comment by jonaz** [comment]
That would be a perfect solution from my perspective. 

I dont know if anyone needs pods and service labels separated. If so there might be a need for two lists, perhaps targetPodLabels and targetServiceLabels. I would prefer just taking service and pods labels, with pods having priority. 

I agree with keeping the ```label_``` prefix consistent with kube-state-metrics

**Comment by yskopets** [comment]
@brancz As a user, I’d like to:
- be able to propagate labels from both `service` and `pod` (on my choice)
- be able to select labels for propagation using regular expressions, e.g. `org_.*` or `example\.org/.*`
- be able to rename labels during propagation, e.g. `example.org/feature: true` => `org_feature: true`
- be able to override default prefix (`label_`), if any
- not to worry about accidentally overriding internal labels, such as `namespace`, `service`, `pod`, `job`

E.g.,
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myteam
  labels:
    team: myteam
spec:
  selector:
    matchLabels:
      team: my-team
  endpoints:
  - port: web
  propagateLabels:
  - source: # optional, both `pod` and `service` by default; the order could be taken into account in corner cases 
    - pod
    - service
    match: "example\.org/(.*)" # optional, match any by default
    rename: "org_$1"           # optional, original value by default
  - match: "org_.*"            # more typical case
```

**Comment by wleese** [comment]
Any progress on this? :)

**Comment by brancz** [comment]
We added relabeling support for the remote read/write and metric relabeling, so I'd suggest that we add full relabeling capabilities to the ServiceMonitor/Endpoints object as well.

**Comment by olvesh** [comment]
@brancz that is really good news. If there exists any WIP I would love testing this feature. 

To add some context on the importance of this feature, consider that a lot of community supported Grafana dashboards are using the labels that will be added from e.g. (swap `pod` with either `service` or `node` ++ for other usecases): 
```yaml
    - separator: ;
      regex: __meta_kubernetes_pod_label_(.+)
      replacement: $1
      action: labelmap
```

After migrating to prometheus-operator I found I had to edit many our community supported dashboards, effectively having to maintain those ourself. The same goes for a good set of alerts I have gathered around. Luckily most of them come from the well curated set of alerts from CoreOS.

Metric relabeling only takes me a step of the way as it won't consider the meta info available when scraping.  Not sure how the `WriteRelabelConfigs` works though. Would that perhaps solve my usecase?
