### ISSUE TITLE
Prometheus instance has no targets (syncing nodes into Endpoints object failed)

### ISSUE THREAD

**Issue by irishandyb** [coreos/prometheus-operator#701]
**What did you do?**

I have deployed Prometheus operator to monitor my application, however the Prometheus instance is showing no targets listed.

Note that before deploying a Prometheus instance and Service Monitor for my app, I deployed kube prometheus by following the [KOPSonAWS docs](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/KOPSonAWS.md).
With this, the prometheus-k8s instance in the monitoring namespace is working as expected and lists all cluster related targets. So, user error is highly likely here.

**What did you expect to see?**

I expected to see my app listed as a target in Prometheus.

**What did you see instead? Under which circumstances?**

A blank page listing no targets.

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:16:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

	KOPS on AWS

* Manifests:

My apps manifest:
```
apiVersion: apps/v1beta2 # for versions before 1.7.0 use apps/v1beta1
kind: Deployment
metadata:
  name: sampleapp
  namespace: sampleapp
  labels:
    app: sampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: mysampleapp:latest
        ports:
        - name: web
          containerPort: 8081
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: sampleapp
  namespace: sampleapp
spec:
  selector:
    app: sampleapp
  ports:
  - name: web
    protocol: TCP
    port: 8081
    targetPort: web
```

The prometheus instance manifest:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: sampleapp
  labels:
    app: prometheus
spec:
  version: v1.7.1
  serviceMonitorSelector:
    matchLabels:
      app: sampleapp
  resources:
    requests:
      # 2Gi is default, but won't schedule if you don't have a node with >2Gi
      # memory. Modify based on your target and time-series count for
      # production use. This value is mainly meant for demonstration/testing
      # purposes.
      memory: 400Mi
---
kind: Service
apiVersion: v1
metadata:
  name: prometheus
  namespace: sampleapp
spec:
  selector:
    app: prometheus
  ports:
  - name: web
    protocol: TCP
    port: 30904
    targetPort: 9090
```

and lastly, the service monitor:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sampleapp
  namespace: sampleapp
  labels:
    app: sampleapp
spec:
  selector:
    matchLabels:
      app: sampleapp
  endpoints:
  - port: web
    interval: 10s
```

* Prometheus Operator Logs:

```
ts=2017-10-19T10:01:17Z caller=operator.go:293 component=prometheusoperator msg="Prometheus updated" key=monitoring/k8s
ts=2017-10-19T10:01:17Z caller=operator.go:640 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2017-10-19T10:01:17Z caller=operator.go:998 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-10-19T10:01:24Z caller=operator.go:273 component=prometheusoperator msg="Prometheus added" key=sampleapp/prometheus
ts=2017-10-19T10:01:24Z caller=operator.go:640 component=prometheusoperator msg="sync prometheus" key=sampleapp/prometheus
ts=2017-10-19T10:01:24Z caller=operator.go:987 component=prometheusoperator msg="creating configuration"
ts=2017-10-19T10:01:24Z caller=operator.go:640 component=prometheusoperator msg="sync prometheus" key=sampleapp/prometheus
ts=2017-10-19T10:01:24Z caller=operator.go:998 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-10-19T10:01:24Z caller=operator.go:640 component=prometheusoperator msg="sync prometheus" key=sampleapp/prometheus
ts=2017-10-19T10:01:24Z caller=operator.go:347 component=alertmanageroperator msg="update handler" old=4300 cur=4304
ts=2017-10-19T10:01:24Z caller=operator.go:998 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-10-19T10:01:24Z caller=operator.go:605 component=prometheusoperator msg="update handler" old=4300 cur=4304
ts=2017-10-19T10:01:24Z caller=operator.go:640 component=prometheusoperator msg="sync prometheus" key=sampleapp/prometheus
ts=2017-10-19T10:01:24Z caller=operator.go:998 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-10-19T10:02:08Z caller=operator.go:327 component=alertmanageroperator msg="Alertmanager updated" key=monitoring/main
ts=2017-10-19T10:02:08Z caller=operator.go:383 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
ts=2017-10-19T10:02:23Z caller=operator.go:293 component=prometheusoperator msg="Prometheus updated" key=monitoring/k8s
ts=2017-10-19T10:02:23Z caller=operator.go:293 component=prometheusoperator msg="Prometheus updated" key=sampleapp/prometheus
ts=2017-10-19T10:02:23Z caller=operator.go:640 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2017-10-19T10:02:23Z caller=operator.go:998 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-10-19T10:02:23Z caller=operator.go:640 component=prometheusoperator msg="sync prometheus" key=sampleapp/prometheus
ts=2017-10-19T10:02:23Z caller=operator.go:998 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-10-19T10:02:29Z caller=operator.go:640 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2017-10-19T10:02:29Z caller=operator.go:998 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-10-19T10:02:29Z caller=operator.go:640 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2017-10-19T10:02:29Z caller=operator.go:998 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-10-19T10:02:40Z caller=operator.go:605 component=prometheusoperator msg="update handler" old=4304 cur=4445
ts=2017-10-19T10:02:40Z caller=operator.go:640 component=prometheusoperator msg="sync prometheus" key=sampleapp/prometheus
ts=2017-10-19T10:02:40Z caller=operator.go:347 component=alertmanageroperator msg="update handler" old=4304 cur=4445
ts=2017-10-19T10:02:40Z caller=operator.go:998 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-10-19T10:03:08Z caller=operator.go:327 component=alertmanageroperator msg="Alertmanager updated" key=monitoring/main
ts=2017-10-19T10:03:08Z caller=operator.go:383 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
ts=2017-10-19T10:03:20Z caller=operator.go:640 component=prometheusoperator msg="sync prometheus" key=sampleapp/prometheus
ts=2017-10-19T10:03:20Z caller=operator.go:1001 component=prometheusoperator msg="current config or current configmaps has changed"
ts=2017-10-19T10:03:20Z caller=operator.go:1007 component=prometheusoperator msg="updating configuration"
ts=2017-10-19T10:03:20Z caller=operator.go:640 component=prometheusoperator msg="sync prometheus" key=sampleapp/prometheus
ts=2017-10-19T10:03:20Z caller=operator.go:998 component=prometheusoperator msg="updating config skipped, no configuration change"
ts=2017-10-19T10:03:33Z caller=operator.go:306 component=prometheusoperator msg="syncing nodes into Endpoints object failed" err=null
```

I thought that this may be a namespacing issue, so I tried deploying everything to default but the results were the same.

Does anyone see what I may be doing wrong? or how I can get further more detailed debug logs from prom-operator? Currently it just has the last line on syncing nodes to EPs failing.

Many thanks,
Andy

**Comment by brancz** [comment]
Can you share the configuration that your Prometheus instance has loaded (you can find it in the Prometheus web UI)? Also the `Deployment` used to deploy the Prometheus Operator would be helpful as well.

**Comment by irishandyb** [comment]
Hi @brancz 

The Prometheus instance configuration is:

```
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
```

It seems quite empty, I am guessing it is a default.

The `Deployment` for the Prometheus Operator is the one from `kube-prometheus`. [Linked here](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/prometheus-operator/prometheus-operator.yaml)

Although, I note that you have recently updated the image tag version to `v0.14.0` - I do not see a v14 on Quay so I have reverted back to the `v0.13.0` tag.

Additionally, As I had torn down the kops cluster, I had to redeploy the cluster to capture the above Prom config. This time around I noticed the `syncing nodes into Endpoints object failed` message after the initial prometheus-operator deployment but before the prometheus instance or servicemonitor were created.

Lastly, I note that kube-prom was recently updated to use Prometheus tag `v2.0.0-rc.1`. In the Deployment I posted initially I used `v1.7.1`. I have tried updating to the 2.x tag with no change in result.

Kind Regards,
Andy

**Comment by brancz** [comment]
The fact that your configuration is nothing but the default, this means the `ServiceMonitor` was either not correctly selected or is malformed. Can you double check that your `ServiceMonitor` is correctly indented (also no tabs instead of spaces etc.)?

**Comment by irishandyb** [comment]
This is the service monitor definition that I am using:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sampleapp
  namespace: sampleapp
  labels:
    app: sampleapp
spec:
  selector:
    matchLabels:
      app: sampleapp
  endpoints:
  - port: web
    interval: 10s
```

I based it on (or copied it from) the [example definitions for kube-prom](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/examples/example-app/servicemonitor-frontend.yaml). Also comparing it to the `prometheus-k8s` definitions for kube-prob ([here](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-service-monitor-alertmanager.yaml)), I notice that these definitions have a `namespaceSelector`.

```
  namespaceSelector:
    matchNames:
    - monitoring
```

Perhaps this is something I need to add, as I am running my service in the `sampleapp` NS. Although I did try deploy everything to default and that didn't work either. I will give the `namespaceSelector` a try over the weekend.

Also, does it matter what NS that the `ServiceMonitor` is deployed to? I deploy my `ServiceMonitor` to the `sampleapp` NS, but perhaps it needs to run in the `monitoring` NS alongside the operator?

**Comment by brancz** [comment]
The kube-prometheus Prometheus instance is highly adapted to _only_ monitor cluster components. It only has RBAC access to the namespaces it needs to: default, monitoring, and kube-system. If you look at your Prometheus logs, this will probably tell you that you don't have access to request something from the apiserver.

**Comment by irishandyb** [comment]
I am deploying a separate Prometheus instance to monitor my sampleapp.

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: sampleapp
  labels:
    app: prometheus
spec:
  version: v1.7.1
  serviceMonitorSelector:
    matchLabels:
      app: sampleapp
  resources:
    requests:
      # 2Gi is default, but won't schedule if you don't have a node with >2Gi
      # memory. Modify based on your target and time-series count for
      # production use. This value is mainly meant for demonstration/testing
      # purposes.
      memory: 400Mi
---
kind: Service
apiVersion: v1
metadata:
  name: prometheus
  namespace: sampleapp
spec:
  selector:
    app: prometheus
  ports:
  - name: web
    protocol: TCP
    port: 30904
    targetPort: 9090
```
and then a ServiceMonitor to tie my app to this Prometheus instance:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sampleapp
  namespace: sampleapp
  labels:
    app: sampleapp
spec:
  selector:
    matchLabels:
      app: sampleapp
  endpoints:
  - port: web
    interval: 10s
```

Do you see any reason why this would not work? There must be something wrong with these manifests because the prometheus instance in the sampleapp namespace does not get configured with the service monitor.

**Comment by brancz** [comment]
> There must be something wrong with these manifests because the prometheus instance in the sampleapp namespace does not get configured with the service monitor.

Yes I agree. Can you check the logs of the Prometheus server? It might show if there are permission problems or malformed configuration or something like that.

**Comment by irishandyb** [comment]
I just got around to testing again today. Looks like I made a mistake on the above regarding the Prometheus configuration. It takes some time for the prometheus-config-reloader to push the config after the service monitor is created. Previously I had checked right away and not waited. Today, I see the following under the Prometheus configuration tab:

```
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
scrape_configs:
- job_name: sampleapp/sampleapp/0
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - api_server: null
    role: endpoints
    namespaces:
      names:
      - sampleapp
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_label_app]
    separator: ;
    regex: sampleapp
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: web
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: ${1}
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: web
    action: replace
```

There are no errors in the prometheus logs:
```
level=info ts=2017-10-22T08:58:48.892015977Z caller=main.go:216 msg="Starting prometheus" version="(version=2.0.0-rc.1, branch=HEAD, revision=5ab8834befbd92241a88976c790ace7543edcd59)"
level=info ts=2017-10-22T08:58:48.892115056Z caller=main.go:217 build_context="(go=go1.9.1, user=root@1f56dd8b6f7b, date=20171017-12:34:15)"
level=info ts=2017-10-22T08:58:48.892163723Z caller=main.go:218 host_details="(Linux 4.4.78-k8s #1 SMP Fri Jul 28 01:28:39 UTC 2017 x86_64 prometheus-prometheus-0 (none))"
level=info ts=2017-10-22T08:58:48.895060701Z caller=web.go:380 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2017-10-22T08:58:48.895787189Z caller=main.go:315 msg="Starting TSDB"
level=info ts=2017-10-22T08:58:48.915806574Z caller=targetmanager.go:68 component="target manager" msg="Starting target manager..."
level=info ts=2017-10-22T08:58:48.92163596Z caller=main.go:327 msg="TSDB started"
level=info ts=2017-10-22T08:58:48.92170002Z caller=main.go:394 msg="Loading configuration file" filename=/etc/prometheus/config/prometheus.yaml
level=info ts=2017-10-22T08:58:48.921937642Z caller=main.go:371 msg="Server is ready to receive requests."
level=info ts=2017-10-22T08:58:49.27556235Z caller=main.go:394 msg="Loading configuration file" filename=/etc/prometheus/config/prometheus.yaml
level=info ts=2017-10-22T09:00:17.457440378Z caller=main.go:394 msg="Loading configuration file" filename=/etc/prometheus/config/prometheus.yaml
level=info ts=2017-10-22T09:00:17.458215127Z caller=kubernetes.go:100 component="target manager" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2017-10-22T09:44:48.487319538Z caller=main.go:394 msg="Loading configuration file" filename=/etc/prometheus/config/prometheus.yaml
level=info ts=2017-10-22T09:45:54.456308687Z caller=main.go:394 msg="Loading configuration file" filename=/etc/prometheus/config/prometheus.yaml
level=info ts=2017-10-22T09:45:54.456875018Z caller=kubernetes.go:100 component="target manager" discovery=k8s msg="Using pod service account via in-cluster config"
```

I have also tried a few different changes today. As mentioned in a previous comment, I have added the `namespaceSelector` to the service monitor.
Lastly, I thought that it may be a permissions issue, so I have updated my Prometheus manifest to include a service account and role definitions (that I have blatantly copied from kube-prom with changed names and namespaces):

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sampleapp
  namespace: sampleapp
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: prometheus-sampleapp
  namespace: sampleapp
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus-k8s
rules:
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prometheus-sampleapp
  namespace: sampleapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-sampleapp
subjects:
- kind: ServiceAccount
  name: prometheus-sampleapp
  namespace: sampleapp
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus-sampleapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-sampleapp
subjects:
- kind: ServiceAccount
  name: prometheus-sampleapp
  namespace: sampleapp
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: sampleapp
  labels:
    app: prometheus
spec:
  version: v2.0.0-rc.1
  serviceAccountName: prometheus-sampleapp
  serviceMonitorSelector:
    matchLabels:
      app: sampleapp
  resources:
    requests:
      # 2Gi is default, but won't schedule if you don't have a node with >2Gi
      # memory. Modify based on your target and time-series count for
      # production use. This value is mainly meant for demonstration/testing
      # purposes.
      memory: 400Mi
---
kind: Service
apiVersion: v1
metadata:
  name: prometheus
  namespace: sampleapp
spec:
  selector:
    app: prometheus
  ports:
  - name: web
    protocol: TCP
    port: 30904
    targetPort: 9090
``` 

However, unfortunately while the service monitor configuration is being pushed to prom, the targets are not being detected and no errors are being logged.

**Comment by irishandyb** [comment]
Got some more time today to play around with this. Solved the problem, my Service was missing the label that the Service Monitor was tied to.
```
kind: Service
apiVersion: v1
metadata:
  name: prometheus
  namespace: sampleapp
spec:
  selector:
    app: prometheus
  ports:
  - name: web
    protocol: TCP
    port: 30904
    targetPort: 9090
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sampleapp
  namespace: sampleapp
  labels:
    app: sampleapp
spec:
  selector:
    matchLabels:
      app: sampleapp
  endpoints:
  - port: web
    interval: 10s
```

I just had to update the service to include the label:

```
metadata:
  name: prometheus
  namespace: sampleapp
  labels:
    app: sampleapp
```

As hinted in my original post, I always suspected user error was the cause - however, I am embarrassed that it took me that long to notice the missing label. 

Either way, all happy now, closing. :)
