### ISSUE TITLE
Permission denied when using prometheus-operator on minikube

### ISSUE THREAD

**Issue by yamihalovna** [coreos/prometheus-operator#708]
**What did you do?**
I ran the latest version of prometheus-operator in minikube.
**What did you expect to see?**
Prometheus working

**What did you see instead? Under which circumstances?**
 Prometheus pod fails with 
```level=info ts=2017-10-25T13:58:34.846730617Z caller=web.go:380 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2017-10-25T13:58:34.846787804Z caller=main.go:315 msg="Starting TSDB"
level=error ts=2017-10-25T13:58:34.848202305Z caller=main.go:324 msg="Opening storage failed" err="open DB in /var/prometheus/data: open /var/prometheus/data/714202058: permission denied"
```
**Environment**
minikube installed on MacOS

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T05:22:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-09-11T21:52:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	minikube

* Manifests:

```
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: app
  namespace: jetbrainslicense
spec:
  externalUrl: http://prometheus.jetbrainslicense.minikube.test
  replicas: 2
  retention: 168h
  serviceMonitorSelector:
    matchLabels:
      app: jetbrainslicense
  resources:
    requests:
      memory: 2Gi
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 50Gi
  alerting:
    alertmanagers:
    - namespace: jetbrainslicense
      name: alertmanager
      port: http-metrics
  serviceAccountName: prometheus
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```
