### ISSUE TITLE
Question about target discovery

### ISSUE THREAD

**Issue by ejwood79** [coreos/prometheus-operator#726]
['logs-from-prometheus-in-prometheus-prometheus-0.txt'](https://github.com/coreos/prometheus-operator/files/1443672/logs-from-prometheus-in-prometheus-prometheus-0.txt)
['logs-from-prometheus-operator-in-prometheus-operator-77859cfbf8-jmxgx.txt'](https://github.com/coreos/prometheus-operator/files/1443673/logs-from-prometheus-operator-in-prometheus-operator-77859cfbf8-jmxgx.txt)

**What did you do?**
Following the getting started guide, I set up a service, serviceMonitor, and serviceMonitorSelector. The prometheus running in that namespace is scraping my service.

**What did you expect to see?**
In the prometheus UI, I expected to see a target representing that service, and the ability to query and graph.

**What did you see instead? Under which circumstances?**
Nothing is showing up in the prometheus UI.

**Environment**

* Kubernetes version information:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-12T00:44:37Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"dirty", BuildDate:"2017-10-17T15:09:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: minikube

* Manifests:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpdrone
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: httpdrone
        version: v1
    spec:
      containers:
      - name: httpdrone
        image: *redacted*
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: httpdrone
  labels:
    app: httpdrone
spec:
  ports:
  - name: web
    port: 8080
  selector:
    app: httpdrone
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: httpdrone
  labels:
    team: platform
spec:
  selector:
    matchLabels:
      app: httpdrone
  endpoints:
    - port: web 
      path: /application/prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      team: platform
  resources:
    requests:
      memory: 400Mi
```

* Prometheus Operator Logs: attached.
