### ISSUE TITLE
Allow jobconfig to be dynamically configured by Service labels

### ISSUE THREAD

**Issue by wleese** [coreos/prometheus-operator#729]
While the concept that everyone creates ServiceMonitors to get their endpoints scraped is great, it would also be nice to have a small amount of ServiceMonitors, with more flexibility.

We'd like to have labels on the k8s Service actually be used to determine the metrics_path and port(name). This would allow a minimal of ServiceMonitors with only a small amount of configuration being static.

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: generic-servicemonitor
  labels:
    prometheus: k8s
    k8s-app: bolcom-app
spec:
  endpoints:
  - interval: 30s
    pathFromLabel: metrics-path
    targetPortFromLabel: metrics-port
  namespaceSelector:
    any: true
```

Where a service would provide metrics-path and metrics-port labels

```
apiVersion: v1
kind: Service
metadata:
  labels:
    metrics-path: /metrics
    metrics-port: 8080
  name: myapp
spec:
  ports:
  - name: http
    port: 8080
  selector:
    application: myapp
```
