### ISSUE TITLE
How to make -storage.local.retention=24h longer

### ISSUE THREAD

**Issue by kubebc** [coreos/prometheus-operator#732]
Hi, Team,

1.  I've tried to update "retention" from 24h to 8760h below, but both failed. Any tips? Thanks!

$ kubectl edit statefulsets -n tectonic-system prometheus-k8s
```
apiVersion: apps/v1beta1
kind: StatefulSet
..
    spec:
      containers:
      - args:
        - -storage.local.retention=24h
```

Edited this file from console. 
```
kind: Prometheus
  name: k8s
  replicas: 1
  retention: 8760h
  ruleSelector:
```

2.  Are my storage config right?
```
  retention: 8760h
  storage:
    volumeClaimTemplate
      - metadata:
        name: prometheus-k8s-db
        annotations:
         volume.beta.kubernetes.io/storage-class: gold
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        selector:
          matchLabels:
            app: prometheus-k8s
```

**Comment by brancz** [comment]
The Tectonic Prometheus instance intentionally does not offer persistent storage today, as we're about to migrate it to Prometheus 2.0. Regarding the retention, there is a `ConfigMap` called `tectonic-monitoring` in the `tectonic-system` namespace, within it you can configure selected things for the Tectonic Monitoring stack. We need this in order to be able to control the customization so we can provide any guarantee for automated upgrades to work. 

See the documentation for what is explicitly configurable [here](https://coreos.com/tectonic/docs/latest/tectonic-prometheus-operator/user-guides/configuring-tectonic-monitoring.html).

**Comment by kubebc** [comment]
Amazing! 
1. I've set "retention: 8760h" following your guide.
```
$ kubectl edit cm -n tectonic-system tectonic-monitoring
configmap "tectonic-monitoring" edited
$ kubectl edit statefulset -n tectonic-system prometheus-k8s
Edit cancelled, no changes made.
spec:
      containers:
      - args:
        - -storage.local.retention=8760h
```
2. prometheus-k8s-db cannot survive after pod restating, what's your recommendation to backup and recover prometheus-k8s-db? Thanks! 
```
      volumes:
      - emptyDir: {}
        name: prometheus-k8s-db

        volumeMounts:
        - mountPath: /var/prometheus/data
          name: prometheus-k8s-db
```
Fyi, I used to copy data files out from prometheus container as a backup, and then copy back in as recovery. But those data are unrecognizable at last.
```
$ kubectl exec -it prometheus-3067433533-4rz0q -- sh
/prometheus # tar zcvf data.tgz data
$ kubectl exec -it prometheus-3067433533-4rz0q -- sh
/prometheus # ls
data      data.tgz
/prometheus # du -sh data.tgz
43.7M    data.tgz
$ kubectl cp default/prometheus-3067433533-4rz0q:/prometheus/data.tgz data.tgz
tar: removing leading '/' from member names
$ ls
data.tgz
$ du -sh data.tgz
44M    data.tgz
```
