### ISSUE TITLE
kube-prometheus: TargetDown alert is not working

### ISSUE THREAD

**Issue by r0bj** [coreos/prometheus-operator#749]
Alert definition from `kube-prometheus`:
```
alert: TargetDown
expr: 100
  * (count(up == 0) BY (job) / count(up) BY (job)) > 10
for: 10m
labels:
  severity: warning
annotations:
  description: '{{ $value | printf "%.2f" }}% or more of {{ $labels.job }}
    targets are down.'
  summary: Targets are down
```

It won't work as expected:
1. for the first 5 minutes alert is in PENDING state (waiting 10 minutes)
2. after 5 minutes there are no results of `count(up == 0)`, failing job is just not present at all
3. alert is resolved despite failing job

I think it affects all alerts based on `up` metric.
Is there a better way of doing such alert?
