### ISSUE TITLE
Seeing data:null though /metrics endpoint does have data

### ISSUE THREAD

**Issue by nuala33** [coreos/prometheus-operator#758]
**What did you do?**
We are spinning up a new prometheus instance in a new k8s 1.7 cluster. Although we are able to see a number of metrics in the browser via the prometheusserver:9090/metrics endpoint, prometheusserver:9090/api/v1/label/\__name\__/values returns the following:
{
status: "success",
data: null
}

Additionally, when we load the UI we are seeing no dropdown options where it says "- insert metrics at cursor -". Is it possible we missed a step when setting up this cluster?

**What did you expect to see?**

We expected to be able to choose metrics from the dropdown menu that says "- insert metrics at cursor -". We are able to do this with our other Prometheus cluster that has been running for a while.

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.8", GitCommit:"bc6162cc70b4a39a7f39391564e0dd0be60b39e9", GitTreeState:"clean", BuildDate:"2017-10-05T06:35:40Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 

Custom chef deploy on bare metal CentOS 7.

We are running v1.7.0 of Prometheus with prometheus-operator v0.11.0.

* Manifests:

```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: ny5
  namespace: observability
  labels:
    prometheus: ny5
spec:
  replicas: 2
  version: v1.7.0
  externalUrl: "http://prometheusserver:9090/" 
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchExpressions:
    - {key: k8s-app, operator: Exists}
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: ny5
  resources:
    limits:
      cpu: 8000m
      memory: 20Gi
    requests:
      cpu: 4000m
      memory: 10Gi
  retention: 720h0m0s
  alerting:
    alertmanagers:
    - namespace: observability
      name: alertmanager-main
      port: web
```

* Prometheus Operator Logs:
Nothing relevant as far as I can tell.

**Comment by brancz** [comment]
Do you have Prometheus configured to scrape itself? Otherwise Prometheus won't ingest this data.

**Comment by nuala33** [comment]
Thanks as always, @brancz! Adding a ServiceMonitor for Prometheus did the trick :)

**Comment by nuala33** [comment]
Hey one last thing. Is this documentation up to date? https://github.etsycorp.com/Engineering/prometheus-operator/blob/master/helm/alertmanager/values.yaml

I would have thought that Alertmanager uses the volumeClaimTemplate pattern now, similar to how you'd set up persistent storage in Prometheus. Is that correct?

**Comment by brancz** [comment]
@nuala33 you're absolutely right, the documentation is outdated, the Alertmanager object did adopt the same `StorageSpec` as the Prometheus object. Could you create a PR to fix that? :slightly_smiling_face:

**Comment by nuala33** [comment]
I'd be glad to contribute. The only concern I have is that my Alertmanager StorageSpec does look identical to what I have set up for Prometheus, yet I see data being written to my Prometheus nfs mount and not to the Alertmanager mount.

Output of `mount` on one of my alertmanager pods:
```
promstore.dc.domain.com:/var/lib/alertmanager/0/alertmanager-db on /var/alertmanager/data type nfs4 (rw,sync,noatime,vers=4.0,rsize=32768,wsize=32768,namlen=255,soft,proto=tcp,port=0,timeo=25,retrans=2,sec=sys,clientaddr=10.36.0.17,local_lock=none,addr=10.96.100.13)
```

Yet /var/alertmanager/data is an empty directory on all 3 pods. The only place I can see anything that looks like alertmanager data is in /etc/alertmanager/data. When I cat this file, it has strange characters:
```
�
�
observabilityjobkube-state-metricinstance10.36.35.160:808endpointate-metricspodprometheus-shared-1	namespace
                                                                 http-metrics'	containerprometheus-config-reloader&	alertnamePrometheusTooManyRestarts
                     �ø����%"
                            �ȸ��ݞ�*
                                  �ȸ�����BNualaJTesting alertmanager metrics
                                                                           �����ݞ�/
```

Here are the configs (if correct after all, I will create a PR to add the StorageSpec the docs):

```
apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "Alertmanager"
metadata:
  name: "main"
  labels:
    alertmanager: "main"
spec:
  replicas: 3
  version: v0.7.1
  externalUrl: "http://alertmanager:9093/" 
  alertmanager:
    persistentVolume: enabled
  resources:
    limits:
      cpu: 1000m
      memory: 10Gi
    requests:
      cpu: 1000m
      memory: 10Gi
  retention: 720h0m0s
  storage:
    volumeClaimTemplate:
      spec:
        selector:
          matchLabels:
            app: "alertmanager-persistent-volume"
        resources:
          requests:
            storage: 50Gi
```
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alert-manager-storage-0
  annotations:
    volume.beta.kubernetes.io/mount-options: "rw,noatime,sync,vers=4.0,rsize=32768,wsize=32768,namlen=255,soft,proto=tcp,port=0,timeo=25,retrans=2"
  namespace: observability
  labels:
    app: "alertmanager-persistent-volume"
spec:
  capacity:
    storage: 60Gi
  accessModes:
  - ReadWriteOnce # required
  nfs:
    server: promstore.dc.domain.com
    path: "/var/lib/alertmanager/0"
```

**Comment by brancz** [comment]
Alertmanager flushes its state only every 10minutes or so to disk. Is this still the case now? Could you have a look at the Alertmanager logs?

**Comment by nuala33** [comment]
Hmm, I did silence one alert to trigger an event but all I see in the logs since are:

```
time="2017-11-17T18:34:31Z" level=info msg="running maintenance" component=nflog source="nflog.go:286"
time="2017-11-17T18:34:31Z" level=info msg="running maintenance" component=silences source="silence.go:232"
time="2017-11-17T18:34:31Z" level=info msg="maintenance done" component=nflog duration=61.194µs source="nflog.go:303"
time="2017-11-17T18:34:31Z" level=info msg="maintenance done" component=silences duration=45.578µs source="silence.go:249"
time="2017-11-17T18:49:31Z" level=info msg="running maintenance" component=nflog source="nflog.go:286"
time="2017-11-17T18:49:31Z" level=info msg="running maintenance" component=silences source="silence.go:232"
time="2017-11-17T18:49:31Z" level=info msg="maintenance done" component=nflog duration=58.574µs source="nflog.go:303"
time="2017-11-17T18:49:31Z" level=info msg="maintenance done" component=silences duration=78.343µs source="silence.go:249"
```

And the /var/alertmanager/data directory remains empty. 🤷‍♀️

**Comment by nuala33** [comment]
Ah, maybe these logs from the Prometheus operator are telling. If my alertmanager instances aren't in sync, could this be the cause of the problem?

```ts=2017-11-17T18:48:13Z caller=operator.go:363 component=alertmanageroperator msg="sync alertmanager" key=observability/main
E1117 18:48:13.637502       1 operator.go:237] Sync "observability/main" failed: updating statefulset failed: StatefulSet.apps "alertmanager-main" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas' and 'containers' are forbidden.
ts=2017-11-17T18:51:47Z caller=operator.go:307 component=alertmanageroperator msg="Alertmanager updated" key=observability/main
```

**Comment by brancz** [comment]
Yes this is a limitation of Kubernetes, that is no longer present in newer versions. The solution here is to entirely remove the Alertmanager object and create it from scratch (and make sure the statefulset that belonged to the old Alertmanager object was also deleted).

**Comment by nuala33** [comment]
Hmm, any ideas why I might be seeing this upon deleting my statefulset? I know its familiar but I can't remember the solution here. See config above. Version of the Operator is 0.11.0

  17s		11s		16	statefulset			Warning		FailedCreate		create Pod alertmanager-main-1 in StatefulSet alertmanager-main failed error: Failed to create PVC alertmanager-main-db-alertmanager-main-1: PersistentVolumeClaim "alertmanager-main-db-alertmanager-main-1" is invalid: spec.resources[storage]: Required value

**Comment by nuala33** [comment]
Ah, never mind. I figured out the last bit. The syntax isn't the same as I thought between Alertmanager and Prometheus for persistent storage. Changing the config to this fixed the issue of pods not creating:
```
  storage:
    selector:
      matchLabels:
        app: "alertmanager-persistent-volume"
    resources:
      requests:
        storage: 50Gi
```
Now just waiting to see if we can get some data being written to disk.
