### ISSUE TITLE
deployment breaks in namespaces other than `monitoring`

### ISSUE THREAD

**Issue by hawksight** [coreos/prometheus-operator#765]
* What I was doing:
I was attempting to deploy using the kube-prometheus script method to the `default` namespace

* What I seen
Everything deployed (or seemed to) but prometheus was not picking up most metrics therefore Grafana was graphing almost nothing as it couldn't get most of the data it needed.
Notably grafana could not detect nodes, pods or deployments, so those options on dashboard were `None`

* Environment
minikube version 1.8
kubectl version 1.8.2

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"dirty", BuildDate:"2017-10-17T15:09:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: minikube

* Manifests:
There are a few places where `monitoring` namespace is hard coded and therefore I think the issue I faced was that the operator could not find the relevant rbac permission to get the data it needed

For example, [prometheus-k8s-role-bindings.yaml](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/prometheus/prometheus-k8s-role-bindings.yaml)
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus-k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
```

Grafana data source needs changed if prometheus is not in the monitoring namespace:
https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/grafana/grafana-dashboards.yaml#L6288

(There is almost definitely more references to `monitoring`)

* Prometheus Operator Logs: Sorry I don't have them to hand as retrospectively raising this.

* Other Notes:
Im raising this as the [deploy](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/hack/cluster-monitoring/deploy#L7-L17) script indicates that by setting a variable that you may be able to deploy to any namespace:
```
if [ -z "${NAMESPACE}" ]; then
    NAMESPACE=monitoring
fi

kubectl create namespace "$NAMESPACE"

kctl() {
    kubectl --namespace "$NAMESPACE" "$@"
}
```

I don't think that's the case due to the hard coding of certain values.
I expect that this might be better solved with the helm chart version at some point as a global namespace could be set to deploy all components to said namespace. I also notice that helm charts tend not to set a namespace explicitly and you can pass it to the helm command.

I thought it's important to note the issue as if you are using Nginx ingress, you cant have ingress across namespaces, which means you may need to deploy another ingress to the monitoring namespace to be able to access the service more easily. One more thing to consider in a live or staging environment etc.

Please let me know if I missed something and the above can be easily changed / configured.
