### ISSUE TITLE
Need to deploy Operator with restricted rights in a K8S cluster

### ISSUE THREAD

**Issue by younid** [coreos/prometheus-operator#787]
**What did you do?**
Hello,

I Deployed Prometheus with Operator following the "getting started" guide from the project site (https://coreos.com/operators/prometheus/docs/latest/user-guides/getting-started.html)
And it worked correctly but after this I needed to deploy it on another cluster which is using RBAC and is more restrictive. The administrator asked me to change RBAC files to reduce rights granted to Operator.

Is it possible to have Prometheus Operator running with a minimum of granted rights (cluster wide one) and is it safe enouth if I reduce rights by myself in RBAC declaration (with DENY logs in apiserver logs) ?
Thank's for your help.

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prometheus-operator
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-operator
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus-operator
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - "get"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - prometheuses
  - servicemonitors
  verbs:
  - "*"
- apiGroups: [""]
  resources:
  - nodes
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources:
  - namespaces
  verbs: ["list"]
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources:
  - services
  - endpoints
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: monitoring
  name: prometheus-operator
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs: ["list", "watch", "create", "update", "delete"]
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  verbs: ["list", "get", "watch", "create", "update", "delete"]
- apiGroups: [""]
  resources:
  - pods
  verbs: ["list", "delete"]
- apiGroups: [""]
  resources:
  - services
  - endpoints
  verbs: ["get", "create", "update"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operator
  namespace: monitoring
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/kubelet
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        image: quay.io/coreos/prometheus-operator:v0.15.0
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      serviceAccountName: prometheus-operator

```

**What did you expect to see?**
I expected Operator to be used  with less rights granted on cluster wide.

**What did you see instead? Under which circumstances?**
I see some errors in apiserver logs according to Operator trying to use verbs with cluster wide rights.

```
RBAC DENY: user "system:serviceaccount:monitoring:prometheus-operator" groups ["system:serviceaccounts" "system:serviceaccounts:monitoring" "system:authenticated"] cannot "list" resource "configmaps" cluster-wide
RBAC DENY: user "system:serviceaccount:monitoring:prometheus-operator" groups ["system:serviceaccounts" "system:serviceaccounts:monitoring" "system:authenticated"] cannot "list" resource "secrets" cluster-wide
RBAC DENY: user "system:serviceaccount:monitoring:prometheus-operator" groups ["system:serviceaccounts" "system:serviceaccounts:monitoring" "system:authenticated"] cannot "watch" resource "secrets" cluster-wide
RBAC DENY: user "system:serviceaccount:monitoring:prometheus-operator" groups ["system:serviceaccounts" "system:serviceaccounts:monitoring" "system:authenticated"] cannot "watch" resource "configmaps" cluster-wide

```

**Environment**

* Kubernetes version information:

	insert output of `kubectl version` here

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.

```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2+coreos.0", GitCommit:"c6574824e296e68a20d36f00e71fa01a81132b66", GitTreeState:"clean", BuildDate:"2017-07-24T23:28:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2+coreos.0", GitCommit:"c6574824e296e68a20d36f00e71fa01a81132b66", GitTreeState:"clean", BuildDate:"2017-07-24T23:28:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

```
* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
No error visible in Prometheus Operator logs
```

**Comment by brancz** [comment]
This is merely an example. You can also run the Prometheus Operator with the `--namespace` flag. Then it will only require `Role`s and `RoleBinding`s, however will also only work with objects within that namespace, and you need to create the CRDs yourself (as it requires cluster level roles to create them). `ClusterRole`s and `ClusterRoleBinding`s are not unreasonable, as that is exactly what upstream controllers use as well. If you need or want to run the Prometheus Operator in a restricted environment it is possible though.

**Comment by younid** [comment]
Hello and thank you for your answer.
If I understand well there's flag that I can use to setup the scope of Operator to the namespace I want.
Just to put this flag as parameter when creating the container like this ?

```
    spec:
      containers:
      - args:
        - --namespace=monitoring
        - --kubelet-service=kube-system/kubelet
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        image: quay.io/coreos/prometheus-operator:v0.15.0

```

Another question, when you say that I need to create CRDs by myself, what do you mean ?
Do I need to create a new yaml file and put inside an apiextension declaration ?

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition

```
If it is the case, what should I put inside because I have no such kind of declaration in my actual deployement of Prometheus Operator ?

Regards,
Younid

**Comment by brancz** [comment]
> If it is the case, what should I put inside because I have no such kind of declaration in my actual deployement of Prometheus Operator ?

Right, because the Prometheus Operator creates it for you, if you can give it a `ClusterRole` to do so. Otherwise this:

**Comment by younid** [comment]
Hello,
I putted the namespace flag in Operator deploiement manifest and created the CRDs with manual manifests also.

Here are the files used (without the RBAC part):

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
  namespace: monitoring-prom-ope
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
    spec:
      containers:
      - args:
        - --namespace=monitoring-prom-ope
        - --kubelet-service=kube-system/kubelet
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        image: quay.io/coreos/prometheus-operator:v0.15.0
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      serviceAccountName: prometheus-operator

```

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: servicemonitors.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    kind: ServiceMonitor
    listKind: ServiceMonitorList
    plural: servicemonitors
    singular: servicemonitor
  scope: Namespaced
  version: v1

```

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: prometheuses.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    kind: Prometheus
    listKind: PrometheusList
    plural: prometheuses
    singular: prometheus
  scope: Namespaced
  version: v1

```


```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: alertmanagers.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    kind: Alertmanager
    listKind: AlertmanagerList
    plural: alertmanagers
    singular: alertmanager
  scope: Namespaced
  version: v1

```

For the moment I still have some errors because Operator is not able to list or watch some resources but they are declared with a verb set to ["*"] in Role part and binded with RoleBinding to the user.

```
ts=2017-11-29T23:13:56Z caller=operator.go:156 component=alertmanageroperator msg="connection established" cluster-version=v1.7.2+coreos.0
ts=2017-11-29T23:13:56Z caller=operator.go:257 component=prometheusoperator msg="connection established" cluster-version=v1.7.2+coreos.0
ts=2017-11-29T23:13:56Z caller=operator.go:170 component=alertmanageroperator msg="CRD API endpoints ready"
E1129 23:13:56.319071       5 reflector.go:201] github.com/coreos/prometheus-operator/pkg/alertmanager/operator.go:178: Failed to list *v1beta1.StatefulSet: User "system:serviceaccount:monitoring-prom-ope:prometheus-operator" cannot list statefulsets.apps in the namespace "monitoring-prom-ope". (get statefulsets.apps)
ts=2017-11-29T23:13:56Z caller=operator.go:271 component=prometheusoperator msg="CRD API endpoints ready"
E1129 23:13:56.339262       5 reflector.go:304] github.com/coreos/prometheus-operator/pkg/alertmanager/operator.go:177: Failed to watch *v1.Alertmanager: User "system:serviceaccount:monitoring-prom-ope:prometheus-operator" cannot watch alertmanagers.monitoring.coreos.com in the namespace "monitoring-prom-ope". (get alertmanagers.monitoring.coreos.com)
E1129 23:13:56.339496       5 reflector.go:201] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:282: Failed to list *v1beta1.StatefulSet: User "system:serviceaccount:monitoring-prom-ope:prometheus-operator" cannot list statefulsets.apps in the namespace "monitoring-prom-ope". (get statefulsets.apps)
E1129 23:13:56.342119       5 reflector.go:304] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:278: Failed to watch *v1.Prometheus: User "system:serviceaccount:monitoring-prom-ope:prometheus-operator" cannot watch prometheuses.monitoring.coreos.com in the namespace "monitoring-prom-ope". (get prometheuses.monitoring.coreos.com)
E1129 23:13:56.343603       5 reflector.go:201] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:281: Failed to list *v1.Secret: User "system:serviceaccount:monitoring-prom-ope:prometheus-operator" cannot list secrets in the namespace "monitoring-prom-ope". (get secrets)
E1129 23:13:56.352296       5 reflector.go:304] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:279: Failed to watch *v1.ServiceMonitor: User "system:serviceaccount:monitoring-prom-ope:prometheus-operator" cannot watch servicemonitors.monitoring.coreos.com in the namespace "monitoring-prom-ope". (get servicemonitors.monitoring.coreos.com)

```

**Comment by brancz** [comment]
Can you share the exact Role and RoleBinding you are using?

**Comment by younid** [comment]
Hello,

Thank you for your support. I managed to make it (nearly) work properly now.
There's only one last bad log visible in apiserver and in Opertaor's pod :

`rbac.go:114] RBAC DENY: user "system:serviceaccount:monitoring-prom-ope:prometheus-operator" groups ["system:serviceaccounts" "system:serviceaccounts:monitoring-prom-ope" "system:authenticated"] cannot "update" resource "services" named "kubelet" in namespace "kube-system"
`
`ts=2017-11-30T16:06:13Z caller=operator.go:341 component=prometheusoperator msg="syncing nodes into Endpoints object failed" err="synchronizing kubelet service object failed: updating service object failed: User \"system:serviceaccount:monitoring-prom-ope:prometheus-operator\" cannot update services in the namespace \"kube-system\". (put services kubelet)"
`

However, here is my last RBAC and deployment last manifest version. Nothing else is changed.

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: monitoring-prom-ope
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus-operator
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - "get"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "get"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - prometheuses
  - servicemonitors
  verbs: ["get", "list"]
- apiGroups: [""]
  resources:
  - pods
  verbs: ["list"]
- apiGroups: [""]
  resources:
  - services
  - endpoints
  verbs: ["get", "list"]
- apiGroups: [""]
  resources:
  - nodes
  verbs: ["list"]
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs: ["list"]
- apiGroups: [""]
  resources:
  - namespaces
  verbs: ["list"]
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prometheus-operator
  namespace: monitoring-prom-ope
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-operator
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: monitoring-prom-ope
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: prometheus-operator
  namespace: monitoring-prom-ope
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - prometheuses
  - servicemonitors
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs: ["*"]
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  verbs: ["*"]
- apiGroups: [""]
  resources:
  - pods
  verbs: ["list", "delete"]
- apiGroups: [""]
  resources:
  - services
  - endpoints
  verbs: ["get", "create", "update"]
- apiGroups: [""]
  resources:
  - nodes
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources:
  - namespaces
  verbs: ["list"]
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operator
  namespace: monitoring-prom-ope
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-operator
  name: prometheus-operator
  namespace: monitoring-prom-ope
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
    spec:
      containers:
      - args:
        - --namespace=monitoring-prom-ope
        - --kubelet-service=kube-system/kubelet
        - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
        image: quay.io/coreos/prometheus-operator:v0.15.0
        name: prometheus-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      serviceAccountName: prometheus-operator

```

Regards,
Younid
