### ISSUE TITLE
cant create kube-prometheus

### ISSUE THREAD

**Issue by shavo007** [coreos/prometheus-operator#816]
**What did you do?**
Ran command

```

 helm install --name kube-prometheus   --namespace=monitoring --set prometheus.rbacEnable=false --set rbacEnable=false --set exporter-kube-state.rbacEnable=false helm/kube-prometheus



```

Commented out requirements  based on existing issue  #443

```
dependencies:
  - name: alertmanager
    version: 0.0.5
    #e2e-repository: file://../alertmanager
    repository: https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/

  - name: prometheus
    version: 0.0.5
    #e2e-repository: file://../prometheus
    repository: https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/

```

**What did you expect to see?**
Resources created...

**What did you see instead? Under which circumstances?**

Error: found in requirements.yaml, but missing in charts/ directory: exporter-kube-api, exporter-kube-controller-manager, exporter-kube-dns, exporter-kube-etcd, exporter-kube-scheduler, exporter-kube-state, exporter-kubelets, exporter-kubernetes, exporter-node, grafana

If I use the official chart the node exporters keep crashing aswell. So Im stuck!!! 

**Environment**

* Kubernetes version information:

	insert output of `kubectl version` here 1.6.4

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, 

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```
