### ISSUE TITLE
How to view service monitors and CRD

### ISSUE THREAD

**Issue by shavo007** [coreos/prometheus-operator#818]
* Kubernetes version information:

	Client version v1.8.1
Server version: v1.7.4

* Kubernetes cluster kind: 

: kops, 

sample service monitor

* Manifests:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingestr
  namespace: monitoring
  labels:
    k8s-app: ingestr
    app: ingestr
    env: dev
spec:
  selector:
    matchLabels:
      app: ingestr
  namespaceSelector:
    matchNames:
    - dev
  endpoints:
  - port: http
    path: /management/prometheus
```

I cant see these resources on the dashboard.

Or how can i view them with kubectl?

Thanks,
Shane.
