### ISSUE TITLE
Grafana helm and serverDashboardFiles

### ISSUE THREAD

**Issue by sebglon** [coreos/prometheus-operator#819]
**What did you do?**
Hello, 

Acutaly, i have no found documentation on how to use Helm package and how to customize configuration.
I want to haveto deploy many custom json dashboard with helm but i have an error with `serverDashboardFiles`.

This is my values.yml:
```
grafana:
    image:
        tag: 4.5.2
    service:
        type: loadBalancer
        loadBalancerIP:
    dataSource: 
        - assets/grafana.ds/prometheus-datasource.json
    serverDashboardFiles: 
        - assets/grafana.dashboard/prometheus-datasource.json
        - assets/grafana.dashboard/deployment-dashboard.json  
```
And i have this error: 
```
helm install --name sgl1 . -f ../../jenkins-env/preprod/metrology-values.yaml --namespace sgl
Error: release sgl1 failed: ConfigMap in version "v1" cannot be handled as a ConfigMap: [pos 27]: json: expect char '{' but got char '['
```

The json dashboard is valid and is well imported if i create manualy the configmap.

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

GKE 1.7.11

* Kubernetes version information:

kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.11-gke.0", GitCommit:"3500f53730c1fea7b57901977df165c3eb317bce", GitTreeState:"clean", BuildDate:"2017-11-27T19:37:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

GKE deployment

**Comment by brancz** [comment]
@gianrubio @weiwei04 ^

**Comment by shavo007** [comment]
+1 just came across this. in the doc there is no mention of serverDashboardFiles in values file.

located here 
https://github.com/coreos/prometheus-operator/tree/master/helm/grafana

Or how easy is it to add in dashboards from bundle here?

https://github.com/aws-samples/aws-workshop-for-kubernetes/blob/master/cluster-monitoring/templates/prometheus/grafana-bundle.yaml

**Comment by shavo007** [comment]
apologies for the questions:

but what is the main differences from main helm chart and this one?
https://hub.kubeapps.com/charts/stable/grafana

**Comment by gianrubio** [comment]
@sebglon I can take a look on it, can you share your json files?

**Comment by gianrubio** [comment]
> but what is the main differences from main helm chart and this one?

@shavo007 the main diference is the [grafana-watcher](https://github.com/coreos/prometheus-operator/blob/6fe338830364822d7fbb12aad70327d2cd5c6bf2/contrib/grafana-watcher/README.md) that automatically generate grafana configuration after changes in the configmap.

**Comment by sebglon** [comment]
I have only extracted your dashboard available on https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/grafana/grafana-dashboards.yaml

**Comment by sebglon** [comment]
When i launch dry-run on debug, i have this:
```
# Source: jenkins/charts/grafana/templates/dashboards-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: pouring-jaguar-grafana
    chart: "grafana-0.5.0"
    component: "grafana"
    heritage: "Tiller"
    release: "pouring-jaguar"
  name: pouring-jaguar-grafana-dashs
data:
  - assets/grafana.dashboard/kubernetes-cluster-status-dashboard.json
```
