### ISSUE TITLE
Feature Request: support dropping metrics at scrape time

### ISSUE THREAD

**Issue by Capitrium** [coreos/prometheus-operator#826]
We recently ran a batch of about 2 million k8s jobs in under 24 hours, which led to some serious time series churn since the kubelets and kube-state-metrics expose metrics for every pod, and Prometheus was inevitably OOM-killed even with the memory requests/limits set to over 50Gi.

Our temporary solution was to simply stop scraping those sources entirely to prevent Prometheus from getting overloaded. This works, but is a bit excessive since we still want to collect those metrics for longer-running pods.

Ideally, we'd be able to configure the prometheus operator to ignore those metrics when scraping those sources. Are there any thoughts on adding this functionality to the operator? Maybe adding a `dropTargets` field to the Endpoint spec, something like this:

```yaml
dropTargets:
- match: my-job-pod-.+
  source:
  - pod_name
```

The above would add the following to the `relabel_configs` in the Prometheus configuration generated for that ServiceMonitor:

```yaml
- source_labels: [__meta_kubernetes_pod_name]
  separator: ;
  regex: (my-job-pod-.+)
  action: drop
```

Currently, the only long-term solution is to use a custom Prometheus configuration, and I'd rather not have to give up all the other functionality in the prometheus operator associated with doing that.
