### ISSUE TITLE
Proposal: Configure Prometheus alerts in the ServiceMonitor

### ISSUE THREAD

**Issue by gianrubio** [coreos/prometheus-operator#828]
ServiceMonitors and NetworkPolicies are good examples on the flexibility that kubernetes can offer to developers configure theirs monitoring and networking rules. 

I thought we are missing a flexibility to customize alerts because nowadays developers need access to configmap to change alerts. I'm proposing to add an object in the [ServiceMonitor](https://github.com/coreos/prometheus-operator/blob/197eb012d973f5aaf4d0446fd8f638f1b9067128/pkg/client/monitoring/v1/types.go#L177-L185) to accept alerts configuration.

Any thoughts?

**Comment by brancz** [comment]
Can you elaborate on the difference on configuring alerts in the ServiceMonitor vs in a ConfigMap? Dynamic reloading that is mentioned in the tweet is taken care of by the Prometheus Operator.

I feel what you're looking for here is a general application definition abstraction on top of Kubernetes and Prometheus in general.

**Comment by gianrubio** [comment]
My first thought was not really clear let me explain again. I would like to have an way to configure the alerts not only in the configmaps. My proposal was to allow the serviceMonitor to accept alerts definition something like this:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
...
  alerts: |+
  groups:
  - name: elasticsearch.rules
    rules:
      - alert: ElasticSearchNodeDown
        expr: up{job="es-metrics"} == 0 or count(job="es-metrics") == 0
        for: 20m
        labels:
          service: elasticsearch
          severity: warning
        annotations:
          summary: Elasticsearch cannot be scraped
          description: Prometheus could not scrape a {{ $labels.job }} for more than 20 minutes
```

In that case developers doesn't need to touch the configmap, they will only manipulate one file that will be the `serviceMonitor`.
