### ISSUE TITLE
External Services not showing up as a target

### ISSUE THREAD

**Issue by loganasherjones** [coreos/prometheus-operator#834]
**What did you do?**
I am attempting to monitor a ceph cluster with the prometheus running inside the kubernetes cluster. I created a service with `ExternalName` and an `Endpoints` inside the cluster for the external service.  I can successfully hit the endpoint from inside a pod in the cluster. I then created a `ServiceMonitor` and the configuration appeared in Prometheus, but I don't see the target and no errors are reported in any logs. This feels to me like I am just missing something, but I cannot figure out what I've missed.

**What did you expect to see?**
I expected to see the external service show up as a target or errors in the prometheus-operator log.

**What did you see instead? Under which circumstances?**
No target showed up for the external service and no logs in the prometheus-operator log.

**Environment**

* Kubernetes version information:

- Kuberentes 1.8.4

* Kubernetes cluster kind: 

- kubeadm

* Manifests:

External service manifests (Deployed to the `kube-system` namespace)
```
---
apiVersion: v1
kind: Service
metadata:
  name: ceph-k8s
  labels:
    component: ceph-k8s
spec:
  type: ExternalName
  externalName: {EXTERNAL_IP}
  ports:
  - port: 9283
    name: scrape
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ceph-k8s
  labels:
    k8s-app: ceph-k8s
subsets:
  - addresses:
    - ip: {EXTERNAL_IP}
    ports:
      - port: 9283
```

ServiceMonitor (deployed, along with prometheus-operator/prometheus in the `monitoring` namespace)
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ceph-k8s
  labels:
    k8s-app: ceph-k8s
  spec:
    endpoints:
      - port: scrape
        interval: 30s
        path: /
      selector:
        matchLabels:
          component: ceph-k8s
      namespaceSelector:
        matchNames:
        - kube-system
```

The configuration that gets generated in Prometheus:

```
- job_name: monitoring/ceph-prometheus/9
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /
  scheme: http
  kubernetes_sd_configs:
  - api_server: null
    role: endpoints
    namespaces:
      names:
      - kube-system
  relabel_configs:
    ...
````

* Prometheus Operator Logs:

No errors
```
ts=2017-12-19T15:50:30Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2017-12-19T15:50:30Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2017-12-19T15:50:30Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2017-12-19T15:50:30Z caller=operator.go:983 component="prometheusoperator" msg="current config or current configmaps has changed"
ts=2017-12-19T15:50:30Z caller=operator.go:989 component="prometheusoperator" msg="updating configuration"
ts=2017-12-19T15:50:30Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2017-12-19T15:50:30Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
ts=2017-12-19T15:50:30Z caller=operator.go:671 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
```

**Comment by brancz** [comment]
External Services are currently not supported by Prometheus, therefore we don't have any possibility to support it either yet. There have been some attempts at it though, that I believe just need to be finished up.

Related:
* https://github.com/coreos/prometheus-operator/pull/372
* https://github.com/prometheus/prometheus/issues/2791

**Comment by jdoupe** [comment]
For the record, this example works fine - if you label the Service and Endpoints the same (you have one labeled "component: ceph-k8s" and the other "k8s-app: ceph-k8s") and obviously set the ServiceMonitor selector to match.

**Comment by amalucelli** [comment]
Below a example that works if anyone needs.

The point here's that we need three manifests:

1. `Service` that points to the external resource (`type: ExternalName`);
2. `Endpoints` that points to the external address of our resource (this type of service don't create the `Endpoint` resource automatically, we need to create it manually);
3. `ServiceMonitor` with the correct selectors;

**Service Manifest**

```yaml
kind: Service
apiVersion: v1
metadata:
  name: my-internal-server
  labels:
    k8s-app: node-exporter
spec:
  externalName: 1.2.3.4
  type: ExternalName
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: 9100
```

**Endpoints Manifest**

```yaml
apiVersion: v1
kind: Endpoints
metadata:
  name: my-internal-server
  labels:
    k8s-app: node-exporter
subsets:
- addresses:
  - ip: 1.2.3.4
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
```

**ServiceMonitor Manifest**

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: internal-servers
  labels:
    k8s-app: node-exporter
spec:
  selector:
    matchLabels:
      k8s-app: node-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: metrics
    interval: 10s
    honorLabels: true
    path: /metrics
```

**Comment by stonefury** [comment]
@amalucelli  I'm currently trying to get external nodes monitored.  Your example was very close but the service file looked like it was missing the port:.  Could you confirm this still works? I just set this up via the specs below but it doesn't seem to be working.

`pet-bfleming-2:try3 bfleming$ cat *
apiVersion: v1
kind: Endpoints
metadata:
  name: my-internal-server
  labels:
    k8s-app: node-exporter
subsets:
- addresses:
  - ip: 172.20.58.243
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: internal-servers
  labels:
    k8s-app: node-exporter
spec:
  selector:
    matchLabels:
      k8s-app: node-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: metrics
    interval: 10s
    honorLabels: true
    path: /metrics
kind: Service
apiVersion: v1
metadata:
  name: my-internal-server
  labels:
    k8s-app: node-exporter
spec:
  type: ExternalName
  externalName: 172.20.58.243
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: 9100
pet-bfleming-2:try3 bfleming$`

**Comment by amalucelli** [comment]
@stonefury yes! I've compared and reviewed your configuration based on my working stack and your configuration looks good, the only thing that differs are the `k8s-app` label and the `ip` address.

Can you review the following points?

1. The `Service` and `Endpoints` were created in `monitoring` namespace?
2. Are your `Prometheus` configured to select the `k8s-app` label?

```
  serviceMonitorSelector:
    matchExpressions:
    - {key: k8s-app, operator: Exists}
```

As far as I know, the `ports` spec when `Service` is a `ExternalName` doesn't have any effects, I usually configure this only for convinience as I know what kind of ports I'm using on those external servers.

**Comment by stonefury** [comment]
@amalucelli  I cleaned up some of my failed attempts, and maybe I needed to wait a little longer for data to show up. It works! Fantastic, thanks for your post on this, and really appreciate you responding so quick. You should create a gist for this. That example is very useful.

**Comment by amalucelli** [comment]
That's nice @stonefury!

For the friendly name, some considerations/ideas:

Grafana use the following templating on `nodes-dashboard.json` to suggest the `IP`:`Port` list:

```yaml
"query": "label_values(node_boot_time, instance)",
```

Querying Prometheus for `node_boot_time`, Grafana use the [`label_values`](http://docs.grafana.org/features/datasources/prometheus/#query-variable) function based on the `instance` label, that will return all of our nodes *(below we have k8s nodes and external servers)*: 

**Element** | **Value**
-- | --
`node_boot_time{endpoint="https",instance="1.2.3.4:9100",job="node-exporter",namespace="monitoring",pod="node-exporter-xpto123",service="node-exporter"}` | `1521484132`
`node_boot_time{endpoint="https",instance="1.2.3.5:9100",job="node-exporter",namespace="monitoring",pod="node-exporter-xpto456",service="node-exporter"}` | `1520525328`
`node_boot_time{endpoint="metrics",instance="5.6.7.8:9100",job="internal-server-server1",namespace="servers",service="internal-server-server1"}` | `1520008665`
`node_boot_time{endpoint="metrics",instance="5.6.7.9:9100",job="internal-server-server2",namespace="servers",service="internal-server-server2"}` | `1520519128`

As you can see, in this model we don't have a common tag that works for both k8s nodes and external servers. I would suggest to you to create a new dashboard only for those internal servers and change that specific query.

**Comment by stonefury** [comment]
Thanks @amalucelli .  I don't quite understand your suggestion on getting friendly values. I tried a few things, but I think I just need to learn more about grafana and prometheus. At this point I'm just familiar with the k8s aspect of it.

**Comment by bamb00** [comment]
@amalucelli I have a service that is not external that I am targeting.  Would I still need the endpoint? For example the target will be a service,

          kind: Service
          apiVersion: v1
          metadata:
            name: my-internal-server
            labels:
              k8s-app: node-exporter
          spec:
            ports:
            - name: metrics
              port: 9100
              protocol: TCP
              targetPort: 9100

          apiVersion: v1
          kind: Endpoints
          metadata:
            name: my-internal-server
            labels:
              k8s-app: node-exporter
          subsets:
            ports:
            - name: metrics
              port: 9100
              protocol: TCP

          apiVersion: monitoring.coreos.com/v1
          kind: ServiceMonitor
          metadata:
            name: internal-servers
            labels:
              k8s-app: node-exporter
          spec:
            selector:
              matchLabels:
                k8s-app: node-exporter
            namespaceSelector:
              matchNames:
              - monitoring
            endpoints:
            - port: metrics
              interval: 10s
              honorLabels: true
              path: /metrics

**Comment by amalucelli** [comment]
@bamb00 I think that you only need to specify a selector for your `Service` object. Also don't create manually the `Endpoints` resource after that.

Based on the [docs](https://kubernetes.io/docs/concepts/services-networking/service/):

> The Service’s selector will be evaluated continuously and the results will be POSTed to an Endpoints object also named “my-service”.

Also in the docs, there's a example of what happens when you don't specify the selector spec.

> Because this service has no selector, the corresponding Endpoints object will not be created.

**Comment by CharlesHuangGeminiOpenCloud** [comment]
Hi, I use the following yaml to create Endponts & Service & ServiceMonitor. kubectl create with no error and  I can also see the `monitoring/nodejs-metrics-sm/0` item in prometheus web Status -> Service Discovery page.  

But service not showing up as a target , and in the `monitoring/nodejs-metrics-sm/0` item,  the Target Labels show `Dropped` value. 

p.s. use prometheus-operator tag: v0.18.0 ; k8s 1.10

Hope someone can help.  
Thanks in advance.

endpoint.yaml
```  
apiVersion: v1
kind: Endpoints
metadata:
  name: nodejs-metrics
  labels:
    k8s-app: nodejs-metrics
subsets:
  - addresses:
    - ip: 10.113.99.1
    ports:
      - name: metrics
        port: 3000
        protocol: TCP
```


service.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: nodejs-metrics-svc
  namespace: monitoring
  labels:
    k8s-app: nodejs-metrics
spec:
  type: ExternalName
  externalName: 10.113.99.1
  ports:
  - name: metrics
    port: 3000
    protocol: TCP
    targetPort: 3000
```


service_monitor.yaml
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: nodejs-metrics-sm
  labels:
    k8s-app: nodejs-metrics
spec:
  selector:
    matchLabels:
      k8s-app: nodejs-metrics
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
  - port: metrics
    interval: 10s
    honorLabels: true
    path: /metrics
```
