### ISSUE TITLE
How to configure grafana.ini inside kube-prometheus

### ISSUE THREAD

**Issue by xussof** [coreos/prometheus-operator#835]
Hi all,
I'm trying to deploy a kube-prometheus with grafana using terraform. But basically the command that terraform uses is helm install --name kube-prometheus coreos/kube-prometheus. Today has beed release the newest version of this git so grafana is allowed to be installed throught kube-prometheus-values.yaml

My question is how I can edit /etc/grafana/grafana.ini which is  afile inside the container, to allow Google OATh for example.

I have read something about configMap but I don't know how exactly how I can include this file with configs inside this helm. I have been hours trying to find a solution but nothing has worked.

Thanks

**Comment by brancz** [comment]
Luckily Grafana allows configuring almost anything via environment variables. I would suggest to extend the helm chart to allow configuring everything to your needs.

/cc @weiwei04

**Comment by xeor** [comment]
Just make sure you don't set `GF_SERVER_ENFORCE_DOMAIN`, or the config-reloader container wont work.

As an example, here is how you can let a proxy in front (that you trust), add headers to authenticate you and make you admin. Useful for grafana @ home :)

```
    extraVars:
    - name: GF_SERVER_DOMAIN
      value: "grafana.your.domain"
    - name: GF_USERS_ALLOW_SIGN_UP
      value: "false"
    - name: GF_USERS_ALLOW_ORG_CREATE
      value: "false"
    - name: GF_USERS_AUTO_ASSIGN_ORG
      value: "true"
    - name: GF_USERS_AUTO_ASSIGN_ORG_ROLE
      value: "Admin"
    - name: GF_AUTH_DISABLE_LOGIN_FORM
      value: "true"
    - name: GF_AUTH_DISABLE_SIGNOUT_MENU
      value: "true"
    - name: GF_AUTH_PROXY_ENABLED
      value: "true"
    - name: GF_AUTH_PROXY_HEADER_NAME
      value: "x-auth-request-user"
    - name: GF_AUTH_PROXY_HEADER_PROPERTY
      value: "username"
    - name: GF_AUTH_PROXY_AUTO_SIGN_UP
      value: "true"
```
