### ISSUE TITLE
k8sControllerManagerDown/k8sSchedulerDown alerts happening daily

### ISSUE THREAD

**Issue by sujithnss** [coreos/prometheus-operator#845]
Hi Team

I'm novice to here and i have set up the prometheus-operator in Kubernetes Cluster. But daily I'm seeing the below alert. I'm not sure what went wrong and where to trace the issue. Kindly please help me. 

- 1 alert for alertname=K8SSchedulerDown

- 1 alert for alertname=K8SControllerManagerDown

* Kubernetes version information:

	Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:46:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
	kops

**Comment by brancz** [comment]
I'm guessing you're not actually monitoring the scheduler and controller manager, can you have a look at the `/targets` page of your Prometheus server and check whether there is a healthy scheduler and controller manager?

**Comment by thoslin** [comment]
Got the same issue here. Check the targets page, no scheduler or controller monitored. Are we supposed to add these targets manually? I'm just wondering if these targets are not set up by default, should the rules be excluded by default?

**Comment by brancz** [comment]
This sadly depends on the way you have setup your cluster. A while ago I tried to push for some normalization across install methods, but it didn't lead anywhere.

You need to make sure there is an `Endpoints` object in the `kube-system` namespace that exposes the IPs of your controller-manager and scheduler. In a self-hosted environment (for example created through bootkube) it is enough to simply create these services:

https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus/manifests/k8s/self-hosted

As this is not the first time this was reported, some community members have started to contribute services for kubeadm:

https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus/manifests/k8s/kubeadm

I'm happy to accept PRs for any further install methods, if they are generalizable.

**Comment by shamsalmon** [comment]
If you are using kops those self-hosted ones should fix your issue. They did for me.

**Comment by ne1000** [comment]
@sujithnss @brancz  I also met the same issue, but in my case i have used binary packages to install the cluster , can you give me a piece of advice fix the issue?

**Comment by brancz** [comment]
In that case you either need to make use of the `additionalScrapeConfigs` functionality to use another service discovery mechanism other than Prometheus, or maintain a `Service` and respective `Endpoints` object manually.

**Comment by ne1000** [comment]
@brancz Thank you for your help, for example. I have create a service object as below:

```
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-controller-manager-prometheus-discovery
  labels:
    k8s-app: kube-controller-manager
spec:
  selector:
    k8s-app: kube-controller-manager
  type: ClusterIP
  ports:
  - name: http-metrics
    port: 10252
    targetPort: 10252
    protocol: TCP

```

but I don't understand how to create Endpoints object manually, do I have to do anything else?

**Comment by brancz** [comment]
You want to skip the `selector`, as that will allow you to manually provision the underlying `Endpoints` object. In the end that looks something like:

```
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-controller-manager-prometheus-discovery
  labels:
    k8s-app: kube-controller-manager
spec:
  type: ClusterIP
  ports:
  - name: http-metrics
    port: 10252
    targetPort: 10252
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  namespace: kube-system
  name: kube-controller-manager-prometheus-discovery
  labels:
    k8s-app: kube-controller-managersubsets:
- addresses:
  - ip: 127.0.0.1
  ports:
  - name: http-metrics
    port: 10252
    protocol: TCP
```

Just replacing or adding the IPs to the `addresses` array.
