### ISSUE TITLE
kube-prometheus persistent volumes 

### ISSUE THREAD

**Issue by simon-k8s** [coreos/prometheus-operator#860]
**What did you do?**

I configured kube-prometheus with the vaules.yaml. The I tried to install the charts in the recommended way:

```
helm install  --name prometheus-operator coreos/prometheus-operator
helm install --name kube-prometheus -f values.yaml coreos/kube-prometheus
helm install --name grafana -f values.yaml  coreos/grafana
```

**What did you expect to see?**

I expected to see a complete prometheus installation. Including the prometheus operator a few exporter the alertmanager and grafana. 

What did you see instead? Under which circumstances?

The exporter pods were created and the prometheus operator and grafana. The two pods that should be created via the prometheus operator were missing:
```
alertmanager-kube-prometheus-0
prometheus-kube-prometheus-0
```
I deleted the kube-prometheus deployment. Then  I edited the values.yaml and commented out the configuration for the persistent volumes:

```
 ## Alertmanager StorageSpec for persistent data
  ## Ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/storage.md
  ##
  storageSpec: {} 
  #  class: generic 
  #  resources:
  #    requests:
  #      storage: 2Gi
  selector: {}
```

I deployed again and the two pods were created but without the needed volumes. What do I need to do to deploy the alertmanager and the prometheus pod with persistent storage? The grafana chart works with a very similar storage configuration.  

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-16T03:16:50Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:05:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by gianrubio** [comment]
The [storage spec](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/storage.md#manual-storage-provisioning) was changed in previous version and the helm example haven't been update.

Please remove the previous installed charts, change the storageSpec and install it again.

``` 
spec:
  ...
  storage:
    volumeClaimTemplate:
      spec:
        selector:
          matchLabels:
            app: my-example-prometheus
        resources:
          requests:
            storage: 10Gi 
``` 

Note: Since the last kube-prometheus chart update, grafana is installed [by default] (https://github.com/coreos/prometheus-operator/blob/master/helm/kube-prometheus/values.yaml#L5) so you don't need to setup it.

**Comment by simon-k8s** [comment]
@gianrubio cheers that fixed the problem. I now have two volumes one for the alertmanager and one  for prometheus. Will you add an option to create a pv for the grafana installation?

**Comment by gianrubio** [comment]
@simon-k8s glas to help you, I'll do a PR to fix the docs.

>Will you add an option to create a pv for the grafana installation? 

 I don't think you need a pv for grafana, all the configurations are loaded during the bootstrap of the grafana container. If you want to change configuration I'd recommend you to do in the configmaps.

**Comment by leifmadsen** [comment]
@gianrubio in what version of Operator was the storage spec updated? I can't for the life of me get the persistent storage to deploy due to errors in the Go code (missing data for the deprecated methods):

```
storage:
    volumeClaimTemplate:
      spec:
        storageClassName: prometheus
        resources:
          requests:
            storage: 2Gi
```
I seem to be running `v0.17.0` so I'm a bit confused why I'm getting an issue with the Go structs complaining.

**Comment by leifmadsen** [comment]
OK, actually after destroying my cluster, and doing another set of tests, I was able to figure out a working configuration:

```
  storage:
    class: ""
    selector: {}
    resources: {}
    volumeClaimTemplate:
      spec:
        storageClassName: promops
        resources:
          requests:
            storage: 2Gi
```

I'll see what I can do about supplying a documentation update, because I wasn't able to get things working without defining the deprecated arguments.

(FYI this is being added to the old [deprecated?] `kube-prometheus/manifests/` because my environment doesn't allow for the use of Helm currently.)
