### ISSUE TITLE
using external Alert Manager

### ISSUE THREAD

**Issue by tomplus** [coreos/prometheus-operator#871]
**What did you do?**

I want to use an external AlertManager (not deployed on K8s cluster) but I can't see any way to do it. There are no options to point external Service as AlertManager.

**What did you expect to see?**

I created AlertManager service:

```yaml
kind: Service
apiVersion: v1
metadata:
  name: alertmanager-ext
  namespace: monitoring
spec:
  type: ExternalName
  externalName: alertmanager.example.com
```
But Prometheus needs endpoints (which need IP addresses, which I don't want to store there).

Or maybe an option to add something to the generated prometheus config, I could use it to add my own section about alertmanager, for instance:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: example
spec:
  replicas: 1
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: example
  additionalConfiguration: |
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - alertmanager.example.com
```

Any ideas ?  Thanks !

**Comment by brancz** [comment]
You only need to make sure that your Alertmanager cluster IPs are in an `Endpoints` object, then it can be "discovered" like any other Alertmanager as if it was running on Kubernetes. Make sure though that *all* Alertmanager nodes are discovered, as that's the HA contract between Prometheus and Alertmanager.

**Comment by tomplus** [comment]
Yes, I did such test:

```
kind: Service
apiVersion: v1
metadata:
  name: alertmanager-ext
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 80
---
kind: Endpoints
apiVersion: v1
metadata:
  name: alertmanager-ext
  namespace: monitoring
subsets:
  - addresses:
      - ip: 93.184.216.34
    ports:
      - name: web
        port: 80
```
and Prometheus found it. But I have to store IP address there :/ It's external address of loadbalancer, it can change and so I have to synchronize it somehow.
