### ISSUE TITLE
Alerting DeadMansSwitch

### ISSUE THREAD

**Issue by KeithTt** [coreos/prometheus-operator#883]
kube version: 1.9.1

I stop a kubelet on one node when I test email-alert config, after that I start the kubelet, alerts disappear except this one.

![image](https://user-images.githubusercontent.com/15189954/34866164-87e69938-f7b6-11e7-978a-f1cf89a756fa.png)

How to deal with this alert?...

**Comment by brancz** [comment]
The `DeadMansSwitch` is intended to fire at all times. It makes sure that your entire alerting pipeline actually works.

Basically it verifies, that Prometheus can reach Alertmanager, and Alertmanager can reach your notification provider. PagerDuty for example has an integration called DeadMansSnitch, which pages you, when an alert _is not_ firing. Basically when you get paged about this, it means something in your alerting pipeline is broken, and you may not be receiving alerts.

If your notification provider doesn't support something like this, it's still worth having to check that Prometheus can reach Alertmanager, but you may want to either silent the alert, or route it to /dev/null.

Let us know if you have any other questions, but in terms of the issue reported, everything is working as expected.

**Comment by KeithTt** [comment]
@brancz Thanks for your time.

How to check that Prometheus can reach Alertmanager?

I can receive emails about this alert.

![image](https://user-images.githubusercontent.com/15189954/34868888-2dbfc09c-f7c0-11e7-962a-9d6e4a2f5e9e.png)

Does this mean Prometheus can reach Alertmanager?

**Comment by brancz** [comment]
Yes, but you probably don't want to actually send that alert via email. I highly recommend not using email as your notification mechanism, as it doesn't support anything like a deadmansswitch. If you want to use email then I would suggest to configure alertmanager not to send alerts with severity "none".

**Comment by KeithTt** [comment]
So this alert does not need to deal with?

And how to config alertmanager not to sent alert with severity "none"?...

**Comment by brancz** [comment]
I recommend pagerduty or opsgenie. If you just want to not send those alerts you can filter them in the alertmanager config, by saying you want to send all alerts where severity != none.

**Comment by KeithTt** [comment]
@brancz Thanks for your advice, I will have a try.

And I add `severity != none` to my alert config:

```
global:
  resolve_timeout: 5m
  smtp_smarthost: "mail.xxxx.com:25"
  smtp_from: "example@xxxx.com"
  smtp_auth_username: "expample@xxxx.com"
  smtp_auth_password: "pass"
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 15m
  receiver: team-X-mails
  routes:
  - match_re:
      alertname: ^(host_cpu_usage|node_filesystem_free|host_down)$
    receiver: team-X-mails
    routes:
    - match_re:
        severity: != none
      receiver: team-X-mails
receivers:
- name: "team-X-mails"
  email_configs:
  - to: "example@xxxx.com"
```

Am I right?...

**Comment by KeithTt** [comment]
@brancz I still do not figure out how to set `severity != none`, I need your help...

**Comment by brancz** [comment]
I would have to try myself, but I think what you're looking for is:

```
global:
  resolve_timeout: 5m
  smtp_smarthost: "mail.xxxx.com:25"
  smtp_from: "example@xxxx.com"
  smtp_auth_username: "expample@xxxx.com"
  smtp_auth_password: "pass"
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 15m
  receiver: team-X-mails
  routes:
  - match_re:
      alertname: ^(host_cpu_usage|node_filesystem_free|host_down)$
      severity: ^(none)$
    receiver: team-X-mails
receivers:
- name: "team-X-mails"
  email_configs:
  - to: "example@xxxx.com"
```
