### ISSUE TITLE
[helm] grafana datasource & prometheus scrape target don't respect prometheus.routePrefix

### ISSUE THREAD

**Issue by danielm0hr** [coreos/prometheus-operator#903]
**What did you do?**

Set `prometheus.routePrefix: /prometheus` in order to make ingress on subpath work.

**What did you expect to see?**

- Grafana datasource set to `http://kube-prometheus-prometheus:9090/prometheus`
- Prometheus scrape target for prometheus server set to `http://kube-prometheus-prometheus:9090/prometheus/metrics`

**What did you see instead? Under which circumstances?**

- Grafana datasource set to `http://kube-prometheus-prometheus:9090`
- Prometheus scrape target for prometheus server set to `http://kube-prometheus-prometheus:9090/metrics`

**Environment**

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1+coreos.0", GitCommit:"59359d9fdce74738ac9a672d2f31e9a346c5cece", GitTreeState:"clean", BuildDate:"2017-10-12T21:53:13Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

Bare metal cluster setup with Kubespray 2.3.0

**Workaround**

- Changed grafana data source config in grafana UI after deployment
- Changed prometheus ServiceMonitor manifest after deployment (added `path: /prometheus/metrics` to endpoint)

**Comment by brancz** [comment]
I highly recommend again prefixing Prometheus with a path. If you're doing this to request yourdomain.com/prometheus, I instead would recommend to rewrite the URL with your ingress. I'm saying this because we've gone through this and it's very painful, as there are a lot of things that behave totally different (Alertmanager as well for example) and it makes no sense for internal communication to have to be prefixed just because the external access requires it.

**Comment by champtar** [comment]
Hi @danielm0hr @brancz 

alertmanager is working out of the box:
```
alertmanager:
  routePrefix: /alertmanager/
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/rewrite-target: /
```

for prometheus, i did a small patch
```
diff --git a/helm/prometheus/templates/ingress.yaml b/helm/prometheus/templates/ingress.yaml
index 62b9830..7b830bd 100755
--- a/helm/prometheus/templates/ingress.yaml
+++ b/helm/prometheus/templates/ingress.yaml
@@ -21,7 +21,7 @@ spec:
     - host: "{{ .Values.ingress.fqdn }}"
       http:
         paths:
-          - path: "{{ .Values.routePrefix }}"
+          - path: "{{ .Values.ingress.path }}"
             backend:
               serviceName: {{ template "prometheus.fullname" . }}
               servicePort: 9090
```

and used this config
```
prometheus:
  externalUrl: /prometheus/
  ingress:
    enabled: true
    path: /prometheus
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/rewrite-target: /
```
(the goal is to leave default for routePrefix) 

and for grafana 2 patches:
```
diff --git a/helm/grafana/templates/grafana-deployment.yaml b/helm/grafana/templates/grafana-deployment.yaml
index 7c3fdd2..0c4c73a 100644
--- a/helm/grafana/templates/grafana-deployment.yaml
+++ b/helm/grafana/templates/grafana-deployment.yaml
@@ -23,6 +23,8 @@ spec:
       - name: grafana
         image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
         env:
+        - name: GF_SERVER_ROOT_URL
+          value: "%(protocol)s://%(domain)s:/grafana"
         - name: GF_AUTH_BASIC_ENABLED
           value: "true"
         - name: GF_AUTH_ANONYMOUS_ENABLED
diff --git a/helm/grafana/templates/ingress.yaml b/helm/grafana/templates/ingress.yaml
index f7eb50b..28bbf92 100644
--- a/helm/grafana/templates/ingress.yaml
+++ b/helm/grafana/templates/ingress.yaml
@@ -18,7 +18,7 @@ spec:
     - host: {{ .Values.ingress.fqdn }}
       http:
         paths:
-          - path: /
+          - path: "{{ .Values.routePrefix }}"
             backend:
               serviceName: {{ printf "%s-%s" $releaseName "grafana" | trunc 63 }}
               servicePort: 80
```

and this config:
```
grafana:
  routePrefix: /grafana/
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/rewrite-target: /
```

Hope this help
