### ISSUE TITLE
Cannot use matchExpressions syntax with Rules Selector in Prometheus Helm Chart

### ISSUE THREAD

**Issue by MihaiAnei** [coreos/prometheus-operator#914]
**What did you do?**
I deployed Prometheus using Helm.

**What did you expect to see?**
As with `serviceMonitorsSelector` I expected that the values from the Prometheus chart for `rulesSelector` can be written like this:
```
rulesSelector: {
  matchExpressions: [{key: prometheus, operator: In, values: [alertmanager, prometheus-inf]}]
}
```
This syntax only works for `serviceMonitorsSelector`.

The bug is [here](https://github.com/coreos/prometheus-operator/blob/master/helm/prometheus/templates/prometheus.yaml), line 68. Comparing it to line 59, the difference is clear. 

I need to specify that matchExpressions syntax works for both. Right now I edit the Prometheus resource in Kubernetes by hand in order to achieve the same results as with `serviceMonitorSelector`. 

If you need more details, please tell me.

**Comment by gianrubio** [comment]
@MihaiAnei pelase paste the values.yaml from your helm chart

**Comment by MihaiAnei** [comment]
My custom chart values:
```
rulesSelector: {
  matchExpressions: [{key: prometheus, operator: In, values: [alertmanager, prometheus-k8s, node-exporter]}]
}
serviceMonitorsSelector: {
  matchExpressions: [{key: prometheus, operator: In, values: [alertmanager, nginx-ingress-controller, prometheus-k8s, prometheus-inf, prometheus-operator, node-exporter]}]
}
```
Expected output (Prometheus custom resource yaml):
```
spec:
  serviceMonitorSelector:
    matchExpressions:
    - key: prometheus
      operator: In
      values:
      - alertmanager
      - nginx-ingress-controller
      - prometheus-k8s
      - prometheus-inf
      - prometheus-operator
      - node-exporter
  ruleSelector:
    matchExpressions:
    - key: prometheus
      operator: In
      values:
      - alertmanager
      - prometheus-k8s
      - node-exporter
```
Actual values:
```
  serviceMonitorSelector:
    matchExpressions:
    - key: prometheus
      operator: In
      values:
      - alertmanager
      - nginx-ingress-controller
      - prometheus-k8s
      - prometheus-inf
      - prometheus-operator
      - node-exporter
  ruleSelector:
    matchLabels:
      matchExpressions:
      - key: prometheus
        operator: In
        values:
        - alertmanager
        - prometheus-k8s
        - node-exporter
```
