### ISSUE TITLE
Helm grafana with ingress not work if service is on ClusterIP

### ISSUE THREAD

**Issue by sebglon** [coreos/prometheus-operator#918]
**What did you do?**
I want to use grafana helm with an ingress.
I have not specify service.type
And i have this error on my ingress:
`googleapi: Error 400: Invalid value for field 'namedPorts[0].port': '0'. Must be greater than or equal to 1, invalid`

**What did you expect to see?**
GCE ingress only support NodePort Service with Ingress.
Is it the case for all?
If it is the case, we can force service.type=NodePort if ingress.enabled=true

**What did you see instead? Under which circumstances?**

**Environment**

* Kubernetes version information:

kubernetes: 1.8
Provider GCE

**Comment by gianrubio** [comment]
@sebglon please paste the values.yaml

**Comment by sebglon** [comment]
```
grafana-paas:
    adminUser: "admin"
    adminPassword: "admin"
    auth:
        anonymous:
            enabled: false
    ingress:
        enabled: true
        annotations:
            kubernetes.io/ingress.global-static-ip-name: "grafana-customer"
            kubernetes.io/ingress.class: "gce"
            kubernetes.io/ingress.allow-http: "false"
            ingress.kubernetes.io/force-ssl-redirect: "true"
        fqdn: "my.site.com"

```
