### ISSUE TITLE
Helm Grafana - ingress fail with anonymous disabled 

### ISSUE THREAD

**Issue by sebglon** [coreos/prometheus-operator#934]
**What did you do?**
I want to use grafana behind ingress and without anonymous authentication.
```
grafana-paas:
    adminUser: "admin"
    adminPassword: "admin"
    auth:
        anonymous:
            enabled: false
    service:
        type: NodePort
    ingress:
        enabled: true
        annotations:
            kubernetes.io/ingress.global-static-ip-name: "grafana-customer"
            kubernetes.io/ingress.class: "gce"
            kubernetes.io/ingress.allow-http: "false"
            ingress.kubernetes.io/force-ssl-redirect: "true"
```

But ingress can set Up because backend health not manage HTTP 302.

show:
https://github.com/kubernetes/ingress-gce/issues/39
https://github.com/kubernetes/ingress-nginx/issues/582

To use ingress without anonymous auth, we can add readiness prod on deployment
https://github.com/kubernetes/ingress-nginx/blob/6ed6475e87588494dd29ba5d33bac167ae8acfdd/controllers/gce/examples/health_checks/health_check_app.yaml#L17

with path "/metrics" as described in: https://github.com/grafana/grafana/issues/3302
https://github.com/grafana/grafana/issues/3302
