### ISSUE TITLE
kube-prometheus chart update to >0.11 broke installation

### ISSUE THREAD

**Issue by simon-k8s** [coreos/prometheus-operator#969]
**What did you do?**

Sorry for having to open this issue again. But it still does not work for me. I am running the kube-prometheus helm chart version 0.0.10 which works fine. If i try and upgrade my installation to anything higher than 0.0.10 I get the following error from the kubelet exporter:

`
Get https://192.168.1.27:10250/metrics/cadvisor: x509: cannot validate certificate for 192.168.1.27 because it doesn't contain any IP SANs
`

**What did you expect to see?**

I expect to have a working installation after the upgrade

**What did you see instead? Under which circumstances?**

A broken kubelet exporter with no metrics

**Environment**

* Kubernetes version information:

`
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T21:12:46Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
`

Screen shot before the upgrade:

![prometheus](https://user-images.githubusercontent.com/29921946/35925089-1ef1efa8-0c25-11e8-9d90-c2a58c9e2433.png)

Screen shot after the upgrade:

![prometheus](https://user-images.githubusercontent.com/29921946/35924867-8ad3adb6-0c24-11e8-95e6-a4e893459157.png)

**Comment by gianrubio** [comment]
What command are using to upgrade kube-prometheus and to which version are you upgrading?

**Comment by simon-k8s** [comment]
@gianrubio I am using this command to run the upgrade:

`helm upgrade -f values.yaml kube-prometheus coreos/kube-prometheus
`

I can't upgrade to any version higher than 0.10 with out breaking the kubelet exporter with the pod metrics. The version 0.10 works without a problem. Previous versions also worked. 

`kube-prometheus    	1       	Wed Feb  7 16:23:40 2018	DEPLOYED	kube-prometheus-0.0.10    	monitoring`

I think it broke after this commit:

[#910](https://github.com/coreos/prometheus-operator/pull/910)

Would be great if we can fix this issue.

**Comment by antonikonovalov** [comment]
the same problem

**Comment by gianrubio** [comment]
The changes on #910 was already rolled back. Could you run the command again adding —dry-run —debug 
Please also paste your values.yaml

**Comment by simon-k8s** [comment]
This is the output from the dry run:

[helm_output.txt](https://github.com/coreos/prometheus-operator/files/1707449/helm_output.txt)

This is my values file:

[values.txt](https://github.com/coreos/prometheus-operator/files/1707452/values.txt)

**Comment by antonikonovalov** [comment]
not use values

just install 
```
helm install coreos/kube-prometheus --name kube-prometheus --set global.rbacEnable=true --namespace monitoring --debug
```
output log - https://gist.github.com/antonikonovalov/a0047598388ec7e27cdd1e54498fecb2

I use kube via docker for mac
<img width="1440" alt="screen shot 2018-02-08 at 17 56 50" src="https://user-images.githubusercontent.com/1614346/35979470-7bc52874-0cf9-11e8-9656-a8e31b86cbef.png">

**Comment by antonikonovalov** [comment]
I apply that
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    chart: "exporter-kubelets-0.2.1"
    component: kubelets
    heritage: "Tiller"
    release: "kube-prometheus"
    prometheus: kube-prometheus
  name: kube-prometheus-exporter-kubelets
spec:
  jobLabel: kube-prometheus-exporter-kubelets
  selector:
    matchLabels:
      k8s-app: kubelet
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: https-metrics
    scheme: https
    interval: 15s
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  - port: https-metrics
    scheme: https
    path: /metrics/cadvisor
    interval: 30s
    honorLabels: true
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
```

and now all is UP, but insecure :)
