### ISSUE TITLE
Custom Config File

### ISSUE THREAD

**Issue by pashok2398** [coreos/prometheus-operator#971]
**What did you do?**
cd contrib/kube-prometheus/
hack/cluster-monitoring/deploy

**What did you expect to see?**
Prometheus target: kubelet
https://KUBELET:10250/metrics/cadvisor UP

**What did you see instead? Under which circumstances?**
Prometheus target: kubelet
https://KUBELET:10250/metrics/cadvisor DOWN

server returned HTTP status 401 Unauthorized

**Environment**
Bluemix

* Kubernetes version information:

	insert output of `kubectl version` here
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.6-4+9c2a4c1ed1ee7e", GitCommit:"9c2a4c1ed1ee7e2e121203aa9a87315633a89eca", GitTreeState:"clean", BuildDate:"2018-01-22T08:23:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	insert how you created your cluster: kops, bootkube, tectonic-installer, etc.
Bluemix

* Manifests:

```
insert manifests relevant to the issue
```

* Prometheus Operator Logs:

```
insert Prometheus Operator logs relevant to the issue here
```
I wanted to replace/add configuration to the prometheus.yaml file:
```
relabel_configs:
- action: labelmap
  regex: __meta_kubernetes_node_label_(.+)
- target_label: __address__
  replacement: kubernetes.default.svc.cluster.local:443
- target_label: __scheme__
  replacement: https
- source_labels: [__meta_kubernetes_node_name]
  regex: (.+)
  target_label: __metrics_path__
  replacement: /api/v1/nodes/${1}/proxy/metrics
```
based on this solution: https://github.com/prometheus/prometheus/issues/2606#issuecomment-294869099 and tried to change the secret (prometheus-k8s) however getting it always rewrites.
How can i implement a custom config.file
