### ISSUE TITLE
Validation over deprecated fields?

### ISSUE THREAD

**Issue by Quentin-M** [coreos/prometheus-operator#992]
**What did you do?**

Using `quay.io/coreos/prometheus-operator:v0.17.0`, the following used to work.

```
  storage:
    volumeClaimTemplate:
      metadata:
        name: prometheus-storage
        namespace: kube-system
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .prometheus.volumeSize }}Gi
```

**What did you expect to see?**

```
validation failure list:
  spec.storage.class in body is required
  spec.storage.selector in body is required
  spec.storage.resources in body is required
```
But those fields are showed as deprecated? Why would I have to specify them?

Sorry for the brief issue, can add more information as needed. Just wanted to throw this out there ASAP.
