### ISSUE TITLE
Change the Local Retention from 24 hours to custom  

### ISSUE THREAD

**Issue by hamid2013** [coreos/prometheus-operator#999]
**What did you do?**
```
I have checked the prometheus process, and it is running with the local retention of 24 Hours. 
```

**What did you expect to see?**
```
Can we able to change that to custom Hours and save the data to the persistent storage.
``` 

**Environment** 
```
Test and Prod
```

* Kubernetes version information:

	Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T02:00:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

	Cluster Created: Azure ACS using acs-engine

**Comment by mbenabda** [comment]
have you used the helm chart to install the operator ? 
in that case
```
helm install coreos/kube-prometheus \
         --name kube-prometheus \
         --set prometheus.retention=48h
```
otherwise:
in your ```Prometheus``` object's ```spec``` field:
```yaml
...
kind: Prometheus
spec:
   retention: "48h"
   ...
```
if you did that already and it didn't work: tell us your prometheus-operator version & dump your Prometheus object's yaml in here

**Comment by hamid2013** [comment]
Thanks @mbenabda 

I have made that work. But is it possible to store the data in the persistent storage.

**Comment by mbenabda** [comment]
yes: see PrometheusSpec.storage.
eg:
```yaml
...
kind: Prometheus
spec:
  retention: "48h"
  ...
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
```
